### ISSUE TITLE
Tilesource file types save very different data than Editor 1

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#100]
Editor 2 open and save:

![screen shot 2016-09-16 at 16 18 52](https://cloud.githubusercontent.com/assets/65613/18589141/a0f2569c-7c29-11e6-828a-0ecbae834044.png)

![screen shot 2016-09-16 at 16 20 26](https://cloud.githubusercontent.com/assets/65613/18589144/a781ac9c-7c29-11e6-8877-c18d2f57496d.png)

Editor 1 open and save:

![screen shot 2016-09-16 at 16 20 33](https://cloud.githubusercontent.com/assets/65613/18589158/ba094d70-7c29-11e6-86e0-e6ef9540e3a9.png)

**Comment by sicher** [comment]
[ice.tilesource.txt](https://github.com/defold/editor2-issues/files/479407/ice.tilesource.txt)

**Comment by sicher** [comment]
![tileset_ice64](https://cloud.githubusercontent.com/assets/65613/18624935/6be8153a-7e4b-11e6-9f67-b14af7517e48.png)

**Comment by erikangelin-king** [comment]
DEFEDIT-431
