### ISSUE TITLE
Can't open project in second instance of editor v.2 [DEFEDIT-1027]

### ISSUE THREAD

**Issue by Dragosha** [defold/editor2-issues#1000]
### Steps to reproduce
1. open editor
2. open the project within in
3. open second instance of editor. (for study other project in parallel). all ok
4. try to open other project in instance 2.
5. second editor is closing.

p.s. in previous version (a week ago) of editor second instance worked fine.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>8bdb83b693362a29e11dbb1af9826863771b0a35</td></tr>
<tr><td>Build time</td><td>2017-06-13T12:25:22.541733</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged, please try it out and reopen if there are any problems!

**Comment by Dragosha** [comment]
seems to work fine. thanks!
