### ISSUE TITLE
Gui Spine lost spine scene reference when moving node in hierarchy.

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1015]
### Expected behaviour
Spine scene should remain what it was set

### Actual behaviour
The spine scene field becomes blank

Note: This node was originally copied from a different gui.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>6cc25e87754f6c42979bae89277fd849b741818a</td></tr>
<tr><td>Build time</td><td>2017-06-19T14:34:05.488692</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
This should be fixed with defold/defold#1641!
