### ISSUE TITLE
Error clicking in the Curve Editor view

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#1017]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>bcdadad53a0fe292524c57689eac6e49d735a351</td></tr>
<tr><td>Build time</td><td>2017-06-21T16:55:53.386434</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=333a5052f3b549a08db973951c3f5594'>333a5052f3b549a08db973951c3f5594</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can't repro, error info gone :(
