### ISSUE TITLE
Crash when clicking Build

### ISSUE THREAD

**Issue by SanchoBlaze** [defold/editor2-issues#1019]
### Expected behaviour
Build the project
### Actual behaviour
Crashed
java.lang.UnsatisfiedLinkError: Can't obtain static method fromNative(Method, Object) from class com.sun.jna.Native
### Steps to reproduce
Click Build (Getting Started Tutorial)
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>86632bf7cdeb8d9833baff3864fe480c1162f8da</td></tr>
<tr><td>Build time</td><td>2017-06-22T10:48:42.692440</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2d0b7c7115954d779f699cc413121fd4'>2d0b7c7115954d779f699cc413121fd4</a></td></tr>
<table>

**Comment by matgis-king** [comment]
Internal Note: Possibly something like this going on here?
https://stackoverflow.com/questions/21679004/jna-unsatisfiedlinkerror-works-when-i-set-java-library-path-to-a-bogus-value

**Comment by SanchoBlaze** [comment]
I do have an older version of java (v7) installed.

**Comment by matgis-king** [comment]
Thanks! I suspect there could be a conflicting JNA installation on your machine that we're loading by mistake. We might need to supply a flag to our bundled Java Runtime. Could you try to edit the `config` file next to `Defold.exe` and insert `-Djna.nosys=true,` at the front of the `vmargs` setting so it looks like this?
```
vmargs = -Djna.nosys=true,-Ddefold.resourcespath=${bootstrap.resourcespath},...
```
Depending on where you put your Defold folder, Windows might fight you on this. I had to copy the `config` file onto my desktop to be able to edit it, then copy it back after making the change, overwriting the old one.

If this solves your issue, we can try including the `jna.nosys` flag in future builds of the editor.

**Comment by SanchoBlaze** [comment]
Yep, that fixed it. Thanks :)

**Comment by matgis-king** [comment]
Thank you! We'll add the flag to future builds!
