### ISSUE TITLE
copy paste trees with gui elements does not result in correct texture reference for child elements

### ISSUE THREAD

**Issue by dodspunkare** [defold/editor2-issues#1026]
While in .gui:

### Expected behaviour
I have a tree of boxes with texture "gui/the_most_awesome_texture" set for child boxes.

When I copy and paste this tree of boxes the child boxes still have texture set to "gui/the_most_awesome_texture".

### Actual behaviour
In GUI i have a tree of boxes with texture "gui/the_most_awesome_texture" set for child boxes.

When I copy and paste this tree of boxes the **_child_** boxes have texture set to "/the_most_awesome_texture". Which does not exist.

### Steps to reproduce
Element with children with assigned textures. Copy paste. Cry.

I'm now forced to manually set the correct texture for all children in the tree.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>86632bf7cdeb8d9833baff3864fe480c1162f8da</td></tr>
<tr><td>Build time</td><td>2017-06-22T10:48:42.692440</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
This should be fixed with defold/defold#1641!
