### ISSUE TITLE
Alt + up/down to move nodes in .gui activates and sets focus on File menu.

### ISSUE THREAD

**Issue by dodspunkare** [defold/editor2-issues#1028]
### Expected behaviour

Alt + up/down to move around nodes in .gui w/o issue.

### Actual behaviour

Alt-key sets focus on top menu so trying tro Alt + down will pull down File menu tab and hence only allow one step and then the focus is all on the file menu. Alt + up works as long as you don't use Alt + down.

### Steps to reproduce

Use Alt+up/down.

However I'd like to throwback to this https://github.com/defold/editor2-issues/issues/448 and press for the feature of being able to use drag and drop to change order of nodes.

And being of the subject I'm going to point out something that's probably not worth its own issue report and that is that the Alt + up/down does not work for the fonts-folder in .gui. To see my fonts in random order under .gui is too painful to describe in words.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>86632bf7cdeb8d9833baff3864fe480c1162f8da</td></tr>
<tr><td>Build time</td><td>2017-06-22T10:48:42.692440</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
With defold/defold#1662 the Alt key will no longer move focus to the menu bar, since it is used in Defold for shortcuts and viewport interactions.
