### ISSUE TITLE
Model animations don't support dae files

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1029]
### Expected behaviour
In editor 1, placing a dae file in a models animation field will make that be the animation, referenced by the name of the file as the animation name.

### Actual behaviour
You can put a dae file there in the editor, but the animation won't be accessible at runtime through the name of the file. Animation sets works though.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>86632bf7cdeb8d9833baff3864fe480c1162f8da</td></tr>
<tr><td>Build time</td><td>2017-06-22T10:48:42.692440</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by andreas-strangequest** [comment]
Stumbled upon this as well. Animation sets are sometimes a big hassle for artists (creating a file for each animation) and therefor we've created our own animation system from one single dae (the original) to get rid of the need for animation sets.

**Comment by Malmer** [comment]
@andreas-strangequest Yes, going forward it would be sweet if an animation set could also define a time/frame range in the file and give it a custom name, so that you could have many animations in the same file, but just different parts of it.

**Comment by RagnarSvenssonKing** [comment]
Fixed!

**Comment by Malmer** [comment]
❤️
