### ISSUE TITLE
Unable to Fetch Libraries from GitHub

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#103]
### Expected behaviour
When I have a dependency to a GitHub repo release (ZIP) containing a Defold project I expect to be able to fetch it just as I was able to do so with the old editor

### Actual behaviour
Now the editor flashes red and my dependency is not included

### Steps to reproduce
Add a dependency to a GitHub repo (https://github.com/britzl/defads/archive/master.zip) and do Fetch Libraries

<hr/>
Defold version: 1.2.88
Defold sha: fae5e61b4d76818de0e7d2c8a395dd372704e060
Platform: Mac OS X 10.10.5 (x86_64)
Java version: 1.8.0_45-b14

**Comment by RagnarSvenssonKing** [comment]
Required by internal King teams
