### ISSUE TITLE
Incorrect syntax highlighting for multi-line Lua strings

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#1032]
Currently we do not treat the `[[...]]` string literal syntax correctly when editing a Lua file. It should be highlighted as regular strings in the code editor.

From the spec:
> We can delimit literal strings also by matching double square brackets `[[...]]`. Literals in this bracketed form may run for several lines, may nest, and do not interpret escape sequences.

![lua-multi-line-string-highlight](https://user-images.githubusercontent.com/22448941/27578986-382936c6-5b26-11e7-8d45-06bd658fd3c8.png)

**Comment by erikangelin-king** [comment]
Fixed in new code editor
