### ISSUE TITLE
#extension directive in shaders fail due to stuff inserted in top of shaders at build time [DEFEDIT-1126]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1033]
Description:
Adding #extension directive like:
`#extension GL_EXT_shader_framebuffer_fetch : require`

On top of a shader will give the following error message:

`WARNING:GRAPHICS: ERROR: 0:9: '' : syntax error: #extension must always be before any non-preprocessor tokens`

This is caused by Defold inserting things at the top of the shader when building.
Defold should insert these declarations after any initial # lines in the file.

See: DEF-2793

**Comment by matgis-king** [comment]
A fix was merged on 2017-09-12.
