### ISSUE TITLE
Editor 2 mac os x grid axis render bug

### ISSUE THREAD

**Issue by nemish** [defold/editor2-issues#1034]
Hello! I have some not very beautiful bug. It doesn't block development but it is a little annoying. Please, look at gif in [post on the forum](https://forum.defold.com/t/editor-2-mac-os-x-grid-axis-render-bug/9482) (didn't find how to attach file here). Thanks!

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>86632bf7cdeb8d9833baff3864fe480c1162f8da</td></tr>
<tr><td>Build time</td><td>2017-06-22T10:48:42.692440</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Thanks for reporting! What hardware do you use? Did this start happening recently or always? Does it look the same when you have multiple tabs open? Does it look the same for all content which is shown in the scene view? (there are three types of views; text view, form view, and scene view).

**Comment by nemish** [comment]
I use laptop with this configuration:
MacBook Pro (Retina, 13-inch, Late 2013).
Proc. 2,4 GHz Intel Core i5
Intel Iris 1536 Mb

It started happening since I installed Defold Editor 2, by other words - always. On the old Defold everything looks ok. Sorry, but I don't know how to check it in the text or form views. In the scene view it looks the same for all objects which I'm editing (collection, go, atlas etc.) and doesn't matter how many tabs currently opened.

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/editor-2-mac-os-x-grid-axis-render-bug/9482/3

**Comment by RagnarSvenssonKing** [comment]
I have pushed a fix that could potentially solve this issue. Would you mind trying again?

**Comment by RagnarSvenssonKing** [comment]
I will close this issue for now, assuming it is fixed. Please submit a new issue in case it happens again (re-submitting will give us more valuable info about your GPUs).

**Comment by nemish** [comment]
Thanks, it works like a charm!
