### ISSUE TITLE
Defold 2.0 no longer prioritized (keypresses denied)

### ISSUE THREAD

**Issue by GamingBud** [defold/editor2-issues#1038]
On rare occasions, (possibly) after alt-tabbing back into the Defold window, any key I press will respond with the Windows 7 "incorrect key" ding. Which basically means that Defold wasn't typing out my key presses when I tried to write.

I've been told that this is possibly the result of the "Update" window taking priority behind the scenes. At the time, it certainly wasn't obvious. I'll report back if I find that it happens again with no "update" window.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>d557479bcc8b59d8808f16a314a37adbbb2ab078</td></tr>
<tr><td>Build time</td><td>2017-06-27T15:58:04.890636</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/editor-2-invalid-characters/9465
