### ISSUE TITLE
Error while programming a go

### ISSUE THREAD

**Issue by Reinoldo** [defold/editor2-issues#1040]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>411f4cf5926fbe89c0893efc16acf48b982d1ae6</td></tr>
<tr><td>Build time</td><td>2017-06-29T17:47:39.795052</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=cbbd590b5c284432bb6ee5031db38840'>cbbd590b5c284432bb6ee5031db38840</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Hi, do you remember what this error was? Was it a NullPointerException perhaps? For some reason the tool we use to collect the stack traces (sentry.io) has lost the stack trace for this error, so I can't tell what it was.

**Comment by erikangelin-king** [comment]
Please reopen if it happens again.
