### ISSUE TITLE
Exception when try to find places where use deleted gui component

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1046]
### Expected behaviour
Show me collections that use deleted node
### Actual behaviour
exception
### Steps to reproduce
1. Create gui component
2. Add gui component to some collection
3. Remove node
4. Build project
5. Try to double click to the build error message
![2017-07-01_20-50-33](https://user-images.githubusercontent.com/2209596/27764307-f11e8034-5e9e-11e7-8f18-2f8c30e6eb8c.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>2b46a7e2dcee415d080f7d275d113890f017c965</td></tr>
<tr><td>Build time</td><td>2017-06-30T18:08:14.612210</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=ddc9074ebb2f4fb89905789c8556f617'>ddc9074ebb2f4fb89905789c8556f617</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
