### ISSUE TITLE
Bug with window of recent projects

### ISSUE THREAD

**Issue by wyrmling** [defold/editor2-issues#1047]
Same project appears twice:
![7ojrhbvxtveocni0igrboq](https://user-images.githubusercontent.com/13387159/27769234-5734f3d2-5f2e-11e7-98d6-2f9d20e5ce64.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>2b46a7e2dcee415d080f7d275d113890f017c965</td></tr>
<tr><td>Build time</td><td>2017-06-30T18:08:14.612210</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by AGulev** [comment]
Duplicate https://github.com/defold/editor2-issues/issues/157

**Comment by AGulev** [comment]
Can't reproduce in 1.2.144.
I can't reproduce this issue in 1.2.144. Feel free to reopen in case it is still an issue.
