### ISSUE TITLE
Add possibility to remove items from window of recent projects

### ISSUE THREAD

**Issue by wyrmling** [defold/editor2-issues#1048]
Would be great to have an option to delete items from the list of recent projects, f.e.:

![screenshot_2](https://user-images.githubusercontent.com/13387159/27769270-14942a6a-5f2f-11e7-866e-42d3189b481e.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>2b46a7e2dcee415d080f7d275d113890f017c965</td></tr>
<tr><td>Build time</td><td>2017-06-30T18:08:14.612210</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by tadaaagames** [comment]
I second this suggestion. Definitely needed after a while

**Comment by vlaaad** [comment]
Implemented, check for updates!
