### ISSUE TITLE
Spine model don't shows in HTML5 [DEFEDIT-1167]

### ISSUE THREAD

**Issue by Dragosha** [defold/editor2-issues#1049]
### Expected behaviour
All ok in dmengine build, but do not show in HTML5:
https://www.youtube.com/watch?v=SyZoKClrrYs
![2017-07-02_17-12-24](https://user-images.githubusercontent.com/842807/27769724-be0ee048-5f49-11e7-951a-f999ed54b452.png)

UPD:
the same problem in win32 bundle. 
But only with this spine model. I try to add other model and it works fine in htlm5.
![2017-07-02_18-02-33](https://user-images.githubusercontent.com/842807/27770018-0983870c-5f51-11e7-835b-d9792b02b578.png)

So, I can send spine model for tests.

Both model exported with latest Spine 3.6.36.

### Steps to reproduce

may be the similar issue: https://github.com/defold/editor2-issues/issues/714
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>2b46a7e2dcee415d080f7d275d113890f017c965</td></tr>
<tr><td>Build time</td><td>2017-06-30T18:08:14.612210</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Dragosha** [comment]
just made the new spine model and got the same issue
![2017-07-05_16-16-12](https://user-images.githubusercontent.com/842807/27862223-ac6550e2-619d-11e7-9ac7-8aa31c88dd21.png)

**Comment by Dragosha** [comment]
upd:
if build with editor v.1 (Version 1.2.107) model do not shows in dmengine too.

**Comment by Dragosha** [comment]
Spine model with Mouse for tests:
[hero.zip](https://github.com/defold/editor2-issues/files/1127094/hero.zip)
contains:
-images
-json
-spine project (3.6.36)
-defold stuff

**Comment by Dragosha** [comment]
SOLVED:
https://forum.defold.com/t/does-anybody-have-problem-with-spine-model/9657/3?u=dragosha

> seems what i solved the problem. ::facepalm.jpg::
> In second editor there is properties "skin" with "default" value. But model have no this skin. If we choose that skin when create spinemodel - we have a problem. And editor v.2. doesn't shows any error.
> I just opened the project in first editor and got error tips in spinemodel properties. Remove "default" skin and voila, all works fine.

All what we need is the tips with error message like this:
![2017-07-06_13-56-18](https://user-images.githubusercontent.com/842807/27903592-4cedf0ae-6253-11e7-87ab-f9c30abd0f82.png)

**Comment by matgis-king** [comment]
The error will now show up in editor 2 as well.
