### ISSUE TITLE
504 Gateway Time-out when trying to build extension-html5 

### ISSUE THREAD

**Issue by the1schwartz** [defold/editor2-issues#1050]
### Expected behaviour
Should build to HTML5

### Actual behaviour
Build fails and gives the following output:

Build server output: <html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

### Steps to reproduce
Download project here: https://github.com/defold/extension-html5
Try to build to HTML5

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>2b46a7e2dcee415d080f7d275d113890f017c965</td></tr>
<tr><td>Build time</td><td>2017-06-30T18:08:14.612210</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by mathiaswking** [comment]
We had a low timeout value on the build server, which we've increased significantly.
Cannot reproduce this error since that fix. (Also [confirmed by user](https://forum.defold.com/t/unable-to-build-for-html5-when-html5-native-extension-is-included-def-2815/9662/5?u=mathias_westerdahl))
