### ISSUE TITLE
Build doesn't work

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1052]
Build with my DefUnityAds plugin doesn't work after editor update, but I didn't make any changes in plugin. (any platform or Cmd+B)
Error:
![2017-07-05_15-25-23](https://user-images.githubusercontent.com/2209596/27864233-6301e44e-6196-11e7-8ac1-bdf9e43db48f.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>8c2083883fdf321a3fa2aa1a1a5d319a82635c10</td></tr>
<tr><td>Build time</td><td>2017-07-05T12:49:45.608192</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by mathiaswking** [comment]
The build server has been updated and restarted. Please try again!
Sorry for the inconvenience!

**Comment by AGulev** [comment]
fixed
