### ISSUE TITLE
Intel Grafic error when open a GO [DEFEDIT-929]

### ISSUE THREAD

**Issue by getJv** [defold/editor2-issues#1053]
### Expected behaviour
See the GO properties and Outline
### Actual behaviour
Intel Grafic error when open a GO
### Steps to reproduce
Double click on a GO component

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>6a36f46bbd1180851909b2f15171d22b502dd38e</td></tr>
<tr><td>Build time</td><td>2017-07-08T00:43:25.979550</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6a303d3b623545f5a5f6cc206e6f5498'>6a303d3b623545f5a5f6cc206e6f5498</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
I have pushed a fix which could potentially solve this error. Could you please try? (Wait for the app to ask you to update it.)

**Comment by RagnarSvenssonKing** [comment]
I will close this issue for now, assuming it is fixed. Please submit a new issue in case it happens again (re-submitting will give us more valuable info about your GPUs).
