### ISSUE TITLE
render texture needs to have an in engine object

### ISSUE THREAD

**Issue by needsnaming** [defold/editor2-issues#1056]
It would be nice to have a render target object in the engine. 
An object that does it own render, and maybe has its own render script.
When it renders it would just render to its own texture. 
And you would be able to place the render object like any other game object.

I have spent 3 weeks trying to make one render texture work as hoped. 
I need to mask part of a game object from rendering, I will be doing some parallax objects on it.
But that object will be in the center of the screen. and the parallax objects should not bleed into the rest of the scene. 
there is no resource or material that I have seen that fully covers what needs to be done.
I have tried to piece it together from half pieces of code in the forums.
It has not gone well. 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>6a36f46bbd1180851909b2f15171d22b502dd38e</td></tr>
<tr><td>Build time</td><td>2017-07-08T00:43:25.979550</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Sorry to hear you haven't been able to achieve what you intended to do. Reading the desc, it's hard to understand what the underlying problems are. Would it be possible for you to supply any visuals of what you are trying to achieve?

**Comment by needsnaming** [comment]
I think I'm just being dumb. Using a render target might have been the wrong approach. 

I want to mask a game object. I guess I should try using the render target. But the short of what I was trying to do was to mask parallax scrolling game objects within a given screen area. 

excuse my developer art:
![1-toy-dinosaur](https://user-images.githubusercontent.com/1650079/28101857-7e49d81e-6688-11e7-941d-faa5018636f5.png)

The slot machine thing needs to have parallax above and below it for the reels to scroll into view for the correct effect. It would look like below without a mask. It is possible to easily mask gui items, there isn't an easy way to mask game objects. So maybe we just need an easy way to mask game objects in the game scene?

![this](https://user-images.githubusercontent.com/1650079/28101954-28f7602e-6689-11e7-84c3-77628d7c87c4.png)

**Comment by needsnaming** [comment]
I got it working with the stencil buffer. 
I just chose the wrong path to get what I needed done.
derp.

**Comment by RagnarSvenssonKing** [comment]
Cool! There are many different ways to achieve clipping in your case above (it seems even alpha-blending could work? Maybe the real case in your game is different.). There are many discussions about it in the forums, this is an example: https://forum.defold.com/t/making-a-flashlight/286/4

I will close this issue for now, please file a new issue if something is missing on the engine side to do what you want.
