### ISSUE TITLE
Editor 2 suggests me remove [input] section

### ISSUE THREAD

**Issue by GerodruS** [defold/editor2-issues#1059]
When I open game.settings file in Editor 2, there is a reset button near to [input] section.
If I press the button, the section will be removed from file.
It will the cause of crash of iOS build when it start.

**Comment by RagnarSvenssonKing** [comment]
I'm tracing this error right now. When you reset that field it goes back to the default: "/input/game.input_binding". Could it be that you have no /input/game.input_binding file in your project? I.e. it is not a problem specific to iOS, but that it doesn't tell you that the file is missing as a build error before trying to launch the engine? Otherwise I'm having troubles reproducing.

**Comment by GerodruS** [comment]
First part I've reproduced this right now: Win 10, Editor 2, v1.2.109
1. Open project. 
2. Open game.project in notepad++ - [input] section was here.
3. Open game.project in defold editor.
4. Click to reset button near to Game Binding section.
5. Switch back to notepad++, reload file - [input] section has disappeared.

**Comment by RagnarSvenssonKing** [comment]
It is actually meant to disappear, as the field value goes back to the default which does not need to be explicitly specified. The problem is if it causes a crash. Is the crash still there?

**Comment by GerodruS** [comment]
Oh, I got it, sorry for not full information: on mac I've created a build using an Editor 1.

**Comment by RagnarSvenssonKing** [comment]
Sorry, but just to clarify: does it crash on any platform when using Editor 2?

**Comment by GerodruS** [comment]
I've tested this only on iOS device. I will try another platform.
I've reproduced this again with the project: https://github.com/GerodruS/Defold-Tests
If there is no [input] section - crash

**Comment by GerodruS** [comment]
I've tried build for macOS and It does not start without [input] section too.

**Comment by RagnarSvenssonKing** [comment]
Ok great, thanks for the help! I'll look into it.

**Comment by britzl** [comment]
The default value when reset is no longer an empty string but an actual file path: /input/game.input_binding
