### ISSUE TITLE
Error after clicking on message in console

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#1060]
### Expected behaviour
See place where present error
### Actual behaviour
clojure.lang.ExceptionInfo: No resource node found for resource 'null'
### Steps to reproduce
Click on here
![image](https://user-images.githubusercontent.com/588556/28073440-55308268-665e-11e7-8234-cc0d76138556.png)

I rename animation name in TileSource. It animation was connect to the sprite. After click on message I receive error.
<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Build time</td><td>2017-07-11T15:59:44.823918</td></tr>
<tr><td>GPU</td><td>GeForce GT 440/PCIe/SSE2</td></tr>
<tr><td>Defold sha</td><td>1eba32545b54335c582adbc73fcca5e431bc06e2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 375.95</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d751f7f2681d4e2e8c9c70e7cc97a518'>d751f7f2681d4e2e8c9c70e7cc97a518</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
