### ISSUE TITLE
Null pointer exception

### ISSUE THREAD

**Issue by colmsjo** [defold/editor2-issues#1062]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Build time</td><td>2017-07-11T19:16:55.263326</td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 3000 OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>c715295e4f540bf117a44fa06c138765b632e93b</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.2.36</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c8158ce3fc1243cc96b2dddf0ec26241'>c8158ce3fc1243cc96b2dddf0ec26241</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
