### ISSUE TITLE
java.lang.NullPointerException: Unknown, when build the project

### ISSUE THREAD

**Issue by getJv** [defold/editor2-issues#1063]
### Expected behaviour

We were implementing the pause game function... so we had add a pause.gui in our controller.collection.
after build the game we received a "java.lang.NullPointerException: Unknown"

IF you need any other information, please feel free to ask. bye
### Actual behaviour
Received a "java.lang.NullPointerException: Unknown" when build the project

### Steps to reproduce
1 - Open our project,
2 - Build (ctrl+B)
3 - get a pretty and crazy:  "java.lang.NullPointerException: Unknown"

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.108</td></tr>
<tr><td>Defold sha</td><td>e856d1d8b44f6651fc0746b6db1afe726402e0d9</td></tr>
<tr><td>Build time</td><td>2017-07-10T14:58:17.123329</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=1f8f6eec0939452fafc8f46933bf9458'>1f8f6eec0939452fafc8f46933bf9458</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Are you able to reproduce the error? If so, would you mind restarting the editor, reproducing the error and reporting again? When the app has been running for a while, stack traces are removed as a part of JVM optimizations, which makes it harder to trace the errors.

**Comment by getJv** [comment]
Yes, i'm able. But i'm not in home now. when i get home i will send this information to you (20h:00 in BRL timezone). See you!

**Comment by getJv** [comment]
Hey Sven, here is the error, just after the first defold execution. If you need more information or another action, please let me know. See you!


![defolderror](https://user-images.githubusercontent.com/2864961/28142581-e98a0a22-6737-11e7-8b88-9e5632cf47e9.png)

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Build time</td><td>2017-07-11T19:16:55.263326</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>Defold sha</td><td>c715295e4f540bf117a44fa06c138765b632e93b</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 9.17.10.2963</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=58226851a1eb489d8fcd0bb79016de1c'>58226851a1eb489d8fcd0bb79016de1c</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Excellent, thank you!

**Comment by RagnarSvenssonKing** [comment]
Fixed!

**Comment by getJv** [comment]
?? What i need to to now sven?may I  update my defold?

**Comment by RagnarSvenssonKing** [comment]
It should bring up a dialog that asks you to upgrade to the latest version. The dialog appears after the new package has been downloaded so it might take a while after you have started the app.

**Comment by getJv** [comment]
Nice sven. Really thanks. Defold team are amazing. See you on defold forum.

**Comment by RagnarSvenssonKing** [comment]
Did it work for you? By the way, my name is Ragnar, Sven is another member of the team. ;)

**Comment by getJv** [comment]
oh man? RagnarSven... and Sven are two different persons. haha i would never figure out this for my self, hahaha.

I did a new checkout (import) in another path, and now it is working again.

Thanks for your help Mr. Ragnar! :D
