### ISSUE TITLE
deleting object does not seem to delete the entry from the outline list.

### ISSUE THREAD

**Issue by needsnaming** [defold/editor2-issues#1066]
### Expected behaviour
Deleting object from the outline window will remove that object from the outline window.

### Actual behaviour
The object remains in the outline window. 

![capture6](https://user-images.githubusercontent.com/1650079/28105825-7eef8d3e-669e-11e7-9734-909f5ca3ab7d.PNG)

### Steps to reproduce
delete an object from the outline window. 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Defold sha</td><td>c715295e4f540bf117a44fa06c138765b632e93b</td></tr>
<tr><td>Build time</td><td>2017-07-11T19:16:55.263326</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4542</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Were you trying to delete the "AttackFactory" in the screenshot? Did anything else happen? Would you mind checking the log file to see if anything went bad? (Help > Show Logs)

**Comment by GerodruS** [comment]
I have the issue too in editors for Mac and Win.
There is no errors or warnings at the moment of deleting.
[editor2.2017-07-12 copy.log.txt](https://github.com/defold/editor2-issues/files/1141234/editor2.2017-07-12.copy.log.txt)

**Comment by needsnaming** [comment]
Yes that is an image after I delete the item.

I do not see anything in my logs with a time stamp correlating to when I delete the item.
If I add a sprite and set it to an image, the sprite remains in the scene after deleting it. 
It gets removed when I add a new sprite to the object. 

Unsure if this behavior started after todays update. I have not been able to play much in defold the last week due to my day job. 

steps I take:
add component
[optionally set component values]
delete component
[component remains in scene graph and outline window]
add component
[delete component is removed and replaced by the new component]

**Comment by RagnarSvenssonKing** [comment]
Thanks, I was able to reproduce as well. I believe this is a quite recent regression, sorry about that! Will look into it immediately.

**Comment by RagnarSvenssonKing** [comment]
Fixed and pushed, update coming shortly.
