### ISSUE TITLE
The "about" box contains non selectable text

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#107]
### Expected behaviour

I want to be able to select the SHA in the about box

### Actual behaviour

The goddamn about box won't let me

### Steps to reproduce

1. Select "About" in the Help menu.
2. Try to select any text in the pop up box.

<hr/>
Defold version: 1.2.88
Defold sha: dd99233cf72a65c1b0a1f09c679669cdac73a135
Platform: Mac OS X 10.11.6 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Fixed
