### ISSUE TITLE
Defold 2 cannot reload my project

### ISSUE THREAD

**Issue by jsapar** [defold/editor2-issues#1070]
### Expected behaviour
Run the game.

### Steps to reproduce
After clicking save all and attempting to exit Defold Editor 2, I am prompted that unsaved changed exist. After closing Defold, reopening it, and attempting to build my project, I get this error: 

### Actual behaviour

java.io.IOException: Cannot run program "C:\Users\AppData\Local\Defold\unpack\4e3debe8e925c1baee32e13d8716b7c7ae21a45c\x86_64-win32\bin\dmengine.exe" (in directory "C:\Users\Defold Projects\War Battles"): CreateProcess error=2, The system cannot find the file specified
java.io.IOException: CreateProcess error=2, The system cannot find the file specified

<hr/>

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Build time</td><td>2017-07-13T13:24:50.073465</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>Defold sha</td><td>4e3debe8e925c1baee32e13d8716b7c7ae21a45c</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4542</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=7319d50b9b314987a53be86638a58063'>7319d50b9b314987a53be86638a58063</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
The incorrectly appearing dialog will be fixed soon. The missing engine binary is a big problem though. Did you check on the file system if the file was there? Is there any risk antivirus could have snatched it?

**Comment by jsapar** [comment]
@RagnarSvenssonKing it seems as though the file it was looking for was there. I temporarily fixed the problem by booting up Defold through file explorer rather than with the shortcut I created. However, after I came back to my computer after some time the same problem arose.

**Comment by RagnarSvenssonKing** [comment]
Alright, that is really strange. I will mark this as "serious" for now. If this problem keeps happening and gets on your nerves, don't hesitate to comment and it will be raised to blocker.

**Comment by erikangelin-king** [comment]
@jsapar Is this still happening?

**Comment by erikangelin-king** [comment]
Closing, please reopen if it happens again!
