### ISSUE TITLE
Sometimes editor remove Collection properties 

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1074]
### Expected behaviour
Editor shouldn't delete properties by itself

### Actual behaviour
Sometimes Editor remove my properties from 2 my collection
![2017-07-21_12-28-34](https://user-images.githubusercontent.com/2209596/28457894-7695862e-6e10-11e7-9253-bd5697bfd856.png)

### Steps to reproduce
1. edit something in game.project
2. cmd+S for saving changes
3. sometimes (not stable reproduced)  editor remove properties from 2 my collection (it's all time the same property and same collections)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.109</td></tr>
<tr><td>Defold sha</td><td>cc5030bb38e30bdbcb423f510247c9e180cb580c</td></tr>
<tr><td>Build time</td><td>2017-07-18T18:27:15.898712</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
