### ISSUE TITLE
Defold Editor 2.0 Not responding 

### ISSUE THREAD

**Issue by wajahatali5** [defold/editor2-issues#1076]
When I am going to add a collection in Main collection, Editor stuck their and showing loader only, I wait enough time for loading but when I clicked on editor, it error me NOT RESPONDING.

**Comment by RagnarSvenssonKing** [comment]
Are you perhaps adding the same collection? We have a known issue for this. If not, could you please describe in more detail the steps you are taking for it to hang?

**Comment by erikangelin-king** [comment]
Please reopen if it was some other error than the infinite recursion described above.
