### ISSUE TITLE
Empty "Import project from defold.com" list 

### ISSUE THREAD

**Issue by abadonna** [defold/editor2-issues#1078]
while trying to open project from dashboard

**Comment by Dragosha** [comment]
May be related with account sign in.  When I pressed "next" button - nothing happening.
![2017-07-25_14-08-46](https://user-images.githubusercontent.com/842807/28564592-e5ceacb6-7142-11e7-9043-b48494380de9.png)

**Comment by andreas-strangequest** [comment]
I could login with my gmail account but still nothing is populated in the From Dashboard import dropdown. Only solution to get my projects is via Defold Editor 1, import it and then choose From Disk.

**Comment by rob-work** [comment]
I had the same "Empty "Import project from defold.com" list issue.
I could login (though the font was corrupted)

Version 1.2.110
9235b1cfa15414eaff57bb2f772bf7423dfdad8f
2017-07-24T17:31:26.049802
MacOS 10.12.5
Intel Core i7
java version "1.8.0_131"

I too can open a v1 project which then shows in the recent list.

<img width="265" alt="import_project_and_applications" src="https://user-images.githubusercontent.com/786282/28673500-94ba8dba-72da-11e7-8373-071a6184ab1a.png">

**Comment by erikangelin-king** [comment]
Recently merged a fix for this. Please report back if it works/doesn't work for you after the next update!

**Comment by rob-work** [comment]
Top notch, will do.

**Comment by rob-work** [comment]
New build fixes the reported issue for me.
I can now see the the projects in the drop down list, and open them
Top work

**Comment by matgis-king** [comment]
Closing this since the fix seems to have solved it.
