### ISSUE TITLE
Make texture field searchable

### ISSUE THREAD

**Issue by blidfors** [defold/editor2-issues#1080]
You should be able to search for textures in the texture field of gui nodes.
Minimum expected behaviour would be that of Editor 1 where you could manually enter the path the texture you want.

**Comment by adamwestman** [comment]
As an improvement maybe an asset browser, where you could select from available ones and have "recently used" and "recently added".

**Comment by matgis-king** [comment]
Duplicate of #849, but you can expect this to be added soon!

**Comment by matgis-king** [comment]
You can now type-to-filter inside all Property Editor dropdowns!
