### ISSUE TITLE
Scaled text nodes in GUI scenes render wireframe incorrectly [DEFEDIT-1081]

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#1081]
### Expected behaviour

Wireframe should enclose the area delimited by the text's size times the scaling factor.

### Actual behaviour

Wireframe encloses the area delimited by the text's size times **the square of** the scaling factor.

Here's an example: A text field with a size of 100px and a scaling factor of 0.5 has a 25px wireframe around it instead of a 50px wireframe:

<img width="1552" alt="screen shot 2017-07-25 at 18 01 43" src="https://user-images.githubusercontent.com/428060/28578770-57309a34-7163-11e7-92c3-e98477443e3e.png">

### Steps to reproduce

1. Create a new GUI scene
2. Add a text node
3. Scale the text node on either axis

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>9235b1cfa15414eaff57bb2f772bf7423dfdad8f</td></tr>
<tr><td>Build time</td><td>2017-07-24T17:32:10.672322</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 650M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by matgis-king** [comment]
Related to #992?
