### ISSUE TITLE
Editor1 vs Editor2 hash [BLOCKER][CRITICAL] (DEF-1284)

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#1082]
There is a discrepancy between how editor1 and editor2 handles string concatenation of hash values.

### Expected behaviour
DEBUG:SCRIPT:   Testing 'wait_until_true':
DEBUG:SCRIPT:     [OK] (1.347574s) 'wait_until_true'

### Actual behaviour
DEBUG:SCRIPT: test:116: bad argument #1 to 'format' (string expected, got userdata)
stack traceback:
	[C]: in function 'format'
### Steps to reproduce

`local var = ("Timeout while waiting for message with id %s"):format(hash("my_val"))`

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>9235b1cfa15414eaff57bb2f772bf7423dfdad8f</td></tr>
<tr><td>Build time</td><td>2017-07-24T17:32:10.672322</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<table>

**Comment by mathiaswking** [comment]
This is a manifestation of DEF-1284, which is about updating our luajit to a version that supports 64 bit archs.

**Comment by AGulev** [comment]
@mathiaswking  @adamwestman 
is this still an issue after 1.2.115 ?
https://forum.defold.com/t/defold-1-2-115-has-been-released/12616

**Comment by adamwestman** [comment]
@AGulev thanks for the ping, yes I have verified that this is indeed fixed now. 

**Actual Behaviour**
`DEBUG:SCRIPT: Timeout while waiting for message with id hash: [my_val]`
