### ISSUE TITLE
Html5 bundle not loading after changing game.project

### ISSUE THREAD

**Issue by Diskaut** [defold/editor2-issues#1086]
If I change game.project in my project then make html5 bundle and add it to my github.io it freezes at splash image with 0 or 1 percents loading.
For example, if I create new empty project and bundle it at github.io, it works fine. But if I change, for instance, version of this project in game.project it freezes at loading screen (this is when I changed version https://diskaut.github.io/htmltest/).
Also, I think it wasn't a problem month ago. And all old game.projects works somehow. I have two almost identical game.projects that works fine. But if I change one in the editor to be copy of another (change version and where splash_image is) it stops working when I add it to the site.

**Comment by mathiaswking** [comment]
Hi @Diskaut!
I wondering if this might be related to another issue where the engine file comes out empty after bundling. Could you check the size of your MyProject.js (or whatever your project is called) in the bundle folder?

**Comment by Diskaut** [comment]
Ok. It was my mistake in the end. It was of line ending in Windows.
I was previously working in Defold from Ubuntu and it was fine then and I forgot that line ending can be a problem.
