### ISSUE TITLE
Don't show first property in curve editor (ParticeFX)

### ISSUE THREAD

**Issue by Dragosha** [defold/editor2-issues#1089]
![2017-07-28_20-00-18](https://user-images.githubusercontent.com/842807/28723230-9188f65e-73cf-11e7-913e-5fa5fdf34874.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>915313820483e170a6086c16c5bd361bb1a404ad</td></tr>
<tr><td>Build time</td><td>2017-07-28T12:55:02.949454</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>GeForce GT 640/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 381.65</td></tr>
<table>

**Comment by matgis-king** [comment]
I tried to emulate your scene, but was unable to reproduce this issue. Do you happen to know if you were doing something special to get this to happen?

**Comment by Dragosha** [comment]
Hmm, I did not some special things. It happens on any my Particle scenes. Another scene:
![2017-08-01_20-56-02](https://user-images.githubusercontent.com/842807/28834517-e83b8334-76fb-11e7-9889-8468455c26cd.png)
May be depend from OS?

**Comment by matgis-king** [comment]
It did indeed only happen on Windows, and I think you needed to have commas as decimal separators in your system locale settings for it to occur. Thanks for reporting!
