### ISSUE TITLE
Win 32 version will not install on Windows 7

### ISSUE THREAD

**Issue by greggaree** [defold/editor2-issues#109]
Windows 7 64 bit doesn't install when invoking defold.exe.

When I change vmargs settings in config file, editor will install:

Original vmargs settings:
vmargs = -Xms1024m,-Xmx2048m

Modifications to vmargs settings:
vmargs = -Xms1024m,-Xmx1536m

**Comment by RagnarSvenssonKing** [comment]
Fixed
