### ISSUE TITLE
Error : The graphics device does not support

### ISSUE THREAD

**Issue by kkaragoz** [defold/editor2-issues#1090]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Build time</td><td>2017-07-28T18:03:18.671894</td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>Defold sha</td><td>1e63dbed620e768b558ccea36e7a68e622f8c52d</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=505bc90218fe4edaa70d027d7cea9760'>505bc90218fe4edaa70d027d7cea9760</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by matgis-king** [comment]
This is likely due to using an old graphics driver. Could you try again after updating your driver to the latest version?
