### ISSUE TITLE
Ability to filter/search in the game.project settings

### ISSUE THREAD

**Issue by andsveking** [defold/editor2-issues#1095]
### Feature request
Hello, just a random unknown guy here, I have a little feature request that I think would be really useful. :)

How about if you press CMD/Ctrl+F inside the game.project view, you would be able to filter out setting entries? (Say I would hit the filter/search shortcut and enter "display" and it would only show settings related to display.)

Cheers!

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Defold sha</td><td>f99ec13bc35396b0c5e77a2888962a8702e2fc55</td></tr>
<tr><td>Build time</td><td>2017-08-03T10:29:40.214729</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 550</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.13</td></tr>
<table>

**Comment by vlaaad** [comment]
Now we have it! Check for updates mr random unknown guy!
