### ISSUE TITLE
NullPointerException: Unknown when dragging files to the Assets panel in Defold Editor 2

### ISSUE THREAD

**Issue by TheAndruu** [defold/editor2-issues#1096]
### Expected behaviour
Not to get a NPE when dragging files into the Assets window of Defold Editor 2.

### Actual behaviour
Whenever files are dragged into the project explorer area / assets manager panel, a **NullPointerException: Unknown** option panel pops up.  The files are copied correctly, all the same.

Here's a picture of the dialog which pops up when trying to drag over `hero.json` into the `hero` folder:
![npedraggingfilestoprojectexplorer](https://user-images.githubusercontent.com/6318781/28995008-34d60712-79ab-11e7-9210-74d259158b17.png)

### Steps to reproduce

Have a project open in Defold Editor 2.  Drag a file (json, image, doesn't matter) from the file explorer (Nautilus on Fedora 26) into a folder in the Assets panel.  Experience the NullPointerException popup.

This was encountered while following the "Getting Started Tutorial", each time it said to drag files from the 'assets' download into the appropriate folder in the instructions.

<hr/>

<table>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Build time</td><td>2017-08-03T10:29:21.223968</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) </td></tr>
<tr><td>Defold sha</td><td>f99ec13bc35396b0c5e77a2888962a8702e2fc55</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.1.5</td></tr>
<tr><td>OS version</td><td>4.11.11-300.fc26.x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=cbf2bbbcfe59494eab6ff93ac470314d'>cbf2bbbcfe59494eab6ff93ac470314d</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@TheAndruu Can't repro this, please reopen if it still happens for you!
