### ISSUE TITLE
Defold Editor 2's console says libopenal.so.1 is missing when 'Build' is executed, but libopenal.so.1 is present

### ISSUE THREAD

**Issue by TheAndruu** [defold/editor2-issues#1097]
### Encountered behavior

In Defold Editor 2, when trying to run 'Build' on the "Getting started" tutorial, the below error is printed in the console:

> /home/username/.Defold/unpack/f99ec13bc35396b0c5e77a2888962a8702e2fc55/x86_64-linux/bin/dmengine: error while loading shared libraries: libopenal.so.1: cannot open shared object file: No such file or directory

### Attempts to solve

Following the instructions in the [FAQ](https://www.defold.com/faq/), installed the following package:

`sudo dnf install openal-soft.i686`

This led to `libopenal.so.1` being placed in `/usr/lib/`, as in the following screenshot:
![libopenalmissing](https://user-images.githubusercontent.com/6318781/28995102-95d45d64-79ad-11e7-860a-08cc4b260138.png)

As one can see in the above screenshot, the console still prints out the quoted message from above stating it cannot find libopenal.so.1 still.  

After installing the openal-soft.i686 package, a full reboot of the machine was attempted and the message still persists. 

<hr/>

<table>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>Linux spin</td><td>Fedora 26 with GNOME</td></tr>
<tr><td>Defold version</td><td>1.2.110</td></tr>
<tr><td>Build time</td><td>2017-08-03T10:29:21.223968</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) </td></tr>
<tr><td>Defold sha</td><td>f99ec13bc35396b0c5e77a2888962a8702e2fc55</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.1.5</td></tr>
<tr><td>OS version</td><td>4.11.11-300.fc26.x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Hi @TheAndruu!

Thanks for reporting this. It looks like you need to install `openal-devel` too on Fedora 26. So, if you run:

```
sudo dnf install openal-devel
```

Does it work after that?

**Comment by TheAndruu** [comment]
Hi @ragnard-king 

Installed `openal-devel` and then got this error when attempting to build:

> /home/username/.Defold/unpack/f99ec13bc35396b0c5e77a2888962a8702e2fc55/x86_64-linux/bin/dmengine: error while loading shared libraries: libGLU.so.1: cannot open shared object file: No such file or directory

So then I installed:
`sudo dnf install mesa-libGLU`

And now everything works great!  I'm able to run "Build" and the game starts up, runs, and has no errors in the console.

Thanks for the help!

**Comment by ragnard-king** [comment]
Great to hear it is now working for you!

Would of course be helpful if we could document the exact package requirements better on Linux, but it is hard given the matrix of distributions, libraries and package managers... I'll see if we can do better though. Closing this now.
