### ISSUE TITLE
Login process, not using system browser, wont use app password

### ISSUE THREAD

**Issue by xarses** [defold/editor2-issues#1098]
The first time logging in, it requires that I log in to my google account, however I already have sessions in my system browser, which are not available in the defold login. I should be able to use these sessions, rather than being prompted for login credentials.

Further, there is no ability to verify that the site is truly from google.com, or that the app is properly using my credentials.

Lastly, I created an application password (https://myaccount.google.com/apppasswords), which the defold-google-login won't validate.

On linux

**Comment by matgis-king** [comment]
You bring up an excellent point. We'll need to look into this.

**Comment by ragnard-king** [comment]
We've now changed the login process to use the system browser instead of the embedded one, which I believe should resolve your concerns. Available in next update within the hour.
