### ISSUE TITLE
"java.lang.NullPointerException: Unknown" with display resolutions and revert arrow

### ISSUE THREAD

**Issue by Dene33** [defold/editor2-issues#1103]
### Expected behaviour
HTML 5 build

### Actual behaviour
error "java.lang.NullPointerException: Unknown", can't build HTML 5

### Steps to reproduce
Okay, I found what causes this bug. Revert arrows near width and height options (game.project > display). If you put some values to width/height and then click revert arrow, error "java.lang.NullPointerException: Unknown" will appear and HTML 5 will not build.

<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Build time</td><td>2017-08-07T13:46:03.829717</td></tr>
<tr><td>GPU</td><td>ATI Radeon HD 4600 Series</td></tr>
<tr><td>Defold sha</td><td>cdfcda942632f9e49e844204c72be967660c8483</td></tr>
<tr><td>GPU Driver</td><td>3.3.11672 Compatibility Profile Context</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=51ff23ae789c4c5f97b7b015f34978f8'>51ff23ae789c4c5f97b7b015f34978f8</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by Dene33** [comment]
At last we found the exact problem with this issue. The problem is not with resolutions but with revert arrows.

**Comment by ragnard-king** [comment]
Fixed in latest update.
