### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alexanderosadc** [defold/editor2-issues#1104]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Build time</td><td>2017-08-08T18:03:45.605901</td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>Defold sha</td><td>3c2b6332fcf45e66ab393b3a30a482996bb93b7d</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6cda06c414664818a20cac72e5f2215b'>6cda06c414664818a20cac72e5f2215b</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Hi @alexanderosadc! 

The error here was: "The graphics device does not support: glGenBuffers GPU: GDI Generic Driver: 1.1.0 Please try to update your driver to the latest version and restart the application."

To fix this you need to make sure you have installed the correct graphics drivers for your computer, and that the correct graphics card is in use. Closing issue now, but feel free to reopen if you need more help with this.
