### ISSUE TITLE
Sign local iOS application

### ISSUE THREAD

**Issue by dtmzr** [defold/editor2-issues#1105]
### Expected behaviour
- Signing local application

### Actual behaviour
- Trying to sign application in cloud and failing - cause it's local
- Bundling process doesn't work right -> #1091 

### Steps to reproduce
- Create local project and load from disk
- Try to sign iOS application -> Error
- Bundling with right profiles fails too

### Error
> clojure.lang.ExceptionInfo: handler ':editor.bundle/sign' in context ':dialog' failed at ':run' with message 'unknown protocol: ssh'
java.net.MalformedURLException: unknown protocol: ssh

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Build time</td><td>2017-08-09T11:43:07.633937</td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>668115e8cfb2b1d8cb8af94ba1de90a64c69fac8</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.13</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=08056379072d4a97abe33db15f149055'>08056379072d4a97abe33db15f149055</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Labelling this as a feature as we don't currently support signing without uploading to dashboard. We will still investigate the bundling errors reported in #1091.

**Comment by artrmz** [comment]
Looking forward for this! 👍

**Comment by AGulev** [comment]
Outdated. The dashboard is shutted down.
We have signing without uploading to dashboard
