### ISSUE TITLE
Missing settings in .project file

### ISSUE THREAD

**Issue by mosmetro** [defold/editor2-issues#1109]
In [physics] section in .project file those settings are missing:
 ray_cast_limit_2d
 ray_cast_limit_3d
trigger_overlap_capacity

And we can't edit .project file in text mode. Too bad.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Defold sha</td><td>5f3ff6f93eadaf0fdec617c8baac0c4e2232f22d</td></tr>
<tr><td>Build time</td><td>2017-08-11T11:03:14.856873</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.17</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed
