### ISSUE TITLE
File change * doesn't always hide when saving

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1116]
![2017-08-12 16_16_16-defold editor 2 0 - defsp](https://user-images.githubusercontent.com/409170/29244863-ace0974e-7f79-11e7-8f0b-149c8bda7c08.png)

I'm not sure what causes it. If you close a file when this happens it goes back to looking how it should.

**Comment by erikangelin-king** [comment]
Do you know how to reproduce this? We've found a caching issue that could possibly cause this, but it would be nice to verify the fix.

**Comment by subsoap** [comment]
I will report if it happens again. I'm working many hours in editor 2 right now so might get lucky with finding cause.

**Comment by AGulev** [comment]
@subsoap Have you reproduced this issue again?

**Comment by vlaaad** [comment]
@subsoap Have you reproduced this issue again?

**Comment by subsoap** [comment]
@vlaaad have not!

**Comment by vlaaad** [comment]
Good to hear that!
