### ISSUE TITLE
Just try build my project from Editor1 

### ISSUE THREAD

**Issue by realstudent** [defold/editor2-issues#1122]
Just try build my project from Editor1 as HTML5 and fail.
Native builds working well.

### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Build time</td><td>2017-08-11T11:03:14.856873</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>Defold sha</td><td>5f3ff6f93eadaf0fdec617c8baac0c4e2232f22d</td></tr>
<tr><td>GPU Driver</td><td>4.5.13476 Compatibility Profile Context 22.19.171.1</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=ee01fc58de6946d09accc15d2441f8cb'>ee01fc58de6946d09accc15d2441f8cb</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed in latest update.
