### ISSUE TITLE
Editor 2 crash if select main gui in template of node

### ISSUE THREAD

**Issue by LosJustos** [defold/editor2-issues#1131]
Hey, 
i just missclicked and accidentally put the main gui into its own node. 
The Editor doesnt response anymore.

I just selected "Gui" inside Template. Not a big issue 😄 

![gui_error](https://user-images.githubusercontent.com/18404304/29371507-ce73002c-82a8-11e7-9f2f-eff13c42d149.png)

**Comment by erikangelin-king** [comment]
Duplicate #140
