### ISSUE TITLE
Bundle html5

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#1136]
I Tried to do a bundle for html5 with release mode on.

### Expected behaviour
I get a nice folder that can run my game.

### Actual behaviour
This error.

### Steps to reproduce
Check out this project and bundle for html5
<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Build time</td><td>2017-08-18T11:22:43.456551</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>47593b576ee002a1ef3b665a0f5d153844fea980</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=7170bed8c48046f88637e8e8b0f2afbe'>7170bed8c48046f88637e8e8b0f2afbe</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed in latest update.
