### ISSUE TITLE
Tile Map Palette can only be viewed once per edit in Main Editor View [DEFEDIT-1111]

### ISSUE THREAD

**Issue by npmcguirk** [defold/editor2-issues#1137]
### Expected behaviour
When editing a Tile Map in the Main Editor View, view the Tile Map Palette either use Ctrl+Shift+T or select "Show Palette" from the Scene menu. 
### Actual behaviour
The Palette can be viewed once per Layer edit, but after the first view the shortcut keys do not behave and the menu item "Show Palette" is blacked out. To view the Palette again, the Layer must be deselected by either switching Layers in the Outline view, or selecting a different object in the Project Explorer.
### Steps to reproduce
1. Create a Tile Map and add a Tile Source.
2. Select the first layer that is created with the Tile Map
3. Use either the shortcut keys or menu option under Scene to Show Palette and select a tile to paint with.
4. Paint anything or nothing
5. Attempt to view the Palette again through either using the shortcut keys or menu option under Scene.
6. Select the Tile Map in the Outline view being sure the Layer is deselected in the Outline.
7. Select the target Layer again, and confirm Show Palette is now available

Personal addendum: Ctrl+Shift+T isn't a very efficient way to bring up the palette, if Shift+T isn't bound that'd be much nicer.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Defold sha</td><td>47593b576ee002a1ef3b665a0f5d153844fea980</td></tr>
<tr><td>Build time</td><td>2017-08-18T11:22:43.456551</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 6450</td></tr>
<tr><td>GPU Driver</td><td>4.1.10428 Compatibility Profile Context</td></tr>
<table>

**Comment by matgis-king** [comment]
Thanks for the detailed error report! The issue has been fixed and you'll get an update to the editor shortly.

We're also working on improving the keyboard shortcuts in a later update.
