### ISSUE TITLE
Linux: Editor maxes out 16GB RAM and locks up system

### ISSUE THREAD

**Issue by chvck** [defold/editor2-issues#1138]
Seemingly randomly the editor maxes out my RAM (16GB), I usually have ~6GB in use. From what I can tell it's fine one second and the next my system is locking up. I've tried leaving the editor idling for days and have no issues doing that, it only happens when the editor is actively in use. Unfortunately, I don't really have any reproduction steps.

OS name | Linux Ubuntu 17.04
-- | --
Defold version | 1.2.110
Build time | 2017-07-28T18:03:04.536063
GPU | AMD Sapphire Radeon R9 270
Defold sha | 1e63dbed620e768b558ccea36e7a68e622f8c52d
Java version | 1.8.0_131-b11
OS arch | x86_64

**Comment by ragnard-king** [comment]
You can help us debug this issue by forcing the application to create a memory dump when it runs out of memory. Then we can analyse the dump and hopefully see what is causing the runaway allocation. To do this, follow these steps:

1. Create a directory for the memory dump
2. In the directory where you installed Defold, open the `config` file 
3. On the line that starts with `vmargs = `, add the following at the end of the line:

        -XX:+HeapDumpOnOutOfMemoryError,-XX:HeapDumpPath=/path/to/the/dump/dir/you/created

4. Run the editor and wait until it crashes
5. After a crash, you should find a file called `.hprof` in your dump directory. Put that file somewhere where we can download it. Send the link to me: ragnar.dahlen@king.com

Please let me know if you need help with any of these steps. Thanks!

**Comment by chvck** [comment]
I've just done this and I've just had a lock up, I think that as Defold doesn't crash with an OOM error that it hasn't written a log. What happens is that my entire system locks up and I have to drop into a shell session and kill Defold to get my system back (I have a photo of the htop in the shell session that I can send if desired). I did find a log file from Saturday in the top level of my Defold directory, I've put it at https://gist.github.com/chvck/ba0dc112c457f479995ae1c1beea9720. (I couldn't see anything in the log that concerned me security wise but if there's anything in there that I've missed then please let me know when you have taken a copy so that I can take it down).

**Comment by ragnard-king** [comment]
Thanks for the update! It's a little bit strange that you did not get a heap dump as the log clearly shows an OOM happened. 

There's another option though. From your log I can see it failed to create a core dump:

https://gist.github.com/chvck/ba0dc112c457f479995ae1c1beea9720#file-hs_err_pid4300-log-L22

If you enable core dumping (see "try "ulimit -c unlimited" before starting Java again"), then run the editor until it crashes, you should hopefully get a core dump. From the core dump you can then extract a heap dump using the `jmap` tool. `jmap` only comes with a full JDK though, so you would need to install that (OpenJDK or Oracle is fine). Then you can run:

```
jmap  -dump:format=b,file=heap.hprof path/to/defold/jre/bin/java /path/to/core/dump
```

Let me know how that goes or if you need any further help. Would be great to track down this issue.

**Comment by chvck** [comment]
I'll have a go when I get home tonight. That log file is the only one that I've been able to get and it's from Friday, I'll try leaving the editor for longer when my system freezes and see if anything recovers to try to get a log output and core dump. Hopefully I can get them as I agree it'd be great to track it down, my entire OS freezing a couple of times an hour isn't ideal!

**Comment by ragnard-king** [comment]
Great, thanks for your help with this. We definitely don't want to freeze your (or anyone else's) system so tracking this down is a priority.

**Comment by chvck** [comment]
I've let it keep running until it crashes out twice tonight but both time it's failed to write a heap dump. I can see when running the editor that com.defold.editor.Updater is downloading another config file to /tmp/ is it maybe using that instead? In that config file the vmargs are set to the unedited ones.

I've also tried setting the ulimit to unlimited and then running Defold from the same shell session but the logs still say that core dumps are disabled.

Is there a way that I can set the JVM memory limit to be lower? Each lockup takes over an hour for the editor to finally crash out and during that period my computer is totally unusable as I have no memory or swap left.

**Comment by ragnard-king** [comment]
Doh. One thing you could try is omit the `-XX:HeapDumpPath` arguments, ie. only append:

```
-XX:+HeapDumpOnOutOfMemoryError
```

to the `vmargs = ` line (note that arguments need to be separated by `,`). That should write the heap dump into the current directory.

You can lower the JVM memory limit by appending the argument `-Xmx` to the same line, for example:

```
-Xmx1G
````

For a maximum heap size of 1G (you can try 2G, 1G, 512M etc).

So, somehting like:

```
vmargs = [stuff that is already there],-XX:+HeapDumpOnOutOfMemoryError,-Xmx1G
```

**Comment by ragnard-king** [comment]
To troubleshoot the heap dump issue, you could try this:

1. Put [this](https://gist.githubusercontent.com/ragnard-king/916b38a91bd18bad933975246f7fb59e/raw/124d633a22d55470f7712af4a5a7172c76fb1583/OOMTest.java) in a file called `OOMTest.java`
2. Compile: `javac OOMTest.java`
3. Run: `java -XX:+HeapDumpOnOutOfMemoryError OOMTest`

That should definitely run an create a heap dump in the current directory.

**Comment by chvck** [comment]
Making the OOMTest does indeed create a heap dump. I've been using jvisualvm and from what I can see the heap usage is low which is why -Xmx isn't doing anything. I've tried setting ulimit -m to quite low on the session and it still seems to ignore it. I have tried running without the HeapDumpPath argument and I still get no heap dump. I could manually get a heap dump through jvisualvm when the memory usage gets toward my system maximum if that'd be of any use?

**Comment by chvck** [comment]
Last night I did manage to limit the memory and cause my machine not to freeze when Defold does by using `ulimit -d -m -v`. I didn't get a dump - my machine just constantly wants to force quit Defold when it hangs but I could set ulimit to 8G and use jvisualvm to get a heap dump when Defold freezes up that way?

**Comment by ragnard-king** [comment]
A heap dump from jvisualvm would be great!

If you're already using jvisualvm, do you see a slow gradual increase in memory usage until it dies, or does it suddenly peak and die?

**Comment by chvck** [comment]
What I've seen during normal running is a kind of saw tooth profile where the heap climbs (stays under 500mb) and then drops instantly. I assume this is GC or something? I don't know a lot about the java ecosystem. When it runs out of memory the heap still seems to be under 500mb but it flatlines. Does this suggest that something is causing issues?

I'm running Defold through terminal and this might be a red herring but last night during one of the freezes I saw an error message from my graphics driver which googling found a post from 2013 reported as a driver issue causing the driver to eat RAM. As this was an issue from 2013 I'm guessing it's probably unrelated by might be worth bearing in mind and I'll keep an eye for it appearing again (I've only seen it once). I'll grab a heap dump tonight :)

**Comment by chvck** [comment]
I don't know what's changed by when using ulimit the editor now instantly crashes out on OOM so I don't get chance to heapdump it (despite reporting creating a core dump it doesn't). I've taken a heapdump of the java process, with no ulimit set, when my system RAM got to ~13GB. Hopefully this will help! https://www.dropbox.com/s/m4rjx4zsjs6jwka/heapdump-1503650931242.hprof?dl=0

**Comment by chvck** [comment]
With ulimit -d -v -m all set to 9000000 it seems to usually crash with

```
libGL error: failed to create drawable
libGL error: failed to create drawable
Failed in glXMakeCurrent#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 280 bytes for AllocateHeap
```
https://www.dropbox.com/s/xb6v1mypfgut3dj/Screenshot%20from%202017-08-25%2009-58-59.png is an image from jvisualvm as the editor crashed.

**Comment by erikangelin-king** [comment]
Hi @chvck! I'm going through oldish issues, is this still happening?

**Comment by chvck** [comment]
To be honest I've not used Defold in a few months. It was still happening when I last used it though.

**Comment by erikangelin-king** [comment]
Thanks for reporting back, I'm closing this for now. I hope you feel like trying Defold again some day, please reopen if the same thing happens then :)
