### ISSUE TITLE
GUI texture node bounding box shows texture atlas inner padding

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1139]
With inner padding set 4 in texture

![2017-08-18 14_27_15-defold editor 2 0 - defsp](https://user-images.githubusercontent.com/409170/29478365-627f1ea8-8421-11e7-84c8-8039883900f6.png)

With inner padding set to 0 in texture

![2017-08-18 14_27_29-defold editor 2 0 - defsp](https://user-images.githubusercontent.com/409170/29478382-75351b1a-8421-11e7-9f8a-bd0018c00d2d.png)

This does not impact the positioning in the Properties for x,y, but makes the bounding box less useful for eyeballing positioning of things

**Comment by matgis-king** [comment]
I think this is by design? If you want the box to fit tightly around the image I think you should be using Extrude Borders instead of Inner Padding, but perhaps I'm misunderstanding your use case?

**Comment by subsoap** [comment]
That may be the case, I will test more to see if there are any issues. I think the issue is that the inner padding has no consequence for size or placement but still changes the bounding box but I'd have to double check in a bit...

**Comment by erikangelin-king** [comment]
@subsoap Still an issue?
