### ISSUE TITLE
Engine should still get mouse action events while cursor is outside of game window (DEF-1996)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1142]
This causes an issue with software cursors when the hardware cursor leaves the game Window.

![2017-08-18 18_46_02-defsp](https://user-images.githubusercontent.com/409170/29482408-8134d3fa-8445-11e7-85d2-aeb23fd0f12a.png)

I can make a workaround with DefOS but it would be cleaner if the engine did it.

**Comment by britzl** [comment]
DEF-1996

**Comment by britzl** [comment]
Duplicate: https://github.com/defold/editor2-issues/issues/1992
