### ISSUE TITLE
In msg.post the receiver shorthand nil should be removed (DEF-2860)

### ISSUE THREAD

**Issue by mosmetro** [defold/editor2-issues#1143]
In msg.post the receiver shorthand nil for the current component should be removed. This is the source of the hard to find bugs when receiver stored in a variable, and that variable in some cases becomes nil.
The receiver shorthands should be always valid string, url or hash, not nil.

**Comment by Malmer** [comment]
I second this one. Source for many bugs.

**Comment by sicher** [comment]
There is already a warning if doing go.delete(nil). I believe that was a first step towards removing the shorthand. Added an issue DEF-2860.

**Comment by AGulev** [comment]
Solved in https://forum.defold.com/t/defold-1-2-160-has-been-released/60637
