### ISSUE TITLE
physics.ray_cast needs additional parameter

### ISSUE THREAD

**Issue by mosmetro** [defold/editor2-issues#1145]
physics.ray_cast needs response_receiver(url) parameter. This is useful when we request ray cast in context of one script and want receive response in another.

**Comment by sicher** [comment]
There is an issue reported about adding an optional callback to physics.ray_cast(). DEF-2581

**Comment by mosmetro** [comment]
DEF-2581 is unrelated to this issue. Callback is just another way to receive response in the same context.
The point is to receive responses in another script, attached to another game object.

Example:
local ray_cast_response_receiver = go.get_id(...) 
physics.ray_cast(my_start, my_end, my_groups, ray_cast_response_receiver)

**Comment by britzl** [comment]
With the ray cast callback it becomes very easy to forward the response to another receiver.

We will however not build this kind of functionality into the engine. It is not done anywhere else in the engine either.
