### ISSUE TITLE
Unable to Sync project

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#1152]
Given I want to open local projects and not use the Dashboard unless I have to.
When I have made changes to the project I wish to Syncronize the project.
Then I am prompted to login.
And I sign in with one of my two accounts.
And I press "Pull".

### Expected behaviour
Remote changes are pulled down and I am asked to commit and push my work.

### Actual behaviour
I see an "Error getting changes" message.

### Steps to reproduce
Download a project from Dashboard using Account A.
Logout and Close Defold Editor.
Open local project without Signing in.
When Prompted to Sign-in (Syncronize the project), Select Account B.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.112</td></tr>
<tr><td>Defold sha</td><td>5822990e6cbb8aeabc2cb5aa6d868452ee0d4ee8</td></tr>
<tr><td>Build time</td><td>2017-08-23T18:31:51.747055</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<table>

**Comment by adamwestman** [comment]
This was related to wrong account being used.

The project was checked out from Account A and then I opened it locally using Account B.

**Comment by erikangelin-king** [comment]
Closing this with leftover issue of improving error messages #1158
