### ISSUE TITLE
Log output lags [DEFEDIT-1124]

### ISSUE THREAD

**Issue by olovn** [defold/editor2-issues#1156]
### Expected behaviour
Log output is perceived as nearly real time

### Actual behaviour
Log output is delayed. It gets more and more delay the longer you keep using the editor. I have to restart the editor several times every day because of this.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Defold sha</td><td>8975f56e27df2fa15395dbd44aea897bdad29064</td></tr>
<tr><td>Build time</td><td>2017-08-14T10:14:50.341779</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M295X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed, coming in next update.
