### ISSUE TITLE
Add Options For Searching | Search is too fuzzy [DEFEDIT-1123]

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1159]
If I search for "camera.lua" I get a lot of files. In the current project I work in searching for "camera.lua" gives about 200 hits because the search is so fuzzy.

**c**om/pl**a**tform/**mera**/thing.**lua**
**c**om/pl**a**tform/**mera**/stuff.**lua**
**c**om/pl**a**tform/**mera**/that.**lua**
**c**om/pl**a**tform/**mera**/this.**lua**
/main/**camera.lua**

The search is way to fuzzy, more often than not a user would use the search for a file they kinda know the name of but not where it is. If I know exactly what the file is called I want to be able to find it easier. I doubt anyone would search "camera.lua" to find "stuff.lua".

Add "!" for using explicit searching, it matches on complete words. Until a * is found where it uses the fuzzy search again.

**Comment by matgis-king** [comment]
While the fuzzy search algorithm will return a lot of matches, it will rate what it considers better matches higher, and present them at the top of the list. I ran your example paths through the scoring algorithm, and it correctly had `/main/camera.lua` as the top result. To me, this works well for the use case you describe, where the user kinda knows what the file is named but not where it is.

I'd love to tweak the scoring algorithm if it has issues, though. Perhaps you could send me an email with some concrete examples of searches where you think it gets it wrong in the project you're working on?

**Comment by Jerakin** [comment]
You got mail!

**Comment by matgis-king** [comment]
A fix has been merged. Thanks for reporting!
