### ISSUE TITLE
Mouseover tab doesn't show paths for all resources

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1161]
### Expected behaviour
mouseover tab
Tool tip with path to the file

### Actual behaviour
mouseover tab
Tool tip without file

### Steps to reproduce
mouseover tab of a file that are in builtins or in dependency.

<table>
<tr><td>Defold version</td><td>1.2.111</td></tr>
<tr><td>Defold sha</td><td>17730223b7df1ab57434a900a5cb7692dbdb975e</td></tr>
<tr><td>Build time</td><td>2017-08-16T14:52:43.956621</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix coming in next update. We will now always show the project path when hovering a tab. We've also added two additional resource commands "Copy Project Path" and "Copy Full Path", available in resource context menus.
