### ISSUE TITLE
Weird charset in Google login window & logout not working.

### ISSUE THREAD

**Issue by jpz** [defold/editor2-issues#1165]
Operating System: MacOS 10.12.5
Defold.app version 1.2.112 

I downloaded the DMG, I ran Defold.app editor2 directly from the DMG bundle, and when I signed in I got some weird characters (screenshots below.)

~~I wanted to reproduce, before submitting this issue, with the Defold.app moved to the Applications directory, in case that had been a cause.~~   

_I have since reproduced successfully._

~~I tried logging out, and rerunning (with Defold.app now dragged into the Applications folder), however the logout doesn't seem to me log out, so I couldn't reproduce a second time.~~

_I was logged out successfully, the login screen only appears at Import Project, not at start-up, logout is working fine._

My Macbook's internationalisation settings are UK, but this might be Google internationalisation, on the basis of my IP geolocation - and my IP geolocates to Sydney, Australia.

<img width="806" alt="login 2" src="https://user-images.githubusercontent.com/934340/29809309-08db7dee-8cdf-11e7-865f-f79abf774e59.png">
<img width="798" alt="login" src="https://user-images.githubusercontent.com/934340/29809310-09259a8c-8cdf-11e7-8037-30630b4a3334.png">

**Comment by erikangelin-king** [comment]
The weird characters is a known webfont/javafx issue. If you copy-paste the text into notes for instance it will be readable. We're looking into maybe using the system browser instead.

**Comment by erikangelin-king** [comment]
See #432, #1157
