### ISSUE TITLE
game.project setting to auto-increment a build number in the game.project file

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1168]
> A standard feature for IDE and build process. If feature enabled every time when you build/bundle project last minor version number auto incremented on 1

https://forum.defold.com/t/autoincrement-build-version/11106

**Comment by erikangelin-king** [comment]
We've discussed this and we don't want to assign the version string any particular meaning. We want to later on support "editor extensions" or at least running simple scripts from within the editor, and this problem looks like a perfect match for that. Thanks!
