### ISSUE TITLE
Editor Extendability [DEF-2859]

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1170]
(Copy of DEF-2859)

**Description:**
I want to be able to add scripts and user tools into the Engine directly. 
First step would be the ability to trigger user scripts on Close, Open, Pre-build, Post-build and such events.
It could then be extended to the ability to add GUI elements that are 'native' to the editor.

**Use case:**
The ability to run post-build scripts would be really handy for pipeline stuff like meta data generation that is needed for the game, with a good enough system and support the limits are endless! See graphical applications like Maya and its python support for an good example of how it would work.

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/autoincrement-build-version/11106/8
https://github.com/defold/editor2-issues/issues/1168

**Comment by vlaaad** [comment]
@Jerakin please have a look at editor scripts ([announcement](https://forum.defold.com/t/editor-scripts-alpha-release/63573), [manual](https://defold.com/manuals/editor-scripts/))
