### ISSUE TITLE
No error produced if no game.project file is in folder of a .project file opened

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1171]
I created a blank game.project file for a blank project example and accidentally named it games.project instead of game.project ... reopened the launcher 3 times before I realized there was something wrong. No error was produced, just the loader disappeared.

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144. Feel free to reopen in case it is still an issue.

(Now you can't open project without game.project file)
