### ISSUE TITLE
Launching engine - Launch failed

### ISSUE THREAD

**Issue by abadonna** [defold/editor2-issues#1173]
### Expected behaviour
MACOS Sierra 10.12.4, building project with CMD-B in new editor, target -> New Local Engine
should open new window with game inside
 
### Actual behaviour

Message in console: 
"Launching engine
Launch failed"

### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.112</td></tr>
<tr><td>Defold sha</td><td>b261c77f370bf6bb5a9cff7d40552ab89cc57bae</td></tr>
<tr><td>Build time</td><td>2017-09-01T14:11:04.309816</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 540</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.24.45</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We recently merged some changes to how building connects to the launched engine. Does this happen on an empty project? Are you using native extensions?

**Comment by abadonna** [comment]
Yes, just created a fresh one to test.
No extensions.

**Comment by erikangelin-king** [comment]
Could you try downloading a fresh version of the editor from the dashboard?

**Comment by erikangelin-king** [comment]
As a temporary workaround you can download the version just before the change here:
https://d.defold.com/editor2/f0f8705de03e808595901dc5f098db9c118ee07e/editor2/Defold-x86_64-darwin.dmg
Let it overwrite the version you have installed, and when the question about updating pops up just click “Skip Update”.
We'll look into this next week.

**Comment by tarnumius** [comment]
Same error on windows too.
https://d.defold.com/editor2/f0f8705de03e808595901dc5f098db9c118ee07e/editor2/Defold-x86_64-win32.zip - link for windows

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/launch-failed-error-on-macos-after-update-editor-2/11176/7

**Comment by erikangelin-king** [comment]
Thanks @tarnumius!

**Comment by erikangelin-king** [comment]
We're trying to track down this issue. Were you running the editor without a network connection? Did the engine window appear and then close or did it never appear at all?

**Comment by abadonna** [comment]
OK, now it works if online.
If offline - icon pops up and disappears, now window is visible

**Comment by erikangelin-king** [comment]
Thanks! That makes (some) sense.

**Comment by erikangelin-king** [comment]
We've just reverted the broken commit while we investigate what went wrong, so feel free to update.

**Comment by tarnumius** [comment]
Thank you!

**Comment by erikangelin-king** [comment]
This issue was fixed recently, please reopen if there are any more problems :)
