### ISSUE TITLE
Synchronization lose my changes [DEFEDIT-1141]

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1177]
### Actual behaviour
1) I start a refactoring of game.

2)I rename some modules,go,create new modules,moved them and etc.

3)Then i push synchronization button.

4)In synchronization i don't have all my changes. I have only changes for one file.

5)I cancel synchronization.

6)I get error.( i don't report it,i cancel it)

7)I lost all changes except changes that was in synchronization window.

8)I have changes and new files in editor, if they was opened.I can save files that was before in git. But i can't save new files.

### Steps to reproduce
Don't know. Not happended before.
Maybe it because i use atom as lua ide.(i use atom before without problems)
<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.112</td></tr>
<tr><td>Build time</td><td>2017-09-01T20:08:01.999211</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>Defold sha</td><td>6483f6e0d117d6a1f9a0f1820117f9f2432368df</td></tr>
<tr><td>GPU Driver</td><td>4.5.13474 Compatibility Profile Context 22.19.162.4</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=f78fb09ff827460bb7fc3b58928c0b8d'>f78fb09ff827460bb7fc3b58928c0b8d</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by d954mas** [comment]
In git i have stash wip on with all my new files

**Comment by erikangelin-king** [comment]
If you manage to reproduce this please let us know!

**Comment by EdwardvanRaak** [comment]
Got this error before having the same issue, everything reverted back to initial commit. No way to get my progress back.

`clojure.lang.ExceptionInfo: handler ‘:synchronize’ in context ‘:global’ failed at ‘:run’ with message ‘Could not delete file A:\some_name\some_name\main\images\some_name’`

I do remember that I was removing folders from the file explorer and that the editor was giving errors and shortly after that I tried to synchronize.
