### ISSUE TITLE
Using latest sublime as code editor fails catastrophically

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#1178]
STR:

1. Set `/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl` as code editor
2. Open a script or lua file
3. Defold launches many many instances of sublime, until it crashes.

**Comment by JCash** [comment]
First, I couldn't even do that: Entering `/Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl` (since it's a plain text field I assumed it to be a shell command, and that's what you use in the shell :/)
Once I removed that back slash, I got the same issue as you

**Comment by ragnard-king** [comment]
Re-tested now and I can't reproduce this issue with either Sublime 3 (3143) or Sublime 2 (2.0.2). Please re-open if the issue still persists.
