### ISSUE TITLE
Font outline alpha in HTML5 

### ISSUE THREAD

**Issue by abadonna** [defold/editor2-issues#1179]
Outline alpha property is missing in Font Editor (but exists in .font file)
Zero alpha (default) makes outlines invisible in HTML5 builds

<table>
<tr><td>Defold version</td><td>1.2.112</td></tr>
<tr><td>Defold sha</td><td>6483f6e0d117d6a1f9a0f1820117f9f2432368df</td></tr>
<tr><td>Build time</td><td>2017-09-01T20:08:01.999211</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 540</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.24.45</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update within 1h.
