### ISSUE TITLE
gui.glue(node,position)

### ISSUE THREAD

**Issue by GamingBud** [defold/editor2-issues#1186]
> https://forum.defold.com/t/gui-glue-node-position/11310

gui.glue(node,position) would allow you to make a gui component and keep it in the same place, relative to world position, and would help build components such as tooltips, buttons, and menu’s in different ways.
I would like to use the gui function to build a tooltip. When the tooltip is created, I need it to stay relative to it’s position in the world, not to the camera. This way, the menu will stay over an object displaying it’s details and values. For instance, when I click on a tree, it will display it’s a pine tree with a certain amount of wood harvestable. Also built into the tooltip are two buttons, “chop” and “close”, hopefully self-explanatory.
```
gui.set_xanchor and
gui.set_yanchor
```
set the gui’s anchor relative to the screen resolution, but keep it glued to the camera position.

**Comment by matgis-king** [comment]
Is this solved by the response @britzl posted on the forum thread?

**Comment by GamingBud** [comment]
It would be nice to have a function which directly did this, but I understand there are things of much higher priority. You can close this if necessary.
