### ISSUE TITLE
Animation preview in atlas editor

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1189]
Add possibility to play animation in atlas editor. It will be useful to check that animation correct, and choose correct frame rate.

**Comment by ragnard-king** [comment]
This is already possible:

1. Select the animation you want to play in the outline.
2. Select "Scene" -> "Play" in main menu (or Shortcut+P) to play. 

You can tweak the animation settings (including images) while it's playing. Same thing with tile sources. You can also select a sprite with an animation and play it in the same way.

Does this solve your problem?

**Comment by d954mas** [comment]
Yes, that what i need, thanks.

**Comment by ragnard-king** [comment]
Ok, great, closing this then.
