### ISSUE TITLE
Started building the project, and got this error

### ISSUE THREAD

**Issue by EgillAntonssonKing** [defold/editor2-issues#1190]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.112</td></tr>
<tr><td>Build time</td><td>2017-09-06T10:01:07.310257</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>68284097dbce2f183b9554e17bb732976328b367</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6e6e022e64534f4e9d460057bf245821'>6e6e022e64534f4e9d460057bf245821</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This was an OOM/GC overhead limit exceeded. Since then we have made some significant improvements to the memory usage during build. Closing for now, please reopen if it happens again and we'll have a closer look at your case.
