### ISSUE TITLE
Get Remote Change window cannot click x to quit the window

### ISSUE THREAD

**Issue by wingyplus** [defold/editor2-issues#1197]
When I open Get Remote Change window (from Synchronize menu). I cannot close by click quit button (x button on the top left) to close it but Cancel button does.

### Expected behaviour
When I click quit button, it should be close Get Remote Change window.

### Actual behaviour
It doesn't close.

### Steps to reproduce
* Go to File > Synchronize..., Get Remote Change is open
* Try to click quit button (x button on the top left)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Defold sha</td><td>d8eecb28411ff3cd0c9a11187ae6a1afbd1dd514</td></tr>
<tr><td>Build time</td><td>2017-09-11T17:13:36.783725</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<table>

**Comment by matgis-king** [comment]
This is by design. We need the user to choose either Done or Cancel, and since Cancel will abort the entire Sync operation and revert any resolved conflicts we thought it best to prevent this from happening by accident.
