### ISSUE TITLE
Opening a .tilemap can alter it (syntactically) [DEFEDIT-1135]

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#1198]
After opening my [tilemap](https://github.com/JCash/defoldexamples/blob/master/main/astar/images/tiles.tilemap) it becomes dirty and it subsequently will show up in the git changelist unless I revert it.

### Expected behaviour
No change upon opening

### Actual behaviour
The tilemap show up as dirty

### Steps to reproduce
Open this [tilemap](https://github.com/JCash/defoldexamples/blob/master/main/astar/images/tiles.tilemap)
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Defold sha</td><td>d8eecb28411ff3cd0c9a11187ae6a1afbd1dd514</td></tr>
<tr><td>Build time</td><td>2017-09-11T17:13:36.783725</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M290X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<table>

**Comment by matgis-king** [comment]
Fixed in defold/defold#1779, merged on Sep 19, 2017.
