### ISSUE TITLE
Error after adding file to collection from dependency

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1200]
This is what I did
1. Open editor( with --new)
2. Open a collection
3. Add dependency
4. Fetch Libraries
5. Add script from the dependency to a collection.

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-11T17:13:36.783725</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>d8eecb28411ff3cd0c9a11187ae6a1afbd1dd514</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=8dcbbeaefa5b4a18a3cd5b1103c73af2'>8dcbbeaefa5b4a18a3cd5b1103c73af2</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Could you mail me the script or better yet info on the dependency you added? Seems to be an error in our lua parser, guessing the script hits some broken code path.

**Comment by Jerakin** [comment]
It was defcon https://github.com/britzl/defcon/blob/master/defcon/console.script

**Comment by Jerakin** [comment]
Also added [DefNet](https://github.com/britzl/defnet) and [some info dependency](https://github.com/Jerakin/defbug) at the same time.

**Comment by Jerakin** [comment]
I could add it without a hick-up after a engine restart

**Comment by erikangelin-king** [comment]
Can't repro this :( Please open or report if it happens again!
