### ISSUE TITLE
Build error: No such file or directory

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1202]
Trying Build but get this error. Says that the directory doesn't exist even though the path given in the error exists.

Not sure how to repo but, I have more than one editor open, the project have been open a while without me changing anything and working in the other instances of the editor.

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-11T17:13:36.783725</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>d8eecb28411ff3cd0c9a11187ae6a1afbd1dd514</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=9324a07efba340b3b6c16c0d02dbcc16'>9324a07efba340b3b6c16c0d02dbcc16</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can't repro, and sadly the error info has been lost. Please report the issue if it happens again!
