### ISSUE TITLE
Can not fetch project

### ISSUE THREAD

**Issue by umutkarakoc** [defold/editor2-issues#1206]
Hi everyone,
When i try to open project from dashboard. I got this error:
"http://cr.defold.se:9998/prjs/78725: authentication not  supported"
![error](https://user-images.githubusercontent.com/3602670/30385932-3720346e-98b1-11e7-8df3-92414d58c721.PNG)
It is work when I try editor vesion 1 with same account.
Os: Windows 10 64x

**Comment by matgis-king** [comment]
It seems we have trouble communicating with the Defold servers using the current credentials. Here are some things to try:
* Open any project in the new editor, then choose **Logout** from the File menu. Close the editor and try to import your project again.
* A firewall or proxy might be blocking communications with the server. If you're on a home network, temporarily disable the Windows Firewall and see if you are able to reach the servers. If that works, you should re-enable the Windows Firewall and configure it to let the Defold editor through.

**Comment by erikangelin-king** [comment]
@umutkarakoc Please reopen if it happens again.
