### ISSUE TITLE
Upgraded to new version and opened the getting started project from dashboard. Crashed

### ISSUE THREAD

**Issue by vinuf666** [defold/editor2-issues#1212]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-13T14:46:12.984175</td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>Defold sha</td><td>2792f64cbb7bf6209b04b3b8e108167c67b115c8</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=383fc2b04e384e18b29f4061a4bbc898'>383fc2b04e384e18b29f4061a4bbc898</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by matgis-king** [comment]
Looking at the error message, this appears to be this:

```
The graphics device does not support: glGenBuffers
GPU: GDI Generic
Driver: 1.1.0
Please try to update your driver to the latest version and restart the application.
```

This error will appear if your graphics driver does not support a feature we need to render the scene view in Editor 2. Typically this will only happen if your graphics driver is really old but we've received a bunch of similar reports over the weekend, so perhaps something has happened.

Were you able to run Editor 2 in the past? If so, did you recently change something such as installing a Windows update or driver?

Do you still get the error if you update your graphics driver to the latest version?

**Comment by vinuf666** [comment]
Hi Mats,

Thank you for the quick info. Yes it makes sense. The system is an Oracle
virtualbox windows 7 host and the issue happened after the vm host drivers
were updated yesterday. The virtualbox itself was upgraded due to which the
drivers also updated.

Thanks,
Vinu

On 18-Sep-2017 1:30 PM, "Mats Gisselson" <notifications@github.com> wrote:

Looking at the error message, this appears to be this:

The graphics device does not support: glGenBuffers
GPU: GDI Generic
Driver: 1.1.0
Please try to update your driver to the latest version and restart the
application.

This error will appear if your graphics driver does not support a feature
we need to render the scene view in Editor 2. Typically this will only
happen if your graphics driver is really old but we've received a bunch of
similar reports over the weekend, so perhaps something has happened.

Were you able to run Editor 2 in the past? If so, did you recently change
something such as installing a Windows update or driver?

Do you still get the error if you update your graphics driver to the latest
version?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/defold/editor2-issues/issues/1212#issuecomment-330151646>,
or mute the thread

**Comment by matgis-king** [comment]
We've had limited success with Virtualbox ourselves, but have managed to get the editor to run inside a Parallells VM, so it seems like it should be possible.

The VM needs to be configured to support OpenGL 2.0 since we use it to render the scene view. In Parallells this is a setting that has to be explicitly turned on for it to work. Perhaps a similar setting exists in Virtualbox that was somehow lost during the upgrade?

**Comment by vinuf666** [comment]
Thanks Mats,

I got it working by checking 'Enable 3D Acceleration' under the Settings of
the VM ->Display->Screen (Tab).
Now it opened up.
Thank you for the hint.

-Best,
Vinu

**Comment by matgis-king** [comment]
Thanks for posting the solution! I'll close this issue. Glad to hear you got it to work!
