### ISSUE TITLE
Error Syncing with server

### ISSUE THREAD

**Issue by BoidBoid** [defold/editor2-issues#1213]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-06T17:05:59.888263</td></tr>
<tr><td>GPU</td><td>GeForce GTX 660/PCIe/SSE2</td></tr>
<tr><td>Defold sha</td><td>073b68bff657b19461b7fcafec83927e976f2e29</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 382.05</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=3582e642256242a28c6918e63db21490'>3582e642256242a28c6918e63db21490</a></td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Sorry @BoidBoid, error info was lost, please re-report if it happens again!
