### ISSUE TITLE
GPU Driver update pop-up

### ISSUE THREAD

**Issue by jeslick** [defold/editor2-issues#1214]
### Expected behaviour
On Launch, Pop-up said I needed to update my GPU Drivers, stating that mine were Version 1.10 and called "GDI Generic"
### Actual behaviour
Upon clicking dismiss, pop-up closes and program seems to run as normal.
### Steps to reproduce
Download defold2 and launch I guess.
<hr/>

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-13T14:46:12.984175</td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>Defold sha</td><td>2792f64cbb7bf6209b04b3b8e108167c67b115c8</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=e6f4cd1c1dc140d5a55c5b79cba91178'>e6f4cd1c1dc140d5a55c5b79cba91178</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Hi @jeslick,

That popup is there to tell you that your GPU driver does not support all the capabilities we use in the editor, meaning some views/features won't work correctly or at all. Were you able to run editor2 previously without the warning, or is this the first time you've tried it?

**Comment by matgis-king** [comment]
Also, do you still get the error if you update your graphics driver to the latest version?

**Comment by erikangelin-king** [comment]
@jeslick Please reopen if the editor is still complaining and updating the drivers doesn't help.
