### ISSUE TITLE
Crash when building

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1216]
Not sure why. Only tried to build.

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-18T10:56:30.427085</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>ffa4685cf0d07abbc1fa31ee4247154b3aa139cd</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=555b96f6c9924f6cb98833ce4f7bde7b'>555b96f6c9924f6cb98833ce4f7bde7b</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Do you have any idea what you did before it happened? The bug happens when we try to process some code in a script-file, but for some reason it has changed (to null) in an unexpected way. Did you add a library, edit/delete/rename a script file, undo in a script file or something similar? If it happens again, it would be great to get some more information.

**Comment by Jerakin** [comment]
Does the error say which script file? Would give me a hint to what I could have been doning.
But I renamed a lot of assets but they where textures and collections only, no script files.

**Comment by ragnard-king** [comment]
Unfortunately it does not. I'll continue digging. If it happens again, please let me know.

**Comment by erikangelin-king** [comment]
Hi @Jerakin! We've recently fixed two separate issues that could result in this error. I'm closing this for now, but please reopen/re-report if it happens again so we get a new stack trace to work from :)
