### ISSUE TITLE
Error when closing

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1217]
Not sure why, had to force quit to be able to close the editor
<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.113</td></tr>
<tr><td>Build time</td><td>2017-09-18T10:56:30.427085</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>ffa4685cf0d07abbc1fa31ee4247154b3aa139cd</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=09facedcf63b42119e2d94c87ff4abc5'>09facedcf63b42119e2d94c87ff4abc5</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Likely consequence of #1216
