### ISSUE TITLE
Lag when leaving window and returning [DEFEDIT-1138]

### ISSUE THREAD

**Issue by robertatamking** [defold/editor2-issues#1225]
On PC

Defold lags when changing to a different window and returning.  It hangs on "Reloading modified resources" even though nothing was changed and takes about 2-3 seconds before the window becomes active again.  This happens every time when switching to a different window.

**Comment by ragnard-king** [comment]
A fix that should speed up the "Reloading modified resources" operation has been merged and will be available in an update within 1h.
