### ISSUE TITLE
Shortcuts W, E, R don't work in particle editor

### ISSUE THREAD

**Issue by robertatamking** [defold/editor2-issues#1227]

**Comment by ragnard-king** [comment]
I think it's only R (scale) that doesn't currently work. Behaviour in editor1 is that the scale tool changes "Emitter Size X/Y/Z".

**Comment by robertatamking** [comment]
Testing on PC, none of the shortcuts are working for me.

**Comment by ragnard-king** [comment]
Have you updated to latest update? (No "Update Available" visible in bottom right corner)

**Comment by ragnard-king** [comment]
Fix has been merged, coming in update within 1h.
