### ISSUE TITLE
Can't close the editor nor build after going backwards in git history

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1230]
### Expected behaviour
Being able to use the editor as normal (maybe after it have loaded the updated resources into memory)

### Actual behaviour
Errors

### Steps to reproduce
Go backwards in git history, quite a bit I presume?

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.114</td></tr>
<tr><td>Build time</td><td>2017-09-19T17:49:18.100419</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>c3abddc8fb392204cc0bb4b9b335a90513f42622</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=65cb1cfa440d44f48973416a4bad1b54'>65cb1cfa440d44f48973416a4bad1b54</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hnnnggg, error info was lost on this one also :( @Jerakin, please re-report if it happens again!
