### ISSUE TITLE
Tilemap issue: Buggy drawing behavior.

### ISSUE THREAD

**Issue by AxelHammarback** [defold/editor2-issues#1231]
### Expected behaviour
I expect it to draw the tiles on the tilemap

### Actual behaviour
It appears as if it's not drawing the tiles. Could have something to do with the fact that I've drawn on those tiles before, as this error doesn't occur when drawing on "fresh" tiles.

### Steps to reproduce

**Video:** [editor2-bug-tilemap-video.zip](https://github.com/defold/editor2-issues/files/1333080/editor2-bug-tilemap-video.zip)

**Affected project:** [snake-tutorial-tilemap-bug.zip](https://github.com/defold/editor2-issues/files/1333077/snake-tutorial-tilemap-bug.zip)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.114</td></tr>
<tr><td>Defold sha</td><td>de362140b079dcade1daffb2d47a8caddf80ff47</td></tr>
<tr><td>Build time</td><td>2017-09-21T16:18:58.933590</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.14.73</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix has been merged, coming in next update, within the hour
