### ISSUE TITLE
Difference in editor 1 and 2 save format (editor 2 omits spaces)

### ISSUE THREAD

**Issue by olovn** [defold/editor2-issues#1240]
### Expected behaviour
Editor 1 and 2 should serialize data in the same way so that we don't get modified files when nothing actually has changed.

### Actual behaviour
[2:54 PM] Olov Nordenstam: We get a lot of changed files due to that Editor 1 and 2 serializes parameters with or without spaces (see screenshot). That causes some unneeded frequency of modified files since we are a big project and people are using editor 1 & 2, roughly 50/50.

[2:54 PM] Olov Nordenstam: (Defold 2 saves without spaces)

Example off diffing lines:
-  "    value: \"0.4, 0.75, 0.99, 1.0\"\n"
+  "    value: \"0.4,0.75,0.99,1.0\"\n"

### Steps to reproduce

Open the Presto project in editor 2, when you do a save all, it will very often give the mentioned result, provided that files have previously been saved in editor 1.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.114</td></tr>
<tr><td>Defold sha</td><td>73ff54ab5003782f88d777655badef8c8e68c42b</td></tr>
<tr><td>Build time</td><td>2017-09-19T12:59:55.512553</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M295X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed, coming in update within the hour.
