### ISSUE TITLE
Native extension broken on windows

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1241]
### Actual behaviour
![2017-09-28_22-06-52](https://user-images.githubusercontent.com/2655263/30985631-84685640-a499-11e7-92c1-447d9204c83a.png)
### Steps to reproduce
Create new project. Add any native extension
Build not working. Html build working
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.114</td></tr>
<tr><td>Defold sha</td><td>016ad4027dd4f52dcb8499c3b21560a7f9e4fdb8</td></tr>
<tr><td>Build time</td><td>2017-09-28T20:34:21.870277</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13474 Compatibility Profile Context 22.19.162.4</td></tr>
<table>

**Comment by mathiaswking** [comment]
This is now fixed in the next update!
