### ISSUE TITLE
Tilemap in engine has optimization issues with draw calls

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1242]
If a tilemap has more tile area why does it cause extra draw calls? As the tilemap increases in dimension size, the number of drawcalls it causes increases.

Some more potential issues mentioned in this thread 

https://forum.defold.com/t/how-to-optimize-tile-map-draw-calls/11961

**Comment by AGulev** [comment]
Solved in [1.2.161](https://forum.defold.com/t/defold-1-2-161-has-been-released/61861)
