### ISSUE TITLE
after tilesource removing [DEFEDIT-1152]

### ISSUE THREAD

**Issue by kiripu** [defold/editor2-issues#1244]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.114</td></tr>
<tr><td>Build time</td><td>2017-09-29T16:26:18.320597</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>Defold sha</td><td>8647b82b881f6c8eb9e52128f69940d2494e9d9b</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 375.70</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=b126e5b2e1d54399a5cacb96b08ee7ca'>b126e5b2e1d54399a5cacb96b08ee7ca</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Root cause of this error has been fixed. Coming in next update.
