### ISSUE TITLE
Building native extensions on Windows needs better user experience

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1251]
Currently this is what is shown. The editor window shows that it is not responding, mouse cursor icon does change to progress/wait.

![2017-10-02 15_10_47-](https://user-images.githubusercontent.com/409170/31101779-ff4a5524-a783-11e7-8000-d54408728bbd.png)

 It should not make the editor window unresponsive, and it would be better if there was a cancel-able dialog which shows the progress.

![2017-10-02-15_14_50-2017-10-02-15_14_06-defold-editor-2 0---monarch png- -66](https://user-images.githubusercontent.com/409170/31102160-d0947f3c-a785-11e7-92c2-4d804cae71ce.png)

**Comment by AGulev** [comment]
@subsoap 
 looks like this issue was solved in 1.2.144 https://forum.defold.com/t/defold-1-2-144-has-been-released/37962 ?
DEFEDIT-1497 - Fixed : Don’t block UI while building native extensions

**Comment by markusgustavssonking** [comment]
@subsoap Is this still an issue?

**Comment by subsoap** [comment]
@markusgustavssonking it's better now for sure.
