### ISSUE TITLE
Multiline quotes not styled properly in editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1252]
![2017-10-02 17_52_00-defold editor 2 0 - defstring](https://user-images.githubusercontent.com/409170/31105620-76c121da-a79a-11e7-9b0b-6aff580e006f.png)

![2017-10-02 17_52_44-defold editor 2 0 - defstring](https://user-images.githubusercontent.com/409170/31105635-865da3de-a79a-11e7-9724-17e8679805f1.png)

**Comment by erikangelin-king** [comment]
Fixed in new code editor
