### ISSUE TITLE
Add fixed width font for console printing

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1253]
The editor needs a fixed width font option too.

**Comment by erikangelin-king** [comment]
> The editor needs a fixed width font option too.
What do you mean?

**Comment by subsoap** [comment]
I mean the code editor.

![2017-10-03 01_28_02-lnpoverlaywindow](https://user-images.githubusercontent.com/409170/31116227-220d1302-a7da-11e7-96b8-e70a5f92b70e.png)

**Comment by erikangelin-king** [comment]
Thats awful! Will be fixed as part of our push for a better text editor.

**Comment by AGulev** [comment]
@erikangelin-king  @subsoap looks good in updated text editor
![2018-01-08_21-05-27](https://user-images.githubusercontent.com/2209596/34684885-aadeca20-f4b7-11e7-8104-de9f90dbf04d.jpg)
