### ISSUE TITLE
Support Import/Export of Tiled Map Editor Tilemaps

### ISSUE THREAD

**Issue by brian3kb** [defold/editor2-issues#1256]
The current tilemap file format can't be opened in third-party map/image editing tools such as Tiled or PyxelEdit. Could support be added? Or are there plans to significantly improve the Tilemap editing capabilities of Editor2?

**Comment by subsoap** [comment]
Tiled can export its native format to Defold's format when you enable the extension for it.

You can also import Tiled data (my preferred way) directly while running the game into Defold tilemaps. This way you export in Tiled to a lua file and then can also selectively load stuff like entities for scripting.

Use Tiled, don't use the built in tilemap editor for now except to setup your tilespace dimensions (or use text editor to do that).

**Comment by brian3kb** [comment]
Thanks! I completely missed the defold export extension in Tiled.
