### ISSUE TITLE
Editor background is red on win32 version

### ISSUE THREAD

**Issue by mohannadAbbady** [defold/editor2-issues#1259]
![capture](https://user-images.githubusercontent.com/19725566/31222210-0bde9cbc-a9cf-11e7-88a2-1ad37b09508c.PNG)

### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold  #sha</td><td>bcc9ce6ad9fa2ecf200dcd2fdf5745ca3af63af4</td></tr>
<tr><td>Build time</td><td>2017-10-04T13:38:12.950044</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi! Could you try updating the drivers for your graphics card? Usually when something strange happens in the Scene View it can be fixed by updating the drivers.

**Comment by erikangelin-king** [comment]
@mohannadAbbady Did updating the drivers help? Please reopen if this is still an issue!
