### ISSUE TITLE
Alt+Up and alt+Down doesn't work on windows

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1260]
I try to move nodes by Alt+Up and Alt+Down - it doesn't work. 
Reproduced only on Windows PC
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.114</td></tr>
<tr><td>Defold sha</td><td>0a4c973befa772ea142a9d0f02bdcc696cd5041e</td></tr>
<tr><td>Build time</td><td>2017-09-27T15:26:14.998723</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 376.51</td></tr>
<table>

**Comment by ragnard-king** [comment]
Have you tried upgrading to latest version? We fixed a bug related to this on the 27/9. I can't reproduce on Windows 10, tried moving GUI node up/down.

**Comment by AGulev** [comment]
@ragnard-king you right, sorry for that.

**Comment by ragnard-king** [comment]
No problem, thanks for the report, glad it was already resolved!
