### ISSUE TITLE
Can't select atlas file from a sprite component on Linux

### ISSUE THREAD

**Issue by andsve** [defold/editor2-issues#1261]
### Expected behaviour
Should be able to select the atlas file on a inline sprite component.

### Actual behaviour
"java.lang.IllegalStateException: showAndWait is not allowed during animation or layout processing"

### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-04T13:38:18.277809</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Bay Trail </td></tr>
<tr><td>Defold sha</td><td>bcc9ce6ad9fa2ecf200dcd2fdf5745ca3af63af4</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 13.0.6</td></tr>
<tr><td>OS version</td><td>4.11.0-kali1-amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=dc342dcb9afd4d1e92de4fff9d028dee'>dc342dcb9afd4d1e92de4fff9d028dee</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@andsve Can't reproduce, please reopen if it happens again.

**Comment by RagnarSvenssonKing** [comment]
I managed to reproduce and fix it.
