### ISSUE TITLE
Defold try to build unused collection.

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1262]
### Expected behaviour
If some collection never use, it shouldn't build.
### Actual behaviour
When I try to make macos or windows (mobile bundles works fine) bundle defold try to build collection that never used. This collection is technical for testing and have errors, and I can't make a bundle without fixes these bugs.

### Steps to reproduce
1. Create two collection Main and Test (Test never uses)
2. Create test object
3. Add this object to Test collection
4. Remove object from the disk (it will make an error in Test collection)
5. Try to make bunlde macos or windows (mobile works fine)
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>09d608ee477790864a9560dfc2fc3a064f2d48e7</td></tr>
<tr><td>Build time</td><td>2017-10-05T09:43:57.389621</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by matgis-king** [comment]
This is an unfortunate result of us reusing the "Bob" bundling system from the old editor. Bob does not care if a resource is used - it will build everything. The plan is to eventually port everything to the new editor 2 build system, but it might take some time until we're able to do so.
