### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by MalekBakeer** [defold/editor2-issues#1267]
### Expected behaviour
To build normally for testing
### Actual behaviour
It show an error when building while the last build was running
### Steps to reproduce
Build with ctr+b and rebuild again
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>09d608ee477790864a9560dfc2fc3a064f2d48e7</td></tr>
<tr><td>Build time</td><td>2017-10-05T09:43:57.389621</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4550</td></tr>
<table>

**Comment by matgis-king** [comment]
What was the error?

**Comment by MalekBakeer** [comment]
It gives me only that the build timed out, it should do something or replace the last build with the new one

**Comment by erikangelin-king** [comment]
Can't repro this, but please reopen if it happens again!
