### ISSUE TITLE
TEXC_Create Error

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1271]
I recieve an error for some png when try to make any bundle on macos (on windows all fine):
![2017-10-06_19-22-25](https://user-images.githubusercontent.com/2209596/31287940-b3b99228-aacb-11e7-8b3a-29cd118bd414.png)
![2017-10-06_19-26-33](https://user-images.githubusercontent.com/2209596/31288111-48613de0-aacc-11e7-857e-d15fc7978e4f.png)

Project where I receive an error for example https://github.com/subsoap/defos/tree/dev/removeffi

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>056073b7b5601fb4a3b29eb60af5b291da3caf07</td></tr>
<tr><td>Build time</td><td>2017-10-06T14:46:52.793727</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This should be fixed on Mac and Windows now, we're working on Linux. Please reopen otherwise!
