### ISSUE TITLE
trying to build admob extension sample project.

### ISSUE THREAD

**Issue by amanadriano** [defold/editor2-issues#1273]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>09d608ee477790864a9560dfc2fc3a064f2d48e7</td></tr>
<tr><td>Build time</td><td>2017-10-05T09:43:57.389621</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.17</td></tr>
<table>

**Comment by matgis-king** [comment]
https://forum.defold.com/t/problem-using-admob-extension/12216

**Comment by matgis-king** [comment]
Was this for editor 2 hanging when bundling?

**Comment by erikangelin-king** [comment]
@amanadriano I'm going through old issues, was this ever solved?

**Comment by amanadriano** [comment]
heyllo @erikangelin-king i ended up using unity ads. but would love to be able to implement admob instead.

**Comment by erikangelin-king** [comment]
Closing this, reopen or ask on forum if you need any help.
