### ISSUE TITLE
Unable to bundle

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1276]
### Expected behaviour
I should be able to bundle

### Actual behaviour
I'm not able to bundle. I get a com.dynamo.bob.TexcLibrary.TEXC_Create(IIIILjava/nio/Buffer);com/sun/jna/Pointer; error on any atlas. I've tried multiple projects. I have also downloaded and installed a fresh version without success.

### Steps to reproduce
Download/update to the latest version
Bundle a project containing an atlas
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>056073b7b5601fb4a3b29eb60af5b291da3caf07</td></tr>
<tr><td>Build time</td><td>2017-10-06T14:45:46.853471</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by AGulev** [comment]
Same thing https://github.com/defold/editor2-issues/issues/1271

**Comment by matgis-king** [comment]
Closing as duplicate.
