### ISSUE TITLE
Show hidden fields in game.project

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1277]
Some fields [are documented as hidden in game.project](https://www.defold.com/manuals/project-settings/#_project). I think we should expose these and make them visible. It's very unfriendly for a new user to have to open game.project as a text file to make certain changes

**Comment by AGulev** [comment]
We have no hidden resources anymore 
https://github.com/defold/doc/commit/5f37e463218c73448091e3455a36488d6861a327#diff-5916bc917eaa44187fd341fbc114a287
