### ISSUE TITLE
Improve gamepad detection / callbacks (DEF-3349)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1279]
- Allow to setup callbacks when gamepads are connected or disconnected
- Get list of all gamepads connected
- Allow gamepads to be connected while game is running

Right now there is no way to detect a gamepad until some input happens. Gamepads must also be connected before game runs. Both of these are bad for PC game releases.

**Comment by britzl** [comment]
DEF-3349

**Comment by AGulev** [comment]
https://forum.defold.com/t/gamepad-detection-def-3349/29014

**Comment by AGulev** [comment]
Solved in 1.2.157 https://forum.defold.com/t/defold-1-2-157-has-been-released/55935
