### ISSUE TITLE
Cannot build project after last update

### ISSUE THREAD

**Issue by linuxfranz** [defold/editor2-issues#1286]
### Expected behaviour
Project -> Build (CTRL B) builds project

### Actual behaviour
Error dialogue pops up:
java.lang.NoClassDefFoundError:Could not initialize class com.defold.libs.TexcLibrary

### Steps to reproduce
Start build

<hr/>

<table>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-06T14:46:52.793727</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 515 (Skylake GT2) </td></tr>
<tr><td>Defold sha</td><td>056073b7b5601fb4a3b29eb60af5b291da3caf07</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.2.1</td></tr>
<tr><td>OS version</td><td>4.13.4-1-default</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6d7e3f3ee7024eb4a0a5de2165e7fa4d'>6d7e3f3ee7024eb4a0a5de2165e7fa4d</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by linuxfranz** [comment]
Exception in Log:

2017-10-08 11:02:20.503 465088 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 98}
java.lang.UnsatisfiedLinkError: Unable to load library 'texc_shared': Native library (linux-x86-64/libtexc_shared.so) not found in resource path ([file:/home/franz/Software/Defold/packages/defold-056073b7b5601fb4a3b29eb60af5b291da3caf07.jar])
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:271)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:398)
	at com.sun.jna.Native.register(Native.java:1396)
	at com.sun.jna.Native.register(Native.java:1156)
	at com.defold.libs.TexcLibrary.<clinit>(TexcLibrary.java:17)
	at com.defold.editor.pipeline.TextureGenerator.generateFromColorAndFormat(TextureGenerator.java:172)
	at com.defold.editor.pipeline.TextureGenerator.generate(TextureGenerator.java:320)

**Comment by TedCassirer** [comment]
Same issue for me

**Comment by malachany** [comment]
Same issue as well

**Comment by malachany** [comment]
Part of the issue looks to be the path. Mine is looking in:
```linux-x86-64/libtexc_shared.so```

However, that path does not exist: (showing only important part of tree)
```
~/.Defold/unpack/056073b7b5601fb4a3b29eb60af5b291da3caf07 $ tree 
.

├── x86_64-linux
│   ├── bin
│   │   ├── dmengine
│   │   ├── dmengine_release
│   │   └── luajit
│   └── lib
│       ├── libgluegen-rt.so
│       ├── libjogl_desktop.so
│       ├── libjogl_mobile.so
│       ├── libnativewindow_awt.so
│       ├── libnativewindow_x11.so
│       ├── libnewt.so
│       ├── libparticle_shared.so
│       ├── libPVRTexLib.so
│       └── libtexc_shared.so
├── x86-linux
│   ├── bin
│   │   ├── dmengine
│   │   ├── dmengine_release
│   │   └── luajit
│   └── lib
│       ├── libgluegen-rt.so
│       ├── libjogl_desktop.so
│       ├── libjogl_mobile.so
│       ├── libnativewindow_awt.so
│       ├── libnativewindow_x11.so
│       ├── libnewt.so
│       ├── libparticle_shared.so
│       ├── libPVRTexLib.so
│       └── libtexc_shared.so
```

If I copy one of these to linux-x86-64, I get:
```java.lang.NoClassDefFoundError: Could not initialize class com.defold.libs.TexcLibrary```

**Comment by erikangelin-king** [comment]
Hi! Thanks all for reporting! We will look into this properly tomorrow. Meanwhile you can try downloading an earlier version, just don't update :)

http://d.defold.com/editor2/7263fbd517ba5d85a3fa463b122266bf7d7200a4/editor2/Defold-x86_64-darwin.dmg
http://d.defold.com/editor2/7263fbd517ba5d85a3fa463b122266bf7d7200a4/editor2/Defold-x86-win32.zip
http://d.defold.com/editor2/7263fbd517ba5d85a3fa463b122266bf7d7200a4/editor2/Defold-x86_64-linux.zip

**Comment by erikangelin-king** [comment]
Hi again! The corresponding issue for Mac and Windows has been fixed, but some work remains for Linux. The underlying reason for the error is that as part of native extension support for linux we are updating to a newer version of pvrtexlib and bumping the minimum requirement to ubuntu 16. Apparently, native library loading works a bit differently.

**Comment by malachany** [comment]
Thanks for the update and quick response.

**Comment by erikangelin-king** [comment]
Suspecting this is due to some missing libraries / incompatibility with your linux flavour, could you try running ldd on libPVRTexLib.so?

**Comment by mathiaswking** [comment]
If you run "ldd libPVRTexLib.so" from a Terminal, what is the output?
I wonder if the shared library is incompatible with the OS you are running on. (We've just updated our build system to use Ubuntu 16.04)

**Comment by malachany** [comment]
I can test tonight when I get home from work, if no one has done this by then.

**Comment by erikangelin-king** [comment]
This is (fingers crossed!) fixed in the latest update!

**Comment by linuxfranz** [comment]
Just when I wanted to check with ldd :-P

Yes, works for me with the latest update. Thanks a lot!
