### ISSUE TITLE
Freezes on 2-step

### ISSUE THREAD

**Issue by 5252ntf** [defold/editor2-issues#1288]
I am totally unable to sign in. 
I get stuck on the following screen.
![image](https://user-images.githubusercontent.com/32651888/31355450-e98375c8-acff-11e7-9035-7ffd89ea9490.png)
I have already hit yes.
If try another way i get stuck on the next screen.
![image](https://user-images.githubusercontent.com/32651888/31355479-0f4eeabc-ad00-11e7-909f-a51ce296e6de.png)
If i click on any of the options it highlights them and then does nothing.

**Comment by brian3kb** [comment]
I'm seeing the same thing, tap 'Yes' on my phone, but the 2-step doesn't progress, selecting other options does nothing.

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>4ec5524a33497148aed335e8fb58bbd3ea4ed3d6</td></tr>
<tr><td>Build time</td><td>2017-10-09T13:27:07.344940</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 530</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4627</td></tr>
<table>

**Comment by Teddy-Schmitz** [comment]
Same issue

Defold version | 1.2.115
-- | --
Defold sha | 4ec5524a33497148aed335e8fb58bbd3ea4ed3d6
OS name | ArchLinux
OS arch | amd64
Java version | openjdk version "1.8.0_144-b01"

**Comment by ragnard-king** [comment]
Thanks for the report! We're working on a fix where we will use the system web browser for login, instead of the embedded one, which has proven very brittle wrt. googles login process.

**Comment by ragnard-king** [comment]
We've now changed the login process to use the system browser instead of the embedded one which should resolve this issue. Available in an update within the hour.
