### ISSUE TITLE
Switching branch causes shuffling of .render material assignments

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1289]
May also happen when you remove a material assigned to .render.

### Expected behaviour
File is not messed up when switching between branches.

### Actual behaviour
Wrong material assigned to the wrong name

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>e2dfa562149fd6a3610466c365d9f6b9faada7de</td></tr>
<tr><td>Build time</td><td>2017-10-10T10:54:24.549713</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<table>

**Comment by matgis-king** [comment]
Can you provide repro steps?

**Comment by Malmer** [comment]
I can show it happen in our project. Not sure if it is universal.

**Comment by Malmer** [comment]
Repro case that happens in our project:

* Open up the .render file
* Have a bunch of materials in the render file (we have 10)
* Delete one of them (the actual .material file, not the entry in the render file)
* Do a revert on the deletion
-> The material assignments are shuffled around in the render file.

**Comment by ragnard-king** [comment]
Fixed, coming in next update.
