### ISSUE TITLE
ParticleFX simulation breaks with a second project

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#129]
### Expected behaviour

Can play particle effects simultaneously in multiple projects. 
### Actual behaviour

Particle effect stops playing (no particles rendered) when a particle effect is opened in a second project. After that, no particle effects are visible in either project when pressing play.
### Steps to reproduce
- create a particlefx
- verify that it plays correctly
- stop particlefx
- open a another project
- create a particlefx
- try to play particlefx in either project

<hr/>

Defold version: dev
Defold sha: 
Platform: Mac OS X 10.11.6 (x86_64)
Java version: 1.8.0_101-b13

**Comment by erikangelin-king** [comment]
Can no longer open multiple projects...
