### ISSUE TITLE
Unable to bundle APK containing an Android extension [DEFEDIT-1170]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1295]
### Expected behaviour
It should be possible to bundle an Android app in a project containing one or more native extensions.

### Actual behaviour
The bundle process fails. The reason seems to be because the native extension builder generates a warning ([options] boostrap class path not set in conjunction with -source 1.6) which is treated as an error by the bundle pipeline in Editor 2.

### Steps to reproduce
Bundle an Android project containing a native extension. For instance this project: https://github.com/britzl/defold-gyro

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>3f8b2ee4616a260cd374cd96c7cb1a1b26371f37</td></tr>
<tr><td>Build time</td><td>2017-10-11T08:08:59.734006</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<table>

**Comment by matgis-king** [comment]
I did a quick test, but was unable to reproduce the issue. Can you provide detailed repro steps?

**Comment by matgis-king** [comment]
Note: I was able to reproduce using the updated repro steps attached to DEFEDIT-1170 in our internal issue tracker.

**Comment by mathiaswking** [comment]
A fix is in review right now.

**Comment by matgis-king** [comment]
@mathiaswking Do you know if the fix has been merged yet?

**Comment by dapetcu21** [comment]
Any update on this? I'm still having this issue.

**Comment by britzl** [comment]
Fixed.
