### ISSUE TITLE
Bundling will cause gui spines with skin set to "default" to not be visible [DEFEDIT-1167]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1296]
Works when in Build and Run mode. When bundling it becomes hidden.

Repro:
Gui spine
Set skin to "Default"
Bundle

**Comment by matgis-king** [comment]
Same issue as #1049.

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/html5-runner-tutorial-missing-frog/12662/11
