### ISSUE TITLE
libtexc_shared.so not found in resource jar

### ISSUE THREAD

**Issue by marsgpl** [defold/editor2-issues#1297]
### Expected behaviour
By pressing "Build" on fresh installation of defold 2 editor on newly created project I expect something like running blank-screen app.

### Actual behaviour
Doesn't compile

### Steps to reproduce
1. download defold 2 on arch linux
2. run defold 2
3. create new fresh project
4. try to build that project
5. does not compile

<hr/>

<table>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-11T16:53:26.520151</td></tr>
<tr><td>GPU</td><td>GeForce GTS 450/PCIe/SSE2</td></tr>
<tr><td>Defold sha</td><td>f0484ab5c778714df1ffa3136d41c54b6ffc9d13</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 387.12</td></tr>
<tr><td>OS version</td><td>4.13.4-1-ARCH</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2e7b22d708324fa187eebde97c808d6e'>2e7b22d708324fa187eebde97c808d6e</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! This should be fixed in the latest update :)
