### ISSUE TITLE
Opening project without modifying anything shows files changed

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#13]
(reported by @gregor-king-gullwi)

Opening the project (Mac OS) without modifying anything shows several changed files, but with no apparent diff (Line endings perhaps?)

![image](https://cloud.githubusercontent.com/assets/20399970/17628022/5a087de0-60ab-11e6-9173-ff3f794a08a0.png)

**Comment by gregor-king-gullwi** [comment]
Just confirming that this is still an issue in the latest version (1.2.92, 76e7f6a4e6707b8c2a560d35eb3f37eab1aa8075)

**Comment by ragnard-king** [comment]
@gregor-king-gullwi What is the output of `git config --global core.autocrlf` on your machine?

**Comment by gregor-king-gullwi** [comment]
gregor.gullwi$ git config --global core.autocrlf
input

**Comment by ragnard-king** [comment]
@gregor-king-gullwi A fix for this has now been merged and should be available in the latest update. Would you be able to confirm if the issue has been resolved?

**Comment by gregor-king-gullwi** [comment]
Fixed comfirmed!

**Comment by ragnard-king** [comment]
Thanks for reporting and re-testing! Closing.
