### ISSUE TITLE
Where did the 3d collision shapes go?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1302]
These three shapes are flat 2d. Are they 3d shapes when using 3d physics?

![2017-10-11 19_39_11-defold editor 2 0 - defstring](https://user-images.githubusercontent.com/409170/31476581-e65853ce-aebb-11e7-91ad-6085e8bcd909.png)

Would be useful to be able to define .dae models as collision shapes when using 3d physics. For characters you want the pill shape usually, but for ground or a prop you may want the actual shape of its geometry or a low poly version for collision.

**Comment by ragnard-king** [comment]
The editor currently always draws the shapes in 2D. If you've set the [physics type to 3D in your game.project](https://www.defold.com/manuals/project-settings/#_physics) the shapes are indeed 3D in the engine, so in that case we should draw them in 3D in the editor too.

**Comment by subsoap** [comment]
@ragnard-king Still an issue, makes trying to make 3d scenes quite tedious...

![2018-07-04 16_04_49-first person shooter example for defold](https://user-images.githubusercontent.com/409170/42295893-ff52c576-7fa3-11e8-9d69-dbe654495dfe.png)
![2018-07-04 16_04_37-defold editor 2 0 - first person shooter example for defold](https://user-images.githubusercontent.com/409170/42295894-ff6a3972-7fa3-11e8-935f-5b1611725c13.png)

**Comment by ooploopl-** [comment]
It is really hard to edit shapes as billboards. Please implement 3d collision shapes in viewport.

**Comment by AGulev** [comment]
Duplicate https://github.com/defold/editor2-issues/issues/1123
