### ISSUE TITLE
Error after moving files on disk

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1304]
Moved files on disk

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-09T13:27:07.344940</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>4ec5524a33497148aed335e8fb58bbd3ea4ed3d6</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=bf32002095ed45bc9b48996eb7ac27ca'>bf32002095ed45bc9b48996eb7ac27ca</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
https://sentry.io/defold/editor2/issues/368929201/events/7945720511/

**Comment by erikangelin-king** [comment]
Hi @Jerakin ! The stack trace of the error is no longer available in Sentry, so I don't have much to go on. Closing, but please reopen if you can repro!
