### ISSUE TITLE
Editor stalls for several seconds when the window is resized or when Console pane is resized

### ISSUE THREAD

**Issue by RogerLevy** [defold/editor2-issues#1305]
Defold Editor 1.2.115, Windows 10.  When I resize the editor window it takes several seconds for it to update and become responsive.  Same when resizing the Console pane.

**Comment by erikangelin-king** [comment]
Just to make sure, this is in editor 2, right? Are you working on a large project? Many dependencies?

**Comment by RogerLevy** [comment]
Yes editor 2. This happens regardless of the size of a project. It can be a
blank project.

**Comment by RogerLevy** [comment]
The issue seems to have resolved itself after a reboot.

**Comment by ragnard-king** [comment]
@RogerLevy Thanks for the update. I'll close this for now, but please re-open if it happens again.
