### ISSUE TITLE
Can't select XML file for android.manifest attribute

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#1312]
1. Create `AndroidManifest.xml` file in project
2. Open `game.project`
3. Browse for `android.manifest` resource
4. Can't select `AndroidManifest.xml`

**Comment by ragnard-king** [comment]
Fixed, coming in next update.

**Comment by AGulev** [comment]
I think you can close https://github.com/defold/editor2-issues/issues/791  too

**Comment by ragnard-king** [comment]
@AGulev Oh, right, thanks! Two in one smäll as we say in swedish.
