### ISSUE TITLE
Error after build

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1313]
1. Tweaked a particlfx (mainly the curves of it)
2. pressed build
3. went afk
4. got back - had error

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-12T15:52:40.077189</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold sha</td><td>4b23eb23a8da84f8c7dc26a219d6898af08b5bbd</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=1638d9f01dd24415a357efa92d8b5215'>1638d9f01dd24415a357efa92d8b5215</a></td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
https://sentry.io/defold/editor2/issues/371176158/events/8072729150/

**Comment by subsoap** [comment]
#980 maybe?

**Comment by erikangelin-king** [comment]
Haha, nice guess but no, this was an OOM/GC overhead limit exceeded.

**Comment by ragnard-king** [comment]
Hey @Jerakin,

Did you successfully build the project before tweaking the particlefx, or was this the first time during that editor session that you tried to build? Are you able to re-produce the issue?

**Comment by erikangelin-king** [comment]
Closing this as can't repro, but we're well aware that we need to look over memory usage. Please reopen if it happens again.
