### ISSUE TITLE
Outdated lua suggest

### ISSUE THREAD

**Issue by 243083df** [defold/editor2-issues#1314]
### Expected behaviour
Suggest use `is_enabled`
### Actual behaviour
Suggest use `get_enabled`
### Steps to reproduce
Create GUI. Create box with id `go`.
Append gui script to gui with code in `init` function:
```
local node = gui.get_node("go")
print(node.enabled)
```
In console output will be suggest:
``
ERROR:SCRIPT: /scripts/main.gui_script:19: Illegal operation, try gui.get_enabled(<node>)
``
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold sha</td><td>f85872026c49ff4fb5b658c2cce9730e9ab825e1</td></tr>
<tr><td>Build time</td><td>2017-10-16T15:44:35.985950</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 6900 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1151.1008</td></tr>
<table>

**Comment by britzl** [comment]
That's a generic recommendation without any real intelligence behind it:

`return luaL_error(L, "Illegal operation, try %s.get_%s(<node>)", LIB_NAME, key);
`
Where key is whatever you tried to read. 

`print(node.foobar) -> Illegal operation, try gui.get_foobar(<node>)`
