### ISSUE TITLE
Something wrong with constant-type-worldview?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1323]
I'm setting up a spherical environment map shader which uses constant-type-worldview but stationary models appear to have their texture rotated at certain view orientations.

See here https://gfycat.com/gifs/detail/SeveralBothBarnswallow

This version of this project has the problem example https://github.com/subsoap/defmaterial/tree/ce645a5e06d004be32d7adb0a2f876135f0dd612

**Comment by subsoap** [comment]
It looks like it has something to do with when multiple models with the same material setup are in the same scene and using these values. Maybe Sven can help.

**Comment by matgis-king** [comment]
@andsveking Any ideas?

**Comment by andsveking** [comment]
@subsoap Is this still an issue? I tried the version you linked in the latest Ed2 and couldn't reproduce the issue. 🙁

**Comment by subsoap** [comment]
@andsveking I tested that version of the project and don't see the same kind of effect while rotating around so must have been fixed at some point!

**Comment by andsveking** [comment]
Good, thanks! Closing this issue for now, let us know if you happen to experience it again.
