### ISSUE TITLE
Space as first character on resource selector produces dialog error

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1327]
Type space as the first character produces error. Multiple spaces can be added, with each deletion of a space error happens too.

![2017-10-18 21_11_24-defold editor 2 0 - defmaterial](https://user-images.githubusercontent.com/409170/31753938-fb7e0568-b448-11e7-9269-2364051908cf.png)

![2017-10-18 21_11_33-defold editor 2 0 - defmaterial](https://user-images.githubusercontent.com/409170/31753940-fdae03ec-b448-11e7-9696-649d78f47736.png)

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.116</td></tr>
<tr><td>Build time</td><td>2017-10-18T13:54:25.663375</td></tr>
<tr><td>GPU</td><td>GeForce GTX 750/PCIe/SSE2</td></tr>
<tr><td>Defold sha</td><td>7032d32d861f09f2293193fabc588efcc1220756</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 387.92</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6e9c56ee75d748afbc31cd1c0311ce69"'>6e9c56ee75d748afbc31cd1c0311ce69</a></td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed, coming in next update.
