### ISSUE TITLE
Win 10 - Cannot open Defold.exe

### ISSUE THREAD

**Issue by AJirenius** [defold/editor2-issues#133]
Installed latest version of Editor2 on new Windows 10 computer (on desktop, no weird pathname)
Tried running exe but it closed before I could read any terminal.

From terminal, located in Defold root folder I tried:
_defold.exe_
gave error message:
 **"FATAL:TOOLS: Failed to load config file '/config' (-1)"**

Also tried 
_Defold.exe C:\Users\Andreas\Desktop\Defold\_

same error message. 

Ive been checking security settings and cannot find any problems.

**Comment by ragnard-king** [comment]
Hi @AJirenius,

Thanks for the report, we're investigating.

Is there a "config" file in your Defold root folder?

**Comment by mathiaswking** [comment]
Is this similar to https://github.com/defold/editor2-issues/issues/105 ?

I.e. could you start with: C:\Users\Andreas\Desktop\Defold\defold.exe ?

**Comment by AJirenius** [comment]
Yes the config file is there
When starting with full path from root I get this instead:


DEBUG:TOOLS: arg 0: C:/Users/Emelie/Desktop/Defold/packages/jre/bin/java
DEBUG:TOOLS: arg 1: -cp
DEBUG:TOOLS: arg 2: C:/Users/Emelie/Desktop/Defold/packages/defold-e799db0c48897c3041f912f15cd649ee96ffc39b.jar
DEBUG:TOOLS: arg 3: -Xms1024m
DEBUG:TOOLS: arg 4: -Xmx1400m
DEBUG:TOOLS: arg 5: -Ddefold.resourcespath=C:/Users/Emelie/Desktop/Defold
DEBUG:TOOLS: arg 6: -Ddefold.version=1.2.90
DEBUG:TOOLS: arg 7: -Ddefold.sha1=e799db0c48897c3041f912f15cd649ee96ffc39b
DEBUG:TOOLS: arg 8: -Djava.ext.dirs=C:/Users/Emelie/Desktop/Defold/packages/jre/lib/ext
DEBUG:TOOLS: arg 9: -Djava.net.preferIPv4Stack=true
DEBUG:TOOLS: arg 10: -Dsun.net.client.defaultConnectTimeout=30000
DEBUG:TOOLS: arg 11: -Dsun.net.client.defaultReadTimeout=30000
DEBUG:TOOLS: arg 12: -Djogl.texture.notexrect=true
DEBUG:TOOLS: arg 13: com.defold.editor.Start
DEBUG:TOOLS: arg 14: (null)
DEBUG:TOOLS: "C:/Users/Emelie/Desktop/Defold/packages/jre/bin/java" -cp C:/Users/Emelie/Desktop/Defold/packages/defold-e799db0c48897c3041f912f15cd649ee96ffc39b.jar -Xms1024m -Xmx1400m -Ddefold.resourcespath=C:/Users/Emelie/Desktop/Defold -Ddefold.version=1.2.90 -Ddefold.sha1=e799db0c48897c3041f912f15cd649ee96ffc39b -Djava.ext.dirs=C:/Users/Emelie/Desktop/Defold/packages/jre/lib/ext -Djava.net.preferIPv4Stack=true -Dsun.net.client.defaultConnectTimeout=30000 -Dsun.net.client.defaultReadTimeout=30000 -Djogl.texture.notexrect=true com.defold.editor.Start
Error occurred during initialization of VM

**Comment by AJirenius** [comment]
Any specific Java version I need to have installed?

**Comment by erikangelin-king** [comment]
Jre is bundled so shouldn't be a problem. I just tried downloading that version on a Win10 machine, I get the same output but then it starts normally. Looking into this!

**Comment by erikangelin-king** [comment]
Could you give me some system specs, output of systeminfo?

**Comment by AJirenius** [comment]
Host Name:                 DESKTOP-OFU4EG0
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.14393 N/A Build 14393
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Emelie
Registered Organization:
Product ID:                00326-30000-00001-AA980
Original Install Date:     2016-10-17, 18:56:09
System Boot Time:          2016-10-18, 17:47:30
System Manufacturer:       ASUSTeK Computer INC.
System Model:              CG8350
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 42 Stepping 7 GenuineIntel ~1600 Mhz
BIOS Version:              American Megatrends Inc. 1402, 2011-09-29
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             sv;Swedish
Input Locale:              sv;Swedish
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     12 269 MB
Available Physical Memory: 8 937 MB
Virtual Memory: Max Size:  14 701 MB
Virtual Memory: Available: 10 736 MB
Virtual Memory: In Use:    3 965 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-OFU4EG0
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB3176935
                           [02]: KB3176937
                           [03]: KB3194343
                           [04]: KB3199209
                           [05]: KB3194798
Network Card(s):           2 NIC(s) Installed.
                           [01]: Realtek PCIe GBE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: D-Link DWA-140 RangeBooster N USB Adapter(rev.B2)
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.62
                                 [02]: fe80::7cf8:53c2:925a:dcc7
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by erikangelin-king** [comment]
Plenty of Memory :)
Could you try running the following command from the end of the debug output to see if we get any more info:

C:/Users/Emelie/Desktop/Defold/packages/jre/bin/java -cp C:/Users/Emelie/Desktop/Defold/packages/defold-e799db0c48897c3041f912f15cd649ee96ffc39b.jar -Xms1024m -Xmx1400m -Ddefold.resourcespath=C:/Users/Emelie/Desktop/Defold -Ddefold.version=1.2.90 -Ddefold.sha1=e799db0c48897c3041f912f15cd649ee96ffc39b -Djava.ext.dirs=C:/Users/Emelie/Desktop/Defold/packages/jre/lib/ext -Djava.net.preferIPv4Stack=true -Dsun.net.client.defaultConnectTimeout=30000 -Dsun.net.client.defaultReadTimeout=30000 -Djogl.texture.notexrect=true com.defold.editor.Start

**Comment by AJirenius** [comment]
Getting the same memory error message. When setting Xms1400m down to 1024m it started the editor

**Comment by ragnard-king** [comment]
@AJirenius Some documentation hints that Xms/Xmx needs to be a multiple of 1024 (bytes). Just to test, does it work with 2048m? 4096m?

**Comment by AJirenius** [comment]
Unfortunately no. Anything to do with 32/64 bits Java? Seems like 32 bits cannot allocate much.

**Comment by erikangelin-king** [comment]
@AJirenius Yes, we only build a 32-bit version for Windows, and for some reason the jvm has trouble allocating enough memory. The long term solution is of course to build a 64-bit version.

**Comment by AJirenius** [comment]
Ok. As I change to 1024 the editor at least starts. It's enough to try it out.
Thank you for the help

**Comment by ragnard-king** [comment]
@AJirenius We now provide a 64-bit editor (and engine!) for windows, which should hopefully ahved solved this for you. Have you been given a link to a 64-bit version?

**Comment by erikangelin-king** [comment]
Closing this, feel free to reopen if you have any more problems @AJirenius.
