### ISSUE TITLE
Can't open projects from dashboard

### ISSUE THREAD

**Issue by ArtC0de** [defold/editor2-issues#1330]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold editor sha</td><td>fdbab6abdd802e25eaa3ce1e09135bd45c50dfd7</td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>Build time</td><td>2017-10-19T15:48:11.510907</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
What is the error you are getting?

**Comment by ArtC0de** [comment]
It was a Java error, solved!

2017-10-20 9:20 GMT+02:00 Ragnar Dahlén <notifications@github.com>:

**Comment by erikangelin-king** [comment]
Can't repro.
