### ISSUE TITLE
Inconsistent buffer / resource behavior between desktop and HTML5 builds

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1335]
What happens on desktop

![2017-10-20 09_49_22-defdraw](https://user-images.githubusercontent.com/409170/31832523-2b0dff84-b57c-11e7-95f6-e0d51f574be7.png)

What happens on HTML5 (undesired result)

![2017-10-20 09_50_47-defdraw](https://user-images.githubusercontent.com/409170/31832528-32e37c8e-b57c-11e7-9df5-a5e6dc6580f6.png)

This version of this project has example ready to test
https://github.com/subsoap/defdraw/tree/919b9b7fe0f85c881ca7bfb9daa3901d22ab15f3

**Comment by AGulev** [comment]
Can't reproduce 
![image](https://user-images.githubusercontent.com/2209596/69832289-b48a1d00-122d-11ea-9b56-356e951a52bb.png)

**Comment by subsoap** [comment]
It looks like the undesired result happens on macOS and HTML5 for you? 🤔 I don't even remember what this was about though now.
