### ISSUE TITLE
If delete key is pressed on keyboard on Assets view the dialog needs to respect Enter and Esc [DEFEDIT-1518]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1336]
![2017-10-22 01_21_58-defold editor 2 0 - blank project](https://user-images.githubusercontent.com/409170/31859925-7eb84cce-b6c7-11e7-930e-0a3795034258.png)

When this dialog appears the Enter key needs to be the same as OK and Esc key needs to be the same as Cancel.

**Comment by AGulev** [comment]
Related https://github.com/defold/editor2-issues/issues/142 and maybe https://github.com/defold/editor2-issues/issues/2188
@markusgustavssonking ?
