### ISSUE TITLE
Can't change file extension in rename in editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1337]
I wanted to change a txt file to an .input_binding file but instead of renaming from a .txt to .input_binding it instead just cut off the .txt extension, and renaming again in editor to add the extension does not work either.

![2017-10-22 02_24_48-defold editor 2 0 - blank project](https://user-images.githubusercontent.com/409170/31860546-58693912-b6d0-11e7-9160-d4535680ed90.png)

![2017-10-22 02_24_55-defold editor 2 0 - blank project](https://user-images.githubusercontent.com/409170/31860549-5bed673e-b6d0-11e7-9673-e04f102cb085.png)

**Comment by AGulev** [comment]
@subsoap @erikangelin-king same as https://github.com/defold/editor2-issues/issues/784
