### ISSUE TITLE
Don't represent script property values as a float if they are not represented that way in the script

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1338]
![2017-10-22 03_44_23-defold editor 2 0 - 2d fov field of view](https://user-images.githubusercontent.com/409170/31861090-68dad4e4-b6db-11e7-8a3b-e534ad427e2b.png)

![2017-10-22 03_44_11-defold editor 2 0 - 2d fov field of view](https://user-images.githubusercontent.com/409170/31861091-6c5ca476-b6db-11e7-84c3-3bd0d70ffeeb.png)

**Comment by erikangelin-king** [comment]
Quick win if simply display whole numbers as whole numbers
