### ISSUE TITLE
Defold Crashes on Ubuntu 16.04 

### ISSUE THREAD

**Issue by FlashManiac** [defold/editor2-issues#134]
First run successfully. But after editor crash not running.

[defold-crush-ubuntu-logs.zip](https://github.com/defold/editor2-issues/files/541750/defold-crush-ubuntu-logs.zip)

**Comment by ragnard-king** [comment]
Hi @FlashManiac,

Thanks for the report.

Could you provide the output of `glxinfo` (part of `mesa-utils`, `apt-get install mesa-utils`)? It looks like you are possibly hitting a bug in the nouveau driver you are using. If possible, it might be worth giving the official nvidia drivers a go to see if that solves the problem.

**Comment by ragnard-king** [comment]
@FlashManiac Also, when does it crash? From the logs, it looks like it starts correctly but then crashes when you open an asset in the scene view. Is that correct?

**Comment by FlashManiac** [comment]
Old versiuon of Defold works nice.

Yes, first when I imported my project and opened scene - editor crushed. And after when I start editor - crush.

My glxinfo : 
[glxinfo.txt](https://github.com/defold/editor2-issues/files/542020/glxinfo.txt)

**Comment by ragnard-king** [comment]
@FlashManiac We've identified the problem and are working on a solution. Will let you know when a fix is available.

**Comment by FlashManiac** [comment]
Thank You!

**Comment by ragnard-king** [comment]
@FlashManiac Can you send me (Ragnar_Dahlen) a message on the defold forum and I'll send you a new link for editor2 which should have this bug fixed.

**Comment by ragnard-king** [comment]
Closing as it should be solved and I haven't heard back. Feel free to re-open if the issue persists.
