### ISSUE TITLE
Tooltip for builtin paths shows as blank

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1341]
By the way make the path show faster not require so long to hover!

What happens when you hover a tab to see the path of a builtin file

![2017-10-22 14_28_57-defold editor 2 0 - 2d fov field of view](https://user-images.githubusercontent.com/409170/31866515-6580e4dc-b735-11e7-8c66-9a00f44f4881.png)

**Comment by Jerakin** [comment]
https://github.com/defold/editor2-issues/issues/1161

**Comment by ragnard-king** [comment]
Fix coming in next update. We will now always show the project path when hovering a tab. We've also added two additional resource commands "Copy Project Path" and "Copy Full Path", available in resource context menus.
