### ISSUE TITLE
Fail to build existing project

### ISSUE THREAD

**Issue by Wilkopolis** [defold/editor2-issues#1342]
I have a project that I have been building and testing with regularly for a few days now. However I added a proxy collection to a second collection and now it will not build. Removing the collection proxy fixes this issue. However now my project only has the one proxy.

### Expected behaviour
Attempted to Build project or even Rebuild project.

### Actual behaviour
Error window pops up:
java.lang.AssertionError: Assert failed: Cycle detected on node type editor.collection/CollectionNode and output :build-targets
(not (contains? (:in-production ctx) [node-id label]))

### Steps to reproduce
Attempt to build my project.

<hr/>

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-20T09:50:19.803349</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>Defold editor sha</td><td>aa950d4a61b1b8374135732b702aeb14289105c7</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.94</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3f5bad79c16a4c5eb1b548e8bbbe9be9"'>3f5bad79c16a4c5eb1b548e8bbbe9be9</a></td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by Wilkopolis** [comment]
I suspect this issue comes from when I have collection1 with a proxy to a collection2 which has a proxy to collection1 which has a proxy to collection2... etc.

**Comment by erikangelin-king** [comment]
You've already found the underlying reason :) Closing this as almost-duplicate-of: https://github.com/defold/editor2-issues/issues/365
