### ISSUE TITLE
error while sign in

### ISSUE THREAD

**Issue by prashanteb** [defold/editor2-issues#1347]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Defold editor sha</td><td>2346b0366a811cba06abdf9d377a907391cf9d5b</td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>Build time</td><td>2017-10-25T18:22:30.039677</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f710aa48de1d44c8b4403322d8beaa11"'>f710aa48de1d44c8b4403322d8beaa11</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! The error was a connection timeout. We should present this in a nicer way rather than popping up an error dialog. But for now, please check your network connection and firewall settings and try again :)

**Comment by erikangelin-king** [comment]
Closing, @prashanteb please reopen if you still have trouble signing in.
