### ISSUE TITLE
Random null pointer exceptions thrown from editor. 

### ISSUE THREAD

**Issue by theronpatrick** [defold/editor2-issues#1349]
### Expected behaviour
Open game object in editor

### Actual behaviour
Get error message with null pointer exception

### Steps to reproduce
Unclear unfortunately. I think it might have happened when creating an object then deleting it within the editor. Doesn't appear to have any effect on editor, just really annoying.

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-25T18:22:30.039677</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>Defold editor sha</td><td>2346b0366a811cba06abdf9d377a907391cf9d5b</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.17</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"7e52d6aced9a42ea9835c35185d7ad63"'>7e52d6aced9a42ea9835c35185d7ad63</a></td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Thanks for reporting! Just merged a fix, update coming shortly!
