### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by valmirt** [defold/editor2-issues#1350]
### Actual behaviour
In Outline of Spine Scene, a click on the hip appears this error message:
An error ocurred:
java.lang.IllegalArgumentException: Cannot format given Object as a Number

### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-25T18:22:30.039677</td></tr>
<tr><td>GPU</td><td>GeForce GT 740M/PCIe/SSE2</td></tr>
<tr><td>Defold editor sha</td><td>2346b0366a811cba06abdf9d377a907391cf9d5b</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.90</td></tr>
<tr><td>OS version</td><td>4.10.0-37-generic</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"c9f301067bc34e90ba49e4a20021453a"'>c9f301067bc34e90ba49e4a20021453a</a></td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by matgis-king** [comment]
Same issue as #1348.
