### ISSUE TITLE
Exception when deleting resource [DEFEDIT-1193]

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#1351]
### Expected behaviour

No error.

### Actual behaviour

Tab is not closed. Error when clicking in tab.

### Steps to reproduce

1. Create some resource.
2. Open resource.
3. Delete resource.

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-25T16:06:14.133732</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>Defold editor sha</td><td>d53d05f308f80239efd96491ad976a6d80efef0d</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"dde39811514749a09482cfa5c8ea4373"'>dde39811514749a09482cfa5c8ea4373</a></td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed! Update coming soon!
