### ISSUE TITLE
java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by elvenbyte** [defold/editor2-issues#1353]
### Expected behaviour
context menu
### Actual behaviour
java.lang.NullPointerException: Unknown
### Steps to reproduce
try to add component to a game object
<hr/>

<table>
<tr><td>OS name</td><td>Windows 8.1</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-26T10:20:35.159392</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4600</td></tr>
<tr><td>Defold editor sha</td><td>45ad45943a10685320d7172a285c2ba68e88268f</td></tr>
<tr><td>GPU Driver</td><td>4.2.0 - Build 10.18.10.3412</td></tr>
<tr><td>OS version</td><td>6.3</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! Can you still reproduce this? If you get the error, please press report to send us a stack trace :)

**Comment by elvenbyte** [comment]
Hi.

Ok, I'll do it.

Thanks.

David Moñino

2017-10-27 10:04 GMT+02:00 erikangelin-king <notifications@github.com>:

**Comment by erikangelin-king** [comment]
Can't repro.
