### ISSUE TITLE
Link with editor functionality in Assets/project explorer is missing

### ISSUE THREAD

**Issue by ludd1** [defold/editor2-issues#1357]
### Expected behaviour
I really would like the file open in the editor to be selected and scrolled to in the assets overview/project explorer. As the toggle "Link with editor" for this is working in editor 1.
### Actual behaviour
I open a file in the editor with the open assets command, the assets overview does not update its view.
### Steps to reproduce
Open a file in a subfolder in the project using the open assets command. 
Watch the left side assets overview and see that the file is not scrolled to, it's parent folder is not unfolded.
Try to find a button that enables this functionality and you will not find one.
![skarmavbild 2017-10-27 kl 11 55 52](https://user-images.githubusercontent.com/5894714/32098695-d6b386ba-bb0d-11e7-9ca3-452968c00033.png)
![skarmavbild 2017-10-27 kl 11 55 33](https://user-images.githubusercontent.com/5894714/32098696-d6d00baa-bb0d-11e7-88c1-b45ec5decb5b.png)

<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-24T10:20:48.077206</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>Defold editor sha</td><td>53cce46009fc5f61f0cd1e8e95717fd51a35adfc</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by ragnard-king** [comment]
This feature will be available in the next update shortly.

There's a new setting to toggle this behaviour "Track Active Tab in Asset Browser". By default it is disabled. Open preferences to change it:

![image](https://user-images.githubusercontent.com/20399970/32377257-4fe6a366-c0a7-11e7-9699-d6d26be50eb7.png)
