### ISSUE TITLE
Text editor movement shortcuts switched on windows

### ISSUE THREAD

**Issue by rgrams** [defold/editor2-issues#1358]
### Expected behaviour
Ctrl+Left or Right arrow keys is the standard shortcut for moving the cursor to the next/previous word on Windows. (see https://en.wikipedia.org/wiki/Table_of_keyboard_shortcuts#Text_editing) The Defold text editor uses Alt instead of Ctrl! 

The same is true of deleting next/previous words. It should be Ctrl+Del/Backspace, instead of Alt+Del/Backspace. 

### Actual behaviour

Defold instead uses Ctrl+Left and Right as Home and End, which causes endless frustration. _Every other text input field_ in the editor uses the correct shortcuts (Ctrl+left/right) to skip words. 

<hr>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-24T16:46:36.809213</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>Defold editor sha</td><td>e878b78bfa0e6bb21444df7e2ede86839d044dbd</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 9.18.10.3165</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by vlaaad** [comment]
[Fixed](https://forum.defold.com/t/ux-improvements-for-code-navigation-and-keyboard-shortcuts/44967)!
