### ISSUE TITLE
The graphics device does not support: glGenBuffers GPU: GDI Generic --Driver: 1.1.0

### ISSUE THREAD

**Issue by fredaudy** [defold/editor2-issues#1364]
### Expected behaviour
launch a register dashboard project

### Actual behaviour
error during the launch time dachboard project

### Steps to reproduce
open exiting project via dashboard then error,
in fact any time the editor is supposed to display something, the error occured

<hr/>

<table>
<tr><td>OS name</td><td>Windows 8.1</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-27T11:20:27.904016</td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>Defold editor sha</td><td>c365ab67009a66cefb521f560845dc42cf24a721</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>OS version</td><td>6.3</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9488cdd086fe48bdad04bb5058dcfadf"'>9488cdd086fe48bdad04bb5058dcfadf</a></td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! This usually happens with old graphics drivers, can you try updating them? Otherwise, if you're running on a virtual machine try finding a setting for opengl or "Enable 3d acceleration".

**Comment by fredaudy** [comment]
Hi!

my graphic card (nvidia gtx 660) is up to date, and it design for openGL4.3,
and i'm not on a virtual machine.

**Comment by erikangelin-king** [comment]
Hmm... The card and gl version should be enough, but the error indicates we only find "GDI Generic" drivers for your card, and these won't work. Are you using these drivers? http://www.nvidia.com/download/driverResults.aspx/125894/en-us

**Comment by fredaudy** [comment]
thank's a lot,
I was convinced that my graphic card was up to date... and i was wrong.

**Comment by erikangelin-king** [comment]
Great you got it to work :)
