### ISSUE TITLE
java.lang.ClassCastException: javafx.scene.Scene cannot be cast to javafx.scene.control.ListView

### ISSUE THREAD

**Issue by nakajinro** [defold/editor2-issues#1365]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-27T11:20:27.904016</td></tr>
<tr><td>GPU</td><td>Radeon (TM) RX 480 Graphics</td></tr>
<tr><td>Defold editor sha</td><td>c365ab67009a66cefb521f560845dc42cf24a721</td></tr>
<tr><td>GPU Driver</td><td>4.5.13464 Compatibility Profile Context 21.19.384.0</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"31a936515988492abb9a8bbfa0cc9b76"'>31a936515988492abb9a8bbfa0cc9b76</a></td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix will come in an update shortly!
