### ISSUE TITLE
Tile map issue

### ISSUE THREAD

**Issue by WIlson-YCD** [defold/editor2-issues#1367]
### Expected behaviour
Create a tile map
### Actual behaviour
errors 
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.115</td></tr>
<tr><td>Build time</td><td>2017-10-30T10:01:29.330826</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7500G</td></tr>
<tr><td>Defold editor sha</td><td>b84c6c3a4684f5852c3f3cbd18661d9ee95e61d5</td></tr>
<tr><td>GPU Driver</td><td>4.2.11481 Compatibility Profile Context</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"dc624578de734782adde8f338093e4df"'>dc624578de734782adde8f338093e4df</a></td></tr>
<tr><td>Defold engine sha</td><td>57fb5f1ad5df59262aa415f298f97694debc991c</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! It looks like you were trying to create a tilemap named <rbol.material and the "<" is not a legal file name character. We should have proper file name validation, I'll create a new issue for this. For now, don't use any weird characters :)
