### ISSUE TITLE
Find in files won’t search in libraries [DEFEDIT-1202]

### ISSUE THREAD

**Issue by saracglaser** [defold/editor2-issues#1370]
Simply can’t do without this. Half of codebase is in libraries.

**Comment by saracglaser** [comment]
DEFEDIT-1202

**Comment by Jerakin** [comment]
https://github.com/defold/editor2-issues/issues/607

It should also search resources (json files and such), especially if they are added as custom resources.

**Comment by ragnard-king** [comment]
This issue has been fixed and will be available in the next update.
