### ISSUE TITLE
runner tutorial on Defold v1.2.115, msg.post() issue

### ISSUE THREAD

**Issue by fredaudy** [defold/editor2-issues#1374]
i start the tutoriel "Runner" on the Defold's old version without any problem,
But when i switched to Defold v1.2.115, i've got error on msg.post, due to the receiver-url:

with the following syntax (in the platform.srcipt) :
`msg.post("controller#script", "delete_spawn", { id = go.get_id() })`
i've got the error :
`ERROR:GAMEOBJECT: Instance '<unknown>' could not be found when dispatching message 'delete_spawn'`

i have to specify the msg.url, to get the script running without error:
`    local controllerUrl = msg.url("level/controller#script")`
`    msg.post(controllerUrl, "delete_spawn", { id = go.get_id() })`

**Comment by erikangelin-king** [comment]
Hi!
In the runner tutorial, the platform.script says:
`msg.post("/level/controller#script", "delete_spawn", { id = go.get_id() })`
Note the leading `/level`.
Are you saying it works without the `/level` on an older version of the engine?

**Comment by fredaudy** [comment]
Hi,

yes, you're right, in the old defold version, the correct syntax, is :
`msg.post("/level/controller#script", "delete_spawn", { id = go.get_id() })`

but, in the new one, i tested several syntaxes without success :
`msg.post("/level/controller#script", "delete_spawn", { id = go.get_id() })`
`msg.post("/controller#script", "delete_spawn", { id = go.get_id() })`
`msg.post("controller#script", "delete_spawn", { id = go.get_id() })`
...

the only way, i've got the script running, it's by specifying the controller url, and using it in the msg.post 
`local controllerUrl = msg.url("level/controller#script")`
`msg.post(controllerUrl, "delete_spawn", { id = go.get_id() })`

**Comment by sicher** [comment]
There must be something else going on here. I'm testing with the latest and earlier versions. All work with this code:

```
msg.post("/level/controller#script", "delete_spawn", { id = go.get_id() })
```

Can you print "controllerURL" after constructing it and check that you see:

```
DEBUG:SCRIPT: url: [main:/level/controller#script]
```

**Comment by erikangelin-king** [comment]
@fredaudy Was this ever solved? Can I close the issue?

**Comment by fredaudy** [comment]
Yes it's ok, thank's a lot. You can close it.
