### ISSUE TITLE
Error when trying hotkeys

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1382]
Error when trying to remember the open resource hotkey
<hr/>

<table>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>Defold version</td><td>1.2.116</td></tr>
<tr><td>Build time</td><td>2017-11-03T15:05:03.116841</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>Defold editor sha</td><td>72eab2b695c8c843bb4212267f0f5eeb0bf636b2</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f463564752ce4221ac8bcfe2b68e1bca"'>f463564752ce4221ac8bcfe2b68e1bca</a></td></tr>
<tr><td>Defold engine sha</td><td>33da4aa91761d531471f364ef1693c2acec16de7</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Not much to go on here @Jerakin, but please re-report if it happens again!
