### ISSUE TITLE
This popped up

### ISSUE THREAD

**Issue by josatt** [defold/editor2-issues#1383]
### Steps to reproduce

<hr/>

<table>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>Defold version</td><td>1.2.116</td></tr>
<tr><td>Build time</td><td>2017-11-03T15:05:03.116841</td></tr>
<tr><td>GPU</td><td>GeForce GTX 770/PCIe/SSE2</td></tr>
<tr><td>Defold editor sha</td><td>72eab2b695c8c843bb4212267f0f5eeb0bf636b2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 358.50</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f09b159e113c462d819e672d1377858a"'>f09b159e113c462d819e672d1377858a</a></td></tr>
<tr><td>Defold engine sha</td><td>33da4aa91761d531471f364ef1693c2acec16de7</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @josatt! We can no longer read the stack trace of this error, so there is not much to go on. Please re-report if whatever happened happens again :)
