### ISSUE TITLE
Сrooked font in text nodes when Font includes all chars

### ISSUE THREAD

**Issue by Dragosha** [defold/editor2-issues#1392]
![2017-11-09_11-21-00](https://user-images.githubusercontent.com/842807/32591402-bf51dcd2-c540-11e7-9fcc-dc8831d17782.png)

I used RobotoSlab font (standart Android font) and enable "all chars" checkbox:
![2017-11-09_11-26-40](https://user-images.githubusercontent.com/842807/32591438-e9679cd2-c540-11e7-833b-0abcdee27158.png)

Some text fields in my GUI scenes contains text in cyrillic.

<hr/>

<table>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>Defold version</td><td>1.2.116</td></tr>
<tr><td>Build time</td><td>2017-11-03T15:05:03.116841</td></tr>
<tr><td>GPU</td><td>GeForce GT 640/PCIe/SSE2</td></tr>
<tr><td>Defold editor sha</td><td>72eab2b695c8c843bb4212267f0f5eeb0bf636b2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 385.46</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Defold engine sha</td><td>33da4aa91761d531471f364ef1693c2acec16de7</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<table>

**Comment by Insality** [comment]
Often get the same thing. Editor 2.0, MacOS 10.13. 
Glitch to this font and to normal, then drag nodes, add text labels and some more actions in editor

**Comment by AZOTKirill** [comment]
Yep, that's the problem I met too. Editor 2, macOS 10.13.
It appears when more than one text block using the some font.

**Comment by subsoap** [comment]
It has happened on Windows 10 with labels too when multiple labels use the same font

![example](https://user-images.githubusercontent.com/409170/32592396-5261bf2e-c4d8-11e7-95e5-94c8e34670ea.png)

**Comment by ragnard-king** [comment]
Thanks for the reports, will take a look at this immediately.

**Comment by subsoap** [comment]
![2017-11-09 09_05_48-defold editor 2 0 - defos](https://user-images.githubusercontent.com/409170/32618695-42648c50-c52d-11e7-9f53-25ca03cfd3f0.png)

After copying and pasting a node

**Comment by ragnard-king** [comment]
This is an issue with glyph-caching and batching. A fix is in the works.

**Comment by ragnard-king** [comment]
This issue has been fixed in the latest update.

**Comment by Dragosha** [comment]
May be it the similar issue like this is alive on elder devices. Got a report from player:

> Just wanted to show you some screenshots of the font bug that happens on my phone. Now, my phone is a little old. It's a Samsung Galaxy Ace 3 purchased in 2014, so I'm not sure if that is the reason for the problem. The fonts display perfectly on my wife's newer Huawei phone.
Also, when the font is messed up, if I navigate to another page, such as the store or leaderboards and then return to the affected page, the problem is fixed temporarily. 

screenshots: 
![screenshot_2018-03-25-11-15-40](https://user-images.githubusercontent.com/842807/37904262-a82df67c-3114-11e8-9142-ded750e6de48.png)
![screenshot_2018-03-25-11-01-28](https://user-images.githubusercontent.com/842807/37904265-aaa656c4-3114-11e8-93e9-c3c586543075.png)
![screenshot_2018-03-25-11-02-18](https://user-images.githubusercontent.com/842807/37904268-af400da6-3114-11e8-930b-1233beb9fc72.png)

@ragnard-king  I can't reproduce that and dont' getting similar reports from another players, so i just  inform you.
