### ISSUE TITLE
Can't test builds which require DLLs except for bundling, editor gives no indication of failure to launch

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1399]
I have to bundle a windows build and then copy the DLL into the folder. If I do Project -> Build nothing happens, no error is allowed to be produced.

The error before adding the DLL into the program's folder.

![2017-11-10 15_26_09-defsteam exe - system error](https://user-images.githubusercontent.com/409170/32682740-88c7af98-c62b-11e7-86ff-ee9c50d2887f.png)

I tried adding the appropriate DLL to appropriate res folder but does not seem to help in the editor but does place the DLL in the folder of the exe when bundling.

**Comment by subsoap** [comment]
Putting the dlls into the same folder as the game.project folder works although probably still want to have files within the res folder handled properly.

https://forum.defold.com/t/testing-native-extensions-which-require-dlls-with-editor-2-solved/13721/3

**Comment by ragnard-king** [comment]
Also, see https://forum.defold.com/t/testing-native-extensions-which-require-dlls-with-editor-2-solved/13721/4 for two better options.

Closing.
