### ISSUE TITLE
Relational operators < > don't have styling but >= <= do in text editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1401]
![2017-11-11 22_11_48-defold editor 2 0 - defcollide](https://user-images.githubusercontent.com/409170/32696457-7a4398d0-c72d-11e7-8e02-c661f8176202.png)
![2017-11-11 22_11_43-defold editor 2 0 - defcollide](https://user-images.githubusercontent.com/409170/32696458-7a6b933a-c72d-11e7-879d-8970d3d8917b.png)

**Comment by AGulev** [comment]
@subsoap @erikangelin-king fixed in new text editor
