### ISSUE TITLE
If anything is selected in Windows console window engine suspends until unselected 

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1403]
- Click on text in console
- Give engine focus
- Engine freezes until selection is cleared in console

If possible it would be better if the engine did not freeze. There may be cases where we want to allow the player to see the console and select text from it without it making the game accidentally freeze. It's also not super obvious that text selected makes the engine freeze.

**Comment by matgis-king** [comment]
Sadly, this behavior is built into the Windows console host. Whenever there is a selection, writes to the standard output streams will block until the selection is cleared. This means whichever thread was writing to stdout cannot proceed until the selection is cleared.

A potential workaround would be move all writes to stdout to a background thread, but often this kind of output is used for debugging so you kind of want the output to complete before proceeding.

I don't think we should change this in the engine, but if you're frequently running into this issue, you might want to turn off **Quick Edit** mode for your command prompt. There is a setting in Properties that should be off by default. When disabled, the user would have to explicitly select **Mark** from the context menu to enter selection mode.
