### ISSUE TITLE
Begin to exclusively encourage Editor 2 use

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1419]
I seem to be seeing many new users using Editor 1. I don't see why not to now begin to encourage use of Editor 2 by all new users, to encourage Editor 1 users to upgrade to Editor 2 within Editor 1 in some way.

**Comment by erikangelin-king** [comment]
Agreed :) We're changing how editor 1/2 are presented. Closing this though as it's not an editor2 issue.
