### ISSUE TITLE
.init has special highlighting in text editor when it shouldn't

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1421]
![2017-11-21 17_03_02-defold editor 2 0 - defglot](https://user-images.githubusercontent.com/409170/33104622-e9ad4bf0-cedd-11e7-8ee1-e5c13b50b3c1.png)

**Comment by Jerakin** [comment]
This goes for all builtin functions doesn't? init, update, final, on_message, on_action, on reload

**Comment by AGulev** [comment]
@subsoap 
Can you recheck? I think this issue can be closed.

**Comment by subsoap** [comment]
![new_init](https://user-images.githubusercontent.com/409170/34688025-8e9e7a4c-f465-11e7-9d70-5b2f67376c30.png)

Yes, it's different now.
