### ISSUE TITLE
Memoryleak while running the editor for an extended period of time

### ISSUE THREAD

**Issue by jakob-pogulis-king** [defold/editor2-issues#143]
I've been using the editor to edit a single script file. After about 6 hours the editor starts to become unresponsive and the "loading cursor" (badboll) shows up for everything from scrolling in the script to accessing API autocompletion.

Running `jvisualvm` displayed memory usage at about 1200 MiB. After restarting the editor it was down to between 200 MiB and 250 MiB. Running the editor with `jvisualvm` active shows the normal gc saw tooth pattern, but running for a longer period of time it is a very noticeable increase that doesn't go away.

During the entire time I only had a single script file open and ran the engine a couple of times (CTRL+B), I never opened another view, used search, or clicked around in the fileview. I did not verify whether the increase occurred regardless of running the engine or not.

**Comment by ragnard-king** [comment]
@jakob-pogulis-king Found a cause,  fix coming.

**Comment by ragnard-king** [comment]
@jakob-pogulis-king A fix for this has now been merged to dev. Would you be able to run the same test as last time to see if you can reproduce or not?
