### ISSUE TITLE
Some Window API constants don't show up in autocomplete?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1430]
![not_showing_up](https://user-images.githubusercontent.com/409170/33199067-833cf218-d0a3-11e7-8f1e-2109e755a511.gif)

![2017-11-23 23_09_45-window reference](https://user-images.githubusercontent.com/409170/33199070-8816ea3c-d0a3-11e7-85df-6517c1f7545d.png)

Should they be there?

**Comment by erikangelin-king** [comment]
Fixed in update coming shortly.
