### ISSUE TITLE
Edit text resources (json, xml, sh and such) in the editor [DEFEDIT-1319]

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1434]
Being able to edit files that the editor doesn't recognise is important. Not being able to is a common annoyance.

**Comment by subsoap** [comment]
+1

Also malformed JSON files won't open at all.

**Comment by saracglaser** [comment]
Issur created in JIRA [https://jira.int.midasplayer.com/browse/DEFEDIT-1319| DEFEDIT-1319]
