### ISSUE TITLE
Can't login to google

### ISSUE THREAD

**Issue by gothicka112** [defold/editor2-issues#1442]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-11-21T11:35:53.295906</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a1738699fce748ba80bec3eeb5072c92349f0d2e</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi! Can you tell us a little bit more about what you were doing and how it failed?

This could be caused by the Windows Firewall blocking communications. Can you make sure the Defold Editor is let through the firewall?

**Comment by erikangelin-king** [comment]
@gothicka112 Did it work eventually? Is this still an issue?
