### ISSUE TITLE
Remove try_game.png from HTML5 template

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1446]
try_game.png is not bundled with html5 builds, it shouldn't be in the html file either

```Failed to load resource: the server responded with a status of 404 (Not Found)```

**Comment by andsveking** [comment]
Added an issue for a more general "looking over our default HTML template"; DEF-3031

**Comment by AGulev** [comment]
@erikangelin-king 
https://forum.defold.com/t/html5-splash-image-bug-in-safari-def-3061-solved/15323/8
It seems like solved issue

**Comment by erikangelin-king** [comment]
@AGulev Hmm, DEF-3031 is not fixed yet. The forum link refers to DEF-30**61**. Still, thanks for helping out!

**Comment by AGulev** [comment]
@erikangelin-king you right (I copy/paste into wrong window, sorry)

**Comment by AGulev** [comment]
Solved https://forum.defold.com/t/defold-1-2-160-has-been-released/60637
