### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by dparmijog** [defold/editor2-issues#1447]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-11-28T17:32:46.897328</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4fe06ccefdbcc2e1608064ba1e0d670ac04b5a86</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b27d67f678ff45049bedd589ea7fc8ee"'>b27d67f678ff45049bedd589ea7fc8ee</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 960/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by dparmijog** [comment]
java.lang.OutOfMemoryError: Java heap space

**Comment by erikangelin-king** [comment]
It looks like you're on a 32-bit windows machine. How much ram do you have installed? Is this a large project? Many large textures? Any change we could have a look at your project?

**Comment by erikangelin-king** [comment]
@dparmijog Do you still get the error?

**Comment by erikangelin-king** [comment]
Hi again @dparmijog! For some reason the stack trace has disappeared from the error so there is not much to go on here. We are aware of the general problem of memory usage though and are looking into it.
