### ISSUE TITLE
Add "Update available" in the Defold Splash/Open project window

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1449]
It would be nice if there was a small thing you could click on directly on the splash for updating window, if there is an update you will get a popup after a few min but that is too long the user will most likely miss that and only see that there is an update available after they have opened the project.

In this screen
![screen shot 2017-11-29 at 10 08 13](https://user-images.githubusercontent.com/5273682/33368961-73e8d4c2-d4f3-11e7-9df0-38aab0bc94a2.png)

**Comment by amel** [comment]
I think this issue can be closed? 🙂 

![image](https://user-images.githubusercontent.com/10830880/44914107-80c0fe80-ad2f-11e8-81d0-f3132843edb2.png)

**Comment by erikangelin-king** [comment]
Hi @amel! One issue left is that we download the update before we show the Update Available notification. We want to split this into notifying that there is an update available and letting the user choose whether to download and update.

**Comment by markusgustavssonking** [comment]
@vlaaad I guess we can close this now?
