### ISSUE TITLE
Mouse cursor becomes almost unmovable when hovering window while building [OS X]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1453]
It didn't use to do this, but now when building (complete build, not incremental) the whole computer becomes super slow, and you can barely move the mouse cursor if it is above the defold window. Once outside it becomes fast though.

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-01T11:46:24.447729</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>909862a870081f044e0592fe1263f68309a24868</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.58.32</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.1</td></tr>
<table>

**Comment by matgis-king** [comment]
Can you recall when this behavior started?

**Comment by Malmer** [comment]
It doesn't happen anymore. Must have been something with my computer or a specific release.

**Comment by matgis-king** [comment]
Thanks for letting us know! I did a speculative fix for it. I guess it worked!
https://github.com/defold/defold/pull/1952/files#diff-d413fd17971b89832fee8a69268eb581R1237
