### ISSUE TITLE
Add async library / dependency fetching

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1454]
When your project has many libs it can take a while to go through them all. It would be much faster if this process was done asynchronous.

**Comment by AGulev** [comment]
<img width="1467" alt="screen shot 2019-01-05 at 22 12 32" src="https://user-images.githubusercontent.com/2209596/50729258-14b83200-1137-11e9-983f-fd546cab1624.png">
Looks like in 1.2.144 this issue already solved? @matgis-king

**Comment by matgis-king** [comment]
Yes! We now fetch dependencies in the background, so I'll close this one.
