### ISSUE TITLE
Build failed: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1456]
Got this when trying to build. I had an update available so updated to it and building worked, but still posting in case this is useful.

```Build failed: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil```

**Comment by matgis-king** [comment]
Thanks for reporting, but we cannot really tell much from this I'm afraid. If you encounter it again, please report it using the error report dialog. That gives us a callstack and a better idea of where the bug originates from.

**Comment by subsoap** [comment]
There was no report error dialog when this specific popup appeared only a close button.

**Comment by subsoap** [comment]
![2017-12-04 02_52_38-alert](https://user-images.githubusercontent.com/409170/33549110-4912f544-d89e-11e7-8d7b-2936120487dc.png)

It happened again after adding this lib, fetching, and then attempting to build https://github.com/GameAnalytics/GA-SDK-DEFOLD/archive/master.zip

**Comment by subsoap** [comment]
This happened again but with adding a different library. The situation seems to possibly be where you have made one or more builds with a project with native extensions and then later with the same editor session running add another native extension lib.

**Comment by subsoap** [comment]
Happens on a Mac too

Open project
Add native extension dependency
(Building once here may or may not matter)
Fetch libraries
Do build

Get

```
Build failed: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil
```

**Comment by matgis-king** [comment]
There might be a warning in the editor log file with a stack trace for this error. Would you mind posting it here?

**Comment by erikangelin-king** [comment]
@subsoap Does this still happen?

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144.

**Comment by erikangelin-king** [comment]
Reopen if it happen again
