### ISSUE TITLE
Error while building android bundle

### ISSUE THREAD

**Issue by jpikavalko** [defold/editor2-issues#1457]
### Expected behaviour
To build APK
### Actual behaviour
I got an error for a file that doesn't exist and isn't even used in the project i.e. I can't make android bundle because of files I don't even need/use.
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-11-29T11:55:04.592036</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>94728efe3067af165ba73e4f871ca8c83a3dc534</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"e8346f0e308f4f84989934da25cdc7a0"'>e8346f0e308f4f84989934da25cdc7a0</a></td></tr>
<tr><td>GPU</td><td>Quadro K2200/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 372.90</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment]
The error occurred when double-clicking the resulting Build Error. This was fixed in https://github.com/defold/defold/pull/1938, merged on Nov 30th.
