### ISSUE TITLE
New console view bounds misalignment [DEFEDIT-1243]

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#1465]
### Expected behaviour

There should be no left padding to the console window

### Actual behaviour

There is this left padding:

<img width="868" alt="screen shot 2017-12-04 at 13 00 27" src="https://user-images.githubusercontent.com/428060/33549594-b7ec48c6-d8f3-11e7-807e-eebd32b12a03.png">

### Steps to reproduce

Open a project

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-01T11:46:24.447729</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>909862a870081f044e0592fe1263f68309a24868</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 650M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.26.6 355.11.10.10.15.102</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.1</td></tr>
<table>

**Comment by coderm4ster** [comment]
There is a padding because the console displays the repetitive lines only once and then the number on the left side of the row is displayed as to how many times the same row occurred.

**Comment by dapetcu21** [comment]
Oh! Didn't notice it. Still, it's sort of a waste of space. I like the way Chrome does this by showing the count inline, not on the gutter:

![screen shot 2017-12-05 at 10 13 31](https://user-images.githubusercontent.com/428060/33596654-12192df8-d9a5-11e7-966c-14f402047459.png)

**Comment by matgis-king** [comment]
We intend to use the gutter for more stuff soon. We might revise the styling once we see how our plans pan out.

**Comment by matgis-king** [comment]
The gutter width has been slimmed down somewhat, and it doesn't look quite as unfinished now. Style tweaks are ongoing, but I'll close this for now.
