### ISSUE TITLE
Can't edit atlases with missing files [DEFEDIT-1246]

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1468]
What happens:
Error "_The file 'image' could not be found_" makes the atlas not render, it also makes the atlas editor stop working.

What should happen:
Images that are missing should have that indicated in the Outline and in the atlas viewer.
(As a MVP just being able to edit/delete images from the outline would be nice)

**Comment by Jerakin** [comment]
If the atlas is small enough it looks like you can edit/remove them from the outline. But a bigger atlas seams to stall.

**Comment by erikangelin-king** [comment]
Partial fix merged, coming in an update shortly. Atlas editor no longer becomes completely unusable. Indication of error in Outline moved to separate issue https://github.com/defold/editor2-issues/issues/1489.
