### ISSUE TITLE
Editor does not recognize changes in certain files

### ISSUE THREAD

**Issue by AKashpur** [defold/editor2-issues#1469]
I add few lines of code to to certain .script files, that have a lot of incvluded .lua files, save changes to files, and build project. The result is builded without those changes.

  for example i tried to add print message id prior to handle message. I see that message is handled, but
there is no print on console

  I tried to remove content of /build folder before building, it did not help. So i had to restart editor in order to this changes being actually included in build.

### Expected behaviour
   Changes in .script files be inncluded in build when press "build"
### Actual behaviour
   Changes in .script file are excluded from build when press "build"
### Steps to reproduce
1)  Have a script files with 500-600 lines of code, and require "" ~20 .lua files of similar size
2)  Modify .script file in atom, save changes, make sure defold editor displays this changes before pressing build
<hr/>

<table>
<tr><td>Build time</td><td>2017-11-21T11:35:53.295906</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a1738699fce748ba80bec3eeb5072c92349f0d2e</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>GPU</td><td>GeForce GTS 450/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 375.70</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @AKashpur ! We've done a lot of changes to the reload and build systems since this was reported. Is this still an issue?

**Comment by erikangelin-king** [comment]
Closing, reopen if still an issue.
