### ISSUE TITLE
Issue with the Spine animation from the getting started tutorial

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#147]
When I run the getting started tutorial I get the following error:

WARNING:RESOURCE: Resource not found: /_generated_89a15a08.texturec
WARNING:RESOURCE: Unable to create resource: build/default/hero/hero.texturesetc
WARNING:RESOURCE: Unable to create resource: build/default/hero/hero.rigscenec
WARNING:RESOURCE: Unable to create resource: build/default/_generated_1ff35037.spinemodelc
WARNING:RESOURCE: Unable to create resource: build/default/_generated_9864d8f6.goc
ERROR:GAMEOBJECT: Could not instantiate game object from prototype /_generated_9864d8f6.goc.
WARNING:RESOURCE: Unable to create resource: build/default/main/main.collectionc

Project is shared with Ragnar

**Comment by ragnard-king** [comment]
@britzl Could you share this project with me too please?
