### ISSUE TITLE
Overrides lost when you edit a GUI template [DEFEDIT-1250]

### ISSUE THREAD

**Issue by caiitlinz** [defold/editor2-issues#1470]
If I make a change to a template (such as adding another node) and save it, it then reverts the template to it's basic state wherever it is used. This is a problem as we're often using templates for things like text buttons (where we will go in and change the label for the string node so it will be called in code), size and shape (9 slice) or turn the alpha on and off (for changing what icon is on a button for example.)

Repro:
Create gui file with nodes
Add it to another gui file as a template
Make overrides within template (set alpha, change texture etc)
Make change to original gui file (for example add another node) and save

Overrides will be lost.

**Comment by erikangelin-king** [comment]
Hi @caiitlinz! I've tried to reproduce this with a couple of versions of the editor, but no luck :( We recently fixed a pretty serious issue when reloading external changes. If for instance you used an external git client to bring in a new version of the project, or used an external editor to modify the .gui files you would almost definitely lose your overrides. I will close this issue for now, but please reopen if it happens again!
