### ISSUE TITLE
Error when I try to change version of lib

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1472]
### Steps to reproduce
1. Remove one of using lib from the project
![2017-12-07_15-57-34](https://user-images.githubusercontent.com/2209596/33716469-5aa0ce96-db67-11e7-824f-65186bc6d763.jpg)
2. Fetch Libraries
3. Add Library one more time
4. Fetch Libraries
5. Build

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-05T15:10:09.513828</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>64ce5ae5b5d3020ed350cfa8b1b744e8a8f7291c</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"c719e9e8957a472d809212c2bd514c89"'>c719e9e8957a472d809212c2bd514c89</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can you still repro this issue? We merged a pretty large change in how we load resources on December 12 and the stacktrace here looks like a typical case that was fixed.

**Comment by erikangelin-king** [comment]
Hi again @AGulev! Apart from the fix above we've also merged a fix for a pretty serious issue in fetch libraries that might very well have caused this. I'm closing this as I can't repro, but as always - please reopen if it happens again!

**Comment by AGulev** [comment]
Ok, thanks. I just checked a second ago -  looks like all fine.
