### ISSUE TITLE
Loading/Setting Images In Game (showAndWait, gtk)

### ISSUE THREAD

**Issue by aussiemale23** [defold/editor2-issues#1476]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-11T12:35:04.798046</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>51e3e93c04fc8124a692353310690f82790a10a7</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4552c8443f644fdea575b00e2f8908e8"'>4552c8443f644fdea575b00e2f8908e8</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 6310 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1151</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.9.66-1-MANJARO</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed
