### ISSUE TITLE
Problem when create bundle for iOS

### ISSUE THREAD

**Issue by albertopiantanida** [defold/editor2-issues#1478]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-12T17:47:20.856348</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>06735f288cd2d489644fd38be32c20ce8d43deb9</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6cd2acc0bae341819100807d385f8f2d"'>6cd2acc0bae341819100807d385f8f2d</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by britzl** [comment]
The root folder of the project was changed using Finder while the project was opened.
