### ISSUE TITLE
Error trying to use the find functionality (cmd+f)

### ISSUE THREAD

**Issue by ricardperez** [defold/editor2-issues#1482]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-11T12:34:21.444204</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>51e3e93c04fc8124a692353310690f82790a10a7</td></tr>
<tr><td>Defold engine sha</td><td>4ac025d15c25a9e0dbf14140d2e5d443c2edfdc4</td></tr>
<tr><td>Defold version</td><td>1.2.117</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"149310e4e2ce408a819b91571b2ddbe3"'>149310e4e2ce408a819b91571b2ddbe3</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.25.17</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by matgis-king** [comment]
This was fixed in defold/defold#1970, which was merged shortly after this report.
