### ISSUE TITLE
If you move node using alt+up - it's break layouts

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1485]
### Steps to reproduce
1. We have two layouts
![2017-12-15_18-03-53](https://user-images.githubusercontent.com/2209596/34047762-5bb214e6-e1c2-11e7-8102-efc100fb6e0b.jpg)
and
![2017-12-15_18-04-21](https://user-images.githubusercontent.com/2209596/34047770-65a7faf6-e1c2-11e7-8fa3-a66cab758fd2.jpg)
2. Try to move node:
![dec-15-2017 18-05-01](https://user-images.githubusercontent.com/2209596/34047877-c7f3e940-e1c2-11e7-89ee-1e2de4852bb4.gif)
3. Landscape layout is broken
<hr/>

<table>
<tr><td>Build time</td><td>2017-12-14T17:13:33.989564</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1e1eeea9e02f2be269bc02a4ca2d455e3ac1dea4</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by AGulev** [comment]
this bug is blocker for using layout feature at all =( 
@erikangelin-king

**Comment by AGulev** [comment]
It is still a big problem for us (

**Comment by AGulev** [comment]
and one more upd

**Comment by AGulev** [comment]
@erikangelin-king 
when I move nodes to new one node:
![2018-05-05_17-25-10](https://user-images.githubusercontent.com/2209596/39664258-55b8aa4c-5089-11e8-94ed-1356ce0acbbf.jpg)
after changes:
![2018-05-05_17-26-39](https://user-images.githubusercontent.com/2209596/39664279-82584a12-5089-11e8-8a23-af7d42f922fd.jpg)
in game:
![2018-05-05_17-27-53](https://user-images.githubusercontent.com/2209596/39664289-ae0192c2-5089-11e8-8eef-c5272eb55a21.jpg)

after editor restart the same as before changes:
![2018-05-05_17-25-10](https://user-images.githubusercontent.com/2209596/39664258-55b8aa4c-5089-11e8-94ed-1356ce0acbbf.jpg)

**Comment by erikangelin-king** [comment]
Hi again @AGulev! You only reordered the nodes? Can you reproduce this, and if so can you give me access to a simple version of this gui?
If you reorder the nodes and save, does the diff look reasonable?
Will look at this tomorrow.

**Comment by AGulev** [comment]
https://youtu.be/JGfxJcybvDE
Changes with atl+up alt+down even  do not save on disk. You can see on video.

Give me your email, I'll share project with you

**Comment by erikangelin-king** [comment]
erik.angelin@king.com
Thanks for finding this!

**Comment by erikangelin-king** [comment]
Fixed for real this time :) (fingers crossed)
