### ISSUE TITLE
Build failed: Wrong number of args (2) passed to: build-errors/build-error

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1487]
Recieve next error when try to build NE with mistakes:
![2017-12-15_23-44-12](https://user-images.githubusercontent.com/2209596/34059835-dfb41274-e1f1-11e7-9147-75af28600e1a.jpg)
Have no way to find an error in NE
<hr/>

<table>
<tr><td>Build time</td><td>2017-12-14T17:13:33.989564</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1e1eeea9e02f2be269bc02a4ca2d455e3ac1dea4</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
