### ISSUE TITLE
Windows: Menus are closed by themselves after a few seconds

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#149]
1. Use windows OS, i use windows 7
2. For instance open Scene menu and Camera
3. Hoover the mouse over Frame selection for a few seconds

Actual result:
The menu closes by itself
![screen shot 074](https://cloud.githubusercontent.com/assets/22887289/20101277/8c6b17e2-a5c1-11e6-9a8a-80bde7ef8d2b.PNG)

**Comment by matgis-king** [comment]
Fix was merged in PR defold/defold#1066.
