### ISSUE TITLE
Hot reloading while debugger is paused throws exception

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1490]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-18T17:12:31.707374</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>b90cbc0c52db3022a0f166e69770827530fda748</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4f838593380547b5a009de6c9b4134ef"'>4f838593380547b5a009de6c9b4134ef</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.24</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.2</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed, you can no longer hot reload when the debugger is paused.
