### ISSUE TITLE
clojure.lang.ExceptionInfo: handler ':save-all' in context ':global' failed at ':run' with message 'null' java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1492]
This happened after trying to fetch libs after changing them, then change an atlas and save.

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-18T15:46:59.696578</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bc1ac962a31070399d56bd4fc25386eadf36c9ca</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"04290faf095840e497de3924f0c5fb5b"'>04290faf095840e497de3924f0c5fb5b</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @subsoap, this looks like an error that could be due to a bug we recently fixed in fetch libraries. I'm closing for now, but please reopen/re-report if it happens again!
