### ISSUE TITLE
When trying to close Defold java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1493]
I click X at top right and this error appears. Alt+f4 produces this error too. Had to kill Java to get it to close at all.

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-18T15:46:59.696578</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bc1ac962a31070399d56bd4fc25386eadf36c9ca</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9ec41d61f057425e931bf18eb2029c83"'>9ec41d61f057425e931bf18eb2029c83</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Maybe consequence of earlier error?

**Comment by subsoap** [comment]
Yes, probably, but still reported it.

**Comment by erikangelin-king** [comment]
Closing since recently fixed (likely) original bug in fetch libraries.
