### ISSUE TITLE
Code editor tabs problem

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1496]
### Expected behaviour
Tabs showing in editor
### Actual behaviour
only first tab showin in editor
### Steps to reproduce

<hr/>

```lua
function M.clear()
	for y=1, M.height do
		for x=1, M.width do
			M.nodes[y][x] = COLORS.BLACK
		end	
	end
end
```

![2017-12-20_14-46-15](https://user-images.githubusercontent.com/2655263/34205764-c4c6b042-e594-11e7-8545-92b7e16c8f73.png)

<table>
<tr><td>Build time</td><td>2017-12-20T11:39:04.310057</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0b3e73e0639c96a463dffb9e9d25cd257de12016</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.4326</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix has been merged, coming in next update shortly.
