### ISSUE TITLE
Defold is no longer opening scripts in external editor(Atom) [DEFEDIT-1263]

### ISSUE THREAD

**Issue by pradeepkulasekaran** [defold/editor2-issues#1498]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-20T11:39:04.310057</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0b3e73e0639c96a463dffb9e9d25cd257de12016</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.26.6 355.11.10.10.15.102</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed, update coming shortly.

**Comment by pradeepkulasekaran** [comment]
**This isn't a new one. Was there long back..**

If Atom/Sublime wasn't  opened it will open many instance of it.
It will crash the mac or can't be stopped until force quit.

<img width="365" alt="screen shot 2017-12-22 at 12 12 38 am" src="https://user-images.githubusercontent.com/12084522/34270079-fad92610-e6ac-11e7-9873-7eb566e3c787.png">
<img width="1440" alt="screen shot 2017-12-22 at 12 12 35 am" src="https://user-images.githubusercontent.com/12084522/34270086-ffb3d7f2-e6ac-11e7-941e-a812ab66e091.png">
