### ISSUE TITLE
Windows 7: Keyboard shortcuts doesnt work properly

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#151]
ctrl+x, c, v, z etc doesnt work in the properties section or game.project
It works in for instance create new popup.

**Comment by sofiahe** [comment]
I got the same issue on the linux laptop.

**Comment by subsoap** [comment]
Most keyboard shortcuts are not working for me in Windows 10 both the old shorcuts from Editor 1 and whatever is labeled in the menus. For example, Ctrl+P Ctrl+T does nothing in the ParticleFX editor (I'd like spacebar playback toggle back). Pressing F (or what it says it is now Ctrl+.) to fit to an object in the Viewport doesn't work either (again old shortcut F would be better).

**Comment by subsoap** [comment]
Not having Ctrl+S to save is painful. 😭
