### ISSUE TITLE
[DEF-3059] Debugger does not break on breakpoints in builtins

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#1519]
1. Set a breakpoint in `/builtins/render/default.render_script`, `update` function
2. Run project with debugger
3. Breakpoint does not suspend execution.

**Comment by AGulev** [comment]
https://forum.defold.com/t/defold-1-2-120-has-been-released/16284
DEF-3059 - Fixed: User can now set break points in the user render script (and not the builtin one).
@andsveking look like fixed issue?

**Comment by vlaaad** [comment]
Can't reproduce. Feel free to reopen if you still have this problem.
