### ISSUE TITLE
java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by AnubisCode** [defold/editor2-issues#1521]
### Steps to reproduce
write in the script of game object:
go.property("", 1) 

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-20T14:02:39.036446</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e54a61d1478bc3987ad99ab8a3f598ced60da000</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a427051d3fbf4c31a6fafcb65777f5f8"'>a427051d3fbf4c31a6fafcb65777f5f8</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed in next update.
