### ISSUE TITLE
Many instance of Atom/Sublime opening in Mac

### ISSUE THREAD

**Issue by pradeepkulasekaran** [defold/editor2-issues#1522]
**This isn't a new one. Was there long back..**

If Atom/Sublime wasn't opened it will open many instance of it.
It will crash the mac or can't be stopped until force quit.

<img width="365" alt="screen shot 2017-12-22 at 12 12 38 am" src="https://user-images.githubusercontent.com/12084522/34270079-fad92610-e6ac-11e7-9873-7eb566e3c787.png">
<img width="1440" alt="screen shot 2017-12-22 at 12 12 35 am" src="https://user-images.githubusercontent.com/12084522/34270086-ffb3d7f2-e6ac-11e7-941e-a812ab66e091.png">

**Comment by ragnard-king** [comment]
Hi @pradeepkulasekaran!

Sorry to hear you're having this issue. Can you try downloading and installing latest version of editor2 again from the dashboard? This could be due to a fix we have made to a part of the application that is not updated automatically.

**Comment by pradeepkulasekaran** [comment]
done a clean install still problem exists...
