### ISSUE TITLE
StackOverflowError when copy paste

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1526]
### Expected behaviour
1)Copy long string to editor
2)If press enter after long line, then get same exception
### Actual behaviour
java.lang.StackOverflowError: Unknown
### Steps to reproduce
1)Copy that lua code
2)Try past it in editor
`local FRAME_UTILS = require libs.frame.frame_utils
local colors = {vmath.vector3(0.09803921729326248, 1.0 ,0.09803921729326248), vmath.vector3(0.0, 0.0 ,0.0), vmath.vector3(0.07058823853731155, 0.7019608020782471 ,0.07058823853731155), vmath.vector3(0.05098039284348488, 0.501960813999176 ,0.05098039284348488), vmath.vector3(1.0, 1.0 ,0.4000000059604645), vmath.vector3(1.0, 1.0 ,0.0), vmath.vector3(0.7490196228027344, 0.7490196228027344 ,0.0), vmath.vector3(1.0, 0.250980406999588 ,0.250980406999588), vmath.vector3(1.0, 0.0 ,0.0), vmath.vector3(0.800000011920929, 0.0 ,0.0), vmath.vector3(0.3490196168422699, 0.3490196168422699 ,1.0), vmath.vector3(0.0, 0.0 ,1.0), vmath.vector3(0.0, 0.0 ,0.6509804129600525), vmath.vector3(1.0, 0.43529412150382996 ,0.20000000298023224), vmath.vector3(1.0, 0.29411765933036804 ,0.0), vmath.vector3(0.800000011920929, 0.23529411852359772 ,0.0)}
local frames = {{width = 25 ,height = 13, {colors[1], colors[1], colors[3], colors[3], colors[2], colors[5], colors[5], colors[5], colors[6], colors[2], colors[8], colors[8], colors[8], colors[9], colors[2], colors[11], colors[11], colors[2], colors[11], colors[2], colors[14], colors[14], colors[14], colors[15], colors[2]}, {colors[1], colors[3], colors[3], colors[4], colors[2], colors[5], colors[6], colors[6], colors[7], colors[2], colors[8], colors[9], colors[9], colors[9], colors[2], colors[11], colors[12], colors[2], colors[12], colors[2], colors[14], colors[15], colors[15], colors[15], colors[2]}, {colors[2], colors[3], colors[3], colors[2], colors[2], colors[5], colors[6], colors[2], colors[2], colors[2], colors[8], colors[2], colors[2], colors[9], colors[2], colors[11], colors[12], colors[2], colors[12], colors[2], colors[14], colors[2], colors[2], colors[2], colors[2]}, {colors[2], colors[3], colors[3], colors[2], colors[2], colors[6], colors[6], colors[2], colors[2], colors[2], colors[9], colors[2], colors[2], colors[9], colors[2], colors[12], colors[12], colors[2], colors[12], colors[2], colors[15], colors[15], colors[15], colors[15], colors[2]}, {colors[2], colors[3], colors[3], colors[2], colors[2], colors[6], colors[6], colors[2], colors[2], colors[2], colors[9], colors[2], colors[2], colors[9], colors[2], colors[12], colors[2], colors[12], colors[12], colors[2], colors[15], colors[15], colors[15], colors[15], colors[2]}, {colors[2], colors[3], colors[3], colors[2], colors[2], colors[6], colors[6], colors[2], colors[2], colors[2], colors[9], colors[2], colors[2], colors[10], colors[2], colors[12], colors[2], colors[12], colors[13], colors[2], colors[2], colors[2], colors[2], colors[16], colors[2]}, {colors[1], colors[3], colors[3], colors[4], colors[2], colors[6], colors[6], colors[6], colors[7], colors[2], colors[9], colors[9], colors[9], colors[10], colors[2], colors[12], colors[2], colors[12], colors[13], colors[2], colors[15], colors[15], colors[15], colors[16], colors[2]}, {colors[3], colors[3], colors[4], colors[4], colors[2], colors[6], colors[7], colors[7], colors[7], colors[2], colors[10], colors[10], colors[10], colors[10], colors[2], colors[13], colors[2], colors[13], colors[13], colors[2], colors[15], colors[16], colors[16], colors[16], colors[2]}, {colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2], colors[2]}, {colors[1], colors[3], colors[2], colors[1], colors[2], colors[5], colors[2], colors[6], colors[2], colors[8], colors[9], colors[2], colors[8], colors[2], colors[2], colors[2], colors[11], colors[2], colors[2], colors[14], colors[15], colors[2], colors[14], colors[15], colors[15]}, {colors[3], colors[4], colors[2], colors[3], colors[2], colors[2], colors[6], colors[2], colors[2], colors[8], colors[9], colors[2], colors[9], colors[2], colors[2], colors[11], colors[2], colors[12], colors[2], colors[15], colors[15], colors[2], colors[2], colors[15], colors[2]}, {colors[3], colors[2], colors[2], colors[3], colors[2], colors[2], colors[6], colors[2], colors[2], colors[9], colors[2], colors[2], colors[9], colors[2], colors[2], colors[12], colors[12], colors[12], colors[2], colors[15], colors[16], colors[2], colors[2], colors[15], colors[2]}, {colors[1], colors[2], colors[2], colors[3], colors[2], colors[6], colors[2], colors[7], colors[2], colors[9], colors[10], colors[2], colors[9], colors[10], colors[2], colors[12], colors[2], colors[13], colors[2], colors[15], colors[2], colors[16], colors[2], colors[16], colors[2]}}}
return frames`

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:35:10.187441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13474 Compatibility Profile Context 22.19.162.4</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment]
I tried pasting the code in various places in a decently large `.lua` file, but was unable to reproduce the error. Can you tell us anything else that might help us reproduce it?

**Comment by d954mas** [comment]
Looks like it problem, with very long line in lua file.

**Comment by d954mas** [comment]
This lua file, not opening in editor. Editor is not responding. I think this is same problem. File contain very long line.
[test_animation.zip](https://github.com/defold/editor2-issues/files/1597311/test_animation.zip)

**Comment by matgis-king** [comment]
The supplied file does indeed cause the editor to stop responding. Reclassifying as blocker.

**Comment by matgis-king** [comment]
This was caused by a recursive regular expression while attempting to syntax-highlight very long lines. We now detect very long lines and skip syntax highlighting for them, to at least it won't break.
