### ISSUE TITLE
Viewing txt files with MANY lines in editor is very slow

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1527]
I have a text file with 174k lines (a word list). In notepad++ it's fine, in editor 2 it's very slow.

**Comment by matgis-king** [comment]
Do you mean editing is slow? I'm able to view really long `.lua` files without significant slowdown, but editing is currently rather slow due to the language analysis we perform.

**Comment by subsoap** [comment]
I meant .txt files not .lua files. Viewing them, scrolling the view is very slow.

**Comment by matgis-king** [comment]
Thanks for clarifying. We should probably start using the new code editor component to view these kind of files instead of a basic multi-line text field.

**Comment by matgis-king** [comment]
Text files are now editable using the regular code editor.
