### ISSUE TITLE
Fetch library is sometimes allowed twice

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1530]
I was able to fetch library twice in a row and this happened

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:35:10.187441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9989c1ca6d924b4e9f4cfe3e73a7ca17"'>9989c1ca6d924b4e9f4cfe3e73a7ca17</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Recently fixed! You can still fetch libraries twice, but it should no longer have horrible consequences.
