### ISSUE TITLE
Defold 2 Debugger issue

### ISSUE THREAD

**Issue by oivoodoo** [defold/editor2-issues#1533]
### Actual behaviour

- Start debugger
- Attacha debugger

<img width="540" alt="screenshot 2017-12-26 13 32 04" src="https://user-images.githubusercontent.com/54469/34354699-3bbe0604-ea41-11e7-85af-2e07ab5d4258.png">

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:34:17.904795</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ca50ac87fcef474e9dca67c7b2773049"'>ca50ac87fcef474e9dca67c7b2773049</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @oivoodoo ! The target selection was broken resulting in us failing to connect to the engine. We merged a fix about a week ago. Can you try again?

**Comment by erikangelin-king** [comment]
Reopen if still an issue
