### ISSUE TITLE
Editor doesnt open if there is a space in the foldername

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#154]
On windows 7
Place Defold folder somewhere
Rename the folder to a name with a space in it
Try to start defold.exe

Editor doesnt open if there is a space in the folder name where the exe is placed.
C:\Users\sofia.hedlund\Desktop\Defold Editor 2\Defold

**Comment by RagnarSvenssonKing** [comment]
Fixed

**Comment by sofiahe** [comment]
@RagnarSvenssonKing Är du säkert? Händer forfarande i :
Defold version: 1.2.93
Defold sha: b98a912b54700e27d0051f3d8b11e5f22b1b67a2
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by sofiahe** [comment]
Still in; Defold sha: 5b644c3774e25722c589812fb4acf7042e34308a

**Comment by erikangelin-king** [comment]
Hi! The fix is part of the launcher Defold.exe which is not currently updated automatically, you have to download a fresh copy.

**Comment by sofiahe** [comment]
Yes it works with a new install. Closing
