### ISSUE TITLE
Editor exception on breakpoint

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#1547]
<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:35:10.187441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"0a105deea8634f5baee9159fff6624e2"'>0a105deea8634f5baee9159fff6624e2</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.24</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.2</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Malmer! We just merged a fix for this.
