### ISSUE TITLE
Unable to install application from dashboard after "Sign iOS app..." [DEFEDIT-1274]

### ISSUE THREAD

**Issue by andsveking** [defold/editor2-issues#1548]
Using same cert and profile in Editor 1 works, but in Editor 2 I get the following error on device:
![img_5f2e982258e1-1](https://user-images.githubusercontent.com/10498365/34482364-cc62c0c0-efb7-11e7-82cf-b107decd3727.jpeg)

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:35:10.187441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M290X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.58.32</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@andsveking Fix merged, please reopen if it doesn't help :)
