### ISSUE TITLE
Underscore not visible in dropdown menu

### ISSUE THREAD

**Issue by andreas-strangequest** [defold/editor2-issues#1549]
### Expected behaviour
When clicking on dropdown menu for open files names should be as filenames
### Actual behaviour
filenames containing underscore is not viewed properly (without underscore)
![screen shot 2018-01-02 at 12 50 55](https://user-images.githubusercontent.com/23556757/34482976-dcbaf61e-efbb-11e7-9fcd-b85759a37d75.png)

**Comment by erikangelin-king** [comment]
Seems like the javafx tab pane does not disable mnemonic parsing on the menu items in the context menu. See `setupPopupMenu` in http://grepcode.com/file/repo1.maven.org/maven2/net.java.openjfx.backport/openjfx-78-backport/1.8.0-ea-b96.1/com/sun/javafx/scene/control/skin/TabPaneSkin.java#TabPaneSkin.TabControlButtons

**Comment by AGulev** [comment]
related https://github.com/defold/editor2-issues/issues/601
