### ISSUE TITLE
When opening a existing project it doesnt default to where the projects are saved [DEFEDIT-1181]

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#155]
1. Create a project on the dashboard
2. Open the editor
3. Import the project
4. Save the project 
5. Close down the editor
6. Start the editor
7. Click Open to open the project

Actual result: The default location of the open dialog is not where the project is saved

Expected result: to be by default in the space where the projects are saved when they are imported. Now it defaults to Computer.
![screen shot 077](https://cloud.githubusercontent.com/assets/22887289/20131561/8cb20092-a65e-11e6-89e1-82bde319efb6.PNG)

**Comment by RagnarSvenssonKing** [comment]
I suspect that the actual issue is that preferences are not saved on Windows. Try this to find out:

Resize the window panes in a weird way. (e.g. minimising asset view, maximising outline view)
Restart the app and the panes should look exactly the same

**Comment by sofiahe** [comment]
Ok, tried to change the windows panes and restarted. The changes were saved.

**Comment by RagnarSvenssonKing** [comment]
Quick win if we can save the path in preferences and use it when browsing for game.project files.

**Comment by erikangelin-king** [comment]
At least partially fixed, seems it's not always possible to set the initial directory for the file chooser on macos. Left as separate issue #1344.
