### ISSUE TITLE
Simply double clicking in the Outline when nothing is in it leads to NullPointerException

### ISSUE THREAD

**Issue by LukasSchulz** [defold/editor2-issues#1550]
### Expected behavior
Nothing happening
### Actual behavior
Some NullPointerException
### Steps to reproduce
Double click inside "Outline" when nothing is in it
<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:35:10.187441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9c3ba795a5ec452d90ec8694f95d7e99"'>9c3ba795a5ec452d90ec8694f95d7e99</a></td></tr>
<tr><td>GPU</td><td>GeForce 840M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.76</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We can't reproduce this, can you give more detailed steps to repro?

**Comment by LukasSchulz** [comment]
ok, sorry, found out there is more to that.
So first, you have to make a file (whatever type [I tested with collection and sprite, but it seems to be irrelevant]) then this File opens in the Outline and the Middle top Menu (forgot the name, sorry). Then, in the "asset" menu, you have to delete that file. It gets closed in the outline and "Middle Menu" but, if you now double-click on the Outline menu, you get the Error I got.

**Comment by LukasSchulz** [comment]
Ok, one addition. To me, this only happened now twice and even I can't reproduce it now. I will report back if I find out more.

**Comment by erikangelin-king** [comment]
Can't repro with those steps either, but please reopen if it happens again! Thanks!
