### ISSUE TITLE
I can't type in any sysmboly using [AltGR] on my Keyboard (ex. "{";"}")

### ISSUE THREAD

**Issue by LukasSchulz** [defold/editor2-issues#1551]
### Expected behaviour
Typing of Symbols like {or [ works
### Actual behaviour
Typing issues nothing or Hotkeys (eg. Making Text smaller but not typing the actual letters)
I don't know if this issue only exists on my Keyboard Layout because I have a German one, but still, then I would like to have an Option for changing/disabling specific Hotkeys
### Steps to reproduce
Simply Holding [Alt Gr] and trying to type any Character
<hr/>

<table>
<tr><td>Build time</td><td>2017-12-22T14:35:10.187441</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b17ecc8a61828aa0b0c1a73a8102840859da4ab8</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>GPU</td><td>GeForce 840M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.76</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jerakin** [comment]
I think this was fixed an hour ago, the newest version of the editor is 8e6ca2bc94e54368a7b4d7dbf4c709ec2310fbca you got b17ecc8a61828aa0b0c1a73a8102840859da4ab8. Try to update the editor by clicking the "Update Available" in the lower right corner and see if you can use Alt Gr then :)

**Comment by LukasSchulz** [comment]
ok, thanks
