### ISSUE TITLE
Undo/Redo actions are shared between the open tabs

### ISSUE THREAD

**Issue by coderm4ster** [defold/editor2-issues#1553]
Expected behaviour: Each open tab should have an independent Undo/Redo operation stack

**Comment by erikangelin-king** [comment]
This is by design, but we're considering changing it.

**Comment by subsoap** [comment]
@erikangelin-king It's really annoying to have one tab focused, press ctrl+z a bunch, then realize that it deleted a bunch of code in another tab.

**Comment by erikangelin-king** [comment]
@subsoap Yes, we're painfully aware :) We're discussing different options. Short term we'll probably begin with making it more apparent where the undo/redo action is happening. Maybe by flipping focus to a related tab, or having a "history" panel. Ultimately we need to settle on how many undo/redo histories we want in the application. One per tab might make sense if you look at scripts, but in for instance collections - due to in place editing of referred collections/game objects - it's no longer as obvious.

**Comment by subsoap** [comment]
@erikangelin-king Make it per open tab, if a tab is closed clear its history. Only allow undo to happen to the currently active tab. Let users define how much undo history they want to keep. Have a separate editor / code history maximum able to be set. A peekable history view might be handy.

**Comment by erikangelin-king** [comment]
@subsoap Yes, in principle I agree, but there are annoying cases that we have not agreed on. For instance, say you have your `main.collection` open in a tab. That collection has a sub collection `sub.collection`, with a game object from `foo.go`. You change (not override) some setting on that game object from this tab. That becomes something you can undo. Then you open `foo.go` and realise, nah, that change was no good. Now what? Do you have to move back to `main.collection` i.e. the "perspective" of the project where you did the change? I would at least want to be able to undo from `foo.go` also. Probably also from the tab `sub.collection` if that is also open. This is what I ment when I wrote that one undo/redo per tab is not so clear cut :) The reason undo/redo is like it is right now is that we haven't sorted this out.

**Comment by subsoap** [comment]
@erikangelin-king I would have it so you can only undo from the current context/perspective which are modification has taken place. In this case, if you wanted to revert the foo.go and you already lost the main.collection context then the user would need to resort to recovering its previous version with git history.

Maybe have extra file revision history separate from undo/redo within the editor.
