### ISSUE TITLE
Double cursor typing in editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1556]
Not sure what caused this

![double_cursor](https://user-images.githubusercontent.com/409170/34579144-a3268b48-f13c-11e7-9533-76a9baa2c378.gif)

**Comment by rgrams** [comment]
It's a feature. There are a few different ways to get multiple cursors:
1. Ctrl+Click
2. Have something selected and hit Ctrl+D (select next occurrence)
3. Have multiple lines selected and hit Ctrl+Shift+L (adds a cursor on each selected line)

You can press Escape or click somewhere else to go back to one cursor.

**Comment by subsoap** [comment]
@rgrams thank you for info.
