### ISSUE TITLE
Error output in console inside pprint output

### ISSUE THREAD

**Issue by LosJustos** [defold/editor2-issues#1560]
I pprint() a table and get an error because of a nil calue. The error in the console is just printed inside the output and looks wrong:

![ss 2018-01-06 at 05 15 53](https://user-images.githubusercontent.com/18404304/34641468-4ecd0a7a-f305-11e7-82bd-56e63e173d06.png)

**Comment by erikangelin-king** [comment]
Hi! This could be a message from a custom `__tostring` using `sub` on a nil value, or maybe another thread calling `sub`. Not much we can do about it I'm afraid, thanks for reporting though!
