### ISSUE TITLE
Illegal Character

### ISSUE THREAD

**Issue by GamingBud** [defold/editor2-issues#1564]
When creating a folder with an illegal character, like in my case the '?', the engine doesn't catch it and instead sends a "crash" message. The engine doesn't crash, it just reports it as a bug when the engine should just say that I cannot use that character in a folder name.

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-05T13:48:09.323479</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6b263769c4aeef9ac237318a1e92271e51d85f22</td></tr>
<tr><td>Defold engine sha</td><td>0faa10db6bb28907d67358ad5810f3962437f3fd</td></tr>
<tr><td>Defold version</td><td>1.2.118</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"22b2ea90be1d427b9779902703e3270f"'>22b2ea90be1d427b9779902703e3270f</a></td></tr>
<tr><td>GPU</td><td>Radeon(TM) RX 460 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13491 Compatibility Profile Context 22.19.662.4</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144. Feel free to reopen in case it is still an issue.

![2019-01-05_23-04-15](https://user-images.githubusercontent.com/2209596/50729680-484a8a80-113e-11e9-80e5-da3e6b3f77a7.jpg)
