### ISSUE TITLE
Latest project is shown twice in the latest project list when opening Editor

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#157]
Open the same project 2 times in a row.

The latest project is always shown twice in the latest project list when opening the editor.

![screen shot 078](https://cloud.githubusercontent.com/assets/22887289/20132042/597e6492-a661-11e6-9d6e-8208a8bfeb0a.PNG)

**Comment by erikangelin-king** [comment]
Can't repro :(

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144. Feel free to reopen in case it is still an issue.
