### ISSUE TITLE
Autocomplete of math.huge is wrong

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1577]
### Expected behaviour
math.huge is treated as a constant value when autocompleting

### Actual behaviour
math.huge is treated as a function when autocompleting

### Steps to reproduce
Try to autocomplete math.huge
Notice that the editor adds parenthesis to math.huge()

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-09T13:50:10.476691</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a35142141107e02d7125b0842c440e6d21fe7376</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by AGulev** [comment]
Can't reproduce
