### ISSUE TITLE
Drop-down assets menu does not show correct name of open assets

### ISSUE THREAD

**Issue by spongepaddy** [defold/editor2-issues#1579]
### Expected behaviour
The drop-down assets menu should show the correct name of the open assets

### Actual behaviour
First underscore of the asset name is stripped in the menu (see image)

### Steps to reproduce
Always happens

![screen shot 2018-01-17 at 09 59 59](https://user-images.githubusercontent.com/5442727/35034085-4308673c-fb6d-11e7-8fb1-e1332f7cbf01.png)

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-09T13:50:10.476691</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a35142141107e02d7125b0842c440e6d21fe7376</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.10.14 310.42.25f02</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
See #1549
