### ISSUE TITLE
Native not show build errors [DEFEDIT-1529]

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1581]
### Expected behaviour
Show build errors for native extensions
### Actual behaviour
Show only warnings
### Steps to reproduce
1)Clone project https://github.com/d954mas/defold-raycasting
2)step at commit "get only warnings in ne(not showing errors)" 1c5394b8a4df7006feb995b63d5ab06be9974157
3)Try build it.
![2018-01-17_13-27-54](https://user-images.githubusercontent.com/2655263/35037991-45284484-fb8a-11e7-8059-b45c6658f86e.png)

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-15T13:51:11.848458</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8b805e523a12eb6f58652ee8ac3e88b980fabf1e</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.4326</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by selimanac** [comment]
Same here for windows build: https://github.com/selimanac/DAABBCC
More info: https://forum.defold.com/t/compiling-native-extension-lib-for-windows/17377/5

**Comment by d954mas** [comment]
@selimanac .I think the problem with parsing response from build server. You can open logs for editor2, and you will see your errors. In windows logs inside: C:\Users\user\AppData\Local\Defold

**Comment by d954mas** [comment]
@erikangelin-king any news with it?=) it's annoying to read errors from logs=)

**Comment by erikangelin-king** [comment]
Hi @d954mas! Sorry, no news yet. @matgis-king is neck deep in implementing a tricky feature and I'm just back after being sick for a week, working on some build/build-caching/debugger issues.

**Comment by selimanac** [comment]
@d954mas  I check the log files. In my case, there is nothing related to build in the log.
