### ISSUE TITLE
Grandchildren to clipping nodes does not render correctly [DEFEDIT-1413]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1582]
STR:

1. Create a GUI with a clipping node, a child and a grandchild node.
2. Notice how the grandchild node does not clip in the editor.

![screen shot 2018-01-18 at 08 59 41](https://user-images.githubusercontent.com/65613/35086766-17c0fcf8-fc2e-11e7-9741-527eab773ba8.png)

Runtime is fine:

![screen shot 2018-01-18 at 08 59 51](https://user-images.githubusercontent.com/65613/35086819-3d1eab58-fc2e-11e7-8e84-4809c9438e36.png)

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/gui-clipping-has-no-effect-on-grandchildren-nodes-is-this-by-design-or-bug/15876
