### ISSUE TITLE
Font with outline width more than 1 gets clipped

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1583]
### Expected behaviour
Outline should not be clipped

### Actual behaviour
Outline is clipped

### Steps to reproduce
on a DF font set outline to more than 1

### Example
![screen shot 2018-01-19 at 14 38 43](https://user-images.githubusercontent.com/5273682/35153595-76d4236a-fd27-11e7-93ae-5b8683ee357a.png)

You can see a tiny bit of clipping already with width 2, at with 4 it is very obvious.

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-15T13:51:11.848458</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8b805e523a12eb6f58652ee8ac3e88b980fabf1e</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by britzl** [comment]
Fixed.
