### ISSUE TITLE
Text tracking floats doesnt work in Editor 2 [DEFEDIT-1526]

### ISSUE THREAD

**Issue by andreas-strangequest** [defold/editor2-issues#1589]
### Expected behaviour
Text Tracking "between" integers (eg. 0.5 ) should show Text tracking correct.
### Actual behaviour
Editor view shows weird text tracking
### Steps to reproduce
Add a textnode with a working font. Set Text Tracking to -0.5

Works in engine. 

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-15T13:51:11.848458</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8b805e523a12eb6f58652ee8ac3e88b980fabf1e</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.14.73</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by mosmetro** [comment]
Very annoying bug. Please fix this asap.

**Comment by AGulev** [comment]
+1 

This bug especially annoying when we use fonts with outline.

**Comment by sicher** [comment]
It seems that the tracking is added at the end of the text or something. In editor:

<img width="884" alt="screen shot 2018-07-06 at 10 42 43" src="https://user-images.githubusercontent.com/65613/42369166-6e70a41c-8109-11e8-9dff-8ff12ad9a8d6.png">

And runtime:

<img width="565" alt="screen shot 2018-07-06 at 10 43 22" src="https://user-images.githubusercontent.com/65613/42369179-75d8fbbe-8109-11e8-8b54-7a8a5b3b59b6.png">
