### ISSUE TITLE
Crashing when trying to use life stretch curves.

### ISSUE THREAD

**Issue by milleStrangequest** [defold/editor2-issues#1592]
### Steps to reproduce
Click life stretch curve button.
<hr/>

<table>
<tr><td>Build time</td><td>2018-01-15T10:34:26.890830</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e3a93908f8da15cf1570aa78cc0c0c014f502aa6</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"923b6fdba4144442b7c3b64615d3b24f"'>923b6fdba4144442b7c3b64615d3b24f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 21.20.16.4550</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Also affects forum user Agulev

**Comment by AGulev** [comment]
Yes, Thanks @britzl 
I'll push more info today later.

**Comment by AGulev** [comment]
exception when tap to next btns:
![2018-04-25_15-56-18](https://user-images.githubusercontent.com/2209596/39247136-3c799aea-48a1-11e8-99ea-ff0b97ccadaf.jpg)

**Comment by AGulev** [comment]
But today's our issue is https://github.com/defold/editor2-issues/issues/1839

**Comment by erikangelin-king** [comment]
The code for the curve button assumed there was always a start value. Simplest fix was to disable it until you've entered something in the fields.

**Comment by erikangelin-king** [comment]
Alright, regression fixed, fix-fix merged, re-closing issue :)
