### ISSUE TITLE
2d raycast gets no response when completely within another object

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1599]
Example here

![2018-01-25 12_12_41-defbullet](https://user-images.githubusercontent.com/409170/35410093-10b0975c-01c9-11e8-9e04-86c568fa05c7.png)

![2018-01-25 12_13_25-defold editor 2 0 - defbullet](https://user-images.githubusercontent.com/409170/35410132-2ef41978-01c9-11e8-913d-e7166ef8532b.png)

Small objects within other objects do produce a response, but raycasts with start and end within an object don't. This is annoying because I was hoping to use raycasts to solve bullet tunneling.

https://forum.defold.com/t/raycast-within-a-collision-object-is-not-detected/415

**Comment by AGulev** [comment]
https://github.com/defold/defold/issues/4933
