### ISSUE TITLE
Promted to confrim Unsaved changes when closing project which hasnt been changed

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#160]
1. Open a project
2. Dont change anything
3. Close the editor directly

Actual result: 
Unsaved changes exist, are you sure you want to quit?

Expected result:
As there hasnt been any changes in the project I should be able to close down the editor without this confirmation popup
![screen shot 080](https://cloud.githubusercontent.com/assets/22887289/20132788/e5352658-a664-11e6-86a6-e713ae4da588.PNG)

**Comment by dapetcu21** [comment]
I am also experiencing this.

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>745b7940a228ab460a1d3a2a947f75f725cba839</td></tr>
<tr><td>Build time</td><td>2017-01-25T15:57:32.800241</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment]
Also have this showing. No file is open. Still get the dialog.

![2017-03-15 03_42_01-promted to confrim unsaved changes when closing project which hasnt been changed](https://cloud.githubusercontent.com/assets/409170/23944813/6d98c188-0931-11e7-8fc2-8bc695f027c0.png)


<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>a3de6c12b751a0dc37e0f3bd4eb23ca89e628585</td></tr>
<tr><td>Build time</td><td>2017-03-14T18:59:57.241052</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Tomires** [comment]
Same, I sometimes forget to save the changes because the dialogue kind of lost its sense of importance as it shows up every time I exit out of the editor.

Defold version: 1.2.102
Defold sha: e41546be9f07d669d1675d079e786788cd9b8f85
OS: elementaryOS 0.4 Loki (based on Ubuntu 16.04) x64
Kernel version: 4.4.0-72-generic

**Comment by erikangelin-king** [comment]
related https://github.com/defold/editor2-issues/issues/190

**Comment by erikangelin-king** [comment]
related https://github.com/defold/editor2-issues/issues/212

**Comment by RagnarSvenssonKing** [comment]
Fixed!
