### ISSUE TITLE
Editor error when switching to a deleted file

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1600]
### Expected behaviour
It should be possible to switch back to the editor and not have it crash even though one of the open files has been deleted

### Actual behaviour
An error was generated when I switched back to the editor and the file I had opened (an .appmanifest file) was deleted (actually renamed) outside the editor

### Steps to reproduce
Have a file open in the editor
Put the editor in the background
Rename the file
Switch back

Hmm... I wasn't able to reproduce it again...

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-25T11:14:28.131710</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>31c069c6af9abaefa5135cc5a686a4d4b7cff474</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.28.10 355.11.10.10.20.111</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by matgis-king** [comment]
Note: Possibly an `ErrorValue` reaching the internals of the code editor by mistake?

**Comment by erikangelin-king** [comment]
@britzl Reopen if it happens again, think this was fixed.
