### ISSUE TITLE
Whenever i type in a float number in the particle system editor, it keeps changing them to this long winded decimal point monstrosities [DEFEDIT-1296]

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#1604]

**Comment by erikangelin-king** [comment]
<img width="405" alt="screen shot 2018-01-10 at 10 19 57" src="https://user-images.githubusercontent.com/12696401/35500676-9afdb3e8-04d7-11e8-8f43-683c561c872f.png">

**Comment by Jerakin** [comment]
https://github.com/defold/editor2-issues/issues/1565
