### ISSUE TITLE
Shortcut to comment/uncomment line(s)

### ISSUE THREAD

**Issue by andsveking** [defold/editor2-issues#1606]
I would love to have a keyboard command to comment/uncomment a line or a block of lines.

The default setup in Sublime Text (on macOS) is Cmd+/ if I'm not mistaken. I tried this, which would be equal to Shift+Cmd+7 on a Swedish keyboard, but it just shows the `Help` menu. :(

Personally I would like this to be Shift+Cmd+C instead since it's a much easier combo, at least on my keyboard... :)

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-25T11:14:28.131710</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>31c069c6af9abaefa5135cc5a686a4d4b7cff474</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M290X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.58.32</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.1</td></tr>
<table>

**Comment by programmerby** [comment]
Any news? This is a critical feature needed.

**Comment by AGulev** [comment]
pls pls pls!

**Comment by kikoosvk** [comment]
pls pls pls !

**Comment by vlaaad** [comment]
Fixed, check for udpates! 
<kbd>Cmd /</kbd> on macOS, <kbd>Ctrl /</kbd> on linux and windows.
