### ISSUE TITLE
Setting the size to be equal to the slice9 values breaks rendering in the editor

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1610]
### Expected behaviour
The rendering in the editor should reflect that of the engine

### Actual behaviour
The rendering in the editor breaks

### Steps to reproduce
Set the size.x of a node to X (e.g. 50)
Set slice9.x and slice9.z to X/2 (e.g. 25)

### Comparison
![screen shot 2018-01-30 at 10 13 37](https://user-images.githubusercontent.com/5273682/35557816-91986f9e-05a6-11e8-9572-242041c071d4.png)
 
![screen shot 2018-01-30 at 10 13 22](https://user-images.githubusercontent.com/5273682/35557832-a0f282fe-05a6-11e8-8bfe-0cfe9b5bcf05.png)

![screen shot 2018-01-30 at 10 19 06](https://user-images.githubusercontent.com/5273682/35557972-0c255196-05a7-11e8-90b1-b22dfd487bf0.png)

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-25T11:14:28.131710</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>31c069c6af9abaefa5135cc5a686a4d4b7cff474</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Recently merged a fix.
