### ISSUE TITLE
Autocomplete error [DEFEDIT-1291]

### ISSUE THREAD

**Issue by SebastienBellanger** [defold/editor2-issues#1611]
Demo file has been provided

I get the error every time I type a key:
java.lang.RuntimeException: Unable to convert: class clojure.core.reducers.Cat to Object[]

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-25T11:14:28.131710</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>31c069c6af9abaefa5135cc5a686a4d4b7cff474</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a487e1e4c2fc4e968701b9d2c0b16712"'>a487e1e4c2fc4e968701b9d2c0b16712</a></td></tr>
<tr><td>GPU</td><td>AMD RADEON R9 M295X</td></tr>
<tr><td>GPU Driver</td><td>4.5.13476 Compatibility Profile Context 22.19.170.1536</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Should be fixed now!
