### ISSUE TITLE
Error when i open any *.script and try to save changes. Everytyme. [DEFEDIT-1340]

### ISSUE THREAD

**Issue by alexblackbird** [defold/editor2-issues#1613]
Error when i open any *.script and try to save changes. Everytyme.
Error apears after update.

Thanks!

"clojure.lang.ExceptionInfo: handler ':save-all' in context ':global' failed at ':run' with message 'No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil'
java.lang.IllegalArgumentException: No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil"

UPD
This error occurs when the project is opened from the disk. (Without using the git)

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-31T09:41:41.329058</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8a48ddb58a6e30f1ed96e4e834019cbc6858bbc5</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b4442cc3f16e46b196d43bfec90cc84d"'>b4442cc3f16e46b196d43bfec90cc84d</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 960/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by alexblackbird** [comment]
after this 

"java.lang.IllegalArgumentException: No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil"

**Comment by matgis-king** [comment]
Try as I might, I cannot reproduce this. The error suggests that we're unable to locate the UI element that we use to list the changed files. This should still be there even though your project is not managed by Git, so I'm kind of dumbfounded. Perhaps there is something in the logs that might help us. I'm `mats.gisselson` on the Defold Forum if you want to send us the logs.

**Comment by dapetcu21** [comment]
@matgis-king I think I have managed to reproduce this. This happens when you open a new project with a new git repository, but with no initial commit.

**Comment by dapetcu21** [comment]
What I did when it happened: I cloned https://github.com/subsoap/defos, deleted .git, ran `git init`, then opened Defold and opened the project in it, then tried to save anything.

**Comment by erikangelin-king** [comment]
See also #1735
