### ISSUE TITLE
Undo breaks when editing fragment programs .fp

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1622]
Make many changes, do many undos, cursor moves around instead of undoing properly

**Comment by subsoap** [comment]
This was closed on purpose?

**Comment by matgis-king** [comment]
Yes, I think defold/defold#2070 fixes it.

Prior to the fix, every move of the cursor would create an undo step, so the cursor would move one character at a time. With the fix, we group undo into larger steps. I though this was what the error report was about, but perhaps I'm misunderstanding the issue?

**Comment by subsoap** [comment]
Probably fixed then. I'll report if it happens again.
