### ISSUE TITLE
Can't debug blossom

### ISSUE THREAD

**Issue by EgillAntonssonKing** [defold/editor2-issues#1624]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-31T09:41:41.329058</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8a48ddb58a6e30f1ed96e4e834019cbc6858bbc5</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2535aca4872c4af18df79aa4164dbd8e"'>2535aca4872c4af18df79aa4164dbd8e</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.24</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.2</td></tr>
<table>

**Comment by matgis-king** [comment]
Is the issue still present? I just tried this and it seems to work.

**Comment by erikangelin-king** [comment]
This was an OOM/Java heap space. We recently merged a fix that decreases memory usage during build. Closing this for now, but reopen if it happens again.
