### ISSUE TITLE
One of the defold's window become unresponsive and forces me to restart to fix

### ISSUE THREAD

**Issue by Fuzzyperson** [defold/editor2-issues#1625]
I don't know how to reproduce this, because it's kinda random to happen.

### Expected behaviour
when you closed your games that launched from the defold editor -> It just closes.
when you closed one of the tabs from the code window -> it shows the left tab.

### Actual behaviour
gives me an error, it says:
clojure.lang.ExceptionInfo:Concurrent modification of graph

and one of the defold editor's window (e.g. console, code window, changed files) becomes unresponsive.
console won't refresh anymore even if you hit the clear button.
code window won't show where I selected, inserted, or deleted.

The only fix that I know is to restart the defold editor entirely.
but as soon as I started to work, and when I did something, It happens again.
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-01T17:37:41.431250</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>24e2664ee09752f75c0521eb8ebd45cc3271aa54</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4d5d5d2ce78b4cd0b26cbb589a5f11d4"'>4d5d5d2ce78b4cd0b26cbb589a5f11d4</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 960/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Fuzzyperson ! We found and fixed a cause for this error just after you reported, has it happened again since? Can we close the issue?

**Comment by Fuzzyperson** [comment]
sorry for late reply!
And yeah, looks like It fixed, It never happened since then!
