### ISSUE TITLE
Same crash as 1626 but another reproduce case

### ISSUE THREAD

**Issue by andreas-strangequest** [defold/editor2-issues#1627]
### Steps to reproduce
Closed running app. 
<hr/>

<table>
<tr><td>Build time</td><td>2018-02-01T17:37:41.431250</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>24e2664ee09752f75c0521eb8ebd45cc3271aa54</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"5ef90d9b0ac5461db1bbaaf7e33ec59b"'>5ef90d9b0ac5461db1bbaaf7e33ec59b</a></td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.14.73</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#1626

**Comment by erikangelin-king** [comment]
Fix for #1626 merged, should cover this as well!
