### ISSUE TITLE
Game Object: Missing icon for Light component

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#163]
Right click on Game object and add Light component

Actual result:
Missing Icon

The other components have a correct icon

![screen shot 082](https://cloud.githubusercontent.com/assets/22887289/20134194/d731d6fe-a66a-11e6-9b92-2d82a4f97ebe.PNG)

**Comment by RagnarSvenssonKing** [comment]
"Fixed" since we removed the light altogether.
