### ISSUE TITLE
Error on external git pull???

### ISSUE THREAD

**Issue by rgrams** [defold/editor2-issues#1631]
I really don't know what's causing this error, but I am getting it multiple times a day lately. This time I did git pull from my git client GUI (Gitkraken), I was already up to date so nothing was changed, then I switched back to the Defold editor and this error was there. This is the second time I know of that it's happened exactly like that, but I don't think that's the only occasion when I get "concurrent modification of graph" errors. I'm guessing it has something to do with modifying files outside of Defold. 

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-02T11:06:30.753964</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>659720155a36366288a3a20b7aacc7c73cdc9126</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ff76569ca1904073a5344958c968972b"'>ff76569ca1904073a5344958c968972b</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 9.18.10.3165</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by rgrams** [comment]
Welp, there's another one, but this time it popped up as soon as I closed the game after running it from the editor, which is new. (But I did not restart the editor since the last error)

<tr><td>Error: </td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d69d72fa00e2400a8de4e90a5a6c4747"'>d69d72fa00e2400a8de4e90a5a6c4747</a></td></tr>

**Comment by erikangelin-king** [comment]
Hi! Thanks for reporting! This is a duplicate of #1626, we just merged a fix.

**Comment by rgrams** [comment]
Ah! Awesome, thanks! I will keep my eye out for the Update button.
