### ISSUE TITLE
Concurrent modification of graph crash

### ISSUE THREAD

**Issue by SebastienBellanger** [defold/editor2-issues#1632]
One of the open text windows crashed and is unresponsive. Can be solved by closing and opening it back up again.
Got this error clojure.lang.ExceptionInfo: Concurrent modification of graph

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-02T11:06:30.753964</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>659720155a36366288a3a20b7aacc7c73cdc9126</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"acc554b0251c4b77a65484221acc3e50"'>acc554b0251c4b77a65484221acc3e50</a></td></tr>
<tr><td>GPU</td><td>AMD RADEON R9 M295X</td></tr>
<tr><td>GPU Driver</td><td>4.5.13476 Compatibility Profile Context 22.19.170.1536</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This was fixed earlier today, please install the update when it shows up!
