### ISSUE TITLE
random error since the last update

### ISSUE THREAD

**Issue by MGProduction** [defold/editor2-issues#1634]
this odd error (a dialog with an error message)  happened several times eve while doing *nothing* since the last update. After that console output freeze (sometimes)

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-01T17:37:41.431250</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>24e2664ee09752f75c0521eb8ebd45cc3271aa54</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2dc66d8eb4664215b72e8edbe4dbf733"'>2dc66d8eb4664215b72e8edbe4dbf733</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.4358</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! This issue was fixed yesterday and an update should appear soon.
