### ISSUE TITLE
Error (glGenBuffers)

### ISSUE THREAD

**Issue by zitz1980** [defold/editor2-issues#1636]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-02T18:11:41.481194</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9513f5404c2c6668a38b5415c549a869b65a27ff</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3324d71941b1452d8d999a92e74f83c8"'>3324d71941b1452d8d999a92e74f83c8</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @zitz1980! Have you tried updating your graphics drivers? Do you have an Intel(R) HD Graphics card?

**Comment by erikangelin-king** [comment]
@zitz1980 Shoot me an email at erik.angelin@king.com and I'll help you out.

**Comment by erikangelin-king** [comment]
@zitz1980 This became the first faq :) https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md

**Comment by zitz1980** [comment]
Thank you, I 'll try it.

2018-02-12 12:16 GMT+03:00 erikangelin-king <notifications@github.com>:

**Comment by erikangelin-king** [comment]
@zitz1980 Did it help?

**Comment by zitz1980** [comment]
Yes. Thanks a lot.

2018-03-09 17:31 GMT+03:00 erikangelin-king <notifications@github.com>:
