### ISSUE TITLE
not enough heap [DEFEDIT-1301]

### ISSUE THREAD

**Issue by neonovoepsheno** [defold/editor2-issues#1638]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-05T10:35:17.272878</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5687f96313ec6f4b7bb914617b67764206ced10b</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"c37a36978f9942a98e1cd58eac1b387f"'>c37a36978f9942a98e1cd58eac1b387f</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 5450</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1151.1008</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Does this happen every time you build, or was it a one-time thing?

**Comment by neonovoepsheno** [comment]
Every time

**Comment by neonovoepsheno** [comment]
@matgis-king Every time

**Comment by matgis-king** [comment]
We're looking into this and are working on a fix. The duplicate report #1643 has more info.
