### ISSUE TITLE
OutOfMemoryError:GC overhead limit exceeded

### ISSUE THREAD

**Issue by gianlucabelvisi** [defold/editor2-issues#1639]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-05T11:33:32.956312</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5687f96313ec6f4b7bb914617b67764206ced10b</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"79d0619e5ff749188380576c3e4a6b40"'>79d0619e5ff749188380576c3e4a6b40</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by matgis-king** [comment]
Apparently the problem went away after restarting the machine. Closing this blocker for now, but we should look into memory usage more in the future.
