### ISSUE TITLE
Game Object: Missing contextual menu options, cut, copy, paste [DEFEDIT-1082]

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#164]
1. Right click on Game object in Outline
2. Add  a Collision object
3. Right click on Collision object

Actual result: 
Missing option to add collision shape.
Also missing the copy, paste, cut options.
![screen shot 083](https://cloud.githubusercontent.com/assets/22887289/20134348/6986feb2-a66b-11e6-8171-6644e78ef1df.PNG)

![image](https://cloud.githubusercontent.com/assets/22887289/21053713/f25d6862-be2a-11e6-886a-d6c4eb88f3c6.png)

Goes for all components in the list.

**Comment by RagnarSvenssonKing** [comment]
Duplicate of #86

**Comment by sofiahe** [comment]
good, closing

**Comment by sofiahe** [comment]
#86 have only added "Add shape" to the contextual menu. The other options are still missing, Copy, paste and delete for all components.
