### ISSUE TITLE
Unhandled 403 when opening project from dashboard

### ISSUE THREAD

**Issue by onefifth** [defold/editor2-issues#1646]
### Expected behaviour
Handled exception/error.
### Actual behaviour
Unhandled error.
### Steps to reproduce
After clicking "Open from Dashboard", Windows firewall was in the middle of asking if "Java(TM) Platform SE binary" should be allowed to access the internet on public/private networks (very fresh Windows install). The resulting 403 was uncaught.

Might be related to issue #1645
<hr/>

<table>
<tr><td>Build time</td><td>2018-02-05T11:33:32.956312</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5687f96313ec6f4b7bb914617b67764206ced10b</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a1db2fecc1dc419cbbfbd57481927594"'>a1db2fecc1dc419cbbfbd57481927594</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
Outdated. The dashboard is shutted down.
