### ISSUE TITLE
Custom GO script properties from libs are being reset [DEFEDIT-1307]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1649]
This seems to happen also when changing libraries sometimes without resetting libs. Sometimes all custom properties will be reset! It seems to happen consistently when adding and then deleting a an unrelated lib dependency and then saving.

The lib where the GO is required was not modified for 22 days but still got reset to default state.

**Comment by erikangelin-king** [comment]
@subsoap  Ha :) We tried to repro this issue last week but never succeeded. Are you saying the script with the `go.property` definitions comes from a library? Is the game object a separate `.go` file, referenced from a collection, or embedded in a collection? It would really help if you could flesh out your STR! Thanks!

**Comment by erikangelin-king** [comment]
@subsoap Managed to repro it, great!

**Comment by erikangelin-king** [comment]
Fix merged! Hope the CI gods are in a good mood.
