### ISSUE TITLE
Renaming an asset which is open does not update the opened file tab

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#165]
1. Create a new script file
2. Open it
3. Rename it by right clicking it in assets

Actual result: The open file is not renamed until its closed and opened again.
![screen shot 085](https://cloud.githubusercontent.com/assets/22887289/20134948/a465cbf6-a66d-11e6-8cc6-38b44c2a6c49.PNG)

**Comment by RagnarSvenssonKing** [comment]
Quick win if it can be solved through the listener that checks for removed files and subsequently removes the tabs.

**Comment by RagnarSvenssonKing** [comment]
Will be fixed as part of DEFEDIT-614

**Comment by ragnard-king** [comment]
Fixed by defold/defold#1158
