### ISSUE TITLE
Editor doesn't recognize file extensions if not in lowercase

### ISSUE THREAD

**Issue by piXelicidio** [defold/editor2-issues#1651]
![daedefold](https://user-images.githubusercontent.com/6601446/36066847-ee7871f2-0e87-11e8-948f-682f21ce82b9.jpg)

Drag anything to the Assets tree, if the file extensions is not in lowercase the editor doesn't recognize it and even double-click doesn't work to open asset.

**Comment by erikangelin-king** [comment]
By design for now, see also #1092.
