### ISSUE TITLE
Poor display spine animation in HTML5 (DEF-3211)

### ISSUE THREAD

**Issue by alexblackbird** [defold/editor2-issues#1654]
### Problem
I created animation in DragonBones and import in spine format
![image](https://user-images.githubusercontent.com/8341327/36092506-48937420-0ff0-11e8-8689-c4271c0937f8.png)

What i see in html5 and windows bundle:
![cat](https://user-images.githubusercontent.com/8341327/36092202-36575e58-0fef-11e8-8f2e-54f9de3bca64.PNG)

In android and ctrl + B test looks okay!

### Solution
If open .json file with animation data and add "spine": "3.6.32" in skeleton section
{
	"skeleton":{
	"width":339.24,
	"height":459.92,
	"fps":24,
	"hash":" ",
	"name":"Armature",
	**"spine": "3.6.32"**
}
...
Animation is played perfectly!

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-09T17:55:28.506062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ae0c5857e5a413235c097fcc87d53a3f62756d1c</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>GeForce GTX 960/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by britzl** [comment]
DEF-3211

**Comment by AGulev** [comment]
https://forum.defold.com/t/defold-1-2-136-has-been-released/29039
DEF-3211 - Fixed: Some Dragonbones spine scenes break while bundling.
@erikangelin-king
