### ISSUE TITLE
go.property not created if conatins calculations

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#1656]
### Expected behaviour
Properties contain property with calculated value
### Actual behaviour
Property not showing in Properties
Property not created(self.property_name = nil)
### Steps to reproduce
1)create script with line go.property("raycasting_fov", 1.57075 * 1.2)
2)open go in editor
3)print(self.raycasting_fov) -- nil
<hr/>

<table>
<tr><td>Build time</td><td>2018-02-09T17:55:28.506062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ae0c5857e5a413235c097fcc87d53a3f62756d1c</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.4326</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This is by design. We parse the value to determine its type, and roughly only understand literals/constants - no expressions. Reopen if you feel this should be a feature request.
