### ISSUE TITLE
This error occurred when debugging locally

### ISSUE THREAD

**Issue by EgillAntonssonKing** [defold/editor2-issues#1658]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-09T17:55:28.506062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ae0c5857e5a413235c097fcc87d53a3f62756d1c</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"767f91e21d694445813c80c38bd871c6"'>767f91e21d694445813c80c38bd871c6</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@EgillAntonssonKing Just merged a fix.
