### ISSUE TITLE
Hot Reloading grayed out in the menu

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#1659]
>rantingbob
>I’m working in Win10, running Editor2 v1.2.120 2018-02-09T17:55:28.506062.
>Hot reloading is grayed out in the menu, and I’m not sure why, or what I need to do to my project to make it work again. Suggestions?

>tacklemcclean
>Sometimes this happens to me when I’m switching target a lot. Try setting your target again, might work?

>rantingbob
>Windows editor 2, standard application that I can Project->Build on, and yes, that’s what I’ve done. No app-manifest, and only 1 target, the standard engine.

https://forum.defold.com/t/hot-reloading-grayed-out-in-the-menu/16745/3

**Comment by ShriekBob** [comment]
Editor: v1.2.120 2018-02-09T17:55:28.506062.
OS: Windows 10 64-bit - up to date as of Feb 13th 2018
Project: War Battles tutorial
Behavior: War Battles can be built using Ctrl+B, but once running can not be hot reloaded, the option is greyed out.

**Comment by Gianmichele** [comment]
Confirming. Defold editor 2 v 1.2.120 hot reload does not work

**Comment by pullingour** [comment]
Same issue here.  

#### OS:  
OS X El Capitan 10.11.6 (15G1611)
#### Editor:  
same as @ShriekBob
#### Screenshot:  
<img width="346" alt="screen shot 2018-02-19 at 01 02 33" src="https://user-images.githubusercontent.com/7346730/36353950-a5ee0d4a-1510-11e8-9715-97fa78fca20a.png">

"Hot Reload" in **File > Menu** is grayed out, press ⌘ + R then nothing happen.

**Comment by erikangelin-king** [comment]
Hi @ShriekBob @pullingour @Gianmichele ! The target selection was broken for a while, resulting in us not finding an engine instance to run Hot Reload on :) A fix was merged about a week ago, does this still happen?

**Comment by ShriekBob** [comment]
Yep, its fixed.

**Comment by erikangelin-king** [comment]
@ShriekBob Great, closing this then.

**Comment by iovorobiev** [comment]
Just discovered that I also have this problem. Editor version is 1.2.122

**Comment by erikangelin-king** [comment]
@iovorobiev It depends, that number is the engine version shipped with the editor. Can you give me the sha's from the about dialog also?

**Comment by iovorobiev** [comment]
@erikangelin-king `c36f6b56c6056d077bd2ef7fbcca72d131caae6a` and `fce7921da858a71876773c75920b74310ca7ac1f`

**Comment by erikangelin-king** [comment]
@iovorobiev The target selection should be fixed in that version. What were you trying to hot reload? Is anything selected (✓) in the targets submenu?

**Comment by iovorobiev** [comment]
Okay, I actually tried to hot reload changed property for the game object. Now I see that if I change the script itself I can hot reload it. Is hot reloading properties just not supported?

**Comment by erikangelin-king** [comment]
@iovorobiev You can hot reload script files, but not game objects or collections. Do you mean you tried to hot reload while in the properties panel? In that case it would try to hot reload the resource in the active tab.

**Comment by iovorobiev** [comment]
Okay, so I have a game object in a collection, it has a script in it and this script has a property (Jump Takeoff Speed). I change it from 900 to 1800, save everything and then try to hot reload but I am not able to do that. 

<img width="276" alt="2018-03-14_0743" src="https://user-images.githubusercontent.com/1309921/37375646-9d6e37d2-275b-11e8-9bb2-17a2673cd6f2.png">

**Comment by erikangelin-king** [comment]
@iovorobiev The issue here is that the overridden value you set for `jump_takeoff_speed` is stored in, and only used in, the top level collection you have opened here. I guess it's `main.collection`. You can override a `go.property` value on several levels:
* in the game object referring to the script (override value stored in game object)
* in a collection referring to the game object (override value stored in collection)
* in a collection referring to the subcollection with the game object (override value stored in collection)

The value used for the property is roughly the "topmost" override.

Your override will end up in `main.collection`, and sadly collections cannot be hot reloaded. If you want to try hot reloading, you could open `hero.script`, change the default value for `jump_takeoff_speed` and then hot reload `hero.script`.

**Comment by iovorobiev** [comment]
Thanks a lot, @erikangelin-king now it's clear. Is it intended that collections cannot be hot reloaded or do you have plans to enable it? I've just started with defold, sorry if I'm asking about fundamentals in that case.

**Comment by erikangelin-king** [comment]
@iovorobiev Well, I think we all agree it would be nice to be able to hot reload everything but it's a pretty large/tricky issue (if at all possible/sensible), and not a current priority.
Feel free to ask more questions on the forum (https://forum.defold.com/), that's how we all learn :)
