### ISSUE TITLE
final() didn't work on android

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1661]
final() didn't work on android when user close an app. Is this a bug or by design?
https://forum.defold.com/t/getting-notifications-when-an-application-working/8019/9?u=agulev
Simple code for checking:
`
local my_file_path = sys.get_save_file("my_game", "my_file")
function init(self)
	print(my_file_path)
	local my_table = sys.load(my_file_path)
	if next(my_table) then
		gui.set_text(gui.get_node("here"), my_table.some_num)
	else
		gui.set_text(gui.get_node("here"), "nil")
	end
end

function final(self)
	sys.save(my_file_path, {some_num = math.random()})
end

`
you need one gui component and text node with id  "here". 

On ios it's works fine.

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-12T12:22:19.130062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>43cbb5fc7f1e3b6f80e82931c7a3145ba2738b39</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by subsoap** [comment]
Android has a different kind of life cycle where data can be lost when closing AFAIK. There are also differences between Android versions.

Try to get the API version of the Android device user is using?

**Comment by britzl** [comment]
I don't think we should rely on final() to be called when the app closes. And we should not do anything long-running there either. final() is more of a lifecycle function to use when a script component gets deleted/unloaded.

**Comment by subsoap** [comment]
What should be done by the dev is to use window to see if focus is lost. I believe this works on Android and gives dev enough time to run functions to save game. This is comparable to "on_suspend" other engines have.

**Comment by AGulev** [comment]
@britzl  Absolutely agree with you, would be great to add this point to the docs. Something like "can't be used for actions when application close" or something like this.
(I reported this issue just because people often asked me and think that it's wrong behaviour. Now I have a link to this issue to show that using final() method for this kind of things a bad design)
