### ISSUE TITLE
Just proving tutorial...

### ISSUE THREAD

**Issue by elvenbyte** [defold/editor2-issues#1663]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-12T12:22:19.130062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>43cbb5fc7f1e3b6f80e82931c7a3145ba2738b39</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4600</td></tr>
<tr><td>GPU Driver</td><td>4.2.0 - Build 10.18.10.3412</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 8.1</td></tr>
<tr><td>OS version</td><td>6.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@elvenbyte There is no information about the error in this report. If you manage to reproduce the error, please press the report button in the dialog.
