### ISSUE TITLE
Attach debugger not working in 1.2.120

### ISSUE THREAD

**Issue by petereliassonking** [defold/editor2-issues#1666]

**Comment by erikangelin-king** [comment]
Hi @petereliassonking ! The target selection was broken for a couple of weeks, resulting in various network related errors. We merged a fix about a week ago. Has this happened again since?

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144.

**Comment by vlaaad** [comment]
We also released a couple of improvements to debugger recently. Feel free to reopen if you still have this problem.
