### ISSUE TITLE
Pressing enter in a text document (yaml), reindents (breaks) the file

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#1668]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-12T12:22:19.130062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>43cbb5fc7f1e3b6f80e82931c7a3145ba2738b39</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M290X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by mathiaswking** [comment]
<img width="473" alt="screen shot 2018-02-16 at 09 30 50" src="https://user-images.githubusercontent.com/14980582/36299220-5adc6ac4-12fc-11e8-859b-3b3d77d45bfe.png">
<img width="492" alt="screen shot 2018-02-16 at 09 30 59" src="https://user-images.githubusercontent.com/14980582/36299223-5e906b98-12fc-11e8-88a4-23fe1dc86941.png">

**Comment by mathiaswking** [comment]
Next (related) issue: Pasting text on the line:
Before:
<img width="541" alt="screen shot 2018-02-16 at 09 35 12" src="https://user-images.githubusercontent.com/14980582/36299827-13669c70-12ff-11e8-93f6-9e0540aa7904.png">

After:
<img width="556" alt="screen shot 2018-02-16 at 09 35 20" src="https://user-images.githubusercontent.com/14980582/36299835-1b81b2dc-12ff-11e8-8d1b-286274f23c99.png">

**Comment by matgis-king** [comment]
We no longer attempt to "fix" indentation when we don't have a proper syntax definition for the language.
