### ISSUE TITLE
Random error when opening hero.spinescene after hero.go strangely got cleaned out

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#167]
Dont remember all steps. 
i opened here.go and saw that all objects in outline had been removed in it.
I tried to recreate here.go and linked here.spinescene to it again. When clickling on the asset file for here.spincescene this appeared.

{:cause nil,
 :via
 [{:type java.lang.NullPointerException,
   :message nil,
   :at [clojure.lang.Numbers divide "Numbers.java" 3792]}],
 :trace
 [[clojure.lang.Numbers divide "Numbers.java" 3792]
  [editor.spine$fn__56819 invokeStatic "spine.clj" 423]
  [editor.spine$fn__56819 invoke "spine.clj" 422]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.lang.Var invoke "Var.java" 379]
  [editor.spine$SpineSceneNode$behavior$spine_scene_pb invokeStatic "spine.clj" 622]
  [editor.spine$SpineSceneNode$behavior$spine_scene_pb invoke "spine.clj" 622]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 271]
  [editor.spine$SpineSceneNode$behavior$scene invokeStatic "spine.clj" 622]
  [editor.spine$SpineSceneNode$behavior$scene invoke "spine.clj" 622]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 271]
  [internal.node$pull_first_input_value invokeStatic "node.clj" 1096]
  [editor.scene$SceneView$behavior$render_data invokeStatic "scene.clj" 407]
  [editor.scene$SceneView$behavior$render_data invoke "scene.clj" 407]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 271]
  [editor.scene$SceneView$behavior$selected_renderables invokeStatic "scene.clj" 407]
  [editor.scene$SceneView$behavior$selected_renderables invoke "scene.clj" 407]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 271]
  [editor.scene$SceneView$behavior$selected_aabb invokeStatic "scene.clj" 407]
  [editor.scene$SceneView$behavior$selected_aabb invoke "scene.clj" 407]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 271]
  [internal.node$node_value_STAR_ invokeStatic "node.clj" 338]
  [internal.node$node_value invokeStatic "node.clj" 353]
  [dynamo.graph$node_value invokeStatic "graph.clj" 738]
  [dynamo.graph$node_value invoke "graph.clj" 710]
  [dynamo.graph$node_value invokeStatic "graph.clj" 726]
  [editor.scene$frame_selection invokeStatic "scene.clj" 518]
  [editor.scene$make_gl_pane$fn__23779 invoke "scene.clj" 649]
  [editor.scene.proxy$com.defold.control.Region$ff19274a layoutChildren nil -1]
  [javafx.scene.Parent layout "Parent.java" 1087]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Parent layout "Parent.java" 1093]
  [javafx.scene.Scene doLayoutPass "Scene.java" 552]
  [javafx.scene.Scene$ScenePulseListener pulse "Scene.java" 2397]
  [com.sun.javafx.tk.Toolkit lambda$runPulse$30 "Toolkit.java" 355]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.tk.Toolkit runPulse "Toolkit.java" 354]
  [com.sun.javafx.tk.Toolkit firePulse "Toolkit.java" 381]
  [com.sun.javafx.tk.quantum.QuantumToolkit pulse "QuantumToolkit.java" 510]
  [com.sun.javafx.tk.quantum.QuantumToolkit pulse "QuantumToolkit.java" 490]
  [com.sun.javafx.tk.quantum.QuantumToolkit lambda$runToolkit$404 "QuantumToolkit.java" 319]
  [com.sun.glass.ui.InvokeLaterDispatcher$Future run "InvokeLaterDispatcher.java" 95]
  [com.sun.glass.ui.win.WinApplication _runLoop "WinApplication.java" -2]
  [com.sun.glass.ui.win.WinApplication lambda$null$148 "WinApplication.java" 191]
  [java.lang.Thread run "Thread.java" 745]]}

**Comment by ragnard-king** [comment]
Possibly same as https://github.com/defold/editor2-issues/issues/147?

**Comment by sofiahe** [comment]
Havent seen this again, close?

**Comment by ragnard-king** [comment]
Yeah, can't really re-produce and the code involved has changed quite a bit since this happened.
