### ISSUE TITLE
pprint not always doing proper line breaks when table printing is truncated on previous line (DEF-3149)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1694]
![2018-02-25 08_32_14-defold editor 2 0 - defsave](https://user-images.githubusercontent.com/409170/36643877-7829325e-1a06-11e8-9c13-7f1a969adfce.png)

**Comment by matgis-king** [comment]
We should make it more obvious that the output got truncated. Perhaps we need to print something like `----- (output truncated) -----` on a separate line.

**Comment by andsveking** [comment]
Added a engine issue for this: **DEF-3149**

**Comment by AGulev** [comment]
Fixed in 1.2.141
https://forum.defold.com/t/defold-1-2-141-has-been-released/33996
