### ISSUE TITLE
Missing error logging when build NE [DEFEDIT-1529]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1698]
Editor 2
![2018-02-26_21-08-39](https://user-images.githubusercontent.com/2209596/36687028-609f9856-1b39-11e8-8714-f69662751007.jpg)

Same project in Editor1
![2018-02-26_21-10-26](https://user-images.githubusercontent.com/2209596/36687051-7b11b8fe-1b39-11e8-9c74-149fe2de153d.jpg)

Error txt:
[error.txt](https://github.com/defold/editor2-issues/files/1759766/error.txt)

project:
[appsflyer.zip](https://github.com/defold/editor2-issues/files/1759770/appsflyer.zip)

<table>
<tr><td>Build time</td><td>2018-02-20T13:20:55.242831</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>965412654cfd7cc7b81136666ecb731690b33553</td></tr>
<tr><td>Defold engine sha</td><td>9988355914f63362a4292c4827639f0187275e70</td></tr>
<tr><td>Defold version</td><td>1.2.121</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by mathiaswking** [comment]
@matgis-king I think we need to have a catch-all for Editor 2, to make sure the error gets visible.

In this case, there's no real good info to parse from the log itself and connect to a single resource in the project:
"clang-3.9: error: linker command failed with exit code 1 (use -v to see invocation)"

Editor 1 handles this case by detecting that no resource 
was matched, then trying to match the ext.manifest, then the app manifest, then no resource (as in this case it seems).

**Comment by AGulev** [comment]
The same issue is here https://github.com/defold/editor2-issues/issues/1581

**Comment by AGulev** [comment]
@markusgustavssonking WOW!!!
