### ISSUE TITLE
Got this when attach debugger to a project

### ISSUE THREAD

**Issue by EgillAntonssonKing** [defold/editor2-issues#1701]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-20T13:20:55.242831</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>965412654cfd7cc7b81136666ecb731690b33553</td></tr>
<tr><td>Defold engine sha</td><td>9988355914f63362a4292c4827639f0187275e70</td></tr>
<tr><td>Defold version</td><td>1.2.121</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f902c946bc6e436486839f754cf4eb53"'>f902c946bc6e436486839f754cf4eb53</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by vlaaad** [comment]
We also released a couple of improvements to debugger recently. Feel free to reopen if you still have this problem.
