### ISSUE TITLE
Include the directories of Defold editor logs within the readme of this git

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1703]
C:\Users\ username \AppData\Local\Defold

etc.

**Comment by AGulev** [comment]
On mac: 
/Users/**username**/Library/Application Support/Defold

**Comment by vlaaad** [comment]
On linux ~/.Defold

**Comment by AGulev** [comment]
https://github.com/defold/editor2-issues/blob/master/faq/logs.md
