### ISSUE TITLE
Add goto/label support for HTML5 target

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1711]
Currently only HTML5 builds don't support goto/labels ?

https://forum.defold.com/t/goto-not-working-on-html5-solved/2074/9

http://luajit.org/extensions.html

**Comment by britzl** [comment]
There is no backport of goto and labels for vanilla Lua 5.1. We will not be able to support got on html5 until we can switch to LuaJIT on HTML5 (which isn't likely to happen anytime soon).

**Comment by subsoap** [comment]
You can emulate them if you parse the Lua scripts yourself... but it's a huge pain.
