### ISSUE TITLE
(Request) Ability to remove cluttered "Recent Projects"

### ISSUE THREAD

**Issue by Gmanicus** [defold/editor2-issues#1715]
https://forum.defold.com/t/simple-ability-to-remove-cluttered-recent-projects/17454

My recent projects list is a mess every time I open up the Defold Editor, and there is no way–that I’ve found–to remove any of the listings from “Recent Projects”.

Many of those projects were tests for certain components and I soon deleted the files, yet it still appears as a project in the “Recent Projects” list.

It would be nice to see something like this:
![untitled](https://user-images.githubusercontent.com/11013079/36943646-47192808-1f52-11e8-810e-cfba2c370fb7.png)

**Comment by AGulev** [comment]
Duplicate https://github.com/defold/editor2-issues/issues/1048

**Comment by vlaaad** [comment]
Implemented, check for updates!
