### ISSUE TITLE
The filter function when importing from the dashboard crashes

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1719]
### Expected behaviour
I should be able to filter the list

### Actual behaviour
I get a crash when writing in the filter field

### Steps to reproduce
Open from Dashboard
Write in the filter field
Crash!

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-02T11:02:01.279571</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>74a96d564f1ecdcf54b5cc00c965cb80ddeee1be</td></tr>
<tr><td>Defold engine sha</td><td>fce7921da858a71876773c75920b74310ca7ac1f</td></tr>
<tr><td>Defold version</td><td>1.2.122</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f3efb70178cb4f789a9625d8b3cc99a0"'>f3efb70178cb4f789a9625d8b3cc99a0</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#1723 has better error, closing
