### ISSUE TITLE
Key triggers dropdown is not sorted alphabetically hard to find a specific key

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#172]
Open game.input_binding
Add a new trigger to Key triggers
Try to fast find and add Key_Up

Its hard to find the correct key in the list as its not sorted alphabetically and its not possible to search for it

**Comment by RagnarSvenssonKing** [comment]
Filter is needed

**Comment by vlaaad** [comment]
It's now sorted alphabetically, check for updates!
