### ISSUE TITLE
Autocomplete asserts because of bad formatting 

### ISSUE THREAD

**Issue by SebastienBellanger** [defold/editor2-issues#1721]
I created a list, but forgot to add the "=" sign, and autocomplete started to throw asserts with every key stroke.

E.g.

local MY_LIST {
  [1] = "hello",
  [2] = "world"
}

Will repo this case.

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-02T11:02:01.279571</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>74a96d564f1ecdcf54b5cc00c965cb80ddeee1be</td></tr>
<tr><td>Defold engine sha</td><td>fce7921da858a71876773c75920b74310ca7ac1f</td></tr>
<tr><td>Defold version</td><td>1.2.122</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"20ae8612df6a49c798eaafd13300d4fd"'>20ae8612df6a49c798eaafd13300d4fd</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 387.95</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged a week ago :)
