### ISSUE TITLE
Created a new folder and got the following exception

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1722]
### Steps to reproduce

1. Start Defold
2. Open project
3. Right click a folder and create new one.

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-02T11:02:01.279571</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>74a96d564f1ecdcf54b5cc00c965cb80ddeee1be</td></tr>
<tr><td>Defold engine sha</td><td>fce7921da858a71876773c75920b74310ca7ac1f</td></tr>
<tr><td>Defold version</td><td>1.2.122</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9f27a26e2f8c48cda8d72f1a62f3fa91"'>9f27a26e2f8c48cda8d72f1a62f3fa91</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
I can't repro this, does it happen every time? In every project?
