### ISSUE TITLE
Crash when filtering projects during Import from Dashboard [DEFEDIT-1325]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1723]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-02T11:02:01.279571</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>74a96d564f1ecdcf54b5cc00c965cb80ddeee1be</td></tr>
<tr><td>Defold engine sha</td><td>fce7921da858a71876773c75920b74310ca7ac1f</td></tr>
<tr><td>Defold version</td><td>1.2.122</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"c3f0265fc7d3436a848a5628950e2246"'>c3f0265fc7d3436a848a5628950e2246</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged! The error occurs when you have projects with the same name.
