### ISSUE TITLE
Just report this unknown issue

### ISSUE THREAD

**Issue by lichongsw** [defold/editor2-issues#1726]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-02T11:02:01.279571</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>74a96d564f1ecdcf54b5cc00c965cb80ddeee1be</td></tr>
<tr><td>Defold engine sha</td><td>fce7921da858a71876773c75920b74310ca7ac1f</td></tr>
<tr><td>Defold version</td><td>1.2.122</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2b8bcd3a9eaa46ff9ac47e6ddd1968f2"'>2b8bcd3a9eaa46ff9ac47e6ddd1968f2</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 376.09</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @lichongsw!
Can you reproduce this? Do you have a `.script` file where this always happens?
Thanks!

**Comment by lichongsw** [comment]
Hi @erikangelin-king ，
I didn't meet this issue again. I will post some detailed informations if it's reproduced next time.

**Comment by erikangelin-king** [comment]
Just merged a fix for this issue! Duplicate/related to #1739 #1691
