### ISSUE TITLE
Make __dm_script_instance__ part of the API and document it

### ISSUE THREAD

**Issue by mosmetro** [defold/editor2-issues#1729]
Very useful feature.
Allows me organize strict update order between script components, re-route messages like ‘ray_cast_response’ to another script instance, greatly reduce amount of messages sent between scripts, etc.
https://forum.defold.com/t/make-dm-script-instance-part-of-the-api-and-document-it

**Comment by AGulev** [comment]
We fully removed this feature.
We don't recumbent, but if you really need it you can use https://github.com/DanEngelbrecht/LuaScriptInstance
