### ISSUE TITLE
I renamed the test.mm.script to test.mm on disc [DEFEDIT-1341]

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#1730]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-13T09:44:26.875787</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d8a7715fefcfa9e86a81dceec9a5f4b25a6ebbba</td></tr>
<tr><td>Defold engine sha</td><td>46d8b7e63d7e0f0f4acd545c46d25ca2b227a806</td></tr>
<tr><td>Defold version</td><td>1.2.123</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"95ac72fdd71044e4945522f5c7c382ec"'>95ac72fdd71044e4945522f5c7c382ec</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M290X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by matgis-king** [comment]
Note: Looks like an `ErrorValue` reached some part of the text editor.
