### ISSUE TITLE
Native Extension compiler compatibility for MSVC2017

### ISSUE THREAD

**Issue by selimanac** [defold/editor2-issues#1734]
Forum thread is here: https://forum.defold.com/t/compiling-native-extension-lib-for-windows/17377/16?u=selimanac

**Comment by AGulev** [comment]
@selimanac could you check with [1.2.164](https://forum.defold.com/t/defold-1-2-164-has-been-released/63982?u=agulev)
It should be fine now.
> Issue-4540 - Fixed: NE - Updated to MSVC 2019 SDK
