### ISSUE TITLE
cmd+D when nothing is selected

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1739]
<hr/>

<table>
<tr><td>Build time</td><td>2018-03-09T15:47:03.974365</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c36f6b56c6056d077bd2ef7fbcca72d131caae6a</td></tr>
<tr><td>Defold engine sha</td><td>fce7921da858a71876773c75920b74310ca7ac1f</td></tr>
<tr><td>Defold version</td><td>1.2.122</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"80efc2440fb5478bab7e7746eb3b9c42"'>80efc2440fb5478bab7e7746eb3b9c42</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged!
