### ISSUE TITLE
Opening a project from dashboard does not work

### ISSUE THREAD

**Issue by Braniacslambam** [defold/editor2-issues#1742]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-13T09:44:16.239005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d8a7715fefcfa9e86a81dceec9a5f4b25a6ebbba</td></tr>
<tr><td>Defold engine sha</td><td>46d8b7e63d7e0f0f4acd545c46d25ca2b227a806</td></tr>
<tr><td>Defold version</td><td>1.2.123</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@Braniacslambam Seems like the exception / error info is missing for some reason. Can you reproduce this? What error did you get?

**Comment by IVTore** [comment]
![deception](https://user-images.githubusercontent.com/29803458/37519360-db0ed2b6-2929-11e8-9935-2d6800cb6b4a.png)
Please help. Very deceptive when trying to start :D

**Comment by erikangelin-king** [comment]
Closing. If this is still an issue, please check this FAQ and reopen if it doesn't help. https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md
