### ISSUE TITLE
Reorder frames in animation groups

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#1748]
For our game, we have a lot of animations where frames are duplicated so that they have different hold times. This is really difficult to do without being able to reorder frames in the atlas editor. We have about 500 animations of that type to make and being able to reorder frames without cheating with Atom would be really helpful.

**Comment by AGulev** [comment]
![jan-06-2019 10-13-42](https://user-images.githubusercontent.com/2209596/50734192-c8530d80-119b-11e9-9fc0-0ad99cb059b0.gif)
Now it's possible using Alt+Up and Alt+Down.

**Comment by dapetcu21** [comment]
Yup. It's possible. I'll close this and make 2 other issues related to this.

**Comment by dapetcu21** [comment]
Opened here: #2383 #2384
