### ISSUE TITLE
Html template canvas transparency problem with Safari

### ISSUE THREAD

**Issue by selimanac** [defold/editor2-issues#1749]
Safari 11.0.3
Defold 1.2.123

![screen shot 2018-03-17 at 14 03 16](https://user-images.githubusercontent.com/1324635/37554928-c86cac06-29f0-11e8-8153-04ccccf0687f.png)

**Comment by AGulev** [comment]
https://forum.defold.com/t/html5-splash-image-bug-in-safari/15323

**Comment by AGulev** [comment]
@erikangelin-king  @selimanac Solved in Defold 1.2.125

**Comment by AGulev** [comment]
@erikangelin-king
https://forum.defold.com/t/html5-splash-image-bug-in-safari-def-3061-solved/15323/8
It seems like solved issue  DEF-3061
