### ISSUE TITLE
Doesnt work to have two different tilesource images

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#175]
Open a project with a working tilesource (gamefromscratch walking man)
Add a another tilesource asset to the same project.
Open both tilesource assets
In the new tilesource set a new image

Actual result: Nothing happens in the new tilesource asset
Switch over to the original asset which now shows the new image.

Seems as both tilesource assets can only use the same image path.

![screen shot 092](https://cloud.githubusercontent.com/assets/22887289/20181229/992ebd1a-a75d-11e6-81f2-9cf6b42e2af3.PNG)
![screen shot 093](https://cloud.githubusercontent.com/assets/22887289/20181228/992e1be4-a75d-11e6-94d2-6921c2d17c38.PNG)

Defold version: 1.2.92
Defold sha: f44590dedb0a53fd405e8944a33e322815a3c5ed
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
It actually works as designed, but the design is bad. The reason behind this is that the selection model we currently use is *global*. This means that when you open the new tile source, that tile source becomes selected. When you then open the old tile source, that becomes selected again. Going back to the tab of the new tile source _does not_ select it again, the old is still selected and its properties is being displayed in the properties view. So when you set that image, you are in fact setting it for the old tile source. This is very confusing and I even agree it is a blocker anyway.

**Comment by ragnarsvensson** [comment]
Fixed
