### ISSUE TITLE
Defold crashes on intel GPU 

### ISSUE THREAD

**Issue by arkoak** [defold/editor2-issues#1753]
### Expected behaviour
It should not throw the error and allow opening the tutorial project
### Actual behaviour
AN error is thrown each time the window is resized moved etc. Cannot use defold at all.
### Steps to reproduce
Open the tutorial project.
<hr/>

<table>
<tr><td>Build time</td><td>2018-02-12T12:22:19.130062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>43cbb5fc7f1e3b6f80e82931c7a3145ba2738b39</td></tr>
<tr><td>Defold engine sha</td><td>c70ad190898e790f8284e8dab0e31c9090476be9</td></tr>
<tr><td>Defold version</td><td>1.2.120</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"0eed0fc9d2af4548a626409b80576e37"'>0eed0fc9d2af4548a626409b80576e37</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @arkoak! There is an FAQ about this issue here: https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md

**Comment by erikangelin-king** [comment]
Closing, reopen if it still does not work.
