### ISSUE TITLE
Search in the editor and report an exception.

### ISSUE THREAD

**Issue by lichongsw** [defold/editor2-issues#1757]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-19T14:21:54.831948</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ff44954b99e0a269dc1910c33cdb80b68e91afae</td></tr>
<tr><td>Defold engine sha</td><td>46d8b7e63d7e0f0f4acd545c46d25ca2b227a806</td></tr>
<tr><td>Defold version</td><td>1.2.123</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"e24feae926ae4e6ea4c6e9dc2356c868"'>e24feae926ae4e6ea4c6e9dc2356c868</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 385.54</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

![image](https://user-images.githubusercontent.com/29301662/37602347-1f24e612-2bc7-11e8-89d6-b2253b3736c6.png)

**Comment by erikangelin-king** [comment]
This was fixed a couple of weeks ago.
