### ISSUE TITLE
Project title cant be changed from My Project in game.project

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#176]
Open a project
Open game.project
Change title to anything
Save
Close the tab with game.project
Reopen game.project

Actual result: Back My Project, name is not saved

Expected result: To have the name of the project I opened in the first place, not my project.
And expected to be able to change it. 
And the correct name should be shown in the editor title bar.

**Comment by erikangelin-king** [comment]
I'm almost certain what you're seeing here is another (serious!) issue with the forms in general, that values are not stored on focus loss - like clicking outside the field or in the menu. I just tested and if you change the title setting and press enter while in the field, the new value will stick.
