### ISSUE TITLE
Resetting a label's scale from a template

### ISSUE THREAD

**Issue by Qwarr** [defold/editor2-issues#1781]
### Expected behaviour
When using a template of an object that has a label in it.
Pressing the reset button next to a label's scale to reset all values back to 1, 1, 1

### Actual behaviour
Pressing the reset button gives an error, "clojure.lang.ExceptionInfo: SCHEMA-VALIDATION"

### Steps to reproduce
Have a template that uses a label then change it's scale, try to reset using the reset button.

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-29T10:04:12.285850</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7b3ad804702670db33809955240a5de3671111b8</td></tr>
<tr><td>Defold engine sha</td><td>e3f2a48e6495946eb8aede3c843471bb037976aa</td></tr>
<tr><td>Defold version</td><td>1.2.124</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"110e94dccdc84ffdb2f1a688ef577a41"'>110e94dccdc84ffdb2f1a688ef577a41</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 760/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed!
