### ISSUE TITLE
Color icon of image causing render errors in atlases

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1786]
This is how it currently look
![screen shot 2018-04-03 at 15 36 06](https://user-images.githubusercontent.com/5273682/38252874-7f135e48-3755-11e8-8108-57131bdce223.png)

Something like this would make errors easier to find
![screen shot 2018-04-03 at 15 36 06](https://user-images.githubusercontent.com/5273682/38252894-90565fd4-3755-11e8-9d8b-7c090edc530d.png)

**Comment by AGulev** [comment]
https://github.com/defold/editor2-issues/issues/667

**Comment by AGulev** [comment]
This issue was solved in 1.2.138
https://forum.defold.com/t/defold-1-2-138-has-been-released/31459?u=agulev
DEFEDIT-1459 - Changed: Incorrect path casing now results in build error.
