### ISSUE TITLE
GPU: GDI Generic

### ISSUE THREAD

**Issue by tola** [defold/editor2-issues#1790]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-04T10:27:19.326624</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>05f53bc54bbb73befbb40580acb38dfc711fff90</td></tr>
<tr><td>Defold engine sha</td><td>e3f2a48e6495946eb8aede3c843471bb037976aa</td></tr>
<tr><td>Defold version</td><td>1.2.124</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6fd7fa6c78ad4ca4b3855d875630a304"'>6fd7fa6c78ad4ca4b3855d875630a304</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

> com.jogamp.opengl.GLException: The graphics device does not support: glGenBuffers
GPU: GDI Generic
Driver: 1.1.0
Please try to update your driver to the latest version and restart the application.

**Comment by erikangelin-king** [comment]
This is a pretty common error, see if any of this helps: https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md

**Comment by tola** [comment]
I was able to make it work by undoing the manifest change on the bundled java.exe
 https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md 
 
 Steps to fix this issue:

1. First, copy mt.exe from Visual Studio installation folder to your `Defold\package\jre\bin `
2. Second, open command prompt C:\Defold\packages\jre\bin\mt.exe -inputresource:java.exe -out:java.manifest
3. Look for a java.manifest file, open it with a text editor to comment out or remove this line from it `<supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"></supportedOS> `
4. Save java.manifest
5. Embed the manifest again. In your command prompt run `C:\Defold\packages\jre\bin\mt.exe -manifest java.manifest -outputresource:java.exe;#1`
6. Now, open Defold again. Error is gone.

 

Thank you @erikangelin-king

**Comment by erikangelin-king** [comment]
Glad it worked @tola Have fun!
