### ISSUE TITLE
Clicked on particle_blob.tilesource in the 'graphics' folder

### ISSUE THREAD

**Issue by dpMerchant** [defold/editor2-issues#1792]
### Expected behaviour
clicked on a tilesource file, should of showed me the tile
### Actual behaviour
popped up this message 
"java.lang.UnsatisfiedLinkError: /home/dagamer/.Defold/unpack/05f53bc54bbb73befbb40580acb38dfc711fff90/x86_64-linux/lib/libPVRTexLib.so: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /home/dagamer/.Defold/unpack/05f53bc54bbb73befbb40580acb38dfc711fff90/x86_64-linux/lib/libPVRTexLib.so)
### Steps to reproduce"
Fresh install of Xubuntu 14.04, installed Defold, created a new project, double clicked on particle_blob.tilesource
<hr/>

<table>
<tr><td>Build time</td><td>2018-04-04T10:27:01.827803</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>05f53bc54bbb73befbb40580acb38dfc711fff90</td></tr>
<tr><td>Defold engine sha</td><td>e3f2a48e6495946eb8aede3c843471bb037976aa</td></tr>
<tr><td>Defold version</td><td>1.2.124</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"558ef1404ce24374a0d884c7e466097c"'>558ef1404ce24374a0d884c7e466097c</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 5450 </td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1151</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>3.16.0-77-generic</td></tr>
<table>

**Comment by mathiaswking** [comment]
Hi @dpMerchant !
Defold is targeting Ubuntu 16.04 64-bit and upwards. And what you are getting is a problem of missing shared libraries on your install. Essentially, you're missing the dll's used when building with GCC 4.8 (which we use), and which are available on Ubuntu 16.04 64 bit.

I cannot guarantuee that it will work, but this [stackoverflow thread](https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx) seems to have some suggestions on how to install the needed gcc version to get usable libraries. You might also have to set the LD_LIBRARY_PATH in order for the executable to find them.

**Comment by erikangelin-king** [comment]
Reopen if still an issue
