### ISSUE TITLE
The debugger is no longer working [DEFEDIT-1350]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1799]
### Expected behaviour
The debugger should detect breakpoints

### Actual behaviour
The debugger doesn't react to breakpoints

### Steps to reproduce
Set a breakpoint. Run code.

Related to DEF-3162?
<hr/>

<table>
<tr><td>Build time</td><td>2018-04-09T17:07:31.540444</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>25827f84add1d8efaf9e91332274a11159e54463</td></tr>
<tr><td>Defold engine sha</td><td>f9995611e4d5befaa75d6b6d7becdd52823e01eb</td></tr>
<tr><td>Defold version</td><td>1.2.125</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.30.25 355.11.10.10.30.120</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Just merged a fix!
