### ISSUE TITLE
Cant preview particleFX

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#180]
Create a particleFX
Click spacebar to preview it

Actual result: 
Nothing happens.
Might be same issue as the other missing keyboard shortcuts. However, there is no option in the menu to preview the particleFX.

Defold version: 1.2.92
Defold sha: 6b93aa5a6e1fb7a0104253d435df4b0a3282b96f
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
It should work to select the ParticleFX in the outline, and then [Scene > Play] in the menu.

**Comment by sofiahe** [comment]
thanks [Scene > Play] works. However, not the keyboard shortcuts. which should be the general missing keyboard shortcuts bug.
closing this one.
