### ISSUE TITLE
error on building the project

### ISSUE THREAD

**Issue by AlexarJING** [defold/editor2-issues#1801]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-09T17:07:31.540444</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>25827f84add1d8efaf9e91332274a11159e54463</td></tr>
<tr><td>Defold engine sha</td><td>f9995611e4d5befaa75d6b6d7becdd52823e01eb</td></tr>
<tr><td>Defold version</td><td>1.2.125</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"52cc81370c2242cb8a5bbfaed2e00c0b"'>52cc81370c2242cb8a5bbfaed2e00c0b</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4400</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 20.19.15.4474</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AlexarJING** [comment]
java.lang.UnsatisfiedLinkError: Can't load library: C:\Users\Alexar\AppData\Local\Defold\unpack\25827f84add1d8efaf9e91332274a11159e54463\x86_64-win32\lib\PVRTexLib.dll

**Comment by erikangelin-king** [comment]
Hi @AlexarJING! Did you have multiple editors open when this happened? Have you tried restarting the editor?

**Comment by AlexarJING** [comment]
@erikangelin-king after restart everything seems to be ok, thank you !

**Comment by AlexarJING** [comment]
euh, yes, it happened after i tried to update and restart for the new version 125.
