### ISSUE TITLE
Synchronize fails to create a remote repository

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#1806]
1) Create empty project
2) File > Synchronize, Start

> Creating remote repository...
> A message body reader for Java class com.dynamo.cr.protocol.proto.Protocol$ProjectInfo, and Java type class com.dynamo.cr.protocol.proto.Protocol$ProjectInfo, and MIME media type application/json was not found

**Comment by RagnarSvenssonKing** [comment]
Fixed!
