### ISSUE TITLE
z position of nodes causes nodes in engine to not draw if they are outside of renderscript range

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1809]
https://forum.defold.com/t/z-position-of-nodes-on-same-layer/18895

**Comment by dapetcu21** [comment]
That's normal rendering behaviour. Your GPU clips any geometry outside the unit cube in screen space. I actually rely on this behaviour to render only what's behind a blur overlay to a render target.

**Comment by subsoap** [comment]
It needs to be documented otherwise it will probably be "fixed"

**Comment by sicher** [comment]
Sounds good to me. I'll fix that! Thanks.
