### ISSUE TITLE
Missing Blob error when saving after deleting script files

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#181]
Deleted two script files from project
Saved all.
Couldnt repeat.

Defold version: 1.2.92
Defold sha: 6b93aa5a6e1fb7a0104253d435df4b0a3282b96f
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

{:cause "Missing blob cd7e3769f9ef8098aafb3c5814f86d718fe76747",
 :via
 [{:type java.security.PrivilegedActionException,
   :message nil,
   :at
   [java.security.AccessController doPrivileged "AccessController.java" -2]}
  {:type org.eclipse.jgit.errors.MissingObjectException,
   :message "Missing blob cd7e3769f9ef8098aafb3c5814f86d718fe76747",
   :at
   [org.eclipse.jgit.internal.storage.file.WindowCursor open "WindowCursor.java" 147]}],
 :trace
 [[org.eclipse.jgit.internal.storage.file.WindowCursor open "WindowCursor.java" 147]
  [org.eclipse.jgit.diff.ContentSource$ObjectReaderSource open "ContentSource.java" 144]
  [org.eclipse.jgit.diff.ContentSource$Pair open "ContentSource.java" 280]
  [org.eclipse.jgit.diff.SimilarityRenameDetector hash "SimilarityRenameDetector.java" 372]
  [org.eclipse.jgit.diff.SimilarityRenameDetector buildMatrix "SimilarityRenameDetector.java" 285]
  [org.eclipse.jgit.diff.SimilarityRenameDetector compute "SimilarityRenameDetector.java" 138]
  [org.eclipse.jgit.diff.RenameDetector findContentRenames "RenameDetector.java" 491]
  [org.eclipse.jgit.diff.RenameDetector compute "RenameDetector.java" 377]
  [org.eclipse.jgit.diff.RenameDetector compute "RenameDetector.java" 347]
  [editor.git$unified_status invokeStatic "git.clj" 90]
  [editor.changes_view$refresh_BANG_ invokeStatic "changes_view.clj" 22]
  [editor.changes_view$make_changes_view$fn__68274 invoke "changes_view.clj" 124]
  [editor.ui$fn$reify__10201 handle "ui.clj" 485]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 86]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.CompositeEventDispatcher dispatchBubblingEvent "CompositeEventDispatcher.java" 59]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 49]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.Node fireEvent "Node.java" 8413]
  [javafx.scene.control.Button fire "Button.java" 185]
  [com.sun.javafx.scene.control.behavior.ButtonBehavior mouseReleased "ButtonBehavior.java" 182]
  [com.sun.javafx.scene.control.skin.BehaviorSkinBase$1 handle "BehaviorSkinBase.java" 96]
  [com.sun.javafx.scene.control.skin.BehaviorSkinBase$1 handle "BehaviorSkinBase.java" 89]
  [com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord handleBubblingEvent "CompositeEventHandler.java" 218]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 80]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.CompositeEventDispatcher dispatchBubblingEvent "CompositeEventDispatcher.java" 59]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.Scene$MouseHandler process "Scene.java" 3757]
  [javafx.scene.Scene$MouseHandler access$1500 "Scene.java" 3485]
  [javafx.scene.Scene impl_processMouseEvent "Scene.java" 1762]
  [javafx.scene.Scene$ScenePeerListener mouseEvent "Scene.java" 2494]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 380]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 294]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler lambda$handleMouseEvent$354 "GlassViewEventHandler.java" 416]
  [com.sun.javafx.tk.quantum.QuantumToolkit runWithoutRenderLock "QuantumToolkit.java" 389]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler handleMouseEvent "GlassViewEventHandler.java" 415]
  [com.sun.glass.ui.View handleMouseEvent "View.java" 555]
  [com.sun.glass.ui.View notifyMouse "View.java" 937]
  [com.sun.glass.ui.win.WinApplication _runLoop "WinApplication.java" -2]
  [com.sun.glass.ui.win.WinApplication lambda$null$148 "WinApplication.java" 191]
  [java.lang.Thread run "Thread.java" 745]]}

**Comment by sofiahe** [comment]
Close as cant reproduce?

**Comment by erikangelin-king** [comment]
Can't reproduce
