### ISSUE TITLE
error on activating a fx in editor2

### ISSUE THREAD

**Issue by AlexarJING** [defold/editor2-issues#1810]
![image](https://user-images.githubusercontent.com/15058075/38664719-f64ec6be-3e6c-11e8-8356-86ab46a7092c.png)

**Comment by britzl** [comment]
Does this happen for all particle effects or just a single one? Does it happen always? Can you please share a project where we can reproduce this?

**Comment by erikangelin-king** [comment]
Believe this has been fixed, reopen if it happens again.
