### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dincerguner** [defold/editor2-issues#1822]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-18T09:49:50.238070</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d4334f540409d1f8c1999ab26de6804d19b4d3be</td></tr>
<tr><td>Defold engine sha</td><td>f9995611e4d5befaa75d6b6d7becdd52823e01eb</td></tr>
<tr><td>Defold version</td><td>1.2.125</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"42544a87d8204140a71baabba8007a1d"'>42544a87d8204140a71baabba8007a1d</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Looks like there was some sort of issue authenticating with the servers. It could be that a firewall is interfering with the connection. Can you get it to work if you disable the firewall?

**Comment by erikangelin-king** [comment]
Can no longer see the specific error, but please check this FAQ and reopen if you need further help. https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md
