### ISSUE TITLE
Seems to be an issue with the Class here!

### ISSUE THREAD

**Issue by artcadev** [defold/editor2-issues#1829]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-23T16:33:33.104161</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>73274e58a26e38b1748c3dbe11a09bb6c81cc258</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4d07265a5b874d69884042bf90ba5d40"'>4d07265a5b874d69884042bf90ba5d40</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 391.01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This is a consequence of the previous error #1828, so closing.
