### ISSUE TITLE
Three button mouse setting doesn't do anything [DEFEDIT-770]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#183]
### Expected behaviour
After setting the editor to use a three button mouse, panning should work as in previous editor. (As a side note: Why does the setting exist at all? Can't both control methods be active at the same time? I see no conflict in them)

### Actual behaviour
Middle mouse dragging while holding alt just creates a selection box, and one button mouse controls are still active.

### Steps to reproduce
Change setting to three button mouse.
Try panning using alt+middle mouse.
(Note: restarting editor makes no difference)

<hr/>
Defold version: 1.2.92
Defold sha: 1c8ac905ef40848821d6b84c25483c0d125d9fb4
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
How I would prefer the control scheme to be, which would require no setting and would be very close to what editor 1 does, while dropping pointless things like Alt+Middle mouse. 

More importantly they are easy enough to discover for both one button users or three button users with no manual needed (three button mouse users would never need to use a key at all for viewport navigation).


**Select:** 
Left

**Pan:**
Middle
Alt+Left

**Rotate:**
Right
Ctrl+Left

**Zoom:**
Scroll wheel/trackpad scroll
Alt+Right
Ctrl+Alt+Left

**Comment by Malmer** [comment]
BLOCKER

**Comment by blurymind** [comment]
Please remove the requirement to hold the alt key. Simply middle clicking to pan would be ideal.
It's just such a common action

**Comment by matgis-king** [comment]
My only issue with this is that I don't think the right mouse button should rotate the scene on its own, because I think one might sometimes rotate the scene minutely by accident when bringing up the Right-click context menu. Apart from that, I think it makes sense to implement this as described.

**Comment by Malmer** [comment]
Yes, one could always make that into something that use a modifier key. Or simply just make a deadzone for it. Is a common approach for viewport navigation.
