### ISSUE TITLE
No preview of spine model with skins [DEFEDIT-1563]

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1832]
If your spine have skins you will not get a preview of it.

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-24T10:36:37.496984</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>64f555bb05f028251dcdecfcd21060c200b85ec3</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

[spine_scene.zip](https://github.com/defold/editor2-issues/files/1946300/spine_scene.zip)

**Comment by erikangelin-king** [comment]
Can you mail us a sample spine scene?

**Comment by Jerakin** [comment]
@erikangelin-king Attached a project
