### ISSUE TITLE
Exception when try to use curves

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1839]
Open next particle and choose an emitter in outline:
[untitled.zip](https://github.com/defold/editor2-issues/files/1947288/untitled.zip)
Switch tab to Curve Editor

<table>
<tr><td>Build time</td><td>2018-04-24T14:28:35.106868</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>68f05266ec2b9c8c3ef450cf8fa87f99ef9f3499</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4d4886d6107841bd98de25421540198e"'>4d4886d6107841bd98de25421540198e</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
In the attached untitled.particlefx there is a duplicate point under PARTICLE_KEY_ALPHA, maybe the result of a merge conflict. Anyhow, removing that should fix things. The proper fix for this issue is obviously to handle bad data on load.

**Comment by AGulev** [comment]
@erikangelin-king we fixed a bug manually in our particlefx files. It's strange, we made the emitters with bug by copy other one emitter without an error. But now we can't reproduce this process.
Anyway thank you!

**Comment by AGulev** [comment]
Can't reproduce anymore
