### ISSUE TITLE
dmengine.exe has stopped working

### ISSUE THREAD

**Issue by jj11d7t** [defold/editor2-issues#1848]
### Expected behaviour
When I press "Build" or run the .exe file after bundling, a window should open and I can play the game.

### Actual behaviour
When I press "Build" or run the .exe file after bundling, a window opens, but I get the Windows error message: "dmengine.exe has stopped working" or "myproject.exe has stopped working" -- 'myproject.exe' being the name of the .exe file I'm trying to run.

### Steps to reproduce
Press "Build" or run the .exe file produced after bundling.

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-26T18:01:47.417397</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d2aff4d90ed624f24194024c4ca4bd52f8ec2a94</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 22.20.16.4836</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/dmengine-exe-has-stopped-working-windows-10-defold-editor-2-0/19434/6

**Comment by jj11d7t** [comment]
Copy-pasted from my reply to the forum thread.

> You’re gonna get a kick out of this. Downdating worked. I’m not sure at exactly which graphics driver version dmengine.exe starts causing problems though, and in hindsight, I should’ve noted what version my driver was on initially… it was 22.y.z or something or other.
> 
> Anyway, here’s the steps to repro:
> 1. Open Device Manager.
> 2. Right-click Intel HD 520 Graphics driver.
> 3. From the dropdown menu, select ‘Properties’, then navigate to the ‘Driver’ tab.
> 4. Select ‘Rollback’ driver.
> 
> I am now on driver version 21.20.16.4627, and Defold has no problems building or bundling.
