### ISSUE TITLE
Editing shader constants is impossible, because the controls don't fit the area

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#185]
### Expected behaviour
Double-clicking a vector constant would make those values visually editable

### Actual behaviour
Double clicking shows controls which are scaled and cropped in a way that makes it impossible to see the value in the box and edit what is there.

### Steps to reproduce
Open a shader with shader user constants and try to edit them.

<hr/>
Defold version: 1.2.92
Defold sha: 1c8ac905ef40848821d6b84c25483c0d125d9fb4
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Minor changes to forms: tables now take more of available space and columns are resized to fit editing controls.

**Comment by Malmer** [comment]
It is still kinda buggy and hard to use, but now it is usable. Wouldn't call it production quality though.

**Comment by erikangelin-king** [comment]
I agree, we have several other issues logged about these forms - values not being committed when focus is lost etc, but I hope we've removed the immediate blocker.
