### ISSUE TITLE
Inconsistent 'Enter Key' Input in HTML5 Build (DEF-1866)

### ISSUE THREAD

**Issue by GamingBud** [defold/editor2-issues#1851]
There is an issue of inconsistency between Windows and HTML5 builds where, when pressing the enter key, it is not received as text input on Windows, and yet it IS on HTML5 builds. It passes it's text value as a tilde (~).

It is even illogically bypassing my parameter that BANS the tilde (~) as text input. My parameter is as follows:
`if action_id == hash("text") and action.text ~= "~" then -------------------------------------------------
msg.post("/Console#System_GUI", "message_system", ---------------------------------------------------
{text = "USER INPUTTED: '" .. action.text .. "' WITH ACTION_ID: " .. action_id})`

The post to my message handler returns: "USER INPUTTED: '~' WITH ACTION_ID: [text]", which makes absolutely no sense since the line before bans usage of the tilde as text input. What's also odd is the fact that it blocks regular tilde inputs.

Because my game relies upon text input for commands and chatting, this is literally game-breaking, and so far there is no workaround.

**Comment by britzl** [comment]
DEF-1866 (will be released in 1.2.135)

**Comment by AGulev** [comment]
@erikangelin-king 
released in https://forum.defold.com/t/defold-1-2-135-has-been-released/28297
