### ISSUE TITLE
Build HTML5 fails with response code 400 when using any dependencies [DEFEDIT-1379]

### ISSUE THREAD

**Issue by xero1** [defold/editor2-issues#1853]
### Expected behaviour
The editor (Editor 2) should compile and launch the HTML5 build.

### Actual behaviour
Build fails immediately with the following message:
```
java.io.IOException: Server returned HTTP response code: 400 for URL: https://github.com/subsoap/defos/archive/master.zip
java.io.IOException: Server returned HTTP response code: 400 for URL: https://github.com/subsoap/defos/archive/master.zip
```

### Steps to reproduce
Add any dependency URL to `game.project` and build using `Project > Build HTML5`

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-30T09:55:08.003048</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>894605c6b2a502666bf84578a2d4776e3547b8cd</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"14cca71881a546318e9227d34f6f3584"'>14cca71881a546318e9227d34f6f3584</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 980/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 390.65</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @xero1! Just merged a fix for this. You apparently needed to be logged in for this to work before. After the upcoming update this is no longer needed.
