### ISSUE TITLE
Moving tabs not working

### ISSUE THREAD

**Issue by getriot** [defold/editor2-issues#1855]
### Expected behaviour
Clicking and dragging a tab should let me move it
### Actual behaviour
Actually, clicking on a tab and dragging it isn't working for me
### Steps to reproduce
Open a code tab and try to drag it
<hr/>

<table>
<tr><td>Build time</td><td>2018-04-04T10:27:19.326624</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>05f53bc54bbb73befbb40580acb38dfc711fff90</td></tr>
<tr><td>Defold engine sha</td><td>e3f2a48e6495946eb8aede3c843471bb037976aa</td></tr>
<tr><td>Defold version</td><td>1.2.124</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 391.35</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
See also #255

**Comment by vlaaad** [comment]
Fixed! Check for updates! :tada:
