### ISSUE TITLE
Can't Download the Project

### ISSUE THREAD

**Issue by Thendplayer** [defold/editor2-issues#1856]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-30T09:55:08.003048</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>894605c6b2a502666bf84578a2d4776e3547b8cd</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"926ebff2977b4862a576f5d3368a994f"'>926ebff2977b4862a576f5d3368a994f</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Looks like we're unable to establish a connection to the server. Might be a firewall that is blocking connections. Can you try disabling the firewall?

**Comment by erikangelin-king** [comment]
Here are some further tips: https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md Please reopen if you need more help.
