### ISSUE TITLE
ERROR:GRAPHICS: gl error 1280

### ISSUE THREAD

**Issue by AnubisCode** [defold/editor2-issues#1857]
after the last update (1.2.126): 

if I create HTML5 app via: Project->Bundle->HTML5 Application
get this error
> ERROR:GRAPHICS: gl error 1280

but if open via Project->Build HTML5
there are all okay, without this bug.

<table>
<tr><td>Build time</td><td>2018-04-23T11:46:20.300696</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by AGulev** [comment]
I have the same bug only with debug bundle (bundle without release appmanifest)

**Comment by britzl** [comment]
Does this only happen on Windows? Still a problem? Can you please share a project?

**Comment by AnubisCode** [comment]
@britzl this bug was happened a long time ago (1.2.126) version. now all okay.

**Comment by britzl** [comment]
Ok, closing.
