### ISSUE TITLE
Atlas and HTML5

### ISSUE THREAD

**Issue by VincentLagerros** [defold/editor2-issues#1858]
### Expected behaviour
That everything works
### Actual behaviour
The screen is compleatly black - nothing
### Steps to reproduce
Just have a 4k picture in atlas when building it on HTML5 or on defold forum, you don't even have to use that pic in the game. (mine was 3100x2100)
<hr/>

<table>
<tr><td>Build time</td><td>2018-04-30T09:55:08.003048</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>894605c6b2a502666bf84578a2d4776e3547b8cd</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>GPU</td><td>GeForce GT 540M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 382.05</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
So, are you saying that everything works now or?

**Comment by erikangelin-king** [comment]
Please reopen if this is still an issue.
