### ISSUE TITLE
Game objects are not sorted alphabetically in outline

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#186]
Opening collections will show game objects in a different order in the outline compared to the previous editor. This may seem like a small thing, but the implications for workflow are huge. It makes it really hard to work with things which are in some way ordered, having to step through them and do some changes.

### Expected behaviour
The game objects should be sorted alphabetically, or there should be a way to re-order them.

### Actual behaviour
The order seems random

### Steps to reproduce

<hr/>
Defold version: 1.2.92
Defold sha: 1c8ac905ef40848821d6b84c25483c0d125d9fb4
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
Preferably the components on the parent game object should be sorted to be at the bottom of the list, after the child game objects, same as in editor 1.

**Comment by RagnarSvenssonKing** [comment]
Fixed
