### ISSUE TITLE
Error on sync - "stashing local changes did not successfully complete" - local files erased

### ISSUE THREAD

**Issue by 8bitskull** [defold/editor2-issues#1867]
I recently switched from Editor 1 to Editor 2. I created a local branch yesterday and I now attempted to synchronize my local changes, which caused an error message to pop up (visible in this [video clip](https://clips.twitch.tv/SneakyMuddySpiderPoooound)).

This seems to have failed the sync, and more importantly, has erased most of my local changes and files. The files that weren't erased are now locked and require admin privilege to open or copy. The lost files are completely gone it seems, I can't find them in the recycle bin or anything.

I haven't had any issues like this in Editor 1 and have been behaving the same way. I am happy to answer any questions as I am not sure what pertinent information I may have missed.

Report dump below.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-03T10:29:15.219020</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7472d566b3a0f0d492ab52ce6cbb279a47602be</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"10d29bb882a040a6ac747a7ed9f7acb0"'>10d29bb882a040a6ac747a7ed9f7acb0</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.43</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Ouch! So sorry for the data loss!
Were you using an external editor like Atom for instance? We have had problems with some external editors locking files, particularly on windows. Are you comfortable with command line git? If so you could see if at least parts of your work were stashed. I suggest you make a backup zip of the project directory as-is before trying any git wizardry though :) If you're willing to share the zip we could try to help out!

**Comment by 8bitskull** [comment]
Yep - I was using Atom.

Unfortunately I don't know anything about git, but on the bright side the most critical files were still open in Atom so I managed to salvage those. The remainder of the work I have already re-created (and promptly backed up). Thanks for the offer though!

**Comment by erikangelin-king** [comment]
Think we've had issues with Atom before. If you want to use the sync features from the editor, I think the safest bet is to close down Atom before. The offer stands if this happens again!

**Comment by 8bitskull** [comment]
I am not sure if this is relevant to the issue, but now that I think about it I am pretty certain I also lost files that were not open in Atom. For instance, I am sure I lost files like: .go, .atlas, .sprite, and .gui. Basically, anything that was created and hadn't been synced previously.

**Comment by erikangelin-king** [comment]
I guess JGit managed to stash or otherwise move the .go/.atlas etc and then choked when accessing some file you had open in Atom. Reopen the issue if you need any help.
