### ISSUE TITLE
Defold Unable To Build/Run Sample Project

### ISSUE THREAD

**Issue by ThobyV** [defold/editor2-issues#1868]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-03T10:28:50.186995</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7472d566b3a0f0d492ab52ce6cbb279a47602be</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"e9b121c13f9c47978dee08498694c939"'>e9b121c13f9c47978dee08498694c939</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Ironlake Mobile </td></tr>
<tr><td>GPU Driver</td><td>2.1 Mesa 18.0.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.16.6-300.fc28.x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
From the error message it seems the texture compression library could not be loaded properly. Could you check from the command line if `/home/<your user name>/.Defold/unpack/e7472d566b3a0f0d492ab52ce6cbb279a47602be/x86_64-linux/lib/libPVRTexLib.so` exists? If it exists, it could be that it requires some other library that is missing on your system. I'm a bit rusty on Linux but IIRC `ldd libPVRTexLib.so` or `objdump -p libPVRTexLib.so` should show the libraries it needs.

**Comment by ThobyV** [comment]
Thanks so much for your quick reply

After running >unpack

**Comment by erikangelin-king** [comment]
Just to clarify, `/home/myusername/.Defold/unpack/<sha of editor>` is where the editor unpacks some native libraries, it should be recreated everytime you start the editor.
Great you solved this on your own, thanks for the instructions :)

**Comment by ThobyV** [comment]
Thanks a lot for the clarification, love defold! Great work on it guys.
