### ISSUE TITLE
Crash when switching back to .gui file

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#1870]
### Expected behaviour
No crash

### Actual behaviour
Crash

### Steps to reproduce
Created one .gui file
Created one .gui_script file
Added one line of code in init()
Switched back to the .gui file
Boom

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-03T10:29:15.219020</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7472d566b3a0f0d492ab52ce6cbb279a47602be</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"308137866fe842adb1770619988ff97e"'>308137866fe842adb1770619988ff97e</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.30.25 355.11.10.10.30.120</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can you repro this?

**Comment by britzl** [comment]
No. Sorry. One time thing.
