### ISSUE TITLE
Seemingly unnecessary error messages

### ISSUE THREAD

**Issue by Ists-Cilveks** [defold/editor2-issues#1871]
Whenever I open the editor or resize the window, I get an error message.
I have an old, weak computer, which might be part of the problem.
The program *seems* to work, though I only got it today.

![The error](https://user-images.githubusercontent.com/38190993/39715779-0243d058-5237-11e8-9b95-29266aa9ec14.png)

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-07T16:22:34.891568</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0980fa0e972873c7ccec5175c7d6079c501d9748</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ddb3a4480f594a8c975417eacfaa81eb"'>ddb3a4480f594a8c975417eacfaa81eb</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Please reopen if you need more help!
