### ISSUE TITLE
Easy access to web-based profiler

### ISSUE THREAD

**Issue by nwestberg** [defold/editor2-issues#1878]
### Expected behaviour
This is not a bug report, rather a small feature request.

It would be great with a menu option or button that opens the profiler in the default browser. Very similar to what Help->Profile->Measure and Show does, but opening http://<Target IP>:8002/. This would make the profiler more accessible and more likely to get used.

### Actual behaviour
The user needs to enter IP and port manually in the browser.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-03T10:28:05.591816</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7472d566b3a0f0d492ab52ce6cbb279a47602be</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M395X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.42.15</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by vlaaad** [comment]
Fixed in newest editor-alpha channel update, new menu item <kbd> Debug → Open Web Profiler </kbd>
