### ISSUE TITLE
Particle play command does nothing

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#188]
### Expected behaviour
Pressing Cmd+P or the menu option should play the particles.

### Actual behaviour
Nothing happens.

### Steps to reproduce
Open any particle system and press play.

<hr/>
Defold version: 1.2.92
Defold sha: 1c8ac905ef40848821d6b84c25483c0d125d9fb4
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Fixed
