### ISSUE TITLE
Editor animations playing at a random rate

### ISSUE THREAD

**Issue by getriot** [defold/editor2-issues#1880]
### Expected behaviour
Work as it normally does
### Actual behaviour
After updating to the last version all the animations i set up just play at a random fps rate, making the game completely unplayable and untestable, i first thought that was the variable_dt, but it was checked already.
### Steps to reproduce
Update the editor
<hr/>

<table>
<tr><td>Build time</td><td>2018-05-09T12:09:39.008781</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5e191142e56da0ecbc874f924d6a96e32acc02a7</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 391.35</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by getriot** [comment]
Somehow it happens updating the editor, can't give you further information, i solved refreshing the stylesheet, which i don't know if makes sense or not

**Comment by erikangelin-king** [comment]
Hi @getriot!
Was this when running the game after building or bundling? Was the animation in an atlas or a tilesource? Has it happened again, can you reproduce it? If so, can you share the project where it happens?

**Comment by getriot** [comment]
Hi @erikangelin-king !
Unfortunately can't reproduce it for now, waiting for the next update to try to reproduce and fix it again, maybe i can make a video out of that to be more clear!
All i can say is that the animation was in the atlas and building or rebuilding the project wasn't fixing.

**Comment by erikangelin-king** [comment]
Please reopen if it happens again!
