### ISSUE TITLE
Text box wont accept escape characters

### ISSUE THREAD

**Issue by benjames-171** [defold/editor2-issues#1882]
### Expected behaviour

expected clipboard to paste into search textbox

### Actual behaviour

error message - java.lang.StringIndexOutOfBoundsException: String index out of range: 9

### Steps to reproduce

copy a tab character into the clipboard then attempt to paste into the 'find' field from the 'find and replace' dialog. This produces the above error

(I was attempting to convert all spaces to tabs in my code)

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-09T12:09:39.008781</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5e191142e56da0ecbc874f924d6a96e32acc02a7</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"477c12d700744501a0e43ba20c0147f8"'>477c12d700744501a0e43ba20c0147f8</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 22.20.16.4815</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
We have not been able to reproduce this error. It could be related to the contents of the file you were editing. Are you able to share a small bit of code that exhibits the problem?

Note that there is actually a **Convert Indentation** option under the Edit menu that might do what you want without using Find and Replace.

**Comment by erikangelin-king** [comment]
Please reopen or re-report if it happens again!
