### ISSUE TITLE
java.lang.NumberFormatException in console

### ISSUE THREAD

**Issue by DragoXqwas** [defold/editor2-issues#1884]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-03-22T11:44:26.240466</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>faf12542fa813f2e673f4f4c23e586affae54742</td></tr>
<tr><td>Defold engine sha</td><td>46d8b7e63d7e0f0f4acd545c46d25ca2b227a806</td></tr>
<tr><td>Defold version</td><td>1.2.123</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d989fcef745d46e18f8d5b83aa1b840e"'>d989fcef745d46e18f8d5b83aa1b840e</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.4358</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @DragoXqwas!
Can you reproduce this error?

**Comment by erikangelin-king** [comment]
Please report if it happens again.
