### ISSUE TITLE
error on sync the project created in local machine.

### ISSUE THREAD

**Issue by AlexarJING** [defold/editor2-issues#1885]
here is the error message 
Creating remote repository...
A message body reader for Java class com.dynamo.cr.protocol.proto.Protocol$ProjectInfo, and Java type class com.dynamo.cr.protocol.proto.Protocol$ProjectInfo, and MIME media type application/json was not found

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-06T10:48:49.123524</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4be7483ab997ab58c7d8fe930a73774cd81baae5</td></tr>
<tr><td>Defold engine sha</td><td>e3f2a48e6495946eb8aede3c843471bb037976aa</td></tr>
<tr><td>Defold version</td><td>1.2.124</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 8670D</td></tr>
<tr><td>GPU Driver</td><td>4.5.13413 Compatibility Profile Context 15.201.2811.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This was fixed in a later version of the editor, please update and try again (There should be an update notification in the bottom right corner of the editor).
