### ISSUE TITLE
error clicking on main.atlas

### ISSUE THREAD

**Issue by mhsdeveloper** [defold/editor2-issues#1888]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-15T13:40:35.945853</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c6518fdafa9e0d23e1a3cd86b351d0b8021ddda2</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4a6ae775c60e434098f758097fc7a30c"'>4a6ae775c60e434098f758097fc7a30c</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Kabylake GT2 </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.0.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.16.4-1.el7.elrepo.x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @mhsdeveloper! Looks like a dynamically linked library is missing on your system. This has happened to another user here: #1792 We never heard back, could you try the same solution?
https://stackoverflow.com/questions/20357033/how-to-fix-program-name-usr-lib-x86-64-linux-gnu-libstdc-so-6-version-cxx

**Comment by erikangelin-king** [comment]
@mhsdeveloper did it work?

**Comment by mhsdeveloper** [comment]
No; on Centos 7 the newest version gcc 4.9 doesn't seem to bundle with the lib that's missing.

Ok, have a mac nearby that I can develop on for now.


thanks for the follow up!

________________________________

**Comment by erikangelin-king** [comment]
Closing for now, please report if it happens again. The error information was automatically purged :/
