### ISSUE TITLE
error clicking on main.atlas

### ISSUE THREAD

**Issue by mhsdeveloper** [defold/editor2-issues#1889]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-15T13:40:35.945853</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c6518fdafa9e0d23e1a3cd86b351d0b8021ddda2</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Kabylake GT2 </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.0.1</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.16.4-1.el7.elrepo.x86_64</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#1888
