### ISSUE TITLE
Switching back to a collection tab resets the scrolling of the outline

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#189]
This is **very** frustrating when switching back and forth between tabs, for instance when you want to check something in an other tab, and your scroll position in the outline is lost.

### Expected behaviour
The scroll position should remain what it was.

### Actual behaviour
It is reset to the top position.

### Steps to reproduce
In collection with many items: Scroll down
Switch tab
Switch back to collection tab.

<hr/>
Defold version: 1.2.92
Defold sha: 1c8ac905ef40848821d6b84c25483c0d125d9fb4
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by sicher** [comment]
Cannot reproduce. Fixed?
