### ISSUE TITLE
Error Report: Trying to create a new project

### ISSUE THREAD

**Issue by gilmarsquinelato** [defold/editor2-issues#1893]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-17T12:46:37.670024</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fc90c9a16a9a7ce4e9404cae83854919d47f6725</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6bd2d21d61cd402287f82d51a2b99e40"'>6bd2d21d61cd402287f82d51a2b99e40</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Sorry, the error contained no useful information so we have nothing to go on here. Please file a new issue if it happens again.
