### ISSUE TITLE
Editing external library files results in "not all files saved" warning when exiting.

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#190]
### Expected behaviour
While it is pretty cool that you can go in and add/modify code in libraries you have imported (great for debugging!), there should be some warning or indication while editing or when doing "File - Save all" that the changes you've made can not be saved. Because now the only warning you get is when you exit the application, and it tells you that not all files are saved.

### Actual behaviour
I get a warning only on exit that not all files are saved.

### Steps to reproduce
Edit a script in an imported library
Run the game - The line you added executes (which is pretty cool!)
Do File - Save All
Exit Defold

<hr/>
Defold version: 1.2.92
Defold sha: f96542b6ca540e8e3d79ed4b9c88c443eeaa838a
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Fixed!
