### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by tgdc** [defold/editor2-issues#1901]
### Steps to reproduce
Creating a new project.

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-18T11:46:42.076955</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>72c38cf63238417e13aea630a63980c115455399</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"31f157d1a82445d883b40fec4834a6dc"'>31f157d1a82445d883b40fec4834a6dc</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-20-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @tgdc! Hmm, this looks like a permissions issue. Did you ever get past the welcome screen? Could you try downloading the template project to another directory?

**Comment by erikangelin-king** [comment]
@tgdc Ping?

**Comment by erikangelin-king** [comment]
Please reopen if it happens again, the error info disappeared.
