### ISSUE TITLE
NPE when moving a go, i think

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1904]
### Steps to reproduce

Not reproducible. Happened once.

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-22T10:24:16.870974</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>afbf5872bbd461d6e16c42ee179a4ffddec6919c</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"41d7553be7134751b74d5c32a598dcab"'>41d7553be7134751b74d5c32a598dcab</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
No error :(
