### ISSUE TITLE
Editor2 GUI scene. Box's order issue

### ISSUE THREAD

**Issue by Dragosha** [defold/editor2-issues#1906]
As you can see at screenshots below there is issue with background box that overlaps other boxes.
![2018-05-23_14-16-50](https://user-images.githubusercontent.com/842807/40415914-793672be-5e95-11e8-9d68-69bf57101d62.png)
![2018-05-23_14-28-59](https://user-images.githubusercontent.com/842807/40416143-fce07f56-5e95-11e8-847b-5d8abe047c56.png)
There is no "layers" settings for this boxes. And all worked correctly before Windows 10 had made last update :-O

p.s. It issue observed only at editor, in dmengine all correct.

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-23T09:28:32.990195</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>076e116ae09c690723ce05abbb953bfab55b606a</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>GPU</td><td>GeForce GT 640/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.73</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by subsoap** [comment]
The latest Windows 10 update was a real doozy. Several things broke for me orz

**Comment by erikangelin-king** [comment]
Hi! Did you also update the editor before this happened?

**Comment by Dragosha** [comment]
@erikangelin-king 
1. I have 1.2.127. It works ok.
2. Windows 10 have made the big update and reboot the system.
3. I opened the editor and saw this issue first time.
4. updated the editor to 1.2.128
5. the issue did not disappear
6. now I back to 1.2.127 on this PC and it still


**UPD: the same issue on my Mac !**
screenshot:
![2018-05-24_14-28-19](https://user-images.githubusercontent.com/842807/40476985-ce128d12-5f5e-11e8-95af-1eba1c1e4010.png)

<table>
<tr><td>Build time</td><td>2018-05-18T11:47:06.528922</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>72c38cf63238417e13aea630a63980c115455399</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.30.12</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.2</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Thanks @Dragosha! I recently made some changes to the node reordering code and might have broken the rendering. Will check on monday since we’re on a conference.

**Comment by erikangelin-king** [comment]
Just merged some fixes for gui node render order in the editor. Please reopen if it still looks weird after the next update!

**Comment by erikangelin-king** [comment]
Hi @Dragosha! We failed to merge this sprints fixes into what becomes the `stable` channel. They are however available on the `editor-alpha` channel which is what you will be on by default if you download the editor from the dashboard, so as a workaround we suggest downloading a new editor. If the frequent updates becomes an issue, I think you can temporarily blank out the `[build] ... channel =` field in the `config` file to disable them.

**Comment by Dragosha** [comment]
@erikangelin-king  ok ) It's not a big problem, just inform you.

All is correct on Mac:
![2018-06-05_17-24-58](https://user-images.githubusercontent.com/842807/40975816-99e16c62-68e5-11e8-9f5a-1aedd8844833.png)
Both computers I've updated in editor trough blue link "update is available".

**Comment by erikangelin-king** [comment]
So everything looks correct on both Mac & Windows on `editor-alpha` now? Can I close the issue?

**Comment by erikangelin-king** [comment]
@Dragosha I'm going through gui related issues, this is fixed right?

**Comment by Dragosha** [comment]
@erikangelin-king 
all correct now:
![2018-08-21_12-58-50](https://user-images.githubusercontent.com/842807/44388634-0976b800-a542-11e8-8523-20d69b5f9a0c.png)
