### ISSUE TITLE
Editor 2 build errors get sent to all open copies of the editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1909]
If you build a project with a NE and there is an error all copies of the editor are sent the build error and not just the copy which did the NE building

**Comment by erikangelin-king** [comment]
Hi @subsoap! Interesting! Can't for the life of me understand how this could happen :)
* You're running a couple of editors at the same time. With the same project open?
* After building from one editor, the build errors show up in all editor instances?

**Comment by subsoap** [comment]
At the time of posting this, I had 3 copies of the editor open on Windows 10, they were each of a different project. I had a Native Extension build error, and it appeared in the logs of all 3 copies of the editor.

**Comment by erikangelin-king** [comment]
Wait, so you mean in the log file, like the ones you find with `Help > Show Logs`? I thought you ment in the `Build Errors` tab?

**Comment by subsoap** [comment]
I meant the error showed up in Build Errors for all three copies of the editor not log files.

**Comment by erikangelin-king** [comment]
Hi @subsoap! Going through old "more-info" issues. Can you still repro this bizarre behaviour?
