### ISSUE TITLE
Texture profile path was changed really bad

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#191]
Before editor 2 in game.project:
`texture_profiles = /main/render/game.texture_profiles`

After editing any file in the project and doing Save All:
`texture_profiles = c`

<hr/>
Defold version: 1.2.92
Defold sha: 2c2cf57f335326e92de7fdaf952a14ac4fc24646
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by AGulev** [comment]
Now my path looks like 
texture_profiles = /render/custom.texture_profiles
after editing something in Editor 2 
texture_profiles = /render/custom.texture_profilesc
- and new path an error in editor 1

Could not find supplied texture_profiles file: /render/custom.texture_profilesc	game.project	/RedHood/content	Unknown	Problem

**Comment by erikangelin-king** [comment]
Oops, thanks for reporting!

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-585

**Comment by matgis-king** [comment]
A fix has been merged into the dev branch. It should reach the builds during the day.
