### ISSUE TITLE
Sprite cloning error

### ISSUE THREAD

**Issue by Rasulbek** [defold/editor2-issues#1915]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-22T11:28:07.809896</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>34834e835bccb4a7aace4cde1d8bdacc07d06e43</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d7b4dd2f53bd414aa61987bd0045d963"'>d7b4dd2f53bd414aa61987bd0045d963</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.4252</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Rasulbek! Can you provide a repro project for this?

**Comment by Rasulbek** [comment]
Actually it was my bad. Issue solved already, thanks for attention.

**Comment by erikangelin-king** [comment]
@Rasulbek This looks like an error that occurred during Build, and we would like to fix it properly - i.e. you should get a build error instead of an ugly error reporting dialog :) So, please let us know if you manage to reproduce the error.
