### ISSUE TITLE
Editor freezes for a while with (Not Responding) while bundling

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1916]
On mac I get a progress bar, on windows it freezes and looks like it crashed the editor.

(Android)

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-22T15:28:17.333815</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3e2193e5cb163317aebc4ac67c50f9ec9d0c2d29</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Everytime? Every project?

**Comment by matgis-king** [comment]
We just tried this on Windows, and we do get a progress bar when selecting Project > Build. We don't yet have a progress bar for bundling the project, but that is the same on macOS.

Is there something special about this project? Does it use native extensions?

**Comment by subsoap** [comment]
For me on Windows 10 the editor does not "freeze" when building unless there is native extension / appmanifest changes.

**Comment by Jerakin** [comment]
It was a very minimal project, no dependencies at all.

**Comment by erikangelin-king** [comment]
Can you repro with that project, and if so, can you share it?

**Comment by Jerakin** [comment]
As I was going to get some more info for this I realized that I wrote building and _not bundling_. Is this still not known?

**Comment by matgis-king** [comment]
That makes sense. We've not yet implemented a progress bar when bundling. I'm updating the title to reflect that it is not specific to Windows.

**Comment by matgis-king** [comment]
In the original report you mention that you do get a progress bar on Mac. You do if you choose **Project > Build**, but not when bundling (on Mac or on any other OS). It's annoying and we'll implement it eventually, but we are focusing on other issues at the moment.

**Comment by Jerakin** [comment]
Yeah, I misremembered that part. However, the issue is that defold (seemingly) crashes when bundling.

**Comment by matgis-king** [comment]
We now bundle on a background thread, so you can keep working while bundling.
