### ISSUE TITLE
Help Defold isn't working right and this error keeps coming up.

### ISSUE THREAD

**Issue by Movie1053** [defold/editor2-issues#1918]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-03T10:29:15.219020</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7472d566b3a0f0d492ab52ce6cbb279a47602be</td></tr>
<tr><td>Defold engine sha</td><td>32ba5eaa128e4b54113fb36eb4b9eff33d8582b3</td></tr>
<tr><td>Defold version</td><td>1.2.126</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"737facf851244371b1456e2d6d0b5873"'>737facf851244371b1456e2d6d0b5873</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Movie1053! This is a pretty frequent issue likely having to do with your graphics card drivers. Please follow the instructions here and report back whether it worked: https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md

**Comment by Movie1053** [comment]
Sorry to bother you, I'm new to this and can't get past the first step, lol. Where and how do I find the mt.exe if I already have it installed, and where did I get one if I don't have it.

**Comment by erikangelin-king** [comment]
Hi @Movie1053! Did you try just updating your graphics card drivers first? If that does not help and you have an older Intel HD card, I can help out. If you're unsure about what graphics card you have, check the output of `dxdiag` (https://support.microsoft.com/en-us/help/4028644/windows-open-and-run-dxdiagexe)

**Comment by Movie1053** [comment]
This is the version I have
DxDiag Version: 10.00.16299.0015 64bit Unicode

Card name: Intel(R) HD Graphics
        Manufacturer: Intel Corporation
           Chip type: Intel(R) HD Graphics (Core i5)
            DAC type: Internal
         Device Type: Full Device

**Comment by erikangelin-king** [comment]
That looks like one of the problematic intel cards. No warranties or guarantees or nothing, but I've attached a `java.exe` patched according to the instructions.  Replacing the java.exe found in your `Defold\packages\jre\bin` with this one could solve the problem.
[java.zip](https://github.com/defold/editor2-issues/files/2054343/java.zip)

**Comment by Movie1053** [comment]
It's working great now thanks so much!!! :)
