### ISSUE TITLE
No way to prevent an update of the editor when restarting

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#192]
Our workflow requires us to lock on a specific version of Defold, and only upgrade at set intervals which we control (for testing purposes). Editor 2 will notify you of a new version and allow you to cancel the update. However, when you restart the app manually for any reason it will be updated automatically.

There should be a way to postpone an update until it fits the release/testing schedule of the game you're working on. Like in editor 1.2.x I could always just answer "No" to the update question.

<hr/>
Defold version: 1.2.92
Defold sha: 87c1c209a4b0c3652ab0738016a16afa734a79b3
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
In short what we want is something similar like having these buttons (the titles are conceptual):

[Upgrade and Restart] - Same as now. Restarts and reinstalls.
[Upgrade on next Startup] - Same as cancel does now. Installs next time you start
[Skip this version] - Doesn't bother again with notifications about this specific version of the editor. Will not install anything. An option to install the new version on demand should still exists from the menu bar.

**Comment by matgis-king** [comment]
Currently the editor will download updates in the background and automatically upgrade on next startup despite the users wishes. The simplest possible fix would be to simply ask whether or not the new version should be installed when we detect a new version on the server. If you choose not to, we do nothing, but will keep pestering you about it as new versions appear.

**Comment by Malmer** [comment]
Fixed?

**Comment by erikangelin-king** [comment]
Yes!
