### ISSUE TITLE
Request: Double click log message in the console goes to file and line [DEFEDIT-1434]

### ISSUE THREAD

**Issue by nwestberg** [defold/editor2-issues#1920]
### Expected behaviour
Hey, really appreciate line and number for script errors (DEFEDIT-1394) !
It would be great if similarly, double clicking runtime log messages in the console output window would take me to the file and line that did the printing. It would be very useful when navigating large projects / debugging other peoples code.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-22T11:28:07.809896</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>34834e835bccb4a7aace4cde1d8bdacc07d06e43</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
I second that!
