### ISSUE TITLE
NPE when closing code editor with cmd-w

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1921]
### Steps to reproduce

Not able to repro this.

<hr/>

<table>
<tr><td>Build time</td><td></td></tr>
<tr><td>Defold channel</td><td></td></tr>
<tr><td>Defold editor sha</td><td></td></tr>
<tr><td>Defold engine sha</td><td></td></tr>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"99130e70030d463284684dbc477e0827"'>99130e70030d463284684dbc477e0827</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_162-b12</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Error auto pruned :(
