### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by Christiantoledo** [defold/editor2-issues#1923]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-29T14:24:05.623360</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>52ab435c47551384104157e01aa9f4989e93c53a</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d177b397c84a43f6b42a32b4461cfa6e"'>d177b397c84a43f6b42a32b4461cfa6e</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Christiantoledo! This is a pretty common error, please follow the instructions here: https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md Report back whether it worked.
