### ISSUE TITLE
Unable to build game [DEFEDIT-1400]

### ISSUE THREAD

**Issue by abjornr** [defold/editor2-issues#1924]
### Expected behaviour
Being able to build the game
### Actual behaviour
![capture](https://user-images.githubusercontent.com/15891275/40707034-ce9e2882-63ef-11e8-8033-49be04de67eb.PNG)
### Steps to reproduce
Left the editor open during the night, when trying to start this morning got this error in every file.
Solved by restarting the computer, was not enough to just restart defold.
<hr/>

<table>
<tr><td>Build time</td><td>2018-05-28T12:43:12.191155</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>733c91c99765a9103b9af9465397e1841bacfdb0</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 381.67</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @abjornr! We've seen this type of error when running multiple editors simultaneously (the editors both think they own the unpack directory and may remove/overwrite stuff breaking each others assumptions). What I don't get is why you had to restart Windows to make it work again. It really should be enough to restart a single editor. Could you send me (erik.angelin@king.com) the editor log files from `Help > Show Logs`?
In any case, please let us know if you find a way to consistently reproduce this.

**Comment by erikangelin-king** [comment]
Reopen if it's still an issue!
