### ISSUE TITLE
NPE when doing something

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#1929]
Cannot reproduce. :)

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-31T12:28:25.243367</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1d3cc191481a8042b776fee43875f86cc0adb450</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"87d6f6b1bea64073bb93ccf66954986e"'>87d6f6b1bea64073bb93ccf66954986e</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Error auto pruned. Think it you might have been scrolling (mouse wheel / apple mouse) while closing the tab, that seems to cause NPE's!
