### ISSUE TITLE
Geometry wars demo project renders wrong [DEFEDIT-738]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#193]
Opening and running the Geometry wars demo project in the new editor exposes rendering errors. It looks like the glow pass is vertically inverted or something similar.

<img width="1280" alt="screen shot 2016-11-16 at 09 55 40" src="https://cloud.githubusercontent.com/assets/65613/20342627/24d74646-abe3-11e6-96a1-7cd799fce36a.png">

**Comment by matgis-king** [comment]
Tested this in the `dev` branch just now. Seems to be fixed. Geometry Wars still seems to be affected by #195, though. You can see the engine exhaust particles from the players ship spawn in the wrong direction and size. Curiously the engine particles look correct in the above screenshot. Hmm.

Anyway, closing this for now.
