### ISSUE TITLE
Extra info for #1926

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1930]
I did something like this:
1. Copied a line
2. pasted it
3. undo the pasted
4. pressed enter
5. pasted it again

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-31T10:55:50.198405</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3cee4731ac15ce305fac4c30f2b1b78958ef06e3</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"92ea1c0ab3c1428d89a3783aa18b71ac"'>92ea1c0ab3c1428d89a3783aa18b71ac</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Thanks! Added to original issue.
