### ISSUE TITLE
Build android

### ISSUE THREAD

**Issue by guidosette** [defold/editor2-issues#1931]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-31T12:28:25.243367</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1d3cc191481a8042b776fee43875f86cc0adb450</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a07fb09c62834ccba9c177885730a678"'>a07fb09c62834ccba9c177885730a678</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD - FirePro D300 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.66.31</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @guidosette! This happens when you click a build error. Can you share the project with us so we can have a look? erik.angelin@king.com

**Comment by guidoDiStudio** [comment]
Hi, how can i share the project with you?
Thanks

**Comment by erikangelin-king** [comment]
Hi again @guidoDiStudio! If this still happens, you can add me to the team from the dashboard (erik.angelin@king.com).

**Comment by erikangelin-king** [comment]
Please reopen if it's still an issue!
