### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ilyanengen** [defold/editor2-issues#1933]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-04T12:41:42.851480</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cf13ba73542b93add32f0e0f107cbb2abab5993a</td></tr>
<tr><td>Defold engine sha</td><td>30b201abdb7224683a3b3de2a02b22946dbbd427</td></tr>
<tr><td>Defold version</td><td>1.2.129</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6d5ad330c33046aabb0b28b97173ffc4"'>6d5ad330c33046aabb0b28b97173ffc4</a></td></tr>
<tr><td>GPU</td><td>GeForce 310M/PCI/SSE2</td></tr>
<tr><td>GPU Driver</td><td>3.1 NVIDIA 189.69</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @ilyanengen! Does this happen all the time? What if you restart the editor?

**Comment by ilyanengen** [comment]
@erikangelin-king Sorry for disturbing you. Editor restart solved the problem.
PS: The error occured when I tried to build a new Walking astonaut tutorial.
