### ISSUE TITLE
OutOfMemory Error, Windows

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#1945]
Think I accidentally iterated a table as I edited it or something

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-22T15:28:17.333815</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3e2193e5cb163317aebc4ac67c50f9ec9d0c2d29</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d8095e329c634b5da5d7c4d8b8046bf8"'>d8095e329c634b5da5d7c4d8b8046bf8</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by Jerakin** [comment]
While this error is building up I print a table to the console and after the error is dismissed console stops working completely

**Comment by erikangelin-king** [comment]
Can you provide a repro for this?

**Comment by Jerakin** [comment]
Unfortunatelly I have completely forgot what I was doing when this happened. I say close it for now, and re-open/re-report if it happens again.

**Comment by Jerakin** [comment]
Might have been editing a table as I was iterating it
