### ISSUE TITLE
Math not always working in properties?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1946]
Sometimes I try to do simple math in property edit boxes, but it does not always work. I press enter, it doesn't compute the result for simple stuff like 1024/2 etc.

**Comment by sicher** [comment]
Do you get mixed results in the same edit box or is it not working in certain boxes?

**Comment by subsoap** [comment]
Yes/no. It works sometimes in a single edit box then inexplicably doesn't. Or when I edit another box with a math formula then press enter and it goes through then it also solves any other formula in another field of the same property list.

**Comment by sicher** [comment]
I have tried to replicate this without success. Do you know a way to reproduce this issue?

**Comment by sicher** [comment]
Alright, thanks. I'm closing this for now. If it reappears, we'll reopen it.
