### ISSUE TITLE
Can't create a bundle for macOS

### ISSUE THREAD

**Issue by pullingour** [defold/editor2-issues#1950]
### Actual behaviour

return Error Message ``` '/Users/username/Desktop/game/gamename' exists but is a directory```

### Steps to reproduce

Every time this problem occurs when I try to bundle for macOS but others are fine.

### Dependencies

[https://www.defold.com/community/projects/76569/](https://www.defold.com/community/projects/76569/)

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-11T10:10:52.962382</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>2769946c7c87e5d4da537fd994a880771245b70f</td></tr>
<tr><td>Defold engine sha</td><td>30b201abdb7224683a3b3de2a02b22946dbbd427</td></tr>
<tr><td>Defold version</td><td>1.2.129</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d482519cee1544158162d1257f9168b4"'>d482519cee1544158162d1257f9168b4</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.42.15</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi! The attached error does not appear to match your description, so we cannot tell what went wrong. It looks like you are trying to output the bundle to a path that contains a conflicting directory name at a location where we expect a file of the same name.

Try using a different bundle output path. If that does not work, there might be something strange with your project. If you are able to share it with us, we could take a look at it. You can direct-message me as `mats.gisselson` on the Defold forum if you want me to take a look.

**Comment by pullingour** [comment]
@matgis-king Sorry for late reply. I sent message and project files on Defold forum.

**Comment by matgis-king** [comment]
Hi! I took a look at your project and found the issue. It seems the `game.project` file specifies an OSX App Icon, but the value is set to an empty string.

![empty-app-icon](https://user-images.githubusercontent.com/22448941/41531064-78b6ccb4-72f2-11e8-8516-67c58150e916.png)

Simply click on the little "revert" button next to the **App Icon** setting, and it should bundle properly. Feel free to reopen this issue if this does not fix your problem!

I've registered an internal ticket about handling this situation better and showing a more helpful error message.

**Comment by pullingour** [comment]
@matgis-king 
It worked fine! Thank you!!
