### ISSUE TITLE
Issuing app hide command (Cmd+H) on OS X shows a java about dialog

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#196]
### Expected behaviour
The app window would be hidden

### Actual behaviour
About java popup appears

### Steps to reproduce
Press Cmd+H or click the menu "java" - "Hide com.defold.editor.Start"

(Also: the app title probably shouldn't be "Java" and the hide option should probably just read as "Defold")

<hr/>
Defold version: 1.2.93
Defold sha: 5fc0def992295afce60ccb53f977a6d2342655bc
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Fixed!
