### ISSUE TITLE
Nice-to-have: Open asset dialog keep state [DEFEDIT-1495]

### ISSUE THREAD

**Issue by nwestberg** [defold/editor2-issues#1964]
It would be nice if the open asset dialog kept it's state between invocations (by state I mean what's currently typed into the text field and the current result set.) 

XCode for example does this and IIRC visual studio/visual assist does it too. Why? Well, imagine working on a game that has, say, a fish feature. Then it's likely to need to open a slew of files which all have something to do with fish. fish_manager, fish_factory, fish_ui, ... etc.  In such cases, it's helpful when the open asset dialog continues from where it left off. Especially helpful in large projects where it's difficult to keep track of everything.

**Comment by AGulev** [comment]
Issue was fixed in 1.2.143 
https://forum.defold.com/t/defold-1-2-143-has-been-released/36627
DEFEDIT-1495 - Added: Remember Open Assets dialog settings between sessions
