### ISSUE TITLE
Error occurs when attempting to debug a game on Android device [DEFEDIT-1409]

### ISSUE THREAD

**Issue by EgillAntonssonKing** [defold/editor2-issues#1967]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-18T16:06:50.083684</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4f2478d053dd63a6fcaa794b994256e7b0b25038</td></tr>
<tr><td>Defold engine sha</td><td>3abf70ee10dfb24e43529ff2e7ffbf1905ef5c19</td></tr>
<tr><td>Defold version</td><td>1.2.130</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2be4e4aa09b94d5fb54bb2ff470d0f3b"'>2be4e4aa09b94d5fb54bb2ff470d0f3b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
The game is probably taking too long to respond because debugging is enabled during initialisation. We're discussing changing this behaviour. In the meantime, is it an acceptable workaround to start the game + attach instead?

**Comment by matgis-king** [comment]
This seems to be due to a network error or because the game has locked up and is no longer responding to calls. In this case we cannot attach the debugger, since the game is unable to run the code required to start the debugger server.

We should improve the error message, though.

**Comment by EgillAntonssonKing** [comment]
Answering @erikangelin-king question (got it in an email, but don't see it here)
"In the meantime, is it an acceptable workaround to start the game + attach instead?"

I can do that in cases where I don't have to debug very early in the code initialization,
in that case it's hard to do.

**Comment by matgis-king** [comment]
Yeah, we removed that because we found this error was actually from choosing Attach Debugger, not Run With Debugger.

**Comment by matgis-king** [comment]
Improved error message.
