### ISSUE TITLE
Deu Panic Linux Ubuntu 18

### ISSUE THREAD

**Issue by marcioreyes** [defold/editor2-issues#1969]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-13T14:54:11.173394</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>381307d375b2955aa85f43aabcb0014fbc0ed21d</td></tr>
<tr><td>Defold engine sha</td><td>30b201abdb7224683a3b3de2a02b22946dbbd427</td></tr>
<tr><td>Defold version</td><td>1.2.129</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 530 (Skylake GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.0.0-rc5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-23-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @marcioreyes! What happened?

**Comment by erikangelin-king** [comment]
Reopen if whatever it was, happens again!
