### ISSUE TITLE
No hotkey for file rename DEFEDIT-1517

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#197]
### Expected behaviour
Pressing F2 should rename selected file. And there is no new replacement hotkey either.

### Actual behaviour
Nothing happens. No hotkey bound to action.

<hr/>
Defold version: 1.2.93
Defold sha: 0ebee65fcbcb5dd1716c011214147aa0b4a1f594
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Jerakin** [comment]
If this is an easy thing I would love this to be added. Don't know how often I press F2 to rename a file only to be dissapointed. :(

**Comment by 8bitskull** [comment]
+1, was about to post a suggestion regarding this before finding this issue.

**Comment by K-Klear** [comment]
Just adding my support. I keep mashing F2 all the time out of habit.
