### ISSUE TITLE
Error on launch project

### ISSUE THREAD

**Issue by stoarch** [defold/editor2-issues#1970]
### Expected behaviour
Game launched after build
### Actual behaviour
Error: java.util.concurrent.ExecutionException: java.lang.Error: Invalid memory access
java.lang.Error: Invalid memory access
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-23T09:28:32.990195</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>076e116ae09c690723ce05abbb953bfab55b606a</td></tr>
<tr><td>Defold engine sha</td><td>477e0e1034b76a6f9e07fb5ead5dc10adcd2ba6d</td></tr>
<tr><td>Defold version</td><td>1.2.128</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"29752a0b76064854b3bd9f70ea50ab57"'>29752a0b76064854b3bd9f70ea50ab57</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4400</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 20.19.15.4642</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @stoarch! Can you reproduce this error? If so, can you give us access to the project? We suspect some particular image is causing the error and it would be interesting to see why.

**Comment by stoarch** [comment]
Hello
I rebuild it from clean and it launched (one time error)
I do not like hezienbugs.
So sorry to disturb you with this error.
It can not be reproduced.

Thank you for response
Good luck
Vladimir

2018-06-20 14:19 GMT+06:00 erikangelin-king <notifications@github.com>:

**Comment by erikangelin-king** [comment]
Alright, please let us know if it happens again!

**Comment by stoarch** [comment]
Yes, I will. And try to reproduce it, so you can hunt and kill this bug :)
Good day to you.

2018-06-20 16:52 GMT+06:00 erikangelin-king <notifications@github.com>:
