### ISSUE TITLE
Hide assets in Editor

### ISSUE THREAD

**Issue by ErikBuchholtz** [defold/editor2-issues#1971]
### Expected behaviour

Working in a cluttered Collection scene can be a chore. Being able to hide things temporarily seems like a thing that you should be able to do, right?

### Actual behaviour

Well, turns out you can completely forget about such modern conveniences as a "hide the fucking asset for a minute so i can see what the fuck i'm doing" feature??

### Steps to reproduce

Open the editor. Open a collection file. Marvel at its inability to hide stuff that get in your way.

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-15T16:36:50.281821</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5ce6820d1dde4e9796949ffc33eaee074655bd56</td></tr>
<tr><td>Defold engine sha</td><td>30b201abdb7224683a3b3de2a02b22946dbbd427</td></tr>
<tr><td>Defold version</td><td>1.2.129</td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M395X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.58.32</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.1</td></tr>
<table>

**Comment by subsoap** [comment]
https://github.com/defold/editor2-issues/issues/899
https://github.com/defold/editor2-issues/issues/668
https://github.com/defold/editor2-issues/issues/681
