### ISSUE TITLE
Model and sprite incorrect z order editor vs engine

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1974]
In editor the model is above the larger sprite

![2018-06-21 19_14_56-defold editor 2 0 - newshadertests](https://user-images.githubusercontent.com/409170/41754503-6b4952ee-7587-11e8-936e-958e8e88a2a3.png)

In engine sprite is above the model

![2018-06-21 19_15_01-newshadertests](https://user-images.githubusercontent.com/409170/41754524-818eddd0-7587-11e8-84be-5f67d5ce4295.png)

Example project zip in this issue https://github.com/defold/editor2-issues/issues/1973

**Comment by subsoap** [comment]
I changed the z position of the model directly instead of just the GO it was attached to and was able to place it in front of the sprite so seems like there is some kind of issue there.

**Comment by erikangelin-king** [comment]
@subsoap Did you investigate this further?

**Comment by erikangelin-king** [comment]
Please reopen if you find anything odd
