### ISSUE TITLE
Clicking the "open" button on the second pane opens the file on the first instead of the second as expected

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1976]
These kinds of buttons should respect the panel they are currently on for opening files

![2018-06-21 20_28_46-defold editor 2 0 - newshadertests](https://user-images.githubusercontent.com/409170/41756495-b7c7d776-7591-11e8-83bc-ce8243d68b3a.png)

**Comment by erikangelin-king** [comment]
Can't reproduce, probably fixed at some point :)
