### ISSUE TITLE
Gamepad is not always detected at launch + need better continuous ability to detect plugged in gamepads (DEF-3349)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1983]
I have notice sometimes when I launch a game meant to use a gamepad it's non-functional. I have to relaunch the game to get it to work.

And of course plugging in a gamepad post launch never works. This needs to be an option somehow either let us pool or have a callback of somekind when a new gamepad is detected.

**Comment by andsveking** [comment]
This has been bugging me sooo sooo much... 😢 Added a ticket for this: DEF-3349

I have started looking at a solution for this, I have something working/prototype on macOS. It's currently not prioritised, but I will hopefully have time to continue with this on our next exploration day. 🤓

**Comment by AGulev** [comment]
Solved in 1.2.157 https://forum.defold.com/t/defold-1-2-157-has-been-released/55935
