### ISSUE TITLE
Paste doesn't work in text editor

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#199]
### Expected behaviour
Pressing Cmd+V in the text editor should paste what is in the clipboard.

### Actual behaviour
Nothing happens

### Steps to reproduce
1. Copy some text to clipboard
2. Press Cmd+V (or use the menu option Edit-Paste)

<hr/>
Defold version: 1.2.93
Defold sha: 5b644c3774e25722c589812fb4acf7042e34308a
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Can't repro :(
