### ISSUE TITLE
creating new GUI

### ISSUE THREAD

**Issue by runseld** [defold/editor2-issues#1993]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-18T16:05:54.249508</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4f2478d053dd63a6fcaa794b994256e7b0b25038</td></tr>
<tr><td>Defold engine sha</td><td>3abf70ee10dfb24e43529ff2e7ffbf1905ef5c19</td></tr>
<tr><td>Defold version</td><td>1.2.130</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"eb44f2717e3149d584f35f2cef249972"'>eb44f2717e3149d584f35f2cef249972</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD - FirePro D300 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.66.31</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Does this happen all the time or just once?

**Comment by runseld** [comment]
Just want so far, I just want to make you aware. Hasn’t happened since

-- 
RU

**Comment by erikangelin-king** [comment]
The error info was automatically purged, please report if it happens again.
