### ISSUE TITLE
If you edit a .gamepads file in an external editor while having it open in Defold the editor resizes with no way to resize

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2001]
![ed](https://user-images.githubusercontent.com/409170/41943967-88215854-795a-11e8-95dc-5e96baee3bde.png)

If I close and reopen the gamepads file it remains squished like this. If I edit the file and then resave in external editor it seems to scale back the way it should be.

**Comment by AGulev** [comment]
Solved
