### ISSUE TITLE
Gamepads behave badly when they do not have mapping setup in .gamepads

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2002]
A friend tested a game with a logitech f310 and he said pressing a would make window change fullscreen while b would close it. I have keys esc and f11 set to close / change fullscreen in .input_binding so I assume since this gamepad's device name isn't listed it has tried to use the .input_binding ones seemingly randomly.

Instead gamepads should try to default to a sane binding such as xbox 360 wired bindings. Maybe allow us to define a default binding.

We should also try to batch convert one of the big lists of bindings so they can be used with Defold projects.

**Comment by subsoap** [comment]
Update apparently Steam was interfering, but I don't have complete information yet.

![unknown](https://user-images.githubusercontent.com/409170/41945656-10911690-7963-11e8-9ae9-b4d9a4795be0.png)

**Comment by britzl** [comment]
Can we close this or is it still an issue?
