### ISSUE TITLE
Option to disable firewall invoking features on windows for release builds

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2003]
This kind of popup can be alarming, if no network features are required they should be allowed to be disabled from causing this kind of popup if possible.

![2018-06-26 17_14_10-windows security alert](https://user-images.githubusercontent.com/409170/41945903-7b7ed4f0-7964-11e8-8727-25b02e26a61a.png)

**Comment by britzl** [comment]
Can you verify that you weren't running a debug build? I'm thinking that maybe you had a native extension and din't use an app manifest.

**Comment by subsoap** [comment]
It must have been as you said a native extension enabled making it actually a debug build. Just tested a vanilla release build and no firewall request showed up.

**Comment by britzl** [comment]
Ok, thanks. Closing.

**Comment by mathiaswking** [comment]
Ok, great!
