### ISSUE TITLE
when i did tried to import tutorial project, i got error

### ISSUE THREAD

**Issue by ugurgungezerler** [defold/editor2-issues#2006]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-25T12:13:01.378662</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3af7e148260175bcaedb62b7e9ae442d08dfac4d</td></tr>
<tr><td>Defold engine sha</td><td>091e7e02ce492d3c4e493324b9db57d40df69e95</td></tr>
<tr><td>Defold version</td><td>1.2.131</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4f8f89db584a46e592cf7ef6950fdd28"'>4f8f89db584a46e592cf7ef6950fdd28</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @ugurgungezerler! This has happened for other users also, for instance here #1010. Can you try the solution suggested?

**Comment by erikangelin-king** [comment]
Please reopen if you need help!
