### ISSUE TITLE
clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172 on Ubuntu 18.04

### ISSUE THREAD

**Issue by baguzzzaji** [defold/editor2-issues#2007]
### Expected behaviour
Running the game

### Actual behaviour
An error occured

### Steps to reproduce
Install Defold in Ubuntu 18.04 and then run the game with F5

<hr/>

<table>
<tr><td>Build time</td><td>2018-06-25T12:12:42.935826</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3af7e148260175bcaedb62b7e9ae442d08dfac4d</td></tr>
<tr><td>Defold engine sha</td><td>091e7e02ce492d3c4e493324b9db57d40df69e95</td></tr>
<tr><td>Defold version</td><td>1.2.131</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"5f270d5454bc4047b09a0edfc4927941"'>5f270d5454bc4047b09a0edfc4927941</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.0.0-rc5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-23-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @baguzzzaji! This looks like a network issue. Does it happen every time? Do you get any relevant output in the Console tab? Do you have a firewall running, and if so, could you make sure `dmengine` is allowed to open ports on localhost?

**Comment by BaptisteGarcin** [comment]
Got the same issue on 18.04 as well, did you find a workaround ?

**Comment by androidneha** [comment]
I am also getting this same error in ubuntu 18.04 and in console tab I got this error 
```/home/neha/.Defold/unpack/378984826370bdddbeb4fd36c60b711630f9b8dd/x86_64-linux/bin/dmengine: error while loading shared libraries: libopenal.so.1: cannot open shared object file: No such file or directory```

**Comment by Atanvadro** [comment]
Had the same issue, solved by manually installing libopenal:
sudo apt-get install libopenal1

**Comment by erikangelin-king** [comment]
@baguzzzaji Please reopen if you need help.
