### ISSUE TITLE
Syncing repo failed - All changes reverted!

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#201]
Did some changes
Tried using synchronize
The inital repo pull gave an error
All changes were lost

Note: The repo is hosted on an corporate github.

**Comment by RagnarSvenssonKing** [comment]
There is a good chance the changes remain in the [git stash list](https://git-scm.com/book/en/v1/Git-Tools-Stashing). It would help a lot if you posted that error next time.

**Comment by Malmer** [comment]
The changes seemed to actually reside in a stash. And the reason why I couldn't sync was (I think) because the server wasn't available from that location. So I guess in those situations it should probably just restore the stash it made.

**Comment by matgis-king** [comment]
I could reproduce this by clicking the close button in the window title bar - seems we do not restore the state on disk to what it was prior to the sync. I've disabled the close button in the above PR, forcing the user to make an active choice instead.
