### ISSUE TITLE
Problem while saving [DEFEDIT-1415]

### ISSUE THREAD

**Issue by paweljarosz** [defold/editor2-issues#2010]
### Expected behaviour
Saved project
### Actual behaviour
While saving a project, I get this error: "Error 1". After clicking Dismiss, I am getting errors like in "Error 2"
### Steps to reproduce
Save project (Ctrl+S)
<hr/>

<table>
<tr><td>Build time</td><td>2018-06-11T10:10:52.962382</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>2769946c7c87e5d4da537fd994a880771245b70f</td></tr>
<tr><td>Defold engine sha</td><td>30b201abdb7224683a3b3de2a02b22946dbbd427</td></tr>
<tr><td>Defold version</td><td>1.2.129</td></tr>
<tr><td>Error 1</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"cda57e7b62614218ae59b9d537812623"'>cda57e7b62614218ae59b9d537812623</a></td></tr>
<tr><td>Error 2</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6b2710241e5743e59bff9aa1a3079fa9"'>6b2710241e5743e59bff9aa1a3079fa9</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.4377</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment]
Does the problem remain after restarting the editor?

Looking at the code, it seems this could only happen if something has gone wrong at an earlier point. Did you get an error when loading the project, or perhaps there is something in the log files?

**Comment by paweljarosz** [comment]
I've tried to restart both Defold Editor and computer, but it still occurs - after first try to save - not at the beggining. Files seems to be saved on a disk, but I can't synchronize with git.

**Comment by matgis-king** [comment]
Thanks for getting back to us. I wonder if there might be something strange about the Git state of the project. If you create a new project and add it to git, does it have the same issue? If not, would you be comfortable zipping up your project folder and sharing it with us? You can send files to `mats.gisselson` on the Defold forum.

**Comment by paweljarosz** [comment]
There is no problem with other projects, also - with new project - everything is working including git synchronizing. Yes, I can send the zipped project :)

**Comment by matgis-king** [comment]
Thanks for letting us look at your project. An update to the editor is on the way that should get it working again.

**Comment by paweljarosz** [comment]
Thank you ;)
