### ISSUE TITLE
Can't start a game that works fine in Defold 1.x

### ISSUE THREAD

**Issue by oak5tream** [defold/editor2-issues#202]
### Expected behaviour
I expect the game to be able to start.

### Actual behaviour
I get the following error: com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused

I though that it had something to do with having another instance of Defold running at the same time, but after closing it (Defold 1.x) and restarting Defold (2.x), I still get the same error.

The game starts fine in Defold 1.x

### Steps to reproduce
Start Defold and try to start a game.

<hr/>
Defold version: 1.2.93
Defold sha: 5b644c3774e25722c589812fb4acf7042e34308a
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_45-b14

**Comment by ragnard-king** [comment]
Hi @oak5tream! 

Can you reproduce this problem with a current version of Editor2? If so, are you able to share this game project with me?

**Comment by RagnarSvenssonKing** [comment]
Seems to be independent of project, check firewall etc. Ed2 should of course handle that gracefully so it's still a bug.

**Comment by oak5tream** [comment]
Yep. I tested on another project as well, and it's still reproducable.
