### ISSUE TITLE
After translating a modifier, particle properties can no longer be clicked [DEFEDIT-1427]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2022]
Something about translating a modifier's position with the widget is making the properties unable to get focus

Actually I'm not sure of the exact cause, but something is happening to lock up the panels after a modifier has focus / effect is playing

https://www.youtube.com/watch?v=uXdF_Rd0RTE&feature=youtu.be

**Comment by erikangelin-king** [comment]
Hi @subsoap! We've seen this happen before but never managed to reproduce it consistently - does this happen for you every time you move the modifier? If so, can you share the particlefx file? What version of the editor/engine are you on? This is on windows, right?

**Comment by erikangelin-king** [comment]
Let us know if you find a way :) This one has annoyed us for quite some time now.

**Comment by subsoap** [comment]
Will do! I'll be making a bunch more particle effects in the near future so may find what the cause is.

**Comment by erikangelin-king** [comment]
Workaround merged!
