### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by ksmolniy** [defold/editor2-issues#2026]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-03T09:12:36.108133</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a13691e3c44049058b32f368c28be264"'>a13691e3c44049058b32f368c28be264</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @ksmolniy! We see this pretty often, please try the solutions in this faq and report back whether it worked for you. https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md

**Comment by erikangelin-king** [comment]
Similar report with linked java.exe, if that's the error. https://github.com/defold/editor2-issues/issues/1918

**Comment by ksmolniy** [comment]
@erikangelin-king thx you it work
