### ISSUE TITLE
Can't not create new collection - string out of bound

### ISSUE THREAD

**Issue by gamereward** [defold/editor2-issues#2027]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-03T09:11:40.206015</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2ade4bb30d7d4049829c00cc7e4b7d12"'>2ade4bb30d7d4049829c00cc7e4b7d12</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M370X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.66.31</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @gamereward! Strange, can't repro this. Does it happen every time? What did you name your collection?

**Comment by erikangelin-king** [comment]
@gamereward Please re-report if this happens again, the error information was automatically purged so we don't have much to go on.
