### ISSUE TITLE
The Find (in File) button order should be "Prev" to the left and "Next" to the right

### ISSUE THREAD

**Issue by EgillAntonssonKing** [defold/editor2-issues#2028]
I think this way is how most applications have it (I can't name one that doesn't).

**Comment by AGulev** [comment]
Issue was solved DEFEDIT-1441
![2019-01-06_13-29-06](https://user-images.githubusercontent.com/2209596/50735997-4c66be80-11b7-11e9-978b-6d2b95a5c550.jpg)
