### ISSUE TITLE
GDI Generic

### ISSUE THREAD

**Issue by meromeropannna** [defold/editor2-issues#2034]
When I opened new program, this error occurred. 

**com.jogamp.opengl.GLException: The graphics device does not support: glGenBuffers
GPU: GDI Generic
Driver: 1.1.0
Please try to update your driver to the latest version and restart the application.**

I installed latest version of graphic driver. I use Intel HD Graphics 3000.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-03T09:12:36.108133</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b3ccd3749f6e47a9ada4573d296f6984"'>b3ccd3749f6e47a9ada4573d296f6984</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @meromeropannna! Try the instructions here and report back whether it worked: https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md

**Comment by erikangelin-king** [comment]
Similar report with linked java.exe, if that's the error. #1918

**Comment by meromeropannna** [comment]
After replacing the java.exe it worked properly. Thanks!
