### ISSUE TITLE
Cant load main collection in my MagicLink project

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#204]
Build my magiclink project from the tutorial magical link
Click the start button in the game

Actual result:
ERROR:RESOURCE: Unknown resource type: collection
ERROR:GAMESYS: The collection /main/board.collection could not be loaded.

Works fine in editor 1 with same project.

Ask me for access to the project.

Defold version: 1.2.93
Defold sha: 2325311fcc41c606c539914767295f0ff2cefe18
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Fix recently merged, should make it into a new build within an hour.
