### ISSUE TITLE
Not able to download project

### ISSUE THREAD

**Issue by lilrooness** [defold/editor2-issues#2041]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-03T09:11:40.206015</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"1c23a8db531e42eab4ca7aa19cb850a0"'>1c23a8db531e42eab4ca7aa19cb850a0</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.2</td></tr>
<table>

**Comment by lilrooness** [comment]
Solved, was behind a corporate firewall which was messing with the certificates somehow

**Comment by erikangelin-king** [comment]
@lilrooness! Thanks for reporting and closing :) Any learnings that could be helpful if it happens to others? I.e. any steps to fix it you can tell us about?
