### ISSUE TITLE
Changes in gui-template do not apply in bundle

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#2044]
### Expected behaviour
Bundle should have the same behaviour as build.

### Actual behaviour
Changes that I do in templates after adding them in other GUI didn't save when I made bundle. But in Build (cmd+b) all fine.

### Steps to reproduce
Unfortunately I can't reproduce this issue in new project: I can't find what exactly the reason of this behavior , but I can share project where bug reproduced.

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-03T09:12:36.108133</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by matgis-king** [comment]
Can you please share the project with me? I'm `mats.gisselson` on the Defold forum if you want to DM me. Also, please describe what we should be looking for so we can reproduce it.

**Comment by AGulev** [comment]
@matgis-king  I sent youmore info in DM on the forum

**Comment by matgis-king** [comment]
(Whoops. Meant to click "Comment")

We're still looking into issues with the Gui templates, but got sidetracked by a few crash fixes that some users were experiencing. The Gui template stuff is still a top priority for us, but it turns out to be quite tricky to get right.

**Comment by AGulev** [comment]
Thank you for the status update!

**Comment by dev-masih** [comment]
is this problem still exists?

**Comment by matgis-king** [comment]
Yes, the problem has not yet been addressed.
