### ISSUE TITLE
Engine does not close previously open webviews when building for Android (DEF-3368)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2049]
```ERROR:WEBVIEW: Max number of webviews already opened: 1```

If engine is rebuilt while a webview was left open it remains open still.

**Comment by subsoap** [comment]
Workaround is to always destroy webviews on final even if that's not normally flow of closing a webview

```
function final(self)
	webview.destroy(self.webview_id)
end
```

**Comment by subsoap** [comment]
Yes Project->Build with an Android engine as target does not close previously left open webviews.

**Comment by mathiaswking** [comment]
This should be fixed with the [1.2.134 release](https://forum.defold.com/t/defold-1-2-134-has-been-released/25866)
