### ISSUE TITLE
Dosya import ederken hata vermesi

### ISSUE THREAD

**Issue by evliyabalik** [defold/editor2-issues#2056]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-03T09:12:18.170414</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"7920048abe58472ab4356c3cf832b3be"'>7920048abe58472ab4356c3cf832b3be</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-21deepin-generic</td></tr>
<table>

**Comment by evliyabalik** [comment]
sorunum dosyayı import ederken bir uyarı şeklinde hata göstermesi yardımcı olursanız sevinirim

**Comment by matgis-king** [comment]
Firewall blocking connection?

**Comment by evliyabalik** [comment]
security wall closed

**Comment by matgis-king** [comment]
Problem solved?

**Comment by erikangelin-king** [comment]
More tips: https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md
Please reopen if you need help.
