### ISSUE TITLE
HasUserData found for class: nil

### ISSUE THREAD

**Issue by cenkbaykul** [defold/editor2-issues#2058]
### Actual behaviour
java.lang.IllegalArgumentException: No implementation of method: :user-data of protocol: #'editor.ui/HasUserData found for class: nil

### Steps to reproduce
When i try to open any tab ,object or even switch to external code editor .this message always appear and stay on the screen
_**Also editor lost tracking "Changed files".**_
<hr/>

<table>
<tr><td>Build time</td><td>2018-07-03T09:12:36.108133</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bd8e9b221dc47489fd0ee20a3b2477ed27063c24</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d623db01fc924254822bd0ee83ecc2ce"'>d623db01fc924254822bd0ee83ecc2ce</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon(TM) R7 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.201.1101.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Can you try updating the editor? I believe a fix for this issue was merged yesterday.

**Comment by cenkbaykul** [comment]
problem solved after update thank you
