### ISSUE TITLE
Logout doesnt log you out

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#206]
Open a project
Select log out from file menu (no feedback another issue logged about the no feedback issue)
Select Quit
Restart editor

Actual result:
You are still logged in
Both in win and mac

Expected result:
You should be asked to log in again

Defold version: 1.2.93
Defold sha: a30ee42320e3f61a379c3cb1d786d1957dfe5b45
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Ask me about quick-win?

**Comment by erikangelin-king** [comment]
Can't repro this :( Don't you get a login prompt if you try to import a project for instance? Are you using a king account? Note that the recent projects list is currently not cleared when logging out.

**Comment by sicher** [comment]
It seems to work. Some form of verification would be nice though.

**Comment by sofiahe** [comment]
I can still reproduce this on windows 7, so maybe a windows issue.
Or maybe I missunderstand the issue? When I select log out and then quit and reopen the editor I thought i was supposed to get the sign in window again? Or what should the log out option do?
Yes using a king account.

**Comment by erikangelin-king** [comment]
The logout function "works", but it's effect is not obvious and we don't give any feedback.

**Comment by EmilEnglund** [comment]
I have the same problem, and since there is no "Switch Project" in the menu I've been trying to use "Log Out" as means of opening a new project.

The fact that it visually does nothing and that you can click it and log out even though you are already logged out, makes this feel completely broken to a user like me.

**Comment by erikangelin-king** [comment]
Closing this since it does in fact log you out, there is another issue about feedback which we agree is clearly missing: https://github.com/defold/editor2-issues/issues/78
