### ISSUE TITLE
 open not working

### ISSUE THREAD

**Issue by evliyabalik** [defold/editor2-issues#2065]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-12T13:22:50.509062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c51bcfc8418fd3bcb2a9517a1deaa7c98339014f</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Sandybridge Mobile </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 13.0.6</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-21deepin-generic</td></tr>
<table>

Hello there

I can not open the open (Ctrl + O) menu under the file menu and it gives no response. I also have to close the editor to open a new project, I am waiting for your help in this regard thank you

**Comment by erikangelin-king** [comment]
There is no `Open` option under the file menu. Did you mean `Open Assets...` with shortcut `Ctrl + P`? You currently can't change project without restarting the editor, something we obviously want to fix eventually.
