### ISSUE TITLE
Can't create new project. PKIX path building failed. Unable to find valid certification path to requested target.

### ISSUE THREAD

**Issue by fukushimasan** [defold/editor2-issues#2067]
### Expected behaviour
A new project is created.

### Actual behaviour
An error occurred on create new project.

### Steps to reproduce
1. Download Editor 2 (for Windows 64-bit) from www.defold.com. 
2. Open Editor
3. Choose NEW PROJECT > From Tutorial > choose 'Side scroller tutorial'.
4.  Then, Error Dialog opend.

In Dialog, the message was blow
An error occurred:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
<hr/>

<table>
<tr><td>Build time</td><td>2018-07-12T13:22:50.509062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c51bcfc8418fd3bcb2a9517a1deaa7c98339014f</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ec40db1869e6408cb05a7c1930d3ce89"'>ec40db1869e6408cb05a7c1930d3ce89</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @fukushimasan! We're trying to reproduce this issue, can you please try the same steps we've given to @AndyGFX in #2100?

**Comment by erikangelin-king** [comment]
Issue was Antivirus software intercepting connection. Created FAQ here: https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md
