### ISSUE TITLE
Particlefx placement in GUI is sometimes incorrect as window resizes (DEF-3421)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2069]
Not sure the cause. The particlefx is an play once mode effect which is triggered every 3 seconds. I can somewhat consistently get the position to be wrong by resizing a window randomly. It should remain centered with the other box nodes, as it does most of the time, but sometimes its placement is weird.

Video showing it happening https://www.youtube.com/watch?v=-WRqOkpW23g&feature=youtu.be

**Comment by johan-becknoren-king** [comment]
Created DEF-3421 to track this issue.

**Comment by johan-becknoren-king** [comment]
Hopefully fixed in 1.2.138, will re-open issue if that is not the case.
