### ISSUE TITLE
As window size changes, particlefx scale is not consistent with other nodes (DEF-3421)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2070]
![2018-07-16 01_04_05-particlefxguisizedif](https://user-images.githubusercontent.com/409170/42748238-3f30e292-8894-11e8-9d9f-e91e27578f03.png)
![2018-07-16 01_03_58-particlefxguisizedif](https://user-images.githubusercontent.com/409170/42748239-3f476e86-8894-11e8-8fb3-dd9532eba38b.png)
![2018-07-16 01_03_47-particlefxguisizedif](https://user-images.githubusercontent.com/409170/42748240-3f5d61c8-8894-11e8-945b-93074b34caa3.png)
![2018-07-16 01_03_34-particlefxguisizedif](https://user-images.githubusercontent.com/409170/42748241-3f756ef8-8894-11e8-9313-06dde43e40de.png)
![2018-07-16 01_03_06-particlefxguisizedif](https://user-images.githubusercontent.com/409170/42748242-3f8e3258-8894-11e8-8bd0-f8eb9c64f482.png)

[ParticleFXGUISizeDif.zip](https://github.com/defold/editor2-issues/files/2196865/ParticleFXGUISizeDif.zip)

As a window is shrunk, the scale stays consistent. But as a window is made larger the scale difference is obviously incorrect. 

This issue makes making particles that look good on both mobile and desktop screens more difficult.

**Comment by johan-becknoren-king** [comment]
Created ticket DEF-3421 to track this.

**Comment by johan-becknoren-king** [comment]
Fixed in 1.2.138.
