### ISSUE TITLE
Building with iPhone X as a target

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2071]
<hr/>

<table>
<tr><td>Build time</td><td>2018-07-12T13:22:50.509062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c51bcfc8418fd3bcb2a9517a1deaa7c98339014f</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2005baf68e6f4353957cd5c0c65c1d97"'>2005baf68e6f4353957cd5c0c65c1d97</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Does this happen consistently? Only when targeting iPhone X? Even with a simple project?

**Comment by Jerakin** [comment]
Unfortunatelly I have completely forgot what I was doing when this happened. I say close it for now, and re-open/re-report if it happens again.
