### ISSUE TITLE
error [DEFEDIT-1419]

### ISSUE THREAD

**Issue by tdtanvn** [defold/editor2-issues#2072]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-12T13:22:50.509062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c51bcfc8418fd3bcb2a9517a1deaa7c98339014f</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"34bd6c9b980e4e18bbf105f37e521015"'>34bd6c9b980e4e18bbf105f37e521015</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 398.36</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Same issue as #2066.
