### ISSUE TITLE
Defold Editor reset written code on external editor [DEFEDIT-1420]

### ISSUE THREAD

**Issue by Insality** [defold/editor2-issues#2076]
Im edit code in Sublime Editor (or and external editor) on big project (Family Age)
When Im saving my progress and return to Defold Editor, i am automatically press ctrl+s to save my code and get newest build.

Seems, what the time, after returning to Defold editor, it is indexing all the changes (git?). But if I save the project in this time, it will override code to older state. Sometimes it lead to totally lose progress, if i cant catch this.

Worked on Windows and Mac

There is way to fix it? May be there is way to disable Editor Git client? The indexing may be too long on some computers

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-18T17:37:42.353005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4828309a21aaec8b7e6d80351d863c6a15a486d9</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 6000</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.30.12</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.2</td></tr>
<table>

**Comment by matgis-king** [comment]
The editor keeps the state of all editable files in memory. When you Alt+Tab back to the editor, we check if any editable files have changed on disk, and reload them into memory if we detect any external changes. This is performed on a background thread so the editor can be used in the meantime.

Data loss can occur if the user choses to save the project while we're still trying to figure out if there were external changes. At this point the externally changed resources have not yet been reloaded into the the editor, so saving will overwrite the external changes with the last known state from the editor.

If a save command is issued while we're trying to incorporate external changes, we must defer the save until after the external changes have been loaded into the editor. We might also want to signal to the user that the save command cannot complete until the external changes have been incorporated, possibly by some sort of progress indicator in the status bar.

**Comment by matgis-king** [comment]
We now always integrate external changes before saving.

**Comment by Insality** [comment]
A lot of thanks to you!
