### ISSUE TITLE
Support Box2D joints (DEF-3025)

### ISSUE THREAD

**Issue by abigpotostew** [defold/editor2-issues#2079]
I would love to use Box2D joints in my game. I'm hoping to implement a drag behavior for a dynamic object, and having a spring joint anchor to a fixed point on a game object is the most accurate way to implement this. This would also support many additional physical simulations. Thank you.

**Comment by britzl** [comment]
We have an internal ticket for this: DEF-3025

An alternative could be to use an extension binding another physics engine such as Chipmunk 2D. Discussed here: https://forum.defold.com/t/physics-and-joints-def-3025/14291/12?u=britzl

**Comment by AGulev** [comment]
Solved in [1.2.156](https://forum.defold.com/t/defold-1-2-156-has-been-released/54508)
