### ISSUE TITLE
help

### ISSUE THREAD

**Issue by JanaGDS** [defold/editor2-issues#2081]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-18T17:36:36.387394</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4828309a21aaec8b7e6d80351d863c6a15a486d9</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
What do you need help with?
