### ISSUE TITLE
liveupdate.settings error occurred (DEF-3386)

### ISSUE THREAD

**Issue by amelvand** [defold/editor2-issues#2083]
### Expected behaviour
Open the liveupdate.settings

### Actual behaviour
Returning this error:

An error occurred:
java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Collection

### Steps to reproduce
Create a new project and/or open a project you already have. Go to Project > Live Update Settings and the error will occur immediately

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-18T17:37:42.353005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4828309a21aaec8b7e6d80351d863c6a15a486d9</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"150f3d4aee814c218532e382b9036907"'>150f3d4aee814c218532e382b9036907</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.36.19</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by andsveking** [comment]
@amelvand We pushed a fix for this yesterday, could you check if you still experience this error after an update?

**Comment by amelvand** [comment]
It works again! Thanks for the quick fix!
