### ISSUE TITLE
Pressing arrow keys while in collection switches tab

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#209]
### Expected behaviour
Pressing arrow key would do nothing (or potentially navigate the object outline) while my focus is in the collection view.

### Actual behaviour
It switches tab.

### Steps to reproduce
Open a collection
Press left or right arrow key

<hr/>
Defold version: 1.2.93
Defold sha: a30ee42320e3f61a379c3cb1d786d1957dfe5b45
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
I think the tab itself used to get keyboard focus when you opened a resource instead of the actual content/view. I can no longer reproduce this issue, please reopen if it's still broken!
