### ISSUE TITLE
No Check Updates

### ISSUE THREAD

**Issue by rinkowei** [defold/editor2-issues#2090]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-12T13:22:50.509062</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c51bcfc8418fd3bcb2a9517a1deaa7c98339014f</td></tr>
<tr><td>Defold engine sha</td><td>09410355c1baf7e474e46cbc2d252f67f673e1dc</td></tr>
<tr><td>Defold version</td><td>1.2.132</td></tr>
<tr><td>GPU</td><td>GeForce GTX 750 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 398.36</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Do you mean an option to disable the automatic check & download of editor updates?
