### ISSUE TITLE
I renamed the game.script to game.appmanifest (while the file was still open) [DEFEDIT-1419]

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#2091]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-18T17:37:42.353005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4828309a21aaec8b7e6d80351d863c6a15a486d9</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9bd537317efb473f98b147340f69b987"'>9bd537317efb473f98b147340f69b987</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M290X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.51.8</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by matgis-king** [comment]
Same issue as #2066.
