### ISSUE TITLE
Cant load the project

### ISSUE THREAD

**Issue by ReydVires** [defold/editor2-issues#2095]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-18T17:37:42.353005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4828309a21aaec8b7e6d80351d863c6a15a486d9</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6e01723ed31e4056924d24f43688deca"'>6e01723ed31e4056924d24f43688deca</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 8330</td></tr>
<tr><td>GPU Driver</td><td>4.5.13474 Compatibility Profile Context 22.19.163.2560</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @ReydVires! Does this happen all the time? Are you running a profiler/debugger or somesuch?

**Comment by ReydVires** [comment]
@erikangelin-king it sometimes happend when I run 2 defold

**Comment by erikangelin-king** [comment]
Closing. We should support running multiple editors simultaneously, but apparently this sometimes break.
