### ISSUE TITLE
Building an Android application

### ISSUE THREAD

**Issue by viennarzc** [defold/editor2-issues#2098]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-25T10:16:43.211043</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>378984826370bdddbeb4fd36c60b711630f9b8dd</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2ef06a065d0b4ee0b351cd3878b50e39"'>2ef06a065d0b4ee0b351cd3878b50e39</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 640</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.32.48</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @viennarzc! Does this happen every time? Can you reproduce it with a simpler project, or are you comfortable sharing the project with us so we can have a look?

**Comment by erikangelin-king** [comment]
Reopen if this still happens or if you need help.
