### ISSUE TITLE
Application runs out of memory when opening large collections

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#210]
### Expected behaviour
The large collection would open

### Actual behaviour
The app hangs and the cursor turns into a spinner

### Steps to reproduce
Open a large collection that references many gui scenes.

<hr/>
Defold version: 1.2.93
Defold sha: a30ee42320e3f61a379c3cb1d786d1957dfe5b45
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
This one seems to be fixed. Correct?

**Comment by erikangelin-king** [comment]
Indeed!
