### ISSUE TITLE
 PKIX path building failed. Unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by AndyGFX** [defold/editor2-issues#2100]
### Expected behaviour
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### Steps to reproduce
Start new project
<hr/>

<table>
<tr><td>Build time</td><td>2018-07-25T10:16:34.183135</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>378984826370bdddbeb4fd36c60b711630f9b8dd</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#2067

**Comment by erikangelin-king** [comment]
Hi @AndyGFX! Looks like the java runtime we bundle isn't using the right set of trusted root certificates (cacerts file). We're having trouble reproducing the error. How does your environment variables look? Perhaps you have a JAVA_HOME setting pointing out some other jre?

**Comment by AndyGFX** [comment]
from java console:

1.8	1.8.0_45	http://java.sun.com/products/autodl/j2se	C:\Program Files\Java\jre1.8.0_45\bin\javaw.exe		true
1.8	1.8.0_05	http://java.sun.com/products/autodl/j2se	C:\Program Files\Java\jre8\bin\javaw.exe		true

**Comment by erikangelin-king** [comment]
Hello again @AndyGFX! I meant, what variable settings do you find under Control Panel/System/Advanced System Settings/Environment Variables...?

**Comment by AndyGFX** [comment]
Sorry ;)

JAVA_HOME
c:\Program Files\Java\jdk1.8.0_05

HOMEPATH
C:\ORACLE\ORA11g\product\11.2.0\client_1\bin;C:\ProgramData\Oracle\Java\javapath;C:\Perl\site\bin;C:\Perl\bin;C:\Oracle\ora10g\bin;C:\Windo
ws\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program
Files\TortoiseSVN\bin;C:\Program Fil
es\Hewlett-Packard\OpenView\service desk 4.5\client (sp22)\bin;C:\Program
Files\Sennheiser\SoftphoneSDK\;C:\Program Files\IIS Express;C:\Us
ers\ondrej.kollar\AppData\Local\Code\bin

Because I haven't full acces to system, I can read it only from console
when I know ENV name. When you need know any other write me env. name and
then I send you result.

Best Regards,
Ondrej

**Comment by erikangelin-king** [comment]
Thanks @AndyGFX! Can you try starting defold from the command line, but first removing the JAVA_HOME environment variable?
* Start `cmd`
* `cd <path to where you installed defold>`
* `set JAVA_HOME=` (this will remove the JAVA_HOME setting from the current environment only)
* `Defold`

**Comment by AndyGFX** [comment]
Tried, but ...

same error window is showed, when [Create New Project] button was pressed (few sec. after) :(

O.

**Comment by erikangelin-king** [comment]
Hmm. Alright, what if you open the file `config` next to `Defold.exe` and after the `vmargs = ...` add the following settings:
`-Djavax.net.debug=ssl`, `-Djavax.net.ssl.trustStore=packages/jre/lib/security/cacerts` and `-Djavax.net.ssl.trustStorePassword=changeit`. All on the same line. Then try running Defold.

**Comment by AndyGFX** [comment]
:(

Nothing new, same problem.

O.

**Comment by erikangelin-king** [comment]
Ok, try setting `'-Djavax.net.debug=all`, run again and then mail me the editor2 log (erik.angelin@king.com) - It should be in `C:\users\<your account>\AppData\Local\Defold\editor2.2018-08-14.log`.

**Comment by erikangelin-king** [comment]
@AndyGFX If you have time for the last experiment, I'd really like to look at the logs.

**Comment by AndyGFX** [comment]
Hi. Sorry I'm now on vacation. Next 7 days I will be out.

**Comment by erikangelin-king** [comment]
@AndyGFX We've found an explanation for this error, will write an FAQ for future reference.

**Comment by erikangelin-king** [comment]
@AndyGFX Check if this applies to you :) https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md
Hope you have/had a nice vacation, and thanks for helping us!

**Comment by erikangelin-king** [comment]
Closing this. We now present a nicer error message on ssl errors and refer to the FAQ.
