### ISSUE TITLE
Renaming a file open as text [DEFEDIT-1419]

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2101]
I think it only happens if the file doesn't have an editor. In this case it was a file named "level.gui copy" but didn't happen with "level copy.gui"

Error: First error

Error 2 and 3 (didn't get a sentry link): 
```
clojure.lang.ExceptionInfo: handler ':cut' in context ':code-view' failed at ':enabled?' with message 'clojure.lang.MapEntry cannot be cast to editor.code.data.CursorRange'
java.lang.ClassCastException: clojure.lang.MapEntry cannot be cast to editor.code.data.CursorRange
```

Error 4 and repeating: Repeated error that can't be dismissed

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-30T17:09:20.393386</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6f9454d6599a1082438e69d68c4d3465b2d8ed47</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d01258364e04430c9c5e356770b7a58f"'>d01258364e04430c9c5e356770b7a58f</a></td></tr>
<tr><td>Error 4 and repeating</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f5e1c3a7f54a41b789c4576b301ce9c5"'>f5e1c3a7f54a41b789c4576b301ce9c5</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by matgis-king** [comment]
Same issue as #2066.
