### ISSUE TITLE
Changed branch [DEFEDIT-1419]

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2105]
Changed from branch A to branch B, a file was open that was created in branch A that didn't exist in branch B.

Got a similar error 4 times.

Then got this error 2 times.
 ```

clojure.lang.ExceptionInfo: handler ':cut' in context ':code-view' failed at ':enabled?' with message 'clojure.lang.MapEntry cannot be cast to editor.code.data.CursorRange'
java.lang.ClassCastException: clojure.lang.MapEntry cannot be cast to editor.code.data.CursorRange
```

Then got the first error another 2 times.

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-30T17:09:20.393386</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6f9454d6599a1082438e69d68c4d3465b2d8ed47</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"dd2e50933dee4d62bf07ccdff62f0c90"'>dd2e50933dee4d62bf07ccdff62f0c90</a></td></tr>
<tr><td>Error 2</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d28b9e2b5ea64043b2a536526ddf22fc"'>d28b9e2b5ea64043b2a536526ddf22fc</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by Jerakin** [comment]
Seems to be same kind of errors as https://github.com/defold/editor2-issues/issues/2101

**Comment by matgis-king** [comment]
Same issue as #2066.
