### ISSUE TITLE
Crashed when sign on iOS Sign button clicked

### ISSUE THREAD

**Issue by CeMcK** [defold/editor2-issues#2106]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-30T17:09:20.393386</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6f9454d6599a1082438e69d68c4d3465b2d8ed47</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"df079e9981b44301a8cc80cd5caf22c9"'>df079e9981b44301a8cc80cd5caf22c9</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.0.17</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @CeMcK! Can you reproduce this?

**Comment by CeMcK** [comment]
@erikangelin-king yes Defold does crash very often on macOS 10.14

**Comment by erikangelin-king** [comment]
@CeMcK Is the provisioning profile field empty?

**Comment by erikangelin-king** [comment]
Closing as the error information was automatically purged. Think you get errors if any fields are empty.
