### ISSUE TITLE
Unify the main texture name of builtin materials (DEF-3419)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2107]
The main texture names between builtin materials is not consistent. They should all be DIFFUSE_TEXTURE or similar for the basic texture name.

**Comment by andsveking** [comment]
Makes sense, it should be consistent! Added issue: **DEF-3419**

**Comment by AGulev** [comment]
Done as part of DEF-3507 (Spir-v toolchain) in 1.2.147
