### ISSUE TITLE
Copy & Paste w/Mouse Does Not Work On Linux?

### ISSUE THREAD

**Issue by FallenAngelSoftware** [defold/editor2-issues#2108]
Hi,

Using the Linux Defold editor on Kubuntu 18.04 64Bit LTS.
Copy & paste with the mouse seems to not be working?
Hope you can fix this soon!
Thanks!

Jesse

**Comment by erikangelin-king** [comment]
Hi @FallenAngelSoftware! Do you mean in the code editor or generally in text input fields?

**Comment by erikangelin-king** [comment]
@FallenAngelSoftware Ping?
