### ISSUE TITLE
Selecting block of text and pressing tab removes text

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#211]
### Expected behaviour
Selected lines should be indented (or un-indented if shift+tab is pressed)

### Actual behaviour
The text is replaced with a tab

### Steps to reproduce
Select many lines of text
Press tab

<hr/>
Defold version: 1.2.93
Defold sha: a30ee42320e3f61a379c3cb1d786d1957dfe5b45
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Fixed with auto-indentation, Tab when any text is selected auto-indents the lines.
