### ISSUE TITLE
Duplicating then renaming a collision object causes build errors [DEFEDIT-1421]

### ISSUE THREAD

**Issue by 8bitskull** [defold/editor2-issues#2111]
Hello!

This is a bit difficult to capture in the subject line, so let me try to explain. I have a lot of enemies in my game, and the file structure looks something like this:
https://forum.defold.com/uploads/default/original/2X/0/05424b61ec11d2a46ab143b75f621077afadcdf8.png

The easiest way for me to create a new type of enemy is just to copy the entire “knight” folder, then rename all the files. I make sure that the references are updated, e.g. the new_enemy.factory file will reference new_enemy.go.

The issue arises when I try to build, I get errors indicating that “knight.collisionobject” can not be found, even when no file is referencing it. The “solution” is to put a “knight.collisionobject” file in every duplicated folder. So, for instance, when I have created a new enemy called “ogre”, the folder looks like this:
https://forum.defold.com/uploads/default/original/2X/a/a8015aa23c19b337d51e0df1a88269998ba05a7e.png

If I do not structure the folder like this, I get build errors like the below:
https://forum.defold.com/uploads/default/original/2X/2/24cb3d2fb492a02b6e6d5d7033f9f3fb49fa81ee.png

Please note that I was not having issues like this when using Editor 1.

Any ideas? Thanks in advance!

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-25T10:16:43.211043</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>378984826370bdddbeb4fd36c60b711630f9b8dd</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.43</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @8bitskull! This looks insane and very serious! Could you share the project with me (erik.angelin@king.com) or Mats (mats.gisselson@king.com) so we can have a look?

**Comment by 8bitskull** [comment]
Done - I have added you both, the project id is 78799 and the name is "Project Iso". Let me know if you need anything else!

**Comment by erikangelin-king** [comment]
Hi @8bitskull!
Could you give more detailed steps to reproduce, I must be doing something differently.

I tried:
* Copy the knight folder from within the editor
* Paste, creating the knight_copy folder
* Rename files within from knight.* to knight_copy.*
* Fix references among the knight_copy.* files
* Added knight_copy.factory to enemy_factory.go
* Build

Also tried copying the folder from the command line with the editor open, relying on it to pick up the new resources.

Thanks!

**Comment by 8bitskull** [comment]
@erikangelin-king ,

I think I have narrowed down the issue. I'm lazy and am using a [bulk renaming software](https://www.bulkrenameutility.co.uk/Main_Intro.php) to change the file names of copied enemy files. I use the "Show in Desktop" button to rename the files directly in the project folder. I imagine this is what causes the problem.

 I can't remember if I was ever able to use the software in Defold 2, but I am sure I did use it in Defold 1 with no issue.

**Comment by 8bitskull** [comment]
Given that this is an issue caused by third party software, I am not sure you are too interested in further information! In any case, I attempted to delete one of the duplicated knight.collisionobject files, then restarting the editor and attempting to build. Doing that I get a new (scarier) error message:

![image](https://user-images.githubusercontent.com/24439991/44087514-005282fc-9fb8-11e8-8730-3e8bf1161774.png)

Reverting the deletion of the duplicated collision object does nothing, until the editor is restarted again at which point it builds like normal.

**Comment by erikangelin-king** [comment]
Thanks for the info! Deleting the knight.collisionobject from the ogre folder did indeed trigger build errors, so now I have something to work on :) You should be able to do file system changes outside the editor, but the editor will not be able to automatically update references then.

**Comment by erikangelin-king** [comment]
Alright, we just merged a fix that we believe should cover this issue. Whenever a .collisionobject file was deleted, all .tilesource would be "poisoned" with an irrelevant build error.
About the "Cannot run program ..." errors, that's a separate issue that usually appears when multiple editors are running/started simultaneously. We haven't had time to look into that properly, but as you noticed restarting usually helps.

**Comment by 8bitskull** [comment]
Can confirm I am now able to delete duplicated/unused collision objects caused by the issue outlined above. Success! :)
