### ISSUE TITLE
whenever there is a change on the sound component the group is reset to "master"

### ISSUE THREAD

**Issue by Deynne** [defold/editor2-issues#2115]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-30T17:09:20.393386</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6f9454d6599a1082438e69d68c4d3465b2d8ed47</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 3000</td></tr>
<tr><td>GPU Driver</td><td>3.1.0 - Build 9.17.10.3223</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by Deynne** [comment]
I now noticed that this happens when you change the sound component in the editor area, but not in the properties area.

**Comment by sicher** [comment]
Clarification. This happens if you create a sound component file and tries to edit it in the protobuf editor.

**Comment by erikangelin-king** [comment]
Fixed
