### ISSUE TITLE
Deleting script asset while open in editor causes crash [DEFEDIT-1419]

### ISSUE THREAD

**Issue by spongepaddy** [defold/editor2-issues#2122]
### Expected behaviour
Deleted asset should not crash the editor.

### Actual behaviour
If a script asset is open when it is deleted, an error is reported and cannot be clicked away, which requires the editor to be re-started.

### Steps to reproduce
Open a script asset, and delete it in the asset browser.
![screen shot 2018-08-13 at 12 56 34](https://user-images.githubusercontent.com/5442727/44027958-a5ef5b74-9ef8-11e8-9008-769e71adb021.png)

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-30T17:09:20.393386</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6f9454d6599a1082438e69d68c4d3465b2d8ed47</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"44b805bd13c24e4686ee320e8a9dc143"'>44b805bd13c24e4686ee320e8a9dc143</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.10.14 310.42.25f02</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by matgis-king** [comment]
Same issue as #2066.
