### ISSUE TITLE
Revert button should require confirmation

### ISSUE THREAD

**Issue by RhythmLynx** [defold/editor2-issues#2123]
Accidentally clicking the Revert button (which is right next to Diff) can immediately destroy potentially hours or days of work without popping up a confirmation window. Revert should really require confirmation, at least as an option in the preferences.

https://forum.defold.com/t/better-diff-tool-option-to-change-diff-tool/27076

**Comment by johan-becknoren-king** [comment]
Fixed in release 1.2.139.
