### ISSUE TITLE
Add "Copy Require Path" to Project explorer

### ISSUE THREAD

**Issue by Qwarr** [defold/editor2-issues#2125]
It would be convenient to be able to right click on a file and get the "require" path.

Currently I use  "Copy Project Path" to get it and just change it from `/example/test/code/file.lua` to `example.test.code.file`

But it would be good to just right click -> Copy Require Path -> `example.test.code.file`

**Comment by AGulev** [comment]
![2018-11-26_17-12-52](https://user-images.githubusercontent.com/2209596/49019239-88f9d000-f19e-11e8-8236-10c1737d8bef.jpg)
looks like already implemented? @erikangelin-king

**Comment by erikangelin-king** [comment]
@AGulev you're right!
