### ISSUE TITLE
HTML5: implement retry logic when preloader fails (DEF-3418)

### ISSUE THREAD

**Issue by aglitchman** [defold/editor2-issues#2127]
The loading process of an HTML5 game shouldn’t be interrupted even if the connection is lost.

In other words, the engine should keep trying (every 5 sec, for example) to load the game assets.

Sometimes, when WiFi or 3G connection is poor, HTML5 games might fail to load, therefore cutting off users that are not experienced enough to realize that the problem is caused by their connection and that all they have to do is reload the page.

**Comment by britzl** [comment]
Good point. Created internal ticket DEF-3418
