### ISSUE TITLE
Error downloading Movement tutorial

### ISSUE THREAD

**Issue by benbritten** [defold/editor2-issues#2128]
### Expected behaviour
Download the movement tutorial from the defold editor

### Actual behaviour

I got this error:
java.io.IOException: Server returned HTTP response code: 502 for URL: https://codeload.github.com/defold/tutorial-movement/zip/master
java.io.IOException: Server returned HTTP response code: 502 for URL: https://codeload.github.com/defold/tutorial-movement/zip/master

### Steps to reproduce
I opened the editor, hit new project, from tutorial, movement tutorial, create new project. A popup came up saying that it was downloading, and then the above error.

<hr/>

<table>
<tr><td>Build time</td><td>2018-08-15T15:07:57.708999</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>647b78d3829e45c0a9ab3b643d426a12feaba2da</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"03d3f324178b4af4b2cf39e084839997"'>03d3f324178b4af4b2cf39e084839997</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by sicher** [comment]
This was likely some temp problem with Github and not the editor. HTTP response 502 indicates a problem on the server side (bad gateway).

**Comment by erikangelin-king** [comment]
We have a ticket for better error messages in cases like this also.
