### ISSUE TITLE
Crash on resizing UI

### ISSUE THREAD

**Issue by nwestberg** [defold/editor2-issues#2131]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-30T17:09:20.393386</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6f9454d6599a1082438e69d68c4d3465b2d8ed47</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"7ecf9073abb8466db50546b02b0a15fa"'>7ecf9073abb8466db50546b02b0a15fa</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M395X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.42.15</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Please update the editor and try again
