### ISSUE TITLE
Login broken

### ISSUE THREAD

**Issue by Derpford** [defold/editor2-issues#2134]
Linux 64bit, tried on Chromium and Firefox (both ESR and current) with cleared cookies. This is evidently a common problem, I've seen multiple forum posts claiming it's "solved" but it continues to be an issue.

Expected behavior: After clicking through Google's sign-in process, I am brought to a confirmation page, where I click the "Get Started" button. This then allows me to download Defold and get started using this frankly amazing-looking engine.
Actual behavior: After clicking through Google's sign-in process, I get a dead link. I am not able to get started. I am actually quite mad about this. Notably, there is a `Loading failed for the <script> with source “https://www.googletagmanager.com/gtm.js?id=GTM-PRNCJN”.` in my console.

Look, if you can't fix your logins, don't gate your app behind them. I *want* to use this engine, but I can't because I can't sign up for it, which means I can't phone home to you while I'm using the engine, which is apparently worth sacrificing the ability of people to use your app for. This is insane, doubly so because I now have no means of contacting the proper support channels (because I can't sign up, because your auth is broken). You've successfully managed to ruin every aspect of "Getting Started". This makes me genuinely concerned for the state of the engine itself, because if you can't even get *Google's external authentication* to work right, how the hell am I supposed to expect the engine to work right? You don't even have to do any of the hard parts of authentication. This is the only time I've ever seen someone create a professional site with a dead sign-up link. Nobody else fucks this up.

**Comment by Derpford** [comment]
Thanks for the workaround. I *do* want to use this engine--the deep Git integration is interesting, and this is the only engine I've seen that uses the scene-object-component structure *and* uses Lua as a language.

**Comment by Derpford** [comment]
Unfortunately, now I have a second problem: My google account hasn't been associated with Defold, meaning I can't log in inside the editor. This removes my access to the tutorials, to the git integration I liked so much, and keeps me out of the project management UI.

**Comment by amel** [comment]
Well, you only need to login to make use of the Defold Cloud. In the meanwhile, you can still host your projects locally and run Git from the command line or through a third party application to perform pulls, pushes, commit, merges, working on several branches and so on. 

I just signed out of my account and I am still able to download the tutorials and examples from within the editor. I'm not sure why you can't access those, but I've made a Dropbox folder for you where you can download all of the tutorials: https://goo.gl/uJPR3Z

**Comment by erikangelin-king** [comment]
Hi @Derpford! That's sad. I tried creating a new account to follow where things went bad. Did you mean the Confirm Signup button on the Confirm Signup page was broken? This is not really my department but I'll let the right people know on Monday.

**Comment by Derpford** [comment]
@erikangelin-king Yep, the confirm signup button was the part that broke.

@amel When I open the editor, I don't get a "Select project" dialog, and if I go to "open project" from the "file" menu I get a dialog asking me to choose a google account. When I choose mine, of course, it says I haven't connected it to Defold, because as noted, the signup page appears to be broken.

**Comment by erikangelin-king** [comment]
Registering works fine for me using Chrome on Mac. Are you perhaps running some ad/popup/tracking blocker?

**Comment by britzl** [comment]
Yes, sorry to hear that you're having problems trying Defold. We want to make the process as easy as possible, and Google authentication is usually super smooth. We're also in the process of adding custom e-mail signup.

I tried registering as well using a new gmail account and had no problems (Chrome and OSX). No idea what's wrong but from my point of view we didn't f**k up completely. Still, I'd like to get to the bottom of this and figure out why it doesn't work for @Derpford

**Comment by Derpford** [comment]
@erikangelin-king Yes, actually. I'll try without the adblock.

**Comment by Derpford** [comment]
OK, turning off adblock on the confirm-signup page removes the script load error but does not fix the problem. Weird--I would've thought that the script loading properly would fix it.

**Comment by amel** [comment]
Do you perhaps have a very slow internet connection?

**Comment by Derpford** [comment]
@amel No, I have a 100MBPS connection.

@erikangelin-king There's a "terms and conditions" checkbox? I only saw the link to terms and conditions, not the checkbox. I think we have our solution.

**Comment by Derpford** [comment]
Confirmed, it was the checkbox. Should probably either add feedback when clicking the button with checkbox unchecked, or change the background color of the checkbox so it isn't blending into the background so much.

**Comment by erikangelin-king** [comment]
@Derpford Great, thanks for reporting back.
