### ISSUE TITLE
No indication that import is still ongoing when importing a large project

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#214]
Importing a large project doesnt give any indication if the project is still being imported or if something has gone wrong.

A spinning wheel or something to indicate that its still working might be good.

Took me about 6 min to import a large project and its hard to know if it still doing it or if it has just stopped.

Defold version: 1.2.93
Defold sha: 5ea2e08c7fa6d8ea601bec8580b893151d174666
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

![screen shot 198](https://cloud.githubusercontent.com/assets/22887289/20669872/af322b98-b576-11e6-99f9-6b62320538a5.PNG)

**Comment by AGulev** [comment]
<img width="997" alt="screenshot 2019-01-03 at 11 09 27" src="https://user-images.githubusercontent.com/2209596/50632531-7f574b00-0f48-11e9-9fcf-11dc30bf6882.png">
Looks like it was fixed with new welcome screens
