### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mcprog** [defold/editor2-issues#2144]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-01-15T13:51:11.848458</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8b805e523a12eb6f58652ee8ac3e88b980fabf1e</td></tr>
<tr><td>Defold engine sha</td><td>2406775912d235d2579cfe723ab4dbcea2ca77ca</td></tr>
<tr><td>Defold version</td><td>1.2.119</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"0c2548e25eb6472fb79964d554a5202b"'>0c2548e25eb6472fb79964d554a5202b</a></td></tr>
<tr><td>GPU</td><td>Radeon (TM) RX 480 Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.5.13506 Compatibility Profile Context 23.20.15002.11</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This was fixed in a later version of the editor. Please update and try again.
