### ISSUE TITLE
Enhancement: Save all when opening synchronize dialog

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#215]
You always need to save before opening sync. Maybe only me but I tend to forget that and presume when I want to sync it should be saved.

**Comment by jakob-pogulis-king** [comment]
I often find myself intentionally leaving files unsaved if I want to commit something but exclude certain portions that are meant for debug. We can call it the "Cut, Save, Paste, Commit" workflow..

**Comment by matgis-king** [comment]
@jakob-pogulis-king Trouble is, your in-memory changes will be lost if the sync operation changes one of the affected files on disk. The editor will refresh the in-memory state from the changed file automatically. But I guess you could do "Cut, Save, Commit, Paste" instead?

For now I think we need to make it safer to use by simply ensuring the project is saved before syncing.

**Comment by jakob-pogulis-king** [comment]
![workflow](https://cloud.githubusercontent.com/assets/17006862/21004849/c303c55a-bd32-11e6-885d-c1acbfcca353.png)
https://xkcd.com/1172/
