### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Wolfman13** [defold/editor2-issues#2165]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-08-31T14:36:39.776742</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fff392c8eeb27510d5400abab53cbae48509865d</td></tr>
<tr><td>Defold engine sha</td><td>1b90c9a905d634b766b467e3536458b9210ec812</td></tr>
<tr><td>Defold version</td><td>1.2.135</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"1b4b9482150747d492aae4e92b5c05bf"'>1b4b9482150747d492aae4e92b5c05bf</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.0.5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-33-generic</td></tr>
<table>

**Comment by matgis-king** [comment]
I believe this can happen if you have the `CLASSPATH` environment variable set to look for Java components at a particular location. This is not recommended, and will likely mess with many other Java-based programs. Try running Defold without the `CLASSPATH` environment variable set.

**Comment by erikangelin-king** [comment]
@Wolfman13 Please reopen if this is still an issue.
