### ISSUE TITLE
Make dependencies a multiline field

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#217]
Open game.project find field dependencies 
When it has several dependencies it would be nice to be able to separate them with a line break.

Came as feedback from a dev

**Comment by AGulev** [comment]
fully agree, it would be great 
![2017-05-10_14-25-17](https://cloud.githubusercontent.com/assets/2209596/25896409/b0f8d7ec-358c-11e7-9571-f43ea878060a.png)

**Comment by ragnard-king** [comment]
Dependencies is now a simple multi-line field, coming in update shortly.
