### ISSUE TITLE
It is possible to override a node's id in a GUI layout. [DEFEDIT-1454]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#2172]
STR:

1. Add layout to GUI.
2. Select it.
3. Type a new id for a node.

<img width="386" alt="screen shot 2018-09-04 at 15 34 12" src="https://user-images.githubusercontent.com/65613/45034551-21792c00-b058-11e8-81f4-cac31c71b85e.png">

**Comment by erikangelin-king** [comment]
Fixed
