### ISSUE TITLE
java.lang.AssertionError: Assert failed

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2183]
<hr/>

<table>
<tr><td>Build time</td><td>2018-09-11T15:34:42.565277</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0d3f4f3edea4a3f95456da915f0ff9284127e233</td></tr>
<tr><td>Defold engine sha</td><td>883d660f9894e0d2bcc7f5895c1eaab1153e98b6</td></tr>
<tr><td>Defold version</td><td>1.2.136</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"af29f54f1aa045a0b38138ff2f2ce4c2"'>af29f54f1aa045a0b38138ff2f2ce4c2</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Jerakin!
This "shouldn't happen", can you help me repro?

**Comment by Jerakin** [comment]
It was when I was bundling/freezing a python app that is in the project. Unfortunately I can't reproduce it at all now, so could close it I guess.

I tried bundling with this script ./.make_toggle_ios.sh in the project.
Dependencies would be (from what I can remember)
`brew install python` - python3
`pip install pyinstaller` - used for bundling
`pip install deftree` - dependency for the script
`pip install PyQt5` - dependency for the script
`pip install sip` - dependency for bundling

**Comment by erikangelin-king** [comment]
@Jerakin Do you remember if you got some other error before this happened?

**Comment by Jerakin** [comment]
Quite sure I got this before it. https://github.com/defold/editor2-issues/issues/2184

**Comment by erikangelin-king** [comment]
Great! Alright, I think the first exception left our map of the resources on disk in a bad state, causing this error. Will close for now, but reopen if it happens again!
