### ISSUE TITLE
java.io.FileNotFoundException: 

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2184]
Getting a lot of reports about files that I have ignored with git, they are build files for a tool.

<hr/>

<table>
<tr><td>Build time</td><td>2018-09-11T15:34:42.565277</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0d3f4f3edea4a3f95456da915f0ff9284127e233</td></tr>
<tr><td>Defold engine sha</td><td>883d660f9894e0d2bcc7f5895c1eaab1153e98b6</td></tr>
<tr><td>Defold version</td><td>1.2.136</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"01e98e6865db4e488e177b8d72964221"'>01e98e6865db4e488e177b8d72964221</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We've just merged a fix with further error checking around i/o, this ought to cover your issue. Please reopen otherwise! FYI, .gitignore only affects the Changed Files view - we still consider the files as part of the project, and they end up in the Assets view.
