### ISSUE TITLE
error

### ISSUE THREAD

**Issue by kubikrubit** [defold/editor2-issues#2186]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-09-11T15:34:09.247387</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0d3f4f3edea4a3f95456da915f0ff9284127e233</td></tr>
<tr><td>Defold engine sha</td><td>883d660f9894e0d2bcc7f5895c1eaab1153e98b6</td></tr>
<tr><td>Defold version</td><td>1.2.136</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a15f7fc2b0cd4a488554e62ad0690c8f"'>a15f7fc2b0cd4a488554e62ad0690c8f</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-34-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @kubikrubit! Please try the workaround here: https://www.defold.com/faq/#_linux_issues

**Comment by erikangelin-king** [comment]
@kubikrubit Still an issue?
