### ISSUE TITLE
java.lang.IllegalArgumentException: Both width and height must be >= 0

### ISSUE THREAD

**Issue by danengelbrecht-king** [defold/editor2-issues#2195]
Moving to other application and back to the editor should not display an exception dialog.
Sometimes if I have the editor running in the background and work for a while I get an exception when activating the application again: "java.lang.IllegalArgumentException: Both width and height must be >= 0". Just Dismissing it the exception dialog seems to work with non side effects.

<hr/>

<table>
<tr><td>Build time</td><td>2018-09-17T11:59:22.610378</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5becbcae44ea3e6eaa88f15a39768ee1e15f5484</td></tr>
<tr><td>Defold engine sha</td><td>883d660f9894e0d2bcc7f5895c1eaab1153e98b6</td></tr>
<tr><td>Defold version</td><td>1.2.136</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.68.20</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can you give us the logs with the exception + stacktrace plz.

**Comment by erikangelin-king** [comment]
Reopen if it happens again
