### ISSUE TITLE
Player crashes when using incorrect particle name in gui.new_particlefx_node() (DEF-3547)

### ISSUE THREAD

**Issue by spongepaddy** [defold/editor2-issues#2197]
### Expected behaviour
Player should not crash when using incorrect particle name in gui.new_particlefx_node()

### Actual behaviour
Player crashes totally when using incorrect particle name in gui.new_particlefx_node()

### Steps to reproduce
gui.new_particlefx_node(vmath.vector3(0,0,0), "made_up_particle_name")

<hr/>

<table>
<tr><td>Build time</td><td>2018-09-17T11:59:22.610378</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5becbcae44ea3e6eaa88f15a39768ee1e15f5484</td></tr>
<tr><td>Defold engine sha</td><td>883d660f9894e0d2bcc7f5895c1eaab1153e98b6</td></tr>
<tr><td>Defold version</td><td>1.2.136</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.10.14 310.42.25f02</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by johan-becknoren-king** [comment]
Added engine ticket DEF-3547 for tracking this.

**Comment by AGulev** [comment]
@erikangelin-king 
DEF-3547 - Fixed: Crash when creating new PFX node with non-existent resource.
https://forum.defold.com/t/defold-1-2-139-has-been-released/32831/5

**Comment by erikangelin-king** [comment]
@AGulev! Indeed, thanks!
