### ISSUE TITLE
Incorrect syntax highlightning for lua

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#22]
Used this file as test:
https://raw.githubusercontent.com/diegonehab/luasocket/master/src/ltn12.lua

- 1 or 2 characters are sometimes highlighted differently to rest of token

![image](https://cloud.githubusercontent.com/assets/20399970/17898156/9a1f4d72-694e-11e6-80de-26fab3196e89.png)

**Comment by erikangelin-king** [comment]
Closing as can't reproduce. Highlighting code has changed lots since this report.
