### ISSUE TITLE
Properties section doesnt update when switching tabs

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#220]
1. Open game.project
2. Open an asset with properties
3. Switch between the tabs and look at the properties section

Actual result: The properties section is not updated when switching between the tabs between an asset with properties and one that doesnt have properties

Defold version: 1.2.93
Defold sha: 5ea2e08c7fa6d8ea601bec8580b893151d174666
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by alexandru-p** [comment]
Same thing occurred with the Outline View a couple of times on the same build, but on WIndows 7 x64.

**Comment by ragnarsvensson** [comment]
Fixed
