### ISSUE TITLE
Crash when building the game while it's still running [DEFEDIT-1462]

### ISSUE THREAD

**Issue by tarekkarray** [defold/editor2-issues#2203]
### Expected behaviour
Old game instance shuts down (killed) when building the project
### Actual behaviour
old game instance isn't killed and I have to force quit.
### Steps to reproduce
just build the game while it is running
<hr/>

<table>
<tr><td>Build time</td><td>2018-09-24T16:06:01.646497</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1e11d155b6dba16d6fd6df8521c825c3baca4835</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"0f841a7b50444a5ab0581d8f22e250ab"'>0f841a7b50444a5ab0581d8f22e250ab</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.68.20</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by selimanac** [comment]
+1

**Comment by mathiaswking** [comment]
This was solved in 1.2.138
