### ISSUE TITLE
Building native exstention freeze editor [DEFEDIT-1497]

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#2212]
In 2018 freezing editor when doing some work instead of doing it in background is very strange.
I cry every time. Build html not freeze but build freeze.
### Expected behaviour
Building native exstention freeze editor
### Actual behaviour
Editor working while building.
### Steps to reproduce
Build a project with native extension.
<hr/>

<table>
<tr><td>Build time</td><td>2018-09-26T16:58:54.946767</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>098e6cee744ab17b3567c2ceb27d3516e537e890</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13539 Compatibility Profile Context 24.20.13017.5001</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by d954mas** [comment]
any news?

**Comment by mathiaswking** [comment]
What version are you on?
Since a while back (a couple of months), the editor doesn't freeze when building extensions?
It does the work in the background afaik.

Btw, do you have the "use-clang: false" in you .appmanifest?

I'll test it on windows later today.

**Comment by erikangelin-king** [comment]
Looking at this, and it seems we are indeed blocking while waiting for a custom dmengine to build. Not just on windows.

**Comment by d954mas** [comment]
i use one of last version. 141 or 142, when i will be home can check. I don't have use-clang: false.

It happened only for build. Bundle and build html work in background.

**Comment by erikangelin-king** [comment]
No need to check, it's obvious from the code that when you build (not bundle) a project with native extensions, we block and wait for the build servers to produce an engine binary. Looking into it now.

**Comment by AGulev** [comment]
The issue solved in 1.2.144
https://forum.defold.com/t/defold-1-2-144-has-been-released/37962

**Comment by AGulev** [comment]
@erikangelin-king I am not sure, but looks like this is very similar issue https://github.com/defold/editor2-issues/issues/742
