### ISSUE TITLE
Pressing "Cmd+B" to run engine while already running causes crash

### ISSUE THREAD

**Issue by danengelbrecht-king** [defold/editor2-issues#2217]
### Expected behaviour
Expected running instance to either reload or restart.

### Actual behaviour
Lots of logs "WARNING:DLIB: Unable to remove /Users/danengelbrecht/Library/Application Support/defold/cache/00/00000000000000" for different files.

The "Error An error occurred: java.lang.NullPointerException: Unknown" dialog.

### Steps to reproduce
Load a project.
Start it with Cmd+B
Once engine instance is running, switch to editor and press Ctrl+B

<hr/>

<table>
<tr><td>Build time</td><td>2018-09-19T14:34:28.077520</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>0a6687458ab980a8097b1ee8aad495790bdb472a</td></tr>
<tr><td>Defold engine sha</td><td>883d660f9894e0d2bcc7f5895c1eaab1153e98b6</td></tr>
<tr><td>Defold version</td><td>1.2.136</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a462857b7f324243aa7f4e621b381c3b"'>a462857b7f324243aa7f4e621b381c3b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.68.20</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by sicher** [comment]
Trying to reproduce with no luck.

**Comment by AGulev** [comment]
I have the same bug.

**Comment by erikangelin-king** [comment]
See #2206, tl;dr probably your ~Library/Application Support/Defold/cache has wound up in a bad state. Workaround is to delete the cache directory.

**Comment by mathiaswking** [comment]
Fixed in 1.2.138 (DEF-3530)
