### ISSUE TITLE
Particle "jumping" glitch in 1.2.137

### ISSUE THREAD

**Issue by spongepaddy** [defold/editor2-issues#2225]
### Expected behaviour
Particle system should behave as it did in 1.2.136

### Actual behaviour
In 1.2.137 particle system starts "jumping" oddly in the editor and in published game

### Steps to reproduce
Make particle system with large textures. See movie attached. 

[smoke-bug.zip](https://github.com/defold/editor2-issues/files/2437450/smoke-bug.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2018-09-24T13:53:36.352756</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.10.14 310.42.25f02</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<table>

**Comment by johan-becknoren-king** [comment]
Fixed in 1.2.138.
