### ISSUE TITLE
Sign iOS App fail

### ISSUE THREAD

**Issue by dasannikov** [defold/editor2-issues#2231]
### Steps to reproduce
Trying to Sign iOS App (Project->Sing iOS APP)
Worked on previous versions.

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-04T11:46:57.993562</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5d6a298743d45b22dbfab3703a9da2a6e41cfde0</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"dd3885ecec0b44edbc1df80fc6af6290"'>dd3885ecec0b44edbc1df80fc6af6290</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.0.34</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @dasannikov! We just merged a fix! Thanks for reporting.
