### ISSUE TITLE
Failed to Build after want to disable node on GUI

### ISSUE THREAD

**Issue by ReydVires** [defold/editor2-issues#2233]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-04T16:12:28.470530</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8b3c538cc0cc3c94ad634988f98b3d0b71f812bc</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"0bd6f3ffeca941939fd6e490ca32a131"'>0bd6f3ffeca941939fd6e490ca32a131</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 640</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.36.19</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by ReydVires** [comment]
This issue comes when I'm not closing the windowed-open-build file then I click build again.

**Comment by erikangelin-king** [comment]
This looks related to an http cache issue that will be fixed shortly. Thanks for reporting.
