### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by adabelle-leiram** [defold/editor2-issues#2234]
### Actual behaviour
About 50% of the time I save, I get this error and can't save or build without restarting the editor

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-04T16:12:28.470530</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8b3c538cc0cc3c94ad634988f98b3d0b71f812bc</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ff870a27bcb34a18a3142a2b8872a67b"'>ff870a27bcb34a18a3142a2b8872a67b</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.68.20</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by mathiaswking** [comment]
An even better "workaround" is to update (if permitted by project) to 1.2.138, where the the http cache is fixed on the engine side.

**Comment by erikangelin-king** [comment]
@adabelle-leiram I believe this has been fixed, please reopen if it happens again!
