### ISSUE TITLE
Side scroller tutorial: build and run doesnt work

### ISSUE THREAD

**Issue by iingemar** [defold/editor2-issues#2246]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-18T15:53:33.358241</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>82d859f18d758dde3a6a404669c92fda56e08f48</td></tr>
<tr><td>Defold engine sha</td><td>cd250cdbbace72ce374bf44ad8302739e69f65ec</td></tr>
<tr><td>Defold version</td><td>1.2.138</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"bc10a81d17e44d499a0e83610b683ad0"'>bc10a81d17e44d499a0e83610b683ad0</a></td></tr>
<tr><td>GPU</td><td>Quadro 600/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.2.0 NVIDIA 304.117</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>3.13.0-24-generic</td></tr>
<table>

**Comment by mathiaswking** [comment]
What OS are you on?

The error suggests that you don't have the correct C++ runtime installed:
"/usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found"

We target Ubuntu 16.04 which has a different version installed.
Perhaps you can try the workaround [listed here](https://github.com/defold/editor2-issues/issues/1792) to see if that helps

**Comment by iingemar** [comment]
Ubuntu 14.04

I will check out the workaround!

**Comment by iingemar** [comment]
Woo! I got it to work!! :D

If anyone else got this problem, try this:

sudo add-apt-repository ppa:ubuntu-toolchain-r/test
sudo apt-get update
sudo apt-get install gcc-4.9 g++-4.9

Thanks!
