### ISSUE TITLE
The graphics device does not support: glGenBuffers GPU: GDI Generic

### ISSUE THREAD

**Issue by ZEUScorp** [defold/editor2-issues#2249]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-18T15:54:27.240659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>82d859f18d758dde3a6a404669c92fda56e08f48</td></tr>
<tr><td>Defold engine sha</td><td>cd250cdbbace72ce374bf44ad8302739e69f65ec</td></tr>
<tr><td>Defold version</td><td>1.2.138</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"47101f65435a476a8a15bd4449cdf9ec"'>47101f65435a476a8a15bd4449cdf9ec</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

What does I have to do to fix this problem? Help me, please!

**Comment by erikangelin-king** [comment]
Try this to start with: https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md
