### ISSUE TITLE
NullPointerException when clicking build error

### ISSUE THREAD

**Issue by zaikoboon** [defold/editor2-issues#2251]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-18T15:54:27.240659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>82d859f18d758dde3a6a404669c92fda56e08f48</td></tr>
<tr><td>Defold engine sha</td><td>cd250cdbbace72ce374bf44ad8302739e69f65ec</td></tr>
<tr><td>Defold version</td><td>1.2.138</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"aebcb518ca304c5c9882c2c0a1680ac9"'>aebcb518ca304c5c9882c2c0a1680ac9</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7700 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13541 Compatibility Profile Context 24.20.13019.1008</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @zaikoboon! Looks like this happened when you clicked on a compilation error, can you share the project with us (invite us as team members on the project dashboard)? Either erik.angelin@king.com or mats.gisselson@king.com
