### ISSUE TITLE
java.lang.NullPointerException: Unknown - when writing code

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2253]
Where simply writing code.

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-18T15:54:27.240659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>82d859f18d758dde3a6a404669c92fda56e08f48</td></tr>
<tr><td>Defold engine sha</td><td>cd250cdbbace72ce374bf44ad8302739e69f65ec</td></tr>
<tr><td>Defold version</td><td>1.2.138</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3c9e70b69fe34eb5968c6ae34d01eaeb"'>3c9e70b69fe34eb5968c6ae34d01eaeb</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by Jerakin** [comment]
Only happened once, it was in `sfx.lua` in our work project and no errors before it happened.

This is just guessing but I think I did something like
1. Write a character
2. Erase it
3. Undo

or

1. Write a character
2. Undo
3. Erase it

In a quick succession.

**Comment by erikangelin-king** [comment]
Please report if it happens again!
