### ISSUE TITLE
The scale tool not working when selecting a sprite

### ISSUE THREAD

**Issue by MasihAkbari** [defold/editor2-issues#2256]
### Expected behaviour
after selecting a sprite and selecting The scale tool from top right corner of editor (or hit R key) a square  appears and we can resize the sprite (image is from defold manual page).  

![scale](https://user-images.githubusercontent.com/8469800/47375763-deedda80-d6fd-11e8-89e5-da69e551bd74.jpg)
### Actual behaviour
selecting a sprite and select scale tools not shown anything and therefore we can't resize them in editor.  

![capture](https://user-images.githubusercontent.com/8469800/47375933-4a37ac80-d6fe-11e8-8a27-b6c19294e392.PNG)

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-18T15:54:27.240659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>82d859f18d758dde3a6a404669c92fda56e08f48</td></tr>
<tr><td>Defold engine sha</td><td>cd250cdbbace72ce374bf44ad8302739e69f65ec</td></tr>
<tr><td>Defold version</td><td>1.2.138</td></tr>
<tr><td>GPU</td><td>GeForce GT 630M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 391.35</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi @MasihAkbari! This works like intended. The Sprite itself does not have a Scale property. Thus, you can only rotate and position Sprites. However, Game Objects, when used in a Collection, are scaleable. The image from the manual depicts a Game Object in a Collection being scaled.
