### ISSUE TITLE
ERROR:DLIB: Invalid cache index file '\AppData\Roaming\defold/http-cache/index'. Removing file.

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2257]
Getting this in console since update. Restarting editor does not help.

![2018-10-23 19_19_21-about](https://user-images.githubusercontent.com/409170/47402041-8ec04980-d6f8-11e8-91c1-6949738f5d55.png)

**Comment by JCash** [comment]
What is the time stamp on that file? The engine decides it's out of date, and it tries to remove it. It would then be recreated later, with new info, and of course a new timestamp.

You can also try to remove it manually to see if that resolves it.
This was updated in 1.2.138 (DEF-3530) https://forum.defold.com/t/defold-1-2-138-has-been-released/31459, so it should have shown before.

Are you perhaps running and alternating between old and new versions?

**Comment by subsoap** [comment]
![2018-10-26 02_10_20-window](https://user-images.githubusercontent.com/409170/47556911-4fdeef00-d8c4-11e8-9118-2797a604af34.png)

I removed the folder (http_cache) and the error no longer appears in the console even after restarting.

BTW old unpack versions are still not removed automatically? They should be probably at least as an option.

![2018-10-26 02_12_43-window](https://user-images.githubusercontent.com/409170/47557079-af3cff00-d8c4-11e8-8727-ea62735ad842.png)

**Comment by mathiaswking** [comment]
@subsoap Is this still an issue?

**Comment by subsoap** [comment]
I have not got the error since.

**Comment by mathiaswking** [comment]
Ok, thx!
