### ISSUE TITLE
Adding Same Collection to A Collection Hung the Editor [DEFEDIT-1522]

### ISSUE THREAD

**Issue by MasihAkbari** [defold/editor2-issues#2258]
### Expected behaviour
perhaps prevent to add a collection under it's self or use a better logic
### Actual behaviour
editor tries to add a collection to itself and gets into an infinite loop that hung the editor.
### Steps to reproduce
just add same collection under itself
<hr/>

<table>
<tr><td>Build time</td><td>2018-10-18T15:54:27.240659</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>82d859f18d758dde3a6a404669c92fda56e08f48</td></tr>
<tr><td>Defold engine sha</td><td>cd250cdbbace72ce374bf44ad8302739e69f65ec</td></tr>
<tr><td>Defold version</td><td>1.2.138</td></tr>
<tr><td>GPU</td><td>GeForce GTX 970/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 391.35</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by markusgustavssonking** [comment]
Made it impossible to select the current collection when clicking to add a nested collection. Still need to solve the bigger issue of detecting cycles but there are other open tickets for that.
