### ISSUE TITLE
Button to hide the middle dock

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#2264]
https://twitter.com/tumeo_/status/1055747300310634496

![](https://pbs.twimg.com/media/DqbEUJ-WkAAGpcz.jpg)

**Comment by AGulev** [comment]
related https://github.com/defold/editor2-issues/issues/2170

**Comment by vlaaad** [comment]
Already released as *View* → *Toogle Tools Pane* (<kbd>F7</kbd>)
