### ISSUE TITLE
Gizmo doesn't work / can't be used

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2284]
![bug](https://user-images.githubusercontent.com/5273682/47950838-9b466c80-df58-11e8-8443-19d3ec97dcc8.gif)

Happens on windows all the time, all gizmos behaves the same.

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-02T17:12:21.660174</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b157b90a2ea5e8b67483d626b1e75ff3bc7d5e6b</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Should be fixed by now, please reopen otherwise!
