### ISSUE TITLE
Transform manipulators are no longer working

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#2285]
### Expected behaviour
I should be able to move, scale and rotate components and game objects using the manipulators/gizmos

### Actual behaviour
I'm not able to transform components and game objects. The manipulators get a mouse over effect but doesn't react to clicks

### Steps to reproduce
Select a game object or component. Select one of the manipulators. Try to use them.
<hr/>

<table>
<tr><td>Build time</td><td>2018-11-02T17:12:21.660174</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b157b90a2ea5e8b67483d626b1e75ff3bc7d5e6b</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.32.0 355.11.10.10.40.102</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by Jerakin** [comment]
https://github.com/defold/editor2-issues/issues/2284
