### ISSUE TITLE
Can you help me? :'( sun.security.validator.ValidatorException: PKIX path building failed

### ISSUE THREAD

**Issue by rtyuio123** [defold/editor2-issues#2287]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-02T17:12:11.850376</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b157b90a2ea5e8b67483d626b1e75ff3bc7d5e6b</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"786f58907f4f4d9b9040ed8ab15591c8"'>786f58907f4f4d9b9040ed8ab15591c8</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @rtyuio123! Try this to start with: https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md

**Comment by erikangelin-king** [comment]
Hi @rtyuio123 Did it help?
