### ISSUE TITLE
[WINDOWS] crash if building when game is open

### ISSUE THREAD

**Issue by abjornr** [defold/editor2-issues#2288]
### Expected behaviour
Rebuild the game and restart.
### Actual behaviour
Crash.
### Steps to reproduce
Build game -> build while game is running.
<hr/>

<table>
<tr><td>Build time</td><td>2018-10-08T10:18:33.678287</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7be7b498ce7051a1535bfcb3abe93ea6eb854dff</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 381.67</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by amel** [comment]
This problem was solved in version 1.2.138 or 139 iirc. You should update Defold and try again :)

**Comment by erikangelin-king** [comment]
Hi @abjornr! We believe this has been fixed, please reopen if you can still reproduce it after updating the editor.
