### ISSUE TITLE
Exception thrown on Lenovo x121e

### ISSUE THREAD

**Issue by thstrauss** [defold/editor2-issues#2289]
### Expected behaviour
No Exception

### Steps to reproduce

Open editor on notebook with following graphic:

Intel(R) HD Graphics 3000

Report Date:			11/5/2018
Report Time[hh:mm:ss]:		19:12:47
Driver Version:			9.17.10.4459
Operating System:		Microsoft Windows 10 Pro(10.0.17134)
Default Language:		German (Germany)
DirectX* Version:		11.0
Physical Memory:		8105 MB
Processor:			Intel(R) Core(TM) i3-2367M CPU @ 1.40GHz
Processor Speed:		1397 MHz
Vendor ID:			8086
Device ID:			0116
Device Revision:		09

*   Processor Graphics Information   *

Processor Graphics in Use:		Intel(R) HD Graphics 3000
Video BIOS:			2089.0
Current Graphics Mode:		1366 by 768

*   Devices Connected to the Graphics Accelerator   *

Active Notebook Displays: 1
	*	Built-in Display	*

Monitor Name:			Generic PnP Monitor
Display Type:			Digital
Gamma Value:			2,2
DDC2 Protocol:			Supported

Maximum Image Size:
Horizontal:			10,24 inches
Vertical:			05,51 inches

Monitor Supported Modes:
1366 by 768 (50 Hz)
1366 by 768 (60 Hz)

Display Power Management Support:
Standby Mode:			Supported
Suspend Mode:			Supported
Active Off Mode:		Supported

Raw EDID:
00 FF FF FF FF FF FF 00 30 AE D1 40 00 00 00 00 
00 14 01 03 80 1A 0E 78 EA 99 85 95 55 56 92 28 
22 50 54 00 00 00 01 01 01 01 01 01 01 01 01 01 
01 01 01 01 01 01 12 1B 56 5A 50 00 19 30 30 20 
36 00 00 90 10 00 00 18 8F 16 56 5A 50 00 19 30 
30 20 36 00 00 90 10 00 00 18 00 00 00 0F 00 8C 
09 32 8C 09 28 14 09 00 06 AF 56 31 00 00 00 FE 
00 42 31 31 36 58 57 30 33 20 56 31 20 0A 00 80 

* Other names and brands are the property of their respective owners. *

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-05T15:33:39.442152</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a01721d5d5bc4f56d482a98c6e4bfa083e0be531</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"fecbc9b12c1c46af8b0137d6f619dada"'>fecbc9b12c1c46af8b0137d6f619dada</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @thstrauss! This is a very common error, please follow this faq and reopen if it doesn't help.
https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md
