### ISSUE TITLE
Possible to overwrite existing file when creating a new file

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#229]
### Steps to reproduce:
1. From the Assets panel, create a new Particle Effect file.
2. Add a Modifier to the Particle Effect from the Outline panel.
3. Save.
4. From the Assets panel, create a new Particle Effect file, using the same name as you did in step 1.

### Expected result:
The editor refuses to create a new file where one already exists. Possibly it would suggest a unique name for the new file.

### Observed result:
The existing file is overwritten with an empty Particle Effect!

**Comment by ragnard-king** [comment]
Fixed.
