### ISSUE TITLE
After this have to close and reopen

### ISSUE THREAD

**Issue by dewmal** [defold/editor2-issues#2292]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-05T15:33:20.799160</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>a01721d5d5bc4f56d482a98c6e4bfa083e0be531</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"47bf44e8aca44d39a63bb54b8e6ce2af"'>47bf44e8aca44d39a63bb54b8e6ce2af</a></td></tr>
<tr><td>GPU</td><td>GeForce 940MX/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 396.54</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-36-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Do you mean you have to restart the editor to be able to use the debugger? The error only shows a connection attempt failed, so we don't have much to go on.

**Comment by erikangelin-king** [comment]
@dewmal Still an issue?
