### ISSUE TITLE
Disable console by default for Windows release variant (DEF-3602)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2294]
When doing a release bundle for Windows the console is not by default disabled, but it should be. 

An appmanifest with ```linkFlags: ["-Wl,/subsystem:windows"]``` is required to disable the console properly.

However it's annoying to define such a manifest in the game.project file because it disables the console on normal builds too, so have to re-enable it only when doing bundles, which is annoying.

**Comment by mathiaswking** [comment]
A fix is ready, awaiting review, and should land in 1.2.142

**Comment by AGulev** [comment]
https://forum.defold.com/t/defold-1-2-142-has-been-released/35271
already fixed? @mathiaswking
