### ISSUE TITLE
Undo is slow on Windows [DEFEDIT-1200]

### ISSUE THREAD

**Issue by robertatamking** [defold/editor2-issues#2296]
Please fix the undo on PC.  It is super slow and buggy.

**Comment by matgis-king** [comment]
Note: This likely only occurs in large projects.

We're currently in the process of redesigning the undo system, but a lot of work remains before we can ship anything. We'll try to repro the bad performance on Windows to see if there is an interim fix.

**Comment by matgis-king** [comment]
We've merged a fix that should make undo significantly faster in large projects.

We still have work to do on the feeling that undo is buggy. This stems from both the fact that we currently have a global undo queue that is shared among all files, so you can undo changes to a file that is no longer open or selected. Also, selection creates an undo step, so you can lose the redo queue by undoing and selecting something.

We're still working on all of the above, but for now at least it will be decently quick to undo or redo inside a large project.

**Comment by AGulev** [comment]
The issue solved in 1.2.144
https://forum.defold.com/t/defold-1-2-144-has-been-released/37962
