### ISSUE TITLE
GL crash when adding game object

### ISSUE THREAD

**Issue by TerisbackDev** [defold/editor2-issues#2298]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-06T17:27:14.747323</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3fbdc79eee27ccde2734dae9d246fdbee1230b35</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13541 Compatibility Profile Context 25.20.14007.1000</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by TerisbackDev** [comment]
_Crashlog_
[hs_err_pid12076.log](https://github.com/defold/editor2-issues/files/2560924/hs_err_pid12076.log)

**Comment by TerisbackDev** [comment]
Most often this happens when I create a new Gameobject
![kek](https://user-images.githubusercontent.com/26527529/48187107-f236b200-e35b-11e8-868b-08b84e62082e.gif)

**Comment by erikangelin-king** [comment]
Hi @TerisbackDev! Has this worked before? Did it work in an older version of the editor? Have you recently updated your graphics drivers?

**Comment by TerisbackDev** [comment]
downgrade driver 18.10.2 to 18.9.3 (amd videocard)
Aaaand, it's stable
