### ISSUE TITLE
Import Project: refresh projects and names

### ISSUE THREAD

**Issue by RagnarSvenssonKing** [defold/editor2-issues#23]
Import Project in the Welcome screen, project list should be refreshed when opened

**Comment by sofiahe** [comment]
steps to reproduce:
1. Start defold
2. Click import project
3. Create a new project in the dashboard
4. Click the dropdown to expand projects in the editor

Expected result: the newly created project to appear

**Comment by britzl** [comment]
Dashboard has been removed
