### ISSUE TITLE
The editor should download engine binaries at start, not be bundled with them

### ISSUE THREAD

**Issue by jakob-pogulis-king** [defold/editor2-issues#230]
If the editor could download the engine binaries based on a preference setting it would be possible to stay with an older version of the engine even though the editor is updated. At the moment this is only possible by using bob or replacing the binaries within the folder structure.

Another huge benefit of this would be that the editor could be completely decoupled from the engine during the build step, which could provide a huge advantage in build speed.

**Comment by erikangelin-king** [comment]
Won't fix, but we'll make it easier to find and use older versions of the editor/engine.
