### ISSUE TITLE
Can't click to move elements in Editor

### ISSUE THREAD

**Issue by SolarLune** [defold/editor2-issues#2301]
### Expected behaviour

To click on the handles for movement or rotation and drag to move or rotate an element in the editor.

### Actual behaviour

Clicking and dragging on the handles will go "through" the handle, just becoming an ordinary click and drag selection box, as though I missed the collision boxes for the editor controls. [Here](https://gfycat.com/PertinentEcstaticHarborseal)'s a very short video to show what I mean.

I don't remember it doing this when I checked out Defold last a couple of months ago, so it might have been something between those releases?

### Steps to reproduce

For me, just clicking and dragging on the controls for an element in the editor space.

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-02T17:12:03.085485</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b157b90a2ea5e8b67483d626b1e75ff3bc7d5e6b</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>GPU</td><td>GeForce GTX 660/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 410.73</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux (Solus OS)</td></tr>
<tr><td>OS version</td><td>4.18.16-96.current</td></tr>
<table>

**Comment by AGulev** [comment]
As I know it was solved in latest 1.2.141, just try to update your editor.

**Comment by SolarLune** [comment]
Wow, no way, I was one version short, haha. I searched and didn't see an issue for this - must've just missed it. Thanks, updating did fix it!
