### ISSUE TITLE
The graphics device does not support: glGenBuffers

### ISSUE THREAD

**Issue by BrancoSmith** [defold/editor2-issues#2302]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-06T17:27:14.747323</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3fbdc79eee27ccde2734dae9d246fdbee1230b35</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b74cd01c51734dfc8aabc1c43df9f746"'>b74cd01c51734dfc8aabc1c43df9f746</a></td></tr>
<tr><td>GPU</td><td>GDI Generic</td></tr>
<tr><td>GPU Driver</td><td>1.1.0</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @BrancoSmith! Please try the steps in this faq: https://github.com/defold/editor2-issues/blob/master/faq/glgenbuffers.md
