### ISSUE TITLE
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by Stiforov** [defold/editor2-issues#2306]
### Expected behaviour
New Project
### Actual behaviour
Can't create new
### Steps to reproduce
Download Editor 2 (for Windows 64-bit) from www.defold.com.
Open Editor
Choose NEW PROJECT > From Tutorial > choose 'Side scroller tutorial'.
Then, Error Dialog opend.
In Dialog, the message was blow
An error occurred:
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-09T15:24:51.916326</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>58b8611c77561e4b55816e48d9a43765af0b0bec</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3c368560b74746948cc86d9cc443fdc5"'>3c368560b74746948cc86d9cc443fdc5</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by Stiforov** [comment]
I read this:
https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md
But it did not help me.

**Comment by erikangelin-king** [comment]
Do you have any antivirus software running?

**Comment by Stiforov** [comment]
Yes, I have Kaspersky, but I shut it down before I starting the Defold.

**Comment by erikangelin-king** [comment]
Shutting it down might not be enough, can you try disabling scanning of encrypted connections? https://forum.kaspersky.com/index.php?/topic/371162-how-to-disable-ssl-interception/
We should probably add a feature for adding arbitrary trusted certificates but it's not a high priority currently.

**Comment by Stiforov** [comment]
Oh, it's alive! Thank You!
