### ISSUE TITLE
Bug Upon Engine Start

### ISSUE THREAD

**Issue by MisaStudios** [defold/editor2-issues#2307]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-09T15:24:35.320102</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>58b8611c77561e4b55816e48d9a43765af0b0bec</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9ba9c2bec4a3467a92fc515d73db80e6"'>9ba9c2bec4a3467a92fc515d73db80e6</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.13.0-36-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Does any of this help? https://www.defold.com/faq/#_linux_issues
