### ISSUE TITLE
Assets deleted instead of being renamed if only capitalization changes [DEFEDIT-1491]

### ISSUE THREAD

**Issue by K-Klear** [defold/editor2-issues#2308]
### Expected behaviour
Asset changes name in commit
### Actual behaviour
Asset gets deleted
### Steps to reproduce

1. Change the capitalization of a name of an asset
2. Synchronize and try to push changes.

Screenshot: https://i.imgur.com/gv3TyGY.png

Note that the assets get deleted whether you push the commit or not. Once you get to the push screen, they are already lost.

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-06T17:27:14.747323</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3fbdc79eee27ccde2734dae9d246fdbee1230b35</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>GPU</td><td>GeForce GTX 670/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 390.65</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
The screenshot shows the renamed files as both Added and Deleted. They are not lost. The file under the old name was Deleted, and the same file was Added under the new name.

This is normal. When a file is renamed or moved, Git tries to detect these pairs of Adds and Deletes and combine them into a Rename. However, if changes were also made to the renamed file in the same commit, the contents of the file might differ enough for Git to not consider the files one and the same.

This is not very serious, though, as pretty much the only thing that happens is that the `git log` command will not be able to show the history of changes to the file past the rename. The actual files in your project are perfectly safe, though.

Hope that explains what happened. Feel free to reopen the issue if you disagree with the explanation!

**Comment by K-Klear** [comment]
> The screenshot shows the renamed files as both Added and Deleted. They are not lost. The file under the old name was Deleted, and the same file was Added under the new name.

Nope. It only deletes them. I should know - I lost half of my project because I decided to change the capitalization on some folders (I was able to recover most of it, though) Here's a better screenshot:

https://i.imgur.com/SSRptaC.png

Also note that for some reason the removal happens even if the push is cancelled.
