### ISSUE TITLE
Open project from context menu with Defold App 

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2310]
Quite sure it should be reported but can't find it.

### Expected behaviour
Opens selected project

### Actual behaviour
![screen shot 2018-11-12 at 11 36 30](https://user-images.githubusercontent.com/5273682/48425844-ebe27480-e765-11e8-9598-2639f8289156.png)

### Steps to reproduce
Right click on a game.project and use "open with..."

**Comment by markusgustavssonking** [comment]
#658 Solves this.
