### ISSUE TITLE
Open project by suplying a path to Defold

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2311]
### Expected behaviour
Immediately opens the project by skipping the splash

### Actual behaviour
Opens the splash

### Steps to reproduce
Try to open Defold from the terminal e.g.
`/Applications/Defold.app/Contents/MacOS/Defold /Users/jerakin/Documents/repositories/defold_project/game.project`

**Comment by markusgustavssonking** [comment]
#658 Solves this.
