### ISSUE TITLE
Debugger crashes when using gui nodes as keys in tables

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#2316]
### Expected behaviour
I should be able to set breakpoints and step through any Lua code without problems

### Actual behaviour
I'm not able to step through the Lua code since the debugger crashes

### Steps to reproduce
Set a breakpoint in the init() function of the attached gui_script.
Step through the code
Notice that the debugger crashes on the line where the second gui node is set as a key in the table (`nodes[box2] = {}`)

See attached project:
[guidebugcrash.zip](https://github.com/defold/editor2-issues/files/2584678/guidebugcrash.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-14T10:25:11.486561</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>dfbd3470660278721c7a0eea27f9e57d53590564</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.32.0 355.11.10.10.40.102</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.6</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed!
