### ISSUE TITLE
Bundle Android fails when Android.manifest moved.

### ISSUE THREAD

**Issue by gerrykwok** [defold/editor2-issues#2317]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-06T17:27:14.747323</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3fbdc79eee27ccde2734dae9d246fdbee1230b35</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"721e1f63221a4442b64f279090538f1f"'>721e1f63221a4442b64f279090538f1f</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4600</td></tr>
<tr><td>GPU Driver</td><td>4.3.0 - Build 10.18.14.4578</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @gerrykwok! Can you share the project with us (invite erik.angelin@king.com) or tell us how to reproduce it from scratch?

**Comment by gerrykwok** [comment]
Sorry,I had solved it.I had moved the Android.manifest file, so Defold got error when bundle android.

________________________________
evakwok1981@hotmail.com

**Comment by AGulev** [comment]
Solved in 1.2.157 https://forum.defold.com/t/defold-1-2-157-has-been-released/55935
