### ISSUE TITLE
adding bonus star / Could not initialize class com.defold.libs.TexcLibrary

### ISSUE THREAD

**Issue by kavata9** [defold/editor2-issues#2320]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-14T10:24:50.720775</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>dfbd3470660278721c7a0eea27f9e57d53590564</td></tr>
<tr><td>Defold engine sha</td><td>738e2ebc3cba56027fa00ca27706019bb772871c</td></tr>
<tr><td>Defold version</td><td>1.2.141</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b91479123f1848f381a14bb6ec248abd"'>b91479123f1848f381a14bb6ec248abd</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 520 (Skylake GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.0.5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-38-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @kavata9! This error is usually caused by a missing c++ runtime library. Please try the instructions given in this issue: https://github.com/defold/editor2-issues/issues/1792

**Comment by erikangelin-king** [comment]
Note: we should probably ship the runtime library

**Comment by erikangelin-king** [comment]
@kavata9 Did it help?

**Comment by kavata9** [comment]
yes  thank you...
Agnes Musyoka

Android Developer,

0724 971-796

kavatamusyoka24@gmail.com
