### ISSUE TITLE
Error when created a new project.

### ISSUE THREAD

**Issue by getJv** [defold/editor2-issues#2328]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-10-30T10:40:05.060369</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>96dc250f88a9afd4211c5389d7e22e9e01d91943</td></tr>
<tr><td>Defold engine sha</td><td>2fc8ff32c9fa3a16c8f4ce44eba8351c054b33dd</td></tr>
<tr><td>Defold version</td><td>1.2.140</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f3d66edff64b4800b82427ebe44b2e8b"'>f3d66edff64b4800b82427ebe44b2e8b</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @getJv!

We're working on improving this error message. It usually means there is an intervening firewall or antivirus software performing scanning of encrypted connections (this injects an unrecognised certificate along the chain to our servers causing the ssl connection establishment to fail). Read more here: https://github.com/defold/editor2-issues/blob/master/faq/pkixpathbuilding.md
Does this apply to your case?

**Comment by getJv** [comment]
Yeah. You are right. There is a corporate firewall here.

To solve this point. I went to the dashboard on website, created the
project from there and then import it to my pc using the IDE.

Thanks for you info.

Em qua, 21 de nov de 2018 14:15, erikangelin-king <notifications@github.com
escreveu:

**Comment by erikangelin-king** [comment]
Closing. We now show a more helpful error message and link to the FAQ.
