### ISSUE TITLE
error starting defold 2

### ISSUE THREAD

**Issue by CHIESOFTWARE** [defold/editor2-issues#2331]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-20T13:31:01.150569</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>dad5cf07671cbbe4040b69122128f834d379c7e2</td></tr>
<tr><td>Defold engine sha</td><td>6230c40dfa051a311aa4005c19097574e062374d</td></tr>
<tr><td>Defold version</td><td>1.2.142</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d1c8c845e9224d3385abb09f11cfcbc0"'>d1c8c845e9224d3385abb09f11cfcbc0</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-39-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @CHIESOFTWARE! Can you try the workaround described here: https://www.defold.com/faq/#_linux_issues
Please report back whether it worked for you. Some seem to get a completely black scene editor.

**Comment by CHIESOFTWARE** [comment]
hi, did not work, i can change the configuration of mesa, the system do not recognise the command EXPORT i try without export but nothing happens .

**Comment by erikangelin-king** [comment]
Hi @CHIESOFTWARE! Did you run the commands in a terminal / shell prompt? It doesn't say in the FAQ but you need to `cd` to the defold directory for `./Defold` to work.
