### ISSUE TITLE
Debbuger crashed dmengine after click continue btn

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#2343]
### Steps to reproduce
1)Open projeckt
2)set breakpoint to init in init_controller
3)Run with debbuger
4)Select continue
5)dmengine not responce

https://yadi.sk/d/5fgNhDTUTW08pg
<hr/>

<table>
<tr><td>Build time</td><td>2018-11-28T10:40:18.269998</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>496c3b0afba64917c0993ed33be59c081d2ad99a</td></tr>
<tr><td>Defold engine sha</td><td>6230c40dfa051a311aa4005c19097574e062374d</td></tr>
<tr><td>Defold version</td><td>1.2.142</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4600</td></tr>
<tr><td>GPU Driver</td><td>4.2.0 - Build 10.18.10.4425</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed I think, sometimes get an out of memory error though because of too much state to serialise in the scope around the breakpoint.
