### ISSUE TITLE
Re-adding game object makes it not appear in Outline view [DEFEDIT-736]

### ISSUE THREAD

**Issue by RagnarSvenssonKing** [defold/editor2-issues#235]
Found by @matgis-king 

Found a bug when adding an embedded game object to a collection file.

1. Open main.collection.
2. Right-click on the Collection in the Outline view and select Add Game Object.
3. Undo.
4. Undo again. Note that nothing is selected in the Outline.
5. Repeat step 2.

Expected: The new game object appears in the Outline
Actual: The new game object does not appear in the Outline, but its properties are shown. Closing and reopening the collection file makes the new game object show up in the Outline.

**Comment by matgis-king** [comment]
Re-tested this today, and the issue remains.

**Comment by erikangelin-king** [comment]
Can't repro
