### ISSUE TITLE
Unable to bundle on every Platform

### ISSUE THREAD

**Issue by sebfitz** [defold/editor2-issues#2354]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-12-06T14:26:29.007950</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1b977585ca43899e522c05ba562f76dd6571baa1</td></tr>
<tr><td>Defold engine sha</td><td>d13de133800e52aeda921e270d1d7340d5ac6684</td></tr>
<tr><td>Defold version</td><td>1.2.143</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 680 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-12.0.19 355.11.10.50.10.103</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We're on it!

**Comment by sebfitz** [comment]
great to hear. i tought i messed it up;)

**Comment by erikangelin-king** [comment]
Just merged a fix, an update should be available shortly. Thanks for reporting!

**Comment by sebfitz** [comment]
perfect, working again. thanks for the fast reaction
