### ISSUE TITLE
Shift Tab causes error in editor 2.0

### ISSUE THREAD

**Issue by trojanfoe** [defold/editor2-issues#2357]
### Expected behaviour
Cursor would move one tab to the left
### Actual behaviour
Error dialog with message "clojure.lang.ExceptionInfo: handler ':backwards-tag-trigger' in context ':code-view' failed at ':run' with message 'null'.
### Steps to reproduce
Press shift-tab while editing.
<hr/>

<table>
<tr><td>Build time</td><td>2018-12-07T14:29:09.379003</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>733561c366c9b1593d2011ad61757dccdb8fb505</td></tr>
<tr><td>Defold engine sha</td><td>d13de133800e52aeda921e270d1d7340d5ac6684</td></tr>
<tr><td>Defold version</td><td>1.2.143</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2f992648608e4523ae0e2cbf15b7083a"'>2f992648608e4523ae0e2cbf15b7083a</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 22.20.16.4836</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Do you have steps to reproduce? Can you share the .script where this happened?

**Comment by erikangelin-king** [comment]
Please reopen if you can repro.
