### ISSUE TITLE
Script can be opened in many tabs if file is moved

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#236]
### Expected behaviour
Opening a file after moving it will open the same tab as was previously opened.

### Actual behaviour
A new tab is opened for the file, resulting in two tabs being open.

### Steps to reproduce
Create a script file and a folder
Make sure the script file is open
Move the script file into the folder
Open the file again

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
Also applies for file renames. In that case the old tab retains the old name of the file, which is a bug in itself.

**Comment by ragnard-king** [comment]
Fixed by defold/defold#1158
