### ISSUE TITLE
[Community Website] Support for .rst files 

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2361]
My project uses README.rst and LICENCE files

While the uploader only take .md files.
![screen shot 2018-12-11 at 10 34 14](https://user-images.githubusercontent.com/5273682/49791268-6932e200-fd30-11e8-9ed7-9936763bab31.png)

Would be good with support for other formats too.

**Comment by AGulev** [comment]
Outdated. The dashboard is shutted down.
