### ISSUE TITLE
OutOfMemory

### ISSUE THREAD

**Issue by redasuio1** [defold/editor2-issues#2363]
> 
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-12-07T14:29:01.880730</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>733561c366c9b1593d2011ad61757dccdb8fb505</td></tr>
<tr><td>Defold engine sha</td><td>d13de133800e52aeda921e270d1d7340d5ac6684</td></tr>
<tr><td>Defold version</td><td>1.2.143</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"452833c33520406bbb8771ccc7d3966a"'>452833c33520406bbb8771ccc7d3966a</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 6450</td></tr>
<tr><td>GPU Driver</td><td>4.5.13399 Compatibility Profile Context 15.200.1062.1004</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by MasihAkbari** [comment]
Very Useful 😐
