### ISSUE TITLE
[INCONSISTENCY] Script template indents with spaces, but tab and autoformat indents with tabs

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#237]
### Expected behaviour
Script templates should also use tabs for indentation.

### Actual behaviour
Script templates are indented with spaces until you auto-format them by selecting all and pressing tab.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
In the end it would be really nice if we could make our own script and shader templates. Maybe even per project. Usually in a project there are certain things you always want to have present in a script or lua module that is very specific to that project. Like a require or a certain form to follow.

**Comment by ragnard-king** [comment]
Templates updated to only contain tabs.
