### ISSUE TITLE
Defold problem Centos 7 running MATE Desktop

### ISSUE THREAD

**Issue by ice2642** [defold/editor2-issues#2373]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-12-18T15:04:40.837005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e6badbdfbe3d296da36f9f8e2e4848ffdfb9a971</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"e13791cd0498412d9e7cb35f7a233046"'>e13791cd0498412d9e7cb35f7a233046</a></td></tr>
<tr><td>GPU</td><td>NVS 300/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>3.3.0 NVIDIA 340.107</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>3.10.0-957.1.3.el7.x86_64</td></tr>
<table>

The Editor 2 Pre release (1.2.115) work. but some games not work, like war battles tutorial. it return The file 'null' could not be loaded.

Sorry about my ENglish

**Comment by matgis-king** [comment]
It looks like the engine is having trouble loading the PVRTexLib library we depend on for texture compression. Seems it was compiled against `CXXABI_1.3.8`, which was introduced in the `libstdc++` that shipped with GCC 4.9.

The engine is unable to start without the correct version of `libstdc++`. It is possible you could get it working by installing a more recent version of GCC and making sure the engine can find it.

This article might help:
http://gcc.gnu.org/onlinedocs/libstdc++/faq.html#faq.how_to_set_paths

**Comment by matgis-king** [comment]
User got it to work on a different distro. See discussion in #2376.
