### ISSUE TITLE
CentOS 7 problem

### ISSUE THREAD

**Issue by ice2642** [defold/editor2-issues#2376]
ice2642@ice ~]$ export LD_LIBRARY_PATH=${prefix}/lib:$LD_LIBRARY_PATH
[ice2642@ice ~]$ gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Downloading packages:
(1/2): devtoolset-7-gcc-plugin-devel-7.3.1-5.13.el7.x86_64 | 1.3 MB   00:04     
(2/2): devtoolset-7-gcc-gdb-plugin-7.3.1-5.13.el7.x86_64.r | 124 kB   00:06     
--------------------------------------------------------------------------------
Total                                              225 kB/s | 1.5 MB  00:06     
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Instalando   : devtoolset-7-gcc-plugin-devel-7.3.1-5.13.el7.x86_64        1/2 
  Instalando   : devtoolset-7-gcc-gdb-plugin-7.3.1-5.13.el7.x86_64          2/2 
  Verifying    : devtoolset-7-gcc-gdb-plugin-7.3.1-5.13.el7.x86_64          1/2 
  Verifying    : devtoolset-7-gcc-plugin-devel-7.3.1-5.13.el7.x86_64        2/2 

Instalados:
  devtoolset-7-gcc-gdb-plugin.x86_64 0:7.3.1-5.13.el7                           
  devtoolset-7-gcc-plugin-devel.x86_64 0:7.3.1-5.13.el7                         

Concluído!
[ice2642@ice ~]$ scl enable devtoolset-7 bash
[ice2642@ice ~]$ which gcc
/opt/rh/devtoolset-7/root/usr/bin/gcc
[ice2642@ice ~]$ gcc --version
gcc (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

[ice2642@ice ~]$ 

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-12-18T15:04:40.837005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e6badbdfbe3d296da36f9f8e2e4848ffdfb9a971</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"efe5b69342e444f1b4f942776bcc819f"'>efe5b69342e444f1b4f942776bcc819f</a></td></tr>
<tr><td>GPU</td><td>NVS 300/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>3.3.0 NVIDIA 340.107</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>3.10.0-957.1.3.el7.x86_64</td></tr>
<table>

**Comment by matgis-king** [comment]
Note: This was an attempt to fix the problem from #2376.

I think you need to update `LD_LIBRARY_PATH` to point to the updated version of `libstdc++` after you've installed the newer version of GCC. Also, I'm not sure if you're supposed to replace `${prefix}` with the path to wherever the new `libstdc++` ended up.

Sorry I'm unable to be more helpful. Most of the dev team is still on vacation, but will be back next week.

**Comment by matgis-king** [comment]
Thanks for letting us know! Hope you enjoy using Defold!
