### ISSUE TITLE
Defold Crash When Deleting Open File

### ISSUE THREAD

**Issue by alexander-e-andrews** [defold/editor2-issues#2377]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2018-07-18T17:37:42.353005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4828309a21aaec8b7e6d80351d863c6a15a486d9</td></tr>
<tr><td>Defold engine sha</td><td>7b2c2c019d6fa106f78e2e98cd3009a21d4095aa</td></tr>
<tr><td>Defold version</td><td>1.2.133</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9438fe7bcbd24b73aeb0503f993000cb"'>9438fe7bcbd24b73aeb0503f993000cb</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 5300</td></tr>
<tr><td>GPU Driver</td><td>4.4.0 - Build 20.19.15.4549</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Thanks for reporting, but this has already been fixed. You'll get the fix if you update to the latest version of the editor.
