### ISSUE TITLE
New-line indentation sometimes resets to first column

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#238]
### Expected behaviour
Indentation should always be at the depth determined by the previous line when doing newline

### Actual behaviour
On rare occasions it jumps all the way back to the far left

### Steps to reproduce
Very unsure how to reproduce this, because it doesn't happen all the time. It seems to be some special occasions it occurs while writing normal code.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Closing, since have new code editor with new rules.
