### ISSUE TITLE
Null Pointer exception if androidmanifest.xml doesn't live at the specified location

### ISSUE THREAD

**Issue by Sahbum** [defold/editor2-issues#2380]
### Expected behaviour
Build an android version
### Actual behaviour
Error: Null pointer exception
### Steps to reproduce
Trying to get Lerg's admob extension working, originally had it as a separate folder and included it through include dirs, but removed it there and added it as a dependency.  

I had my AndroidManifest.xml set to the one in the admob/ folder when I tried to build.  Resetting that to my / folder (where my AndroidManifest.xml) lives, and the error goes away.
<hr/>

<table>
<tr><td>Build time</td><td>2018-12-18T15:04:40.837005</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e6badbdfbe3d296da36f9f8e2e4848ffdfb9a971</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"205010a87c284c81b26b412612027f83"'>205010a87c284c81b26b412612027f83</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) Ivybridge Mobile </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.0.5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.4.0-135-generic</td></tr>
<table>

**Comment by AGulev** [comment]
related https://github.com/defold/editor2-issues/issues/2317

**Comment by AGulev** [comment]
Solved in 1.2.157 https://forum.defold.com/t/defold-1-2-157-has-been-released/55935
