### ISSUE TITLE
Long https responses time out with SSL status code -261 warning

### ISSUE THREAD

**Issue by mdm373** [defold/editor2-issues#2381]
### Expected behaviour
Script handles HTTPS response / data after appropriate wait

### Actual behaviour
See logged warning : WARNING:DLIB: Unhandled ssl status code: -261
See logged error: ERROR:SCRIPT: HTTP request to 'https://testapi.betterdoggo.com/defold-demo/?wait=long' failed (http result: -1  socket result: -1000)
HTTPS response resolves with error

If project network timeout is set to zero, the same issue occurs, but no SSL error code is logged

### Steps to reproduce
Launch demo app. Press 1, 2 or 3. Demo URL will wait for 100, 300 or 700 ms approximately before responding. 100 generally accepts, 300 has mixed results and 700 ms almost always fails. This happens no matter what the network timeout is set to in the project settings
[defold-demo.zip](https://github.com/defold/editor2-issues/files/2729242/defold-demo.zip)

<table>
<tr><td>Build time</td><td>2018-12-18T15:04:58.078787</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e6badbdfbe3d296da36f9f8e2e4848ffdfb9a971</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 416.34</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Created engine issue DEF-3690

**Comment by AGulev** [comment]
Solved in [1.2.162](https://forum.defold.com/t/defold-1-2-162-has-been-released/62959)
