### ISSUE TITLE
Option to disable auto quote/parenthesis completion

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#239]
While a typing saver in theory, I usually find myself spending more time removing extra inserted quotes/parenthesis than I ever do writing them in the first place. Especially when they cause an error I didn't catch.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Quick-win by simply removing auto-closing for now.

**Comment by erikangelin-king** [comment]
We no longer auto close
