### ISSUE TITLE
cannot build html 5 

### ISSUE THREAD

**Issue by Ceydigitaluditha** [defold/editor2-issues#2395]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-01-10T10:42:34.806706</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e064eb3537e95db69e4882fd990b46c41d3d25c2</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"89393349af5f4aa0a687bc2d88b3f3ab"'>89393349af5f4aa0a687bc2d88b3f3ab</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-10.32.48</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.4</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can you share the project? Just add erik.angelin@king.com to the team and we'll have a look.
