### ISSUE TITLE
running on mac

### ISSUE THREAD

**Issue by Nacintosh45** [defold/editor2-issues#2396]
### Expected behaviour
Run a project with a debugger window.
### Actual behaviour
Defold gives me an error message, and then Defold crashes. If an option is not selected in the error window, Defold itself crashes, in the crash dialog, if reopen is not selected, I have to restart my mac to launch Defold again. On one attempt Defold crashed while trying to open up my project.
### Steps to reproduce
Run Defold > Open Project > Debug - Run with debugger (result below)
<img width="555" alt="screen shot 2019-01-10 at 11 23 41 pm" src="https://user-images.githubusercontent.com/16532083/51014907-8fb28b80-152f-11e9-9c05-5e04aa0fb275.png">
<hr/>

<table>
<tr><td>Build time</td><td>2019-01-10T10:41:43.402686</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e064eb3537e95db69e4882fd990b46c41d3d25c2</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"94ddc241459c4edf9fa989fd76c9f238"'>94ddc241459c4edf9fa989fd76c9f238</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.2</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @Nacintosh45! 
So this is actually two different errors.
First you're affected by a crash on macos Mojave: https://github.com/defold/editor2-issues/issues/2218
Workaround here: https://forum.defold.com/t/defold-editor-and-mac-os-mojave/30762/6
Second, something prevents the editor part of the debugger from connecting to the engine. Could be a network issue, or if you're using a release version of the engine or a custom engine with the debugger stripped away. Does this happen on a blank project?
