### ISSUE TITLE
crash on custom code editor

### ISSUE THREAD

**Issue by spartaman** [defold/editor2-issues#2397]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-01-10T10:42:34.806706</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e064eb3537e95db69e4882fd990b46c41d3d25c2</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"eee9a904c70c4a8d87b0b2f063ca0ff9"'>eee9a904c70c4a8d87b0b2f063ca0ff9</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GTX 775M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-12.0.21 355.11.10.50.10.103</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.2</td></tr>
<table>

**Comment by matgis-king** [comment]
It looks like Visual Studio Code changed the name of the MacOS executable inside the App bundle. Try changing the Custom Editor path to `/Applications/Visual Studio Code.app/Contents/MacOS/Electron`. Please feel free to reopen this issue if that does not solve it!
