### ISSUE TITLE
Parenthesis pair hilighting when under cursor

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#240]
When cursor is under a parenthesis it would help a lot of the corresponding opening/close parenthesis was made bold, underlined or different color.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Fixed in new code editor
