### ISSUE TITLE
java.lang.NullPointerException: Unknown during building Android bundle

### ISSUE THREAD

**Issue by funtikar** [defold/editor2-issues#2400]
### Expected behaviour
Compile Android Bundle successfully and get working APK

### Actual behaviour
Error occurs, no working APK generated
![image](https://user-images.githubusercontent.com/3684644/51118335-15457c80-184b-11e9-8523-d617e015898f.png)

### Steps to reproduce
Open a mobile game template, no modification done and build to Android Bundle 
<hr/>

<table>
<tr><td>Build time</td><td>2019-01-10T10:42:34.806706</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e064eb3537e95db69e4882fd990b46c41d3d25c2</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>GPU</td><td>GeForce GTX 650 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 398.82</td></tr>
<tr><td>Java version</td><td>1.8.0_191-b12</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment]
Possible duplicate of #2330, #2251?

**Comment by matgis-king** [comment]
Note: Unable to reproduce on my machine. Tried both with a certificate and without.

**Comment by matgis-king** [comment]
@funtikar It looks like something goes wrong in the signing process. Can you provide more info about which settings you use in the bundle dialog? Are you specifying a certificate and key? Did you follow the [Android development guide](https://www.defold.com/manuals/android/) when generating them?

**Comment by funtikar** [comment]
> @funtikar It looks like something goes wrong in the signing process. Can you provide more info about which settings you use in the bundle dialog? Are you specifying a certificate and key? Did you follow the [Android development guide](https://www.defold.com/manuals/android/) when generating them?

my bad ,some settings in my openssl installation messed up  I didn't properly generate the certificates and keys.
