### ISSUE TITLE
Shadow appeared on a Text nodes after updating to 1.2.144 from 1.2.142

### ISSUE THREAD

**Issue by MaratGilyazov** [defold/editor2-issues#2406]
### Expected behaviour
When update from Editor version 1.2.142 to 1.2.144 your text nodes keep looking the same as before the update 
### Actual behaviour
After the update there is a weird white outline which seems to be caused by the Shadow alpha set to 1 in text node settings
### Steps to reproduce
1) Open the project attached in 1.2.142 and make sure there is no white outline/shadow
2) Open the same project in 1.2.144 and see, that there is strange white outline/shadow now

So, either shadow alfa has changed from 0 to 1, or just was not working before, can't say, but for sure it was not shown before the update

Project: [catapult.zip](https://github.com/defold/editor2-issues/files/2770817/catapult.zip)

Screenshots from 1.2.142 and 1.2.144: 
<img width="250" alt="screenshot 2019-01-17 at 23 23 28" src="https://user-images.githubusercontent.com/15916299/51353203-35c24080-1ab0-11e9-8355-fc7e1e21ca30.png"> <img width="300" alt="screenshot 2019-01-17 at 23 23 08" src="https://user-images.githubusercontent.com/15916299/51353202-3529aa00-1ab0-11e9-9568-5903020db797.png"> 

<hr/>

<table>
<tr><td>Build time</td><td>2019-01-14T18:23:47.720513</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f2dd34486d0c5201dcd791380e2c9304a516348b</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 655</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.2.17</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.1</td></tr>
<table>

**Comment by jhonnyking** [comment]
Previous to 1.2.144 we didn't have any shadow shading in the default font shaders regardless of settings in the font, even though we generated shadows in the resource compilation step. By looking at your project, you have shadows enabled (shadow alpha > 0) in the font you are using so that's why it just appeared in the latest release. Setting alpha to zero in the font or in the label/text node would fix your issue.
