### ISSUE TITLE
Clicking on result line in find in files does not open the file

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#241]
### Expected behaviour
Double clicking on a search result would open that file and put the cursor on that line.

### Actual behaviour
It just closes the window and returns to where you were before in the text editor.

### Steps to reproduce
While in text editor (may not be required)
Search in files via Cmd+Shift+F
Get a multi-file search result (may not be required)
Double click on an item that isn't an open file

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
If unsure about fix, ask me.

**Comment by matgis-king** [comment]
This was fixed as part of defold/defold#1122, which was just merged into `dev`.
