### ISSUE TITLE
MacOS: Small popups like "delete file" become fullscreen when app is in fullscreen mode

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#242]
### Expected behaviour
It should be a small popup or something sliding out or similiar.

### Actual behaviour
The delete file popups takes over the whole screen in a new "desktop"

### Steps to reproduce
On Mac OS:
Make Defold fullscreen (the green button)
Right click and delete a file from the editor

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by ragnard** [comment]
Duplicate of https://github.com/defold/editor2-issues/issues/49

**Comment by erikangelin-king** [comment]
Can't repro
