### ISSUE TITLE
Can't build project on my old notebook

### ISSUE THREAD

**Issue by crewsycrews** [defold/editor2-issues#2427]
### Expected behaviour
Build project
### Actual behaviour
Stops with error: 
java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
java.lang.OutOfMemoryError: Java heap space
### Steps to reproduce
I was developing a game on GGJ 2019 on computer of my brother. Then i turn back home to my notebook and when i clone my [project](https://github.com/crewsycrews/Snowman-s-Home) it can't build it.
<hr/>

<table>
<tr><td>Build time</td><td>2019-01-10T10:42:34.806706</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e064eb3537e95db69e4882fd990b46c41d3d25c2</td></tr>
<tr><td>Defold engine sha</td><td>8def4b50c9aa049670e698d7dff3dc00d77e42d5</td></tr>
<tr><td>Defold version</td><td>1.2.144</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"e7c1a4d5c2764a7fb6a12f0bb2e69e1c"'>e7c1a4d5c2764a7fb6a12f0bb2e69e1c</a></td></tr>
<tr><td>GPU</td><td>ATI Mobility Radeon HD 5470</td></tr>
<tr><td>GPU Driver</td><td>4.0.10242 Compatibility Profile Context</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment]
It looks like your project does not fit in the available RAM.

First of all, make sure you've installed the 64-bit version of the editor. On Windows, the 32-bit editor is only able to address a fraction of the memory available to the 64-bit version.

The Defold editor will use a portion of the available memory, so the memory available to the editor on a 16GB machine will be larger than that on a computer with only 4GB of RAM. You can hack the editor to reserve a larger chunk by editing the `config` file in the directory where you installed Defold.

Under the `[launcher]` section, append `-Xmx2048m,` to the start of the `vmargs` setting like this:
```
vmargs = -Xmx2048m,-Djna.nosys=true,...
```

The `2048` value tells the editor how many megabytes of memory to reserve at startup. You can experiment with different values for `2048`, and you might be able to get it to work that way. If you set it too low your project might not fit, but if you set it too high the editor might take precious memory from other applications and slow them down.
