### ISSUE TITLE
IO Sign fail

### ISSUE THREAD

**Issue by dasannikov** [defold/editor2-issues#2429]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-01-28T15:35:59.785060</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c043948fbf2c57e88d4ca921ea9ab135081bb7e7</td></tr>
<tr><td>Defold engine sha</td><td>9f376d88408bad9088a4187d4f874ae4767a0185</td></tr>
<tr><td>Defold version</td><td>1.2.145</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6d91496eb1c24ba9a20fcc6889d8614f"'>6d91496eb1c24ba9a20fcc6889d8614f</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.2</td></tr>
<table>

**Comment by dasannikov** [comment]
<img width="549" alt="2019-01-30 19 58 00" src="https://user-images.githubusercontent.com/1015770/52001975-72873200-24c9-11e9-815d-10b8c5488081.png">
<img width="538" alt="2019-01-30 19 58 19" src="https://user-images.githubusercontent.com/1015770/52001977-72873200-24c9-11e9-9754-735edd48eea1.png">

**Comment by amel** [comment]
Ah, I have the same issue #2431

**Comment by tallen11** [comment]
I've got this as well, any update?

**Comment by laltin** [comment]
Same here any fix ?

**Comment by erikangelin-king** [comment]
Should be fixed by now, please reopen this issue if it still does not work after updating the editor!
