### ISSUE TITLE
MacOS fullscreen app flickers once when switching to it

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#243]
### Expected behaviour
No flicker

### Actual behaviour
It flickers

### Steps to reproduce
Fullscreen the app
Switch to an other fullscreen app
Switch back to defold

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Closed as unable to reproduce.
