### ISSUE TITLE
Old updates never delete (Windows)

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#2430]
https://forum.defold.com/t/editor2-size/9637

C:\Users\[USERNAME]\AppData\Local\Defold

![2019-01-30_19-24-51](https://user-images.githubusercontent.com/2209596/51987949-ced75b00-24a3-11e9-85e2-b262cd0b10de.png)
![2019-01-30_19-25-37](https://user-images.githubusercontent.com/2209596/51987950-ced75b00-24a3-11e9-9dd2-faf03ec35747.png)
![2019-01-30_19-25-49](https://user-images.githubusercontent.com/2209596/51987952-ced75b00-24a3-11e9-968f-02741a9aa9a0.png)

**Comment by AGulev** [comment]
https://github.com/defold/editor2-issues/issues/630

**Comment by K-Klear** [comment]
Yeah, I'd love to see this sorted. I've got a quite small system drive and have to manually delete the defold folder in AppData every once in a while.

**Comment by realstudent** [comment]
I am also keep i mind to clean Defold AppData time to time. Good if editor updates make self cleanups.

**Comment by aglitchman** [comment]
After half a year of using Defold, the size of this directory is 4Gb. When will you do the automatic cleaning?
