### ISSUE TITLE
defold admob build error

### ISSUE THREAD

**Issue by vino10vino** [defold/editor2-issues#2435]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-01-21T16:41:39.690364</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>58f9a169ac6654b60c56bd013eb2765f4834fa16</td></tr>
<tr><td>Defold engine sha</td><td>9f376d88408bad9088a4187d4f874ae4767a0185</td></tr>
<tr><td>Defold version</td><td>1.2.145</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.4358</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vino10vino** [comment]
![t](https://user-images.githubusercontent.com/46936738/52113151-8dbf8200-262e-11e9-9718-e266352ee294.jpg)

when i bundle android application its shows this error

**Comment by mathiaswking** [comment]
Yes, I recall having to fiddle with the resource file in that example extension:
https://github.com/defold/extension-admob/blob/master/admob/README.md#the-resource-files

**Comment by mathiaswking** [comment]
And, if you were trying our example, there's another option to use this maintained version instead:
https://www.defold.com/community/projects/93085/
