### ISSUE TITLE
Crash when sign iOS app [DEFEDIT-1544]

### ISSUE THREAD

**Issue by ducrt7** [defold/editor2-issues#2437]
### Expected behaviour
create Linker Game sample project
Project > Sign iOS app... > Fill out all information > Sign > sign successfully.

### Actual behaviour
create Linker Game sample project
Project > Sign iOS app... > Fill out all information > Sign > Error Panel: `java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to java.io.File` > Crash

### Steps to reproduce
Project > Sign iOS app... > Fill out all information > Sign > Error Panel: `java.lang.ClassCastException: clojure.lang.PersistentArrayMap cannot be cast to java.io.File`

<hr/>

<table>
<tr><td>Build time</td><td>2019-01-28T15:36:49.949805</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>c043948fbf2c57e88d4ca921ea9ab135081bb7e7</td></tr>
<tr><td>Defold engine sha</td><td>9f376d88408bad9088a4187d4f874ae4767a0185</td></tr>
<tr><td>Defold version</td><td>1.2.145</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2bbaeda48933483cbb2fd7230596a362"'>2bbaeda48933483cbb2fd7230596a362</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 650M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-12.0.19 355.11.10.50.10.103</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#2429

**Comment by JCash** [comment]
As a workaround, you can ofc bundle your app, and install it using XCode or [ios-deploy](https://github.com/ios-control/ios-deploy)

**Comment by erikangelin-king** [comment]
This should be fixed by now :) Please update and retry. If it still fails, please reopen this issue!
