### ISSUE TITLE
[PRAISE] Text editor is more pleasant than expected

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#244]
Before I had only used the text editor for minor testing. Now I've been using it to actually write something. Now while it has quite some ways to go, it is way more pleasant to work with than expected.

Like I like how I can simply do Cmd+G to jump to next instance of the selected text. And overall it doesn't get in your way that much. I was expecting much more road bumps.

**Comment by RagnarSvenssonKing** [comment]
Thanks!
