### ISSUE TITLE
GUI and Collection editor not selecting what I click

### ISSUE THREAD

**Issue by Visne** [defold/editor2-issues#2444]
I'm having an issue where clicking an object in the GUI and Collection editor doesn't select it. Sometimes it selects something random, sometimes nothing at all. The arrows to move or blocks you can press to scale also don't work. Selection boxes also don't work.

I started this project on my laptop, which worked fine. Now I imported it on my desktop, and I have this issue. The only difference I can think of is that my desktop has an AMD GPU, my laptop an NVIDIA GPU.

**Comment by Visne** [comment]
This is also happening with other projects.

**Comment by erikangelin-king** [comment]
We have noticed issues around selection on amd graphics cards and are currently rewriting picking/box selection. Should be out this week or early next.

**Comment by erikangelin-king** [comment]
This was merged a while back, please reopen if the problem persists.
