### ISSUE TITLE
Automatic quotes doesn't detect when already in a string.

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#245]
If I am in the processing of writing code and I have the following code:

`msg.post(url, "my_message`

If I place the cursor at the end of that string and type a ", then it will insert automatically a second quote. It doesn't capture the context of already being inside a string. The code then looks like this, with the cursor planted between the quotes:

`msg.post(url, "my_message""`

If I try to correct the mistake by pressing backspace it will delete both, returning the code to the first state. Only way to get it right is to first move the cursor to the right one step and then backspace.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
See also: #239

**Comment by RagnarSvenssonKing** [comment]
Quick-fix by removing the auto-closing feature

**Comment by erikangelin-king** [comment]
We no longer auto close ".
