### ISSUE TITLE
Double-clicking Defold.app opens two instances of Defold and one hangs

### ISSUE THREAD

**Issue by prime31** [defold/editor2-issues#2453]
### Expected behaviour
- open a single Defold instance

### Actual behaviour
- two instances are spawned and one hangs and has to be force-quit

### Steps to reproduce
- just double click Defold.app on a Mac

<hr/>

<table>
<tr><td>Build time</td><td>2019-02-05T11:32:43.868034</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>30a28591528b8efef42c00476477a222a43e0811</td></tr>
<tr><td>Defold engine sha</td><td>851fbeb469987908d2b785fa3964003acc919394</td></tr>
<tr><td>Defold version</td><td>1.2.146</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.4.9</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.2</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We're working on it.

**Comment by AGulev** [comment]
Fixed in 1.2.147
https://forum.defold.com/t/defold-1-2-147-has-been-released/43851
