### ISSUE TITLE
[SUGGESTION] "Disable Update" checkbox in preferences

### ISSUE THREAD

**Issue by dasannikov** [defold/editor2-issues#2454]
It is very important to halt engine update on release stage (when you finish all polish and test and ready to submit to store)

**Comment by vlaaad** [comment]
We are currently reworking update mechanism so it will download new version only when explicitly asked for, stay tuned!

**Comment by vlaaad** [comment]
We just rolled out new update system to `editor-alpha` channel, now it will ask before updating.
