### ISSUE TITLE
Spine animation broken. Android version [DEF-3770]

### ISSUE THREAD

**Issue by dasannikov** [defold/editor2-issues#2455]
Broken spine animation on android devices.
samsung A8
galaxy s5

![photo_2019-02-08_10-59-54](https://user-images.githubusercontent.com/1015770/52468303-fcea2880-2b90-11e9-9975-60b3fe7b5588.jpg)
![photo_2019-02-08_11-00-00](https://user-images.githubusercontent.com/1015770/52468304-fcea2880-2b90-11e9-95d0-81ad799c9457.jpg)

<table>
<tr><td>Build time</td><td>2019-02-05T11:33:35.388337</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>30a28591528b8efef42c00476477a222a43e0811</td></tr>
<tr><td>Defold engine sha</td><td>851fbeb469987908d2b785fa3964003acc919394</td></tr>
<tr><td>Defold version</td><td>1.2.146</td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.2</td></tr>
<table>

**Comment by dasannikov** [comment]
Here is animation.
[lizzard.zip](https://github.com/defold/editor2-issues/files/2844344/lizzard.zip)

**Comment by dasannikov** [comment]
samsung A8
galaxy s5

huge webp textures

**Comment by dasannikov** [comment]
I have made release windows build today and have the same bug in spine animations.
Looks like it exists in all release build for any platform.

<img width="523" alt="2019-02-14 12 39 17" src="https://user-images.githubusercontent.com/1015770/52781591-9d3ec200-3055-11e9-9a2f-51bc7a97423b.png">

**Comment by dasannikov** [comment]
[LizzardBug.zip](https://github.com/defold/editor2-issues/files/2864604/LizzardBug.zip)
Here is simple project with bug (Build release too see bug)

**Comment by AGulev** [comment]
Fixed in 1.2.148 
https://forum.defold.com/t/defold-1-2-148-has-been-released/45411?u=agulev
