### ISSUE TITLE
Sometimes release engine does not close fully when exiting the game

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2458]
Got a report from a Windows 7 SP1

"The game after shutdown is hanging in the task manager"

We use 

```

 msg.post("@system:", "exit", {code = 0})

```

for exiting.

**Comment by AGulev** [comment]
looks similar to https://github.com/defold/editor2-issues/issues/2460
could you re-check, please?

**Comment by subsoap** [comment]
This issue was likely caused by DiscordRich extension and reports of hanging stopped coming when I disabled the extension for Win7 users.

**Comment by AGulev** [comment]
Thanks!
