### ISSUE TITLE
Editor crashes after losing focus while Synchronize window is opened

### ISSUE THREAD

**Issue by MaratGilyazov** [defold/editor2-issues#2459]
### Expected behaviour
no crashes after losing focus from any state
### Actual behaviour
Editor crashes after losing focus while Synchronize window is opened 
### Steps to reproduce
Open project, open File -> Synchronize, switch focus to any other app - observe that Defold has closed

logs: 
[editor2.2019-02-08.log](https://github.com/defold/editor2-issues/files/2846771/editor2.2019-02-08.log)

<hr/>

<table>
<tr><td>Build time</td><td>2019-02-05T11:33:35.388337</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>30a28591528b8efef42c00476477a222a43e0811</td></tr>
<tr><td>Defold engine sha</td><td>851fbeb469987908d2b785fa3964003acc919394</td></tr>
<tr><td>Defold version</td><td>1.2.146</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 655</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.2.17</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#2369

**Comment by erikangelin-king** [comment]
Try https://forum.defold.com/t/defold-editor-and-mac-os-mojave/30762/6

**Comment by MaratGilyazov** [comment]
> Try https://forum.defold.com/t/defold-editor-and-mac-os-mojave/30762/6

Seems to be working, thanks. Before I was able to repro the crash 3 times out of 5 tries, now I can't repro at all.
