### ISSUE TITLE
dmengine.exe is not responding when closing debug builds on Windows

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2460]
This frequently happens and has for a while. Closing with the windows X button on the top right causes this. It needs to be handled better to close gracefully!

**Comment by AGulev** [comment]
It seems like something related to `http`request  issue. We fixed it, could you please re-check this issue again?

**Comment by subsoap** [comment]
It does not seem like it happens as much now, at least I'm not noticing it.

**Comment by AGulev** [comment]
Thanks!
