### ISSUE TITLE
Error in Ubuntu 18.04

### ISSUE THREAD

**Issue by davidoshiro** [defold/editor2-issues#2462]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-02-05T11:33:21.156061</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>30a28591528b8efef42c00476477a222a43e0811</td></tr>
<tr><td>Defold engine sha</td><td>851fbeb469987908d2b785fa3964003acc919394</td></tr>
<tr><td>Defold version</td><td>1.2.146</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"017d34fb6c90414bb8b54de2835b0470"'>017d34fb6c90414bb8b54de2835b0470</a></td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-45-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
See if this helps: https://www.defold.com/faq/#_linux_issues

**Comment by davidoshiro** [comment]
This has resolved my issues.  Thank you. I'm hoping that these types of issues are addressed in future updates and is made more clear in the installation docs on the web site.
