### ISSUE TITLE
Defold 1.2.146 launch two instance

### ISSUE THREAD

**Issue by gerrykwok** [defold/editor2-issues#2479]
![a29ea300562596613ba8efdcd8c85e42](https://user-images.githubusercontent.com/19986292/52995983-22abe300-3457-11e9-86b5-d45b6bbacd85.png)
![0211a0e35733dc09eb9aa8cf4041fb52](https://user-images.githubusercontent.com/19986292/52995994-293a5a80-3457-11e9-9053-8ed487165e4d.jpg)
When I launch defold 1.2.146 in my mac, It appears two instance, one of two not responding.

**Comment by AGulev** [comment]
Fixed in 1.2.147
https://forum.defold.com/t/defold-1-2-147-has-been-released/43851
