### ISSUE TITLE
editing .proto files

### ISSUE THREAD

**Issue by AKashpur** [defold/editor2-issues#2482]
### Expected behaviour
work as usual

### Actual behaviour
pop ups error message:

java.lang.AssertionError: Assert failed: ["/resources/proto/buidlings_config.proto" "/resources/proto/custom_upgrade_config.proto" "/resources/proto/Animations.proto" "/resources/proto/autogeneration_config.proto" "/resources/proto/craft_config.proto" "/resources/proto/autogeneration_event_config.proto" "/resources/proto/items_config.proto"]
(not (seq unknown-changed))

### Steps to reproduce
added few .proto files to project;
 edit one of .proto files in atom, save changes in atom. switch back to defold
(filenames of changed files are in error message)
<hr/>

<table>
<tr><td>Build time</td><td>2019-02-20T17:05:45.447239</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7305429c80e7617f41732e76f77ba42409006cfc</td></tr>
<tr><td>Defold engine sha</td><td>5f1c6286a8bb1cfd8505517c1734f6d0666bf5df</td></tr>
<tr><td>Defold version</td><td>1.2.147</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b069a986d3654d1c87a37bc3a350eca2"'>b069a986d3654d1c87a37bc3a350eca2</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 25.20.100.6373</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! Thanks for reporting, this looks pretty serious. Did you get another error message before this happened? Can you reproduce it by following your own steps on a blank project?

**Comment by AKashpur** [comment]
could not reproduce just now on blank project.

On project where issue happened I checkout-ed between git branches via command prompt without returnig focus to defold, then redacted .proto files and then switching to defold.

**Comment by erikangelin-king** [comment]
Alright, if you find a way to repro it consistently or if it happens again, please comment.

**Comment by erikangelin-king** [comment]
Closing this for now. I suspect some other error occurred before this, putting the editors file system state out of sync.
