### ISSUE TITLE
NullPointerException and a crash when opening a collection or a model.

### ISSUE THREAD

**Issue by Lerg** [defold/editor2-issues#2485]
### Expected behaviour
Open collection and don't crash.

### Actual behaviour
![screen shot 2019-02-21 at 10 42 28 pm](https://user-images.githubusercontent.com/859486/53189747-07dd9800-362a-11e9-9bc4-9db57d252731.png)

### Steps to reproduce
Create a project, open collection.

Crash report
[editor_crash.txt](https://github.com/defold/editor2-issues/files/2890419/editor_crash.txt)

<hr/>

<table>
<tr><td>Build time</td><td>2019-02-21T18:18:25.830249</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1a1b35f99328139d77f29d49891865bbdef48b20</td></tr>
<tr><td>Defold engine sha</td><td>5f1c6286a8bb1cfd8505517c1734f6d0666bf5df</td></tr>
<tr><td>Defold version</td><td>1.2.147</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9fb7c3d4010743d889370aaa3854b45e"'>9fb7c3d4010743d889370aaa3854b45e</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon HD Tahiti XT Prototype OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.4.10</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by matgis-king** [comment]
Fix merged yesterday.
