### ISSUE TITLE
Play sprites doesn't work

### ISSUE THREAD

**Issue by Shoroh** [defold/editor2-issues#2487]
### Expected behaviour
I can preview sprite set animation by pressing the spacebar or choose Play in View menu.

### Actual behaviour
I can't do this: spacebar doesn't work, Play menu is disabled.

### Steps to reproduce
I just started a tutorial from main menu. 

### Screenshot
<img width="1670" alt="screen shot 2019-02-22 at 10 30 00 pm" src="https://user-images.githubusercontent.com/1865984/53266484-eba52e00-36f1-11e9-95f9-5f04f64d9f6d.png">

<hr/>

<table>
<tr><td>Build time</td><td>2019-02-22T20:05:58.366761</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>e7182ce4d1046ee865e9f4357a81d3e0486162be</td></tr>
<tr><td>Defold engine sha</td><td>5f1c6286a8bb1cfd8505517c1734f6d0666bf5df</td></tr>
<tr><td>Defold version</td><td>1.2.147</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.4.10</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix should be out by now!
