### ISSUE TITLE
Add option to make script ids to automatically be set to the name of the script [DEFEDIT-1058]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#249]
This is more or less a best practice in my book after using defold for quite some time. Having everything named "script" makes for a messy tree. But having it as an option is probably good because opinions are different.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
One thing to consider when creating new things in the outline is to automatically select the id after creation so that one can simply start typing to set a different than the default assigned id. This would apply to creation of game objects as well as adding scripts.

**Comment by matgis-king** [comment]
We decided to not make this an option. Now adding any component from a file names the instance after the file, just like we already do when adding instances of game objects and collections.
