### ISSUE TITLE
Wrong displayed position of rotated Collision Objects [DEFEDIT-1592]

### ISSUE THREAD

**Issue by JohannUlbrich** [defold/editor2-issues#2494]
## What happened
Since I updated the editor to version 1.2.148, the shapes of a collision object are displayed at the wrong position when they are rotated. However, this only affects the displayed position in the editor, not the real position in the game.
The markers for moving and scaling are in the correct position, but the shapes are displayed in a different position. So I can't edit my levels anymore. 

## Steps to reproduce
1. create a Game Object
2. add a collision object
3. add a box shape
4. rotate the box shape by 45 degrees
5. move the box to x = 200

The box is now moved incorrectly in y-direction.

![defold issue](https://user-images.githubusercontent.com/9569884/53846035-b5966280-3fab-11e9-8851-c3401d5da924.PNG)

**Comment by vlaaad** [comment]
Commited a fix into `editor-alpha` channel, update should arrive shortly.
