### ISSUE TITLE
Lack of GUI emitter state constants

### ISSUE THREAD

**Issue by coderm4ster** [defold/editor2-issues#2495]
https://www.defold.com/ref/gui/#gui.play_particlefx:node--emitter_state_function-

Non existent state constants:
gui.EMITTER_STATE_SLEEPING
gui.EMITTER_STATE_PRESPAWN
gui.EMITTER_STATE_SPAWNING
gui.EMITTER_STATE_POSTSPAWN

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-06T16:47:40.865682</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>cf7c0192d52b904e345cfddb4fca5e437d832e9d</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>GPU</td><td>GeForce GT 720/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 398.82</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by jhonnyking** [comment]
Wrong documentation, the state emums are on the particlefx table and not gui. Fixed in 1.2.149
