### ISSUE TITLE
java.lang.AssertionError: Assert Failed while dragging selection box inside an atlas

### ISSUE THREAD

**Issue by TurboSplash** [defold/editor2-issues#2498]
### Expected behaviour
Editor runs normally.
### Actual behaviour
Editor throws error dialog: "java.lang.AssertionError: Assert failed: (= (:pass render-args) pass/overlay)"
The tab inside which the atlas was open becomes unresponsive, selection rectangle then sticks to mouse position. Error pops back up if you try left clicking inside the window. You can only fix it by restarting the editor at this point.
### Steps to reproduce
Seems to happen inside an atlas with multiple images while trying to drag-select.
<hr/>

<table>
<tr><td>Build time</td><td>2019-03-07T16:45:05.812030</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7675d77c9a61f2632e11383712e874ada3f461bc</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"1fa726f4b0b44d09a1b76a8c07b272e6"'>1fa726f4b0b44d09a1b76a8c07b272e6</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 397.64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We merged a fix this morning, you should have an update available.

**Comment by erikangelin-king** [comment]
Our build servers are acting up but hopefully the fix should come out today.

**Comment by erikangelin-king** [comment]
Fix should be out by now!
