### ISSUE TITLE
Werid thing... while in sprites.atlas i click on the atlas and error occures... doesnt let me change selection by clicking on it and keeps popping this error message

### ISSUE THREAD

**Issue by WikGru** [defold/editor2-issues#2501]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-07T16:45:05.812030</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7675d77c9a61f2632e11383712e874ada3f461bc</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"658ea86229f5415096c286b74205b43c"'>658ea86229f5415096c286b74205b43c</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
See #2498

**Comment by erikangelin-king** [comment]
Should be fixed in latest update!
