### ISSUE TITLE
Assertion.Failed:(=(:pass render-args) pass/overlay) When adding animation image

### ISSUE THREAD

**Issue by altuntasfatih** [defold/editor2-issues#2502]
I have  been following this  tutorial https://devga.me/tutorials/defold-crash-course-tutorial/ 
When ı try to add  images on  player animation ,App  gives  an error then crash and quit unexpectedly.

this is error -> 
<img width="1440" alt="Screen Shot 2019-03-11 at 11 42 22 (2)" src="https://user-images.githubusercontent.com/13722649/54110638-fd294e00-43f2-11e9-9cab-ac1828edc40f.png">

Not:I have been using   "rendercam"  package 

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-07T16:44:24.926430</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7675d77c9a61f2632e11383712e874ada3f461bc</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"84ab242a0faf441888b2e3548ef876a1"'>84ab242a0faf441888b2e3548ef876a1</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 640</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
See #2498

**Comment by erikangelin-king** [comment]
Should be fixed in latest update!
