### ISSUE TITLE
There’s no symbol underscore ( _ )

### ISSUE THREAD

**Issue by notbadgun** [defold/editor2-issues#2505]
### Actual behaviour
**Without further ado:**
https://imgur.com/ht3twBZ

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-07T13:54:56.683329</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>8cc49aa84a2b825d42c729c9ae6b7ff8db46135b</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 419.35</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment]
#601
