### ISSUE TITLE
error while trying to build apk (SocketException Connection reset)

### ISSUE THREAD

**Issue by comGordon** [defold/editor2-issues#2508]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-13T16:46:50.202995</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>73e802da8319847efe48443d13c337c4fbe2e2d2</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"346a96ee19cd4cc7b7d8d2ffcccb442d"'>346a96ee19cd4cc7b7d8d2ffcccb442d</a></td></tr>
<tr><td>GPU</td><td>GeForce 940M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 417.35</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Looks like a network error while trying to resolve project dependencies.

**Comment by comGordon** [comment]
> Looks like a network error while trying to resolve project dependencies. You should get a nicer error message.

there is still something strange with fonts in the same update... problem solved by reinstalling the editor
