### ISSUE TITLE
Using box select in gui scene

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2511]
`java.lang.IndexOutOfBoundsException: [ fromIndex: 0, toIndex: 5, size: 3 ]`
<hr/>

<table>
<tr><td>Build time</td><td>2019-03-14T15:50:20.764403</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>55e5522267d42af09f3682825ff785c5050b8fa5</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"42aa3086fdaf4789ac64dabb21a778e6"'>42aa3086fdaf4789ac64dabb21a778e6</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-14T15:50:20.764403</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>55e5522267d42af09f3682825ff785c5050b8fa5</td></tr>
<tr><td>Defold engine sha</td><td>47c9f8e03623ca3ac511b5a55e6cfcc7e51ce340</td></tr>
<tr><td>Defold version</td><td>1.2.148</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"c0a813a23de745cba5dc87ce187d9c8b"'>c0a813a23de745cba5dc87ce187d9c8b</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Just merged a workaround, seems like the issue was introduced with the jdk/openjfx upgrade.
