### ISSUE TITLE
iOS bundle fail.

### ISSUE THREAD

**Issue by dasannikov** [defold/editor2-issues#2515]
![photo_2019-03-20_14-08-32](https://user-images.githubusercontent.com/1015770/54683188-af5ec500-4b19-11e9-8a1b-bc4b80c56643.jpg)

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-18T14:01:01.794546</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>34bb9603dfcb145c74fbb4f36f4146acea4c4252</td></tr>
<tr><td>Defold engine sha</td><td>34bb9603dfcb145c74fbb4f36f4146acea4c4252</td></tr>
<tr><td>Defold version</td><td>1.2.149</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"c77b88a45fec416eb9949487693c7a99"'>c77b88a45fec416eb9949487693c7a99</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by dasannikov** [comment]
I have removed all extensions and it still does not work.
Editor build is working. iOS Bundle show error.

**Comment by dasannikov** [comment]
![photo_2019-03-20_14-36-00](https://user-images.githubusercontent.com/1015770/54684635-817b7f80-4b1d-11e9-8f59-692d024feabc.jpg)

**Comment by dasannikov** [comment]
I have checked on 2 different computers (mac and win) and get the same problem with extensions.

**Comment by dasannikov** [comment]
And I can download links via browser.

**Comment by dasannikov** [comment]
![photo_2019-03-20_14-38-54](https://user-images.githubusercontent.com/1015770/54684769-e8009d80-4b1d-11e9-9d85-db174ce2e0b3.jpg)

**Comment by erikangelin-king** [comment]
Can you please download a newer version of the editor from the dashboard and try again?

**Comment by dasannikov** [comment]
Now it works. No idea what was it. Maybe some things from the provider side.
