### ISSUE TITLE
ClassCastException thrown when empty tilesource file is opened [DEFEDIT-1634]

### ISSUE THREAD

**Issue by warownia1** [defold/editor2-issues#2517]
An error occurs when opening a tilesource file which doesn't have the image field set.

### Expected behaviour
An empty tilesource file opens in the editor.

### Actual behaviour
An exception is thrown

    java.lang.ClassCastException: Unknown

### Steps to reproduce
- create new tilesource file
- open it in the editor

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-20T10:23:38.248345</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>044ab17b22ad90242d52b30ab8f33e52affef761</td></tr>
<tr><td>Defold engine sha</td><td>34bb9603dfcb145c74fbb4f36f4146acea4c4252</td></tr>
<tr><td>Defold version</td><td>1.2.149</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"694c3ddd6e694dff994d4b1d5e4365d7"'>694c3ddd6e694dff994d4b1d5e4365d7</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 240/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>3.3.0 NVIDIA 340.107</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.18.0-16-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Also https://sentry.io/organizations/defold/issues/?project=97739&query=id%3A%22de2bddf078904ffea62cf408453f846d%22&statsPeriod=14d
