### ISSUE TITLE
Build fails with PVRTexLib.dll: Can't find dependent libraries

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#2518]
### Expected behaviour
Not a crash

### Actual behaviour
This crash

### Steps to reproduce
Trying to build Interrogation on Windows on a fresh install of Defold on a relatively fresh install of Windows 10

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-20T10:23:53.866724</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>044ab17b22ad90242d52b30ab8f33e52affef761</td></tr>
<tr><td>Defold engine sha</td><td>34bb9603dfcb145c74fbb4f36f4146acea4c4252</td></tr>
<tr><td>Defold version</td><td>1.2.149</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"4a08db7439c74144861458cd101c8a3a"'>4a08db7439c74144861458cd101c8a3a</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 630</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 24.20.100.6346</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by dapetcu21** [comment]
Update: It worked after installing VC++ Redist 12 (Visual Studio 2013). This should be mentioned somewhere, or checked for and installed/warned about on first run.

**Comment by erikangelin-king** [comment]
Great that it works again, but we already install/unpack the dependencies of PVRTexLib.dll (MSVCR120.dll) when launching the editor, so I don't think installing the redist was what actually solved the problem. We've seen similar errors when running several instances simultaneously, was that the case here?

**Comment by dapetcu21** [comment]
Nope. Only one instance. Installing MSVCR is really what solved it. It's the only thing that changed between a working build and a non-working one. Maybe MSVCR120.dll is not the only dependency and the entire MSVCR package is required?

**Comment by erikangelin-king** [comment]
Hmm... Not according to dependency walker. Maybe if it loads libraries dynamically. We'll see if we can repro on a completely clean system.

**Comment by markusgustavssonking** [comment]
Found and fixed
