### ISSUE TITLE
[Web] Changing date in analytics view gives java error.

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2521]
![Screen Shot 2019-03-21 at 16 11 13](https://user-images.githubusercontent.com/5273682/54762405-5d3ea200-4bf4-11e9-91be-7d8dd2146499.png)

Using the date changer gives `unsafe:javascript:void(0)` both in Firefox and Safari. Firefox have `javascript.enabled true`

**Comment by AGulev** [comment]
Outdated. The dashboard was shutted down.
