### ISSUE TITLE
Opening resource which triggers an external application process causes the application to fault/become unresponsive.

### ISSUE THREAD

**Issue by bjconlan** [defold/editor2-issues#253]
Version: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1,
Linux Version running on Elementary OS (Ubuntu 16.04)

When opening a ttf from the Assets pane the application becomes unresponsive.

1. Using a default application template open the 'builtins', 'fonts' folders.
2. Select the 'vera_mo_bd.ttf' file listed at the bottom of the list by double clicking on it.
3. Verify that the application becomes unresponsive. (requires restart)

No console output seems to be appended when triggering this issue.

**Comment by bjconlan** [comment]
This seems to be a more general issue when viewing files from disk. closing this as I believe this has been covered by a previous issue.

**Comment by bjconlan** [comment]
I'm going to re-open this issue as I have a feeling this seems to be unique perhaps to Elementary OS.

I'm having the issue whenever I believe the the application is attempting to fork out a process. It has always happened after double clicking on a ttf font file but also happened when attempting to view a png file as well as when selecting the `Help > Documentation`, `Help > Report issue` or `help > Report praise`.

The process status becomes `Sl` which seems to be accurate from the state of the app being unresponsive and strace just shows `(wait, -1` (not there is no closing brace outputted by strace)

**Comment by erikangelin-king** [comment]
Duplicate/same underlying issue: https://github.com/defold/editor2-issues/issues/587
