### ISSUE TITLE
ArityError when trying to set resolution [DEFEDIT-1646]

### ISSUE THREAD

**Issue by fuso1914** [defold/editor2-issues#2537]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-01T16:25:41.204316</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>28c24a1290f26ccc416a38c7bd4d943b6737a6af</td></tr>
<tr><td>Defold engine sha</td><td>e79cdece4f5c8498302b3b00591808e3dc5a1827</td></tr>
<tr><td>Defold version</td><td>1.2.150</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"7fafe0051be14cb8aabb05892f62163a"'>7fafe0051be14cb8aabb05892f62163a</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1080/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 419.67</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged
