### ISSUE TITLE
Error when building: clojure.lang.ExceptionInfo: handler ':set-custom-resolution' in context ':global' failed at ':enabled?'

### ISSUE THREAD

**Issue by amel** [defold/editor2-issues#2538]
### Steps to reproduce
Build the project. So far I received this error once.

```
clojure.lang.ExceptionInfo: handler ':set-custom-resolution' in context ':global' failed at ':enabled?' with message 'Wrong number of args (1) passed to: editor.debug-view/suspended?'
clojure.lang.ArityException: Wrong number of args (1) passed to: editor.debug-view/suspended?
```
<hr/>

<table>
<tr><td>Build time</td><td>2019-04-01T16:24:32.159427</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>28c24a1290f26ccc416a38c7bd4d943b6737a6af</td></tr>
<tr><td>Defold engine sha</td><td>e79cdece4f5c8498302b3b00591808e3dc5a1827</td></tr>
<tr><td>Defold version</td><td>1.2.150</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6e500e82af774e348d0db3ceaf5a604a"'>6e500e82af774e348d0db3ceaf5a604a</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Graphics 6100</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged
