### ISSUE TITLE
Website. Dashboard. Not correct today stats. Zeros.

### ISSUE THREAD

**Issue by dasannikov** [defold/editor2-issues#2545]
I have not correct "today stats" on website->dashboard->analytics.
It always zeros. (but I have installs and players. I see it in other tabs)

<img width="1056" alt="Снимок экрана 2019-04-09 в 11 46 40" src="https://user-images.githubusercontent.com/1015770/55790901-a8dec000-5abd-11e9-93f3-26d42f8f459c.png">

**Comment by subsoap** [comment]
The analytics here are going to be discontinued pretty soon as far as I know. Switch to gameanlytics or google analytics.

**Comment by AGulev** [comment]
outdated
