### ISSUE TITLE
Tilemap x,y in editor wrong

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2546]
![2019-04-09 22_31_43-Window](https://user-images.githubusercontent.com/409170/55853764-50d4a780-5b17-11e9-9f65-534aca7bd729.png)

This tile should be labeled as 1,1 in the editor. 

https://www.defold.com/ref/tilemap/#tilemap.get_tile:url-layer-x-y

**Comment by subsoap** [comment]
Honestly it's really weird because the tile to the left and below is 0,0 but whatever that's the way it was made to work.

**Comment by andsveking** [comment]
You are totally right! 🤦‍♂️ Added issue: DEFEDIT-1656

**Comment by andsveking** [comment]
Just merged DEFEDIT-1656 into editor-dev, should be available in a few minutes!
