### ISSUE TITLE
Reorder tabs by dragging

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#255]
Would be nice to be able to re-order the tabs by dragging them.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by nwestberg** [comment]
+1

**Comment by K-Klear** [comment]
+1

**Comment by RussDragon** [comment]
+1

**Comment by vlaaad** [comment]
Fixed! Check for updates! :tada:
