### ISSUE TITLE
I want a "search in files" checkbox option that lets me just look for a file and not search inside of files

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2552]
For example I want to find all .particlefx files

Is there already a way to do this which skips mentions of collections/gui inclusions etc?

**Comment by matgis-king** [comment]
If you go to **File > Open Assets** and type `.particlefx`, it should list them all. Is that what you're after?

**Comment by subsoap** [comment]
@matgis-king That sounds like it!
