### ISSUE TITLE
Error message upon closing .script file [DEFEDIT-1666]

### ISSUE THREAD

**Issue by benjames-171** [defold/editor2-issues#2555]
### Expected behaviour
Close file without an error

### Actual behaviour
Following error was displayed upon closing a .script file:
**clojure.lang.ExceptionInfo: handler ':cut' in context ':code-view' failed at ':enabled?' with message 'No implementation of method: :produce-value of protocol: #'internal.graph.types/Evaluation found for class: nil'
java.lang.IllegalArgumentException: No implementation of method: :produce-value of protocol: #'internal.graph.types/Evaluation found for class: nil**

### Steps to reproduce
Unknown - sorry. Has happened twice in a few minutes. I used CTRL+W to close the file.

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-15T12:16:13.434396</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>05c50298d22411f41c9e89d6c47247607fb68743</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"442c5979db7c4a688a8fd880d46ea103"'>442c5979db7c4a688a8fd880d46ea103</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 25.20.100.6471</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
Note: Seems the view graph is deleted before the selected tab is changed. This means the view still has focus and is using a context with a deleted view-node id. We probably need to ensure the selected tab changes before deleting the graph.
