### ISSUE TITLE
Middle mouse click to close tab doesn't work on non-focused tabs

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#256]
This may be as designed, but it feels weird.

### Expected behaviour
Middle click on a tab will close it.

### Actual behaviour
Middle clicking on a tab does nothing, unless the tab is the active one.

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Jerakin** [comment]
This is one of the daily things I try to do and get sad every time it doesn't work.

**Comment by saracglaser** [comment]
DEFEDIT-1224

**Comment by ragnard-king** [comment]
Fixed, coming in next update.
