### ISSUE TITLE
Linebreaks inside code editor are not working

### ISSUE THREAD

**Issue by baciotti** [defold/editor2-issues#2563]
Repost from: https://forum.defold.com/t/linebreaks-inside-code-editor-does-not-work/49711

Hi guys, this is my first post here :slight_smile:

I am using Linux Mint Cinammon and Defold 1.2.151 and have an annoying bug that is compelling me to user an external editor. Let me explain:

When I try do edit some script code I can break line with “Enter” key. It is possible to paste code and also “paste break lines” but I can’t simply press enter to move to the next line.

I removed OpenJRE (default instalation on Mint/Ubuntu) and switched to Oracle Java 12 JRE but the error persists. I also tried to create a new blank project with a blank script and still can’t breaklines. I am using an external editor to edit code (xed) but I prefer to use the defold one.

So, is there any config file I can check to see it if is something misconfigured?

Thank you very much,

Regards,

Tiago

**Comment by Dzuvan** [comment]
I have the same issue. 
Linux Mint Cinnamon.

**Comment by matgis-king** [comment]
Sounds like you need to configure something. Ubuntu is the only officially supported Linux distro. I'm not sure if it can be made to work with others.

**Comment by Dzuvan** [comment]
Well, Linux Mint is based on Ubuntu, every other software I've used had 100% compatibility. 
The text editor worked fine until a couple of days ago.

**Comment by tyrokod9I** [comment]
I have the same problem. Linux mint 19

**Comment by matgis-king** [comment]
We've managed to reproduce the issue and are looking into it.

**Comment by matgis-king** [comment]
A fix was merged in defold/defold#3019.
