### ISSUE TITLE
Double clicking on the main.collection on the left pane when the main.collection is already open on the right tab pane causes error [DEFEDIT-1673]

### ISSUE THREAD

**Issue by dovo329** [defold/editor2-issues#2567]
### Expected behaviour
Double clicking on main.collection should open main.collection in right pane
### Actual behaviour
Get error
### Steps to reproduce
Going through the War Battles Tutorial

Double clicking on the main.collection on the left pane when the main.collection is already open on the right tab pane (I have left and right tabs open with README.md on the left pane and other stuff such as main.collection on the right pane causes this error.

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-17T18:27:32.896570</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>759189e7da3bb46f6a2655c10a2230e8ab48d4c4</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"7fe36d46259c4d5393d3f49120928e2c"'>7fe36d46259c4d5393d3f49120928e2c</a></td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.0.34</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14</td></tr>
<table>

**Comment by matgis-king** [comment]
Try as we might, we were unable to reproduce this. Are you able to make it happen by just setting up the scenario you describe in the report?

**Comment by dovo329** [comment]
![Screen Shot 2019-04-25 at 6 26 56 AM](https://user-images.githubusercontent.com/11469493/56735831-ce0d3880-6723-11e9-82a5-6fbc91410ef9.png)

I also was unable to reproduce this after quitting Defold, making a new War Tutorials project, trying it there, quitting Defold again and opening the original War Tutorials project and trying to do it again.  But I attached a screen shot of it happening.  Also here is the project attached.

[War battles tutorial.zip](https://github.com/defold/editor2-issues/files/3116852/War.battles.tutorial.zip)

**Comment by dovo329** [comment]
Aha! I know how to repro it now!

So with the brand new freshly downloaded War Battles Tutorial (without any user modifications) I was able to reproduce it with the following steps:

1) Double click on README.md
2) Double click on main/main.collection
3) Right click on README.md tab and do "Move to other tab pane"
4) Right click on README.md tab and do "Swap with other tab pane"
5) Double click on main.collection

Error should pop up

**Comment by matgis-king** [comment]
It does indeed! Thank you for providing detailed repro steps! ❤️
