### ISSUE TITLE
Pressing X (on Windows 10) does not close the Synchronize dialog (only pressing Cancel works)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2569]
![2019-04-26 12_00_01-Synchronize](https://user-images.githubusercontent.com/409170/56830298-d7c59780-681a-11e9-80c5-b3eb59441ce7.png)

**Comment by matgis-king** [comment]
This is actually kind of intentional. In some parts of the Sync process you can cancel or abort and revert to the pre-sync state. In these cases it is unclear what action the close button will take.

**Comment by subsoap** [comment]
The X button should not be there in this case, or it should be disable.

**Comment by matgis-king** [comment]
Unfortunately JavaFX does not currently provide a way to do this.

**Comment by subsoap** [comment]
Can't remove the close button since it's non-functional?

Not sure if this is relevant 

https://stackoverflow.com/questions/8341305/how-to-remove-javafx-stage-buttons-minimize-maximize-close

**Comment by matgis-king** [comment]
Yes, saw that. But the answer is misleading. `StageStyle.UNDECORATED` results in a window with no decorations at all - there's not even a title bar. We want a window with a title bar but without a close button, and there doesn't seem to be a way to do that.

**Comment by subsoap** [comment]
It looks like the only way to do it would be for it to technically be windowless, but for you to make your own title bar which you use to control window position. I can see why you don't want to do that right now, not a huge issue.
