### ISSUE TITLE
iOS Bundle dialog is confusing

### ISSUE THREAD

**Issue by Lerg** [defold/editor2-issues#2576]
iOS bundle dialog mentions 32-bit, 64-bit and Simulator "architectures", but simulator is a platform, so it looks like checking the simulator checkbox would convert the meaning of 32-bit and 64-bit options from armv7-iOS and arm64-iOS to x86-iOS and x86_64-iOS.

I suggest writing full architecture with platform name.

- 32-bit iOS
- 64-bit iOS
- 64-bit iOS Simulator

When 32 bit support is dropped, it can be renamed into just iOS and iOS Simulator.

**Comment by AGulev** [comment]
I think would be better to use simple names as it now (because ui should be for users) and architecture in brackets then
32bit (armv7)
64bit (arm64)
Simulator (x86_64)

**Comment by Lerg** [comment]
A simple hyphen or a comma might look better instead of parenthesis. But works too, removes the confusion.

**Comment by dapetcu21** [comment]
+1 to @AGulev's suggestion. Users that dealt with mobile platforms before are comfortable with architecture names such as armv7, while new users should still understand what is going on.

**Comment by dapetcu21** [comment]
Maybe "32bit ARM" instead of 32bit to make it more explicit? Personally, 32bit/64bit alone with no other qualifier make me think of x86 and x86_64.

**Comment by Lerg** [comment]
Personally I prefer plain armv7, arm64, x86_64, simple and conveys exactly what it is.

**Comment by andsveking** [comment]
Assigned DEFEDIT-1686.

**Comment by andsveking** [comment]
DEFEDIT-1686 has been merged and will be available in next ed2 update.
