### ISSUE TITLE
Ability to auto-zoom the curve editor to fit a curve in view

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#258]
Being able to quickly zoom the curve editor to the extents of a curve would make things a lot more convenient. Maybe by double clicking the curve title or as a toolbar button. Or maybe both.

As it is now you have to zoom and pan a lot when switching between working with an alpha curve (usually between 0..1) and a rotation curve (much higher values).

<hr/>
Defold version: 1.2.94
Defold sha: 04b0207f0e96f05203ed30a5bfc61917b1e1cde1
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Quick-win since it looks like the command (fram camera) is simply disabled in the curve view, it should work and has worked before.

**Comment by RagnarSvenssonKing** [comment]
Fixed previously.
