### ISSUE TITLE
Build errors should also show the line number where the error is indicated

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#261]
It would be a nice addition (as other IDEs have this feature) to show the line number where the error is found.  Currently, the errors in the Build errors tab only show the file where the error appears.
More so, when double clicking the error, the user should be directed to exact file and line where the error occurs.
![2016-12-06 11_20_12-defold editor 2 0 - my project](https://cloud.githubusercontent.com/assets/23701955/20919740/0046d224-bba6-11e6-996e-0a01d5f60573.png)

**Comment by ragnard-king** [comment]
Fixed.
