### ISSUE TITLE
Niggle: Double clicking a build error doesn't take you to the line in question [DEFEDIT-1687]

### ISSUE THREAD

**Issue by totebo** [defold/editor2-issues#2618]
<img width="488" alt="Screenshot 2019-05-25 at 11 00 10" src="https://user-images.githubusercontent.com/4493302/58367865-7574bb00-7edc-11e9-8598-f9c74f92542a.png">

In the example above, I would expect the cursor to jump to Line 743 on double click. Environment info below. Instead nothing happens when double clicking.

<img width="596" alt="Screenshot 2019-05-25 at 11 02 34" src="https://user-images.githubusercontent.com/4493302/58367876-9d641e80-7edc-11e9-8606-56fe5091992a.png">

<img width="698" alt="Screenshot 2019-05-25 at 11 03 58" src="https://user-images.githubusercontent.com/4493302/58367891-d1d7da80-7edc-11e9-8b73-25623dbf1fed.png">

**Comment by matgis-king** [comment]
This should be fixed if you update the editor.

**Comment by totebo** [comment]
Yes, works!
