### ISSUE TITLE
Atlas packing doesn't 'force' square in some cases

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2620]
Atlas doesn't pack optimal

![Screen Shot 2019-05-27 at 09 56 08](https://user-images.githubusercontent.com/5273682/58405403-a0d7e100-8067-11e9-89b8-72fe90c4f0ac.png)

TexturePacker get a 512x512 image. (Algorithm MaxRects and Heuristics AreaFit)
![Screen Shot 2019-05-27 at 10 11 26](https://user-images.githubusercontent.com/5273682/58405484-cf55bc00-8067-11e9-956e-170aa9da9c9a.png)

Repro
[atlas_size.zip](https://github.com/defold/editor2-issues/files/3222523/atlas_size.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2019-05-17T14:30:43.003830</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1a06f0197d99273a997ad723832703ccccf53886</td></tr>
<tr><td>Defold engine sha</td><td>2a329c6cc44abfec727e985898d428d6860f658a</td></tr>
<tr><td>Defold version</td><td>1.2.154</td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by subsoap** [comment]
1024*256=262144
512*512=262144

So they are the same, what matters is power of 2 in either direction. 1/1 or 2/1 or 1/2 doesn't make a difference  to graphics hardware afaik.

1/1 is still prettier. :)

**Comment by Jerakin** [comment]
Except for PVRTC that forces squared textures. If you use it this texture will take 4 times the size of memory than it needs to.

**Comment by subsoap** [comment]
@Jerakin is that still true with currently targetable devices?

**Comment by mathiaswking** [comment]
We already support rotating of the boxes, and we favor square textures.

Bin packing is a NP-hard solution, and there exists many algorithms/implementations.
There is no simple way to find the solution TextiurePacker found, other than replacing our current algorithm, and then there's no guarantee that another atlas grows bigger.

So, it's about replacing our current algorithm, rather than "fixing" it, and as such I think the priority becomes much less.

**Comment by mathiaswking** [comment]
That said... when I looked into it further, it seemed we didn't really sort the boxes properly.
So now we sort on area first...

<img width="1223" alt="Screenshot 2019-08-14 at 12 54 59" src="https://user-images.githubusercontent.com/14980582/63016046-e8b21b80-be92-11e9-88be-b775ad4dcf99.png">

I think this should be in 1.2.161

**Comment by mathiaswking** [comment]
Released in 1.2.160

**Comment by AGulev** [comment]
Solved in[ 1.2.161](https://forum.defold.com/t/defold-1-2-161-has-been-released/61861?u=agulev)
