### ISSUE TITLE
Assertion failed: n->m_Version == version, file ..\src\gui.cpp, line 178

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2625]
Appeared in console while afk

**Comment by mathiaswking** [comment]
That's unfortunate.
Do you have a `_crash` file you can share?

**Comment by subsoap** [comment]
[_crash.zip](https://github.com/defold/editor2-issues/files/3249447/_crash.zip)
Not sure if this one is related but it's the one in the folder.

**Comment by subsoap** [comment]
Just had this happen again

```
Assertion failed: n->m_Version == version, file ..\src\gui.cpp, line 178
```
This time I got the crash right after!

[_crash.zip](https://github.com/defold/editor2-issues/files/3487819/_crash.zip)

![2019-08-09 12_41_29-Window](https://user-images.githubusercontent.com/409170/62804755-0baf8a80-baa3-11e9-9cd2-98a8d2c853f0.png)

**Comment by subsoap** [comment]
It can somewhat consistently happen in our game, possibly related to  deleting nodes or pfx gui nodes.

**Comment by AGulev** [comment]
On what platform you have an error?

**Comment by subsoap** [comment]
Windows 10

**Comment by subsoap** [comment]
Several users are reporting this is happening for them in consistent ways (related to GUI node creation / destruction) we are forced to disable some cool stuff in our next update until this is fixed to avoid the crashes.

**Comment by JCash** [comment]
For windows, we also need the executable together with the crash.dmp file, in order to debug it properly.

**Comment by JCash** [comment]
Also, the editor version doesn't seem to correspond with the crash log (look at the beginnin of the file to see):
1.2.152 - 11b1e7662dd68172fca551c52cba248eea16a364

**Comment by subsoap** [comment]
I'll try to get it to crash again and get you the two files plus exe.

It was the newest _crash on my computer after I got the ```Assertion failed: n->m_Version == version, file ..\src\gui.cpp, line 178 ``` so I assumed it was the one. I sent you reproduction instructions on slack. I'll verify the steps now too to make sure they are working.

**Comment by subsoap** [comment]
Got it to crash the engine again but no _crash is produced in the filesystem at the time of crash, what do?

**Comment by subsoap** [comment]
We will try to make a small sample we can share where it happens consistently and share it tomorrow.

**Comment by subsoap** [comment]
Have yet to get it to happen in an isolated project but another error in the main project related to this did appear 

```
Assertion failed: i < Size(), file C:\buildbot\slave\builds\engine-win32-64-master\build\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 410
```
