### ISSUE TITLE
The Text sub menu of the Edit dropdown is active even if the current tab is not of text type.

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#264]
The user can notice that when the active tab is of a non text (script) type (for example: .gui, .collection and others) the Text menu entry in the Edit dropdown is still selectable, even if it does not have any sub menus. 
It should be grayed out.

![2016-12-07 10_42_39-defold editor 2 0 - magic link](https://cloud.githubusercontent.com/assets/23701955/20960841/fd5a924c-bc6a-11e6-8d1e-50fe08bb8171.png)

**Steps to reproduce:**

1. Open any project
2. From the assets navigator, open any .guy or .collection file by double click.
3. From the Menu bar, click Edit and then hover the text sub menu, notice that no sub menus appear, as it shouldn't apply to non script files.

Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Can't repro
