### ISSUE TITLE
Increase collision groups limit (currently max 16)

### ISSUE THREAD

**Issue by paweljarosz** [defold/editor2-issues#2647]
Currently there can't be more than 16 collision groups in use. As collisions are widely used I would like to have this limit increased. I know this isn't quick-win, but in the future, it would be nice to be able to handle more groups. So I'm leaving a suggestion here.

**Comment by mathiaswking** [comment]
This is a limitation of Box2D and nothing we will try to circumvent.

Also 16 groups is still a lot, could you describe your use case?
