### ISSUE TITLE
profiler.enable_ui() cause engine halt at release build

### ISSUE THREAD

**Issue by selimanac** [defold/editor2-issues#2648]
Engine halts when profiler.enable_ui(false) called at **release build** (Tested on MacOS, iOS, Windows)

```lua
function init(self)
    profiler.enable_ui(false)
    -- halts here. msg.post never reached.
    msg.post("@render:", "clear_color", {color = vmath.vector4(255 / 255, 0 / 255, 0 / 255, 0)})
end
```

**Comment by AGulev** [comment]
There is no profiler module in release mode. 
That means you try to call (nil).enable_ui(false) and get a Lua error there.
It is expected behavior.

**Comment by selimanac** [comment]
> That means you try to call (nil).enable_ui(false) and get a Lua error there.
> It is expected behavior.

Hi @AGulev 

It isn't throw error, actually it should. This is why I opened this issue: It completely blocks the thread, no error no warning, none, game just stops(only on release bundle). 

Is this a expected behavior? If so OK, but not for me. Anyone can forget to remove this simple function from his code and they can pull their hair to find what cause a engine halt on release build.

Example is attached. Simply **bundle** it for target platform and run.

[profiler.zip](https://github.com/defold/editor2-issues/files/4829532/profiler.zip)

**Comment by AGulev** [comment]
I'll take a look today evening.

**Comment by AGulev** [comment]
I'm not sure what can we do here. We already have info in[ Profiling manual](https://defold.com/manuals/profiling/) that this module is available only in Debug:

>Defold includes a set of profiling tools that are integrated with the engine and the build pipeline. These are designed to help find problems with performance and memory usage. The built-in profilers are available on debug builds only.

That's why I closed this issue and told you this is expected behavior.

**Comment by selimanac** [comment]
> If you write any Lua code with error in the first line of the function result will be the same (even in debug mode), for example:

I definitely doesn't aware of that. I thought it is only related to profiler. I get it now, thank you.
This not really important for me, I was thinking the newcomers.
