### ISSUE TITLE
No setting to enable ESC key to exit running game

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#266]
In editor 1 there was a setting to enable the escape key to exit the game when running it. It was really nice to be able to enable that for builds you do directly in the editor.

<hr/>
Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by linusc-king** [comment]
Also consider ctrl+w, ctrl+q or ctrl+x.
