### ISSUE TITLE
I know this is a dupe but it's constantly happening and really annoying

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2665]
It doesn't seem to break the editor it just pops up the error. So maybe detect this specific error and make it silent if it can't be solved directly?

<hr/>

<table>
<tr><td>Build time</td><td>2019-06-25T16:22:53.457850</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39e92de4e2d97ab951ae10cfba7302bbaeec0d2f</td></tr>
<tr><td>Defold engine sha</td><td>d7042d5368c338ed5d66b6dff9c60a20924385ac</td></tr>
<tr><td>Defold version</td><td>1.2.157</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"02711cae357741f6b508c85ab7fcac76"'>02711cae357741f6b508c85ab7fcac76</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.39</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by markusgustavssonking** [comment]
I am sorry you are having this error. The reason it has not been fixed yet is because the actual error is in a dependency and there are factors outside of the code itself that is slowing progress down.
