### ISSUE TITLE
Files are changed when opening a project

### ISSUE THREAD

**Issue by linusc-king** [defold/editor2-issues#267]
### Expected behaviour
No files in the repo are changed when a project is opened. 
I would expect a file to be saved only upon actively saving it.
If that is not possible, I would then like to be informed of any required changes that needs to take place in the project in order to be fully 'up to date' to the current version of the editor either upon editor startup or whenever the editor requires files to be changed.

### Actual behaviour
A lot of files (if not all) are changed upon opening a project including lua- and script-files.

<hr/>
Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
This is common to happen the first time you open a project. If you edit a file. Hit save. And then check sourcetree or similar you will find it has done some minor whitespace changes and maybe some formatting of old files that had the inline format from a editor 1 resource rename.

**Comment by linusc-king** [comment]
I tried saving all (since I can't use ctrl+s because of https://github.com/defold/editor2-issues/issues/151) and no files was saved. The repo is unchanged although I have hundreds of changes in the editor.

**Comment by linusc-king** [comment]
Upon recommendation, I changed a file and saved all. After that I could see the changes in the branch as well. I would expect some kind of message explaining what happened though.

**Comment by Malmer** [comment]
It would make sense if just doing "Save All" without editing an other file would write the changed files to disk.

**Comment by linusc-king** [comment]
It would make sense that the changes are shown when opening a file in the first place.

**Comment by linusc-king** [comment]
This report seems to be a feature request now.

**Comment by linusc-king** [comment]
See https://github.com/defold/editor2-issues/issues/277.
Closing this report.
