### ISSUE TITLE
FileDialog doesn't work

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#2688]
FileDialog doesn't work in macOS 10.15 beta (when you try to bundle a project, for example)
This is JavaFX issue in macOS 10.15 beta 
https://bugs.openjdk.java.net/browse/JDK-8227836

The workaround is using the `bob.jar` on macos 10.15 beta

**Comment by vlaaad** [comment]
Note: this is not a JavaFX issue, this is Java issue.

**Comment by AGulev** [comment]
Yes, you are right!

**Comment by AGulev** [comment]
Solved with the latest version of Catalina
