### ISSUE TITLE
Macos: Occasionaly when clicking the Help menu the items disappear and only the search field remains

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#270]
It acts as if I wrote something in the search field, when in fact I didn't. 
Sometimes it takes half a second or so before the items disappear.

<hr/>
Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
I have verified this, but since the menu can be re-opened with the items we will post-pone fixing this. If anyone finds a stable repro-case we could look into fixing it sooner.

**Comment by RagnarSvenssonKing** [comment]
It's possible that this is related to https://github.com/defold/editor2-issues/issues/269

**Comment by RagnarSvenssonKing** [comment]
Fixed previously.
