### ISSUE TITLE
Add confirm dialog to "rebuild" in editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2738]
Since rebuilding is more rarely needed than building, and can be annoying when accidentally selected on large projects, a confirm dialog for it would be useful

**Comment by matgis-king** [comment]
We feel the likelihood and consequences of triggering a rebuild by mistake are relatively mild. We'd rather not add confirmation dialogs that might impede or annoy users unless there is a risk of losing work.

**Comment by subsoap** [comment]
For small projects it's not problem, for big projects it's annoying. It happens more often than you think especially as currently when you click down on a UI drop down elements your cursor is stuck there when you release even if you are hovering another button. I'm sure as more people use Defold in the future they will +1 this.

**Comment by subsoap** [comment]
https://gfycat.com/sentimentalwastefulherring

Here's video of the problem, if I accidentally click down on "rebuild" I must press esc, moving cursor away isn't enough.

**Comment by subsoap** [comment]
How it should be is in drop downs like this selection should not be locked when clicking down, the release state should determine what if any selections are activated - this is how it is done in most software.

**Comment by matgis-king** [comment]
I've created a new issue for the behavior you describe. I do think that fixing that behavior is the proper solution to this problem.

**Comment by subsoap** [comment]
Still rebuild often by mistake, with normal work I rarely have a legitimate reason to rebuild. Still sucks every single time since the projects are so huge. Please add a dialog to rebuild, and add an option to enable the dialog in the options if you don't want it to be there for everyone.
