### ISSUE TITLE
Resource properties bug in 1.2.163

### ISSUE THREAD

**Issue by mosmetro** [defold/editor2-issues#2756]
[resource_prop_bug.zip](https://github.com/defold/editor2-issues/files/3654145/resource_prop_bug.zip)

https://forum.defold.com/t/resource-properties-in-1-2-163/63292/19
See latest posts.
<hr/>

<table>
<tr><td>Build time</td><td>2019-09-18T10:26:19.361143</td></tr>
<tr><td>Defold channel</td><td>alpha</td></tr>
<tr><td>Defold editor sha</td><td>1eb61acc7a8ca622bedb5bf862ddbf44bfb95727</td></tr>
<tr><td>Defold engine sha</td><td>1eb61acc7a8ca622bedb5bf862ddbf44bfb95727</td></tr>
<tr><td>Defold version</td><td>1.2.163</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"1a8072bb3a3248b1ab40594a12110b30"'>1a8072bb3a3248b1ab40594a12110b30</a></td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.10.12</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.6</td></tr>
<table>

**Comment by AGulev** [comment]
Thank you!

**Comment by matgis-king** [comment]
We found the issue and have committed a fix that will make it into the release. Thanks for reporting!
