### ISSUE TITLE
Tilemap editor lost tile cursor

### ISSUE THREAD

**Issue by mosmetro** [defold/editor2-issues#2762]
It still present in tile palette but no more seen in tilemap editor.

<hr/>

<table>
<tr><td>Build time</td><td>2019-09-24T14:18:18.918026</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7c1a314b318aa7ea6de887b6a314c03c7b161464</td></tr>
<tr><td>Defold engine sha</td><td>e07f3bb9e8c970eceda8dce8efd5905fd67fa720</td></tr>
<tr><td>Defold version</td><td>1.2.162</td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.10.12</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.6</td></tr>
<table>

**Comment by mosmetro** [comment]
Repro:
[test.tilemap.zip](https://github.com/defold/editor2-issues/files/3668004/test.tilemap.zip)
Cursor will be back when you clear layer1 from tiles.

**Comment by matgis-king** [comment]
Note: Probably some `:visibility-aabb` needs to be expanded.
