### ISSUE TITLE
bmfonts no longer rendering in the editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2765]
https://github.com/subsoap/defold-bmfont-example

**Comment by subsoap** [comment]
![2019-09-29 15_44_14-New folder (15)](https://user-images.githubusercontent.com/409170/65840629-1da5f080-e2d0-11e9-982e-ee20d5b8dade.png)

**Comment by matgis-king** [comment]
A fix for this is coming in the 1.2.163 release.
