### ISSUE TITLE
Files appear to have changes

### ISSUE THREAD

**Issue by linusc-king** [defold/editor2-issues#277]
### Expected behaviour
No files are changed in the Editor or on disk, when a project has been opened. 

### Actual behaviour
A lot of files are shown in the "changed files" area in the editor but none of the files have changes on disk. 

<hr/>
Defold version: 1.2.95
Defold sha: 7ca47a7f7aa0e4809e31ab2274fd1693a1fc5a7e
Platform: Windows 7 6.1 (x86)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment]
@linusc-king Hi Linus! Are you able to re-test this with a recent version? We've made some changes/fixes in this area.

**Comment by linusc-king** [comment]
Tested and works as expected above, i.e no files are changed solely upon opening a project.

**Comment by ragnard-king** [comment]
Lovely, thanks for re-testing. Closing this then.
