### ISSUE TITLE
Native extensions cause white flash on window open

### ISSUE THREAD

**Issue by tadaaagames** [defold/editor2-issues#2779]
It seems that with native extensions (tested with defos and directories), when the game opens, there is a white flash that lasts 4-5 frames.

This does not happen with vanilla Defold.

**Comment by subsoap** [comment]
Was this closed because it was fixed? Current engine version still flashes white with NEs

![2019-11-27 18_26_36-Window](https://user-images.githubusercontent.com/409170/69771963-7b757e00-1143-11ea-9293-e91d32dd1a1c.png)
