### ISSUE TITLE
Incorrect location table in a editor script throws error

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2792]
<hr/>

<table>
<tr><td>Build time</td><td>2019-10-14T10:46:12.025242</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6827c2e9f14627b36117de82fbf299c525217329</td></tr>
<tr><td>Defold engine sha</td><td>13261949f45c333806c8aac8bd5b08124ca2810f</td></tr>
<tr><td>Defold version</td><td>1.2.163</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"d9c2f57cd8d547baa6be269e198aa06b"'>d9c2f57cd8d547baa6be269e198aa06b</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment]
Should be fixed, check for updates!
