### ISSUE TITLE
Error when trying to fetch an extension with faulty game.project

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2794]
The include folder was misspelled

<hr/>

<table>
<tr><td>Build time</td><td>2019-10-15T14:39:26.206389</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>ba2e1269b9d77c8eb4e193b33e6060563ad2b1df</td></tr>
<tr><td>Defold engine sha</td><td>13261949f45c333806c8aac8bd5b08124ca2810f</td></tr>
<tr><td>Defold version</td><td>1.2.163</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"39deedf8b88e427e92518c7ee459f46d"'>39deedf8b88e427e92518c7ee459f46d</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment]
Should be fixed, check for updates!
