### ISSUE TITLE
Highlight member at cursor in the text editor

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#280]
Highlight the current selected member in the file.

![screen shot 2016-12-08 at 11 15 15](https://cloud.githubusercontent.com/assets/3929293/21006195/18e408b8-bd38-11e6-990d-a5904aec8ea1.png)

Attached example from LDT
<hr/>
Defold version: 1.2.95
Defold sha: 3d3b4872c5dc544f1cc7d454b826f7193842d4f2
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
New code editor highlights all occurrences of selected word.
