### ISSUE TITLE
List inside variables debug panel is not orders

### ISSUE THREAD

**Issue by dev-masih** [defold/editor2-issues#2804]
like my previous issue report about variables not have any order in debug variables panel (https://github.com/defold/editor2-issues/issues/2797) this time oddly a list inside variables show shuffled indexes that makes tracking a list very difficult.

![debugger](https://user-images.githubusercontent.com/8469800/67222492-4dad6300-f43a-11e9-935b-67ee43e5eb01.jpg)

the code is a simple for loop inserting values into a table

```
local my_list = {}
for i = 1, 20 do
    table.insert(my_list, { id = i })
end
```

pprint show it correctly

![pprint](https://user-images.githubusercontent.com/8469800/67222536-6158c980-f43a-11e9-81ad-50dffd1001fd.jpg)

**Comment by mathiaswking** [comment]
A fix was merged, and it should be working now.
If not, feel free to reopen this issue.

**Comment by dev-masih** [comment]
@mathiaswking thanks, I'll test it as soon as it released on editor-alpha channel
