### ISSUE TITLE
http.request with PATCH method is not posting data

### ISSUE THREAD

**Issue by selimanac** [defold/editor2-issues#2812]
POST, PUT are working but PATCH method is not posting data. 
You can test and see the results [here](https://webhook.site/#!/d9a13364-3e37-464e-9ac5-1e149d46d74d/69564007-edc3-4303-a732-6fb168bb9c4c/1): 

```lua
local post_data = '{"name":"Test"}'
http.request("https://webhook.site/d9a13364-3e37-464e-9ac5-1e149d46d74d", "PATCH", callback, nil, post_data)
```

**Comment by mathiaswking** [comment]
I added so that the `PATCH` verb is also taking the same code path as `POST` and `PUT`.
Should be in 1.2.1.64

**Comment by selimanac** [comment]
Thank you.
