### ISSUE TITLE
ParticleFX tooltips are way too persistent

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2814]
https://gfycat.com/variablewiltedgosling

They persist even if another app has focus / break mouse wheel scrolling in some cases

**Comment by subsoap** [comment]
Tooltip also blocks click input!

**Comment by selimanac** [comment]
This happening everywhere, not only on Particle FX panel.

**Comment by subsoap** [comment]
@selimanac you're right, and it has become even more extremely annoying when working with GUI

**Comment by subsoap** [comment]
![input_block](https://user-images.githubusercontent.com/409170/68817141-96b99700-0635-11ea-972c-5e3962e26b91.png)

Example of blocking input, I can't click into the box if I click here, and the tooltip persists even if I click on it.

Tooltips should fade out on their own while not hovering on their elements, and they could be a click through element, they should never capture input themselves.

**Comment by britzl** [comment]
@vlaaad will look into this soon. Sorry about this.

**Comment by AGulev** [comment]
[Solved in 1.2.166](https://forum.defold.com/t/defold-1-2-166-has-been-released/64558)
