### ISSUE TITLE
Crash after editing file in external editor

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#282]
I got a crash after changing a file in another editor and then going back to defold.

{:cause "Concurrent modification of graph",
 :via
 [{:type clojure.lang.ExceptionInfo,
   :message "Concurrent modification of graph",
   :at [clojure.core$ex_info invokeStatic "core.clj" 4617],
   :data {:_gid 0, :start-tx 143, :sidereal-tx 144}}],
 :trace
 [[clojure.core$ex_info invokeStatic "core.clj" 4617]
  [dynamo.graph$merge_graphs invokeStatic "graph.clj" 98]
  [dynamo.graph$transact$fn__5682 invoke "graph.clj" 147]
  [clojure.lang.AFn call "AFn.java" 18]
  [clojure.lang.LockingTransaction run "LockingTransaction.java" 273]
  [clojure.lang.LockingTransaction runInTransaction "LockingTransaction.java" 229]
  [dynamo.graph$transact invokeStatic "graph.clj" 146]
  [editor.app_view$on_selected_tab_changed invokeStatic "app_view.clj" 96]
  [editor.app_view$make_app_view$reify__23675 changed "app_view.clj" 530]
  [com.sun.javafx.binding.ExpressionHelper$Generic fireValueChangedEvent "ExpressionHelper.java" 361]
  [com.sun.javafx.binding.ExpressionHelper fireValueChangedEvent "ExpressionHelper.java" 81]
  [javafx.beans.property.ReadOnlyObjectPropertyBase fireValueChangedEvent "ReadOnlyObjectPropertyBase.java" 74]
  [javafx.beans.property.ReadOnlyObjectWrapper fireValueChangedEvent "ReadOnlyObjectWrapper.java" 102]
  [javafx.beans.property.ObjectPropertyBase markInvalid "ObjectPropertyBase.java" 112]
  [javafx.beans.property.ObjectPropertyBase set "ObjectPropertyBase.java" 146]
  [javafx.scene.control.SelectionModel setSelectedItem "SelectionModel.java" 102]
  [javafx.scene.control.TabPane$TabPaneSelectionModel select "TabPane.java" 717]
  [javafx.scene.control.TabPane$TabPaneSelectionModel select "TabPane.java" 735]
  [javafx.scene.control.TabPane$TabPaneSelectionModel select "TabPane.java" 656]
  [com.sun.javafx.scene.control.behavior.TabPaneBehavior selectTab "TabPaneBehavior.java" 122]
  [com.sun.javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5 handle "TabPaneSkin.java" 1332]
  [com.sun.javafx.scene.control.skin.TabPaneSkin$TabHeaderSkin$5 handle "TabPaneSkin.java" 1317]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 86]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.CompositeEventDispatcher dispatchBubblingEvent "CompositeEventDispatcher.java" 59]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.Scene$MouseHandler process "Scene.java" 3757]
  [javafx.scene.Scene$MouseHandler access$1500 "Scene.java" 3485]
  [javafx.scene.Scene impl_processMouseEvent "Scene.java" 1762]
  [javafx.scene.Scene$ScenePeerListener mouseEvent "Scene.java" 2494]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 380]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 294]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler lambda$handleMouseEvent$354 "GlassViewEventHandler.java" 416]
  [com.sun.javafx.tk.quantum.QuantumToolkit runWithoutRenderLock "QuantumToolkit.java" 389]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler handleMouseEvent "GlassViewEventHandler.java" 415]
  [com.sun.glass.ui.View handleMouseEvent "View.java" 555]
  [com.sun.glass.ui.View notifyMouse "View.java" 937]],
 :data {:_gid 0, :start-tx 143, :sidereal-tx 144}}

<hr/>
Defold version: 1.2.95
Defold sha: 3d3b4872c5dc544f1cc7d454b826f7193842d4f2
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Will be fixed as part of DEFEDIT-614

**Comment by ragnard-king** [comment]
@SamuelBeijer were you able to consistently reproduce this or did it only happen sporadically?

@RagnarSvenssonKing Can't repro this after defold/defold#1158 but also can't say for certain that it is fixed. We're still doing a transaction in `on-selected-tab-changed`, however we're calling it in one less handler than before.

**Comment by SamuelBeijer** [comment]
No it was not consistently reproduced

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-663

**Comment by ragnard-king** [comment]
Should be fixed by https://github.com/defold/defold/pull/1174
