### ISSUE TITLE
Build error on ubuntu

### ISSUE THREAD

**Issue by AnvarNazar** [defold/editor2-issues#2831]
### Expected behaviour
build and run the game
### Actual behaviour
An error occurred
```
java.util.concurrent.ExecutionException: java.lang.AssertionError: Assert failed: (not (g/error? bytecode))
java.lang.AssertionError: Assert failed: (not (g/error? bytecode))
```
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-10-24T16:19:34.173423</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>be024b63994ffb88d462db9275b6d9f9e553c5d6</td></tr>
<tr><td>Defold engine sha</td><td>13261949f45c333806c8aac8bd5b08124ca2810f</td></tr>
<tr><td>Defold version</td><td>1.2.163</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c3dfd09968644983bd767c98ffda1bbc"'>c3dfd09968644983bd767c98ffda1bbc</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) HD Graphics 620 (Kaby Lake GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 19.0.8</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.0.0-32-generic</td></tr>
<table>

**Comment by britzl** [comment]
Does this happen with any game/project or just one?

**Comment by AnvarNazar** [comment]
It happening with a single project but was fine before. I created a new project but no problems there.

**Comment by britzl** [comment]
Ok. Is there something special about the project? Is it very big? Which dependencies do you have? Try to pinpoint, perhaps by removing one thing at a time until it works.

**Comment by d954mas** [comment]
same https://github.com/defold/editor2-issues/issues/2887
