### ISSUE TITLE
Getting java.lang.NullPointerException: Unknown when pressing "Sign in with Google"

### ISSUE THREAD

**Issue by OldManCharles** [defold/editor2-issues#2833]
### Expected behaviour
Sign in with my google account when pressing the "Sign in with Google" button in the "IMPORT PROJECT" window
### Actual behaviour
I receive a prompt with the aforementioned error and I'm totally unable to sign in with my Google account
### Steps to reproduce
Start Defold, go to import project, and click sign in with google
<hr/>

<table>
<tr><td>Build time</td><td>2019-10-07T10:10:38.592737</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>13261949f45c333806c8aac8bd5b08124ca2810f</td></tr>
<tr><td>Defold engine sha</td><td>13261949f45c333806c8aac8bd5b08124ca2810f</td></tr>
<tr><td>Defold version</td><td>1.2.163</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.8-300.fc31.x86_64, LLVM 9.0.0)</td></tr>
<tr><td>GPU Driver</td><td>4.5 (Compatibility Profile) Mesa 19.2.2</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>5.3.8-300.fc31.x86_64</td></tr>
<table>

**Comment by dev-masih** [comment]
Signing in with Google is deprecated. please make sure you use the latest version of defold.

**Comment by britzl** [comment]
You are using an old version of Defold. The project dashboard has been deprecated:

https://forum.defold.com/t/announcing-dashboard-and-analytics-shutdown/60970
