### ISSUE TITLE
msg.post does not work, when message = nil

### ISSUE THREAD

**Issue by sergeysinyavsky** [defold/editor2-issues#2835]
When using **msg.post(receiver, message_id, nil)**
### Expected behaviour
    Message received with empty table
### Actual behaviour
    Message not received. Also, the function that called msg.post terminates its execution.
    No error messages.
<hr/>

<table>
<tr><td>Build time</td><td>2019-10-24T16:20:33.656990</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>be024b63994ffb88d462db9275b6d9f9e553c5d6</td></tr>
<tr><td>Defold engine sha</td><td>13261949f45c333806c8aac8bd5b08124ca2810f</td></tr>
<tr><td>Defold version</td><td>1.2.163</td></tr>
<tr><td>GPU</td><td>Radeon RX 580 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13571 Compatibility Profile Context 19.9.2 26.20.13003.1007</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by sergeysinyavsky** [comment]
There was no error message because the function was called through **pcall()**.
An error appears that the 3rd argument is nil.

**Comment by britzl** [comment]
Created internal ticket https://github.com/defold/defold/issues/4566
