### ISSUE TITLE
Setting Initial Angular Velocoty in ParticleFX result in error

### ISSUE THREAD

**Issue by Sandstedt** [defold/editor2-issues#2843]
### Expected behaviour
Being able to set the initial angular velocity

### Actual behaviour
Get an "An error accurred" modal with `java.lang.NullPointerException: Unknown`

### Steps to reproduce
Create a particle emitter. Try to write a number in Initial Angular Veclocity. Press tab.

<hr/>

<table>
<tr><td>Build time</td><td>2019-10-24T16:17:54.561331</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>be024b63994ffb88d462db9275b6d9f9e553c5d6</td></tr>
<tr><td>Defold engine sha</td><td>13261949f45c333806c8aac8bd5b08124ca2810f</td></tr>
<tr><td>Defold version</td><td>1.2.163</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"eaacffeb3b5b4688b87572c63e3732bc"'>eaacffeb3b5b4688b87572c63e3732bc</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon R9 M295X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.11.21</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.6</td></tr>
<table>

**Comment by britzl** [comment]
And this happens every time?

**Comment by Sandstedt** [comment]
@britzl "Unfortunately" not. Tried it on my home computer with a fresh version of Defold and an new project. And worked fine. Will try again on my work computer tomorrow to see if it's related to the project or with the hardware.

**Comment by britzl** [comment]
Thank you. Please update with additional information.

**Comment by Sandstedt** [comment]
Hmm, wierd. Now when I try the exact same project, with the same computer on the same particle, it works.

I will file a new bug report if it happens again and make a reference to this one.

**Comment by totebo** [comment]
I have just experienced the same thing. Defold v1.2.174.

In a fresh project it doesn't happen, but in a game it does:
https://youtu.be/KEkmN-cjoLE

Will report back if I find out more.
