### ISSUE TITLE
Shortcut key didn't work on Colemak Layout / MacOS

### ISSUE THREAD

**Issue by thetrung** [defold/editor2-issues#2844]
Any shortcut key won't work on any other layout but the default ABC.
Ex: 
Shortcut to "Save All" is Cmd + S
On Colemak it's Cmd + R ( as R is S from old ABC )

But anyway, I think current shortcut keymap was binded to QWERTY keycode, hope they will make a custom keymapping soon to avoid this awkward situation.

Cheers !

**Comment by britzl** [comment]
Duplicate of #1236
