### ISSUE TITLE
Close button on tab hover

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#285]
When hovering tabs it should show the close [x] button so that one can close it instantly without opening the tab.

<hr/>
Defold version: 1.2.95
Defold sha: dc237f3ae4504aa7b8fcca4bcddf18ebcd4d2e8b
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by AGulev** [comment]
@erikangelin-king  @Malmer Looks like already fixed, can you recheck?

**Comment by erikangelin-king** [comment]
X is always there :)
