### ISSUE TITLE
Debug Build Crashes

### ISSUE THREAD

**Issue by jakeparkernet** [defold/editor2-issues#2853]
### Expected behaviour
Debug build succeeds.
### Actual behaviour
Crashes with Java Timeout error
### Steps to reproduce
Build. Read from a json file in custom resources. Add a print statement within a loop that loops through the values decoded from the json
<hr/>

<table>
<tr><td>Build time</td><td>2019-11-25T14:17:53.774643</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7ef6b801d3b094d0403699ae69dc76f3597ccb6f</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2d9573200e654370ba74c84ade87a6cc"'>2d9573200e654370ba74c84ade87a6cc</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.64</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Are you able to share the snippet of code that reads the json plus the json file itself so that we can try and reproduce it?

**Comment by JCash** [comment]
Or, even better, if you can provide a small repro case we can use, it would be great.

**Comment by jakeparkernet** [comment]
Hi, sorry I thought more information was automatically being shared from my project. I will close this and next time be more diligent.

**Comment by britzl** [comment]
No we don't get access to any source code or anything like that. We get information about what part of the editor code that crashed, but to reproduce and solve we sometimes need additional help.
