### ISSUE TITLE
Can't attach debugger to Android device

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#2854]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-11-29T13:37:43.182609</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39b2b2d4bd91ffd166a5776bd998912a0ec9758c</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"ee650c1dadf54975be2a005f4d77a9fe"'>ee650c1dadf54975be2a005f4d77a9fe</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by britzl** [comment]
Does this happen all the time and with all devices?

**Comment by AGulev** [comment]
I checked only on one device. I'll try to recheck it on one more device then.
