### ISSUE TITLE
Find window should have more features like editor 1 [feature]

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#287]
The find in text window should have more option and start with the current marked word like in editor 1. It feels weird to not being able to press enter to continue searching/replacing

This is the options in editor 1.
![screen shot 2016-12-08 at 12 34 02](https://cloud.githubusercontent.com/assets/3929293/21008634/d530d910-bd42-11e6-9843-ecabb8ac7b6d.png)

<hr/>
Defold version: 1.2.95
Defold sha: dc237f3ae4504aa7b8fcca4bcddf18ebcd4d2e8b
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Obsolete
