### ISSUE TITLE
Pressing Esc to close search pane or autocomplete box forces to exit from full-screen mode on macOS

### ISSUE THREAD

**Issue by astrochili** [defold/editor2-issues#2872]
I know that many people use the full-screen mode on macOS because it's saves screen space and hides unnecessary details like a dock or a menu bar. But there is one annoying bug. When I try to close search pane or autocomplete box by pressing Esc the Defold Editor switches to the window mode.

I don't know any other ways to close these panes so I need switch back to the full-screen mode every time:
-> _press Esc to close the pane_ 
-> _watch a transition to the window mode_
-> _move mouse cursor to green circle button and click on it_
-> _watch a transition to the fullscreen mode_.

**Tech information**
- MacOS 10.14.6
- Editor 1.2.164 (39b2b2d4bd91ffd166a5776bd998912a0ec9758c)

**Steps to reproduce**
- Open a Defold project and go to the full-screen mode
- Close a Defold project by Cmd+Q in the full-screen mode
- Open a Defold project, it will be opened in the full-screen mode with system label "Press ESC to exit full-screen mode".
![Screenshot 2020-06-07 at 00 00 47](https://user-images.githubusercontent.com/4752473/83954543-cee32a00-a852-11ea-958a-253add7a1d1b.png)
- Open any script and press Cmd+F or start to typing anything with an autocomplete box
- Press Esc

**Expected behaviour**
- A search bar or an autocomplete box is closed, the full-screen mode has not changed.

**Actual behaviour**
- A search bar or an autocomplete box is closed, the full-screen mode has changed to the window mode.

**Comment by astrochili** [comment]
Updated steps to reproduce. Need to open project with restoring the full-screen mode. Looks like macOS interprets it as system media full-screen mode that can be closed by pressing an Escape key.

**Comment by astrochili** [comment]
I think [this](https://stackoverflow.com/questions/26114018/fullscreen-transition-in-javafx) and [this](https://www.programcreek.com/java-api-examples/?class=javafx.stage.Stage&method=setFullScreenExitHint) can be useful to resolve the bug:

```
setFullScreenExitHint("");
setFullScreenExitKeyCombination(null);
```

I tried to find something like that in sources but without success.

**Comment by astrochili** [comment]
It seems that I know how to solve the bug.

![Screenshot 2020-06-07 at 00 53 01](https://user-images.githubusercontent.com/4752473/83955288-fb4e7480-a859-11ea-845f-c3f33c9b30b5.png)

Add two lines after `(.setFullScreen stage true)`
```
(.setFullScreenExitHint stage "")
(.setFullScreenExitKeyCombination stage nil)
```

**Comment by madwareru** [comment]
I tested it and sat to admit it but it only hides fullscreen exit hint, ESC still forces window to exit fullscreen.

But we can instead add just one line:
```clojure
(.setFullScreenExitKeyCombination stage KeyCombination/NO_MATCH)
```
And it does int job perfectly

**Comment by madwareru** [comment]
Wow) sorry for this mess, I needed a couple of tries to do PR in a right way.
There is a PR: https://github.com/defold/defold/pull/4888

**Comment by matgis-king** [comment]
Reopening this since the fix is not yet merged.

**Comment by astrochili** [comment]
@matgis-king it looks like was merged 5 days ago -> https://github.com/defold/defold/pull/4888

**Comment by matgis-king** [comment]
Ah, yes! Seems I forgot to close it after merging. Thanks for sorting it out!
