### ISSUE TITLE
Text node does not show euro symbol and hides whole line

### ISSUE THREAD

**Issue by amel** [defold/editor2-issues#2877]
When you use the euro symbol (€) in a text node, the line with the symbol is hidden. When you build the project, the text line does show, but the euro symbol gets replaced by a - or a ~ symbol. 

This is what it looks like when using the system font:
In editor:
![image](https://user-images.githubusercontent.com/10830880/71120036-ce3ed480-21db-11ea-9798-4f6a948f89f1.png)

In local engine:
![image](https://user-images.githubusercontent.com/10830880/71119857-6be5d400-21db-11ea-9ff8-89af05c46a4c.png)

This is what it looks like when using a different font:
In editor:
![image](https://user-images.githubusercontent.com/10830880/71120099-f1698400-21db-11ea-9845-5d1c65958667.png)

In local engine:
![image](https://user-images.githubusercontent.com/10830880/71120113-00503680-21dc-11ea-88a3-54a6c5fc8e1b.png)

**Comment by britzl** [comment]
Have you added the € sign to the Extra Characters field of the font?

**Comment by britzl** [comment]
It works for me using a label and a font containing the Extra Characters field

**Comment by amel** [comment]
Hmm, perhaps it's because of the font. The € sign didn't work in another editor either. I ended up using a different font for the euro sign and that font does work fine when you add the € sign to the `Extra Characters` field.
