### ISSUE TITLE
Printing Hello world

### ISSUE THREAD

**Issue by Dublinscope** [defold/editor2-issues#2879]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-11-29T13:39:24.408889</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39b2b2d4bd91ffd166a5776bd998912a0ec9758c</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"9ab2b2c641944246b6fee9cea6a95d57"'>9ab2b2c641944246b6fee9cea6a95d57</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 441.66</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
Can you reproduce this? What was the steps you took to get it to crash?

**Comment by Dublinscope** [comment]
Sorry I can not reproduce the script that I was running.
I wanted to print "Hello world" on the scene/game canvas and Defold crashed.

A few weeks earlier, I tried to print a circle as a geometry on the scene and Defold crashed as well.

I stopped using Defold as I am not the right user for the game engine.
