### ISSUE TITLE
Project not build. java.util.concurrent.ExecutionException

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#2887]
### Expected behaviour
1)Project build
### Actual behaviour
1)Error while building
2)Bundle and build html work
### Steps to reproduce
1)Project https://drive.google.com/file/d/1tZEEaMGYn4ihnQHMOlgojKzPQf-ndO0o/view?usp=sharing
2)Try to build in windows.
<hr/>

<table>
<tr><td>Build time</td><td>2019-11-29T13:39:24.408889</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39b2b2d4bd91ffd166a5776bd998912a0ec9758c</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"69e17a2f38c14b71840deae5b1b99711"'>69e17a2f38c14b71840deae5b1b99711</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.86</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by d954mas** [comment]
Any idea?)

**Comment by d954mas** [comment]
Same problem on Linux. Not sure about Mac, but looks like cross platform problem

**Comment by d954mas** [comment]
Editor 162 work.

**Comment by britzl** [comment]
Thanks. We'll take a look and see if we can figure out what's wrong.

**Comment by matgis-king** [comment]
Looks like it is the semicolons at the end of the `go.property()` lines in `/platformer_creation_kit/framework/scripts/arrow.script` that are tripping up our parser. We're working on a fix, but the project should build if you just remove the unnecessary semicolons.
