### ISSUE TITLE
Sprite is incorrectly trimmed

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#2893]
This is happening on `b3ce15a30f88531b060534217b109c309f84e066`, with 4-vertex trimming enabled on a single frame from a longer animation.

Actual result:

<img width="289" alt="Screenshot 2020-01-20 at 19 42 25" src="https://user-images.githubusercontent.com/428060/72747421-46266300-3bbd-11ea-8d26-042ef0a76f55.png">

Expected result:

<img width="283" alt="Screenshot 2020-01-20 at 19 42 33" src="https://user-images.githubusercontent.com/428060/72747431-4d4d7100-3bbd-11ea-8141-cd806ae81810.png">

The sprite that's giving me trouble:

![diana_idle1](https://user-images.githubusercontent.com/428060/72747481-6a823f80-3bbd-11ea-9dd6-591a509233a9.png)

**Comment by JCash** [comment]
A new beta with sha1 `4f15d336c3ef1b3123fd1ceaae04813d2b7ae86e` is now released.
Download from https://forum.defold.com/t/defold-1-2-165-beta/64307
