### ISSUE TITLE
Manifest merge fails when referencing bundled resources and using a native extension (Android)

### ISSUE THREAD

**Issue by lrxit** [defold/editor2-issues#2896]
### Expected behaviour
Application should bundle successfully

### Actual behaviour
Bundle Android Application results in error.

![image](https://user-images.githubusercontent.com/49574732/73032211-c1e31280-3e3e-11ea-9048-6c9ffe206453.png)

	/tmp/job153493968657692172/build/AndroidManifest.xml:39: error: Error: No resource found that matches the given name (at 'theme' with value '@style/SplashTheme').

[Error log attached](https://github.com/defold/editor2-issues/files/4106147/build_a404b463128a6eecf3d5cce4916180b222488123_6560573902920042761.txt)

### Steps to reproduce

[Repro case attached](https://github.com/defold/editor2-issues/files/4106099/merge_manifest.zip)

Bundle Android Application works with Defold Editor 1.2.164.
Fails with 1.2.165 beta.

Project is configured with:

- Bundled resources
- Firebase extension
- Android Manifest

![image](https://user-images.githubusercontent.com/49574732/73032696-176bef00-3e40-11ea-942d-693a813548ed.png)

![image](https://user-images.githubusercontent.com/49574732/73032731-2ce11900-3e40-11ea-9a99-9c79bcec0736.png)

AndroidManifest has been changed to use a custom style theme:

![image](https://user-images.githubusercontent.com/49574732/73032294-0a9acb80-3e3f-11ea-852f-9e482e067945.png)

Style is included in bundled resources

![image](https://user-images.githubusercontent.com/49574732/73032843-7df10d00-3e40-11ea-9a90-9b99a3983c90.png)

<hr/>

<table>
<tr><td>Build time</td><td>2020-01-21T18:30:40.410545</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>a404b463128a6eecf3d5cce4916180b222488123</td></tr>
<tr><td>Defold engine sha</td><td>a404b463128a6eecf3d5cce4916180b222488123</td></tr>
<tr><td>Defold version</td><td>1.2.165</td></tr>
<tr><td>GPU</td><td>GeForce GTX 750 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.64</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by JCash** [comment]
There's a new beta version `40e9ca1299d22eed12bb0148ed117f418162cb19` out now with a fix for this.
