### ISSUE TITLE
Add sublime-like minimap [DEFEDIT-1230]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#290]
One of these guys:

![minimap](https://cloud.githubusercontent.com/assets/3016032/21011010/7cc19578-bd4f-11e6-8091-10257217cc55.png)

<hr/>
Defold version: 1.2.95
Defold sha: dc237f3ae4504aa7b8fcca4bcddf18ebcd4d2e8b
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Fixed in new code editor.
