### ISSUE TITLE
issue on mac

### ISSUE THREAD

**Issue by naptok** [defold/editor2-issues#2902]
### Steps to reproduce
1. write "coll"
2. change tab
3. error created!

<hr/>

<table>
<tr><td>Build time</td><td>2020-01-23T17:25:00.524437</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>70cc8d7d712dd866fd12a3a43297045ca7b27cb3</td></tr>
<tr><td>Defold engine sha</td><td>2be2687cbb670c2dbe9cf2e99577bc3338561778</td></tr>
<tr><td>Defold version</td><td>1.2.164</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c1dfd0bc442f40cd948bc7fb0e542d52"'>c1dfd0bc442f40cd948bc7fb0e542d52</a></td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 655</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.3.9</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.2</td></tr>
<table>

**Comment by britzl** [comment]
Thank you. This is a known JavaFX issue

https://github.com/openjdk/jfx/pull/89

We will upgrade JavaFX at some point after this PR has been merged and the problem will go away.
