### ISSUE TITLE
Assertion failed: address.m_family == DOMAIN_IPV4, file ..\src\dlib\socket.cpp, line 387

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2903]
I'm trying to detect if there is an internet connection on Windows and got this error which includes crashing engine when trying to do an http request after I disabled my Ethernet adapter.

sys.get_connectivity() still only works for mobile devices.

**Comment by subsoap** [comment]
https://forum.defold.com/t/crash-on-http-request-on-windows-when-offline/64014/5

Looks like fix is in next release?

**Comment by britzl** [comment]
Yes, please confirm that 1.2.165 solves the problem for you.

**Comment by subsoap** [comment]
@britzl Confirmed that it no longer crashes the engine on Windows when there is no net / adapter. 

It does produce a script error which should be noted, that it should be wrapped in a pcall if used.
```
http.request("https://www.timestampnow.com/", "GET", http_result)
```
When offline =

```ERROR:SCRIPT: Unable to create HTTP connection to 'https://www.timestampnow.com/'. No route to host?```

**Comment by britzl** [comment]
It depends on how you wish to handle it. Doesn't the `http_result` callback get invoked?

**Comment by subsoap** [comment]
Hmm, I just tested again to be sure and a pcall is not necessary.

```
local function http_result(self, _, response)
	print(response.status)
	if response.status == 200 or response.status == 304 then
		print("Net OK!")
	end
	print(response.response)

end


function init(self)
	http.request("https://www.timestampnow.com/", "GET", http_result)
	print("hello?")
end
```

With no net produces 

```
DEBUG:SCRIPT: hello?
ERROR:SCRIPT: Unable to create HTTP connection to 'https://www.timestampnow.com/'. No route to host?
DEBUG:SCRIPT: 0
DEBUG:SCRIPT: 
```
