### ISSUE TITLE
Application freeze after call `sys.exit(0)` on iOS

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#2905]
Platform: iOS.
iPhoneX 
iOS 13.3.1
If I call `sys.exit(0)` application hangs (Android works fine)
Also tested 1.2.164 the same issue.

**Comment by AGulev** [comment]
1.2.153 works fine. 
As I understand on iOS it's not a real exit from the application but something like "goto background" (that's how it works in 1.2.153, at least)
https://apps.apple.com/us/app/classic-solitaire-klondike/id1290718651?ls=1

**Comment by britzl** [comment]
Thanks. Looking into this for 1.2.166

**Comment by AGulev** [comment]
Solved in 1.2.168
