### ISSUE TITLE
Debug Symbols only for armv7 (ios)

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#2907]
When I build iOS build with debug symbols I get only armv7 dSYM file without arm64 dSYM.
It makes impossible to make crashes symbolication on modern devices.

Defold 1.2.165
Build from the editor.

**Comment by JCash** [comment]
You should be able to find it in the build.zip for that architecture?

**Comment by AGulev** [comment]
Maybe ( I was sure that we have it in the build folder with this new option. 
I'll try to rebuild the project and check my crash, but now I'm not sure that I can get the the same dSYM with a new build.

**Comment by AGulev** [comment]
Fixed in 1.2.166
