### ISSUE TITLE
An Error occurred when ParticleFX is simulated on Defold Editor

### ISSUE THREAD

**Issue by Ankhle** [defold/editor2-issues#2910]
### Expected behaviour
Default emitter should be simulated.
### Actual behaviour
![defold_issue](https://user-images.githubusercontent.com/60014720/74100618-85b8ed00-4b74-11ea-9191-a3808294b33a.png)

### Steps to reproduce
1. Create new project with "From Template" and "Desktop game"
2. Create Particle FX by selecting "File" -> "New" -> "Particle FX" -> name "test"
3. Simulate the Particle FX by selecting "View" -> "Play" or hitting space bar. 
<hr/>

<table>
<tr><td>Build time</td><td>2020-02-05T13:28:12.046624</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>842e31305a954a706b74a40c87b689f47fa44848</td></tr>
<tr><td>Defold engine sha</td><td>6fac6e80f09ab297093e3ff65a7f45ad56e06e33</td></tr>
<tr><td>Defold version</td><td>1.2.165</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"3ca078b8d7c94a1793df463134ca6de0"'>3ca078b8d7c94a1793df463134ca6de0</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 3000</td></tr>
<tr><td>GPU Driver</td><td>3.1.0 - Build 9.17.10.4459</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by wkqco33** [comment]
I have exactly same problem on mac. I can't edit particleFX.

**Comment by britzl** [comment]
We have released a fix for this earlier this week. Please update your editor (and confirm that it is working).

**Comment by britzl** [comment]
https://github.com/defold/defold/pull/4661
