### ISSUE TITLE
Editor Crash When ParticleFX Play

### ISSUE THREAD

**Issue by wkqco33** [defold/editor2-issues#2912]
### Expected behaviour
I want to edit my particleFX component but not working.

### Actual behaviour
If I play any particleFX, editor had been crashed.

### Steps to reproduce
any particleFX object click -> play -> crash

-- Error Message --
An error occurred
java.lang.AssertionError: Assert failed: (= 0 (mod (.limit buffer) (:vertex-size layout)))

<hr/>

<table>
<tr><td>Build time</td><td>2020-02-05T13:27:17.176371</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>842e31305a954a706b74a40c87b689f47fa44848</td></tr>
<tr><td>Defold engine sha</td><td>6fac6e80f09ab297093e3ff65a7f45ad56e06e33</td></tr>
<tr><td>Defold version</td><td>1.2.165</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"2e287154a3bb4ff08774de785f85d032"'>2e287154a3bb4ff08774de785f85d032</a></td></tr>
<tr><td>GPU</td><td>Intel Iris OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.4.23</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.3</td></tr>
<table>

**Comment by matgis-king** [comment]
A fix has been merged and an update to the editor should reach you shortly. Thanks for reporting!
