### ISSUE TITLE
Error when adding images to animation

### ISSUE THREAD

**Issue by gmantaos** [defold/editor2-issues#2913]
### Expected behaviour

Images added to the animation.

### Actual behaviour

![image](https://user-images.githubusercontent.com/29335643/74267233-f9d6ca80-4d05-11ea-97d0-44ec667f9dbc.png)

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-02-05T13:28:12.046624</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>842e31305a954a706b74a40c87b689f47fa44848</td></tr>
<tr><td>Defold engine sha</td><td>6fac6e80f09ab297093e3ff65a7f45ad56e06e33</td></tr>
<tr><td>Defold version</td><td>1.2.165</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"accd933c99484a348b4165100c8b135b"'>accd933c99484a348b4165100c8b135b</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 970/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 436.02</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by gmantaos** [comment]
Another error trying to do the same thing:

```
clojure.lang.ExceptionInfo: handler ':hide-selected' in context ':workbench' failed at ':enabled?' with message 'Caught exception during read: '
javax.imageio.IIOException: Caught exception during read: 
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
```

**Comment by britzl** [comment]
Does it matter how many images you're trying to add? Does it matter what filename the images has?

**Comment by gmantaos** [comment]
It's hard to say now, I had to revert to `1.2.164` because I was having issues with my other atlases too.

Very roughly what I sort-of remember trying:

- Adding one of more images to an animation caused the issue.
- The image names were `hit-0.png`, `hit-1.png` etc.
- I did not try changing the image names.
- At some point I was able to add the images to the atlas, and then drag them into the animation I wanted. Doing this broke the atlas, and any collections using said atlas would then not load as well, with similar errors.

**Comment by britzl** [comment]
I wonder if this had to do with the recently released sprite trimming feature? Can you please download the latest release and see if you can reproduce the problem or not? If you are able to reproduce the problem we would appreciate if you could write down the steps you took to make it crash as well as sharing the images and other files you used when you got it to crash. Thanks!

**Comment by gmantaos** [comment]
I can't seem to reproduce it any more on `1.2.165`, strange...

Will re-open the issue if it occurs again :)

**Comment by britzl** [comment]
Ok, thanks for the update! Happy coding!
