### ISSUE TITLE
ERROR:PROFILER: Could not get CPU usage information for thread ...

### ISSUE THREAD

**Issue by mosmetro** [defold/editor2-issues#2918]
ERROR:PROFILER: Could not get CPU usage information for thread 5.
...
ERROR:PROFILER: Could not get CPU usage information for thread 6.
etc.

The question is, why that should bother me? I absolutely don't care why editor can't get this information. That mean nothing.  Please add option to rule out unwanted/useless messages. Or just don't write this kind of messages to console.

That would first reported Jun 25, 2017. Still exists, very annoying and not fixed. It that so hard to fix? I suppose not, this very simple and easy fix. Shame on you.
<hr/>

<table>
<tr><td>Build time</td><td>2020-02-12T11:19:51.822120</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>801e1128222d313bdf47a0e083a681bb01accac4</td></tr>
<tr><td>Defold engine sha</td><td>6fac6e80f09ab297093e3ff65a7f45ad56e06e33</td></tr>
<tr><td>Defold version</td><td>1.2.165</td></tr>
<tr><td>GPU</td><td>Intel HD Graphics 4000 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.10.16</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.6</td></tr>
<table>

**Comment by britzl** [comment]
> Still exists, very annoying and not fixed. It that so hard to fix? I suppose not, this very simple and easy fix. Shame on you

This kind of language usually won't get you anywhere when reporting an issue, but in this case I agree with you that the messages are unwanted and something you as a game developer can't do anything about. The messages will be removed in 1.2.167.
