### ISSUE TITLE
Going to end of line scrolls text editor too far if much longer line exists

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#292]
- Create a new script

- Paste the following code:
```
aaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa aaaaaaaa aaaaaaaaaaaaaa aaaaaaaaaaaaaaa

bbbbbbbbbbbbb bbbbbbbbbb bbbbbbb
```

- Make sure that all the b:s fit into the view but that the a:s are going outside the screen
- Set the cursor on the blank line between the a:s and the b:s
- Now click slightly beyond the end of the b:s

-> The scrolling will now be way too much to the right

<hr/>
Defold version: 1.2.95
Defold sha: a89c5c502c53dae7788f2781bba29685e166d1d2
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment]
Fixed
