### ISSUE TITLE
Can't start the game with debugger attached (F5)

### ISSUE THREAD

**Issue by karlqueckfeldt** [defold/editor2-issues#2926]
### Expected behaviour
The game should start with debugging.

### Actual behaviour
This error message appears.
![image](https://user-images.githubusercontent.com/13727500/76881374-52573580-6879-11ea-888e-45236984decc.png)

Trying to then start again, this message appears.
![image](https://user-images.githubusercontent.com/13727500/76881503-86caf180-6879-11ea-9373-a9ea009daa3b.png)

### Steps to reproduce
Press F5 to start with Debugger.

<hr/>

<table>
<tr><td>Build time</td><td>2020-03-03T08:34:30.874440</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>95fcc9ca28d33583c7103c40c0c54cc73143e322</td></tr>
<tr><td>Defold engine sha</td><td>5295afb3878441fb12f497df8831148525dcfb10</td></tr>
<tr><td>Defold version</td><td>1.2.166</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"82c1044e09ea47f493862103950f2bdd"'>82c1044e09ea47f493862103950f2bdd</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 26.20.100.7263</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by britzl** [comment]
But you're able to connect to the device and launch your game to it?

**Comment by karlqueckfeldt** [comment]
> But you're able to connect to the device and launch your game to it?

Sorry maybe I'm misunderstanding something. I'm just trying to run the debugger on one computer by pressing F5, no external devices connected.

**Comment by britzl** [comment]
Ah, got it. Ok, and I'm assuming that running without debug works?

Is it possible that there's some Windows setting/firewall preventing a connection from the editor to the running game (127.0.0.1:some_port)?

**Comment by britzl** [comment]
Oh, can you build and run and then connect the debugger when the game is running, or do you get the same error?

**Comment by karlqueckfeldt** [comment]
I tried this again today and I don't seem to experience this issue anymore. Running the game with the debugger works fine now, as well as starting without debugger and attaching it after the fact. I have seen the issue come and go, so it might just be as you say that it's because of some firewall configuration and what network I'm on.

**Comment by britzl** [comment]
Ok, good to hear that it works better now! With a lot of people now working from home due to the Coronavirus, maybe you had a VPN connection active when it didn't work? Perhaps the VPN caused problems?
