### ISSUE TITLE
java.lang.NullPointerException: Unknown while bundling for any platform

### ISSUE THREAD

**Issue by VojtechKlos** [defold/editor2-issues#2934]
### Expected behaviour
The game produces a bundle for a given platform
### Actual behaviour
Throws NullPointerException error
### Steps to reproduce
1) clone repo https://github.com/VojtechKlos/example-defold-error
2) try to bundle for any platform (I tried Android and Windows and it gives me the same error)
3) observe error
<hr/>

<table>
<tr><td>Build time</td><td>2020-03-03T08:34:30.874440</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>95fcc9ca28d33583c7103c40c0c54cc73143e322</td></tr>
<tr><td>Defold engine sha</td><td>5295afb3878441fb12f497df8831148525dcfb10</td></tr>
<tr><td>Defold version</td><td>1.2.166</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"839b9f80f7344c22b502ef5d0215bc4a"'>839b9f80f7344c22b502ef5d0215bc4a</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 432.00</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by VojtechKlos** [comment]
I am kind of new to Defold so maybe it is my fault but it gave me an option to report so it is now reported :-)

**Comment by britzl** [comment]
com.dynamo.bob.fs.DefaultFileSystem in get at line 34
com.dynamo.bob.Project in getResource at line 1327
com.dynamo.bob.pipeline.BuilderUtil in checkResource at line 22
com.dynamo.bob.pipeline.LuaBuilder in build at line 184
com.dynamo.bob.Project in runTasks at line 1007
com.dynamo.bob.Project in doBuild at line 808
com.dynamo.bob.Project in build at line 443

**Comment by britzl** [comment]
Change from:

    local globals = require("/globals")

to

    local globals = require("globals")
