### ISSUE TITLE
Clear color game.project issue

### ISSUE THREAD

**Issue by gianmichelemariani** [defold/editor2-issues#2936]
The clear color options in the game.project seem to be broken. Even on an empty project I'm getting green/blue/alpha in the display section, and red under the render section.

Also I cannot understand if values are in 0-1.0 or 0-255.

<img width="722" alt="Screenshot 2020-03-29 at 21 17 39" src="https://user-images.githubusercontent.com/46694168/77859718-e83c7a00-7202-11ea-9a3b-c3c431e60e1c.png">

<hr/>

<table>
<tr><td>Build time</td><td>2020-03-23T12:34:30.668504</td></tr>
<tr><td>Defold channel</td><td>beta</td></tr>
<tr><td>Defold editor sha</td><td>a6ae03390d43043b35d3b92a56c144e7c678c765</td></tr>
<tr><td>Defold engine sha</td><td>a6ae03390d43043b35d3b92a56c144e7c678c765</td></tr>
<tr><td>Defold version</td><td>1.2.167</td></tr>
<tr><td>GPU</td><td>Intel(R) Iris(TM) Plus Graphics 640</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.4.23</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.3</td></tr>
<table>

**Comment by britzl** [comment]
This has been fixed in the latest stable release.
