### ISSUE TITLE
problem with building (if I clean "internals" and do fetching libraries again - all is fine again)

### ISSUE THREAD

**Issue by Lampogolovii** [defold/editor2-issues#2944]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-04-06T11:43:49.851764</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>766ac903e66bda83a005f0546321a6bfe3e17cc5</td></tr>
<tr><td>Defold engine sha</td><td>96f7a5e4f617d5f6f4645f30a3e6ff656689435d</td></tr>
<tr><td>Defold version</td><td>1.2.167</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"f8bb9922bf0247b2a44db338b86d0006"'>f8bb9922bf0247b2a44db338b86d0006</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 650M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-14.0.32 355.11.11.10.10.143</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.4</td></tr>
<table>

**Comment by britzl** [comment]
This usually is an indication that a downloaded dependency was corrupt. This happens a bit too often unfortunately.

**Comment by Lampogolovii** [comment]
Thanks for your answer. I see. Now I'm trying to use only downloaded masters by zip.
