### ISSUE TITLE
Windows Defender reacting on installation

### ISSUE THREAD

**Issue by Trikisatan** [defold/editor2-issues#295]
Windows Defender is claiming the installation of the new editor is a trojan. This may or may not be a problem, but I thought I'd give a heads up as I couldn't find a thread about it when I searched.

Identified as Win32/Repjexi
https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fRepjexi&threatid=2147685370&enterprise=0

Kategori: Trojan

Beskrivning: Det här programmet är farligt och kör kommandon från en attackerare.

Rekommenderad åtgärd: Ta bort programvaran omedelbart.

Objekt: 
file:C:\Users\james\AppData\Local\Temp\defold-unpack2220871503402437216\bin\dmengine.exe
file:C:\Users\james\AppData\Local\Temp\defold-unpack2220871503402437216\bin\dmengine_release.exe
file:C:\Users\james\AppData\Local\Temp\defold-unpack2220871503402437216\bin\luajit.exe

**Comment by Trikisatan** [comment]
Update: After launching the editor for the first time, I couldn't build. So I had to tell Windows Defender to allow Win32/Repjexi (yikes!) and then restart the editor to build.

**Comment by ragnard-king** [comment]
Hopefully fixed now that we've started to sign our windows launcher. Please re-open if not.
