### ISSUE TITLE
+,

### ISSUE THREAD

**Issue by paweljarosz** [defold/editor2-issues#2955]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2020-04-28T07:55:02.593053</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>39749b921d8e37b9a669f4096a3faa6d7252dec5</td></tr>
<tr><td>Defold engine sha</td><td>e22f6d2f81e7c53ebcbfefe703ff22ce5da252c0</td></tr>
<tr><td>Defold version</td><td>1.2.168</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"541ef6d83f954b339f0bceb21749a318"'>541ef6d83f954b339f0bceb21749a318</a></td></tr>
<tr><td>GPU</td><td>Intel(R) UHD Graphics 620</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 25.20.100.6472</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by eangelin** [comment]
Cannot find sentry error, closing.
