### ISSUE TITLE
Search in files, go to code, gets scrolling wrong

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#296]
When doing a search in files and you click a resulting code line the file is opened and the cursor goes to the right place, but the scrolling in the view is all wrong.

### Expected behaviour
Scroll view is where the cursor is.

### Actual behaviour
The scroll view is not where the cursor is.

### Steps to reproduce
In a project with long code files:
Search in files for a term
Double click a search result

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Fixed in new code editor.
