### ISSUE TITLE
Tab information in main editor window dissappears after some size changing of the editor window [DEFEDIT-674]

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#298]
1. Open Editor
2. Open a collection or go asset
3. Change the editor window size a few times to smaller and bigger

Actual result:
After something small changes and sometimes a few more and bigger changes the info in the tab disappears
![change](https://cloud.githubusercontent.com/assets/22887289/21049221/f17f500c-be13-11e6-81f0-e5f8415ba1dc.gif)
 and you have to close the tab and open it again.

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

![change](https://cloud.githubusercontent.com/assets/22887289/21049241/0630ae74-be14-11e6-81a5-f1371e09ed72.gif)

**Comment by erikangelin-king** [comment]
This was related to https://github.com/defold/editor2-issues/issues/361, and after that fix we can no longer reproduce this.
