### ISSUE TITLE
Render error [level.atlas] {type: file not found}, moved png file path not updated in atlas

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#302]
Create an atlas (level.atlas)
add images to the atlas
Save
Move the images to another path
Save
Move the atlas, so you can diff it

As the move and replace didnt work another bug i moved the png one by one to another image folder in level instead of main.

Actual result:
The image path in the atlas for the images has not changed.
![screen shot 266](https://cloud.githubusercontent.com/assets/22887289/21050628/089acf5c-be1c-11e6-9aad-fc774a552fde.PNG)

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Will be fixed as part of DEFEDIT-614

**Comment by ragnard-king** [comment]
Fixed by defold/defold#1158/
