### ISSUE TITLE
Cant copy&paste into the same folder

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#304]
1. Select a game object in a subfolder
2. Right click and copy
3. Select the same subfolder
4. Right click and select paste

Actual result:
Paste is greyed out, it cant be copied into the same folder

In Editor 1 it can be copied into the same folder. You get a alert saying name conflict and enter a new name.

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment]
Fixed.
