### ISSUE TITLE
Some meshes don't show up when running the game [DEFEDIT-669]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#306]
For engine 1.2.95 we needed to change some meshes and transforms for them due to some older bugs in how defold handled collada files. Building the same project in editor 2 gives a different result than editor 1. Usually it means that they don't show at all, most likely due to a quads and flat meshes being rotated 90 degrees along x.

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-669
