### ISSUE TITLE
Console doesn't clear when starting the game [DEFEDIT-746]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#308]
Old editor clears the log when starting a new instance of the game. Preferably there should be a toggle button for "Clear on start". 

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
