### ISSUE TITLE
Search in file option doesnt set the courser on the right row from the search result.

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#313]
1. Open a script file
2. Select File->Search in file option
3. Search for something in the script file you opened
4. Double click on one of the results

Actual result:
The courser in the script file doesnt move to the row for the search result.

This works fine if you dont have the script file open at all.

**Comment by Malmer** [comment]
May be related to #296. In my testing it actually sets the cursor correctly, but the scrolling isn't where the cursor is. Moving the cursor with the keyboard arrows will set the scrolling right though, and in my testing when doing that the cursor was in the right spot.

**Comment by erikangelin-king** [comment]
Fixed in new code editor.
