### ISSUE TITLE
Error occurs when trying to move a large number of items quickly in the Outline view

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#315]
An error occured when trying to move a large number of items at once in the Outline editor

![error](https://cloud.githubusercontent.com/assets/23701955/21101784/824af12e-c083-11e6-8730-f1e00c623fcf.png)

Example structure:
![2016-12-12 16_27_18-defold editor 2 0 - my project](https://cloud.githubusercontent.com/assets/23701955/21102708/fa8e7e04-c087-11e6-9591-88d28b459881.png)

![error](https://cloud.githubusercontent.com/assets/23701955/21101937/4c049e0c-c084-11e6-9565-d1bc437b1b27.gif)

Steps to repro:
1. Create a collection file and add many components to it (game objects, sprites, views, models, collision objects, etc)
2. Start dragging and dropping items from one branch to the other, like in the above gif
3. A proper error message should be shown if some sub'-element is dragged under an element that doesn't support it. 

Error:

`{:cause nil,
 :via
 [{:type java.lang.NullPointerException,
   :message nil,
   :at
   [editor.collection$prop_id_duplicate_QMARK_ invokeStatic "collection.clj" 86]}],
 :trace
 [[editor.collection$prop_id_duplicate_QMARK_ invokeStatic "collection.clj" 86]
  [editor.collection$prop_id_duplicate_QMARK_ invoke "collection.clj" 85]
  [clojure.core$partial$fn__4759 invoke "core.clj" 2515]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 648]
  [editor.validation$prop_error invokeStatic "validation.clj" 48]
  [editor.validation$prop_error doInvoke "validation.clj" 48]
  [clojure.lang.RestFn invoke "RestFn.java" 500]
  [editor.collection$fn__53540 invokeStatic "collection.clj" 89]
  [editor.collection$fn__53540 invoke "collection.clj" 89]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [clojure.lang.Var invoke "Var.java" 379]
  [clojure.lang.Var invoke "Var.java" 379]
  [clojure.lang.Var invoke "Var.java" 379]
  [editor.collection$ReferencedGOInstanceNode$behavior$_declared_properties invokeStatic "collection.clj" 284]
  [editor.collection$ReferencedGOInstanceNode$behavior$_declared_properties invoke "collection.clj" 284]
  [clojure.lang.Var invoke "Var.java" 383]
  [internal.node.NodeImpl produce_value "node.clj" 271]
  [internal.node$node_value_STAR_ invokeStatic "node.clj" 338]
  [internal.node$node_value invokeStatic "node.clj" 353]
  [dynamo.graph$node_value invokeStatic "graph.clj" 739]
  [dynamo.graph$node_value invoke "graph.clj" 711]
  [dynamo.graph$node_value invokeStatic "graph.clj" 727]
  [dynamo.graph$default_node_serializer invokeStatic "graph.clj" 952]
  [dynamo.graph$default_node_serializer invoke "graph.clj" 948]
  [dynamo.graph$copy$serializer__5859 invoke "graph.clj" 994]
  [clojure.core$map_indexed$mapi__7050$fn__7051 invoke "core.clj" 7022]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 521]
  [clojure.core$seq__4357 invokeStatic "core.clj" 137]
  [clojure.core$zipmap invokeStatic "core.clj" 2962]
  [dynamo.graph$copy invokeStatic "graph.clj" 960]
  [dynamo.graph$copy invoke "graph.clj" 960]
  [dynamo.graph$copy invokeStatic "graph.clj" 991]
  [editor.outline$copy invokeStatic "outline.clj" 74]
  [editor.outline$copy invoke "outline.clj" 74]
  [editor.outline$copy invokeStatic "outline.clj" 76]
  [editor.outline_view$drag_detected invokeStatic "outline_view.clj" 282]
  [editor.outline_view$setup_tree_view$reify__62433 handle "outline_view.clj" 416]
  [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 86]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238]
  [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191]
  [com.sun.javafx.event.CompositeEventDispatcher dispatchBubblingEvent "CompositeEventDispatcher.java" 59]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.Scene$DnDGesture fireEvent "Scene.java" 2933]
  [javafx.scene.Scene$DnDGesture process "Scene.java" 3012]
  [javafx.scene.Scene$DnDGesture access$8200 "Scene.java" 2909]
  [javafx.scene.Scene$MouseHandler process "Scene.java" 3773]
  [javafx.scene.Scene$MouseHandler access$1500 "Scene.java" 3485]
  [javafx.scene.Scene impl_processMouseEvent "Scene.java" 1762]
  [javafx.scene.Scene$ScenePeerListener mouseEvent "Scene.java" 2494]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 380]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 294]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler lambda$handleMouseEvent$354 "GlassViewEventHandler.java" 416]
  [com.sun.javafx.tk.quantum.QuantumToolkit runWithoutRenderLock "QuantumToolkit.java" 389]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler handleMouseEvent "GlassViewEventHandler.java" 415]
  [com.sun.glass.ui.View handleMouseEvent "View.java" 555]
  [com.sun.glass.ui.View notifyMouse "View.java" 937]
  [com.sun.glass.ui.win.WinApplication _runLoop "WinApplication.java" -2]
  [com.sun.glass.ui.win.WinApplication lambda$null$148 "WinApplication.java" 191]
  [java.lang.Thread run "Thread.java" 745]]}
`

Defold version: 1.2.95
Defold sha: 2fd8732d146f5a252125ce1b210e3793f50e169c
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment]
Fixed.
