### ISSUE TITLE
User cannot scale two or more sprites at the same time

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#316]
### Expected behaviour
THe user should be able to scale two or more sprites at the same time

![scale](https://cloud.githubusercontent.com/assets/23701955/21104240/78eeee22-c08e-11e6-9c7b-22c35d9546d8.gif)

### Actual behaviour
User cannot scale two or more sprites at the same time. They can be moved and rotated at the same time, but they cannot be scaled. The user can scale two game objects at the same time.

Please note that this issue can be replicated on Editor 1

### Steps to reproduce
Select two or more sprites at the same time and try to scale them.

<hr/>
Defold version: 1.2.95
Defold sha: ed9e4301e4da8dbed5e05ba0a6128758461e59d1
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by RagnarSvenssonKing** [comment]
You should not be able to scale sprites at all, not even 1 sprite. Can you try to scale 1 sprite? It should not be possible either.

**Comment by sofiahe** [comment]
Tested in both editor 1 and 2, its not possible to scale one sprite.

**Comment by Malmer** [comment]
May be related, but when you select many game objects, shouldn't they really rotate around the common center, rather than individually? Or it should be a toggle button.

**Comment by erikangelin-king** [comment]
https://github.com/defold/editor2-issues/issues/713
