### ISSUE TITLE
Error when syncing and not saving before

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#317]
1. Save all
2. Sync, pull and push all
3. Add an empty new atlas file save with the default name and sync (no save before)

Actual result:
![screen shot 280](https://cloud.githubusercontent.com/assets/22887289/21105596/19ea9bcc-c08b-11e6-9b6a-b540235897c4.PNG)

{:cause
 "Could not delete file C:\\Users\\sofia.hedlund\\DefoldTutorial1Editor2_v2\\main\\untitled.atlas",
 :via
 [{:type org.eclipse.jgit.api.errors.JGitInternalException,
   :message "Stashing local changes did not successfully complete",
   :at
   [org.eclipse.jgit.api.StashCreateCommand call "StashCreateCommand.java" 392]}
  {:type java.io.IOException,
   :message
   "Could not delete file C:\\Users\\sofia.hedlund\\DefoldTutorial1Editor2_v2\\main\\untitled.atlas",
   :at [org.eclipse.jgit.util.FileUtils delete "FileUtils.java" 197]}],
 :trace
 [[org.eclipse.jgit.util.FileUtils delete "FileUtils.java" 197]
  [org.eclipse.jgit.util.FileUtils delete "FileUtils.java" 125]
  [org.eclipse.jgit.api.StashCreateCommand call "StashCreateCommand.java" 378]
  [editor.git$stash invokeStatic "git.clj" 172]
  [editor.sync$begin_flow_BANG_ invokeStatic "sync.clj" 116]
  [editor.changes_view$fn__22023$fnk22019_positional__22024$fn__22025 invoke "changes_view.clj" 68]
  [editor.defold_project$save_all_BANG_$fn__12101$fn__12104 invoke "defold_project.clj" 220]
  [clojure.lang.AFn run "AFn.java" 22]
  [com.sun.javafx.application.PlatformImpl lambda$null$173 "PlatformImpl.java" 295]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.application.PlatformImpl lambda$runLater$174 "PlatformImpl.java" 294]
  [com.sun.glass.ui.InvokeLaterDispatcher$Future run "InvokeLaterDispatcher.java" 95]
  [com.sun.glass.ui.win.WinApplication _runLoop "WinApplication.java" -2]
  [com.sun.glass.ui.win.WinApplication lambda$null$148 "WinApplication.java" 191]
  [java.lang.Thread run "Thread.java" 745]]}

<hr/>
Defold version: 1.2.95
Defold sha: c74b0ff5d23062b2fc1fbfd8ae73c5db81ba2c5c
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by matgis-king** [comment]
Fixed along with #215.
