### ISSUE TITLE
Search in files should be redesigned

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#320]
Searching in all files is very important when working with lua and scripts. It would be be nice pressing enter after typing a search would put the search results in a new tab somewhere instead of closing the search popup. The search field should also have a dropdown with the history of previous searches.

<hr/>
Defold version: 1.2.95
Defold sha: 6281048b5c90f95c4ec2973b1b9c8f8e7f3c0b9c
Platform: Mac OS X 10.12.1 (x86_64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
I agree to this. You almost never want to look at just one search result, but rather walk through a bunch of result items and do fixes (or simply read to understand) in sequence.

**Comment by matgis-king** [comment]
We just merged defold/defold#1414, which includes the following improvements to the Search in Files feature:

* The Search in Files dialog is no longer modal, and can be kept around.
  * Double-clicking a match to open it from the Search in Files dialog no longer closes the dialog.
* A Search Results tab has been added to the bottom of the editor window. When the Search in Files dialog is dismissed, the search results move here.
  * Hitting Enter from the search term field closes the Search in Files dialog and moves the results into the Search Results tab.
  * Hitting Escape closes the Search in Files dialog but does not replace the results in the Search Results tab.
* You can now select multiple matches in the Search in Files dialog and press Enter to open them all.
  * Hitting Enter from the search results list in the Search in Files dialog opens all selected matches, but does not dismiss the dialog.
* The previous search terms are remembered between search sessions.
* When opening a project, its contents are indexed to make searching responsive from the start.

Hope you like it!
