### ISSUE TITLE
The whole editor becomes sluggish as the console contents grow in size [DEFEDIT-891]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#322]
If I print() something in update() in a script or if an error is repeatedly written to the console the editor quickly becomes super sluggish. Clearing the console makes it return to normal speed. Perhaps add a max size for the console and throw away older entries?

**Comment by Malmer** [comment]
You really don't want to have the log partly lost within one game run. Probably better to try to make it not sluggish to begin with. Plenty of other tools can do it - with even more advanced logging - without anything getting lost or sluggish.

In this case my guess is that it creates one line in a list view per print line, which soon becomes quite a lot of heavy java objects. If it was just string data and then the view only actually reused the elements that were visible it would probably be much more efficient.

**Comment by Malmer** [comment]
This is very problematic if your game for some reason gets stuck in an infinite loop with prints. Will more or less force you to force-quit not just the game but the editor aswell.

```lua
while true do
    print("hello world")
end
```

-> Use the Force-Quit, Luke

**Comment by matgis-king** [comment]
As a quick fix for this being a blocker, we now prevent the console log from growing too long. We will have to revisit this with a better fix in the future.
