### ISSUE TITLE
All sub-editors have the same toolbar, even where the tools are not applicable

### ISSUE THREAD

**Issue by EmilEnglund** [defold/editor2-issues#325]
### Expected behaviour
The Move, Rotate and Scale tools should be visible only in sub-editors where they are applicable. Other sub-editors would then have other toolbars appropriate to them.
### Actual behaviour
The Move, Rotate and Scale tools are always visible and clickable at the top of the Defold window, and they are the only tools available outside of the top-left text-menus.
### Steps to reproduce
Start the editor
<hr/>
Defold version: 1.2.95
Defold sha: 6281048b5c90f95c4ec2973b1b9c8f8e7f3c0b9c
Platform: Windows 10 10.0 (amd64)
Java version: 1.8.0_102-b14

**Comment by erikangelin-king** [comment]
Fixed, since the tools moved into the scene view.
