### ISSUE TITLE
Cant put a text node on different positions on different layouts

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#327]
1. Create a gui
2. Add a text node
3. Add two layouts, portrait and landscape
4. Try to move the text node to different positions in the two layouts

Actual result:
The position cant be changed per layout, its the same for both.

In editor 1 you can move it to different positions per layout.

Also there is only two layouts in editor 2, in editor 1 there are 3.

<hr/>
Defold version: 1.2.95
Defold sha: 6281048b5c90f95c4ec2973b1b9c8f8e7f3c0b9c
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by AGulev** [comment]
can't reproduce in 1.2.144
