### ISSUE TITLE
The confirm dialog ends up on the wrong screen

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#329]
The confirm dialog doesn't end up on the same screen as the main editor in a multi screen setup. This is annoying, especially since there are no keyboard shortcuts for the confirm screen.

**Comment by RagnarSvenssonKing** [comment]
Quick-win if it's enough to center the dialog in the parent and this is a one liner.

**Comment by erikangelin-king** [comment]
Is this still an issue? I think we've done some related changes.

**Comment by AGulev** [comment]
@britzl  I can't reproduce
