### ISSUE TITLE
Exception while selecting multiple gui nodes in the outline

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#331]
Sometimes when clicking around in the outline and multi-selecting nodes you get an exception:

{:cause nil, :via [{:type java.lang.NullPointerException, :message nil, :at [editor.outline_view$item__GT_value invokeStatic "outline_view.clj" 139]}], :trace [[editor.outline_view$item__GT_value invokeStatic "outline_view.clj" 139] [editor.outline_view$item__GT_value invoke "outline_view.clj" 138] [clojure.core$mapv$fn__6953 invoke "core.clj" 6627] [clojure.core.protocols$iter_reduce invokeStatic "protocols.clj" 49] [clojure.core.protocols$fn__6742 invokeStatic "protocols.clj" 75] [clojure.core.protocols$fn__6742 invoke "protocols.clj" 75] [clojure.core.protocols$fn__6684$G__6679__6697 invoke "protocols.clj" 13] [clojure.core$reduce invokeStatic "core.clj" 6545] [clojure.core$mapv invokeStatic "core.clj" 6618] [editor.outline_view$propagate_selection invokeStatic "outline_view.clj" 403] [editor.outline_view$setup_tree_view$reify__62426 onChanged "outline_view.clj" 408] [com.sun.javafx.collections.ListListenerHelper$SingleChange fireValueChangedEvent "ListListenerHelper.java" 164] [com.sun.javafx.collections.ListListenerHelper fireValueChangedEvent "ListListenerHelper.java" 73] [com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList callObservers "ReadOnlyUnbackedObservableList.java" 75] [javafx.scene.control.MultipleSelectionModelBase$1 onChanged "MultipleSelectionModelBase.java" 97] [com.sun.javafx.collections.ListListenerHelper$Generic fireValueChangedEvent "ListListenerHelper.java" 329] [com.sun.javafx.collections.ListListenerHelper fireValueChangedEvent "ListListenerHelper.java" 73] [com.sun.javafx.scene.control.ReadOnlyUnbackedObservableList callObservers "ReadOnlyUnbackedObservableList.java" 75] [javafx.scene.control.MultipleSelectionModelBase clearAndSelect "MultipleSelectionModelBase.java" 378] [javafx.scene.control.TreeView$TreeViewBitSetSelectionModel clearAndSelect "TreeView.java" 1477] [com.sun.javafx.scene.control.behavior.CellBehaviorBase simpleSelect "CellBehaviorBase.java" 256] [com.sun.javafx.scene.control.behavior.CellBehaviorBase doSelect "CellBehaviorBase.java" 240] [com.sun.javafx.scene.control.behavior.CellBehaviorBase mouseReleased "CellBehaviorBase.java" 159] [com.sun.javafx.scene.control.skin.BehaviorSkinBase$1 handle "BehaviorSkinBase.java" 96] [com.sun.javafx.scene.control.skin.BehaviorSkinBase$1 handle "BehaviorSkinBase.java" 89] [com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord handleBubblingEvent "CompositeEventHandler.java" 218] [com.sun.javafx.event.CompositeEventHandler dispatchBubblingEvent "CompositeEventHandler.java" 80] [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 238] [com.sun.javafx.event.EventHandlerManager dispatchBubblingEvent "EventHandlerManager.java" 191] [com.sun.javafx.event.CompositeEventDispatcher dispatchBubblingEvent "CompositeEventDispatcher.java" 59] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 58] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56] [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114] [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74] [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54] [javafx.event.Event fireEvent "Event.java" 198] [javafx.scene.Scene$MouseHandler process "Scene.java" 3757] [javafx.scene.Scene$MouseHandler access$1500 "Scene.java" 3485] [javafx.scene.Scene impl_processMouseEvent "Scene.java" 1762] [javafx.scene.Scene$ScenePeerListener mouseEvent "Scene.java" 2494] [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 380] [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 294] [java.security.AccessController doPrivileged "AccessController.java" -2] [com.sun.javafx.tk.quantum.GlassViewEventHandler lambda$handleMouseEvent$354 "GlassViewEventHandler.java" 416] [com.sun.javafx.tk.quantum.QuantumToolkit runWithoutRenderLock "QuantumToolkit.java" 389] [com.sun.javafx.tk.quantum.GlassViewEventHandler handleMouseEvent "GlassViewEventHandler.java" 415] [com.sun.glass.ui.View handleMouseEvent "View.java" 555] [com.sun.glass.ui.View notifyMouse "View.java" 937]]}

**Comment by erikangelin-king** [comment]
@britzl Has this happened recently again? Ok to close?

**Comment by britzl** [comment]
Not happening anymore.
