### ISSUE TITLE
GUI rendered beneath sprites in Collection (not-runtime)

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#332]
### Expected behaviour
I open my main collection to view the full composition with gui on top.
### Actual behaviour
I see the outline of the gui nodes - but no color - since GUI is rendered beneath the sprites.

### Steps to reproduce
main.collection structure:
* board.collection
** go
*** sprite
* go
** gui
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.95</td></tr>
<tr><td>Defold sha</td><td>c9fa4c639b8ef10e69b355683dcda63acc595287</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can't repro this, please reopen if it's still an issue!
