### ISSUE TITLE
Unable to open project (crash while loading)

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#333]
We did some work on a gui scene and the whole editor crashed. Now it's not possible to open the project again. The same project can be opened and built in the old editor without any errors.

Zip of project sent to @ragnard-king 

{:cause "Assert failed: source-node-id",
 :via
 [{:type java.lang.AssertionError,
   :message "Assert failed: source-node-id",
   :at [dynamo.graph$connect invokeStatic "graph.clj" 490]}],
 :trace
 [[dynamo.graph$connect invokeStatic "graph.clj" 490]
  [editor.gui$attach_gui_node invokeStatic "gui.clj" 307]
  [editor.gui$load_gui_scene$fn__50703 invoke "gui.clj" 1719]
  [editor.gui$load_gui_scene invokeStatic "gui.clj" 1699]
  [editor.gui$load_gui_scene invoke "gui.clj" 1593]
  [editor.defold_project$load_node invokeStatic "defold_project.clj" 67]
  [editor.defold_project$load_resource_nodes$iter__11991__11995$fn__11996$fn__11997 invoke "defold_project.clj" 85]
  [editor.defold_project$load_resource_nodes$iter__11991__11995$fn__11996 invoke "defold_project.clj" 79]
  [clojure.lang.LazySeq sval "LazySeq.java" 40]
  [clojure.lang.LazySeq seq "LazySeq.java" 49]
  [clojure.lang.RT seq "RT.java" 521]
  [clojure.core$seq__4357 invokeStatic "core.clj" 137]
  [clojure.core$dorun invokeStatic "core.clj" 3024]
  [clojure.core$doall invokeStatic "core.clj" 3039]
  [editor.defold_project$load_resource_nodes invokeStatic "defold_project.clj" 79]
  [editor.defold_project$load_nodes_BANG_ invokeStatic "defold_project.clj" 88]
  [editor.defold_project$load_project$fn__12070 invoke "defold_project.clj" 148]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 646]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1881]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1881]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [editor.defold_project$load_project invokeStatic "defold_project.clj" 148]
  [editor.defold_project$open_project_BANG_ invokeStatic "defold_project.clj" 568]
  [editor.boot_open_project$open_project invokeStatic "boot_open_project.clj" 269]
  [editor.boot_open_project$open_project invoke "boot_open_project.clj" 267]
  [clojure.lang.AFn applyToHelper "AFn.java" 160]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 646]
  [editor.boot$open_project_with_progress_dialog$fn__71965 invoke "boot.clj" 122]
  [editor.ui$modal_progress$fn__10492$fn__10497$fn__10498 invoke "ui.clj" 1087]
  [editor.ui$modal_progress$fn__10492$fn__10497 invoke "ui.clj" 1086]
  [clojure.core$binding_conveyor_fn$fn__4676 invoke "core.clj" 1938]
  [clojure.lang.AFn call "AFn.java" 18]
  [java.util.concurrent.FutureTask run "FutureTask.java" 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1142]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 617]
  [java.lang.Thread run "Thread.java" 745]]}

**Comment by ragnard-king** [comment]
Fix has been committed, coming in build shortly.
