### ISSUE TITLE
Ability to open text files in external editor by default [DEFEDIT-836]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#334]
Currently the built-in text editor is missing features, many of them blockers. To get the text editor up to a level where one can work with it exclusively will take quite a lot of time, and this will make people hesitant to use the new editor.

To reduce friction during this time, it would be nice if one could configure defold to support an external text editor for text files as the default editor. Preferably one should be able to configure the command-line to those editors so that one can go directly to specific line numbers.

Something like this:

External text editor: [/Applications/Sublime Text 3    ]
Arguments: [$FILE:$LINE         ]

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.95</td></tr>
<tr><td>Defold sha</td><td>c9fa4c639b8ef10e69b355683dcda63acc595287</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.1</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Malmer** [comment]
Since at least atom and sublime support the filename.txt:30 format for going to a specific line in a file it may simply be enough with a checkbox that says "supports line numbers".

**Comment by Malmer** [comment]
Personally I view this as one of the quickest wins in terms of reducing pain points in using Defold 2. Until the day comes when the built in text editor is better due to the added integration it will always be a frustration to use. 

I think that the built in text editor needs to make me want to use it, rather than forcing me to use it. As a user I always want to use the best tool for the job. Editing collections and game objects is without question most easily done in the editor. Same goes for most things in defold. But editing scripts is not currently best done inside the editor.

Adding this feature would make using Defold 2 be much more enjoyable until that day comes when the built in text editor is good enough.

**Comment by dapetcu21** [comment]
I support this. As a heavy Atom user (with weird stuff like vim-mode), not being able to open scripts by default in an external editor is pretty much preventing me from using and testing Editor 2, as this particular thing completely breaks my workflow.

**Comment by Malmer** [comment]
BLOCKER, until the built in text editor is improved
