### ISSUE TITLE
Editor deletes content on synchronize / save

### ISSUE THREAD

**Issue by davidwolters** [defold/editor2-issues#335]
Whilst I was saving and synchronizing my content, everything looked fine, but then when I opened up the computer later, I found that files I had not touched throughout the entire day, were altered and a lot of data was removed.

Computer specs: 
MacBook Pro (Retina, 15-inch, Mid 2015)
16 GB Ram
i7 Processor
macOS Sierra

**Comment by RagnarSvenssonKing** [comment]
Could you decribe this issue in more detail? Has it happened many times? What data was lost and how were the files altered?

**Comment by matgis-king** [comment]
Note that the new editor will update every file in the project when you save, so the first time you open an old project and save in the new editor, a lot of files you might not have touched might be updated to the most recent file format. That said, there was an issue we fixed recently that caused the order of components inside game objects to sometimes vary between saves. That could explain why you were seeing changes to files you did not touch.

There was also a bug fixed recently that could cause newly added files to be lost if there was a particular kind of conflict with the server when syncing. Does that sound like what happened to you?

The fixes I mentioned should be in editor builds produced after the 6th of January.

**Comment by matgis-king** [comment]
We've not had any reports of this sort of thing happening after our sync fixes. Closing this for now.
