### ISSUE TITLE
Error whilst opening text file

### ISSUE THREAD

**Issue by sandcoder** [defold/editor2-issues#336]
I created a text file with the terminal in my defold project, and when i tried to open/edit it with the new editor, I got the following stacktrace in an alert box: (Defold 2)

`{:cause
 "Assert failed: Attempting to select nil values\n(every? some? node-ids)",
 :via
 [{:type java.lang.AssertionError,
   :message
   "Assert failed: Attempting to select nil values\n(every? some? node-ids)",
   :at [editor.app_view$select invokeStatic "app_view.clj" 451]}],
 :trace
 [[editor.app_view$select invokeStatic "app_view.clj" 451]
  [editor.app_view$select_BANG_ invokeStatic "app_view.clj" 474]
  [editor.app_view$select_BANG_ invoke "app_view.clj" 474]
  [editor.app_view$select_BANG_ invokeStatic "app_view.clj" 476]
  [editor.app_view$open_resource invokeStatic "app_view.clj" 597]
  [editor.app_view$open_resource invoke "app_view.clj" 578]
  [editor.app_view$open_resource invokeStatic "app_view.clj" 580]
  [editor.app_view$fn__23771$fnk23765_positional__23772 invoke "app_view.clj" 619]
  [editor.app_view$fn__23771$fnk23765__23789$fn__23790 invoke "app_view.clj" 615]
  [editor.app_view$fn__23771$fnk23765__23789 invoke "app_view.clj" 615]
  [clojure.lang.AFn applyToHelper "AFn.java" 154]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.lang.AFunction$1 doInvoke "AFunction.java" 29]
  [clojure.lang.RestFn invoke "RestFn.java" 408]
  [editor.handler$invoke_fnk invokeStatic "handler.clj" 47]
  [editor.handler$run invokeStatic "handler.clj" 65]
  [editor.ui$run_command invokeStatic "ui.clj" 849]
  [editor.ui$bind_double_click_BANG_$reify__10361 handle "ui.clj" 877]
  [com.sun.javafx.event.CompositeEventHandler$NormalEventFilterRecord handleCapturingEvent "CompositeEventHandler.java" 282]
  [com.sun.javafx.event.CompositeEventHandler dispatchCapturingEvent "CompositeEventHandler.java" 98]
  [com.sun.javafx.event.EventHandlerManager dispatchCapturingEvent "EventHandlerManager.java" 223]
  [com.sun.javafx.event.EventHandlerManager dispatchCapturingEvent "EventHandlerManager.java" 180]
  [com.sun.javafx.event.CompositeEventDispatcher dispatchCapturingEvent "CompositeEventDispatcher.java" 43]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 52]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.BasicEventDispatcher dispatchEvent "BasicEventDispatcher.java" 56]
  [com.sun.javafx.event.EventDispatchChainImpl dispatchEvent "EventDispatchChainImpl.java" 114]
  [com.sun.javafx.event.EventUtil fireEventImpl "EventUtil.java" 74]
  [com.sun.javafx.event.EventUtil fireEvent "EventUtil.java" 54]
  [javafx.event.Event fireEvent "Event.java" 198]
  [javafx.scene.Scene$ClickGenerator postProcess "Scene.java" 3470]
  [javafx.scene.Scene$ClickGenerator access$8100 "Scene.java" 3398]
  [javafx.scene.Scene$MouseHandler process "Scene.java" 3766]
  [javafx.scene.Scene$MouseHandler access$1500 "Scene.java" 3485]
  [javafx.scene.Scene impl_processMouseEvent "Scene.java" 1762]
  [javafx.scene.Scene$ScenePeerListener mouseEvent "Scene.java" 2494]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 380]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification run "GlassViewEventHandler.java" 294]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler lambda$handleMouseEvent$354 "GlassViewEventHandler.java" 416]
  [com.sun.javafx.tk.quantum.QuantumToolkit runWithoutRenderLock "QuantumToolkit.java" 389]
  [com.sun.javafx.tk.quantum.GlassViewEventHandler handleMouseEvent "GlassViewEventHandler.java" 415]
  [com.sun.glass.ui.View handleMouseEvent "View.java" 555]
  [com.sun.glass.ui.View notifyMouse "View.java" 937]]}
`

**Comment by RagnarSvenssonKing** [comment]
Will be fixed as part of DEFEDIT-614

**Comment by ragnard-king** [comment]
Fixed by defold/defold#1158
