### ISSUE TITLE
Changed git remote repo and error dialog appeared

### ISSUE THREAD

**Issue by linusc-king** [defold/editor2-issues#338]
### Actual behaviour
A dialog displaying this:
"
An error occurred:
java.lang.NullPointerException: Unknown
"

### Steps to reproduce
Checkout a amazon project during editor startup then switch to another remote repo from shell. Go back to editor and you might get this error.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>35b51f4172ded43b2c860ae1ab5f5756daf3770d</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=9aff363077d64fd8bce6130f09c7535b'>9aff363077d64fd8bce6130f09c7535b</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Did it work if you restarted the app?

**Comment by linusc-king** [comment]
Yes, it worked as expected then.

**Comment by erikangelin-king** [comment]
Closing as can't repro.
