### ISSUE TITLE
Floats are presented in different precision between ED1 and ED2.

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#344]
STR:

Set the X rotation of a GO to 45 and hit enter. See screens below for results.

![screen shot 2016-12-16 at 10 27 01](https://cloud.githubusercontent.com/assets/65613/21257798/35b6195c-c37a-11e6-8b40-511bb79130f7.png)

![screen shot 2016-12-16 at 10 26 44](https://cloud.githubusercontent.com/assets/65613/21257804/41ca4268-c37a-11e6-8aac-65f5b6f38105.png)

**Comment by erikangelin-king** [comment]
Quick-win if caused by quaternion roundtrip, math-utils/round-with-precision.

**Comment by Malmer** [comment]
BLOCKER

**Comment by RagnarSvenssonKing** [comment]
Fixed!
