### ISSUE TITLE
Dragging a script file from the Asset view to a GO in the Outline gives null pointer exception.

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#345]
### Expected behaviour

The script would be added as a component to the GO (if in-place).

### Actual behaviour

Null pointer exception.

### Steps to reproduce

Drag a script file from the Asset view to a GO in the Outline 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f6271550bf9fdbe0bd959dce1af41dcbbf908ffb</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.1</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=5e6ab69a0c47405d9dc37aa837710538'>5e6ab69a0c47405d9dc37aa837710538</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Quick-win if disable feature properly. Nice future feature though.

**Comment by ragnard-king** [comment]
The NPE has been fixed, better drag and drop is tracked by #408
