### ISSUE TITLE
Scene view does not automatically update after external change 

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#346]
### Expected behaviour

Scene view is updated immediately.

### Actual behaviour

Scene view does not update until it is interacted with, for example by moving the cursor.

### Steps to reproduce

1. Open a collection with a game object in scene view.
2. Modify game object in external editor, for example changing position.
3. Switch back to editor

<hr/>

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_101-b13</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can't repro
