### ISSUE TITLE
Find Prev with no search term moves cursor right

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#347]
### Expected behaviour

Nothing should happen if there is no search term.

### Actual behaviour

Cursor moves one position right.

### Steps to reproduce

1. Move cursor somewhere
2. Hit ⌘ + F then Enter (with no search term)
3. Hit Shift + ⌘ + G

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f6271550bf9fdbe0bd959dce1af41dcbbf908ffb</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.1</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
obsolete
