### ISSUE TITLE
Division by zero if keyboard navigating with no view selected [DEFEDIT-734]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#349]
### Expected behaviour

Nothing

### Actual behaviour

Division by zero exception

### Steps to reproduce

1. Open a project
2. Click the blank center to move focus off Assets view
3. Press up or down.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>35b51f4172ded43b2c860ae1ab5f5756daf3770d</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.1</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=13a3fe0eda5e41bfa6e7c3ca81c41662'>13a3fe0eda5e41bfa6e7c3ca81c41662</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Looks like this bug: https://bugs.openjdk.java.net/browse/JDK-8167282

**Comment by ragnard-king** [comment]
Fixed.
