### ISSUE TITLE
Embedded GUI components has duplicate folders in outline

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#35]
### To reproduce

Create a GO, add an embedded GUI component. 

Textures, Fonts, Layers and Layouts folders occur twice.

![image](https://cloud.githubusercontent.com/assets/20399970/18081270/4a696c3e-6e91-11e6-8fd9-32ea8c92968a.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed, gui components should not be possible to embed at all

**Comment by sicher** [comment]
Curious, what is the reason for that?

**Comment by RagnarSvenssonKing** [comment]
Compatibility with editor1, after we switch it could be a feature.

**Comment by sicher** [comment]
Perfect! :)
