### ISSUE TITLE
Collapse/Expand all button in hierarchy file/gameobject structure

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#350]
Requested on forum:
https://forum.defold.com/t/collapse-expand-all-button-in-hierarchy-file-gameobject-structure/3684

It would be really nice to have an option when in a hierarchy structure such as either the file view, or the outline view to be able to right-click on any object in the tree, and get options like "Expand all children" / "Collapse all children", if you want to edit sub categories of many objects, for example consider the following hierarchy structure:

-- Thing 1 (GameObject)
------ SubThing 1 (GameObject)
---------- Element1OfThing2 (GameObject)
-------------- Script I want to edit
-- Thing 2 (GameObject)
------ SubThing 2 (GameObject)
---------- Element1OfThing2 (GameObject)
-------------- Script I want to edit
-- Thing 2 (GameObject)
------ SubThing 2 (GameObject)
---------- Element1OfThing2 (GameObject)
-------------- Script I want to edit

If we have many objects like this, it can be quite messy to have to expand and collapse all of them all the time, so a function that would expand all children / collapse all children would be really usefull here.

**Comment by amel** [comment]
@erikangelin-king Will this feature be implemented anytime soon?

**Comment by matgis-king** [comment]
You can now expand / collapse all by Alt-clicking the disclosure triangle.
