### ISSUE TITLE
Find-replace in file is practically unusable. Needs redesign. [DEFEDIT-668]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#357]
There is no "Find next", no "Replace all". And the replace next hotkey (no button!) just replaces the next one with no option to skip it. And it never remembers what you searched for last. As it is now it is unusable in any real world scenario.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f1d1c4a7d1cd292bc2a3042f3e0060cf02036621</td></tr>
<tr><td>Build time</td><td>2016-12-19T19:31:07.150771</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-668

**Comment by erikangelin-king** [comment]
Simple find/replace bars merged!
