### ISSUE TITLE
Editor incompatibility, broken save for gui with spine node [DEFEDIT-667]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#358]
Backward compatibility between editor1 and editor2. 
1. Edit something in project in editor2.
2. Open project in editor1

All GUI with spine node with error:
Could not generate bone nodes from invalid spine scene: 	level_win_popup.gui

In text file compare it's looks like removing part of file. :
![2016-12-22_00-18-29](https://cloud.githubusercontent.com/assets/2209596/21406348/316195b4-c7dc-11e6-860a-c48cdd81da8a.png)

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-667

**Comment by ragnard-king** [comment]
Fixed.
