### ISSUE TITLE
Can't add images to animation group - an error occured [DEFEDIT-666]

### ISSUE THREAD

**Issue by saracglaser** [defold/editor2-issues#359]
Steps to reproduce
Open an atlas, create animation group, select add images to animations group -> error occurred.

Error:
clojure.lang.ExceptionInfo: handler ':add-from-file' in context ':workbench' failed at ':run' with message 'Wrong number of args (4) passed to: atlas/add-images-handler'
clojure.lang.ArityException: Wrong number of args (4) passed to: atlas/add-images-handler

Recording: https://dl.dropboxusercontent.com/u/9747966/Ed2_add-images-animation-group.mov

### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>7337afc099b03932e2a3f8a0bd441454d4a2e8a7</td></tr>
<tr><td>Build time</td><td>2016-12-21T15:15:06.158558</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=bc9f865fb6b94727b1536e162ff80ce0'>bc9f865fb6b94727b1536e162ff80ce0</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-666

**Comment by RagnarSvenssonKing** [comment]
Fixed
