### ISSUE TITLE
Where I change scene and console size - create error [DEFEDIT-665]

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#361]
### Expected behaviour
Change scene size and console
### Actual behaviour
Change scene size make error and scene disappeared
### Steps to reproduce
Change size of console - first small, second big

BTW, in version 1.2.95 error present, but crush window not show, but scene disappered in silence :)
BTW2, scene disappered if change size with sny panels

Log
java.lang.RuntimeException: java.util.concurrent.ExecutionException: com.jogamp.opengl.GLException: pool-3-thread-1: Context not current on thread, inDestruction: false, obj 0x6f4c9c0b, ctx 0x10002, isShared false, surf true 0x1010e0f, <1033d560, 445ca989>[count 1, qsz 0, owner <JavaFX Application Thread>]
java.util.concurrent.ExecutionException: com.jogamp.opengl.GLException: pool-3-thread-1: Context not current on thread, inDestruction: false, obj 0x6f4c9c0b, ctx 0x10002, isShared false, surf true 0x1010e0f, <1033d560, 445ca989>[count 1, qsz 0, owner <JavaFX Application Thread>]
com.jogamp.opengl.GLException: pool-3-thread-1: Context not current on thread, inDestruction: false, obj 0x6f4c9c0b, ctx 0x10002, isShared false, surf true 0x1010e0f, <1033d560, 445ca989>[count 1, qsz 0, owner <JavaFX Application Thread>]

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>7337afc099b03932e2a3f8a0bd441454d4a2e8a7</td></tr>
<tr><td>Build time</td><td>2016-12-21T15:15:06.158558</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-665

**Comment by erikangelin-king** [comment]
Fixed
