### ISSUE TITLE
Child components translate in unexpected way while attached to a rotated parent in ParticleFX editor [DEFEDIT-490]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#362]
Create a particlefx object, add emitter, rotate the emitter, add a modifier, attempt to translate the modifier. The translation is not corrected for parent rotation.

Editor 1 had this behavior too but it still seems wrong.

**Comment by RagnarSvenssonKing** [comment]
Internal note: the issue is that the manipulator is drawn in world space, but its effect will be applied in local space.

**Comment by matgis-king** [comment]
Likely related to #379?
