### ISSUE TITLE
Open files bar sometimes is buggy when using "Close Others"

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#364]
Images show sometimes what can happen. Most of the time this has happened when I had several other files open before clicking "Close Others" on one.

![2016-12-27 00_48_11-defold editor 2 0 - my project](https://cloud.githubusercontent.com/assets/409170/21495731/3ac73c4e-cbce-11e6-8f62-20fc48a85f93.png)
![2016-12-27 00_48_01-defold editor 2 0 - my project](https://cloud.githubusercontent.com/assets/409170/21495732/3ad832d8-cbce-11e6-8798-40d4a266a8fc.png)
![2016-12-27 00_48_17-defold editor 2 0 - my project](https://cloud.githubusercontent.com/assets/409170/21495733/3ae7743c-cbce-11e6-822b-43531cd18824.png)

**Comment by britzl** [comment]
I get a crash as well when clicking on the area left of the tab.

**Comment by ragnard-king** [comment]
Fix merged, available in update.
