### ISSUE TITLE
Disabled fields have no visible indication of being disabled [DEFEDIT-745]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#367]
See: Static collision type selected, mass is disabled (which it should be) but doesn't show indication it is not editable

**Comment by rawbert** [comment]
I've added a solution for this issue in this commit https://github.com/defold/defold/pull/1218/commits/f3f3033d35f45fbb507fc960d89cff1b161413a8

**Comment by ragnard-king** [comment]
Fixed, disabled fields now have a visual indication that they are not editable.
