### ISSUE TITLE
Opening unassigned resource reference fails in form view

### ISSUE THREAD

**Issue by ragnard** [defold/editor2-issues#368]
### Expected behaviour

Nothing happens.

### Actual behaviour

Exception.

### Steps to reproduce

1. Create a new form edited resource with a reference to another resource (for example a .render)
2. Click on arrow.
 
<hr/>

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>Build time</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_101-b13</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c550d995ee6849c791b2e7dd533d9be2'>c550d995ee6849c791b2e7dd533d9be2</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Can no longer repro, closing.
