### ISSUE TITLE
Cannot build project after setting custom render [DEFEDIT-744]

### ISSUE THREAD

**Issue by ragnard** [defold/editor2-issues#369]
### Expected behaviour

Game builds and runs.

### Actual behaviour

Exception.

### Steps to reproduce

1. Create a new .render
2. Assign a .render_script
3. Select new .render resource as render in game.project 
3. Build and run.

<hr/>

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>Build time</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_101-b13</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a3f44c23093a415183fc5b3663d34fb1'>a3f44c23093a415183fc5b3663d34fb1</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Re-tested, works as expected.
