### ISSUE TITLE
Editor crashes when I select in a specific GUI scene [DEFEDIT-664]

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#370]
### Expected behaviour
Dragging with the mouse in the scene should start creating a selection box.

### Actual behaviour
The editor crashes. This only happens for this particular scene.

### Steps to reproduce
1. Load the `dialogue.gui` scene.
2. Try to drag

I'll attach my scene here along with the font I used.

[Archive.zip](https://github.com/defold/editor2-issues/files/680553/Archive.zip)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>7337afc099b03932e2a3f8a0bd441454d4a2e8a7</td></tr>
<tr><td>Build time</td><td>2016-12-21T15:14:51.922121</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by dapetcu21** [comment]
Here's a crash log: https://gist.github.com/dapetcu21/1db24b86915f027346afc05ea7de1546

**Comment by RagnarSvenssonKing** [comment]
Filed as DEFEDIT-664

**Comment by matgis-king** [comment]
A fix has been merged into the dev branch. Thanks for setting up a test scene - it helped a lot!
