### ISSUE TITLE
Scene editor doesn't render font when it has outline

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#371]
### Expected behaviour
The font body should be rendered, as well as the outline.

### Actual behaviour
The outline of the font is rendered, but the font itself is not. This happens
in all scenes where that font is rendered and in the font editor.

If I set the outline alpha to 0.0 in the font file, the font gets correctly rendered.

![screen shot 2017-01-02 at 10 49 06](https://cloud.githubusercontent.com/assets/428060/21586448/bffb9c10-d0d9-11e6-92f2-79fded902c30.png)
![screen shot 2017-01-02 at 10 52 38](https://cloud.githubusercontent.com/assets/428060/21586446/bfcd7e5c-d0d9-11e6-97ad-6feea9bd4d3a.png)
![screen shot 2017-01-02 at 10 49 16](https://cloud.githubusercontent.com/assets/428060/21586447/bffb3202-d0d9-11e6-97bc-2bcd605cd828.png)

### Steps to reproduce

Open this font file:

[Archive.zip](https://github.com/defold/editor2-issues/files/680571/Archive.zip)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>7337afc099b03932e2a3f8a0bd441454d4a2e8a7</td></tr>
<tr><td>Build time</td><td>2016-12-21T15:14:51.922121</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
Fixed with defold/defold#1665!
