### ISSUE TITLE
Java error report

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#372]
No idea why and what, but I did just delete a .lua file right before getting the error.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>7337afc099b03932e2a3f8a0bd441454d4a2e8a7</td></tr>
<tr><td>Build time</td><td>2016-12-21T15:15:06.158558</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=21b774ba6e914915818c1ef1ba7c9d0e'>21b774ba6e914915818c1ef1ba7c9d0e</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Should be fixed now.
