### ISSUE TITLE
NullPointerException when returning to the editor after hard git reset from the command line

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#374]
### Steps to reproduce
1. Opened a large project created using an older version of the editor.
2. Save the project. Some older file formats will be updates and appear in the **Changed Files** view.
3. From the command-line in the project directory, ran `rm -rf *` followed by `git reset --hard HEAD` to remove local changes from the working directory.
4. Returned to the editor.

### Expected behaviour
The **Changed Files** view is cleared, since there are no longer any local changes.

### Actual behaviour
A `NullPointerException` was thrown.

<hr/>

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>Build time</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=1b4b5665cae94a1ea774c8335b2d160b'>1b4b5665cae94a1ea774c8335b2d160b</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Probably fixed
