### ISSUE TITLE
Consider using the more user friendly error message in the Properties panel

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#387]
Consider using the more user friendly error message in the Properties panel.

For example, if an .atlas file is no longer available, the Default animation field of the Sprite component will show an "ugly" error  (internal.graph.error.....) and on mouse hover, the more user friendly error (the file "X.atlas" could not be found). Consider using the more user friendly as the default error message, and use the more technical error on mouse hover or click

![error](https://cloud.githubusercontent.com/assets/23701955/21892868/75a51faa-d8e1-11e6-8512-b6700f7d351e.png)

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
