### ISSUE TITLE
Some fields are missing from the game.project in editor 2 when compared to editor 1 [DEFEDIT-743]

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#391]
The suer can notice that, when going from editor 1 to editor 2, some fields are missing from the game.project file in the editor. Those fields are: gui , collection,  iap, label and tracking

Open any project in editor 1 and 2 and look at the game.project file. Notice the differences between 1 and 2, some fields are missing in Editor 2

![image](https://cloud.githubusercontent.com/assets/23701955/21895404/476801c0-d8eb-11e6-8445-7f1c3dc1058e.png)

![image](https://cloud.githubusercontent.com/assets/23701955/21895416/589d5d14-d8eb-11e6-8cf4-0c857e66ca88.png)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed, will land in update shortly.
