### ISSUE TITLE
Pushed files are still showing in Changed files are push

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#394]
1. Added hero.json and hero.spincescene
2. Saved
3. Pull and pushed these two files

Actual result:
hero.json and hero.spincescene are still showing in the changed files section. Now with a triangle icon instead of the + icon which they had before the sync

My git status is your branch is up to date. And there is no stash.

![image](https://cloud.githubusercontent.com/assets/22887289/21922587/bafe1f1e-d96f-11e6-83ec-bbc2406b638f.png)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
@sofiahe I'm unable to reproduce this on Windows from the dev branch as of 2017-01-27. If you're able to reproduce it, it would be helpful to know what the Diff View shows for these files.

**Comment by ragnard-king** [comment]
Can't repro.
