### ISSUE TITLE
Error when renaming game object in assets

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#395]
### Steps to reproduce
1. Add a new game object
2. Dont make any changes
3. Right click on the game object in the assets section select rename
3. Rename it

Actual result:
Error 
clojure.lang.ExceptionInfo: handler ':rename' in context ':asset-browser' failed at ':run' with message 'Failed to delete original file 'C:\Users\sofia.hedlund\DefoldTutorial1Editor2_v3\hero\her.go' after copy to 'C:\Users\sofia.hedlund\DefoldTutorial1Editor2_v3\hero\hero.go''
java.io.IOException: Failed to delete original file 'C:\Users\sofia.hedlund\DefoldTutorial1Editor2_v3\hero\her.go' after copy to 'C:\Users\sofia.hedlund\DefoldTutorial1Editor2_v3\hero\hero.go'

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c942ac9f228a46a69c6afdce574e6a49'>c942ac9f228a46a69c6afdce574e6a49</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed, will be available in update shortly.
