### ISSUE TITLE
Selected asset changes if you cancel a delete option

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#396]
1. Right click on an asset 
2. Select delete
3. Select cancel

Actual result:
The marked asset changes to the asset underneath the one used.
![canceldelete2](https://cloud.githubusercontent.com/assets/22887289/21922837/f009de22-d970-11e6-8dea-00ac6121cf71.gif)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed, will be available in update shortly.
