### ISSUE TITLE
Allow the user to create multiple untitled files of the same type

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#398]
The user currently cannot create a new untitled file, if a file with the name "untitled" already exist in the same folder. See the attached GIF.

![untitled files](https://cloud.githubusercontent.com/assets/23701955/21923874/232bd54a-d97f-11e6-8b4c-15ab72bdfcc1.gif)

Consider allowing the user to create a new file with the name similar to untitled(2). Currently, no new untitled file is not created.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>e6b3e14db1c069651d410877ca5e07596bcc4edc</td></tr>
<tr><td>Build time</td><td>2017-01-11T10:00:14.875260</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed at some point :)
