### ISSUE TITLE
Adding corrupted / damaged image files to atlas file leads to infinite error pop-ups

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#399]
It can be noticed that, if the user adds damaged / corrupted image files (tested with .png and .jpg files) to an atlas, infinite error pop-ups will show up.

### Steps to reproduce
1. Corrupt or damage a .jpg or .png file (the easiest way is to open the image file with a text editor and delete sole lines from it)
2. Add the images to a project
3. Create a new atlas file and add the damaged files to the atlas

Notice the infinite error pop-ups that appear.
![endless errors](https://cloud.githubusercontent.com/assets/23701955/21930452/d2612726-d99e-11e6-80dd-44e8a92857cd.gif)

![endless errors jpg](https://cloud.githubusercontent.com/assets/23701955/21930460/d54a0a16-d99e-11e6-853b-ad0be4494644.gif)

Unfortunately, I cannot add the damaged files I've created for testing, even as a .zip archive.

Errors:
javax.imageio.IIOException: Error skipping PNG metadata
java.io.EOFException: Unknownjavax.imageio.IIOException: Error skipping PNG metadata
java.io.EOFException: Unknown

clojure.lang.ExceptionInfo: handler ':scene-play' in context ':global' failed at ':enabled?' with message 'Error skipping PNG metadata'
javax.imageio.IIOException: Error skipping PNG metadata
java.io.EOFException: Unknown

User cannot exit the app once the error pop-ups appear. The app needs to be killed from the Task manager.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>64f26e1b232bd1438987411c15d236ba4ae046a5</td></tr>
<tr><td>Build time</td><td>2017-01-13T13:12:51.249246</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed.
