### ISSUE TITLE
Delay in menu bar appearing after Cmd-Tabbing back to app prevents build [DEFEDIT-701]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#403]
### Expected behaviour
When Cmd-Tabbing back to app the menu bar should appear instantly so that hot key such as Cmd+B works.

### Actual behaviour
It takes roughly 10-20 seconds before the menu bar appears and hot keys are working again.

### Steps to reproduce
Cmd-Tab to other window
Cmd-Tab back
Press Cmd-B

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>a9aa2bfab7870118f82b7c998aaca7258b5bd706</td></tr>
<tr><td>Build time</td><td>2017-01-16T10:11:42.500246</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
A fix has been merged and will be available as an update shortly.
