### ISSUE TITLE
Unable to reassign shaders in material [DEFEDIT-702]

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#404]
1. Open a `.material` file.
2. Browse for a new Vertex Program.
3. Select a different `.vp` file in the file picker and click OK.

The Vertex Program field still refers to the old `.vp` file.

**Comment by Malmer** [comment]
BLOCKER

**Comment by erikangelin-king** [comment]
This is fixed. We're still working on the schema-validation issue when writing in resource fields, but browsing should work.
