### ISSUE TITLE
Error when json draged from finder to folder in Assets

### ISSUE THREAD

**Issue by saracglaser** [defold/editor2-issues#405]
Draged json file from finder to folder under assets.
Error message:
java.lang.NullPointerException:Unknown

![screen shot 2017-01-17 at 15 32 17]
(https://cloud.githubusercontent.com/assets/10513220/22024447/5173c5ae-dcca-11e6-92db-56f66a9d59a7.png)

### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>fd59a3c30ebc45c12dc376a942c8644e258f2f41</td></tr>
<tr><td>Build time</td><td>2017-01-16T14:59:29.789965</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2f723a4ce1ed4aec8edff7fe95066e27'>2f723a4ce1ed4aec8edff7fe95066e27</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Error actually happens when dragging a json file over the **outline** view.

**Comment by ragnard-king** [comment]
Fix has been merged, coming in update shortly.
