### ISSUE TITLE
deleted default renderer in game.project settings

### ISSUE THREAD

**Issue by CoCopia** [defold/editor2-issues#406]
### Expected behaviour
As editor 1, slotted in default renderer
### Actual behaviour
failure
### Steps to reproduce
delete the render setting in game.project and hit enter
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>fd59a3c30ebc45c12dc376a942c8644e258f2f41</td></tr>
<tr><td>Build time</td><td>2017-01-16T14:59:29.789965</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=852504f5fe314b3091854ab86c0821e6'>852504f5fe314b3091854ab86c0821e6</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Thanks for the report @CoCopia!

The bug is not specific to the render setting, but hitting enter on many resource fields fails.

**Comment by erikangelin-king** [comment]
Fixed
