### ISSUE TITLE
Ability to drag game objects to url go.property()

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#409]
It should be possible to drag a game object in a collection to a url go.property() in an script component. The field would be filled in.

For this to work it would require a component selection change to happen on mouse up rather than mouse down as it is now.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>4c2987e5ddd679779902051003fd919df33b3364</td></tr>
<tr><td>Build time</td><td>2017-01-18T13:54:15.761598</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
#408
