### ISSUE TITLE
Concurrent modification of graph when syncing [DEFEDIT-714]

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#413]
1. Created new project in dashboard
2. Imported it
3. Deleted logo.png
4. Deleted logo.atlas
5. Saved
6. Sync

Actual result:
Concurrent modification of graph when syncing 
![screen shot 349](https://cloud.githubusercontent.com/assets/22887289/22154589/6719b846-df2c-11e6-94ec-e72d406adb05.PNG)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>4c2987e5ddd679779902051003fd919df33b3364</td></tr>
<tr><td>Build time</td><td>2017-01-18T13:54:15.761598</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=94133e636b004a809c138f5dd12dc78a'>94133e636b004a809c138f5dd12dc78a</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
