### ISSUE TITLE
java.lang.AssertionError: Assert failed: source-node-id when using Dirtylarry library

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#414]
1. Add https://github.com/andsve/dirtylarry/archive/master.zip to your dependencies
2. Fetch library
3. Click any of the assets

Actual result:
java.lang.AssertionError: Assert failed: source-node-id
Cant use the dirty larry assets

If you restart the editor the dependencie works.

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>55657d37cb8804da80acd35c1d89659c9e46510d</td></tr>
<tr><td>Build time</td><td>2017-01-23T13:46:53.351029</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d5a441c17c1a492ea9627f9f93a506ec'>d5a441c17c1a492ea9627f9f93a506ec</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged and available in latest update.
