### ISSUE TITLE
Target device is shown dubbel if dmengine is restarted when selected in editor

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#416]
1. Select a device as target
2. On device, restart dmengine
3. Check targets again

Actual result:
The device is now shown two time, one selected and one not selected.

![screen shot 357](https://cloud.githubusercontent.com/assets/22887289/22243406/78da70a4-e227-11e6-86d2-ee7f081b6c6d.PNG)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>6adb0f1ceea31b5fe5ea874aaab410c3ef14f8db</td></tr>
<tr><td>Build time</td><td>2017-01-24T10:59:35.304170</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@ragnarsvensson this is fixed right?

**Comment by RagnarSvenssonKing** [comment]
Yes!
