### ISSUE TITLE
Find-in-file options are not remembered across sessions [DEFEDIT-1232]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#417]
Primarily it becomes tedious to always have to check the "wrap" option that really should be checked by default. 

But the other settings should be remembered aswell.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>6adb0f1ceea31b5fe5ea874aaab410c3ef14f8db</td></tr>
<tr><td>Build time</td><td>2017-01-24T10:59:35.304170</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Malmer** [comment]
Is the ability to disable the wrap option even necessary? When do you not want it enabled?

**Comment by ragnard-king** [comment]
change default

**Comment by saracglaser** [comment]
DEFEDIT-1223

**Comment by erikangelin-king** [comment]
... Also DEFEDIT-1232 because I couldn't find 1223 :)
