### ISSUE TITLE
Changed files are not shown in changed files if not saved before sync

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#420]
1. Open a script file
2. Modify the script file
3. Dont save
4. Select synchronise
5. Click Pull
6. Click Push

Actual result:
The modified script file is shown in the stage window but not in changed file section.
If you press cancel the file will be shown in the changed section.

![image](https://cloud.githubusercontent.com/assets/22887289/22250346/d86d6afc-e246-11e6-8aa6-371542daf47f.png)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>6adb0f1ceea31b5fe5ea874aaab410c3ef14f8db</td></tr>
<tr><td>Build time</td><td>2017-01-24T10:59:35.304170</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by AGulev** [comment]
Can't reproduce 1.2.144
