### ISSUE TITLE
No way to lock scrolling of console window

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#421]
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>6adb0f1ceea31b5fe5ea874aaab410c3ef14f8db</td></tr>
<tr><td>Build time</td><td>2017-01-24T10:59:35.304170</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed, right?
