### ISSUE TITLE
 [DEFEDIT-717] Assert failed:  is neither a path nor a resource: nil when copying a project via windows explorer

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#422]
1. Create a new empty project
2. Go to https://github.com/britzl/publicexamples/blob/master/README.md
3. Download the full master zip and extract
4. Copy examples, images, modules, gameproject and read me to your new project via windows explorer

Actual result:
java.lang.AssertionError: Assert failed:  is neither a path nor a resource: nil
false

![image](https://cloud.githubusercontent.com/assets/22887289/22282707/74922516-e2de-11e6-9d8e-30d77556d2b2.png)

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f32230d96b986616b742218d7f1a5bce26519b2e</td></tr>
<tr><td>Build time</td><td>2017-01-24T18:27:02.669047</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a70245204fda43c79be85d5cd6aee9df'>a70245204fda43c79be85d5cd6aee9df</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Reproduced on OSX too, not platform specific.

**Comment by ragnard-king** [comment]
Fix merged and available in latest update.
