### ISSUE TITLE
Frame selection doesn't do the right thing

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#424]
### Expected behaviour
`Scene -> Camera -> Frame Selection` should center the frame on the selected object

### Actual behaviour
It frames incorrectly:

![untitled](https://cloud.githubusercontent.com/assets/428060/22283402/c3de88f6-e2ea-11e6-828c-f06baeaef83a.gif)

### Steps to reproduce
1. Select object
2. `Scene -> Camera-> Frame Selection`

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f32230d96b986616b742218d7f1a5bce26519b2e</td></tr>
<tr><td>Build time</td><td>2017-01-24T18:27:02.669047</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed in latest update.
