### ISSUE TITLE
Frame selection keybind doesn't work

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#425]
### Expected behaviour
`Cmd + .` should trigger `Scene -> Camera -> Frame selection`

### Actual behaviour
Does nothing

### Steps to reproduce
Press `Cmd + .`

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f32230d96b986616b742218d7f1a5bce26519b2e</td></tr>
<tr><td>Build time</td><td>2017-01-24T18:27:02.669047</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
quick-win if change key-binding

**Comment by ragnard-king** [comment]
Verified that "Shortcut+." accelerator does not work at all when using system menu bar on OSX. So best fix now is to pick a different key binding.

**Comment by AGulev** [comment]
I have the same bug, it's strange but it's works when I swith the keyboard language to russian.

**Comment by ragnard-king** [comment]
Frame selection is now bound to 'F', as in editor1 and should work on all platforms.
