### ISSUE TITLE
Preferences keybind doesn't work [DEFEDIT-705]

### ISSUE THREAD

**Issue by alexandru-p** [defold/editor2-issues#426]
### Expected behaviour

`Ctrl + ,` should open he preferences window.

### Actual behaviour

Does nothing

### Steps to reproduce

Press `Ctrl + ,`
<hr/>

Probably similar to https://github.com/defold/editor2-issues/issues/425
<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f32230d96b986616b742218d7f1a5bce26519b2e</td></tr>
<tr><td>Build time</td><td>2017-01-24T18:27:02.669047</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by dapetcu21** [comment]
That's probably because `Ctrl + ,` is also bound to `Scene -> Camera -> Realign`

**Comment by erikangelin-king** [comment]
Fixed, right? Please reopen otherwise!
