### ISSUE TITLE
Linux solus distro. Desktop action e.g Help > Report Issue not invoke a browser

### ISSUE THREAD

**Issue by dmignani** [defold/editor2-issues#428]
Solus 2017.01.01.0 64-bit
not invoke a browser end the editor stop working.

**Comment by ragnard-king** [comment]
Reproduced on ubuntu too. We should probably use `HostServices/showDocument` instead of `Desktop#browse`.

**Comment by erikangelin-king** [comment]
Duplicate, see https://github.com/defold/editor2-issues/issues/587
