### ISSUE TITLE
Google login mangled unicode text

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#432]
### Expected behaviour
English

### Actual behaviour
??????????
![screen shot 2017-01-25 at 21 16 16](https://cloud.githubusercontent.com/assets/428060/22305325/bdd80230-e343-11e6-875e-53ffb15693c4.png)

### Steps to reproduce
Try to sync

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>745b7940a228ab460a1d3a2a947f75f725cba839</td></tr>
<tr><td>Build time</td><td>2017-01-25T15:57:32.800241</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.2</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by saracglaser** [comment]
Had the same issue, but got correct rendering of text when resizing window.

**Comment by Moodge** [comment]
I had this issue on a Macbook Pro with the latest version of OSX but not on my Windows 10 PC

**Comment by MrPhil** [comment]
I've seen this on my Mac Book Pro with Chrome as the default browser and my MacBook (10.11.6) with  Safari as my default browser.

**Comment by ThisIsBa** [comment]
I get this too, but can't resize the window. The login won't actually work either. It just hangs after the login attempt

**Comment by ThisIsBa** [comment]
Found that the although the login still looks all messed up for me, disabling phone authentication made it work.

**Comment by andsveking** [comment]
Google might have changed their login screen, I don't remember it being this bad:
<img width="912" alt="screen shot 2017-07-25 at 10 02 15" src="https://user-images.githubusercontent.com/10498365/28561979-ce0117bc-7120-11e7-81d6-999f84c98dc3.png">

I wasn't able to find where to input the password. Thankfully the login I use has a third-party SSO page that Google forwarded me to after I entered the email address, that page looked and behaved correctly.

**Comment by sevr7gina** [comment]
the same for me - mac os siera - RU language - Defold Editor 2

![2017-08-13 9 08 17](https://user-images.githubusercontent.com/15611825/29246546-14038d5e-8007-11e7-9f4a-46c8ebe65bcb.png)
![2017-08-13 9 07 11](https://user-images.githubusercontent.com/15611825/29246547-140600d4-8007-11e7-99d1-08b0126c5b36.png)

**Comment by ragnard-king** [comment]
We've now changed the login process to use the system browser instead of the embedded one, which should resolve this issue. Available in next update within the hour.
