### ISSUE TITLE
Error when opening project

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#436]
### Expected behaviour
No error

### Actual behaviour
An error

### Steps to reproduce
It happens every time I open the project and when I build and run.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>ffaf26729d27e32af198c09343de4af8b222426d</td></tr>
<tr><td>Build time</td><td>2017-01-26T21:12:59.663339</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6d7a016673df4172a25a213f40fbe1da'>6d7a016673df4172a25a213f40fbe1da</a></td></tr>
<table>

**Comment by ragnard** [comment]
@britzl Can you share the project with me and the other peeps in the editor2 team?

**Comment by ragnard-king** [comment]
@britzl Never mind, not project-related. Fix coming shortly.

**Comment by ragnard-king** [comment]
Fix has been merged, coming in update shortly.
