### ISSUE TITLE
game.project not save params after change in form and text

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#437]
### Expected behaviour
Save game.project file with new params
### Actual behaviour
Save not change game.project file and not apply config(Form and text edit) (if i change file in other text editor params apply correctly)
### Steps to reproduce
Change width and height in form style
Press Ctrl+S
game.project not changes and params not save
<hr/>
PS: In current build i can make windows bundle for external use. Thank you for answer.
<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>f32230d96b986616b742218d7f1a5bce26519b2e</td></tr>
<tr><td>Build time</td><td>2017-01-24T18:27:02.669047</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Values are only stored if you press enter while in the field, this is a sad bug we'll fix!
Editor 2 doesn't have support for bundling yet, but you can open the same project in editor 1 and bundle from there.

**Comment by erikangelin-king** [comment]
... And opening the file as text is mostly for debugging purposes; changes made there are not saved.

**Comment by tarnumius** [comment]
Thank you for answer. I open in text for test only :) 

Yes i make bundle in editor-1, but it win32 and sometimes crushed :)
