### ISSUE TITLE
Animation group has checked flip checkboxes by default [DEFEDIT-742]

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#441]
### Expected behaviour
Checked not present on flip checkboxes by default
### Actual behaviour
Checked present on flip checkboxes by default
### Steps to reproduce
1. Create atlas
2. Add Animation group

![a1f4f-clip-7kb](https://cloud.githubusercontent.com/assets/588556/22399924/e46f6268-e5b8-11e6-89de-cd639ac1f8d5.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>9a3c683d14e3b3e375fc494e83a32523d550771b</td></tr>
<tr><td>Build time</td><td>2017-01-27T17:45:00.623594</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed, merged.
