### ISSUE TITLE
Rename file window renames to filename without extension [DEFEDIT-574]

### ISSUE THREAD

**Issue by otapliger** [defold/editor2-issues#442]
# Expected behaviour

Rename to filename.extension

# Actual behaviour

It renames to filename only

# Steps to reproduce

Right click on a file in the assets explorer and select rename
Type a new name
Press enter

# Annotations

This behaviour happens only on the first time you rename it. Furthers renames on the same file work as expected

[![Rename.bug.png](https://s27.postimg.org/houyjxhlf/Rename_bug.png)](https://postimg.org/image/xzv2g8u33/)

[![Rename.2.bug.png](https://s29.postimg.org/ybr9uyltz/Rename_2_bug.png)](https://postimg.org/image/cckv7r4zn/)

**Comment by adamwestman** [comment]
Renaming script files this way they are basically screwed

**Comment by erikangelin-king** [comment]
Should be fixed.
