### ISSUE TITLE
Camera file has wrong default FOV

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#444]
The FOV in the template is expressed in degrees:

![screen shot 2017-02-01 at 11 25 04](https://cloud.githubusercontent.com/assets/65613/22503256/3435e30c-e871-11e6-8bb0-6b96e2531fa5.png)

But the code expects radians:

![screen shot 2017-02-01 at 11 28 46](https://cloud.githubusercontent.com/assets/65613/22503365/b6a9201a-e871-11e6-9a0f-bf9a88c9841c.png)

The template should be changed to FOV: 0.785

**Comment by erikangelin-king** [comment]
Quick-win if only problem with template
