### ISSUE TITLE
Missing launch images in game.project

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#447]
### Expected behaviour
All Launch images from Editor 1 should exist in Editor 2

### Actual behaviour
I'm missing 1536x2048 (or actually it seems to be missing the label) and also 2048x2732 and 2732x2048

### Steps to reproduce
Open game.project and scroll to the iOS related settings.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>cb37d6c9796f98dd3a94e5f0e79fd3691d3f3833</td></tr>
<tr><td>Build time</td><td>2017-02-02T11:01:23.274110</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Ha, just updated the settings, must have missed these

**Comment by erikangelin-king** [comment]
Fixed, merged.
