### ISSUE TITLE
spine.* auto-complete is missing play_anim()

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#449]
### Expected behaviour
The spine auto-complete functions should show up-to-date results

### Actual behaviour
The spine.play() function has been deprecated and replaced with spine.play_anim() but the spine auto-complete still shows spine.play() and is missing spine.play_anim()

### Steps to reproduce
Create a script file and trigger auto-complete for spine

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>8e1a317594568cd3ff2fe2cff06eb09661f0475e</td></tr>
<tr><td>Build time</td><td>2017-02-02T15:06:39.724621</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Update sdoc files.

**Comment by ragnard-king** [comment]
Has been fixed.
