### ISSUE TITLE
[Windows] Resources are represented by full paths

### ISSUE THREAD

**Issue by jakob-pogulis-king** [defold/editor2-issues#45]
Downloading a fresh copy of the platformer tutorial results in a lot of errors since resources are represented by full paths in Windows rather than the basename as on Mac and Linux. The platformer tutorial runs out of the box on OS X.

![resource-urls-contains-backslashes](https://cloud.githubusercontent.com/assets/17006862/18548461/1a59d334-7b49-11e6-8db2-ec370f46ad5f.png)

![resources-use-full-path-in-atlases](https://cloud.githubusercontent.com/assets/17006862/18548464/1f1a4002-7b49-11e6-9db1-6d0853f4ebb1.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed
