### ISSUE TITLE
cmd+arrow keys not working in input fields

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#450]
### Expected behaviour
It should be possible to use cmd+arrow left/right to move to the beginning/end of an input field in the editor (for instance the Id field in Properties window). alt+left/right works though.

### Actual behaviour
cmd+left/right does nothing

### Steps to reproduce
Select a field that accepts user input, for instance one of the fields in the Properties window when a component is selected. Try to move to the beginning/end of the text in the field using cmd+left/right keys. Notice that nothing happens.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>8e1a317594568cd3ff2fe2cff06eb09661f0475e</td></tr>
<tr><td>Build time</td><td>2017-02-02T15:06:39.724621</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Arrow key movement works in vanilla JavaFX text fields, and in the preferences dialog for example, so we must be accidentally dropping that support somewhere in properties/form views.

**Comment by AGulev** [comment]
I can't reproduce in 1.2.144
