### ISSUE TITLE
Double click and drag doesn't select multiple words in the text editor

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#451]
### Expected behaviour
When double clicking on a single word in the editor it should become selected. This works as expected. When double clicking and dragging to move the cursor it should be possible to select multiple words. This works in the old editor.

### Actual behaviour
Only the last word becomes selected.

### Steps to reproduce
Open a script file and double click but don't release the mouse button. While keeping the mouse button pressed move the mouse cursor to select more text. Release the mouse button. Notice that only the last word gets selected and any additional selected text gets deselected.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>8e1a317594568cd3ff2fe2cff06eb09661f0475e</td></tr>
<tr><td>Build time</td><td>2017-02-02T15:06:39.724621</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed in new code editor
