### ISSUE TITLE
Merged to Editor 2. It crashes like this

### ISSUE THREAD

**Issue by andreas-strangequest** [defold/editor2-issues#452]
### Expected behaviour
Project should start
### Actual behaviour
java.lang.reflect.InvocationTargetException: Unknown
java.lang.reflect.InvocationTargetException: Unknown
com.google.protobuf.UninitializedMessageException: Message missing required fields: bone_index
### Steps to reproduce
Getting a crash when building project.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>4340889c8900d42a76547748946eb37e3e1270a2</td></tr>
<tr><td>Build time</td><td>2017-02-02T19:43:05.656295</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=616325f8dc2a49529060c27c6fc305c2'>616325f8dc2a49529060c27c6fc305c2</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Hi @andreas-strangequest!

Thanks for the report. Any chance you could share a small reproducing project (privately) with us? If not I completely understand. The error happens when we for some reason we produce incorrect build data for a spine scene. I'll have a look at the code to see how we could be failing to emit bone_index.

**Comment by ragnard-king** [comment]
After a quick glance, it would seem like this error could happen if there's an animation that refers to a bone that doesn't exist (a situation we should definitely handle better). Is this something that you could verify?

**Comment by andreas-strangequest** [comment]
Hi.
Yes. The problem was that one bone was renamed and that crashed it all.
Editor 1 had a better error message for this which helped me out. Forgot to update the issue ticket.

Thanks!



[cid:image001.png@01D28138.355D62F0]

Andreas Jirenius
Strange Quest AB
+46 (0)72 317 4317
andreas@strangequest.com<mailto:andreas@strangequest.com>

**Comment by ragnard-king** [comment]
Ok, thanks for the update. Will create a separate issue for improving error handling/reporting when building spine scenes in particular.
