### ISSUE TITLE
Opening a collection

### ISSUE THREAD

**Issue by CoCopia** [defold/editor2-issues#454]
### Expected behaviour
collection to opening in editor
### Actual behaviour
unable to open collection or dismiss error
### Steps to reproduce
open a collection by double clicking
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>7b1ef0ea3669f4bdc49072998d6275b24069f522</td></tr>
<tr><td>Build time</td><td>2017-02-03T15:56:17.987577</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c027185b8d8d496eb9964da2e2f60d00'>c027185b8d8d496eb9964da2e2f60d00</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Same root cause as https://github.com/defold/editor2-issues/issues/455

**Comment by erikangelin-king** [comment]
glGenBuffers...
