### ISSUE TITLE
Opening a .gui file

### ISSUE THREAD

**Issue by CoCopia** [defold/editor2-issues#455]
### Expected behaviour
openin in editor
### Actual behaviour
failed to open, cant dismiss error window
### Steps to reproduce
double click a gui file
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>7b1ef0ea3669f4bdc49072998d6275b24069f522</td></tr>
<tr><td>Build time</td><td>2017-02-03T15:56:17.987577</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d30c9dc187b64cb68d0ad5e9982dd29f'>d30c9dc187b64cb68d0ad5e9982dd29f</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Hi @CoCopia, 

Thanks for the report! The error we are seeing is "Method "glGenBuffers" not available" which indicates that this might be a problem with your OpenGL driver. It's likely falling back to an ancient software-based driver that is part of Windows. Can you try installing/updating your OpenGL driver?

**Comment by RagnarSvenssonKing** [comment]
Fixed previously as better error message indicating user to upgrade driver.
