### ISSUE TITLE
feature request - mid click panning in editor

### ISSUE THREAD

**Issue by blurymind** [defold/editor2-issues#456]
I think that panning in Defold is counter intuitive (ctrl+alt+left click). There is no other game engine or editor using that combination of keys.

example:
http://forum.defold.com/t/how-can-i-pan-move-the-camera-in-the-editor/1051/7

Right now mid click drag is not assigned to anything. Why not make it one of the ways you pan the 2d camera? No need to hold any keyboard key, just mid-click and drag 

:)

consider that defold being used mostly for 2d games, panning in the editor is probably the most common action that the user will do for navigating. It should be intuitive and easy to do. Using three keys to do the most important navigation action in a 2d engine is a bit strange

**Comment by ragnard-king** [comment]
Thanks for the report!

Duplicate of https://github.com/defold/editor2-issues/issues/183

**Comment by blurymind** [comment]
Ah sorry, I should have checked more carefully

Adding a note to this, I found myself orbiting the scene in 3d when trying to figure out where the pan modifier key is.
Does defold have a view command to reset the view after it being orbited in 3d?

**Comment by ragnard-king** [comment]
@blurymind No worries, we appreciate all reports. We definitely want to improve the key/mouse bindings.

For resetting the rotation, there's `Scene -> Camera -> Re-align`.

**Comment by blurymind** [comment]
@ragnard-king thank you!
Also the editor is surprisingly stable for an alpha! Great job

**Comment by blurymind** [comment]
@ragnard-king  I updated to the latest version and mid-click panning works, so as alt+click to pan!
:D 
Thank you for addressing this- it makes the editor much more comfortable and intuitive to use

I am closing this bug report now
