### ISSUE TITLE
bug message when moving a game object after duplicating it

### ISSUE THREAD

**Issue by blurymind** [defold/editor2-issues#458]
I just got an error message when duplicating a game object and moving it

### Steps to reproduce
Move one of the the ground game object inside the ground collection - imported assets from the runner tutorial
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>de4d6bfe1faef85f5485677f6b45f41148bdacf9</td></tr>
<tr><td>Build time</td><td>2017-01-23T10:15:27.704005</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Do you have any more information on the error? Are you able to re-produce it? If so, clicking "Report Issue" in the error dialog and reporting it will gives us more context about the problem.

**Comment by blurymind** [comment]
Hi ragnar, apologies for this. It was an error message that popped up a number of times in the editor and I wasn't sure if the information that it generated would be useful to you, so I clicked the report button it offered.
The actual bug does not seem to be a stopper as It didn't crash the editor. My guess is that it is caused sometimes when creating a new resource or a game object. It's doing something in the background to keep track of things that some times triggers the bug message. 
The error popped up right after I copy and pasted a game object ,then started moving it

Hope that helps

**Comment by Jerakin** [comment]
I have gotten this the same way. If I try to move the game object after pasting it into a collection it gives me `java.lang.NullPointerException: Unknown` error

The game object had the following structure:
-- Game Object ("water_effect")
---- Game Object ("blue_background")
------ Sprite ("sprite1")
---- Game Object ("image")
------ Sprite ("sprite")
---- Game Object ("wave")
------ Particle FX ("particlefx")
------ Script ("script")

When I try to run the I get
```
ERROR:GAMEOBJECT: Child not found: /blue_background
ERROR:GAMEOBJECT: Child not found: /image
ERROR:GAMEOBJECT: Child not found: /wave
```

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>6724f8ac845b14b7a54a1305fbf93a34789f674b</td></tr>
<tr><td>Build time</td><td>2017-02-10T17:47:50.773801</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=7ddb22563c0244efaf8b42a444ccfae2'>7ddb22563c0244efaf8b42a444ccfae2</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
We recently fixed a bug when copy/pasting game objects between collections, this looks like a typical symptom.
