### ISSUE TITLE
bug report pop up - when saving atlas for the first time

### ISSUE THREAD

**Issue by blurymind** [defold/editor2-issues#460]
A bug report pops up to report

**clojure.lang.ExceptionInfo: Concurrent modification of graph**

### Steps to reproduce
1. create new atlas
2. add images to it
3. save with ctrl+s

minor bug, doesn't always happen and doesn't seem to affect the scene
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>de4d6bfe1faef85f5485677f6b45f41148bdacf9</td></tr>
<tr><td>Build time</td><td>2017-01-23T10:15:27.704005</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
This bug was fixed on the 26/1 and I see that the version you're running was built on the 23/1. You should receive an offer to update sometime after starting editor (once it has downloaded the updated version). Can you try updating?

**Comment by blurymind** [comment]
I see.. Sorry for the duplicates @ragnard-king 
When I get the update I will test it again

**Comment by ragnard-king** [comment]
@blurymind No worries, we really appreciate the testing/reporting so please keep it coming :-)

**Comment by erikangelin-king** [comment]
@blurymind Does this still happen for you?

**Comment by erikangelin-king** [comment]
Can't repro
