### ISSUE TITLE
spine model component - once spine scene is set, it can not be changed - error message pops up [DEFEDIT-719]

### ISSUE THREAD

**Issue by blurymind** [defold/editor2-issues#461]
**java.security.PrivilegedActionException: Unknown
java.lang.Exception: Setter of node 72057594037928387 (editor.spine/SpineModelNode) :spine-scene could not be called
java.lang.NullPointerException: Unknown**

### Steps to reproduce
0. Download the stretchyman spine example from
https://github.com/EsotericSoftware/spine-runtimes/tree/master/examples/stretchyman
1. create spine atlas and spine scene - load the stretchyman spine example files into them
2. Create a spine model and then try to load the spine scene of the stretchyman

Defold will fail to load it and spit out an error message

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>de4d6bfe1faef85f5485677f6b45f41148bdacf9</td></tr>
<tr><td>Build time</td><td>2017-01-23T10:15:27.704005</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by blurymind** [comment]
Loading spine scenes in general seems to stop working for some odd reason, after swtching between multiple examples

**Comment by ragnard-king** [comment]
See https://github.com/defold/editor2-issues/issues/460, I think this might also be fixed in a more recent release.

**Comment by blurymind** [comment]
I get this error on the latest update:

java.security.PrivilegedActionException: Unknown
java.lang.Exception: Setter of node 72057594037928267 (editor.spine/SpineModelNode) :spine-scene could not be called
java.lang.NullPointerException: Unknown

It seems to be triggered when on a spine model I try to replace the dragon spine scene with the stretchyman scene 

Even if I try replacing the dragon scene with the dragon scene, I get the same error message

![errorspinescene](https://cloud.githubusercontent.com/assets/6495061/22717058/df8c290e-ed90-11e6-91fc-336f10dc9d75.JPG)

**Comment by blurymind** [comment]
The only workaround is to delete the spine model component and add it again.
Once you set the spine scene in it, you can not change it to something else - you will get the error message!

**Comment by blurymind** [comment]
Moving a spine scene to a folder, after it has been assigned to a spine model seems to cause this bug!

**Comment by matgis-king** [comment]
Indeed, moving the assigned spine scene before assigning the new scene does the trick! Here's my system info with a Sentry link (these contain additional info to help us fix the bug, such as a full callstack and system report):

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>Build time</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2160256fb95d4fbfa0e90c5302c3f5b7'>2160256fb95d4fbfa0e90c5302c3f5b7</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi! This should be fixed by a recent merge, please reopen if the issue remains!
