### ISSUE TITLE
Problem opening large collection [DEFEDIT-767]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#465]
### Expected behaviour
I tried to open map.collection from Blossom Blast

### Actual behaviour
It crashed

### Steps to reproduce
Open Blossom Blast and the map.collection

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>a48d5f28357da97535eb74640370c9e50598eda0</td></tr>
<tr><td>Build time</td><td>2017-02-07T18:10:15.172777</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=344082cc1fd545b08a928ec3e9952695'>344082cc1fd545b08a928ec3e9952695</a></td></tr>
<table>

**Comment by matgis-king** [comment]
The issue was not actually due to scene size, but was caused by a Collada scene that were missing some channels of vertex data. The bug was introduced when we switched Collada loader in order to support 3D animation. We now handle this scenario correctly again.
