### ISSUE TITLE
Project with native extensions crashes the editor while building

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#468]
### Expected behaviour
Native extensions should be built properly

### Actual behaviour
The editor crashes when trying to build a project with native extensions

### Steps to reproduce
Build a project containing native extensions

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>a48d5f28357da97535eb74640370c9e50598eda0</td></tr>
<tr><td>Build time</td><td>2017-02-07T18:10:15.172777</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=aeae4e5b5600455d90e890ad5dda917d'>aeae4e5b5600455d90e890ad5dda917d</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
