### ISSUE TITLE
[Windows 10 x64]: Defold crashes when .fp file is added as material for sprite

### ISSUE THREAD

**Issue by defold-issues** [defold/editor2-issues#471]
### Expected behaviour
Defold should not crash, but it should show an error with an explanation.
### Actual behaviour
Defold crashes, even after renaming the collections.
### Steps to reproduce
1. Launch defold
2. Create a project or use the Ioana Training project (Sofia Hedlund has access to it)
3. Create an atlas file writing in the name field exactly "level.atlas" (notice that the atlas file will be names "level.atlas.atlas")
4. Do the same for the ground.collection (should be "ground.collection.collection") and the main.collection (should be "main.collection.collection")
5. Set everything up in the .atlas and .collection files just to get ground images
6. Click on Project menu and Build Option
7. Notice that defold crashes
8. Start Defold again and modify the .atlas and .collection files names and add them again to the Sprite files
9. Click on Project menu and Build Option
10. Notice that Defold still crashes, even though .atlas file and .collection files have been renamed correctly.
<hr/>
Defold version: 1.2.95
Defold sha: 2fd8732d146f5a252125ce1b210e3793f50e169c
Platform: Windows 10 10.0 (amd64)
Java version: 1.8.0_102-b14

**Comment by sofiahe** [comment]
[12:21 PM] Ragnar Dahlen: on verkar ha valt en .fp-fil som material för en sprite, se ground.collection, ground0, sprite... material där är satt till "/builtins/fonts/font-df.vp"
[12:21 PM] Ragnar Dahlen: det ska inte gå att välja annat än ".material" filter där

**Comment by ragnard-king** [comment]
As updated title indicates, root cause was that a `.fp` file was selected as material for a sprite. Only `.material` resources should be shown when selecting.

**Comment by erikangelin-king** [comment]
potentially quick-fix: constrain resource chooser to relevant types. But does the editor respect the material setting?

**Comment by RagnarSvenssonKing** [comment]
Fixed previously.
