### ISSUE TITLE
[Linux Virtual Machine] The Build function can not be used and several errors are displayed

### ISSUE THREAD

**Issue by defold-issues** [defold/editor2-issues#472]
After following all the steps from the provided tutorial, when using the Build function for the first time, the Defold tool becomes unresponsive and these errors are displayed in the console:
_"Welcome to Defold!
INFO:ENGINE: Defold Engine 1.2.96 (ed344a9)
INFO:ENGINE: Loading data from: build/default
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
AL lib: (WW) ALCjackBackendFactory_init: jack_client_open() failed, 0x11
AL lib: (WW) alc_initconfig: Failed to initialize backend "jack"
INFO:ENGINE: Initialised sound device 'default'

INFO:DLIB: SSDP: Started on address 172.23.0.93
ERROR:GRAPHICS: gl error 1282: invalid operation

dmengine: ../src/opengl/graphics_opengl.cpp:1169: void dmGraphics::SetConstantM4(dmGraphics::HContext, const Vectormath::Aos::Vector4*, int): Assertion `0' failed."__

![defold2](https://cloud.githubusercontent.com/assets/25633889/22740328/f739bcd8-ee17-11e6-9013-d8851aa103fc.jpg)
![defold](https://cloud.githubusercontent.com/assets/25633889/22740327/f73989fc-ee17-11e6-9ccb-725c3eccba9e.jpg)

tested on: Alina Danciu	BUCVML161064bit

**Comment by erikangelin-king** [comment]
Looks like poor gl support on VM
