### ISSUE TITLE
Edits to a cloned builtin shader file cannot be applied [DEFEDIT-733]

### ISSUE THREAD

**Issue by ericroy** [defold/editor2-issues#476]
### Expected behaviour
I expect that if I clone a builtin shader file by coping it to my project, then I should be able to modify it and save my changes.

### Actual behaviour
In actuality, it *looks* like the editor has allowed me to edit and save the file, but no changes are saved.

It's almost like the file has inherited the fact that builtins cannot be modified.  This is somewhat related to, but distinct from #231

### Steps to reproduce
- In the defold editor, right-click-copy a builtin shader file (.vp or .fp)
- Right-click-paste the file somewhere inside the root of the project
- Open the copied shader and make an edit
- Save all
- Inspect the copied shader file in an external editor - no changes have been made

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>e778f9ea025aa86ec65def2f3bf0ea0b4e7407f4</td></tr>
<tr><td>Build time</td><td>2017-02-09T17:34:29.812371</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged, should land in an update shortly. We simply didn't save .vp/.fp files at all :(
