### ISSUE TITLE
Error when trying to save nested templates

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#479]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>6724f8ac845b14b7a54a1305fbf93a34789f674b</td></tr>
<tr><td>Build time</td><td>2017-02-10T17:47:50.773801</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6a6e0f47686142cf9f1eac7a695568e5'>6a6e0f47686142cf9f1eac7a695568e5</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can't repro since error info lost :'(
