### ISSUE TITLE
Nodes attached on spine-nodes are not working [DEFEDIT-820]

### ISSUE THREAD

**Issue by andreas-strangequest** [defold/editor2-issues#482]
This:
<img width="181" alt="screen shot 2017-02-13 at 07 35 50" src="https://cloud.githubusercontent.com/assets/23556757/22873350/dabfd5be-f1bf-11e6-9861-b569634ea78b.png">

Gives this:
<img width="453" alt="screen shot 2017-02-13 at 07 36 28" src="https://cloud.githubusercontent.com/assets/23556757/22873361/ef7c275a-f1bf-11e6-804e-1b36a1273a02.png">

Works perfectly fine in editor 1. To us it's a blocker right now using Ed2.

**Comment by erikangelin-king** [comment]
Fix merged!
