### ISSUE TITLE
[OS X] Popup windows goes full screen when app is run full screen.

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#49]
STR:
1. Open the app.
2. Click the full screen (green) window control in the top-left corner.
3. Press Cmd-Q or select "About..." or any other action that brings up a small popup-window.

![screen shot 2016-09-15 at 13 50 37](https://cloud.githubusercontent.com/assets/65613/18548917/8b204c40-7b4b-11e6-80e8-6bce4858b802.png)

**Comment by sicher** [comment]
Note that some windows, like "Preferences" and "Target IP", that open modally, do not take over the screen:

![screen shot 2017-02-09 at 10 21 44](https://cloud.githubusercontent.com/assets/65613/22776888/b98c214c-eeb1-11e6-8f2f-87a9da577043.png)

It seems like the solution to "About" and "Update" is to make them modal.

**Comment by sicher** [comment]
A quite serious side effect of having non modal popups is that they easily hide behind the main window and is lost.

**Comment by ragnard-king** [comment]
Fixed by https://github.com/defold/defold/pull/1334
