### ISSUE TITLE
Hide Progress bar when not used

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#493]
The top bar that says Done is a bit confusing.
![screen shot 2017-02-13 at 11 46 48](https://cloud.githubusercontent.com/assets/5273682/22880366/2ba321b2-f1e2-11e6-916e-35d2586e66ed.png)

Users are used to seeing a progress bar if something is in progress. It should only be present if it is working on something.

**Comment by ragnard-king** [comment]
We absolutely want to improve how we show progress and what we show in the "toolbar" area.

**Comment by ragnard-king** [comment]
Closing as we've since removed the whole top bar and only show a small progress status text in the lower left corner of the main window. We still absolutely want to improve how we visualise work and progress but at least it's hopefully less annoying as it is right now.
