### ISSUE TITLE
Show unsaved files with asterisk in tab name

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#495]
If you have edit a file but not saved it, it should have an asterisk in its name.
![screen shot 2017-02-13 at 14 13 33](https://cloud.githubusercontent.com/assets/5273682/22884732/bd6d4fbe-f1f6-11e6-97cc-889c8263dc87.png)
![screen shot 2017-02-13 at 14 13 27](https://cloud.githubusercontent.com/assets/5273682/22884733/bd6df752-f1f6-11e6-8add-29350874f875.png)

**Comment by ragnard-king** [comment]
Just a note regarding saving: In editor2 you don't have to save to see the effects of your changes when building.

**Comment by RagnarSvenssonKing** [comment]
Fixed!
