### ISSUE TITLE
DEFEDIT-818 Editor freezes while build is running 

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#497]
### Expected behaviour
Not freezing

### Actual behaviour
Freezing

### Steps to reproduce
Only noticed on one of many projects, so could be project specific.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>17d09dd607a6123914c451c63e2b913540b0e28d</td></tr>
<tr><td>Build time</td><td>2017-02-13T14:42:06.853656</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Jerakin** [comment]
[editor2_freeze.txt](https://github.com/defold/editor2-issues/files/771639/editor2_freeze.txt)

Log

**Comment by ragnard-king** [comment]
The project in question requires around 5G to build. JVM defaults to 4G heap on 16G systems, so running with `-Xmx8G` allowed me to build. We still need to investigate heap usage and cache memory usage, similar to https://github.com/defold/editor2-issues/issues/443.

**Comment by ragnard-king** [comment]
A fix that improves our memory usage for projects that have lots and/or large images will be available in an update later today. Closing this now as the project in this issue now builds within the limit of 4G. There's more we can do about our memory usage, but this is a first (hopefully good) step.
