### ISSUE TITLE
If tilesource not found sprite - error

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#499]
### Expected behaviour
I want change sprite in tilesource when old picture was deleted from disc
### Actual behaviour
java.lang.NullPointerException: Unknown
### Steps to reproduce
1. Create tilesource and add sprite 
2. Remove sprite from old location
3. Reopen tilesource
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>0ffa70f89359fc87d77290be7ebe56f75e583762</td></tr>
<tr><td>Build time</td><td>2017-02-01T14:41:16.507728</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=4dce410d35e2482084c766e993c4d3cc'>4dce410d35e2482084c766e993c4d3cc</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can't repro this, please reopen if it happens again!
