### ISSUE TITLE
Scale properties in collections not saved correctly

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#5]
The platform tutorial (http://www.defold.com/tutorials/platformer/) seems to have some scaling issues when building and running through editor2. See attached images.
Looking at Changed Files shows level/level.collection as changed. Diff shows that all scaling properties have been reset to 1.0 (regardless of their previous values). Reverting the changes and doing Build has no effect, and doing Save All reintroduces the scale reset in level.collection.

Editor1:
![image](https://cloud.githubusercontent.com/assets/20399970/17546658/2e71dedc-5edb-11e6-9dbc-e13ad1e481f1.png)

Editor2:
![image](https://cloud.githubusercontent.com/assets/20399970/17546666/378c6906-5edb-11e6-9d04-d1d2a1ded666.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed
