### ISSUE TITLE
Not search a files start from upper symbol

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#503]
### Expected behaviour
Search files if files start from upper symbol
### Actual behaviour
Not search files start from upper symbol
### Steps to reproduce
1. Create any file start from upper symbol
2. Try search create file

![image](https://cloud.githubusercontent.com/assets/588556/22961012/c5c399e4-f353-11e6-8f1d-0bba066b1ee8.png)
![image](https://cloud.githubusercontent.com/assets/588556/22961018/d7dd109c-f353-11e6-898d-d71b5c722d85.png)
![image](https://cloud.githubusercontent.com/assets/588556/22961029/f15e8122-f353-11e6-8e03-a3494a81ac03.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>bf676a672c175833fbe9e668216d73e303c8e5df</td></tr>
<tr><td>Build time</td><td>2017-02-14T18:51:03.448770</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed
