### ISSUE TITLE
Rename file drop extention

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#504]
### Expected behaviour
Rename file not change extention after rename
### Actual behaviour
Rename file drop extention and not recognized by Editor
### Steps to reproduce
1. Create file
2. Rename file

![image](https://cloud.githubusercontent.com/assets/588556/22961067/374a6e76-f354-11e6-9647-d66d9086a7e9.png)
![image](https://cloud.githubusercontent.com/assets/588556/22961072/4c0ac2de-f354-11e6-94ba-455beb7830a2.png)
![image](https://cloud.githubusercontent.com/assets/588556/22961086/6aad2b46-f354-11e6-96bc-df278702e248.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>bf676a672c175833fbe9e668216d73e303c8e5df</td></tr>
<tr><td>Build time</td><td>2017-02-14T18:51:03.448770</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Duplicate of https://github.com/defold/editor2-issues/issues/442

**Comment by erikangelin-king** [comment]
Fixed.
