### ISSUE TITLE
Create file with same name [DEFEDIT-784]

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#505]
### Expected behaviour
Not happening or warning about file exist
### Actual behaviour
Recieve error java.security.PrivilegedActionException: Unknown
org.eclipse.jgit.errors.MissingObjectException: Missing blob e1532e4e81c3ec7557bb7b5f06e61850ec49c344
### Steps to reproduce
1. Create file
2. Create file with same name in same folder
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>bf676a672c175833fbe9e668216d73e303c8e5df</td></tr>
<tr><td>Build time</td><td>2017-02-14T18:51:03.448770</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=4673488991874f788e526ecf7a9bdf25'>4673488991874f788e526ecf7a9bdf25</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Also, original file is replaced.

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
