### ISSUE TITLE
The editor keeps nagging me about a removed file that is no longer used [DEFEDIT-796]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#506]
### Expected behaviour
If a file is removed from outside of the editor and it isn't actually used by the project the editor should be happy and not complain about a missing file

### Actual behaviour
I removed a file (foo.lua) from outside the editor but the editor keeps insisting that the file is missing when I try to build. The file used to be required by a script but that is no longer the case.

### Steps to reproduce
Add a require to a Lua module from a script. Remove the Lua module from the terminal and also remove the require statement (this probably also has to be done "from the outside"). Go back to the editor and try to build. Notice the message about "The file /foo.lua could not be found"
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>bf676a672c175833fbe9e668216d73e303c8e5df</td></tr>
<tr><td>Build time</td><td>2017-02-14T18:51:03.448770</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged!
