### ISSUE TITLE
[DEFEDIT-789] NPE when creating new tilesource

### ISSUE THREAD

**Issue by GaussX** [defold/editor2-issues#507]
### Expected behaviour
Create new Tilesource
### Actual behaviour
java.lang.NullPointerException: Unknown
### Steps to reproduce
Create new tilesource (issue #459 Closed but error still there)
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>903271a90ba0d672efae3168eb346c228d5f4556</td></tr>
<tr><td>Build time</td><td>2017-02-15T10:32:04.071302</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=ac9a915c3cd241f9972fdbb849e819ca'>ac9a915c3cd241f9972fdbb849e819ca</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Thanks for re-reporting this one @GaussX. Indeed the initial first fix was broken.

Fixed and available in update.
