### ISSUE TITLE
Script component property saved in format not compatible with editor 1 [DEFEDIT-788]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#509]
In testing to transition to editor 2 we still need to run editor 1 in parallel. The created files should be compatible with the old editor (and any command-line builds made through bob.jar on the build servers).

I have a script component named camera.script (id: camera) that has a property named "name". In editor 1 this property is saved like this:

```
  "  properties {\n"
  "    id: \"name\"\n"
  "    value: \"transition\"\n"
  "    type: PROPERTY_TYPE_HASH\n"
  "  }\n"
```

In editor 2 the property is saved like this:

```
  component_properties {
    id: "camera"
    properties {
      id: "name"
      value: "transition"
      type: PROPERTY_TYPE_HASH
    }
  }
```

Saving the file in editor 2 and opening it up in editor 1 will make the name field empty/default.

Since this new format looks much better and easy to work with I would suggest adding support for it in editor 1.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.97</td></tr>
<tr><td>Defold sha</td><td>1032c836a01b9f7de6bebd1f022ca15528ceded8</td></tr>
<tr><td>Build time</td><td>2017-02-15T14:51:24.466675</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged, we will use the editor 1-format for now.

**Comment by Jerakin** [comment]
> use the editor 1-format for now.

@erikangelin-king When the editor 1 is "discontinued" will this format be used instead for embedded data? It is a lot easier to work with.

**Comment by erikangelin-king** [comment]
Hi @Jerakin!
I think we'll keep the editor 1 format for a while so we don't disturb teams using both editors. Once the interest for editor 1 fades I guess we could revisit this part of the issue :)
