### ISSUE TITLE
Automatic indentation is not always correct

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#510]
### Expected behaviour
If I select multiple lines and press tab I expect the indentation to be correct

### Actual behaviour
The indentation becomes completely wrong under certain circumstances

### Steps to reproduce
Take this snippet of code:

```
local function durableRequest1()
	local requestBuilder = gs.getRequestBuilder()
	local logEventRequest = requestBuilder.createLogEventRequest()
	local endSessionRequest = requestBuilder.createEndSessionRequest()
	
	gs.setNetworkAvailable(false)
	
	logEventRequest:setDurable(true)
	logEventRequest:setEventKey("testMessage")
	logEventRequest:setEventAttribute("foo", "bar")
	logEventRequest:send(nil)
	
	endSessionRequest:send(function(response)
		gs.disconnect(false)

		gs.setNetworkAvailable(true)
		gs.setAvailabilityCallback(durableRequest2)
	end)
end
```
Select it all and press tab. Notice that the indentation of the anonymous function is incorrect.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>2e8c2b2eecfeef0d592d030aaebd9705b8e3ece0</td></tr>
<tr><td>Build time</td><td>2017-02-15T17:31:53.133808</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by Malmer** [comment]
Instead of the automatic indentation I would prefer to have normal tab/shift+tab functionality to indent and unindent.

**Comment by britzl** [comment]
I agree with @Malmer  that normal tab/shift-tab would be better. And a separate keybinding to indent selected code or whole file.

**Comment by erikangelin-king** [comment]
We now have normal tab/shift tab and separate indent.
