### ISSUE TITLE
Unable to build and run

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#512]
### Expected behaviour
I should be able to build and run a project without errors
### Actual behaviour
I get "com.sun.jersey.api.client.ClientHandlerException: java.net.ConnectException: Connection refused" when I try to build

### Steps to reproduce
Open any project and try to build and run it.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>ff9e30588b74b1ba11429bb59fb4f8156bb8cc3f</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Old version.
