### ISSUE TITLE
"Not now" button on update dialog

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#514]
Right now there are two options:
Update and restart
Skip version

There is no way to say "Hey, I want this new version, but right now I want to keep working. Install it the next time I restart manually".

**Comment by Malmer** [comment]
Seems like "Not now" is actually what "Skip update" does. The text should change to be clearer and I will be happy to close this issue.

**Comment by erikangelin-king** [comment]
It now says "Not Now" :)
