### ISSUE TITLE
code editor- autocompletion NOT working after using backspace

### ISSUE THREAD

**Issue by blurymind** [defold/editor2-issues#517]
I noticed that autocomple/suggestions stop working in code editor if you hit backspace

Try entering go.set_po

then hit backspace twice

The code suggestion stops working - no suggestion is shown

You have to hit backspace all the way to the comma in order to get it back and type "set_" again in order to see what the suggestions starting with "set_" are

**Comment by blurymind** [comment]
This is a bug report rather than a suggestion, however it is somewhat related to
https://github.com/defold/editor2-issues/issues/439

**Comment by erikangelin-king** [comment]
Fixed in new code editor
