### ISSUE TITLE
gui_script -- changing spine scene in a gui object crashes defold's game preview

### ISSUE THREAD

**Issue by blurymind** [defold/editor2-issues#518]
If I use this code in a gui_script:

> local node = gui.get_node("spinemodel")
> gui.set_spine_scene(node,"drag2")

(called when pressing a button)

that triggers the preview to crash altogether (when I press the button) and I get this in my log:

> Assertion failed: size <= Capacity(), file c:\buildbot\slave\builds\engine-win32-64-dev\build\tmp\dynamo_home\sdk\include\dmsdk/dlib/array.h, line 437

---
if I un-comment the set_spine_scene line and replace it with

> gui.set_spine_playback_rate(node, 80)

I notice that it does change the playback, so the node variable is correct

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>52ca564d1649e4451a1d0915fdd63af2b7686645</td></tr>
<tr><td>Build time</td><td>2017-02-17T16:27:51.518098</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by blurymind** [comment]
as a side node - is it possible to change spine scene during runtime when its in a game object?

**Comment by britzl** [comment]
Unable to reproduce using Defold 1.2.135.

To answer the question of how to change scene in a game object then no, the idea there is that you either have multiple spine components on the go that you enable/disable or that you have multiple game objects.
