### ISSUE TITLE
Error triggered when opened "outro.gui" in geometry haxx project [DEFEDIT-799]

### ISSUE THREAD

**Issue by benjaminglaser** [defold/editor2-issues#520]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>6da30f2b3f7ab92c6536a3456eb579132ffa6abb</td></tr>
<tr><td>Build time</td><td>2017-02-20T18:42:20.127055</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=9b45c5625ea64cea825c2c2a9ce13948'>9b45c5625ea64cea825c2c2a9ce13948</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
