### ISSUE TITLE
Can't create new local project from the editor

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#527]
### Expected behaviour
A button on the start screen to create a new local project, not hosted by defold

### Actual behaviour
I need to copy an other project's game.project manually

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>6725d7a9bc8fc85b3d6759eb5ed7dfb9df2cf9fb</td></tr>
<tr><td>Build time</td><td>2017-02-21T10:13:40.438078</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed
