### ISSUE TITLE
I make require and receieve error

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#531]
### Expected behaviour
Not happend
### Actual behaviour
Recieve error clojure.lang.ExceptionInfo: handler ':key-typed' in context ':code-view' failed at ':run' with message 'Setter of node 72057594037928020 (editor.script/ScriptNode) :code could not be called'
java.lang.Exception: Setter of node 72057594037928020 (editor.script/ScriptNode) :code could not be called
java.nio.file.InvalidPathException: Illegal char <"> at index 43: <path to file>/"".lua
### Steps to reproduce
1. In script type require """" - receieve error.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>47641fce2a5efeecf842e55a0680b3a57d7a6951</td></tr>
<tr><td>Build time</td><td>2017-02-23T17:11:53.865708</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d5585edf16c64cd7a9c081dfee49593b'>d5585edf16c64cd7a9c081dfee49593b</a></td></tr>
<table>

**Comment by matgis-king** [comment]
Note: Not reproducible on macOS, but I can reproduce it on Windows every time.

**Comment by erikangelin-king** [comment]
Can't repro this but quite a lot has changed since it was reported :) Please reopen if it happens again in the new code editor!
