### ISSUE TITLE
Property window does not support vector4

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#532]
### Expected behaviour
I can create a GO property of type vector4. Vector3 works fine

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>21bf8d97d0be64dafe927515ddd0697e04feeb1a</td></tr>
<tr><td>Build time</td><td>2017-02-24T11:10:16.372909</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=b5ecb9f4e16e4c14b6467d0ae5a02368'>b5ecb9f4e16e4c14b6467d0ae5a02368</a></td></tr>
<table>

**Comment by Malmer** [comment]
Isn't this a bug rather than a new feature request? The Defold documentation on go.property states that vector4 is supported. Labelling it feature seems strange.

**Comment by erikangelin-king** [comment]
@SamuelBeijer Just tried this and adding a go.property("cake", vmath.vector4()) seems to work now, please reopen if it breaks somewhere!
