### ISSUE TITLE
Viewport doesn't render sprites using the assigned shaders

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#535]
### Expected behaviour
Tints and custom shader bells and whistles should be visible in editor viewport

### Actual behaviour
Sprite is rendered as is, using some built in shader

### Steps to reproduce
Copy sprite.material from builtins
Change tint value
Apply material to sprite in scene

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>0e2aa50f31fff3ee03dd97c1132bc4b7fec364fb</td></tr>
<tr><td>Build time</td><td>2017-02-24T17:51:03.233874</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed previously.
