### ISSUE TITLE
View transform passed to models is set to world transform [DEFEDIT-823]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#537]
### Expected behaviour
Setting the view transform in the render script to identity matrix should result in a view matrix passed to the shader that is identity.

### Actual behaviour
The matrix passed seems to be the worldview matrix. This also shows an error in the default model shader, in that it only uses the view matrix and not the worldview matrix as it should.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>09c8b4194b94f8d8981493e3bfd25c9b2a79a42b</td></tr>
<tr><td>Build time</td><td>2017-02-27T10:15:04.883521</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
This has been fixed as the description. There is still the issue of every model's vertex data being pre-processed on the CPU to be in world space (to enable batch-rendering). Please report new issues if there is anything related to this that is blocking you.
