### ISSUE TITLE
MacOS: Update editor window often hidden behind main window [DEFEDIT-821]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#538]
The popup about updating the editor is often hidden behind the main editor when it pops up while the user is in other applications. Going back it feels like the app has frozen, but when really there is a hidden update window behind the main window.

The update notification should jump to the front when the main window is clicked.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>f54290874da2306e99d00214501a39ef2e527cd3</td></tr>
<tr><td>Build time</td><td>2017-02-27T17:17:33.018771</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Tomires** [comment]
Just dropping by to say the issue isn't macOS-specific. I am getting the same behaviour on Linux.
