### ISSUE TITLE
[Suggestion] Use Inconsolata LGC or Source Code Pro for the code editor

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#54]
Source Code Pro:

* Great number of styles and weights

http://adobe-fonts.github.io/source-code-pro/

Inconsolata LGC is an extended version of Inconsolata with:

* Proper italics
* Cyrillic characters (yay all our Russian users)
* Greek characters (yay ...)

https://fontlibrary.org/en/font/inconsolata-lgc

**Comment by RagnarSvenssonKing** [comment]
We thought we were using Inconsolata, but in fact Courier was being used because of reasons. Fixed now.
