### ISSUE TITLE
Inner radius property does not visualise properly

### ISSUE THREAD

**Issue by Tomires** [defold/editor2-issues#540]
Live preview isn't adapting properly to changes of the inner radius property.

![image](https://cloud.githubusercontent.com/assets/7209990/23374278/ea2a260c-fd23-11e6-8efb-383ccb5d459a.png)
[editor on the left, game on the right]

OS: Windows 8.1, Linux

### Steps to reproduce

Opened a GUI file.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>4f206f8e0f33a4f82133a3b1cac8ef0355c51697</td></tr>
<tr><td>Build time</td><td>2017-02-27T13:25:37.772145</td></tr>
<tr><td>OS name</td><td>Windows 8.1</td></tr>
<tr><td>OS version</td><td>6.3</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed previously.
