### ISSUE TITLE
Rarely, editor hangs when expanding folder

### ISSUE THREAD

**Issue by ericroy** [defold/editor2-issues#541]
### Expected behaviour
Should be able to click on the arrow beside a folder in the Assets explorer, and the folder should expand.

### Actual behaviour
Rarely, the editor hangs in a busy loop, consuming cpu forever.

### Steps to reproduce
Only happens occasionally...  Just keep using the editor I guess, and expand/collapse folders a lot?

Last time it happened I really wanted to print stack traces of the editor process to go with this report.  I tried using jcmd:

```jcmd <pid> print```

But it didn't work...  sorry, not really a java expert 😞 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>f0eb8c8d2b6c93be94ca3421f75f698d0a08b3f7</td></tr>
<tr><td>Build time</td><td>2017-02-27T18:01:54.924639</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Could you check the logfile at c:\Users\<you>\appdata\Roaming\defold\editor2.log? There could be a bunch of interesting exceptions logged at the time when this happened. I'd gladly have a look if you mail me the log, erik.angelin@king.com.

**Comment by RagnarSvenssonKing** [comment]
This has been fixed previously.
