### ISSUE TITLE
Use assigned materials in the editor

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#543]
From forum: http://forum.defold.com/t/defold-editor-2-0/1407/233

"Anything what i see in the tile source editor, tile map editor, game object (collection) editor is blurred. But i am using pixel art, and so i want nearest filtering, just like in actual game."

Reply: http://forum.defold.com/t/defold-editor-2-0/1407/235

"The materials should be used to render in the editor, just like in the game. This is the case already in many instances, but it's missing for sprites, tile maps and tile sources."

**Comment by patsyn** [comment]
The particle editor also doesn't render with the selected material.

**Comment by ragnard-king** [comment]
A fix for this has now been merged, ie. editor should now render everything that has a material using that material (shaders/uniforms/samplers). Coming in update shortly.
