### ISSUE TITLE
Circle emitter radius seems to be incorrectly drawn in particle editor

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#548]
The preview circle seems twice as big as my emitter really is
![screen shot 2017-03-01 at 10 39 45](https://cloud.githubusercontent.com/assets/3929293/23454178/c70275e6-fe6b-11e6-9b4a-0d15922a3002.png)

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>d978c8b15abcd615b52aef592a61045e64f1d1dd</td></tr>
<tr><td>Build time</td><td>2017-02-27T15:37:50.510544</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Changed to blocker after talking to @SamuelBeijer

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
