### ISSUE TITLE
Editor should show console when starting the game

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#549]
### Expected behaviour
The editor should jump from the console view when starting the game when the build errors tab is active.

### Actual behaviour
It stays on the build error tab

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>4f206f8e0f33a4f82133a3b1cac8ef0355c51697</td></tr>
<tr><td>Build time</td><td>2017-02-27T13:25:24.318905</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in next update.
