### ISSUE TITLE
Double clicking a material tag results in error

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#551]
Got error when doubleclicking on a material tag.

Note: the material was a copy of an older material.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>4f206f8e0f33a4f82133a3b1cac8ef0355c51697</td></tr>
<tr><td>Build time</td><td>2017-02-27T13:25:24.318905</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=13b03d15cd1e4467ad63976cf9526f65'>13b03d15cd1e4467ad63976cf9526f65</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can you repro this?

**Comment by Malmer** [comment]
Doesn't seem I can. Might have been a one-off.

**Comment by erikangelin-king** [comment]
can't repro
