### ISSUE TITLE
Dont show nothing in main view editor

### ISSUE THREAD

**Issue by mncorreialive** [defold/editor2-issues#553]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.98</td></tr>
<tr><td>Defold sha</td><td>4f206f8e0f33a4f82133a3b1cac8ef0355c51697</td></tr>
<tr><td>Build time</td><td>2017-02-27T13:25:37.772145</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=e0b1f35d27a1499da440cceb9c1f2f68'>e0b1f35d27a1499da440cceb9c1f2f68</a></td></tr>
<table>

**Comment by mncorreialive** [comment]
![image](https://cloud.githubusercontent.com/assets/26151779/23530217/8d8295ac-ff7f-11e6-9016-2238c3354e7f.png)

**Comment by erikangelin-king** [comment]
Hi!
This looks like the same problem as reported here: https://github.com/defold/editor2-issues/issues/455
Could you try updating your drivers?

**Comment by erikangelin-king** [comment]
Also, does editor 1 work?

**Comment by erikangelin-king** [comment]
@mncorreialive Please reopen if updating the drivers didn't help!
