### ISSUE TITLE
Very strange error with Access Denied to file

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#555]
I make some changes and add some fles to project. Editor show they on changed files window.

I try synchronize, make push and recieve exception - FileNotFound (Access Dinied) and all my files disappear from disk.

After restart Editor I cancel  syna and files return but very strange behavior

**Comment by erikangelin-king** [comment]
Can't repro, has this happened again?

**Comment by erikangelin-king** [comment]
Can't repro, please reopen if it happens again.
