### ISSUE TITLE
"Missing require" error links to the missing file, rather than the file with the invalid require 

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#557]
### Expected behaviour
Doubleclicking the error in the build errors view should take you to the file with the invalid require statement

### Actual behaviour
It tries to open the missing file. Which doesn't work since it doesn't exist.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>135963c69c03804c91f509ac0407b7053f2fa992</td></tr>
<tr><td>Build time</td><td>2017-03-06T10:16:32.110612</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
