### ISSUE TITLE
New GUI files get wrong Adjust Reference

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#564]
New GUI files get Adjust Reference set to "Root (deprecated)" by default:

![screen shot 2017-03-08 at 10 44 56](https://cloud.githubusercontent.com/assets/65613/23698578/60121a22-03ec-11e7-95a5-4742a71f2eef.png)

It should be set to "Per Node":

![screen shot 2017-03-08 at 10 48 14](https://cloud.githubusercontent.com/assets/65613/23698686/bfd873a2-03ec-11e7-8f58-3caddb483d4c.png)

**Comment by Malmer** [comment]
Maybe it is time to remove this option completely in editor 2 considering it is deprecated. That, or remove the deprecation flag.

**Comment by ragnard-king** [comment]
Fix merged with better default as in editor1. Coming in update shortly.
