### ISSUE TITLE
material tags field not highlighted when selected - unclear UI

### ISSUE THREAD

**Issue by saracglaser** [defold/editor2-issues#568]
Unclear how you are supposed to att a tag to the tags field. When selecting the empty box nothing happens and it's not highlighted with a red line as the other fields where i says 'no content in table'.

Intuitive action for me was to double-click, which doesn't work. Ended up trying right-click and saw the add button.

![screen shot 2017-03-08 at 15 28 17](https://cloud.githubusercontent.com/assets/10513220/23707918/6588f1a6-0414-11e7-9071-6c76644b6a2f.png)
![screen shot 2017-03-08 at 15 28 08](https://cloud.githubusercontent.com/assets/10513220/23707923/675a448a-0414-11e7-9464-610cd481dc39.png)

### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>bf70ee4bff04e38c44e20bb6f60b4eaec4b971be</td></tr>
<tr><td>Build time</td><td>2017-03-07T10:01:03.171927</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by saracglaser** [comment]
Better images
![screen shot 2017-03-08 at 15 33 51](https://cloud.githubusercontent.com/assets/10513220/23707995/ad63e4c2-0414-11e7-865a-7a6706a0c115.png)
![screen shot 2017-03-08 at 15 33 45](https://cloud.githubusercontent.com/assets/10513220/23707996/ad65bb8a-0414-11e7-9ec7-862508fd56cc.png)

**Comment by AGulev** [comment]
<img width="535" alt="image" src="https://user-images.githubusercontent.com/2209596/50694316-db4dcc80-1039-11e9-8a75-c0b50cb965ee.png">
