### ISSUE TITLE
Wrong GUI node parenting

### ISSUE THREAD

**Issue by SpycerLviv** [defold/editor2-issues#569]
### Expected behaviour
Icons should be in checkboxes and Editor 2 shows that.
![image](https://cloud.githubusercontent.com/assets/15369367/23708674/6fa5f444-041f-11e7-985d-d974ec11bd24.png)
### Actual behaviour
However it doesn't work and this is how it looks in Editor 1:
![image](https://cloud.githubusercontent.com/assets/15369367/23708751/b4ee60e0-041f-11e7-92da-a309a62d0e44.png)
### Steps to reproduce
Add nodes and drag-n-drop one of them into another (maybe you need to make one more clone of parent node)
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>bf70ee4bff04e38c44e20bb6f60b4eaec4b971be</td></tr>
<tr><td>Build time</td><td>2017-03-07T10:01:03.171927</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
This is a validation issue, there are id-collisions in the gui.

**Comment by AGulev** [comment]
<img width="326" alt="image" src="https://user-images.githubusercontent.com/2209596/50694419-2536b280-103a-11e9-9034-a9e8b560f33d.png">
Can't reproduce it 1.2.144
Validation works well. 
Pls, reopen issue with more information, if you reproduce the issue.
