### ISSUE TITLE
Game objects remain, but hidden, in collections after deletion [DEFEDIT-880]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#573]
In certain cases when deleting game objects from collections the scripts and objects remain in the scene and run when building. They are not visible in the outline though, only in the collection file when opening it in a text editor. 

Not sure how to repro, but this has happened several times for me. Most likely candidate is if a game object has been copied and then removed. Or when copy pasting between collections (which also sometimes produces an error).

**Comment by Malmer** [comment]
Last time I got the issue was this situation:
* Hade go hierarchy like this:
Go
  Child go
      Sprite on child go
      Script on child go
* Was embedded in one collection
* Created a new collection
* Copied and pasted the go
* Deleted the original go
* Clicked the new child go gave an error. 
* Saved
* At this point the original child go still existed  in the original collection file. But didn't exist in the new collection file. It did exist in the hierarchy outline though of the new collection, but not in the original.

**Comment by erikangelin-king** [comment]
Got an NPE:
Created go file - go1
Created collection - c1
Added go1 to c1
Added game object g2 to go1 in c1
Added sprite and script on g2
Created c2
Embedded c1 in c2
Created c3
Copied go1 from c1
Pasted to c3
Clicked go2 in outline

**Comment by RagnarSvenssonKing** [comment]
Great find! An even simpler repro:

* Create collection - c1
* Add go1 to c1
* Add go2 to c1 under go1
* Copy go1
* Create colleciton - c2
* Paste (go1)
* In c2, select go2

**Comment by ragnard-king** [comment]
Not actually related to copy/paste, trivial repro:

Create a collection:
- Collection
  - go1
    - go2
      - go3

Delete go2.
Save.
Go3 still in saved file, but not parented.

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
