### ISSUE TITLE
Creating Directories for .git Failed

### ISSUE THREAD

**Issue by EWonzen** [defold/editor2-issues#575]
Newbie, just downloaded the editor2 beta, try to start the project, gets this message:

![defold import git fail message](https://cloud.githubusercontent.com/assets/10237662/23730214/2cdef36c-041b-11e7-9487-ca11f8274ce3.png)

**Comment by erikangelin-king** [comment]
The location path looks weird, are you sure you're allowed to write files there? Try putting your project under your home directory :)
