### ISSUE TITLE
Engine crash on remote device when building to target

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#578]
Whenever I build with the target of a device over wifi the target device engine crashes (iOS). Doing the same from editor 1 works fine.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>bf70ee4bff04e38c44e20bb6f60b4eaec4b971be</td></tr>
<tr><td>Build time</td><td>2017-03-07T10:01:03.171927</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by rgrams** [comment]
I believe this is explained in this forum post: https://forum.defold.com/t/is-latest-dmengine-apk-from-d-defold-com-compatible-with-latest-editor2-builds/6162/5

**Comment by RagnarSvenssonKing** [comment]
Is this when you have manually specified an IP address? After having investigated a bit, it seems like that will crash the engine 100%.

**Comment by Malmer** [comment]
Yes. Both for android and ios.

**Comment by RagnarSvenssonKing** [comment]
Fixed
