### ISSUE TITLE
Html5 build failed with getting started tutorial project

### ISSUE THREAD

**Issue by massanchik** [defold/editor2-issues#579]
### Expected behaviour
buld html5
### Actual behaviour
error
### Steps to reproduce
try to build for html5
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>10d986fd114fdf98730fb7d4ad316ba9f5b0213f</td></tr>
<tr><td>Build time</td><td>2017-03-09T16:16:06.019846</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=ee8e694d021d411a8c6e4272cb111cbe'>ee8e694d021d411a8c6e4272cb111cbe</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
http://forum.defold.com/t/in-defold-2-how-can-i-build-html5/6113

**Comment by RagnarSvenssonKing** [comment]
Fixed!
