### ISSUE TITLE
Label scale doesn't update in editor viewport

### ISSUE THREAD

**Issue by rgrams** [defold/editor2-issues#581]
### Expected behaviour
Changing a Label component's scale in the properties panel should update it's size in the viewport. (as it does in Editor 1.)

### Actual behaviour
Nothing happens. Labels always appear at their base size in the viewport. 

### Steps to reproduce
Add a Label component to a GO and try changing its scale property. 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>10d986fd114fdf98730fb7d4ad316ba9f5b0213f</td></tr>
<tr><td>Build time</td><td>2017-03-09T16:17:03.468797</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
Fixed in merged PR defold/defold#1536
