### ISSUE TITLE
Engine freezes when selecting components

### ISSUE THREAD

**Issue by Deynne** [defold/editor2-issues#583]
Every time i open anything in the project and try to select its components, it freezes.
[hs_err_pid3888.log.zip](https://github.com/defold/editor2-issues/files/838108/hs_err_pid3888.log.zip)

**Comment by erikangelin-king** [comment]
http://forum.defold.com/t/defold-2-freezes/6148/4

**Comment by erikangelin-king** [comment]
Hi! I can't repro this locally. Could you please try to upgrade your opengl drivers?

**Comment by Deynne** [comment]
Hi! I did that and it seems to be working fine now. Thanks! Sorry for the bothering...

**Comment by erikangelin-king** [comment]
Thanks for reporting, I'm closing this issue.
