### ISSUE TITLE
Scene editor renders components in the wrong order [DEFEDIT-848]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#584]
I have a project with a bunch of game objects containing sprites and a tilemap. The sprites are rendered in the correct z-order, but the tilemap is rendered behind the sprites even though it should be rendered in front of the sprites. The game itself renders the components in the correct order while the game is running and Editor 1 renders in the correct order as well.

The project: https://github.com/britzl/liverunner
Open collection level1.collection. The tilemap with the level geometry should be rendered in front of the sprites used for hills and clouds.

**Comment by jeevank** [comment]
There's a video demo of this here: https://forum.defold.com/t/hide-show-gameobject-collection-checkbox-in-properties/3687/9

**Comment by matgis-king** [comment]
The Z ordering issue should hopefully be fixed now. A new build should appear shortly.
