### ISSUE TITLE
Editor becomes unresponsive when game prints a lot

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#586]
### Steps to reproduce

Extreme example: (allthough still happens in more realistic scenarios)
```
function update(self,dt)
for i=1,10000 do
print("foo")
end
end
```

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.99</td></tr>
<tr><td>Defold sha</td><td>10d986fd114fdf98730fb7d4ad316ba9f5b0213f</td></tr>
<tr><td>Build time</td><td>2017-03-09T16:17:03.468797</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
See https://github.com/defold/editor2-issues/issues/322
