### ISSUE TITLE
Editor 2 freezes on Linux (Gallium OS) when clicking on a PNG or trying to report an issue

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#587]
From the forum: https://forum.defold.com/t/editor-freezing-when-trying-to-report-a-bug-open-a-png-on-linux-editor-2/6323

Using the editor2 on linux, if I try to open a png within the editor by double clicking it, it'll lock up the editor. Not an issue since I clicked the png by mistake. Figured I'd try to report the bug, but couldn't since the same thing happened on the bug report menu.

I am running the latest build of GalliumOS and the Editor 2 64-bit

**Comment by erikangelin-king** [comment]
Same thing on ubuntu

**Comment by erikangelin-king** [comment]
See https://github.com/defold/editor2-issues/issues/428 for suggested fix

**Comment by ragnard-king** [comment]
A fix for this has been merged and will be available in an update shortly.
