### ISSUE TITLE
Always have localhost available as a remote target

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#593]
If a manual IP is entered then no localhost is available in the list. Make it always exist on top of the list as an option.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>793a67f68264eb276cc177f2836bc698a83b96f6</td></tr>
<tr><td>Build time</td><td>2017-03-15T16:59:39.780482</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed
