### ISSUE TITLE
Viewport performance is slow when using medium poly count meshes

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#596]
Frame rate in the viewport is really slow (like max 10 fps slow) when using a model with 10k triangles. This is on a brand new MacBook Pro. Same geometry runs fine on a low end budget phone from 2013.
 
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
