### ISSUE TITLE
Exception while building HTML5

### ISSUE THREAD

**Issue by kaplad** [defold/editor2-issues#597]
### Expected behaviour 
 -Successful HTML5 build
### Actual behaviour
 - Exception in console
### Steps to reproduce
 - Create empty project
 - Load it in desktop app (macOS)
 - Run `Build HTML5` from menu
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:45:23.542322</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=4b9f19967a2a44e8a730768b215633db'>4b9f19967a2a44e8a730768b215633db</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
