### ISSUE TITLE
Editor1 to Editor2 change in url properties.

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#598]
### Expected behaviour
I have a collection within a collection, where the childed collection have scripts with url properties.
These url fields have been assigned with relative paths to the game-objects within the childed collection.

game.collection
* player.collection
* * beam.go
* * * script
* * ship1.go
* * * url = beam#script
* * ship2.go
* * * url = beam#script

This worked in editor1, but in editor2 I have to write the full url for it to work.
url = default:/player/beam#script

### Actual behaviour
Unless I change the url, the messages posted are sent out in the void.

### Steps to reproduce

1. Setup collection

game.collection
* player.collection
* * beam.go
* * * script
* * ship1.go
* * * url = beam#script
* * ship2.go
* * * url = beam#script

2. from ship1.go
msg.post(self.url, "post")

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<table>

**Comment by adamwestman** [comment]
I have a project I can invite you to, if interesting :)

**Comment by ragnard-king** [comment]
Hi buddy, could you please invite med to the project? ragnar.dahlen@king.com

**Comment by ragnard-king** [comment]
This is really a consequence of https://github.com/defold/editor2-issues/issues/600, which we are currently working on.

**Comment by ragnard-king** [comment]
Fix merged, will be available in update later today.
