### ISSUE TITLE
can't close script

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#599]
### Steps to reproduce
I don't know.Happened once. If happened more times, i will try to understand why.
<hr/>
![2017-03-18_14-36-16](https://cloud.githubusercontent.com/assets/2655263/24071650/a4afeafc-0be8-11e7-9134-7bbe956489fe.png)

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Falcula** [comment]
I have same problem

**Comment by matgis-king** [comment]
Might this be related to selecting **Close Others** from the tab context menu? Could you describe in more detail what you did?

**Comment by d954mas** [comment]
I don't know why it happened. I have a lot of scripts. Then i trying to close them, click to close button. I don't use context menu. Now i can't reproduce it.

**Comment by erikangelin-king** [comment]
Please reopen if it happens again!
