### ISSUE TITLE
collapsed name replace first underline symbol

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#601]
### Steps to reproduce
<hr/>
![2017-03-18_20-47-49](https://cloud.githubusercontent.com/assets/2655263/24074565/4b25e58e-0c1c-11e7-8304-8f137d37d095.png)

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
Quick fix if this happens because the `_` char is used to mark mnemonic char in the menu item - should escape these chars?
