### ISSUE TITLE
trying to open script in editor

### ISSUE THREAD

**Issue by Falcula** [defold/editor2-issues#602]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=a9ad1e943ef24568848deb7ff50791a7'>a9ad1e943ef24568848deb7ff50791a7</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed, new version should appear within 30-60 minutes
