### ISSUE TITLE
Tilemap make error

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#603]
### Expected behaviour
Edit tilemap
### Actual behaviour
Recieve error clojure.lang.ExceptionInfo: handler ':scene-play' in context ':global' failed at ':enabled?' with message '3'
java.lang.ArrayIndexOutOfBoundsException: 3
### Steps to reproduce
Add tilesource to tilemap and recieve error. 
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=ed22f717fe274e82b505171c813bcbe5'>ed22f717fe274e82b505171c813bcbe5</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update later today.
