### ISSUE TITLE
App crashes on android after hitting build

### ISSUE THREAD

**Issue by CandyFace** [defold/editor2-issues#609]
F/defold  (58511618): FATAL:ENGINE: Unable to load project file: 'http://null:49888/build/game.projectc'
### Expected behaviour
Application works, game starts loading

### Actual behaviour
Application crashes.

### Steps to reproduce
1. Connect phone to pc/mac
3. hit build in editor 2.0 (make sure you target the right address)

### Step to analyze
1. adb logcat -s defold
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>171fc6c2c8a850f276e3d2517d8677ba93d7643c</td></tr>
<tr><td>Build time</td><td>2017-03-21T17:37:36.467205</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by Malmer** [comment]
Same thing happens to me on iOS.

**Comment by RagnarSvenssonKing** [comment]
Is this when you have manually specified an IP address? After having investigated a bit, it seems like that will crash the engine 100%.

**Comment by CandyFace** [comment]
I haven't tried without specifying my ip, but yes that may be the reason. It worked prior to the newest engine release and a couple of editor 2 updates though. I'll remove my ip when I get home and see if that fixes the problem.

**Comment by CandyFace** [comment]
I have removed the ip (it says null because I left the field empty) then started dmengine up on my phone, chose the ip from the dropdown menu but the app still crashes.

**Comment by RagnarSvenssonKing** [comment]
Ok, I did not expect that. To be clear, you selected one of the IPs that were generated in the menu? It would be of great help if you check logcat again to see if there is different info regarding the crash, I'm assuming "'http://null:49888/build/game.projectc'" won't be there anymore. (That was the specific problem about the manually entered IP, it did not receive info from the SSDP broadcasting.)

**Comment by CandyFace** [comment]
Yes I selected the generated IP from the menu.

This is what i'm getting now from the log:
F/defold  (91058423): FATAL:ENGINE: Unable to load project file: 'http://0.0.0.0:61371/build/game.projectc'

**Comment by RagnarSvenssonKing** [comment]
Excellent, thanks, this really helps a lot!

**Comment by RagnarSvenssonKing** [comment]
Fixed

**Comment by subsoap** [comment]
I'm getting same error on Android

[Running on target 'Yifang-NX16A8116K' (192.168.0.102)]
INFO:ENGINE: Defold Engine 1.2.105 (719697b)
FATAL:ENGINE: Unable to load project file: 'http://192.168.0.117:63949/build/game.projectc'
INFO:DLIB: SSDP: Done on address 192.168.0.102

![2017-05-22 01_44_34-](https://cloud.githubusercontent.com/assets/409170/26299622/4f31e46a-3e90-11e7-9c80-24062fb0c11b.png)

Pressing build crashed the app. Tested with debug version of APK.

**Comment by Treynolds416** [comment]
Hi, I'm getting the exact same error. Running on my phone 192.168.0.13 (android 5.0)

In defold editor:
```
INFO:ENGINE: Defold Engine 1.2.144 (8def4b5)
FATAL:ENGINE: Unable to load project file: 'http://192.168.0.11:52802/build/game.projectc' (-1)
```

$ adb logcat -s defold
```
--------- beginning of system
W/defold  (12246): WARNING:CRASH: Number of modules exceeds capacity
I/defold  (12246): INFO:DLIB: Log server started on port 44805
I/defold  (12246): INFO:ENGINE: Engine service started on port 8001
I/defold  (12246): INFO:ENGINE: Defold Engine 1.2.144 (8def4b5)
I/defold  (12246): INFO:ENGINE: Loading data from: .
I/defold  (12246): INFO:ENGINE: Initialised sound device 'default'
I/defold  (12246):
I/defold  (12246): INFO:DLIB: SSDP: Started on address 192.168.0.13
I/defold  (12246): INFO:ENGINE: Defold Engine 1.2.144 (8def4b5)
F/defold  (12246): FATAL:ENGINE: Unable to load project file: 'http://192.168.0.11:52802/build/game.projectc' (-1)
I/defold  (12246): INFO:CRASH: Successfully wrote Crashdump to file: /data/data/com.defold.dmengine/files/_crash
```

**Comment by Treynolds416** [comment]
I'm getting the same error message, same sequence of events. It's worked once or twice, but I've tried restarting everything and can't replicate. Target shows up correctly in the editor (Android 5 phone connected correctly via usb), both IPs are correct.

$ adb logcat -s defold
--------- beginning of system
```
W/defold  (12246): WARNING:CRASH: Number of modules exceeds capacity
I/defold  (12246): INFO:DLIB: Log server started on port 44805
I/defold  (12246): INFO:ENGINE: Engine service started on port 8001
I/defold  (12246): INFO:ENGINE: Defold Engine 1.2.144 (8def4b5)
I/defold  (12246): INFO:ENGINE: Loading data from: .
I/defold  (12246): INFO:ENGINE: Initialised sound device 'default'
I/defold  (12246):
I/defold  (12246): INFO:DLIB: SSDP: Started on address 192.168.0.13
I/defold  (12246): INFO:ENGINE: Defold Engine 1.2.144 (8def4b5)
F/defold  (12246): FATAL:ENGINE: Unable to load project file: 'http://192.168.0.11:52802/build/game.projectc' (-1)
I/defold  (12246): INFO:CRASH: Successfully wrote Crashdump to file: /data/data/com.defold.dmengine/files/_crash
```

Also: when I try to use "Target IP" in the project menu, I get this error:
192.168.0.13 could not be reached from this host
