### ISSUE TITLE
Collection scaling property values doesn't save properly

### ISSUE THREAD

**Issue by CandyFace** [defold/editor2-issues#610]
Scenario: I have two collection files, the first with has a background image, the second collection is called "level" which inherits background. If you scale background (the collection file) from within the level file, then save and re-open the project, the scaling values has been reset 

### Expected behaviour
The values have been saved

### Actual behaviour
The values has been reset

### Steps to reproduce
1. Make two collection files, "background" and "level"
  -- background should hold a game object and a sprite image
  -- level should inherit background.
2. open level and scale background (the entire collection)
3. save, quit and re-open. 
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>88be500521808b73e9474915d8cdaa830137d467</td></tr>
<tr><td>Build time</td><td>2017-03-21T18:02:50.121806</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix has been merged and should be available in update shortly.
