### ISSUE TITLE
Editor window glitch

### ISSUE THREAD

**Issue by thardraved** [defold/editor2-issues#611]
### Actual behaviour
It happens when I open files with graphics (sprites, tilemaps, tilesets)

![2017-03-21 22 22 57](https://cloud.githubusercontent.com/assets/14955939/24166676/1fb90cee-0e85-11e7-8ba1-c68798e8fb27.png)
![2017-03-21 22 22 59](https://cloud.githubusercontent.com/assets/14955939/24166678/1fba93a2-0e85-11e7-99e9-0e91cef27991.png)
### Steps to reproduce
Actually I suppose that it's a hardware issue and don't really know how to reproduce it. I'm running on i3-6100 w/Intel hd graphics 530
<hr/>
<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>88be500521808b73e9474915d8cdaa830137d467</td></tr>
<tr><td>Build time</td><td>2017-03-21T18:02:50.121806</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
This might be a driver issue. Could you try downloading and installing the latest drivers for your Intel HD Graphics 530?

**Comment by thardraved** [comment]
I've already have the latest drivers installed. BTW, old Defold engine throws "can't find the name of intel icd opengl driver" error on opening graphics files, but few clicks on "OK" can solve it. Maybe it's connected somehow

**Comment by matgis-king** [comment]
Note, the corruption pattern appears similar to the screenshots attached to this Mozilla Firefox bug report: https://bugzilla.mozilla.org/show_bug.cgi?id=1267068

That post does not have a satisfying resolution though. Closed as "Works for Me". Links to a thread on Intels forum where some users report success with updated drivers, but the issue remains for others.

**Comment by RagnarSvenssonKing** [comment]
I have pushed a fix that might fix this issue, please try again and see if it's fixed.

**Comment by RagnarSvenssonKing** [comment]
I will close this issue for now, assuming it is fixed. Please submit a new issue in case it happens again (re-submitting will give us more valuable info about your GPUs).
