### ISSUE TITLE
"Missing Resource Build Error" Reports Missing From Wrong Asset

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#615]
When you build after a resource is missing/deleted that is used in the project you get an error, that error is showing that it is missing from the wrong location.

I removed a game object "lightning_strike.go" that was reported missing in "lightning_strike.go" while it was actually missing from a factory entry in a game object called "particles.go".

![screen shot 2017-03-23 at 13 50 50](https://cloud.githubusercontent.com/assets/5273682/24249777/d4511214-0fd4-11e7-969e-2b33e45a4d47.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed!
