### ISSUE TITLE
Crash on opening an image (probably duplicate of #587)

### ISSUE THREAD

**Issue by wrq** [defold/editor2-issues#616]
Version 1.2.100
2457607bde457837ffa1d9073480fd45bb2f8da5

cat /etc/*-release
DISTRIB_ID="elementary"
DISTRIB_RELEASE=0.4
DISTRIB_CODENAME=loki
DISTRIB_DESCRIPTION="elementary OS 0.4 Loki"
NAME="elementary OS"
VERSION="0.4 Loki"
ID="elementary"
ID_LIKE=ubuntu
PRETTY_NAME="elementary OS 0.4 Loki"
VERSION_ID="0.4"
HOME_URL="http://elementary.io/"
SUPPORT_URL="http://elementary.io/support/"
BUG_REPORT_URL="https://bugs.launchpad.net/elementary/+filebug"
VERSION_CODENAME=loki
UBUNTU_CODENAME=loki
cat: /etc/upstream-release: Is a directory

If I open the Getting Started Project with the Getting-started-assets, when I right click any of those files and select "Open", Defold locks up entirely, and I have to restart my machine to continue working.

**Comment by erikangelin-king** [comment]
Hi! This looks like https://github.com/defold/editor2-issues/issues/587, I'm guessing you tried to open a png?

**Comment by wrq** [comment]
I think you are right, sorry about that, I have updated the title of this bug.

**Comment by erikangelin-king** [comment]
No worries, thanks for reporting!

**Comment by ragnard-king** [comment]
A fix for https://github.com/defold/editor2-issues/issues/587 has been merged and will be available in update shortly.
