### ISSUE TITLE
Trying to add big image to image atlas

### ISSUE THREAD

**Issue by SpycerLviv** [defold/editor2-issues#617]
### Expected behaviour
Successful .atlas opening
### Actual behaviour
Clear screen and exception
### Steps to reproduce
I have tried several times add 2 big images to my atlas and every time occured "IndexOutOfBounds" exception. Next I successfully did it in Defold old editor, but in Defold2 I got this error.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>828f3490b76018594614a4c47eaaf6cb559f3bc2</td></tr>
<tr><td>Build time</td><td>2017-03-24T11:24:01.605700</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=183733445c66443393ff5b272ab49acc'>183733445c66443393ff5b272ab49acc</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
We will investigate! How large was the image you added?

**Comment by SpycerLviv** [comment]
Here is my atlas:
![image](https://cloud.githubusercontent.com/assets/15369367/24363644/25b79abe-1319-11e7-83c8-6dace319de3d.png)
![image](https://cloud.githubusercontent.com/assets/15369367/24363651/29395362-1319-11e7-9397-76d8becae7a2.png)
I've tried to add image 268x583 (big version of facebook F letter)

**Comment by ragnard-king** [comment]
Would you be able to send me an (exact) copy of the file you are trying to add? Or add me to a project that exhibits this error and contains the problematic images? I think it's probably more related to the image file attributes (type/components/ect) than size. I'm ragnar.dahlen@king.com.

**Comment by SpycerLviv** [comment]
I sent you an email.

**Comment by ragnard-king** [comment]
Thanks for the sample data, re-produced. 

The issue is related to the color-model, the image causing the problem is grayscale whereas the others that have been successfully added to atlas are RGB. A workaround until we've fixed the issue is to change the color model of the problematic image.
