### ISSUE TITLE
Editor 2 doesn't run if there is a problem with files

### ISSUE THREAD

**Issue by SpycerLviv** [defold/editor2-issues#618]
I have [this ](https://github.com/defold/editor2-issues/issues/617)bug in my project. When I restart editor and trying to open this project, Editor loads it but turns off after loading window.

**Comment by ragnard-king** [comment]
I can reproduce the original bug, but I can't reproduce this issue, ie. the editor crashing on startup. For me it loads fine, but opening the atlas fails (which is a bug we of course should fix).

Can you still reproduce the issue (after latest update?)
