### ISSUE TITLE
Ctrl+C in atlas

### ISSUE THREAD

**Issue by SpycerLviv** [defold/editor2-issues#619]
### Steps to reproduce
Try to copy any image via Ctrl+C in image atlas

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>828f3490b76018594614a4c47eaaf6cb559f3bc2</td></tr>
<tr><td>Build time</td><td>2017-03-24T11:24:01.605700</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2a428423bd484666903eb588be6e19a3'>2a428423bd484666903eb588be6e19a3</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fixed.
