### ISSUE TITLE
[Linux] Spine model doesn't show

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#62]
The spine model in our examples test app doesn't show

**Comment by RagnarSvenssonKing** [comment]
Fix will come on monday!
<img width="682" alt="screen shot 2016-09-17 at 12 04 33" src="https://cloud.githubusercontent.com/assets/18021074/18607528/ef4b1644-7cce-11e6-970a-b52eeb6f5a26.png">

**Comment by RagnarSvenssonKing** [comment]
Fixed
