### ISSUE TITLE
error when add node in not default layout

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#620]
### Expected behaviour
adding a node to gui.
### Actual behaviour
get error
### Steps to reproduce
1)Open gui node.
2)Open not default layout(for example landscape)
2)Try to add node
3)get error
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=99b42defcb2e41d4bfa1a21ba910dc80'>99b42defcb2e41d4bfa1a21ba910dc80</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
A fix has been made and will be available in an update later today.
