### ISSUE TITLE
Frame selection in outline

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#622]
Ability to frame the current selection in outliner

**Comment by ragnard-king** [comment]
This should already be possible, see "Scene -> Camera -> Frame Selection". The shortcut keybinding does not currently work on macOS though https://github.com/defold/editor2-issues/issues/425.

**Comment by Jerakin** [comment]
Depends, it doesn't work on mac as you say so I can't test it. When I use the menu way it only frames the scene not the outliner. 

But in a recent update the outline in the selection behaves better anyway, when I reported this the item you selected in the scene didn't get focus in the outliner. So it was hard to find it in the hierarchy. Maybe that is enough.

**Comment by ragnard-king** [comment]
We merged some big changes to how manipulators (and selection) work yesterday so that may be what you are seeing. That the keybinding doesn't work is of course poor, will see if I can fix it a bit sooner.

**Comment by Jerakin** [comment]
The editor frames stuff as it should, so this can be closed
