### ISSUE TITLE
Do not lock the editor when building

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#623]
Building takes a long time, I want the ability to continue working when building.

**Comment by ragnard-king** [comment]
Locking the editor is a quick-fix for an implementation constraint we currently have, but one we definitely aim to remove.

**Comment by matgis-king** [comment]
There's now a progress bar while building, and you can keep working with the editor as it builds.

**Comment by subsoap** [comment]
@matgis-king AWESOME!
