### ISSUE TITLE
Cannot run html5 build [DEFEDIT-879]

### ISSUE THREAD

**Issue by ToooooooBig** [defold/editor2-issues#627]
### Expected behaviour
HTML5 build is built and launched.
### Actual behaviour

`java.lang.IllegalArgumentException: No implementation of method: :resource-type of protocol: #'editor.resource/Resource found for class: nil`

### Steps to reproduce
Create new project, try to build html5 build.
or
[Vivid.zip](https://github.com/defold/editor2-issues/files/873714/Vivid.zip)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>32937772c9f108411b28a4293c74fa6f0549545b</td></tr>
<tr><td>Build time</td><td>2017-03-27T15:09:03.579207</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=44cb1a7db5b94a0aa7c006dea4aef14f'>44cb1a7db5b94a0aa7c006dea4aef14f</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Hey! I could not reproduce this issue using the project you supplied (thanks for that by the way!). Looking at the error report, it seems like this happened:
1) There was an error in the "Build Errors" view
2) You tried to open that file by clicking on the error
3) The reported error happened as a result of trying to open that file

To investigate this further, I would need to know about the first error from 1). Could you post a screen shot of what that error looked like? Thanks!

**Comment by ToooooooBig** [comment]
Hey!

Thanks for the prompt response!

When I try to build game for html5, in the left bottom corner I can see "Building..." message and then this error appears: http://i.imgur.com/iDYb15S.png.
After some time "Building" message is replaced with the "Ready" and nothing happens.

As far as I understood, the error comes from the default logo.png file. In order to check it, I deleted this file and during the build I can see the following behavior: http://i.imgur.com/7gdGqh4.png. So basically it is the same.

I tried to download the latest version of IDE, but the error still reproduces.
I tried to delete logo.png and everything associated with it. The result you can see on the second screenshot.

In the end I can build desktop version without any problem, but html5 build is still inaccessible.
So I would appreciate any piece of advice regarding solving this problem.

**Comment by ToooooooBig** [comment]
I believe I submitted the project without default logo.png.
Here is the project with the picture and all the objects associated with it.
[Vivid.zip](https://github.com/defold/editor2-issues/files/876445/Vivid.zip)

**Comment by RagnarSvenssonKing** [comment]
Ouch, I think I know what it is. I believe it's looking for native shared libs in the wrong place, they are needed to compile the textures. We will fix it! Thanks for the great help in reporting.
