### ISSUE TITLE
3D objects sometimes disappear from the view

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#628]
Not sure why and when, but it happens to me a lot. I have four 10k models. Only 2 are shown.

They all share the same game object.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>ea12592c0b08b510cf939576568f5620bb6bac4a</td></tr>
<tr><td>Build time</td><td>2017-03-28T10:24:14.739785</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Is this perhaps same as the other issue when rotating the camera?

**Comment by Malmer** [comment]
I am very sure that it is. Closing.
