### ISSUE TITLE
Resizing a sidebar locks the system

### ISSUE THREAD

**Issue by henriquecode** [defold/editor2-issues#634]
It's started Defold normally, but whenever need resize sidebar of the objects locks the system.

System: Ubuntu 14.04

------------------------------------------------------------------------------------------------------
A fatal error has been detected by the Java Runtime Environment:

 SIGSEGV (0xb) at pc=0x00007f9990c632c4, pid=3480, tid=0x00007f9954385700

JRE version: Java(TM) SE Runtime Environment (8.0_102-b14) (build 1.8.0_102-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (25.102-b14 mixed mode linux-amd64 compressed oops)
 Problematic frame:
C  [libdrm_nouveau.so.2+0x32c4]

Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again

 If you would like to submit a bug report, please visit:
   http://bugreport.java.com/bugreport/crash.jsp
 The crash happened outside the Java Virtual Machine in native code.
 See problematic frame for where to report the bug.

---------------  T H R E A D  ---------------

Current thread (0x00007f99c8333000):  JavaThread "JavaFX Application Thread" [_thread_in_native, id=3505, stack(0x00007f9954285000,0x00007f9954386000)]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000000007db94

**Comment by RagnarSvenssonKing** [comment]
Could you start with trying to update your drivers? We guess that the crash originates from the driver when the opengl surface is being resized.

**Comment by ragnard-king** [comment]
Tested on Ubuntu 16.04 without nouveau driver and it works there. If you can't upgrade or are already on latest version you could also try using the official nvidia driver to determine if it's a driver issue.

**Comment by henriquecode** [comment]
Thanks very much!! The problem was in drivers. =)
