### ISSUE TITLE
Error when accessing Preferences

### ISSUE THREAD

**Issue by kgoyon** [defold/editor2-issues#636]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.101</td></tr>
<tr><td>Defold sha</td><td>da28295bcf63b94c21d7e77496ff1ccecab6a1d7</td></tr>
<tr><td>Build time</td><td>2017-03-31T14:53:30.355104</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=81a38fd83544492c92cf76b8b34fc3d3'>81a38fd83544492c92cf76b8b34fc3d3</a></td></tr>
<table>

**Comment by CandyFace** [comment]
A bit more info about the error:

```java
clojure.lang.ExceptionInfo: handler ':preferences' in context ':global' failed at ':run' with message  
'javafx.scene.control.TabPane cannot be cast to javafx.scene.layout.Pane'   
java.lang.ClassCastException: javafx.scene.control.TabPane cannot be cast to    
javafx.scene.layout.Pane
```

**Comment by erikangelin-king** [comment]
Thanks for reporting, fix merged.
