### ISSUE TITLE
I've gotten this error opening Preferences menu

### ISSUE THREAD

**Issue by albertopiantanida** [defold/editor2-issues#637]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.101</td></tr>
<tr><td>Defold sha</td><td>da28295bcf63b94c21d7e77496ff1ccecab6a1d7</td></tr>
<tr><td>Build time</td><td>2017-03-31T14:53:30.355104</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c92842eca5074453b0da707d27211025'>c92842eca5074453b0da707d27211025</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
https://github.com/defold/editor2-issues/issues/636https://github.com/defold/editor2-issues/issues/636

**Comment by erikangelin-king** [comment]
Duplicate apparently fixed
