### ISSUE TITLE
add collection to itself

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#638]
### Expected behaviour
error window
### Actual behaviour
app crash
### Steps to reproduce
1)create collection
2)try add collection to itself
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.100</td></tr>
<tr><td>Defold sha</td><td>1afccdb2cd42ca3bc7612a0496dfa6d434a8ebf9</td></tr>
<tr><td>Build time</td><td>2017-03-17T11:46:16.030571</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
https://github.com/defold/editor2-issues/issues/365
