### ISSUE TITLE
[Windows] Java attempts to write registry without administrative rights

### ISSUE THREAD

**Issue by jakob-pogulis-king** [defold/editor2-issues#64]
When starting the editor the following message is displayed in the Command window: `WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.`. I'm not sure why the editor would need administrative permissions to write to an area that is not specific to the user.

This is a minor issue since the editor still runs.

**Comment by erikangelin-king** [comment]
From below links it seems this issue is mostly cosmetic:
http://bugs.java.com/bugdatabase/view_bug.do?bug_id=8139507
https://bugs.openjdk.java.net/browse/JDK-8146335
https://bugs.openjdk.java.net/browse/JDK-8139507

**Comment by erikangelin-king** [comment]
Closing as the settings we use are properly saved and restored.
