### ISSUE TITLE
iPhone connected via cable reports self-assigned IP to target discovery

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#641]
iPhone connected via cable reports self-assigned IP (169.x.x.x) to target discovery.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>3862f55e1f5ad15746a19618f5d875fbe2006df8</td></tr>
<tr><td>Build time</td><td>2017-04-03T15:50:21.138694</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Is there any chance it was this issue: https://github.com/defold/editor2-issues/issues/684

**Comment by Malmer** [comment]
Probably not. But I will test.

**Comment by Malmer** [comment]
Seems to be working correctly now. So it was probably fixed then. Will reopen if problem occurs again.
