### ISSUE TITLE
[Linux] Open project opens a new instance of the editor

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#65]
When pressing Ctrl+O from and opening a new project, a new instance will load, and place the window behind the currently open instance.

**Comment by RagnarSvenssonKing** [comment]
So the issue is in fact that the window opened behind the current window, right? The new window when you open a project is by design.

**Comment by mathiaswking** [comment]
Yes, that's the issue then

**Comment by erikangelin-king** [comment]
Problem sovlded - can no longer open project :P
