### ISSUE TITLE
error when changing tileset image and updating tilesource

### ISSUE THREAD

**Issue by jonasan-c** [defold/editor2-issues#650]
![defold_error2](https://cloud.githubusercontent.com/assets/26818749/24753699/31aa2512-1acb-11e7-856a-89ed444856ec.png)

I have encountered a problem which occurs when I attempt to update the png image for one of my tilesource components for a tilemap.

The tilesource component is already set up and using the currently stored png file, everything working fine.

I then have two approaches which I have tried to update the png which the tilesource uses:

a) I simply drag and drop the new editted png image and overwrite the file in the game directory in the editor. This prompts me if I want to overwrite and I click yes. If i double click and load the tilesource component it appears to be using the new image as expected. However, trying to build the game produces the error visible in the attatched image.

b) In case the approach i took was not as intended, I tried an alternative which involved opening the tilesource component I wish to update and assigning it a different png for its image (i.e. not the image I intend to update). I then delete the image I wish to update from the project, and then recopy the new editted image into the project in the editor. I then change the tilesource image back to the newly copied image. Everything appears to work fine, the tilesource component in the editor shows the new set of updated tiles as expected.... but building the game throws exactly the same error in the console and fails to build.

The first couple of times I encountered this error I ended up having to remove the image, tilesource and its associated tilemap from the project, copy the image and then redo the tilesource and tilemap components before I could get the game to run again, which clearly cannot be the intended use pattern.

Susequently I have discovered through testing that when I have followed either apporoach a) or b) and the game has failed to build with the above error, if I then close the editor and restart it with the same project then the updated tilesource is still present but now the game will build without throwing the error.

So currently I am simply restarting the editor every time I update my tilesource image files and get this error. If restarting the editor is necessary by design in this situation then the editor should prompt me to restart so that I avoid this build error, but (assuming its possible) it would clearly be better if this wasn't necessary and the error did not occur.

Thanks ;)
jonasan (Defold Forum)

**Comment by jonasan-c** [comment]
I have just been adding a further tilemap to my map object (so that the new tilemap can be drawn at a different z-level as an overlay) and have encountered the same problem.

I add a new image, new tilesource, new tilemap component, and then add that from file to my map game object. All seems fine, but building the game produces the exact same error, and restarting the editor builds as normal just as above.

Also, forgot to mention in case it is important: I am using the 64-bit Windows version of editor 2.0

**Comment by RagnarSvenssonKing** [comment]
Sorry to hear about these problems!
The design is that you should have every image file in your project tree, edit them in an image editor and that should (within a second) update the image in the Defold editor, both in the scenes and when you build it into a game. That's it! So basically everything you are doing here should be seen as workarounds to a few bugs. We haven't tested image editing in a while so most likely we have broken it. Sorry! We will investigate and add more tests for this so we can catch it in the future.

**Comment by ragnard-king** [comment]
A fix for this issue has been merged and will be available in an update within an hour or so. Thanks for the report!

**Comment by jonasan-c** [comment]
Excellent, thanks for the prompt fix.
