### ISSUE TITLE
curve editor

### ISSUE THREAD

**Issue by kapw001** [defold/editor2-issues#651]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>dee1ffe137373f4e3ebf89e92b8cb3a8e3418ec8</td></tr>
<tr><td>Build time</td><td>2017-04-06T17:32:00.344916</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>x86</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=10815f019bfb40d28f99236145668566'>10815f019bfb40d28f99236145668566</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Could you try updating your graphics drivers and see if that changes anything?
