### ISSUE TITLE
Icon colors [DEFEDIT-1064]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#654]
All "new item" icons has the same color - too hard to find needed item for creation.
Would be great to have some color differents of icons depends on component(item) type  (green for physycs, gray for code, blue for models etc - or something like this)

![2017-04-07_17-13-23](https://cloud.githubusercontent.com/assets/2209596/24803958/91928a06-1bb5-11e7-9989-0bdd21c1eb86.png)

**Comment by AGulev** [comment]
I see that icons in Assets menu alredy colored. Would be great to make the same in "New" menu.
![2017-04-08_18-38-06](https://cloud.githubusercontent.com/assets/2209596/24830243/87fd69d6-1c8a-11e7-90e2-dafdf8d698a8.png)

**Comment by RagnarSvenssonKing** [comment]
Three errors in the menu too:
Camera Object => Camera
Collection Factory Object => Collection Factory
Factory Object => Factory
