### ISSUE TITLE
 Unexpected eof for socket connection.

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#655]
### Expected behaviour
dmengine runs when I build the project
### Actual behaviour
in console:
WARNING:DLIB: Unexpected eof for socket connection. 

and dmengine freeze with white screen and then crashed
Crashlog in the file

[dmengine_crash_log.txt](https://github.com/defold/editor2-issues/files/908279/dmengine_crash_log.txt)

### Steps to reproduce
just build the project using Cmd+B - sometimes dmengine freeze with warning.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>e41546be9f07d669d1675d079e786788cd9b8f85</td></tr>
<tr><td>Build time</td><td>2017-04-07T15:07:15.541900</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by AGulev** [comment]
@RagnarSvenssonKing I see you set the tag "engine"
Just in case : reproduced only in Editor2  (maybe because there are engine version 1.2.102, i don't know)

**Comment by RagnarSvenssonKing** [comment]
Alright, thanks for the extra info! It might be editor2 after all then.

**Comment by AGulev** [comment]
@RagnarSvenssonKing 
I found simple way for bug reproduction:
1. Build the project Cmd+B
2. Do not close the opened dmengine
3. Build the project Cmd+B one more time

**Comment by AGulev** [comment]
This really really hinders work. I making "Force Quit"  dmengine 7-9 times per day =(

**Comment by RagnarSvenssonKing** [comment]
Sorry, I will start working on it right away!

**Comment by AGulev** [comment]
Thank you very much!!!!

**Comment by RagnarSvenssonKing** [comment]
I get the message "WARNING:DLIB: Unexpected eof for socket connection.", but I can't get it to hang or crash. It works every time I build&run without terminating the game first. Could you try in another project (like the runner template or similar) to see if you have the same problem there? The crash log suggests that it could be related to how the content has been loaded before rebooting the engine.

**Comment by AGulev** [comment]
yes, you right with other project all fine.
I see the "WARNING:DLIB: Unexpected eof for socket connection." message but it works.
What can I provide you for helping solve the problem?

**Comment by RagnarSvenssonKing** [comment]
Would you mind me getting access to your project?

**Comment by RagnarSvenssonKing** [comment]
Thanks! ragnar.svensson@king.com

**Comment by RagnarSvenssonKing** [comment]
Excellent, got the crash now! Thanks a lot, will let you know when I find the reason.

**Comment by RagnarSvenssonKing** [comment]
Ok, I have a theory. If you have the time, you could help me verify it!
* I think that the crash happens while we load resources async (I saw the async_load you are using)
* When you reboot the running engine (build, Cmd+B), the engine loads resources over the network
* Editor2 serves the resources over the network *incredibly slow*. This is a separate issue which I was unaware of, will look into this too.

So I think that the crash comes from an unlucky combination of these things. I will of course fix the crash too.

Could you try to provoke the crash after changing config.lua:
```lua
M.MSG_LOAD = hash("async_load")
```
to
```lua
M.MSG_LOAD = hash("load")
```
I could not get the crash after doing sync loading, but the game hangs with a white screen for long times while loading resources *incredibly slow*.

**Comment by RagnarSvenssonKing** [comment]
574 resources loaded, 300 msec/resource (OMG!!!) => 3 minutes of loading.. this is embarrassing. :)

**Comment by AGulev** [comment]
I have no crash if I change "async_load" to "load". In my case loading time (with a white screen) something about 25 seconds.
Strange, but when I back async_load it works without crashes. Only long load O_o

**Comment by AGulev** [comment]
In editor1 do not closing the dmengine is a way to faster project loading.
Now to close dmengine is faster way. 
But issue is that sometimes I forget to close dmengine...

**Comment by RagnarSvenssonKing** [comment]
It's now around 1000 times faster, takes a second to load it. :) Each resource is around 0.3 msec. Will look at the crash now. I'll let you know when the fixes are available in an update.

**Comment by RagnarSvenssonKing** [comment]
Sorry for the delay, it was really hard to find the reason of the "Unexpected EOF", which in fact turned out to be a bug in Java. Found a workaround though! A fix is up for review after which it will be merged and released. We also found and fixed the crash in the engine. As a bonus the loading is also faster because of more efficient etags-handling.

**Comment by AGulev** [comment]
Awesome news!

**Comment by RagnarSvenssonKing** [comment]
Fixed!
