### ISSUE TITLE
Double clicking a game.project file launches Editor 2 but not the project [DEFEDIT-1523]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#658]
If you double click a game.project file Editor 2 launches, but it doesn't open the project as I would have expected. Instead you end up with the normal Open Project dialog.

Tested on OSX Sierra.

Reported on the forum: https://forum.defold.com/t/editor-2-minor-issues/7266

**Comment by subsoap** [comment]
I tested associating game.project with Defold in Windows 10 and it doesn't work for opening that project either. This would be great to have.

**Comment by adamwestman** [comment]
I seem to recall this working before, so it might be that the open project dialogue addition broke the functionality
