### ISSUE TITLE
Git operations can take a ridiculous amount of time

### ISSUE THREAD

**Issue by RagnarSvenssonKing** [defold/editor2-issues#66]
STR:
1) Moderately sized project
2) Save-all to get a lot of diffs
3) Shift-select all of them in the Changes view, right-click for Revert
Wait.........zzzzz

**Comment by ragnard-king** [comment]
@RagnarSvenssonKing Fixed by https://github.com/defold/defold/pull/912?

**Comment by RagnarSvenssonKing** [comment]
Yes! 👍
