### ISSUE TITLE
Default values in game.project are nil when got via sys.get_config?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#663]
width and height for example have to be manually edited otherwise they will be nil if the user expects to be able to get those default values with sys.get_config. When clicking the make default button in the editor it removes the values in the actual file as well. Maybe instead of doing that it populates the text file itself with all of the builtin default values.

**Comment by subsoap** [comment]
Still need this.

**Comment by britzl** [comment]
DEF-3395. This will be released in 1.2.136.
