### ISSUE TITLE
Lack of collision shape on go components not detected in editor, crashes running app [DEFEDIT-890]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#664]
Currently a go with a collision object but without a collision shape gives no error message, project builds, but crashes.

**Comment by subsoap** [comment]
Seems this has already been fixed in latest update!

**Comment by matgis-king** [comment]
Nah, the issue still remains. A fix is in review, though!

**Comment by matgis-king** [comment]
The fix has been merged.
