### ISSUE TITLE
Toggle visibility of objects in scene editor

### ISSUE THREAD

**Issue by dapetcu21** [defold/editor2-issues#668]
It's currently very difficult to edit a complex scene, especially one with a lot of objects that at runtime would be normally hidden with code.

Being able to have a visibility checkbox for each node (which doesn't affect the runtime), would be a great addition. 

I remember using the disable box in Unity for this, but that was annoying because it would affect the runtime and I would forget to tick it again before running the game and things would break.

For example, in my `level.collection` I have a bunch of separate GUI nodes that render different UI panels (pause menu, for example) which are not all opened at the same time. So, trying to edit `level.collection` becomes impossible:

<img width="1069" alt="screen shot 2017-04-12 at 15 23 43" src="https://cloud.githubusercontent.com/assets/428060/24957527/a9b2b92a-1f94-11e7-9171-e776527f2116.png">

**Comment by AGulev** [comment]
I think it can be linked with https://github.com/defold/editor2-issues/issues/899 and https://github.com/defold/editor2-issues/issues/681

**Comment by matgis-king** [comment]
You can now toggle individual object visibility from the menu. We will add toggles to the Outline at a later stage.
