### ISSUE TITLE
Wrong a click zone in the curve editor [DEFEDIT-906]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#673]
Anchor poits has wrong click zone
![bug2](https://cloud.githubusercontent.com/assets/2209596/24966633/317f70a8-1fb0-11e7-9d37-f1325ba86bee.gif)

**Comment by subsoap** [comment]
The click zone appears to be at the wrong scale compared to the node sizes. It's at the **very** top left corner of the control nodes.
