### ISSUE TITLE
After SAVING got this error. cant continue developing/running project [DEFEDIT-892]

### ISSUE THREAD

**Issue by AgentSasori** [defold/editor2-issues#675]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>cf1b5b2a6804fdddf16c4d13064f431c5f62a60b</td></tr>
<tr><td>Build time</td><td>2017-04-12T16:55:43.267858</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c0350f5557de42f08fc2ad591ba199d9'>c0350f5557de42f08fc2ad591ba199d9</a></td></tr>
<table>

**Comment by AgentSasori** [comment]
Same with editor 1... WTF?

**Comment by subsoap** [comment]
Look at your files and sort by date, try renaming most recently edited files, then see if you can open again.

**Comment by matgis-king** [comment]
It seems this can happen if something in your project is referencing a `.font` file that does not have a `.ttf` file selected for its Font property. Any attempts to build the project will will fail with a cryptic error message in both the old and the new editor.

We're working on a fix for this, but in the meantime you should be able to get back on track by ensuring all your `.font` files have Font resources specified. If you open the `.font` in Editor 2, you should be able to see a light-blue outline around the Font field in the Property Editor. Simply click the `...` button and select the default builtin font and retry building your project.

![font-missing-ttf](https://cloud.githubusercontent.com/assets/22448941/25000015/010b6f0e-2040-11e7-81c4-3f9d2dc21886.png)

**Comment by matgis-king** [comment]
A fix has been merged to Editor 2 that will provide helpful error messages for this situation when building the project.
