### ISSUE TITLE
Change default render script

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#678]
I know that Defold team doesn't want to modify the builtins much over fear of breaking existing projects, but if a project is well developed it should have a different render script from the builtin one anyway. A render script which can maintain the aspect ratio while scaling would be a better default one rather than the one which simply is scaled to fit.

A script like this would be much better for initial impressions as people begin to use Defold. Although maybe also including code to translate the inputs with a module would be good to have as standard built ins as well for blank projects. 

Neither of these exact ones should be used as I think they have some slight issues so should get engineer opinion first but one close to them should replace the existing render script. Optionally could continue to distribute original render script but in a sub depreciated folder so it's easy to switch back to for anyone who does want to keep using it...

https://github.com/britzl/publicexamples/tree/master/examples/fixed_aspect_ratio

```
function init(self)
	self.tile_pred = render.predicate({"tile"})
	self.gui_pred = render.predicate({"gui"})
	self.text_pred = render.predicate({"text"})
	self.particle_pred = render.predicate({"particle"})
	
	self.clear_color = vmath.vector4(0, 0, 0, 0)
	self.clear_color.x = sys.get_config("render.clear_color_red", 0)
	self.clear_color.y = sys.get_config("render.clear_color_green", 0)
	self.clear_color.z = sys.get_config("render.clear_color_blue", 0)
	self.clear_color.w = sys.get_config("render.clear_color_alpha", 0)
	
	self.view = vmath.matrix4()
end


function update(self)
	render.set_depth_mask(true)
	render.clear({[render.BUFFER_COLOR_BIT] = self.clear_color, [render.BUFFER_DEPTH_BIT] = 1, [render.BUFFER_STENCIL_BIT] = 0})

	local original_width = render.get_width()
	local original_height = render.get_height()
	local current_width = render.get_window_width()
	local current_height = render.get_window_height()
	render.set_viewport(0, 0, current_width, current_height)
	render.set_view(self.view)
	
	render.set_depth_mask(false)
	render.disable_state(render.STATE_DEPTH_TEST)
	render.disable_state(render.STATE_STENCIL_TEST)
	render.enable_state(render.STATE_BLEND)
	render.set_blend_func(render.BLEND_SRC_ALPHA, render.BLEND_ONE_MINUS_SRC_ALPHA)
	render.disable_state(render.STATE_CULL_FACE)

	-- center (and zoom out if needed)
	local zoom_factor
	if original_width > original_height then
		if original_width < current_width then
			zoom_factor = math.max(math.min(current_width / original_width, current_height / original_height), 1)
		else
			zoom_factor = math.min(math.min(current_width / original_width, current_height / original_height), 1)
		end
	else
		if original_height < current_height then
			zoom_factor = math.max(math.min(current_width / original_width, current_height / original_height), 1)
		else
			zoom_factor = math.min(math.min(current_width / original_width, current_height / original_height), 1)
		end		
	end
	local projected_width = current_width / zoom_factor
	local projected_height = current_height / zoom_factor
	local xoffset = -(projected_width - original_width) / 2
	local yoffset = -(projected_height - original_height) / 2
	render.set_projection(vmath.matrix4_orthographic(xoffset, xoffset + projected_width, yoffset, yoffset + projected_height, -1, 1))


	render.draw(self.tile_pred)
	render.draw(self.particle_pred)
	render.draw_debug3d()
	
	render.set_view(vmath.matrix4())
	render.set_projection(vmath.matrix4_orthographic(0, current_width, 0, current_height, -1, 1))
	
	render.enable_state(render.STATE_STENCIL_TEST)
	render.draw(self.gui_pred)
	render.draw(self.text_pred)
	render.disable_state(render.STATE_STENCIL_TEST)
	
	render.set_depth_mask(false)
	render.draw_debug2d()
end

function on_message(self, message_id, message)
	if message_id == hash("clear_color") then
		self.clear_color = message.color
	elseif message_id == hash("set_view_projection") then
		self.view = message.view
		pprint(message)
	end
end
```

**Comment by AGulev** [comment]
Yes, it would be great.

But it have no sense to make a lot of math operations and create a lot of new variables in update method.

Now I am using something like this:
`local helper = require "modules.render.helper"
local msgs = require "modules.msgs"

local function update_window(self)
  helper.win_width = render.get_window_width()
  helper.win_height = render.get_window_height()

  helper.zoom_factor = math.min(helper.win_width / helper.current_width, helper.win_height / helper.current_height)
  self.projected_width = helper.win_width / helper.zoom_factor
  self.projected_height = helper.win_height / helper.zoom_factor
  helper.xoffset = - (self.projected_width - helper.current_width) / 2
  helper.yoffset = - (self.projected_height - helper.current_height) / 2

  helper.adjust_stretch_x = helper.win_width / helper.current_width
  helper.adjust_stretch_y = helper.win_height / helper.current_height
  helper.adjust_zoom = math.max(helper.adjust_stretch_x, helper.adjust_stretch_y)
  helper.adjust_fit = math.min(helper.adjust_stretch_x, helper.adjust_stretch_y)

  self.full_proj = vmath.matrix4_orthographic(helper.xoffset, helper.xoffset + self.projected_width,
  helper.yoffset, helper.yoffset + self.projected_height, - 1, 1)

  self.view = vmath.matrix4()
  self.gui_projection = vmath.matrix4_orthographic(0, helper.win_width, 0, helper.win_height, - 1, 1)

  self.zoom_factor_bkg = math.min(helper.win_width / helper.settings_width, helper.win_height / helper.settings_height)
  self.projected_width_bkg = helper.win_width / self.zoom_factor_bkg
  self.projected_height_bkg = helper.win_height / self.zoom_factor_bkg
  self.xoffset_bkg = - (self.projected_width_bkg - helper.settings_width) / 2
  self.yoffset_bkg = - (self.projected_height_bkg - helper.settings_height) / 2
  self.bkg_projection = vmath.matrix4_orthographic(
    self.xoffset_bkg, self.xoffset_bkg + self.projected_width_bkg,
    self.yoffset_bkg, self.yoffset_bkg + self.projected_height_bkg,
  - 1, 1)
end

function init(self)
  self.bkg_pred = render.predicate({"bkg"})
  self.particle_pred = render.predicate({"particle"})
  self.tile_pred = render.predicate({"tile"})
  self.gui_pred = render.predicate({"gui"})
  self.text_pred = render.predicate({"text"})
  self.render_target_pred = render.predicate({"render_target"})

  helper.settings_width = render.get_width()
  helper.settings_height = render.get_height()
  helper.current_width = helper.settings_width
  helper.current_height = helper.settings_height

  self.clear_color = vmath.vector4(0, 0, 0, 0)
  self.clear_color.x = sys.get_config("render.clear_color_red", 0)
  self.clear_color.y = sys.get_config("render.clear_color_green", 0)
  self.clear_color.z = sys.get_config("render.clear_color_blue", 0)
  self.clear_color.w = sys.get_config("render.clear_color_alpha", 0)

  self.view = vmath.matrix4()
  self.clear_param =
  {
    [render.BUFFER_COLOR_BIT] = self.clear_color,
    [render.BUFFER_DEPTH_BIT] = 1,
    [render.BUFFER_STENCIL_BIT] = 0
  }
  update_window(self)
end

function update(self)
  render.set_depth_mask(true)
  render.clear(self.clear_param)

  render.set_viewport(0, 0, helper.win_width, helper.win_height)
  render.set_view(self.view)
  render.set_depth_mask(false)
  render.disable_state(render.STATE_DEPTH_TEST)
  render.disable_state(render.STATE_STENCIL_TEST)
  render.enable_state(render.STATE_BLEND)
  render.set_blend_func(render.BLEND_SRC_ALPHA, render.BLEND_ONE_MINUS_SRC_ALPHA)
  render.disable_state(render.STATE_CULL_FACE)

  render.set_projection(self.bkg_projection)
  render.draw(self.bkg_pred)

  render.set_projection(self.full_proj)

  render.draw(self.tile_pred)
  render.draw(self.particle_pred)
  render.draw_debug3d()
  render.draw_debug2d()

  render.set_view(self.view)
  render.set_projection(self.gui_projection)

  render.enable_state(render.STATE_STENCIL_TEST)
  render.draw(self.gui_pred)
  render.draw(self.text_pred)
  render.disable_state(render.STATE_STENCIL_TEST)

  render.set_depth_mask(false)
end

function on_message(self, message_id, message, sender)
  if message_id == msgs.SET_SIZE then
    helper.current_width = message.width
    helper.current_height = message.height
    update_window(self)
    msg.post(sender, msgs.SET_SIZE)
  elseif message_id == msgs.CLEAR_COLOR then
    self.clear_color = message.color
    self.self.clear_param[render.BUFFER_COLOR_BIT] = self.clear_color
  elseif message_id == msgs.WINDOW_RESIZED then
    update_window(self)
  end
end
`

**Comment by subsoap** [comment]
@AGulev For now I'll recommend all new users to just use Rendercam

**Comment by britzl** [comment]
The latest version of the render script in builtins provides multiple projections. This is a step in the right direction. RenderCam or similar extension provides so much more and should be the choice for more advanced use cases.
