### ISSUE TITLE
Windows icon currently not being used when bundling

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#680]
Icon is specified and in the right directory but not being applied to the final exe.

```
[windows]
app_icon = /icon.ico
```

**Comment by AGulev** [comment]
https://forum.defold.com/t/app-and-window-icon-on-windows-def-3126/17354/3

**Comment by subsoap** [comment]
Still an issue. App built with native extension / appmanifest is not using windows icon properly. It's really a pain to manually edit the exe to add the icon ourselves.

**Comment by britzl** [comment]
Solved in 1.2.135
