### ISSUE TITLE
Add checkbox to enable / disable go from the Outline

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#681]
In additional to the Visible checkbox an Enabled checkbox for GOs (and all of their children including children GOs) in the outline would be very useful. This way we can quickly disable some things without needing to remove them from collections during testing.

**Comment by Dragosha** [comment]
I agree. Visible checkbox would be very very useful. Without this functional some GO may looks very noisy:
![2017-06-25_20-40-06](https://user-images.githubusercontent.com/842807/27526945-90a808be-5a62-11e7-84c9-1b277fbf09a9.png)

**Comment by AGulev** [comment]
Yea, enable/disable go, components and nodes in editor would be great!
![2017-06-26_11-09-37](https://user-images.githubusercontent.com/2209596/27530132-f77ae62c-5a5f-11e7-81b9-385b44a5ef70.png)

**Comment by Dragosha** [comment]
Still waiting for this feature.
![2017-12-06_11-58-02](https://user-images.githubusercontent.com/842807/33648668-c5cd299e-da7c-11e7-878a-1c8ad69bf054.png)

**Comment by AGulev** [comment]
yea,
![2017-12-06_10-34-12](https://user-images.githubusercontent.com/2209596/33649959-0a13e2b6-da71-11e7-9dd9-8d7b373f792e.jpg)

**Comment by AGulev** [comment]
I think it can be linked with https://github.com/defold/editor2-issues/issues/899 and https://github.com/defold/editor2-issues/issues/668

**Comment by AGulev** [comment]
https://github.com/defold/editor2-issues/issues/899

**Comment by erikangelin-king** [comment]
#668

**Comment by AGulev** [comment]
This feature important for nodes too.
Looking forward for this feature. It's really hard to work in editor, make different layouts and so on without this.

**Comment by Dragosha** [comment]
> It's really hard to work in editor, make different layouts and so on without this.
yes, yes and yes

**Comment by AGulev** [comment]
Right now we are working on new project with both orientations (portrait and landscape) and many gui and popups and it's terrible (

**Comment by selimanac** [comment]
Push it :) 👍

**Comment by selimanac** [comment]
+1

**Comment by subsoap** [comment]
![2018-09-24 22_55_46-](https://user-images.githubusercontent.com/409170/45995581-7acbee00-c04d-11e8-990d-c75b5eaff073.png)
![2018-09-24 22_54_38-window](https://user-images.githubusercontent.com/409170/45995582-7acbee00-c04d-11e8-8cad-789d90b6be49.png)
![2018-09-24 22_54_04-window](https://user-images.githubusercontent.com/409170/45995583-7acbee00-c04d-11e8-8baa-6c6d2a27074e.png)
![2018-09-24 22_52_37-window](https://user-images.githubusercontent.com/409170/45995584-7acbee00-c04d-11e8-8683-3e268aeee5b3.png)

Woo! So nice!
