### ISSUE TITLE
Error connecting to engine seems to use some cached IP

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#684]
### Expected behaviour

Open project, start game and then hot reload. Should work.

### Actual behaviour

Error connecting to engine, and the IP reported is not the same as the one in the target menu:

<img width="376" alt="screen shot 2017-04-14 at 11 10 53" src="https://cloud.githubusercontent.com/assets/65613/25039741/9377ad74-2105-11e7-8c1e-af76ca8e5049.png">

<img width="514" alt="screen shot 2017-04-14 at 11 11 05" src="https://cloud.githubusercontent.com/assets/65613/25039749/9e2bd9a2-2105-11e7-9869-306a1d63b81a.png">

Note that 172.19.13.79 is not on any current interface. I don't know where this IP comes from.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>eb6c764ede93df308853ccbf12496487e3683f0e</td></tr>
<tr><td>Build time</td><td>2017-04-13T16:23:46.350160</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.3</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by sicher** [comment]
Trying this on a different machine:

![screen shot 2017-04-18 at 08 50 05](https://cloud.githubusercontent.com/assets/65613/25117892/34a49944-2414-11e7-8a57-f54236d45ea6.png)

and:

![screen shot 2017-04-18 at 08 51 38](https://cloud.githubusercontent.com/assets/65613/25117907/44231dd2-2414-11e7-8932-84a811faab01.png)

But it fails with the following IP that is bound nowhere on the machine:

![screen shot 2017-04-18 at 08 50 38](https://cloud.githubusercontent.com/assets/65613/25117923/5212381a-2414-11e7-83ec-843aa58f2ceb.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed!
