### ISSUE TITLE
Editor 2.0 Does Nothing Upon Clicking "Update"

### ISSUE THREAD

**Issue by GamingBud** [defold/editor2-issues#686]
### Expected behaviour
1. Receive the automated "Restart and Update or Skip Update" message
2. Upon clicking update, I expect it to save my project, restart, and reopen on the updated version.

### Actual behaviour
1. Receive the automated "Restart and Update or Skip Update" message
2. Upon clicking update, it does nothing. It does not flicker, minimize--nothing. The message disappears as if it were April Fools day ;).

### Steps to reproduce
1. Wait for update message
2. Click update
3. If you have the bug, it will do nothing except close the message.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>e41546be9f07d669d1675d079e786788cd9b8f85</td></tr>
<tr><td>Build time</td><td>2017-04-07T15:07:15.541900</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Forum thread: http://forum.defold.com/t/bugged-auto-update-editor2/7366

**Comment by erikangelin-king** [comment]
Hi! Could you please send me your editor 2log file, it should be located in C:\Users\<you>\AppData\Local\Defold.
erik.angelin@king.com

**Comment by GamingBud** [comment]
Done

**Comment by GamingBud** [comment]
Any progress? Any other information needed?

**Comment by GamingBud** [comment]
Tinkered and noticed everything to do with the servers seems to have malfunctioned as well. Logout does nothing. Hot reload replies: (Error connecting to engine on http://127.0.0.1:8001) after a few moments. I need to reinstall. Before I do, is there anything else I could give you that would help you diagnose the issue if another like this becomes evident?

**Comment by GamingBud** [comment]
For some random reason, it actually worked for the first time yesterday. The editor closed, reopened, and had saved my work. Now when I just posted, it showed my build date was yesterday, so I assume it worked.

**Comment by erikangelin-king** [comment]
Hi! Sorry, we really botched following up this issue :( Can't repro this issue, and we've recently changed how the updating works. Has update failed since June or can we close this for now?

**Comment by GamingBud** [comment]
Yes, as of the end of June it's been updating. By the way,I've always been a bit unsure about the update process. A simple dialog after restart of the engine saying what version it had been updated to would be sufficient for me ;).
