### ISSUE TITLE
Getting started project error

### ISSUE THREAD

**Issue by Kumlin** [defold/editor2-issues#692]
### Expected behaviour
Open up the curve editor within the getting started project
### Actual behaviour
Error message pops up  saying "com.jogamp.opengl.GLException: Method "glGenBuffers" not available"
### Steps to reproduce
Open up the getting started project and click on curve editor
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>eb6c764ede93df308853ccbf12496487e3683f0e</td></tr>
<tr><td>Build time</td><td>2017-04-13T16:23:46.350160</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6a5ee1a105744d21a19b895b131d5d4f'>6a5ee1a105744d21a19b895b131d5d4f</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
We see this issue from time to time and the usual cause is old/missing opengl drivers. We will eventually detect this case early on and give a proper warning, but for now please try and update the drivers.
Thanks!
