### ISSUE TITLE
renaming script file from "track_B" to "track_b" results in an error and is unsuccessful [DEFEDIT-908]

### ISSUE THREAD

**Issue by EgillAntonssonKing** [defold/editor2-issues#693]
### Expected behaviour
renaming "track_B" to "track_b" results should be successful

### Actual behaviour
renaming "track_B" to "track_b" results in an error and is unsuccessful

### Steps to reproduce
Create a script file and name it track_B.
Rename it to track_b and observe that error occurs and renaming is unsuccessful.
Error:
"clojure.lang.ExceptionInfo: handler ':rename' in context ':asset-browser' failed at ':run' with message 'Destination '/Users/egillantonsson/code/defold2_workspace/defold_challenge_2017/main/track_b.script' already exists'
org.apache.commons.io.FileExistsException: Destination '/Users/egillantonsson/code/defold2_workspace/defold_challenge_2017/main/track_b.script' already exists
"

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>eb6c764ede93df308853ccbf12496487e3683f0e</td></tr>
<tr><td>Build time</td><td>2017-04-13T16:23:46.350160</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2465bd29249c49489bb1ff06e73abeff'>2465bd29249c49489bb1ff06e73abeff</a></td></tr>
<table>

**Comment by AGulev** [comment]
Same thing with folder and other renaming in Assets window. For example I try to rename folder "Gift" to "gift"

**Comment by erikangelin-king** [comment]
Fix merged!
