### ISSUE TITLE
Add way to dynamically update tilemap based collision information (DEF-3449)

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#694]
Currently if you have a tilemap used as a collision object there is no way to update it. For example, using it for destructible terrain or dynamic level generation. #wishlist

**Comment by mathiaswking** [comment]
Hi @subsoap!
Afaik, the engine should update the physics when you change a tile (http://www.defold.com/ref/tilemap/#tilemap.set_tile:url-layer-x-y-tile--h-flipped---v-flipped-)
Are you experiencing a different behavior?

**Comment by subsoap** [comment]
Just tested again and it does appear to update! Not sure why it didn't work last time. There still is a problem because for example these boxes stay dead even though geometry under them changes. Maybe best user solution would be to add a tiny bit of downward force to wake things up near changed tiles?

![2017-04-19 17_06_06-blank](https://cloud.githubusercontent.com/assets/409170/25207317/86a6d2ac-2522-11e7-9d0c-38a4dbad4e09.png)

**Comment by britzl** [comment]
DEF-3449

**Comment by AGulev** [comment]
@subsoap is this still an issue? I'm not sure, but it sounds like something we already fixed in 1.2.149

**Comment by subsoap** [comment]
I have not tested since so I cannot say for sure. You can test by making a similar scene and randomly setting the blocks on / off with blocks above that have physics enabled. It probably is fixed by now though.

**Comment by AGulev** [comment]
Solved in 1.2.149
