### ISSUE TITLE
Double clicking on an .ogg file in the editor's file browser causes the editor to hang and crash

### ISSUE THREAD

**Issue by EgillAntonsson** [defold/editor2-issues#696]

**Comment by erikangelin-king** [comment]
Are you on Linux? I'm guessing this is another variety of this issue: https://github.com/defold/editor2-issues/issues/587

**Comment by EgillAntonsson** [comment]
Hi @erikangelin-king, this occurs on:
MacBook Pro (Retina, 15-inch, Mid 2015)
macOS Sierra Version 10.12.4

**Comment by EgillAntonsson** [comment]
The Defold Editor 2 is
Version: 1.2.102
eb6c764ede93df308853ccbf12496487e3683f0e

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.

The issue was that we tried to open sound files (ogg, mp3) in the internal text view instead of external editor.
