### ISSUE TITLE
Changing caps on a filename causes an error

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#699]
### Expected behaviour
I should be able to change from Foobar.atlas to foobar.atlas

### Actual behaviour
I get an error when renaming

### Steps to reproduce
Create an atlas (or probably any other file) named Foobar.atlas
Rename it to foobar.atlas
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>72fe1976c208afae6f741f7d35420b525c38bfc7</td></tr>
<tr><td>Build time</td><td>2017-04-18T12:09:42.218860</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=09f546c3ddca4a72a1e761f2c02f7930'>09f546c3ddca4a72a1e761f2c02f7930</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
#693
