### ISSUE TITLE
Saving doesn't work after file(s) have been deleted

### ISSUE THREAD

**Issue by jakob-pogulis-king** [defold/editor2-issues#70]
Saving the project causes an exception when a resource has been deleted. This has been verified on both Windows and OSX.

Steps to reproduce
1. Create an empty project (the standard with a defold logo).
2. From the editor, remove the directory `images` and the file `logo.atlas`.
3. Open `main.collection` and delete the gameobject `go`.
~~4. Create a new directory `images` under the `main` directory.~~
~~5. Add the images  `ground01.png` and `ground02.png` from the asset pack for the getting started tutorial to the `images` directory.~~
6. Save using `CTRL`+`S`

Result
An exception occurs because the file "`/main/logo.atlas`" could not be found. The changes to `main.collection` are not saved, so there are no changes visible even though the gameobject was deleted.

```
{:cause
 "The file '/main/logo.atlas' could not be found.\nThe file '/main/level.atlas.atlas' could not be found.",
 :via
 [{:type java.security.PrivilegedActionException,
   :message nil,
   :at
   [java.security.AccessController doPrivileged "AccessController.java" -2]}
  {:type java.lang.Exception,
   :message
   "The file '/main/logo.atlas' could not be found.\nThe file '/main/level.atlas.atlas' could not be found.",
   :at
   [editor.defold_project$save_all$fn__16684 invoke "defold_project.clj" 175]}],
 :trace
 [[editor.defold_project$save_all$fn__16684 invoke "defold_project.clj" 175]
  [clojure.lang.AFn run "AFn.java" 22]
  [com.sun.javafx.application.PlatformImpl lambda$null$173 "PlatformImpl.java" 295]
  [java.security.AccessController doPrivileged "AccessController.java" -2]
  [com.sun.javafx.application.PlatformImpl lambda$runLater$174 "PlatformImpl.java" 294]
  [com.sun.glass.ui.InvokeLaterDispatcher$Future run "InvokeLaterDispatcher.java" 95]
  [com.sun.glass.ui.win.WinApplication _runLoop "WinApplication.java" -2]
  [com.sun.glass.ui.win.WinApplication lambda$null$148 "WinApplication.java" 191]
  [java.lang.Thread run "Thread.java" 745]]}
```

![saving-after-a-file-has-been-deleted](https://cloud.githubusercontent.com/assets/17006862/18580757/b09ca66e-7bfd-11e6-8bd4-d8861cd2b353.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed
