### ISSUE TITLE
Shouldn't label components scale and translate with GOs?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#702]
Label components should probably default to the tile render predicate? Maybe make duplicate font materials meant for labels that label components default to, or add a text box to their properties to by default force them to the tile predicate?

**Comment by subsoap** [comment]
![2017-05-09 11_13_21-defold editor 2 0 - deffx](https://cloud.githubusercontent.com/assets/409170/25865686/87e3c5f4-34a8-11e7-9ff1-d15329d7e193.png)

Were the label materials changed to tile or did I just originally for some reason get confused and think they were not?

**Comment by britzl** [comment]
Labels are scaled with the rest of the go.
