### ISSUE TITLE
Build Errors should mention the filename

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#704]
Picture related there is an atlas with images missing but no mention of which one. In a large project, this could be annoying to hunt through atlases. Maybe make it also so you can double click the "line 0 ..." text to open the related file on errors like this.

![2017-04-18 18_53_15-defold editor 2 0 - titan dig](https://cloud.githubusercontent.com/assets/409170/25160020/600f10b0-2468-11e7-8900-71c0c2fb084b.png)

**Comment by AGulev** [comment]
@subsoap 
I am not sure that this issue is still actual
Now it looks like:
![2018-01-08_19-34-59](https://user-images.githubusercontent.com/2209596/34680807-1538a506-f4ab-11e7-95ce-21ef8b8fed1d.jpg)

**Comment by erikangelin-king** [comment]
I think this was when bundling, which uses a different build pipe and hence other error messages.

**Comment by britzl** [comment]
Unable to reproduce.
