### ISSUE TITLE
Android bundling results in an invalid apk

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#708]
### Expected behaviour
The Android bundling should result in a working APK

### Actual behaviour
The APK doesn't work
If the APK is unzipped classes.dex is missing and instead there's a var folder tree containing classes.dex

### Steps to reproduce
Bundle Android application
Try to install it. Notice the INSTALL_FAILED_INVALID_APK error
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.102</td></tr>
<tr><td>Defold sha</td><td>c6122682788261b10e589836621815affbdeb40b</td></tr>
<tr><td>Build time</td><td>2017-04-18T17:45:01.066556</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by matgis-king** [comment]
Curiously, this was fixed in the Editor 1 beta, but hadn't yet made it into the dev branch used by Editor 2. It should hopefully be fixed in the next Editor 2 update.

**Comment by matgis-king** [comment]
The commit containing the fix: https://github.com/defold/defold/commit/c895edc360bd7d33dfcf44f385367ec50df7630e
