### ISSUE TITLE
[UX] Outline do not change scroll position when choose image in atlas

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#710]
![apr-19-2017 18-13-15](https://cloud.githubusercontent.com/assets/2209596/25187520/e8f99d28-252b-11e7-8ee5-fab9202b0387.gif)

**Comment by AGulev** [comment]
tha same situation with other editor scenes too. Outline do not change scroll position when user tap to the item (node, sprite etc...)

**Comment by ragnard-king** [comment]
Fix has been merged, coming in update shortly.
