### ISSUE TITLE
Some components incorrectly have transform properties [DEFEDIT-904]

### ISSUE THREAD

**Issue by RagnarSvenssonKing** [defold/editor2-issues#713]
An example of this is collision objects and scripts. Like in Editor1, they should not be there.

Side note: a collision object should in fact have transform properties but that would be a feature and a larger thing to fix. For the time being a collision object can be offseted by adding an extra intermediate game object which carries the offset.

**Comment by rgrams** [comment]
Was also reported for script components as #576 .
