### ISSUE TITLE
When building or hot reloading DEBUG:SCRIPT: Could not connect to localhost:8172: connection refused

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#716]
Scripts hot reload but I'm still getting this error in console for some reason. My hosts file looks fine.

![defold](https://cloud.githubusercontent.com/assets/409170/25295696/7926554e-2699-11e7-99f5-7b657c1aa14a.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>981ca2c7dfed4caebb13bf2c31d07c297bd63ace</td></tr>
<tr><td>Build time</td><td>2017-04-20T12:20:01.004580</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
I have never seen this before. Does it remain after restarting the editor + engine? Is it specific to that game project?

**Comment by erikangelin-king** [comment]
@subsoap I'm going through old issues, is this still happening or can I close?

**Comment by subsoap** [comment]
@erikangelin-king I've not seen this in a long time so closing.
