### ISSUE TITLE
[UX] Texture picker [DEFEDIT-923]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#717]
I can't understand the logic of sprite a name ordering of texture picker. 

In editor1 it was like a queue: if I adding some new sprite it was in the end of the list.
But now it's fully random list. 
![2017-04-22_12-45-38](https://cloud.githubusercontent.com/assets/2209596/25303353/a026f12e-2759-11e7-9423-8804c8f03488.png)

it is inconvenient when you work with big texture with many small sprites.
Would be great to have the same logic as in editor1 or,  at least ordered alphabeticaly the list.

One more option can be auto serch if I start to enter the sprite name.

**Comment by matgis-king** [comment]
With defold/defold#1641, the list will be sorted alphabetically. I agree type-to-filter inside dropdowns would be really nice as well, but I think sorting the list addresses the urgent problem.
