### ISSUE TITLE
Having text selected in the editor, holding shift and then typing { or ( does not delete/replace selected text

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#722]
### Expected behaviour
When having some text selected have typed text replace it. Some characters require holding down shift to type in order to replace such as { or (.

### Actual behaviour
If { or ( are typed with text selected then {} or () is added to the end of line.

### Steps to reproduce
Select some text (but not the entire line's worth of text starting at the beginning of the line) and type { or (

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>24e0f53794f5efbae846052b78250ac160f9f8d1</td></tr>
<tr><td>Build time</td><td>2017-04-21T14:08:33.218528</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by adamwestman** [comment]
In Sublime when you do this the {} [] (), wrapps the word selected.

**Comment by erikangelin-king** [comment]
It now replaces the selected text.
