### ISSUE TITLE
Selecting multiple lines and pressing tab untabs them as a block instead of adding a tab to each sometimes

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#725]
I've had this happen once and can't yet figure out what causes it

Selected some text, pressed tab on instinct, block of text was untabbed to the start of the line based on the line closest to the start of the line, so lines with extra tabs still had some tabbing relative to the least tabbed line.

Will post steps and more info if I can get it to reproduce...

**Comment by subsoap** [comment]
@erikangelin-king 

Before pressing tab with a block selected

```
test
	test
		test
	test
test	
```

![2017-05-02 12_42_54-defold editor 2 0 - pixcade cosmos](https://cloud.githubusercontent.com/assets/409170/25636010/e6554762-2f34-11e7-8741-6f80053ffb6f.png)

After pressing tab with a block selected

```
	test
	test
	test
	test
	test	
```
![2017-05-02 12_44_08-defold editor 2 0 - pixcade cosmos](https://cloud.githubusercontent.com/assets/409170/25636053/0e406586-2f35-11e7-8147-776a30ee8baa.png)

Another example before pressing tab
![2017-05-02 12_44_28-defold editor 2 0 - pixcade cosmos](https://cloud.githubusercontent.com/assets/409170/25636079/1e0ab14c-2f35-11e7-936e-6db0c575f8ad.png)

And after
![2017-05-02 12_44_50-defold editor 2 0 - pixcade cosmos](https://cloud.githubusercontent.com/assets/409170/25636088/2a459814-2f35-11e7-80ac-ff058ae884de.png)

**Comment by erikangelin-king** [comment]
Thanks for the repro, IIRC the auto indentation is pretty naive :)

As an aside, I think you might need a SetWindowPos SWP_FRAMECHANGED after your SetWindowLongPtr.

**Comment by subsoap** [comment]
I posted the code for that here https://forum.defold.com/t/is-there-a-way-to-disable-grey-out-the-maximize-minimize-button-on-a-window-for-windows-os/6906/4?u=pkeod

When was JIT disabled for Mac engine runtime?

**Comment by erikangelin-king** [comment]
The new code editor adds/removes one level of tabs. Reindenting is a separate command.
