### ISSUE TITLE
Bundling on iOS doesn't work.

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#726]
### Expected behaviour
I press Bundle -> iOS Application
### Actual behaviour
This Crash.

### Steps to reproduce
Press the button.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>24e0f53794f5efbae846052b78250ac160f9f8d1</td></tr>
<tr><td>Build time</td><td>2017-04-21T14:08:33.218528</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c02f9fafd9554153900bd73eb7f4f016'>c02f9fafd9554153900bd73eb7f4f016</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Your jvm version looks old, can you try downloading a fresh editor2 from the dashboard? (The jvm is not included in auto updates...)

**Comment by adamwestman** [comment]
It works for my colleague who downloaded Editor2 within the latests months, so at least that timeframe should be fine. I will download a new version and try again!

**Comment by adamwestman** [comment]
A new install fixed the issue
