### ISSUE TITLE
Editor2 has no possibility to create text node with new line symbol \n

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#731]
In editor1 I can paste multiline text from notepad and to paste into the text node.
But it doesn't work in editor2.

Would be great to have make multiline text nodes using alt+enter.

_For now I found only one way: open *.gui file into notepad and replace text 
text:"mutli line" 
with
text:"multi \n"
"line"_

**Comment by Malmer** [comment]
BLOCKER

**Comment by ragnard-king** [comment]
Fix has been merge, support for multi-line text input for GUI text nodes and labels. Coming in update within 1h.
