### ISSUE TITLE
Cannot draw sprites on TileMap

### ISSUE THREAD

**Issue by pakchano** [defold/editor2-issues#735]
### Expected behaviour
Draw a sprite on the desired location with a single click from the mouse button.

### Actual behaviour
The tile map does not allow drawing the tile on the location desired.
I've tried multiple buttons like, shift, control, (command), alt, hold caps, tab, space, etc...

![](https://media.giphy.com/media/l4FGHNuWPFCZHzmb6/giphy.gif)

### Steps to reproduce
1. Add a tile sheet image.
2. Create a tile source and set image source to the new image.
3. Create a tile map and set tile source to the new tile source.
4. Add a new layer to the tile map.
5. Select the new layer and do **Shift + Command + T** on _mac_ or **Shift + Control + T** on _windows_ to open the Tile source palette.
6. Select a sprite from the **Tile Map > Pallet**.
7. Try to draw the sprite on the desired tile location.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>419431e534c1b5b9c5ae1130cd539ed6d83d0510</td></tr>
<tr><td>Build time</td><td>2017-04-26T15:10:11.103189</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment]
Do you have the layer selected?

**Comment by pakchano** [comment]
I certainly did, on the 5th step of the steps to reproduce I mention the selection of a layer.

**Comment by RagnarSvenssonKing** [comment]
I've never seen this issue before and I wasn't able to reproduce it either. What I did:

1. Create a tile source from 'builtins/graphics/particle_blob.png' (the default settings will produce four "corner" tiles of the particle blob).
2. Create a tile map and set tile source to the new tile source.
3. Add a new layer to the tile map.
4. Select the new layer and do Shift + Command + T on mac or Shift + Control + T on windows to open the Tile source palette.
5. Select a sprite from the Tile Map > Pallet.
6. Try to draw the sprite on the desired tile location.

Could you try with the same image just to make sure it still doesn't work for you?
![screen shot 2017-04-27 at 17 07 23](https://cloud.githubusercontent.com/assets/18021074/25490242/83c2b772-2b6c-11e7-8ff4-2557837d7c92.png)

**Comment by subsoap** [comment]
I can confirm it is working on Windows 10.
![2017-04-27 08_45_25-defold editor 2 0 - pixcade cosmos](https://cloud.githubusercontent.com/assets/409170/25491811/e3a32fc4-2b25-11e7-97b0-b5f456b64ccf.png)

![2017-04-27 08_46_35-defold editor 2 0 - pixcade cosmos](https://cloud.githubusercontent.com/assets/409170/25491854/0cb42e22-2b26-11e7-845e-7d42b8aed2ee.png)


I wonder if it has anything to do with the specific tilesource being used?

@pakchano if you switch tilesource to the built in tilesource does it still not work?

**Comment by pakchano** [comment]
Thank you @ragnard-king, @subsoap for your responses.

Today after creating a new tile map the issue disappeared on every new tile map.
![defold-tilemap-issue1](https://cloud.githubusercontent.com/assets/9617583/25493574/af753ad4-2b44-11e7-9876-05e35a42eb35.png)
![defold-tilemap-issue2](https://cloud.githubusercontent.com/assets/9617583/25493573/af718f60-2b44-11e7-9be0-1fa0a13436f2.png)

However, the **issue** is still present in the original tile map I've created called _level1.tilemap_, instead of deleting this file my decision was to keep it.

That means, in case you would like to test or review this issue here is my project _repository_ at your disposal: [https://github.com/pakchano/defold-tilemap-blockingIssue](https://github.com/pakchano/defold-tilemap-blockingIssue).

Thanks again.

**Comment by RagnarSvenssonKing** [comment]
Thanks a lot, we will investigate the problematic file!
