### ISSUE TITLE
Exception in template. Can't restore default for node's texture name.

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#737]
### Expected behaviour
Restore default texture name by click to restore button

### Actual behaviour
exception when try to restore default for template texture

### Steps to reproduce
1. Create a gui file
2. Add other gui file like a template
3. Change texture name to other
4. Try to restore texture field to default
-> Exception

![2017-04-27_16-57-16](https://cloud.githubusercontent.com/assets/2209596/25487266/5f61b7e8-2b6c-11e7-8bea-f841ccaae8dd.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>d65d275ecc5aa865ea6eb440d0649e9a43558d9d</td></tr>
<tr><td>Build time</td><td>2017-04-27T12:35:35.695876</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=3e7c56db88db4dd08f8ad02e59c5d5cb'>3e7c56db88db4dd08f8ad02e59c5d5cb</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update within ~1h.
