### ISSUE TITLE
Resetting overridden text fields often require double reset to remove the override

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#739]
### Expected behaviour
Override should disappear on the first click on the reset button.

### Actual behaviour
The value is reset, but the override remains until you click the reset button again.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>d65d275ecc5aa865ea6eb440d0649e9a43558d9d</td></tr>
<tr><td>Build time</td><td>2017-04-27T12:16:44.918026</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
The reason seems to be that the text field has focus the first time you click. When the text field loses focus, it commits its value, which results in the override reappearing. Obviously a bug!

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
