### ISSUE TITLE
Blinking/freezing and stange behavior of spine animations in build with editor2 (1.2.103) [DEFEDIT-915]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#741]
### Expected behaviour
Working spine animations without blinks

### Actual behaviour
Sometimes animation blink/freeze if build (dmengine on mac) made on editor 2 (1.2.103)

The same code, same project, same animations (attend to wolf eyes)
Editor2 (1.2.103)
![bug](https://cloud.githubusercontent.com/assets/2209596/25527459/847fe116-2c21-11e7-8642-eb3dcc76c76d.gif)

Editor1(1.2.102)
![no_bug](https://cloud.githubusercontent.com/assets/2209596/25527466/883af2dc-2c21-11e7-9508-3840aadbb188.gif)

Sometimes we have other similar bugs with spine animation in editor2 builds (I try to show you later)

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>3b9f5cf63258383be0594b7d6dbdc4ba2e0eebf6</td></tr>
<tr><td>Build time</td><td>2017-04-28T13:23:37.850072</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Thanks for the report!

We suspect this is an engine issue that has since been fixed (you're only seeing it in editor2 because you're getting a newer version of the engine). Would it be possible to re-test this with the very latest update which was published ~1h ago? It should have sha1 312250f7985e9e1a0656b5a2d11340e7269ee312?

**Comment by AGulev** [comment]
@ragnard-king 
unfortunately it still reproduced 
![bug_still](https://cloud.githubusercontent.com/assets/2209596/25529301/271fb07e-2c2a-11e7-9175-56d905b6ef01.gif)

**Comment by ragnard-king** [comment]
@AGulev Sorry to hear that, thanks for testing, we'll investigate.

**Comment by andsveking** [comment]
@AGulev I'll check if there is something strange happening in the engine, I'm going to ping you on Slack.

**Comment by AGulev** [comment]
Looks like some part of this bug was fixed with 7cabaa5643099381ba6c94d8e712a70665a238b1
because we cant reproduce similar bug with other our character  (but it has a mistake in 3b9f5cf63258383be0594b7d6dbdc4ba2e0eebf6 )

With wolf - looks like we have extra elements in project. This elements are not used in animations, but affect it.
And the affect is just in version 103, in version 102 all fine.
I sent to @sven spine projects  with those elements and updated project without those elements.

**Comment by AGulev** [comment]
@andsvekingI'm not sure that it the same issue, but sometimes I see next bug with lakes glitch
![lakes](https://cloud.githubusercontent.com/assets/2209596/25609866/ad80ce30-2f29-11e7-9df5-ca3140064686.gif)

**Comment by andsveking** [comment]
It might be, @matgis-king is finishing up some fixes in Editor 2 to match changes we did in Editor 1 related to draw order. I'll make sure he notifies you when these have been pushed and available as a Editor 2 update.

**Comment by matgis-king** [comment]
The changes to Editor 2 have been merged and should reach you shortly. Please let us know if you have any more issues!
