### ISSUE TITLE
Git synchronize (pull then push) removed renamed files with changes [DEFEDIT-1071]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#742]
### Steps to reproduce
1. Create file "Tutorial.json"
2. Push to git using "synchronize"
3. Open directory with file "Tutorial.json"
4. Rename file to "tutorial.json" and make some changes in notepad (not in editor). _In my case I replace animation file Wolf.json with updated wolf.json_ 
5. Open editor and will see this 
![2017-04-28_18-32-48](https://cloud.githubusercontent.com/assets/2209596/25536145/52f96de4-2c42-11e7-8e72-e8d83d09dc34.png)
6. cmd+U 
7. Pull then Push
8. you will see this
![2017-04-28_18-33-32](https://cloud.githubusercontent.com/assets/2209596/25536195/931e632a-2c42-11e7-8a92-17775f5429df.png)
9. close window and
![2017-04-28_18-34-09](https://cloud.githubusercontent.com/assets/2209596/25536218/aa2d602a-2c42-11e7-8b60-4898be4a921e.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>7cabaa5643099381ba6c94d8e712a70665a238b1</td></tr>
<tr><td>Build time</td><td>2017-04-28T13:59:58.269702</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Trying to repro this gives an error message at step 5 (MissingObjectException, Missing Blob) from jgit's RenameDetector.

**Comment by AGulev** [comment]
@matgis-king I am not sure, but looks like this is very similar issue https://github.com/defold/editor2-issues/issues/2308

**Comment by AGulev** [comment]
Can't reproduce anymore
