### ISSUE TITLE
Should remember more recent projects

### ISSUE THREAD

**Issue by rgrams** [defold/editor2-issues#743]
### Expected behaviour
More "Recent Projects" should be listed in the initial "open project" screen. It only lists the latest three, though there is space for six with the current window size. Most programs I use with an "open recent" menu store the latest 10 items. 

It's especially a pain if you're using Editor 1 projects which are in folders like "branches/48185/29835/" so it's almost impossible to remember which is which. 

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>7cabaa5643099381ba6c94d8e712a70665a238b1</td></tr>
<tr><td>Build time</td><td>2017-04-28T13:59:58.269702</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment]
Maybe ability to favorite a project too to keep it on the list?
