### ISSUE TITLE
Multiline block comments do not color text properly

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#744]
![2017-04-29 22_11_29-defold editor 2 0 - pixcade cosmos](https://cloud.githubusercontent.com/assets/409170/25561845/d0bd8eea-2d28-11e7-98b1-143dbb4d8b4d.png)

**Comment by RagnarSvenssonKing** [comment]
Block comments use double square-brackets:
--[[
Could you test with that?

**Comment by subsoap** [comment]
That looks right. I just forgot how to do multiline block comments!

```
--[[
for if else end
--]]
```
