### ISSUE TITLE
Can't simulate particles in editor v2.0

### ISSUE THREAD

**Issue by alednik** [defold/editor2-issues#748]
### Expected behaviour
Possible to simulate particlefx by pressing space key

### Actual behaviour
Can't simulate particlefx by pressing space key

### Steps to reproduce

1. create particlefx
2. try to simulate by pressing space key

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.103</td></tr>
<tr><td>Defold sha</td><td>7030c79c1511d28a0c80b60d70a479dd1660350c</td></tr>
<tr><td>Build time</td><td>2017-05-02T10:51:56.886521</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by AGulev** [comment]
in editor2 it makes by cmd+P (ctrl+P)
![2017-05-02_14-58-40](https://cloud.githubusercontent.com/assets/2209596/25616881/f015d66e-2f47-11e7-9402-18c8dd713e14.png)

**Comment by alednik** [comment]
Cool! Thanks a lot!
