### ISSUE TITLE
Filter "builtins" out of the "Open Resource" browser

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#75]
The "Open Resource" browser lists all builtin resources by default. It should only list project files, but include builtins when filtering.

![screen shot 2016-09-16 at 11 34 38](https://cloud.githubusercontent.com/assets/65613/18581581/952cbdde-7c01-11e6-803a-dff42cd82191.png)

**Comment by RagnarSvenssonKing** [comment]
Motivate it :)

**Comment by britzl** [comment]
I really don't see how this would be considered serious? I've never even thought of this being a problem. Closing.
