### ISSUE TITLE
Labels in particle fx properties not showing.

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#752]
Some min width or similar needed. Also, suggests that the "Spread" value is labelled "+/-".

![screen shot 2017-05-03 at 09 10 23](https://cloud.githubusercontent.com/assets/65613/25651007/efe779d8-2fe0-11e7-93fd-12da578a881b.png)

**Comment by AGulev** [comment]
yeah, it would be great. Much more clear.

**Comment by ragnard-king** [comment]
Fixed previously, now looks like this:

![image](https://user-images.githubusercontent.com/20399970/27175880-e73e9a12-51c0-11e7-9eb6-53cf1db51f96.png)
