### ISSUE TITLE
Sometimes when fetching libraries it won't update until after restart

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#753]
This error is a bit vague, but we've found that sometimes if you update your dependency and the url remains the same it will still build with the old version. It may be that it uses a cached version of the dependency, or that it doesn't rebuild it properly.

Restarting defold works.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>e8aba6a863dc3979f6f32cd7c85e4415ad20afb3</td></tr>
<tr><td>Build time</td><td>2017-05-03T13:01:34.486174</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
In Malmers case this happened for a lua module on the internal github.

**Comment by erikangelin-king** [comment]
We recently found and fixed a pretty serious issue in Fetch Libraries that would pretty much leave the editors view of resources in a completely broken state. Please reopen if this happens again!
