### ISSUE TITLE
Pressing alt+tab on Windows when an auto-complete is in progress makes user unable to continue typing

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#755]
### Expected behaviour
To continue to be able to type when typing for example `vmath.` pressing alt+tab and then returning to editor.

### Actual behaviour
Users is not able to continue typing.

### Steps to reproduce
Type `vmath.`
Press alt+tab twice to leave and return to the editor 
Can't type at all even if you change cursor position! Have to click off the editor and then click back onto it to be able to type again

If you type `vmath.` and then click to another window, then alt+tab back into Defold it also doesn't allow typing anymore still, the autocomplete menu must still have focus

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>e8aba6a863dc3979f6f32cd7c85e4415ad20afb3</td></tr>
<tr><td>Build time</td><td>2017-05-03T13:01:34.486174</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed in new code editor. Please reopen if you disagree :)
