### ISSUE TITLE
Issue with ordering text nodes with non-UTF-8 characters

### ISSUE THREAD

**Issue by Tomires** [defold/editor2-issues#759]
When I attempt to move a GUI text node (or a parent of that node) with "日” or any other Japanese kanji character set as text, the editor throws out the following error:

![kanji_error](https://cloud.githubusercontent.com/assets/7209990/25717221/0e201ab4-3102-11e7-8c81-51f45f80371b.png)

I had to set the text parameter to a latin character, move the GUI element to its new position and then change the text parameter to its original value.

Editor version: 1.2.104 (e8aba6a863dc3979f6f32cd7c85e4415ad20afb3)
OS: elementaryOS 0.4 Loki (based on Ubuntu 16.04) x64
Kernel version: 4.4.0-72-generic

**Comment by RagnarSvenssonKing** [comment]
Fixed!
