### ISSUE TITLE
Error choosing "Close Others" from Tab context menu

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#762]
### Expected behaviour
The other tabs are closed.

### Actual behaviour
Error.

### Steps to reproduce
1. Opened a bunch of assets.
2. Right-clicked on the tab bar and selected "Close Others".
<hr/>

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>Build time</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=8a61165caeed48d086d005e695a75768'>8a61165caeed48d086d005e695a75768</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
