### ISSUE TITLE
Nodes attached to spine bones in gui don't inherit animation from parent

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#763]
### Expected behaviour
They should animate with the parent. 

### Actual behaviour
They only animate with local animation. 

Note: Properly works in editor 1 and when bundling.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>a3ca144a20afe7858328c68d70cad4bcacf3f4bb</td></tr>
<tr><td>Build time</td><td>2017-05-04T11:48:09.225999</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merge, will come in update shortly.
