### ISSUE TITLE
Error renaming imported folder on macOS [DEFEDIT-967]

### ISSUE THREAD

**Issue by matgis-king** [defold/editor2-issues#765]
### Expected behaviour
The folder is renamed.

### Actual behaviour
An error dialog appears with the following error:
```
java.lang.AssertionError: Assert failed: move of unknown resource "/myextension-broken/.DS_Store"
(some? src-resource)
```

### Steps to reproduce
1. Open a folder using Finder. This will cause a hidden `.DS_Store` file to be created in the folder.
2. Drag the folder from Finder onto a folder in the Assets Panel.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>d6158b6b201fed6a5efcc8f901fbd151f4615697</td></tr>
<tr><td>Build time</td><td>2017-05-04T19:13:48.711228</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=6ecddefa939240db8f86812d7b212a6f'>6ecddefa939240db8f86812d7b212a6f</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
... 3. Rename the folder to something else.
Renaming any folder containing a .dotfile used to fail. Fixed!
