### ISSUE TITLE
GettingStarted tutorial: Ground sprites only get the ground0 image

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#77]
The editor shows the images correctly, but the game only displays the first image (ground0.png)

<img width="1252" alt="screen shot 2016-09-16 at 11 49 24" src="https://cloud.githubusercontent.com/assets/14980582/18582152/036e533c-7c04-11e6-8131-6bca99158836.png">

<img width="1275" alt="screen shot 2016-09-16 at 11 50 00" src="https://cloud.githubusercontent.com/assets/14980582/18582160/06e19394-7c04-11e6-9ebb-84d9a3d7a06f.png">

**Comment by erikangelin-king** [comment]
@king-lothman @mathiaswking Can you please try this again?

**Comment by mathiaswking** [comment]
I tested this now, and it seems to work fine for me.

**Comment by king-lothman** [comment]
Same here. I it seems to work just fine now since I updated the editor.

**Comment by erikangelin-king** [comment]
@king-lothman @mathiaswking Thanks!
