### ISSUE TITLE
Can't paste onto Collection in Outline

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#775]
If I want to copy and paste top level game objects between open collections I must copy and then paste onto other Game Objects and then drag out to make them on root like I want them. I would like to be able to press Ctrl+V to paste with Collection selected.
![2017-05-08 16_49_46-defold editor 2 0 - deffx](https://cloud.githubusercontent.com/assets/409170/25829976/932cae16-340e-11e7-9914-14048bf39572.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed!
