### ISSUE TITLE
Pressing backspace and then delete produces error in some situations 

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#777]
I've not been able to reproduce yet, as soon as I tried to do same steps again it worked without error, but I was editing a fragment program when I selected a body of text and then pressed backspace followed by the delete key.

![2017-05-08 16_59_42-error](https://cloud.githubusercontent.com/assets/409170/25830193/09b6c80e-3410-11e7-95ee-a4b3363e092c.png)

**Comment by ragnard-king** [comment]
Sentry: https://sentry.io/defold/editor2/issues/269167822/

**Comment by subsoap** [comment]
Had it happen again and it was same situation. Selected block of text, delete, backspace, error, undo, delete, backspace, no error.

**Comment by RagnarSvenssonKing** [comment]
Fixed!
