### ISSUE TITLE
If a builtin file is edited and then "saved" the "saved" changes persist through the editor session - should be purely read only

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#778]
Accidentally made changes to a builtin file, saved, tried to reopen to get fresh state, had to reopen editor to get clean copy.

Actually you don't even need to save the file if you make a change and then close the file the changes will persist if you reopen.

**Comment by AGulev** [comment]
looks like the same as https://github.com/defold/editor2-issues/issues/231
