### ISSUE TITLE
Embedded GUI component does not build

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#79]
STR:

1. Create a go
2. Create an embedded GUI component
3. Build

ERROR:RESOURCE: Empty resource path
WARNING:RESOURCE: Unable to create resource: build/default/_generated_312f5bf.guic
WARNING:RESOURCE: Unable to create resource: build/default/_generated_0.goc
ERROR:GAMEOBJECT: Could not instantiate game object from prototype /_generated_0.goc.
WARNING:RESOURCE: Unable to create resource: build/default/main/main.collectionc

**Comment by RagnarSvenssonKing** [comment]
Not supported to do it that way, gui components can't be embedded anymore
