### ISSUE TITLE
Editing of cpp file and try to comment line

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#790]
### Expected behaviour
- Opens in external editor by default;
or
- comments should work by cmd+/;
or
- cmd+/ should ignored without error message.

### Actual behaviour
Defold2 opens for editing cpp file, but when I try to comment some line by cmd+/ - I recieve next error

### Steps to reproduce
Open any *.cpp file and try to comment line by cmd+/
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>a074bbf3e604877b8fb15bd3fa6917bbce0b3872</td></tr>
<tr><td>Build time</td><td>2017-05-10T09:34:16.971024</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=5aa46ee2d27a4956a91f9212586ba1e3'>5aa46ee2d27a4956a91f9212586ba1e3</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix has been merged, coming in update shortly.
