### ISSUE TITLE
Changing capitalization when renaming file 

### ISSUE THREAD

**Issue by maakep** [defold/editor2-issues#792]
Defold version: Latest as of 2017-05-13

## Steps to reproduce
1. Create component `Player.go`
2. Rename to `player.go`
3. "There's already a file with that name"
4. Overwrite

## Actual behaviour
The file is removed

## Desired behaviour
The file is renamed with desired capitalization

**Comment by maakep** [comment]
Quick gif to illustrate: 
![2017-05-13_20-04-29](https://cloud.githubusercontent.com/assets/6514161/26027953/8534dad8-3817-11e7-8def-d2de7327fe5a.gif)

**Comment by erikangelin-king** [comment]
Fix merged!
