### ISSUE TITLE
IllegalArgumentException when building model with empty-string-texture

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#793]
Edited fragment shader program, saved and pressed "Build".

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>8956298e22fc65bab1cde001cca8b6984f016aa6</td></tr>
<tr><td>Build time</td><td>2017-05-08T16:34:16.831920</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=618cf14063fe4f53afda7c97cae8ba01'>618cf14063fe4f53afda7c97cae8ba01</a></td></tr>
<table>

**Comment by sicher** [comment]
I have a model with texture slots. When model is created and no texture is set:

![screen shot 2017-05-10 at 16 51 44](https://cloud.githubusercontent.com/assets/65613/25905026/354dee88-35a1-11e7-85c6-ea234ab55658.png)

As soon as I set one of the textures the exception happens. (Removing texture does not help, probably because the file will contain empty strings set as textures):

![screen shot 2017-05-10 at 16 52 23](https://cloud.githubusercontent.com/assets/65613/25905125/6f81cc96-35a1-11e7-94db-7d5dd9c05b0d.png)

**Comment by RagnarSvenssonKing** [comment]
Fixed!
