### ISSUE TITLE
Add a star to the start of a filename tab when it has been modified and unsaved

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#797]
So "game.project" becomes "*game.project"

The color under the tab could be changed too as a warning

![2017-05-10 18_43_21-defold editor 2 0 - deffx](https://cloud.githubusercontent.com/assets/409170/25928347/a469f6b8-35b0-11e7-9a87-f7ad6deb8b89.png)

![2017-05-10 18_43_21-defold editor 2 0 - deffxw](https://cloud.githubusercontent.com/assets/409170/25928428/10f192d2-35b1-11e7-8040-275a15673a33.png)

#ff1530

**Comment by RagnarSvenssonKing** [comment]
Fixed!
