### ISSUE TITLE
If you add and then remove extra textures from a model it will produce an error when building

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#801]
![2017-05-11 02_18_18-new issue defold_editor2-issues](https://cloud.githubusercontent.com/assets/409170/25941953/23bd2a90-35f0-11e7-8af4-eaf1ad3c923a.png)

java.lang.IllegalArgumentException: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil

  "textures: \\\"/_assets/textures/scrolling/1.png\\\"\\n"
  "textures: \\\"\\\"\\n"
  "textures: \\\"\\\"\\n"

If I edit the collection with the embedded model file directly and remove the second two textures: lines then it will build again

**Comment by RagnarSvenssonKing** [comment]
It's actually the same as #793 which I fixed 30 minutes ago! Unfortunately it needs to go through review etc before its ready in an update, so around monday (the other guys are away at a conference).
