### ISSUE TITLE
Can't paste game object into root of collection

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#802]
### Expected behaviour
When "collection" is selected, paste should insert object

### Actual behaviour
Nothing happens. If I create a game object and select that I can paste as a child.

### Steps to reproduce
Copy game object with Cmd+C
Create new collection
Hit Cmd+V

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>7b2ef0aa2f657205c680ddded145b245e11a8ed7</td></tr>
<tr><td>Build time</td><td>2017-05-10T13:30:34.611101</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Same as #775?

**Comment by Malmer** [comment]
Yes
