### ISSUE TITLE
VIP dae model mesh doesn't open

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#807]
This model is a version of the Defold logo, tried changing it but can't figure out why it won't open!

java.lang.NullPointerException: Unknown

[models.zip](https://github.com/defold/editor2-issues/files/994208/models.zip)

https://skfb.ly/6qEFU

**Comment by subsoap** [comment]
[models.zip](https://github.com/defold/editor2-issues/files/994823/models.zip)

More models to test. Several of them have issues but not all. Defold should be more resilient rather than strict with models probably as it seems most editors / viewers don't have same issues?

**Comment by RagnarSvenssonKing** [comment]
It is most likely bugs in our collada importer. Collada is a very large format and hard to handle every possible combination. We don't try to be strict, actually we already account for and handle several different format errors.

**Comment by RagnarSvenssonKing** [comment]
Fixed!

**Comment by subsoap** [comment]
Fixing this also let me build HTML5 again for project which didn't use the models but had them in its project folder it seems! Thank you!
