### ISSUE TITLE
Weird offset when translating models in editor viewport graph

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#809]
Select a model
Translate its position
Does not move with translation correctly, has an offset which grows
Doesn't matter on what material is set
Happens if you translate a GO parent or the model directly

![2017-05-11 15_40_49-defold_defold-examples_ defold examples](https://cloud.githubusercontent.com/assets/409170/25974921/512b000e-3660-11e7-904c-9fd7919cfa87.png)
![2017-05-11 15_40_57-defold_defold-examples_ defold examples](https://cloud.githubusercontent.com/assets/409170/25974923/512e9fc0-3660-11e7-9ee9-0dec33d1bc41.png)
![2017-05-11 15_40_08-defold_defold-examples_ defold examples](https://cloud.githubusercontent.com/assets/409170/25974924/51312614-3660-11e7-8042-3d3e6f3e3ccb.png)
![2017-05-11 15_40_20-defold_defold-examples_ defold examples](https://cloud.githubusercontent.com/assets/409170/25974922/512bfaa4-3660-11e7-9e0a-2b6d4ceb5a52.png)

**Comment by subsoap** [comment]
Happens when scaling too.

**Comment by RagnarSvenssonKing** [comment]
Could this be a result from you having a custom material, where the world transform is applied in the vertex shader? I just tested an old model and had the same behaviour, when I changed the material back to the builtin model.material, it worked as expected. Since 1.2.100 we pre-bake the world transform into the models for improved batching.

**Comment by subsoap** [comment]
That could be the case. I didn't notice that change, I'll test soon adjusting materials to be closer to the now builtin version.

**Comment by RagnarSvenssonKing** [comment]
👍

**Comment by RagnarSvenssonKing** [comment]
I will close this issue for now, assuming it is fixed. Please let us know if you encounter the same issue again!
