### ISSUE TITLE
'Build HTML5' loads blank page

### ISSUE THREAD

**Issue by RagnarSvenssonKing** [defold/editor2-issues#811]
In Chrome, so far seems like a global issue.

**Comment by RagnarSvenssonKing** [comment]
Fixed!

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/build-html5-opens-an-empty-page-editor2-solved/8273

**Comment by RagnarSvenssonKing** [comment]
Closing since there does not seem to be an easy way to reproduce.
