### ISSUE TITLE
Pressing enter while at the end of a tabbed line can put that line at home position

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#817]
Before
![2017-05-12 22_42_36-defold editor 2 0 - deffx - deffx_cameras_look-at script](https://cloud.githubusercontent.com/assets/409170/26022856/81fe1946-3764-11e7-9d4b-e352b6a1fba1.png)
After pressing enter
![2017-05-12 22_42_42-defold editor 2 0 - deffx - deffx_cameras_look-at script](https://cloud.githubusercontent.com/assets/409170/26022857/859070ae-3764-11e7-9069-dc8a799475f5.png)

**Comment by AGulev** [comment]
@subsoap I can't reproduce it, maybe this issue already fixed?

**Comment by subsoap** [comment]
Possibly! I've not been coding in Defold in a while so can't say.

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144. Feel free to reopen if you can.
