### ISSUE TITLE
Make selecting a block of text highlight duplicates of it within the text editor

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#820]
This speeds up comprehension of code when I can highlight a block of text and see where else it is used at a glance.
![text_highlight_dupes](https://cloud.githubusercontent.com/assets/409170/26023260/032e9e52-376d-11e7-9813-6414b005a69f.gif)

![text_highlight_dupes2](https://cloud.githubusercontent.com/assets/409170/26023272/35835906-376d-11e7-9327-19c4f4a2fd1f.gif)

**Comment by rgrams** [comment]
+1 for this! So useful!

**Comment by erikangelin-king** [comment]
Fixed in new code editor
