### ISSUE TITLE
Panels need better rules for proportional / max ideal sizes when Defold window is resized [DEFEDIT-1158]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#825]
If I have the window like this

![2017-05-13 01_46_50-defold editor 2 0 - deffx](https://cloud.githubusercontent.com/assets/409170/26024039/154f7e60-377e-11e7-8d8e-a77c41facc21.png)

and then maximize it the panels become like this - usually Assets ends up largest
![2017-05-13 01_46_55-defold editor 2 0 - deffx](https://cloud.githubusercontent.com/assets/409170/26024059/3c2d8414-377e-11e7-88c7-edc7667a4205.png)

you can see if I resize the window horizontally it's the left panel which expands the most
![2017-05-13 01_48_05-defold editor 2 0 - deffx](https://cloud.githubusercontent.com/assets/409170/26024062/4bd8c554-377e-11e7-9644-09054b31a595.png)

The center panels should be greedy when resizing the window. The left and right panels should have minimum and maximum ideal values to stretch in size to as the main window resizes. So if the left panel reaches its ideal maximum size it won't keep on expanding, and instead the middle panel area can grow.

Something like this would be the ideal auto expansion

![2017-05-13 01_50_26-defold editor 2 0 - deffx](https://cloud.githubusercontent.com/assets/409170/26024068/96f3428a-377e-11e7-8883-5837a78d72d7.png)

So around 320px width for the left and right panels to organically expand to as window is resized, and then let the middle panel get the rest 100%. 99 times out of 100 we'll resize the side panels when we need to and we would rather have the middle panel take as much space as possible.

**Comment by Jerakin** [comment]
https://github.com/defold/editor2-issues/issues/321
