### ISSUE TITLE
If a material is deleted and then re-added the editor can still give build error that it's deleted until restart

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#826]
I even tried switching model which used material off and build, didn't work, had to restart editor for it to work again.

**Comment by erikangelin-king** [comment]
Can't repro after recent changes.

What I tried in the defold-examples project (https://github.com/defold/defold-examples)
- Build, Click 3D Material and watch the defold logo in all its glory, exit
- Open material-example/material.collection
- Check that logo/model refers to material-example/phong.material
- Delete phone.material
- Build, get relevant build error
- Re-add phong.material
- Build, Click 3D Material and watch the defold logo in all its glory again

Please reopen if your experience differs.
