### ISSUE TITLE
adding tags to fonts raise java.lang.ClassCastException: javafx.scene.Scene cannot be cast to javafx.scene.control.ListView

### ISSUE THREAD

**Issue by rvion** [defold/editor2-issues#829]
### Expected behaviour

adding a tag to a font add a tag to the font

### Actual behaviour

adding a tag to a font raise an error

```
java.lang.ClassCastException: javafx.scene.Scene cannot be cast to javafx.scene.control.ListView
```

### Steps to reproduce

- open a font (/builtins/fonts/font-df.vp),
- click the `+` button to add a tag
- select the tag name input field, add a letter
- ...
- see the exception

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>3f05aa34c4e1bcec7d4aae6469371014a276e9ec</td></tr>
<tr><td>Build time</td><td>2017-05-12T14:21:46.958522</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=12d567f3ff9b4d479caf040dad0a2f82'>12d567f3ff9b4d479caf040dad0a2f82</a></td></tr>
<table>

**Comment by matgis-king** [comment]
Are you able to reproduce this in a more recent build? I'm unable to do so by performing the suggested repro steps.

**Comment by erikangelin-king** [comment]
Can't repro this, please reopen if it happens again!
