### ISSUE TITLE
Error when opening font

### ISSUE THREAD

**Issue by ThaPro** [defold/editor2-issues#830]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>3f05aa34c4e1bcec7d4aae6469371014a276e9ec</td></tr>
<tr><td>Build time</td><td>2017-05-12T14:22:43.901295</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2e2230595ca94b1a81a2b76ecba82428'>2e2230595ca94b1a81a2b76ecba82428</a></td></tr>
<table>

**Comment by subsoap** [comment]
Which font?

**Comment by matgis-king** [comment]
I believe this was fixed with defold/defold#1665. Please re-open if the issue remains!
