### ISSUE TITLE
Need compensated transform for editor transform controls [DEFEDIT-887]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#833]
If I rotate a model's go and then try to re-position the model it translates relative to the new rotation and not the world. There needs to be an option in the editor to be able to compensate for this so that if a rotated model is dragged to move up it actually goes up and not a different direction.

**Comment by matgis-king** [comment]
Internal Note: A work-in-progress branch exists here in case someone wants to revive it: https://github.com/defold/defold/tree/DEFEDIT-887-local-space-manipulators

**Comment by AGulev** [comment]
it was solved in  1.2.130
https://forum.defold.com/t/defold-1-2-130-has-been-released/22487?u=agulev
