### ISSUE TITLE
Can not open Editor without restarting computer.

### ISSUE THREAD

**Issue by adamwestman** [defold/editor2-issues#835]
When I close down the editor I am unable to open it up again, unless I restart my computer. I am using Mac OSX.

**Comment by adamwestman** [comment]
It may be related to issue with Window appearing off-screen.

**Comment by RagnarSvenssonKing** [comment]
Fixed! Unfortunately this requires a clean download and re-install of the Editor, get it in the dashboard: https://dashboard.defold.com
