### ISSUE TITLE
No progress bar when importing large project

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#837]
It seems like the "git clone" part of opening project lacks progress indication:

1. Open large project "From Dashboard".
2. Notice lack of progress bar for a while.

![screen shot 2017-05-15 at 10 12 37](https://cloud.githubusercontent.com/assets/65613/26049680/176bb1d4-395c-11e7-99be-8a02024bd5ff.png)

**Comment by matgis-king** [comment]
Fixed ages ago with the new Welcome screen!
