### ISSUE TITLE
Render error in main.collection [DEFEDIT-944]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#838]
STR:

1. Open internal project "C" (ask me).
2. Open main.collection.

Result:

![screen shot 2017-05-15 at 10 53 07](https://cloud.githubusercontent.com/assets/65613/26049896/fd309964-395c-11e7-9c84-a88c995857aa.png)

This file opens fine in editor 1.

**Comment by matgis-king** [comment]
Looks like we weren't able to extract mesh data from a `.dae` file. Looking at the project content, the file `screen_triangle.dae` appears to have been modified using a text editor in an attempt to add normals. However, they forgot to add indices for the normals to the polylist, so the mesh data is in fact invalid.
