### ISSUE TITLE
Not possible to bundle project [DEFEDIT-950]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#839]
STR:

1. Open internal project "C".
2. Build and run. (Requires fixing a missing texture in a particle fx that Editor 1 ignores).
3. Try to bundle. I have tried iOS and OSX with the same result.

![screen shot 2017-05-15 at 11 08 54](https://cloud.githubusercontent.com/assets/65613/26050570/70e3382e-395f-11e7-8046-944ac824bcad.png)

**Comment by matgis-king** [comment]
This should be fixed with defold/defold#1641!
