### ISSUE TITLE
If a sprite texture is deleted and readded the editor will still think it's missing

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#840]
Similar to 

https://github.com/defold/editor2-issues/issues/826
![2017-05-15 11_34_26-dood](https://cloud.githubusercontent.com/assets/409170/26073094/9ad8f300-3962-11e7-8f7f-fd4b21c8d004.png)

but fixing it took just switching to another texture and back.

**Comment by erikangelin-king** [comment]
Closing as can't repro after recent file system fixes.
What i tried:
- Copy particle_blob.png from builtins to project root
- Create new tile source, set Image to /particle_blob.png
- Delete /particle_blob.png
- Errors in tile source
- Copy particle_blob.png from builtins to project root
- Everything looks nice again

Please reopen if things still look different on your side, and thanks for all the brilliant reports!
