### ISSUE TITLE
Rename Image in tilesource [DEFEDIT-952]

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#843]
### Expected behaviour
Nothing happened
### Actual behaviour
Receieve error
java.lang.AssertionError: Assert failed: (empty? (clojure.set/intersection (set added) (set removed)))
### Steps to reproduce
1. Add image in tilesource
2. Change 1 symbol in image name from lowcase to uppercase(change in Windows Explorer. When I try change in Editor file disappear)
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>3f05aa34c4e1bcec7d4aae6469371014a276e9ec</td></tr>
<tr><td>Build time</td><td>2017-05-12T14:22:43.901295</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=4454d9524ac64c4fa9332aa1fc800a5d'>4454d9524ac64c4fa9332aa1fc800a5d</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Thanks for the report!

**Comment by erikangelin-king** [comment]
Fix merged! Finally!
