### ISSUE TITLE
Make file search filter be able to detect based on path too

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#845]
Currently it only filters based on filename and not folders in the path. Maybe add a config to toggle between filenames only or caring about matching words in the path too. So split path into words and match against each word. And add support for writing like "/mo..." because if you type / it never matches anything and it might be a nice way to filter to certain sub folders faster.

![2017-05-15 17_48_52-select resource](https://cloud.githubusercontent.com/assets/409170/26085157/fd61e034-3996-11e7-9864-5ed4dc766c00.png)

![2017-05-15 17_48_59-select resource](https://cloud.githubusercontent.com/assets/409170/26085160/00b56b70-3997-11e7-8c0a-bb5c45950463.png)

Also maybe current filtering is kind of weird. Type a letter, and it seems like it includes files which shouldn't even begin to match the current filtering rule???

**Comment by ragnard-king** [comment]
I believe the issues raised here have been resolved by the new fuzzy text matching algorithm.
