### ISSUE TITLE
Copying and pasting GOs with children doesn't rename the children

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#856]
I can't select the second version of "go" to rename it without an "java.lang.NullPointerException: Unknown" appearing, renaming the original "go" doesn't help.

![2017-05-16 17_11_03-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26133269/be26f2aa-3a5a-11e7-8641-103eeff0ad12.png)

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>9cafbbce81afde6a5fdd630a7c31194e946ef6cc</td></tr>
<tr><td>Build time</td><td>2017-05-16T18:47:29.809396</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d13d339dddd640c5b3bec5ad9f394b4c'>d13d339dddd640c5b3bec5ad9f394b4c</a></td></tr>
<table>

**Comment by Malmer** [comment]
In my opinion it shouldn't auto-rename the subtree, but the NPE shouldn't be there, obviously.

**Comment by subsoap** [comment]
All GOs become flat in engine so they must have unique names. Their parenting is only for transformations.

Making them not be renamed would requiring making GOs be able to be containers and then be able to sub-reference sub-GOs through their container tree but that would probably be a major engine design change.

**Comment by Malmer** [comment]
Yes, maybe the common case is that you want things auto renamed. It is just that it often is a bit frustrating when editors do things you didn't really ask for.

**Comment by subsoap** [comment]
The ideal situation in this case would be the top GOs to actually be Collections. Maybe a good feature would be able to easily convert top level GOs into collections with a right click. With the previous top level GO the new top level GO in the new Collection.

**Comment by ragnard-king** [comment]
A fix for the initial issue (and various issues with copy/paste of hierarchies) has been merged, coming in update shortly.
