### ISSUE TITLE
Link color codes between Curve Editor and Particle FX Properties

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#857]
![2017-05-16 17_27_24-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26133578/06d0a6f2-3a5d-11e7-8276-ff16ed38ab21.png)

How do I know which curve belongs to which property?

Additionally I have no way to toggle visibility of property curves. If I disable their curve it clears the nodes.

**Comment by RagnarSvenssonKing** [comment]
Ragnar D: This was fixed by your curve view PR.

**Comment by ragnard-king** [comment]
Fix has been merged, coming in update shortly. There should've been a list of properties to the left of the curve view but it was accidentally removed at some point:

![image](https://cloud.githubusercontent.com/assets/20399970/26342796/ba75593c-3f99-11e7-9c6d-d27e0cd25a64.png)
