### ISSUE TITLE
Double clicking the handle of a curve produces error java.lang.IllegalArgumentException: No matching clause: :tangent

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#858]
![2017-05-16 17_46_43-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26133928/ccf5f196-3a5f-11e7-9208-2e35e81e72a0.png)

A complete restart of the editor is required to be able to use the curve editor again once this error happens.

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>9cafbbce81afde6a5fdd630a7c31194e946ef6cc</td></tr>
<tr><td>Build time</td><td>2017-05-16T18:47:29.809396</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=2ff22b80f8fa4b9da208f5076366f181'>2ff22b80f8fa4b9da208f5076366f181</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Fixed!
