### ISSUE TITLE
Sounds do not update in build without rebuild or restart [DEFEDIT-954]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#861]
When I try to change sound in Audacity, and then try to make cmb+B - in build it is the same sound.

Step to reproduce:
1. Build project with some sound
2. Change this sound, but save the same name (you can pull the project with changed sound, or replace with other sound, or just change it in sound editor)
3. Try to build project one more time:
It is still the same (before changes) sound. 

Need to do rebuild or restart of editor to update the sound.

**Comment by erikangelin-king** [comment]
Fix merged!
