### ISSUE TITLE
Particle emitters with wrong atlas gave build error. Fixed it. Still gave same build error. Restarted. No build error.

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#864]
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>ced984cf08cef40a76e4ea1215b181de36cfcfe7</td></tr>
<tr><td>Build time</td><td>2017-05-16T12:15:03.203447</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment]
Seems to be an issue with build errors not being rechecked as files are changed in several cases.

**Comment by ragnard-king** [comment]
Fix merged and available in update.
