### ISSUE TITLE
Can't open lua module file "Unable to open 'file.lua', since it appears damaged."

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#865]
![2017-05-17 03_13_32-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26149392/fd735666-3aae-11e7-822c-2b014fa2a28f.png)

I edited the .lua file so it's just comments but otherwise blank and it still says this. It said this after I tried to require a module with a typo in it.

After I closed everything, and then tried to edit again it let me edit again, run, and fix typo without any alert.

**Comment by ragnard-king** [comment]
@subsoap Thanks for the report! I've been trying to re-produce this issue but haven't been able to. Do you have any steps I could follow that reproduce it? Has it happened again since?

**Comment by subsoap** [comment]
Has not happened again since.

**Comment by ragnard-king** [comment]
Closing this as I could never reproduce. Please re-open if it happens again.
