### ISSUE TITLE
Editor 2 not currently supporting bmfonts? [DEFEDIT-1050]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#867]
Can anyone test this? I tested with 3 different version of BMFont and none of the .fnt files generated would work. I tried using different source fonts too.
![2017-05-17 21_07_08-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26186217/d28028da-3b44-11e7-8dba-e034c18e625e.png)

**Comment by matgis-king** [comment]
Fixed with defold/defold#1665!
