### ISSUE TITLE
Sometimes when clicking at the end of the line the point doesn't get set to the end of the line

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#868]
This happens sometimes

Click here
![2017-05-17 23_01_26-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26188567/d1d72964-3b54-11e7-8de1-429d7c63008a.png)

Pointer goes somewhere like here instead of at the end of the line like you want
![2017-05-17 23_01_32-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26188575/dcb55cfc-3b54-11e7-9cb8-54cb8b4cbe37.png)

Modifying the text more usually clears the problem

**Comment by erikangelin-king** [comment]
Fixed in new text editor
