### ISSUE TITLE
Highlighted text generated from autocomplete isn't removed from typing

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#869]
Type factory. and then press enter

![2017-05-18 01_37_56-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26193639/ba322e60-3b6a-11e7-90ca-f80c6701f0cc.png)

Some text is selected

![2017-05-18 01_38_04-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26193646/bea689be-3b6a-11e7-90a8-6782f817778b.png)

But when you begin to type it's not replaced.

If you select text from start to end direction it will not be replaced by typing. Selected text is only replaced with typing when the text body is selected end to start.

![selected_text](https://cloud.githubusercontent.com/assets/409170/26193811/374993de-3b6b-11e7-8dd3-7e27dedfd164.gif)

**Comment by AGulev** [comment]
@subsoap @erikangelin-king can''t reproduce.
