### ISSUE TITLE
It

### ISSUE THREAD

**Issue by oak5tream** [defold/editor2-issues#870]
### Expected behaviour
When clicking bundle for ios, I should be able to bundle.

### Actual behaviour
I get an error popup saying:

java.lang.NoSuchMethodError: javafx.scene.control.ChoiceBox.setOnAction(Ljavafx/event/EventHandler;)V

### Steps to reproduce
Clicking "Bundle" -> "iOS"

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>a6d932f830de013b8253b9099ba225886d2b9649</td></tr>
<tr><td>Build time</td><td>2017-05-17T15:03:57.538208</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_45-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=806f7f66a2504a9395d70fff893539bf'>806f7f66a2504a9395d70fff893539bf</a></td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Thanks for reporting! It appears you have an old installation before we upgraded the JRE from 1.8.0_45 to 1.8.0_102. Please download a fresh copy and the error should go away. We should fix this so the JRE is either upgraded or the app warns that you need a fresh installation.

**Comment by oak5tream** [comment]
Thanks for the quick reply! Downloading a fresh copy solved my problem!
