### ISSUE TITLE
There's a max particle count in the particle editor

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#873]
My emitters get's capped by some external limit on max particle. It does not seem to be from game.project
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>ced984cf08cef40a76e4ea1215b181de36cfcfe7</td></tr>
<tr><td>Build time</td><td>2017-05-16T12:15:03.203447</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
