### ISSUE TITLE
Animation list dropdown order issue

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#875]
I have several animations in a tilesource. When selecting one from the dropdown they are in an unexpected order. Should be

```
crosshair_1
crosshair_2
crosshair_3
...
crosshair_13
crosshair_14
crosshair_15
```

![2017-05-18 13_08_55-](https://cloud.githubusercontent.com/assets/409170/26221404/38488f5a-3bcb-11e7-9c22-957def109ad8.png)

**Comment by matgis-king** [comment]
The list can now be filtered by typing into the text field, and the entries are ordered by name.
