### ISSUE TITLE
Detect up/down key presses when a dropdown list has focus to move up/down list of options

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#876]
If this list has focus pressing up/down on keyboard should go up and down the list for me without me needing to open the list fully and click another option.

![2017-05-18 13_10_58-animation list dropdown order issue issue 875 defold_editor2-issues](https://cloud.githubusercontent.com/assets/409170/26221475/7c6310a2-3bcb-11e7-8c69-331028de9588.png)

**Comment by matgis-king** [comment]
Closing this as it is no longer applicable with the new behavior introduced by the filterable Property Editor dropdowns.
