### ISSUE TITLE
When editing script - clojure.lang.ExceptionInfo: handler ':key-typed' in context ':code-view' failed at ':run' with message 'Setter of node 72057594037928307 (editor.script/ScriptNode) :code could not be called'

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#879]
Text was like this
![2017-05-18 14_19_05-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26223906/fd801d8e-3bd4-11e7-92f2-f6af562be874.png)

```
local mouse_helper = require(examples.toys.orbit.mouse_helper)
```

Next add a single quot

```
local mouse_helper = require("examples.toys.orbit.mouse_helper)
```

Then try to add another quote at the end

This happens along with error
```
local mouse_helper = require("examples.toys.orbit.mouse_helper"")
```

![2017-05-18 14_18_35-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26223876/e9e3684e-3bd4-11e7-90ae-0ce6a8f93fb1.png)

Just having this line

```
local mouse_helper = require("examples.toys.orbit.mouse_helper)
```
And attempting to close the quotes is enough to produce error.

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>c88196e2ff312e2400bc6473a5b2a496b99d8e81</td></tr>
<tr><td>Build time</td><td>2017-05-18T17:10:38.778148</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=ddfdd3135d6d4d98889e1421c9aadd7f'>ddfdd3135d6d4d98889e1421c9aadd7f</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
