### ISSUE TITLE
java.lang.IllegalArgumentException: Value out of range for int: -Infinity

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#882]
This happened when I was resizing the editor window. I think it has something to do with the curve editor since it glitched out.
![2017-05-19 00_16_22-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26237080/749deb1e-3c28-11e7-98fb-55674d09816e.png)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>c88196e2ff312e2400bc6473a5b2a496b99d8e81</td></tr>
<tr><td>Build time</td><td>2017-05-18T17:10:38.778148</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=0fb0ad006af64509a385a18e01af0e00'>0fb0ad006af64509a385a18e01af0e00</a></td></tr>
<table>

**Comment by subsoap** [comment]
Reproduce: 

be on Windows 10

Maximize Window

Press Windows key + right

If error doesn't happen right away close editor and re-open and do not resize Window before, keep trying a few times until error happens as sometimes it doesn't seem to.

**Comment by matgis-king** [comment]
Note: It seems `rulers/num-format` throws this exception if fed a list with a single value.

**Comment by matgis-king** [comment]
Repro: Open the curve editor and drastically shrink the width of the editor window.

**Comment by RagnarSvenssonKing** [comment]
Fixed!
