### ISSUE TITLE
Game object id naming is not properly increased

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#883]
### Expected behaviour
My copy of the object "test2" should be auto named "test3"

### Actual behaviour
The copy is named "test21"

### Steps to reproduce
Make a copy of game object with number at the end of the id.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>d85dc7e615a04a574c0d772a914fe61b5c5f2dab</td></tr>
<tr><td>Build time</td><td>2017-05-18T15:29:25.374476</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment]
https://github.com/defold/editor2-issues/issues/683

**Comment by RagnarSvenssonKing** [comment]
Closing as duplicate
