### ISSUE TITLE
Trying to export bundle over an already existing exportation

### ISSUE THREAD

**Issue by Deynne** [defold/editor2-issues#885]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>e99fe6c202a25c5b9c68e54af01cf581998f1254</td></tr>
<tr><td>Build time</td><td>2017-05-19T12:00:10.869903</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.4.0-78-generic</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d7cfecc6e821499ea86ac08e04abdc08'>d7cfecc6e821499ea86ac08e04abdc08</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Sentry link broken, seems to be this: https://sentry.io/defold/editor2/issues/276488621/

**Comment by erikangelin-king** [comment]
Sentry info gone :'( not much to go on, please reopen if it happens again!
