### ISSUE TITLE
Add "hot reload" option to Asset outline

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#886]
When using external editor there is no way to hot reload scripts. Make it possible to hot reload them by right clicking the script file in the asset outline and choosing "hot reload" from the menu.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>d85dc7e615a04a574c0d772a914fe61b5c5f2dab</td></tr>
<tr><td>Build time</td><td>2017-05-18T15:29:25.374476</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment]
https://github.com/defold/editor2-issues/issues/832
