### ISSUE TITLE
Can't pick images for cubemap [DEFEDIT-985] [DEFEDIT-988]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#887]
The fields for images are just text fields and it is very unclear what should be there as values. Tried with path to the files, but that didn't work.

[May likely become a blocker for us pretty soon]

**Comment by subsoap** [comment]
1. Set path to each side like "/assets/cubemaps/world/right.png"
2. Each texture must be same size
3. Set .cubemap as texture in model

Still doesn't work?

**Comment by matgis-king** [comment]
Quick-win label was originally for fixing the property fields. Removing, since we still need to implement building of cubemap resources.

**Comment by subsoap** [comment]
+1 to getting cubemap resources building, I'd really like to use them in shaders.

**Comment by erikangelin-king** [comment]
Cubemap support just merged.
