### ISSUE TITLE
When console fills up with enough lines it stops scrolling properly

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#888]
It's a little under 3000 lines that this happens

![console_scrolling](https://cloud.githubusercontent.com/assets/409170/26269460/79d646cc-3ca9-11e7-858e-3074e53e11ea.gif)

**Comment by mosmetro** [comment]
I see this also. Console should continue shows last printed message no matter how often she is truncated.
Just like in old editor. With absence of debugger, proper console output very important. That issue prevents me using Editor 2 any more.

**Comment by erikangelin-king** [comment]
Fixed
