### ISSUE TITLE
Horizontal scroll bar in text editor will sometimes constantly show/hide when a long line is just below the view

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#890]
![h_scroll](https://cloud.githubusercontent.com/assets/409170/26279566/0b32d456-3d6c-11e7-833d-f5c594cb6d9a.gif)

This line is just below the view
![2017-05-20 14_54_10-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26279580/3a327c52-3d6c-11e7-9174-612d9ced4ebd.png)

I assume what's happening is when the scrollbar is not there the view thinks that the long line is close enough to show the scrollbar, and then when the scrollbar is there there is just enough extra distance that it thinks it shouldn't show the scrollbar.

**Comment by erikangelin-king** [comment]
Fixed in new code editor
