### ISSUE TITLE
+%*/ have right syntax highlighting but - sometimes doesn't

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#891]
![2017-05-21 00_31_06-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26282012/d5ce29d6-3dbc-11e7-829d-8c990d02d9a4.png)

![2017-05-21 00_33_24-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26282035/238adb42-3dbd-11e7-9f48-4c6f73154858.png)

**Comment by AGulev** [comment]
@subsoap can't reproduce
