### ISSUE TITLE
If a bundle error refers to a line number of a file it needs to say the filename + path

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#892]
Having this kind of error happen when bundling after many new scripts and changes can be tedious to find the problem...

![2017-05-21 01_41_49-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26282478/15dc75be-3dc7-11e7-8baa-9ced3094f273.png)

**Comment by matgis-king** [comment]
Possible workaround:
Currently building and bundling take different code paths in the editor. We will unify these in the future, but in the meantime you can often get a more helpful error message by choosing Build from the Project menu.

**Comment by subsoap** [comment]
Building gave no error in this situation. Only bundling.

**Comment by matgis-king** [comment]
I see. Obviously we need to adress this properly, but I wanted to post the possible workaround as well in case it could help. Sorry for the trouble you're having.

**Comment by subsoap** [comment]
For the most part, the editor is a joy to work with and I can't wait until it's really ready for general use.

Currently building ignores errors in lua modules which are not directly used. The bundling process goes through everything but doesn't say what errors are where only that they exist.

**Comment by matgis-king** [comment]
This should be fixed with defold/defold#1641!
