### ISSUE TITLE
If cursor is on a line with multiple tabs home key will go toward end of line instead of start of line

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#893]
1. tab multiple times
2. place cursor in the middle of them
3. press home key on keyboard
4. home key will send cursor position to end of line, and then if pressed again will go to start of line

Home key behavior should be to go toward the first tab/space with text on it following tab/spaces and then go toward start of line if pressed again.

![11](https://cloud.githubusercontent.com/assets/409170/26286507/1db9a9c8-3e1c-11e7-807b-422a7780ed3c.png)
![22](https://cloud.githubusercontent.com/assets/409170/26286508/1dbff602-3e1c-11e7-8495-8d3b3bd615e8.png)
![33](https://cloud.githubusercontent.com/assets/409170/26286506/1db90680-3e1c-11e7-90b8-8e169c34253c.png)

**Comment by AGulev** [comment]
@subsoap Can you recheck with new text editor?
If I understand right it works now
