### ISSUE TITLE
Error when building project

### ISSUE THREAD

**Issue by Eaani** [defold/editor2-issues#896]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>8ca9dddb5a241f77250d483dae977ab62567b84d</td></tr>
<tr><td>Build time</td><td>2017-05-16T17:51:11.582754</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=b17a37c4298e4940b4e3f89de2c28c1e'>b17a37c4298e4940b4e3f89de2c28c1e</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
This was with a really old version of project, so not blocker, but should still investigate.

**Comment by RagnarSvenssonKing** [comment]
Sentry.io lost the stack trace, not possible to investigate.
