### ISSUE TITLE
Lacking shortcuts

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#898]
Play/pause, framing, change manipulator are examples of some commands that lack good shortcuts.

**Comment by rgrams** [comment]
Not having F2 for rename (or some other shortcut) #197 is the worst for me, I rename things on a daily basis.

**Comment by Jerakin** [comment]
Related to https://github.com/defold/editor2-issues/issues/492

**Comment by ragnard-king** [comment]
Better shortcut support, as well as shortcuts that are more aligned with editor1, is available in the latest update.
