### ISSUE TITLE
Images added to atlas not rendered until atlas reopened

### ISSUE THREAD

**Issue by johan-becknoren-king** [defold/editor2-issues#90]
When adding images to an Atlas the added images do not show up. It remains empty until it the atlas is closed and then opened again. After that the images show up correctly.

**Comment by ragnard-king** [comment]
I can't reproduce this, images added to both new and existing atlases show up immediately. One thing I did notice though is that the default view for an empty atlas is tiny (~1x1) so when adding an image to a new atlas you often need to zoom out (quite a bit) to actually see the image.
