### ISSUE TITLE
If you copy and paste a GO from one collection to another which has a child GO with a script then rename the parent error produces

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#902]
1. make collection, add two GOs one parented to the other, add a script to the child GO
2. make another collection, copy the parent GO with its tree of children to the second collection
3. rename the parent GO, click on the child GO or attempt to make a build

java.lang.NullPointerException: Unknown

ERROR:GAMEOBJECT: Child not found: /labels

**Comment by subsoap** [comment]
It also appears to break copy and  paste until editor restarts

**Comment by ragnard-king** [comment]
Fix has been merged, coming in update shortly.
