### ISSUE TITLE
Add mersenne Twister as optional PRNG source for engine related RNG

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#907]
Add a version of mersenne Twister or similar good PRNG for whatever in the engine uses RNG but isn't something we can access or modify. Then let us enable the alternative PRNG method.

**Comment by Malmer** [comment]
You can always write your own PRNG in lua. It is usually a pretty good idea anyway, since you can then architect it to have multiple instances with different seeds and other such things.

**Comment by subsoap** [comment]
There is randomness not able to be controlled by us such as how particlefx handles randomness. Maybe that's the only in engine randomness that we have no control of the behavior though.

**Comment by mathiaswking** [comment]
I think this feature request needs some clarification:
1. What features are you lacking from [math.random() / math.randomseed()](https://www.defold.com/ref/math/#math.random:-m---n-) ?
1. Is the feature request actually about being able to control the seed value of the particle effects?

**Comment by subsoap** [comment]
This is not a script thing so nothing to do with 1. it's to allow control the randomness of the game's engine where ever it is. So closer to 2.

**Comment by britzl** [comment]
This isn't likely to be changed. There isn't enough bang for the buck really. My suggestion is that if there are issues with the places in the engine where we use random numbers then please report those instead so that we can fix them.
