### ISSUE TITLE
Play multiple particlefx/animations simultaneously

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#913]

**Comment by subsoap** [comment]
Workaround for this is to have multiple duplicate #particlefx components and cycle between them like sound channels so that multiple can be played per frame of a single type.

**Comment by erikangelin-king** [comment]
Ah, this was actually related to previewing/in place editing in the editor :)

**Comment by subsoap** [comment]
I see. Still, in engine, a single particlefx component can only be played once per frame which might be worth changing too!

**Comment by erikangelin-king** [comment]
Previewing multiple simultaneously in the editor works fine, engine feature request from @subsoap remains.

**Comment by britzl** [comment]
Closing this. We will not implement playing of a pfx multiple times during a frame.
