### ISSUE TITLE
Engine doesn't always report action.released?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#915]
I am polling for when an action.released occurs for certain keys. It seems like sometimes I never get an action.released event for a key. Maybe frames where there is no action the action.released events don't trigger either?

It may also be that if two keys are held and released at once the action.released for one is lost?

A workaround is to clear all input flags at the end of each update loop. Then turn on a flag when a button is held in the on_input. Then it's possible to detect when an action is no longer pressed one frame after.

**Comment by britzl** [comment]
We need a repro case for this. Closing.
