### ISSUE TITLE
Build HTML5 causes NullPointerException.

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#919]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>db5366b992bc49930510ef16b62ca21e82eed775</td></tr>
<tr><td>Build time</td><td>2017-05-23T12:06:51.661002</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=92f628f339ee40b5b1491c026d3432d8'>92f628f339ee40b5b1491c026d3432d8</a></td></tr>
<table>

**Comment by matgis-king** [comment]
Determined to be caused by unexpected files contaminating the project directory.
