### ISSUE TITLE
Save last "Code signing identity" when building bundle

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#920]
Would be great if editor2 would save  last used "Code signing identity" for a bundle.

![2017-05-23_15-19-55](https://cloud.githubusercontent.com/assets/2209596/26353966/5f5f81c6-3fcb-11e7-827e-c355c58e0fef.png)

**Comment by matgis-king** [comment]
Note: This is a regression. It should already be remembering the last selected.
