### ISSUE TITLE
Show full file path

### ISSUE THREAD

**Issue by leXorNet** [defold/editor2-issues#922]
### Expected behaviour
Hovering a tab should show full path (from project root) of the file (like in Editor1).

### Actual behaviour
No tooltip is shown.

### Steps to reproduce
Open two files from different directories with the same name and try to tell them apart :)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>0eda508c32d17e8348ddee69f03b110ae5845e6b</td></tr>
<tr><td>Build time</td><td>2017-05-23T13:13:57.948197</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.10.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by subsoap** [comment]
Related https://github.com/defold/editor2-issues/issues/815
