### ISSUE TITLE
Track selected file (in asset window)

### ISSUE THREAD

**Issue by leXorNet** [defold/editor2-issues#923]
### Expected behaviour
Option in the asset window to track/highlight the file of the currently open tab (like in Editor1).

### Actual behaviour
No such option

### Steps to reproduce
Open a file from a several folder deep path.
Close all folders in the asset view.
Forget where you found the file.
Try to find it again (its not easy) :)

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>0eda508c32d17e8348ddee69f03b110ae5845e6b</td></tr>
<tr><td>Build time</td><td>2017-05-23T13:13:57.948197</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.10.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by RagnarSvenssonKing** [comment]
Quick-win if we add the option "Select in Asset Browser" to the tab context-menu. Having the selection be synced would be a bit more work, still not too much though.

**Comment by Jerakin** [comment]
Would be helpful if this was bind to a hotkey that "frames" stuff. As in pressing F when hovering the Asset view it frames the current active/open file in it.

**Comment by ragnard-king** [comment]
We've now added a "Show In Asset Browser" command, available in context menu on resources (for example right-clicking on tab). Available in latest update.
