### ISSUE TITLE
script editor error when typing require""""

### ISSUE THREAD

**Issue by Dragosha** [defold/editor2-issues#925]
![2017-05-23_19-18-04](https://cloud.githubusercontent.com/assets/842807/26358652/9bf97aa8-3fec-11e7-8787-4289dffb0b6d.png)

### Steps to reproduce
in script editor type 'require' and double quote (")
like this: require """"

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>719697b06f89bcd6f2db1fd2553c391a063040b9</td></tr>
<tr><td>Build time</td><td>2017-05-19T15:48:47.327794</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=e59739b6af81440d8f582d6256f181db'>e59739b6af81440d8f582d6256f181db</a></td></tr>
<table>

**Comment by subsoap** [comment]
Related https://github.com/defold/editor2-issues/issues/879

**Comment by ragnard-king** [comment]
Fix merged, coming in update shortly.
