### ISSUE TITLE
An error that prevents us from pushing the modifications from Editor 2

### ISSUE THREAD

**Issue by olovn** [defold/editor2-issues#926]
**Background**
Some of us in the team would like to start to use Editor 2 now. Therefore we would like to push the modifications that editor 2 makes to the project.

However, for this to work, it must be backwards compatible, so that those who are still working with Editor 1 can still work with the project.

When I just tried to reopen the modified project in editor 1, it seems like it's backwards compatible, except for one annoying error that prevents me from pushing the changes.

**Error description**
This is what I did to get the error:

1. Open the project in Editor 2, use save all and then commit the modifications to a temporary git branch.
2. Open the project in editor 1.
3. Try to build it in editor 1.
4. Three different .gui files failed to build with this error message: _"the texture '' has not been added as a resource"_

When I looked at the modifications that were done to the .gui files I see that:
Editor 2 has changes lines like for example:
_texture: "world_ui/thank_you_filled"_
into:
_texture: "/thank_you_filled"_

So it has removed the prefix that consisted by the name of the atlas.

**Comment by RagnarSvenssonKing** [comment]
Super-blocker! :)

**Comment by matgis-king** [comment]
Note: Likely related to `texture-ids` input coming from the template owner rather than the templated Gui scene itself. This results in `texture-input` being unconnected since the selected texture is not among the `texture-ids`. When the `texture` property is evaluated, the atlas part of the string becomes empty.

**Comment by RagnarSvenssonKing** [comment]
I have done a quick check and come to the conclusion that the reason that the texture is lost is that there is no such animation/image in the specified atlas file. It is still an issue that this is wiped when saving of course. There are also other suspect things I've seen when saving so this requires more investigation.

**Comment by olovn** [comment]
Cool, thank you for the investigation! Apparently those texture entries were obsolete. I have now removed all such references and now Editor 1 can successfully build after Editor 2 has done Save All.

**Comment by RagnarSvenssonKing** [comment]
Since you have such a large project, I would like to go through all the diffs produced by editor2 to make sure there isn't something else we missed.

**Comment by olovn** [comment]
Ok, thank you! The "Save all" Commit has SHA1: 818f6ac729bd9c488f4f942bf78bd98d1a8cdfbb

**Comment by matgis-king** [comment]
With defold/defold#1641, the broken references will no longer be wiped when saving.
