### ISSUE TITLE
Make android input method in game.project a dropdown [DEFEDIT-1070]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#929]
The available options should be a dropdown so you can know what the options are without digging through release notes or manuals. It would also make sense now to make the default into HiddenInputField in editor 2, which is the sane option to use as far as I understand.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>621c78912b789692b4cd6273b857dc82247d8319</td></tr>
<tr><td>Build time</td><td>2017-05-24T11:23:16.429148</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed at some point :)
