### ISSUE TITLE
Legacy .tilegrid files do not work

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#93]
Old projects containing .tilegrid files do not work. When running, the following error shows:

INFO:DLIB: SSDP: Started on address 172.19.20.181
DEBUG:SCRIPT: LOADING planet whiteroom
ERROR:RESOURCE: Unknown resource type: tilegrid
ERROR:GAMESYS: No shapes found in collision object

Note that refactoring of these files do not work either. When renaming "level.tilegrid" to "level.tilemap" no references to the file are updated.

**Comment by sicher** [comment]
I added a "legacy.tilegrid" file to the Feature test project.

**Comment by ragnard-king** [comment]
@sicher Can you give me access to the "Feature" test project please?

**Comment by sicher** [comment]
Sure! Added ragnar.dahlen@king.com <mailto:ragnar.dahlen@king.com>. Is that right?
--
Mikael Säker
www.fablebit.com
Tel. +46 (0) 709 588 440

**Comment by ragnard-king** [comment]
Yep, thanks!

**Comment by ragnard-king** [comment]
@sicher Should be fixed now, closing.
