### ISSUE TITLE
HTML5 build includes report even if you don't mark the checkbox

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#932]
![2017-05-24 15_51_54-js-web](https://cloud.githubusercontent.com/assets/409170/26428907/eb5f640c-4098-11e7-8d47-dc105ac6db2f.png)
![2017-05-24 15_51_50-bundle application](https://cloud.githubusercontent.com/assets/409170/26428906/eb5d8e5c-4098-11e7-9087-65d20ab5bc05.png)

**Comment by AGulev** [comment]
@subsoap can't reproduce
