### ISSUE TITLE
Default editor font not fixed width / tabs / spaces do not perfectly align?

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#938]
![2017-05-26 13_10_30-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26510994/ca38aab8-4214-11e7-8134-b0a921910623.png)

**Comment by AGulev** [comment]
@subsoap 
![2018-01-08_20-42-36](https://user-images.githubusercontent.com/2209596/34683904-79afe69e-f4b4-11e7-8ab4-a24834c3cd43.jpg)
