### ISSUE TITLE
Typing on a long line while window is scrolled horizontally resets the horizontal scroll

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#939]
Before

![2017-05-26 13_12_33-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26511066/151f0a36-4215-11e7-8e6c-5e45bb1ab675.png)

After

![2017-05-26 13_12_39-defold editor 2 0 - defrs](https://cloud.githubusercontent.com/assets/409170/26511080/39242ff6-4215-11e7-859d-04fae1a63d5c.png)

Super tedious

**Comment by AGulev** [comment]
@subsoap Can't reproduce

**Comment by subsoap** [comment]
@AGulev Must have been artifact of old editor
