### ISSUE TITLE
Font file types save more default fields than Editor 1

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#94]
Here's a diff for open and immediate save all for a font file:

![screen shot 2016-09-16 at 13 59 51](https://cloud.githubusercontent.com/assets/65613/18588324/45422d16-7c26-11e6-8ed2-eee9b2ee970f.png)

Editor 1 does not alter the file at all if touched and saved.

**Comment by sicher** [comment]
[body_font.font.txt](https://github.com/defold/editor2-issues/files/479414/body_font.font.txt)

**Comment by erikangelin-king** [comment]
DEFEDIT-431
