### ISSUE TITLE
Double clicking a collection proxy in the Outline should open it [DEFEDIT-1191]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#948]
Double click list item

![2017-05-29 01_29_29-defold editor 2 0 - defold router demo](https://cloud.githubusercontent.com/assets/409170/26542313/470dbfb0-440e-11e7-84c8-59c369a5e42f.png)

Get same behavior as this

![2017-05-29 01_29_18-new issue defold_editor2-issues](https://cloud.githubusercontent.com/assets/409170/26542303/3e9baf36-440e-11e7-84a3-6c9b1238351e.png)

**Comment by subsoap** [comment]
Sorry, this should say Collection Proxy. Collections do open when double clicking, but Collection Proxies do not open the Collection they refer to. Would be nice if they did though.

**Comment by matgis-king** [comment]
You can now double-click embedded Collection Proxies and Factories to open the referenced scene.
