### ISSUE TITLE
Sign iOS App... [DEFEDIT-990]

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#949]
Bug when I try to sign ios app

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>a285bcf69ac6de9d1cab399768b74968c80cd864</td></tr>
<tr><td>Build time</td><td>2017-05-26T15:25:14.131999</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.4</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=21319c4bb66c432c9831e0594a5d4d6e'>21319c4bb66c432c9831e0594a5d4d6e</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged!
