### ISSUE TITLE
GUI files save more default fields than Editor 1

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#95]
Open and save a GUI file on Editor 2 gives the following diff:

![screen shot 2016-09-16 at 14 02 31](https://cloud.githubusercontent.com/assets/65613/18588383/801a6eee-7c26-11e6-911b-08d7b0b8416a.png)

For Editor 1, a slightly different set of additions are done:

![screen shot 2016-09-16 at 14 02 16](https://cloud.githubusercontent.com/assets/65613/18588397/91d4f0e6-7c26-11e6-8e6d-4afc09ba2c51.png)

**Comment by sicher** [comment]
[camera_fx.gui.txt](https://github.com/defold/editor2-issues/files/479413/camera_fx.gui.txt)

**Comment by erikangelin-king** [comment]
DEFEDIT-431
