### ISSUE TITLE
Dragging a library folder (such as builtins) into the root project directory makes a duplicate which breaks building/bundling and which can't be seen in the Assets panel [DEFEDIT-991]

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#950]
The duplicate has to be deleted with the OS directly.

Solution is to not allow duplication of root library folders from drag and drop?

**Comment by erikangelin-king** [comment]
https://forum.defold.com/t/builtins-folder-preventing-defold-from-bundling-solved/8755/3

**Comment by erikangelin-king** [comment]
Fix merged. You can no longer drag & drop builtins to the root folder. Neither can you create a folder named builtins, build etc or rename/move something else to certain reserved names. If you create such a folder externally, the editor will not map its contents and it will not show up in the asset browser (which only displays addressable content), so you also have to remove it externally.
