### ISSUE TITLE
Removing material tag scrolls window to top if not all fits in viewport

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#952]
### Expected behaviour
Scrolling stays where it is.

### Actual behaviour
It scrolls the material view to the top

### Steps to reproduce
Resize window so there is a scrollbar.
Remove a tag.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>a285bcf69ac6de9d1cab399768b74968c80cd864</td></tr>
<tr><td>Build time</td><td>2017-05-30T12:40:03.645753</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by AGulev** [comment]
I can't reproduce this issue in 1.2.144. Feel free to reopen in case it is still an issue.
