### ISSUE TITLE
Console not show UTF-8 texts

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#953]
### Expected behaviour
Console show UTF-8 texts
### Actual behaviour
Not show and show junk
![image](https://cloud.githubusercontent.com/assets/588556/26582329/732c0f5c-4549-11e7-9125-0ca36bde770f.png)

### Steps to reproduce
Print some not english text with UTF-8 codepage in console with print()
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.105</td></tr>
<tr><td>Defold sha</td><td>064a1afef152a7a73cc5328eef663dc46a7743f9</td></tr>
<tr><td>Build time</td><td>2017-05-24T13:45:16.973865</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by sicher** [comment]
This might be a platform thing. I get nice text on macOS:

![screen shot 2017-06-20 at 11 57 40](https://user-images.githubusercontent.com/65613/27327720-c576c920-55af-11e7-9a90-3f3427085a80.png)

**Comment by tarnumius** [comment]
May be Windows problem. On my screen was Russian text(if its important)

**Comment by erikangelin-king** [comment]
Hi @tarnumius! This should be fixed since we introduced the new text editor and console, please reopen if it's still an issue.
