### ISSUE TITLE
Particle FX file types save more default fields than Editor 1

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#97]
Editor 2 adds the following fields on open and save (Editor 1 adds none):

![screen shot 2016-09-16 at 16 05 47](https://cloud.githubusercontent.com/assets/65613/18588713/edb956ee-7c27-11e6-81f2-1ff819d1cbc4.png)

![screen shot 2016-09-16 at 16 08 00](https://cloud.githubusercontent.com/assets/65613/18588768/20a3a582-7c28-11e6-82f0-90c59e9ba0fd.png)

![screen shot 2016-09-16 at 16 08 08](https://cloud.githubusercontent.com/assets/65613/18588772/248e1e2a-7c28-11e6-9b74-a39536a33a30.png)

**Comment by sicher** [comment]
[ship_thruster_trail.particlefx.txt](https://github.com/defold/editor2-issues/files/479411/ship_thruster_trail.particlefx.txt)

[teleport_field.particlefx.txt](https://github.com/defold/editor2-issues/files/479412/teleport_field.particlefx.txt)

**Comment by erikangelin-king** [comment]
DEFEDIT-431
