### ISSUE TITLE
Generate code with tabs, not spaces [DEFEDIT-1282]

### ISSUE THREAD

**Issue by RagnarSvenssonKing** [defold/editor2-issues#971]
Number 12) here: https://forum.defold.com/t/big-list-of-small-annoyances/8798

**Comment by wyrmling** [comment]
Please let user to choose which characters and how much should be used as indents.

**Comment by matgis-king** [comment]
We now respect the type of indentation used in existing files, and the indentation can be converted from the Edit menu.
