### ISSUE TITLE
For some time gameobject property stores value from prototype but not from modified prototype

### ISSUE THREAD

**Issue by madwareru** [defold/editor2-issues#974]
### Expected behaviour
I have a collections for the game levels, it contains special spawner gameobjects which spawn some monsters if there is correct current stage. Each spawner has property:
go.property("stage_id", 1)
In the actual collections this property contains another numbers and it's used to check stage actuality
I expect this value to be actual from the very beginning of the game

Video from Editor 1. Everything is fine here
https://youtu.be/GFueg6xRMHE
### Actual behaviour
For some time after start, stage_id (as well as any other property of a game object) stores the default value. This ends at spawning every monster from the very beginning and as a result player couldn't go to the next stage (not all monsters killed yet). This represents only in Editor 2

Video of incorrect behaviour
https://youtu.be/_7LMCto1hlw
### Steps to reproduce
0. Open Editor 2
1. Create a gameobject asset
2. Add a script to this go with some go property
3. Add some logic which appears in update each 100 milisecond until some conditional will be true. In this conditional we need to check property from (2)
4. Create a collection asset and place go from (1) in it.
5. In script connected to go change property to some custom value
6. Add a collection from (4) into the main collection
7. Enjoy incorrect behaviour -- check returns not what we have expected
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>50e00fd6f61b48dd8ec4e26451aa4c233b951b2b</td></tr>
<tr><td>Build time</td><td>2017-05-31T16:11:00.937422</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by madwareru** [comment]
Here is a video of incorrect behaviour
[https://youtu.be/_7LMCto1hlw](url)

**Comment by madwareru** [comment]
And here is video from Editor 1. Everything is fine here
[https://youtu.be/GFueg6xRMHE](url)

**Comment by madwareru** [comment]
Some update: When I bundle project into executable everything is fine. The problem is only when buttons Build/Rebuild clicked

**Comment by ragnard-king** [comment]
Hi @madwareru! Thanks for the great report, have reproduced this issue and will look into a fix.

**Comment by madwareru** [comment]
thank you, @ragnard-king, waiting for it 👍

**Comment by ragnard-king** [comment]
A fix for this has been merged and is available in the latest update.
