### ISSUE TITLE
Component names have "Object" in their names in the "Add component" menu

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#976]
![screen shot 2017-06-01 at 11 42 44](https://cloud.githubusercontent.com/assets/65613/26679596/20d01aa8-46d6-11e7-8f77-2ccb6b68c108.png)

These components should have "Object" removed:

-  Camera Object
- Factory Object
- Collection Factory Object

**Comment by sicher** [comment]
https://github.com/defold/defold/pull/1609

**Comment by RagnarSvenssonKing** [comment]
Fixed!
