### ISSUE TITLE
No warning if you use the same id in gui [DEFEDIT-919]

### ISSUE THREAD

**Issue by SamuelBeijer** [defold/editor2-issues#977]
If i use the same id for things in gui editor2 will crash on start. It should give you a warning and be able to handle it.

![screen shot 2017-06-01 at 15 11 13](https://cloud.githubusercontent.com/assets/3929293/26681299/f1fea67a-46dc-11e7-8859-4f3c29e75b59.png)

**Comment by matgis-king** [comment]
Note: We should probably merge #1641 before attempting this.

**Comment by AGulev** [comment]
https://github.com/defold/editor2-issues/issues/738
