### ISSUE TITLE
Exception when buildling many times quickly in succession

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#978]
### Expected behaviour
It just works™

### Actual behaviour
Exception

### Steps to reproduce
Hold down Shortcut+B.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>0439d6baf4b2141b49d662963bc33a93fc89df14</td></tr>
<tr><td>Build time</td><td>2017-06-01T16:04:10.745299</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=35db41e4f1704cabb8788ec5a14775ba'>35db41e4f1704cabb8788ec5a14775ba</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixd!
