### ISSUE TITLE
Tileset file types save fewer default fields than Editor 1

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#98]
Open and save in Editor 2:

![screen shot 2016-09-16 at 16 12 42](https://cloud.githubusercontent.com/assets/65613/18588862/8607b760-7c28-11e6-9b3d-d24f0ca3449f.png)

Open and save in Editor 1:

![screen shot 2016-09-16 at 16 12 47](https://cloud.githubusercontent.com/assets/65613/18588878/8ffbdfa8-7c28-11e6-9c5a-d14e2b699169.png)

**Comment by sicher** [comment]
[explosion.tileset.txt](https://github.com/defold/editor2-issues/files/479410/explosion.tileset.txt)

**Comment by erikangelin-king** [comment]
DEFEDIT-431
