### ISSUE TITLE
Collision Object protobuf error [DEFEDIT-1003]

### ISSUE THREAD

**Issue by Dnisher** [defold/editor2-issues#983]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>0439d6baf4b2141b49d662963bc33a93fc89df14</td></tr>
<tr><td>Build time</td><td>2017-06-01T16:04:10.745299</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=d42c95dfd26c4fcd81d715367cc8b0d4'>d42c95dfd26c4fcd81d715367cc8b0d4</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged!

**Comment by erikangelin-king** [comment]
Fixed fix merged :)
