### ISSUE TITLE
Building when a build is already in progress produces error

### ISSUE THREAD

**Issue by Dnisher** [defold/editor2-issues#986]
### Steps to reproduce

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>a9c05fa9f10ceda7c0422fa54fcfd468a4e45930</td></tr>
<tr><td>Build time</td><td>2017-06-05T09:06:28.608604</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=adebbdcbe97a4cc9a0f7595cff5de0b8'>adebbdcbe97a4cc9a0f7595cff5de0b8</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Turned out not to be so "quick-win?" :)
