### ISSUE TITLE
Dot glitch

### ISSUE THREAD

**Issue by ThaPro** [defold/editor2-issues#989]
### Actual behaviour
error when I press "."

### Steps to reproduce

have : 
"local function (self)
end"
in your script.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>dc92d10b96eaa8c0b3e527c76fecb22186d7cd60</td></tr>
<tr><td>Build time</td><td>2017-06-07T13:28:32.440641</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=8ebbef7d9bae4e1d9e35a4032a59211b'>8ebbef7d9bae4e1d9e35a4032a59211b</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Can't reproduce, please reopen if it happens again with the new code editor.
