### ISSUE TITLE
Collection file types save fewer default fields than Editor 1

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#99]
Open and save in Editor 2 (note the removal of "scale_along_z":

![screen shot 2016-09-16 at 16 15 00](https://cloud.githubusercontent.com/assets/65613/18588947/d20dd2ca-7c28-11e6-982c-16abcd7c98c2.png)

Open and save in Editor 1:

![screen shot 2016-09-16 at 16 15 07](https://cloud.githubusercontent.com/assets/65613/18588967/e3626810-7c28-11e6-8bee-8518358ca3d7.png)

**Comment by sicher** [comment]
[checkpoint_activator.collection.txt](https://github.com/defold/editor2-issues/files/479409/checkpoint_activator.collection.txt)

**Comment by erikangelin-king** [comment]
DEFEDIT-431
