### ISSUE TITLE
Can't see size of text box in GUI

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#992]
### Expected behaviour
Changing the size of a text node should show the size of the box

### Actual behaviour
It shows the bounding box of the text content

### Steps to reproduce
Create text node
Increase size

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>128bd17492bf9836889c43012a26bfde16dc8f5e</td></tr>
<tr><td>Build time</td><td>2017-06-08T14:16:33.067702</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
See #1129

**Comment by dapetcu21** [comment]
+1 on this. My resizable text bubbles depend on being able to set the text node size in the editor. This worked well in Editor 1, but adjusting their size in Editor 2 is really painful. I sometimes end up typing `. . . . . . . . .` in the label, so that I can see where it approximately overflows.

**Comment by d954mas** [comment]
+1
