### ISSUE TITLE
Created new folder. Got crash when started typing name [BLOCKER]

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#993]
### Expected behaviour
No crash. I can type the name.

### Actual behaviour
Crash popup.

### Steps to reproduce
Create new folder
Start writing "p" or your favourite alphabetic character in the world
Get error

Restart of Defold doesn't help.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>2c1eba2a0fca3cb7e363c235d0721923337ba1ce</td></tr>
<tr><td>Build time</td><td>2017-06-09T15:53:44.894377</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=55630e337ee744bcb5aefb920a4dd81d'>55630e337ee744bcb5aefb920a4dd81d</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged.
