### ISSUE TITLE
Reset font and layer fields when move text node

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#996]
When I move node with text node - font and layer fields are reset
![font_reset](https://user-images.githubusercontent.com/2209596/27009827-b3748c32-4ea0-11e7-8f6a-a4d23f4b3ccb.gif)

**Comment by AGulev** [comment]
Same bug with box node( texture and layer fields)
![bug_textures](https://user-images.githubusercontent.com/2209596/27028967-2aa423d4-4f6f-11e7-8765-f7016e11b8d9.gif)

**Comment by AGulev** [comment]
@matgis-king @ragnard-king 
This issue really serious. Working with UI is maximum of discomfort especially with https://github.com/defold/editor2-issues/issues/717
Every hierarhy change will reset all textures. And find textures one more time is not  a simple task in big atlas

**Comment by matgis-king** [comment]
@AGulev Agreed. We have a fix coming (DEFEDIT-950) that will address both these issues and several more issues related to Gui editing. The fix is quite large and is currently undergoing code review, but it should hopefully reach you during the week.

**Comment by matgis-king** [comment]
The fix has been merged!
