### ISSUE TITLE
Hit build and got FileNotFoundException. [DEFEDIT-1033]

### ISSUE THREAD

**Issue by sicher** [defold/editor2-issues#997]
Have been running a project in the editor for several days.

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>3abf156877a3555e3ebc89dffba637a4f10ea6be</td></tr>
<tr><td>Build time</td><td>2017-06-01T10:44:40.532486</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=e6fc1ec58daf42d0aaa56f1c78e9b14a'>e6fc1ec58daf42d0aaa56f1c78e9b14a</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fix merged
