### ISSUE TITLE
Unable to bundle project, string index out of bounds [DEF-2768]

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#998]
### Expected behaviour
I should be able to bundle without errors if I can build and run without errors

### Actual behaviour
When I try to bundle for any platform I get a StringIndexOutOfBounds exception

### Steps to reproduce
Try to bundle this project: https://github.com/britzl/publicexamples/tree/master/examples/mike_dangers

I can bundle this project from Editor 1

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>9698f74fc2f7601eb1a22431052817a4a2874d35</td></tr>
<tr><td>Build time</td><td>2017-06-12T18:03:41.215630</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=99c97799dc124c05b81ff38bdc94a409'>99c97799dc124c05b81ff38bdc94a409</a></td></tr>
<table>

**Comment by erikangelin-king** [comment]
Fixed!
