### ISSUE TITLE
Check for updates menu option

### ISSUE THREAD

**Issue by Malmer** [defold/editor2-issues#999]
If you've skipped update you often want to check if there actually is an update now without restarting. Add menu option.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.107</td></tr>
<tr><td>Defold sha</td><td>408976dc89c7921e5ddae7c72109bc35dab56d19</td></tr>
<tr><td>Build time</td><td>2017-06-13T10:08:57.314238</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.5</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
We just merged an "Update Available" thingy in the status bar, is that good enough?

**Comment by Malmer** [comment]
Probably. Will test it, and if implemented the way I think it might be, close this issue.
